Repository Azure/azure-sdk-for-go, pull requests merged in 2018-07, with the labels that each got.

#2161 [AutoPR datafactory/resource-manager] Updating the default package tag for ADF to latest API
  profiles/preview/datafactory/mgmt/datafactory/models.go
  services/datafactory/mgmt/2018-06-01/datafactory/activityruns.go
  services/datafactory/mgmt/2018-06-01/datafactory/client.go
  services/datafactory/mgmt/2018-06-01/datafactory/datasets.go
  services/datafactory/mgmt/2018-06-01/datafactory/factories.go
  services/datafactory/mgmt/2018-06-01/datafactory/integrationruntimenodes.go
  services/datafactory/mgmt/2018-06-01/datafactory/integrationruntimes.go
  services/datafactory/mgmt/2018-06-01/datafactory/linkedservices.go
  services/datafactory/mgmt/2018-06-01/datafactory/models.go
  services/datafactory/mgmt/2018-06-01/datafactory/operations.go
  services/datafactory/mgmt/2018-06-01/datafactory/pipelineruns.go
  services/datafactory/mgmt/2018-06-01/datafactory/pipelines.go
  services/datafactory/mgmt/2018-06-01/datafactory/triggerruns.go
  services/datafactory/mgmt/2018-06-01/datafactory/triggers.go
  services/datafactory/mgmt/2018-06-01/datafactory/version.go
Labels: RestPRMerged, review

#2150 [AutoPR applicationinsights/resource-manager] Java tags1
  profiles/latest/appinsights/mgmt/insights/models.go
  profiles/preview/appinsights/mgmt/insights/models.go
  services/appinsights/mgmt/2015-05-01/insights/analyticsitems.go
  services/appinsights/mgmt/2015-05-01/insights/annotations.go
  services/appinsights/mgmt/2015-05-01/insights/favorite.go
  services/appinsights/mgmt/2015-05-01/insights/favorites.go
  services/appinsights/mgmt/2015-05-01/insights/models.go
  services/appinsights/mgmt/2015-05-01/insights/workbook.go
  services/appinsights/mgmt/2015-05-01/insights/workbooks.go
  services/appinsights/mgmt/2015-05-01/insights/workitemconfigurations.go
Labels: RestPRMerged, review

#2166 [AutoPR] applicationinsights/resource-manager
  profiles/latest/appinsights/mgmt/insights/models.go
  profiles/preview/appinsights/mgmt/insights/models.go
  services/appinsights/mgmt/2015-05-01/insights/analyticsitems.go
  services/appinsights/mgmt/2015-05-01/insights/annotations.go
  services/appinsights/mgmt/2015-05-01/insights/favorite.go
  services/appinsights/mgmt/2015-05-01/insights/favorites.go
  services/appinsights/mgmt/2015-05-01/insights/models.go
  services/appinsights/mgmt/2015-05-01/insights/workbook.go
  services/appinsights/mgmt/2015-05-01/insights/workbooks.go
  services/appinsights/mgmt/2015-05-01/insights/workitemconfigurations.go
Labels: ServicePR, review

#2160 [AutoPR] batchai/resource-manager
  profiles/preview/batchai/mgmt/batchai/models.go
  services/batchai/mgmt/2018-05-01/batchai/models.go
Labels: ServicePR, review

#2156 [AutoPR] advisor/resource-manager
  profiles/latest/advisor/mgmt/advisor/models.go
  profiles/preview/advisor/mgmt/advisor/models.go
  services/advisor/mgmt/2017-04-19/advisor/models.go
  services/advisor/mgmt/2017-04-19/advisor/recommendations.go
Labels: ServicePR, review

#2163 [AutoPR cognitiveservices/data-plane/ComputerVision] Update ComputerVision API
  profiles/preview/cognitiveservices/computervision/models.go
  services/cognitiveservices/v2.0/computervision/models.go
Labels: RestPRMerged, review

#2185 [AutoPR postgresql/resource-manager] Add support for PG 10
  profiles/latest/postgresql/mgmt/postgresql/models.go
  profiles/preview/postgresql/mgmt/postgresql/models.go
  services/postgresql/mgmt/2017-12-01/postgresql/models.go
Labels: RestPRMerged, review

#2093 [AutoPR botservice/resource-manager] misc fixes to oauth related api's on botservice swagger
  services/preview/botservice/mgmt/2017-12-01/botservices/botconnection.go
  services/preview/botservice/mgmt/2017-12-01/botservices/models.go
Labels: RestPRMerged, review

#2173 [AutoPR] containerregistry/resource-manager
  profiles/latest/containerregistry/mgmt/containerregistry/models.go
  profiles/preview/containerregistry/mgmt/containerregistry/models.go
  profiles/preview/preview/containerregistry/mgmt/containerregistry/models.go
  services/containerregistry/mgmt/2017-10-01/containerregistry/models.go
  services/containerregistry/mgmt/2017-10-01/containerregistry/registries.go
  services/preview/containerregistry/mgmt/2018-02-01/containerregistry/models.go
  services/preview/containerregistry/mgmt/2018-02-01/containerregistry/registries.go
Labels: ServicePR, review

#2186 [AutoPR] postgresql/resource-manager
  profiles/latest/postgresql/mgmt/postgresql/models.go
  profiles/preview/postgresql/mgmt/postgresql/models.go
  services/postgresql/mgmt/2017-12-01/postgresql/models.go
Labels: ServicePR, review

#2141 [AutoPR batch/data-plane] Update documentation of possible errors and size limits for Batch
  services/batch/2017-05-01.5.0/batch/account.go
  services/batch/2017-05-01.5.0/batch/application.go
  services/batch/2017-05-01.5.0/batch/certificate.go
  services/batch/2017-05-01.5.0/batch/computenode.go
  services/batch/2017-05-01.5.0/batch/file.go
  services/batch/2017-05-01.5.0/batch/job.go
  services/batch/2017-05-01.5.0/batch/jobschedule.go
  services/batch/2017-05-01.5.0/batch/pool.go
  services/batch/2017-05-01.5.0/batch/task.go
  services/batch/2018-03-01.6.1/batch/account.go
  services/batch/2018-03-01.6.1/batch/application.go
  services/batch/2018-03-01.6.1/batch/certificate.go
  services/batch/2018-03-01.6.1/batch/computenode.go
  services/batch/2018-03-01.6.1/batch/file.go
  services/batch/2018-03-01.6.1/batch/job.go
  services/batch/2018-03-01.6.1/batch/jobschedule.go
  services/batch/2018-03-01.6.1/batch/models.go
  services/batch/2018-03-01.6.1/batch/pool.go
  services/batch/2018-03-01.6.1/batch/task.go
Labels: RestPRMerged, review

#2190 [AutoPR cognitiveservices/data-plane/CustomVision/Training] Custom vision 2.1 updates
  profiles/preview/cognitiveservices/customvision/training/models.go
  services/cognitiveservices/v2.1/customvision/training/client.go
  services/cognitiveservices/v2.1/customvision/training/models.go
  services/cognitiveservices/v2.1/customvision/training/version.go
Labels: RestPRMerged, review

#2196 [AutoPR] cognitiveservices/data-plane/CustomVision/Training
  profiles/preview/cognitiveservices/customvision/training/models.go
  services/cognitiveservices/v2.1/customvision/training/client.go
  services/cognitiveservices/v2.1/customvision/training/models.go
  services/cognitiveservices/v2.1/customvision/training/version.go
Labels: ServicePR, review

#2095 [AutoPR resources/resource-manager] Add userAssignedIdentities
  profiles/preview/resources/mgmt/resources/models.go
  services/resources/mgmt/2018-05-01/resources/models.go
Labels: RestPRMerged, review

#2167 [AutoPR datafactory/resource-manager] [ADF v2]Add integration runtime sharing feature.
  profiles/preview/datafactory/mgmt/datafactory/models.go
  services/datafactory/mgmt/2018-06-01/datafactory/integrationruntimes.go
  services/datafactory/mgmt/2018-06-01/datafactory/models.go
Labels: RestPRMerged, review

#2205 [AutoPR search/resource-manager] Azure Search: Add resource identity (MSI) support
  profiles/latest/search/mgmt/search/models.go
  profiles/preview/search/mgmt/search/models.go
  services/search/mgmt/2015-08-19/search/models.go
Labels: RestPRMerged, review

#2209 [AutoPR datafactory/resource-manager] Remove sharedWithFactories property from SelfHostedIntegrationRuntime…
  services/datafactory/mgmt/2018-06-01/datafactory/models.go
Labels: RestPRMerged, review

#2208 [AutoPR web/resource-manager] Add directive to web apps for Java code gen
  services/web/mgmt/2016-09-01/web/apps.go
  services/web/mgmt/2016-09-01/web/appservicecertificateorders.go
  services/web/mgmt/2018-02-01/web/apps.go
  services/web/mgmt/2018-02-01/web/appservicecertificateorders.go
  services/web/mgmt/2018-02-01/web/appserviceenvironments.go
Labels: RestPRMerged, review

#2210 [AutoPR datafactory/resource-manager] [Datafactory] DatabricksSparkJarActivity, DatabricksSparkPythonActivity and other D…
  profiles/preview/datafactory/mgmt/datafactory/models.go
  services/datafactory/mgmt/2018-06-01/datafactory/models.go
Labels: RestPRMerged, review

#2219 [AutoPR automation/resource-manager] Add x-ms-parameter-location property
  services/preview/automation/mgmt/2018-01-preview/automation/nodecountinformation.go
Labels: RestPRMerged, review

#2202 [AutoPR] resources/resource-manager
  profiles/preview/resources/mgmt/resources/models.go
  services/resources/mgmt/2018-05-01/resources/models.go
Labels: ServicePR, review

#2206 [AutoPR] search/resource-manager
  profiles/latest/search/mgmt/search/models.go
  profiles/preview/search/mgmt/search/models.go
  services/search/mgmt/2015-08-19/search/models.go
Labels: ServicePR, review

#2218 [AutoPR] hdinsight/resource-manager
  services/preview/hdinsight/mgmt/2015-03-01-preview/hdinsight/models.go
  services/preview/hdinsight/mgmt/2018-06-01-preview/hdinsight/models.go
Labels: ServicePR, review

#2127 [AutoPR migrate/resource-manager] Vkotha master
  profiles/preview/migrate/mgmt/migrate/models.go
  services/migrate/mgmt/2018-02-02/migrate/assessedmachines.go
  services/migrate/mgmt/2018-02-02/migrate/assessmentoptions.go
  services/migrate/mgmt/2018-02-02/migrate/assessments.go
  services/migrate/mgmt/2018-02-02/migrate/groups.go
  services/migrate/mgmt/2018-02-02/migrate/machines.go
  services/migrate/mgmt/2018-02-02/migrate/models.go
  services/migrate/mgmt/2018-02-02/migrate/projects.go
Labels: RestPRMerged, review

#2189 [AutoPR consumption/resource-manager] Adding new properties to Consumption Usage Details
  profiles/preview/consumption/mgmt/consumption/models.go
  services/consumption/mgmt/2018-06-30/consumption/balances.go
  services/consumption/mgmt/2018-06-30/consumption/budgets.go
  services/consumption/mgmt/2018-06-30/consumption/client.go
  services/consumption/mgmt/2018-06-30/consumption/costtags.go
  services/consumption/mgmt/2018-06-30/consumption/forecasts.go
  services/consumption/mgmt/2018-06-30/consumption/marketplaces.go
  services/consumption/mgmt/2018-06-30/consumption/models.go
  services/consumption/mgmt/2018-06-30/consumption/operations.go
  services/consumption/mgmt/2018-06-30/consumption/pricesheet.go
  services/consumption/mgmt/2018-06-30/consumption/reservationrecommendations.go
  services/consumption/mgmt/2018-06-30/consumption/reservationsdetails.go
  services/consumption/mgmt/2018-06-30/consumption/reservationssummaries.go
  services/consumption/mgmt/2018-06-30/consumption/tags.go
  services/consumption/mgmt/2018-06-30/consumption/usagedetails.go
  services/consumption/mgmt/2018-06-30/consumption/version.go
Labels: RestPRMerged, review

#2224 [AutoPR compute/resource-manager] Add missing ScaleSet properties
  services/compute/mgmt/2018-06-01/compute/models.go
Labels: RestPRMerged, review

#2220 [AutoPR] automation/resource-manager
  profiles/preview/preview/automation/mgmt/automation/models.go
  services/automation/mgmt/2015-10-31/automation/models.go
  services/automation/mgmt/2015-10-31/automation/runbook.go
  services/automation/mgmt/2015-10-31/automation/runbookdraft.go
  services/preview/automation/mgmt/2017-05-15-preview/automation/job.go
  services/preview/automation/mgmt/2017-05-15-preview/automation/models.go
  services/preview/automation/mgmt/2017-05-15-preview/automation/runbook.go
  services/preview/automation/mgmt/2017-05-15-preview/automation/runbookdraft.go
  services/preview/automation/mgmt/2018-01-preview/automation/job.go
  services/preview/automation/mgmt/2018-01-preview/automation/models.go
  services/preview/automation/mgmt/2018-01-preview/automation/runbook.go
  services/preview/automation/mgmt/2018-01-preview/automation/runbookdraft.go
Labels: ServicePR, review

#2226 [AutoPR] consumption/resource-manager
  profiles/preview/consumption/mgmt/consumption/models.go
  services/consumption/mgmt/2018-06-30/consumption/balances.go
  services/consumption/mgmt/2018-06-30/consumption/budgets.go
  services/consumption/mgmt/2018-06-30/consumption/client.go
  services/consumption/mgmt/2018-06-30/consumption/costtags.go
  services/consumption/mgmt/2018-06-30/consumption/forecasts.go
  services/consumption/mgmt/2018-06-30/consumption/marketplaces.go
  services/consumption/mgmt/2018-06-30/consumption/models.go
  services/consumption/mgmt/2018-06-30/consumption/operations.go
  services/consumption/mgmt/2018-06-30/consumption/pricesheet.go
  services/consumption/mgmt/2018-06-30/consumption/reservationrecommendations.go
  services/consumption/mgmt/2018-06-30/consumption/reservationsdetails.go
  services/consumption/mgmt/2018-06-30/consumption/reservationssummaries.go
  services/consumption/mgmt/2018-06-30/consumption/tags.go
  services/consumption/mgmt/2018-06-30/consumption/usagedetails.go
  services/consumption/mgmt/2018-06-30/consumption/version.go
Labels: ServicePR, review

#2229 [AutoPR] compute/resource-manager
  services/compute/mgmt/2018-06-01/compute/models.go
Labels: ServicePR, review

#2225 [AutoPR] migrate/resource-manager
  profiles/preview/migrate/mgmt/migrate/models.go
  services/migrate/mgmt/2018-02-02/migrate/assessedmachines.go
  services/migrate/mgmt/2018-02-02/migrate/assessmentoptions.go
  services/migrate/mgmt/2018-02-02/migrate/assessments.go
  services/migrate/mgmt/2018-02-02/migrate/groups.go
  services/migrate/mgmt/2018-02-02/migrate/machines.go
  services/migrate/mgmt/2018-02-02/migrate/models.go
  services/migrate/mgmt/2018-02-02/migrate/projects.go
Labels: ServicePR, review

#2145 [AutoPR cost-management/resource-manager] add README file for cost management
  profiles/preview/costmanagement/mgmt/costmanagement/models.go
  services/costmanagement/mgmt/2018-05-31/costmanagement/billingaccountdimensions.go
  services/costmanagement/mgmt/2018-05-31/costmanagement/client.go
  services/costmanagement/mgmt/2018-05-31/costmanagement/models.go
  services/costmanagement/mgmt/2018-05-31/costmanagement/reportconfig.go
  services/costmanagement/mgmt/2018-05-31/costmanagement/resourcegroupdimensions.go
  services/costmanagement/mgmt/2018-05-31/costmanagement/subscriptiondimensions.go
  services/costmanagement/mgmt/2018-05-31/costmanagement/version.go
Labels: RestPRMerged, review

#2197 [AutoPR managementgroups/resource-manager] Updating 2018-03-01-preview to include a few extra fields and parameters
  services/preview/resources/mgmt/2018-03-01-preview/management/models.go
Labels: RestPRMerged, review

#2240 [AutoPR apimanagement/resource-manager] Add revision and Version Description to Contract
  services/preview/apimanagement/mgmt/2018-01-01/apimanagement/models.go
  services/preview/apimanagement/mgmt/2018-06-01-preview/apimanagement/models.go
Labels: RestPRMerged, review

#2235 [AutoPR automation/resource-manager] Changing schema from string to file
  services/automation/mgmt/2015-10-31/automation/runbookdraft.go
  services/preview/automation/mgmt/2017-05-15-preview/automation/runbookdraft.go
  services/preview/automation/mgmt/2018-01-preview/automation/nodecountinformation.go
  services/preview/automation/mgmt/2018-01-preview/automation/runbookdraft.go
Labels: RestPRMerged, review

#2223 [AutoPR recoveryservicesbackup/resource-manager] Added BackupValidateOperation API
  profiles/latest/recoveryservices/mgmt/backup/models.go
  profiles/preview/recoveryservices/mgmt/backup/models.go
  services/recoveryservices/mgmt/2016-12-01/backup/itemlevelrecoveryconnections.go
  services/recoveryservices/mgmt/2016-12-01/backup/models.go
  services/recoveryservices/mgmt/2016-12-01/backup/operationresults.go
  services/recoveryservices/mgmt/2016-12-01/backup/operationstatuses.go
  services/recoveryservices/mgmt/2016-12-01/backup/protecteditemoperationstatuses.go
  services/recoveryservices/mgmt/2016-12-01/backup/protecteditems.go
  services/recoveryservices/mgmt/2016-12-01/backup/protectioncontainers.go
  services/recoveryservices/mgmt/2016-12-01/backup/protectionpolicies.go
  services/recoveryservices/mgmt/2016-12-01/backup/protectionpolicyoperationstatuses.go
  services/recoveryservices/mgmt/2016-12-01/backup/recoverypoints.go
  services/recoveryservices/mgmt/2016-12-01/backup/restores.go
  services/recoveryservices/mgmt/2016-12-01/backup/workloaditems.go
  services/recoveryservices/mgmt/2017-07-01/backup/exportjobsoperationresults.go
  services/recoveryservices/mgmt/2017-07-01/backup/itemlevelrecoveryconnections.go
  services/recoveryservices/mgmt/2017-07-01/backup/models.go
  services/recoveryservices/mgmt/2017-07-01/backup/operation.go
  services/recoveryservices/mgmt/2017-07-01/backup/operationresults.go
  services/recoveryservices/mgmt/2017-07-01/backup/operationstatuses.go
  services/recoveryservices/mgmt/2017-07-01/backup/protecteditemoperationstatuses.go
  services/recoveryservices/mgmt/2017-07-01/backup/protecteditemsgroup.go
  services/recoveryservices/mgmt/2017-07-01/backup/protectioncontainers.go
  services/recoveryservices/mgmt/2017-07-01/backup/protectionpolicies.go
  services/recoveryservices/mgmt/2017-07-01/backup/protectionpolicyoperationstatuses.go
  services/recoveryservices/mgmt/2017-07-01/backup/recoverypoints.go
  services/recoveryservices/mgmt/2017-07-01/backup/restores.go
  services/recoveryservices/mgmt/2017-07-01/backup/workloaditems.go
Labels: RestPRMerged, review

#2231 [AutoPR] cost-management/resource-manager
  profiles/preview/costmanagement/mgmt/costmanagement/models.go
  services/costmanagement/mgmt/2018-05-31/costmanagement/billingaccountdimensions.go
  services/costmanagement/mgmt/2018-05-31/costmanagement/client.go
  services/costmanagement/mgmt/2018-05-31/costmanagement/models.go
  services/costmanagement/mgmt/2018-05-31/costmanagement/reportconfig.go
  services/costmanagement/mgmt/2018-05-31/costmanagement/resourcegroupdimensions.go
  services/costmanagement/mgmt/2018-05-31/costmanagement/subscriptiondimensions.go
  services/costmanagement/mgmt/2018-05-31/costmanagement/version.go
Labels: ServicePR, review

#2236 [AutoPR] managementgroups/resource-manager
  services/preview/resources/mgmt/2018-03-01-preview/management/models.go
Labels: ServicePR, review

#2242 [AutoPR] apimanagement/resource-manager
  services/preview/apimanagement/mgmt/2018-01-01/apimanagement/models.go
  services/preview/apimanagement/mgmt/2018-06-01-preview/apimanagement/models.go
Labels: ServicePR, review

#2245 [AutoPR] hdinsight/resource-manager
  profiles/preview/preview/hdinsight/mgmt/hdinsight/models.go
  services/preview/hdinsight/mgmt/2018-06-01-preview/hdinsight/configurations.go
  services/preview/hdinsight/mgmt/2018-06-01-preview/hdinsight/models.go
Labels: ServicePR, review

#2250 [AutoPR] recoveryservicesbackup/resource-manager
  profiles/latest/recoveryservices/mgmt/backup/models.go
  profiles/preview/recoveryservices/mgmt/backup/models.go
  services/recoveryservices/mgmt/2016-12-01/backup/itemlevelrecoveryconnections.go
  services/recoveryservices/mgmt/2016-12-01/backup/models.go
  services/recoveryservices/mgmt/2016-12-01/backup/operationresults.go
  services/recoveryservices/mgmt/2016-12-01/backup/operationstatuses.go
  services/recoveryservices/mgmt/2016-12-01/backup/protecteditemoperationstatuses.go
  services/recoveryservices/mgmt/2016-12-01/backup/protecteditems.go
  services/recoveryservices/mgmt/2016-12-01/backup/protectioncontainers.go
  services/recoveryservices/mgmt/2016-12-01/backup/protectionpolicies.go
  services/recoveryservices/mgmt/2016-12-01/backup/protectionpolicyoperationstatuses.go
  services/recoveryservices/mgmt/2016-12-01/backup/recoverypoints.go
  services/recoveryservices/mgmt/2016-12-01/backup/restores.go
  services/recoveryservices/mgmt/2016-12-01/backup/workloaditems.go
  services/recoveryservices/mgmt/2017-07-01/backup/exportjobsoperationresults.go
  services/recoveryservices/mgmt/2017-07-01/backup/itemlevelrecoveryconnections.go
  services/recoveryservices/mgmt/2017-07-01/backup/models.go
  services/recoveryservices/mgmt/2017-07-01/backup/operation.go
  services/recoveryservices/mgmt/2017-07-01/backup/operationresults.go
  services/recoveryservices/mgmt/2017-07-01/backup/operationstatuses.go
  services/recoveryservices/mgmt/2017-07-01/backup/protecteditemoperationstatuses.go
  services/recoveryservices/mgmt/2017-07-01/backup/protecteditemsgroup.go
  services/recoveryservices/mgmt/2017-07-01/backup/protectioncontainers.go
  services/recoveryservices/mgmt/2017-07-01/backup/protectionpolicies.go
  services/recoveryservices/mgmt/2017-07-01/backup/protectionpolicyoperationstatuses.go
  services/recoveryservices/mgmt/2017-07-01/backup/recoverypoints.go
  services/recoveryservices/mgmt/2017-07-01/backup/restores.go
  services/recoveryservices/mgmt/2017-07-01/backup/workloaditems.go
Labels: ServicePR, review

#2251 [AutoPR servicefabricmesh/resource-manager] BugFix: defaultSinkRefs is an array of string
  profiles/preview/preview/servicefabricmesh/mgmt/servicefabricmesh/models.go
  services/preview/servicefabricmesh/mgmt/2018-07-01-preview/servicefabricmesh/application.go
  services/preview/servicefabricmesh/mgmt/2018-07-01-preview/servicefabricmesh/client.go
  services/preview/servicefabricmesh/mgmt/2018-07-01-preview/servicefabricmesh/codepackage.go
  services/preview/servicefabricmesh/mgmt/2018-07-01-preview/servicefabricmesh/models.go
  services/preview/servicefabricmesh/mgmt/2018-07-01-preview/servicefabricmesh/network.go
  services/preview/servicefabricmesh/mgmt/2018-07-01-preview/servicefabricmesh/operations.go
  services/preview/servicefabricmesh/mgmt/2018-07-01-preview/servicefabricmesh/replica.go
  services/preview/servicefabricmesh/mgmt/2018-07-01-preview/servicefabricmesh/service.go
  services/preview/servicefabricmesh/mgmt/2018-07-01-preview/servicefabricmesh/version.go
  services/preview/servicefabricmesh/mgmt/2018-07-01-preview/servicefabricmesh/volume.go
Labels: RestPRMerged, review

#2252 [AutoPR] servicefabricmesh/resource-manager
  profiles/preview/preview/servicefabricmesh/mgmt/servicefabricmesh/models.go
  services/preview/servicefabricmesh/mgmt/2018-07-01-preview/servicefabricmesh/application.go
  services/preview/servicefabricmesh/mgmt/2018-07-01-preview/servicefabricmesh/client.go
  services/preview/servicefabricmesh/mgmt/2018-07-01-preview/servicefabricmesh/codepackage.go
  services/preview/servicefabricmesh/mgmt/2018-07-01-preview/servicefabricmesh/models.go
  services/preview/servicefabricmesh/mgmt/2018-07-01-preview/servicefabricmesh/network.go
  services/preview/servicefabricmesh/mgmt/2018-07-01-preview/servicefabricmesh/operations.go
  services/preview/servicefabricmesh/mgmt/2018-07-01-preview/servicefabricmesh/replica.go
  services/preview/servicefabricmesh/mgmt/2018-07-01-preview/servicefabricmesh/service.go
  services/preview/servicefabricmesh/mgmt/2018-07-01-preview/servicefabricmesh/version.go
  services/preview/servicefabricmesh/mgmt/2018-07-01-preview/servicefabricmesh/volume.go
Labels: ServicePR, review

#2241 [AutoPR alertsmanagement/resource-manager] AlertsManagement RP Public preview Swagger Spec
  profiles/preview/alertsmanagement/mgmt/alertsmanagement/models.go
  services/alertsmanagement/mgmt/2018-05-05-preview/alertsmanagement/alerts.go
  services/alertsmanagement/mgmt/2018-05-05-preview/alertsmanagement/client.go
  services/alertsmanagement/mgmt/2018-05-05-preview/alertsmanagement/models.go
  services/alertsmanagement/mgmt/2018-05-05-preview/alertsmanagement/operations.go
  services/alertsmanagement/mgmt/2018-05-05-preview/alertsmanagement/smartgroups.go
  services/alertsmanagement/mgmt/2018-05-05-preview/alertsmanagement/version.go
Labels: RestPRMerged, review

#2255 [AutoPR] compute/resource-manager
  profiles/preview/compute/mgmt/compute/models.go
  services/compute/mgmt/2018-06-01/compute/models.go
Labels: ServicePR, review

#2261 [AutoPR containerservices/resource-manager] [AKS] added PATCH endpoint for updating tags
  profiles/preview/containerservice/mgmt/containerservice/models.go
  services/containerservice/mgmt/2018-03-31/containerservice/managedclusters.go
  services/containerservice/mgmt/2018-03-31/containerservice/models.go
Labels: RestPRMerged, review

#2262 [AutoPR] containerservices/resource-manager
  profiles/preview/containerservice/mgmt/containerservice/models.go
  services/containerservice/mgmt/2018-03-31/containerservice/managedclusters.go
  services/containerservice/mgmt/2018-03-31/containerservice/models.go
Labels: ServicePR, review

#2263 [AutoPR web/resource-manager] [Do Not Merge] Add API for adding external storage account configurations to a web app
  profiles/preview/web/mgmt/web/models.go
  services/web/mgmt/2018-02-01/web/apps.go
  services/web/mgmt/2018-02-01/web/models.go
Labels: RestPRMerged, review

#2267 [AutoPR sql/resource-manager] Bump sql management Node.js package version to 4.1.0
  services/preview/sql/mgmt/2017-03-01-preview/sql/models.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/sensitivitylabels.go
Labels: RestPRMerged, review

#2270 [AutoPR alertsmanagement/resource-manager] move Go package alertsmanagement under preview directory
  profiles/preview/preview/alertsmanagement/mgmt/alertsmanagement/models.go
  services/preview/alertsmanagement/mgmt/2018-05-05-preview/alertsmanagement/alerts.go
  services/preview/alertsmanagement/mgmt/2018-05-05-preview/alertsmanagement/client.go
  services/preview/alertsmanagement/mgmt/2018-05-05-preview/alertsmanagement/models.go
  services/preview/alertsmanagement/mgmt/2018-05-05-preview/alertsmanagement/operations.go
  services/preview/alertsmanagement/mgmt/2018-05-05-preview/alertsmanagement/smartgroups.go
  services/preview/alertsmanagement/mgmt/2018-05-05-preview/alertsmanagement/version.go
Labels: RestPRMerged, review

#2272 [AutoPR] alertsmanagement/resource-manager
  profiles/preview/preview/alertsmanagement/mgmt/alertsmanagement/models.go
  services/preview/alertsmanagement/mgmt/2018-05-05-preview/alertsmanagement/alerts.go
  services/preview/alertsmanagement/mgmt/2018-05-05-preview/alertsmanagement/client.go
  services/preview/alertsmanagement/mgmt/2018-05-05-preview/alertsmanagement/models.go
  services/preview/alertsmanagement/mgmt/2018-05-05-preview/alertsmanagement/operations.go
  services/preview/alertsmanagement/mgmt/2018-05-05-preview/alertsmanagement/smartgroups.go
  services/preview/alertsmanagement/mgmt/2018-05-05-preview/alertsmanagement/version.go
Labels: ServicePR, review

#2273 [AutoPR compute/resource-manager] Fixing instance view object definition in VMSSVMProperties
  services/compute/mgmt/2015-06-15/compute/models.go
  services/compute/mgmt/2016-03-30/compute/models.go
  services/compute/mgmt/2017-03-30/compute/models.go
  services/compute/mgmt/2018-06-01/compute/models.go
  services/preview/compute/mgmt/2016-04-30-preview/compute/models.go
Labels: RestPRMerged, review

#2278 [AutoPR monitor/resource-manager] updated description of recurrent frequency
  profiles/preview/preview/monitor/mgmt/insights/models.go
  services/preview/monitor/mgmt/2017-05-01-preview/insights/models.go
  services/preview/monitor/mgmt/2018-03-01/insights/models.go
Labels: RestPRMerged, review

#2257 [AutoPR cognitiveservices/data-plane/ComputerVision] Enable Computer Vision Client to customize endpoint.
  profiles/preview/cognitiveservices/computervision/models.go
  services/cognitiveservices/v2.0/computervision/client.go
  services/cognitiveservices/v2.0/computervision/models.go
Labels: RestPRMerged, review

#2274 [AutoPR] compute/resource-manager
  services/compute/mgmt/2015-06-15/compute/models.go
  services/compute/mgmt/2016-03-30/compute/models.go
  services/compute/mgmt/2017-03-30/compute/models.go
  services/compute/mgmt/2018-06-01/compute/models.go
  services/preview/compute/mgmt/2016-04-30-preview/compute/models.go
Labels: ServicePR, review

#2279 [AutoPR] monitor/resource-manager
  profiles/preview/preview/monitor/mgmt/insights/models.go
  services/preview/monitor/mgmt/2017-05-01-preview/insights/models.go
  services/preview/monitor/mgmt/2018-03-01/insights/models.go
Labels: ServicePR, review

#2282 [AutoPR] cognitiveservices/data-plane/ComputerVision
  profiles/preview/cognitiveservices/computervision/models.go
  services/cognitiveservices/v2.0/computervision/client.go
  services/cognitiveservices/v2.0/computervision/models.go
Labels: ServicePR, review

#2275 [AutoPR eventgrid/data-plane] Add connection state events and update LifeCycleEvents
  profiles/latest/eventgrid/eventgrid/models.go
  profiles/preview/eventgrid/eventgrid/models.go
  services/eventgrid/2018-01-01/eventgrid/models.go
Labels: RestPRMerged, review

#2283 [AutoPR] eventgrid/data-plane
  profiles/latest/eventgrid/eventgrid/models.go
  profiles/preview/eventgrid/eventgrid/models.go
  services/eventgrid/2018-01-01/eventgrid/models.go
Labels: ServicePR, review

#2287 update dependencies
  Gopkg.lock
  Gopkg.toml
Labels: review

#2277 [AutoPR iotcentral/resource-manager] Add iotcentral version 2018-09-01
  profiles/preview/preview/iotcentral/mgmt/iotcentral/models.go
  services/preview/iotcentral/mgmt/2018-09-01/iotcentral/apps.go
  services/preview/iotcentral/mgmt/2018-09-01/iotcentral/client.go
  services/preview/iotcentral/mgmt/2018-09-01/iotcentral/models.go
  services/preview/iotcentral/mgmt/2018-09-01/iotcentral/operations.go
  services/preview/iotcentral/mgmt/2018-09-01/iotcentral/version.go
Labels: RestPRMerged, review

#2289 [AutoPR] iotcentral/resource-manager
  profiles/preview/preview/iotcentral/mgmt/iotcentral/models.go
  services/preview/iotcentral/mgmt/2018-09-01/iotcentral/apps.go
  services/preview/iotcentral/mgmt/2018-09-01/iotcentral/client.go
  services/preview/iotcentral/mgmt/2018-09-01/iotcentral/models.go
  services/preview/iotcentral/mgmt/2018-09-01/iotcentral/operations.go
  services/preview/iotcentral/mgmt/2018-09-01/iotcentral/version.go
Labels: ServicePR, review

#2291 [AutoPR security/resource-manager] Security Center - Removing properties to allow auto code generation
  profiles/preview/preview/security/mgmt/security/models.go
  services/preview/security/mgmt/2017-08-01-preview/security/alerts.go
  services/preview/security/mgmt/2017-08-01-preview/security/autoprovisioningsettings.go
  services/preview/security/mgmt/2017-08-01-preview/security/client.go
  services/preview/security/mgmt/2017-08-01-preview/security/compliances.go
  services/preview/security/mgmt/2017-08-01-preview/security/contacts.go
  services/preview/security/mgmt/2017-08-01-preview/security/discoveredsecuritysolutions.go
  services/preview/security/mgmt/2017-08-01-preview/security/externalsecuritysolutions.go
  services/preview/security/mgmt/2017-08-01-preview/security/jitnetworkaccesspolicies.go
  services/preview/security/mgmt/2017-08-01-preview/security/locations.go
  services/preview/security/mgmt/2017-08-01-preview/security/models.go
  services/preview/security/mgmt/2017-08-01-preview/security/operations.go
  services/preview/security/mgmt/2017-08-01-preview/security/pricings.go
  services/preview/security/mgmt/2017-08-01-preview/security/tasks.go
  services/preview/security/mgmt/2017-08-01-preview/security/version.go
  services/preview/security/mgmt/2017-08-01-preview/security/workspacesettings.go
Labels: RestPRMerged, review

#2290 [AutoPR datafactory/resource-manager] Updating User Properties
  profiles/preview/datafactory/mgmt/datafactory/models.go
  services/datafactory/mgmt/2018-06-01/datafactory/integrationruntimes.go
  services/datafactory/mgmt/2018-06-01/datafactory/models.go
Labels: RestPRMerged, review

#2305 Update generator version to be used by Swagger To SDK automation
  swagger_to_sdk_config.json
Labels: review

#2307 [AutoPR dns/resource-manager] Use common arm definitions for dns
  profiles/latest/dns/mgmt/dns/models.go
  profiles/preview/preview/dns/mgmt/dns/models.go
  services/dns/mgmt/2016-04-01/dns/models.go
  services/dns/mgmt/2016-04-01/dns/recordsets.go
  services/dns/mgmt/2016-04-01/dns/zones.go
  services/dns/mgmt/2017-09-01/dns/models.go
  services/dns/mgmt/2017-09-01/dns/recordsets.go
  services/dns/mgmt/2017-09-01/dns/zones.go
  services/dns/mgmt/2017-10-01/dns/models.go
  services/dns/mgmt/2017-10-01/dns/recordsets.go
  services/dns/mgmt/2017-10-01/dns/zones.go
  services/preview/dns/mgmt/2015-05-04-preview/dns/models.go
  services/preview/dns/mgmt/2015-05-04-preview/dns/recordsets.go
  services/preview/dns/mgmt/2015-05-04-preview/dns/zones.go
  services/preview/dns/mgmt/2018-03-01-preview/dns/models.go
  services/preview/dns/mgmt/2018-03-01-preview/dns/recordsets.go
  services/preview/dns/mgmt/2018-03-01-preview/dns/zones.go
Labels: RestPRMerged, review

#2313 [AutoPR] dns/resource-manager
  profiles/latest/dns/mgmt/dns/models.go
  profiles/preview/preview/dns/mgmt/dns/models.go
  services/dns/mgmt/2016-04-01/dns/models.go
  services/dns/mgmt/2016-04-01/dns/recordsets.go
  services/dns/mgmt/2016-04-01/dns/zones.go
  services/dns/mgmt/2017-09-01/dns/models.go
  services/dns/mgmt/2017-09-01/dns/recordsets.go
  services/dns/mgmt/2017-09-01/dns/zones.go
  services/dns/mgmt/2017-10-01/dns/models.go
  services/dns/mgmt/2017-10-01/dns/recordsets.go
  services/dns/mgmt/2017-10-01/dns/zones.go
  services/preview/dns/mgmt/2015-05-04-preview/dns/models.go
  services/preview/dns/mgmt/2015-05-04-preview/dns/recordsets.go
  services/preview/dns/mgmt/2015-05-04-preview/dns/zones.go
  services/preview/dns/mgmt/2018-03-01-preview/dns/models.go
  services/preview/dns/mgmt/2018-03-01-preview/dns/recordsets.go
  services/preview/dns/mgmt/2018-03-01-preview/dns/zones.go
Labels: ServicePR, review

#2298 [AutoPR] security/resource-manager
  profiles/preview/preview/security/mgmt/security/models.go
  services/preview/security/mgmt/2017-08-01-preview/security/alerts.go
  services/preview/security/mgmt/2017-08-01-preview/security/autoprovisioningsettings.go
  services/preview/security/mgmt/2017-08-01-preview/security/client.go
  services/preview/security/mgmt/2017-08-01-preview/security/compliances.go
  services/preview/security/mgmt/2017-08-01-preview/security/contacts.go
  services/preview/security/mgmt/2017-08-01-preview/security/discoveredsecuritysolutions.go
  services/preview/security/mgmt/2017-08-01-preview/security/externalsecuritysolutions.go
  services/preview/security/mgmt/2017-08-01-preview/security/jitnetworkaccesspolicies.go
  services/preview/security/mgmt/2017-08-01-preview/security/locations.go
  services/preview/security/mgmt/2017-08-01-preview/security/models.go
  services/preview/security/mgmt/2017-08-01-preview/security/operations.go
  services/preview/security/mgmt/2017-08-01-preview/security/pricings.go
  services/preview/security/mgmt/2017-08-01-preview/security/tasks.go
  services/preview/security/mgmt/2017-08-01-preview/security/version.go
  services/preview/security/mgmt/2017-08-01-preview/security/workspacesettings.go
Labels: ServicePR, review

#2314 Update generator version to 2.1.110 for swagge to sdk
  swagger_to_sdk_config.json
Labels: review

#2300 [AutoPR cognitiveservices/data-plane/Face] [cognitive Services] Update endpoint URL template for Face.
  profiles/latest/cognitiveservices/face/models.go
  profiles/preview/cognitiveservices/face/models.go
  services/cognitiveservices/v1.0/face/client.go
  services/cognitiveservices/v1.0/face/face.go
  services/cognitiveservices/v1.0/face/list.go
  services/cognitiveservices/v1.0/face/models.go
  services/cognitiveservices/v1.0/face/persongroup.go
  services/cognitiveservices/v1.0/face/persongroupperson.go
Labels: RestPRMerged, review

#2301 [AutoPR cognitiveservices/data-plane/TextAnalytics] [Cognitive Services] Update endpoint URL template for TextAnalytics.
  profiles/latest/cognitiveservices/textanalytics/models.go
  profiles/preview/cognitiveservices/textanalytics/models.go
  services/cognitiveservices/v2.0/textanalytics/client.go
  services/cognitiveservices/v2.0/textanalytics/models.go
Labels: RestPRMerged, review

#2297 [AutoPR containerservices/resource-manager] [AKS] remove "KeyVaultSecretRef" and rename to "ManagedClusterServicePrincipalProfile"
  profiles/preview/containerservice/mgmt/containerservice/models.go
  services/containerservice/mgmt/2018-03-31/containerservice/managedclusters.go
  services/containerservice/mgmt/2018-03-31/containerservice/models.go
Labels: RestPRMerged, review

#2308 [AutoPR eventgrid/data-plane] Add actions to event grid schema
  profiles/latest/eventgrid/eventgrid/models.go
  profiles/preview/eventgrid/eventgrid/models.go
  services/eventgrid/2018-01-01/eventgrid/models.go
Labels: RestPRMerged, review

#2330 [AutoPR] eventgrid/data-plane
  profiles/latest/eventgrid/eventgrid/models.go
  profiles/preview/eventgrid/eventgrid/models.go
  services/eventgrid/2018-01-01/eventgrid/models.go
Labels: ServicePR, review

#2321 [AutoPR] cognitiveservices/data-plane/Face
  profiles/latest/cognitiveservices/face/models.go
  profiles/preview/cognitiveservices/face/models.go
  services/cognitiveservices/v1.0/face/client.go
  services/cognitiveservices/v1.0/face/face.go
  services/cognitiveservices/v1.0/face/list.go
  services/cognitiveservices/v1.0/face/models.go
  services/cognitiveservices/v1.0/face/persongroup.go
  services/cognitiveservices/v1.0/face/persongroupperson.go
Labels: ServicePR, review

#2323 [AutoPR] cognitiveservices/data-plane/TextAnalytics
  profiles/latest/cognitiveservices/textanalytics/models.go
  profiles/preview/cognitiveservices/textanalytics/models.go
  services/cognitiveservices/v2.0/textanalytics/client.go
  services/cognitiveservices/v2.0/textanalytics/models.go
Labels: ServicePR, review

#2336 [AutoPR network/resource-manager] Python conf for Network 2018-06
  services/network/mgmt/2016-03-30/network/models.go
  services/network/mgmt/2016-06-01/network/models.go
  services/network/mgmt/2018-04-01/network/models.go
  services/network/mgmt/2018-04-01/network/vpnconnections.go
  services/preview/network/mgmt/2015-05-01-preview/network/models.go
Labels: RestPRMerged, review

#2338 [AutoPR] network/resource-manager
  services/network/mgmt/2016-03-30/network/models.go
  services/network/mgmt/2016-06-01/network/models.go
  services/network/mgmt/2018-04-01/network/models.go
  services/network/mgmt/2018-04-01/network/vpnconnections.go
  services/preview/network/mgmt/2015-05-01-preview/network/models.go
Labels: ServicePR, review

#2334 [AutoPR automation/resource-manager] Update automation management Node.js package version to 5.0.0-preview
  services/automation/mgmt/2015-10-31/automation/runbookdraft.go
  services/preview/automation/mgmt/2017-05-15-preview/automation/runbookdraft.go
  services/preview/automation/mgmt/2018-01-preview/automation/runbookdraft.go
Labels: RestPRMerged, review

#2324 [AutoPR] containerservices/resource-manager
  profiles/preview/containerservice/mgmt/containerservice/models.go
  services/containerservice/mgmt/2018-03-31/containerservice/managedclusters.go
  services/containerservice/mgmt/2018-03-31/containerservice/models.go
Labels: ServicePR, review

#2271 [AutoPR cognitiveservices/data-plane/LUIS/Runtime] Changing Entity Index to integer
  services/cognitiveservices/v2.0/luis/runtime/models.go
Labels: RestPRMerged, review

#2294 [AutoPR cognitiveservices/data-plane/ComputerVision] ComputerVision: bug fixes for /describe and /analyze [breaking]
  services/cognitiveservices/v2.0/computervision/client.go
  services/cognitiveservices/v2.0/computervision/models.go
Labels: RestPRMerged, review

#2344 [AutoPR] cognitiveservices/data-plane/ComputerVision
  services/cognitiveservices/v2.0/computervision/client.go
  services/cognitiveservices/v2.0/computervision/models.go
Labels: ServicePR, review

#2343 [AutoPR] cognitiveservices/data-plane/LUIS/Runtime
  services/cognitiveservices/v2.0/luis/runtime/models.go
Labels: ServicePR, review

#2341 [AutoPR containerservices/resource-manager] New credential api
  profiles/preview/containerservice/mgmt/containerservice/models.go
  services/containerservice/mgmt/2018-03-31/containerservice/managedclusters.go
  services/containerservice/mgmt/2018-03-31/containerservice/models.go
Labels: RestPRMerged, review

#2342 [AutoPR] containerservices/resource-manager
  profiles/preview/containerservice/mgmt/containerservice/models.go
  services/containerservice/mgmt/2018-03-31/containerservice/managedclusters.go
  services/containerservice/mgmt/2018-03-31/containerservice/models.go
Labels: ServicePR, review

#2276 [AutoPR storage/resource-manager] [Storage] Set the SignedResource as optional in ListServiceSAS
  Gopkg.lock
  services/preview/storage/mgmt/2018-03-01-preview/storage/models.go
  services/storage/mgmt/2017-06-01/storage/models.go
  services/storage/mgmt/2017-10-01/storage/models.go
  services/storage/mgmt/2018-02-01/storage/models.go
Labels: RestPRMerged, review

#2348 [AutoPR web/resource-manager] Fix documentation issues with metrics APIs
  Gopkg.lock
  services/web/mgmt/2018-02-01/web/apps.go
  services/web/mgmt/2018-02-01/web/appserviceenvironments.go
  services/web/mgmt/2018-02-01/web/appserviceplans.go
  services/web/mgmt/2018-02-01/web/recommendations.go
Labels: RestPRMerged, review

#2352 [AutoPR] web/resource-manager
  Gopkg.lock
  services/web/mgmt/2018-02-01/web/apps.go
  services/web/mgmt/2018-02-01/web/appserviceenvironments.go
  services/web/mgmt/2018-02-01/web/appserviceplans.go
  services/web/mgmt/2018-02-01/web/recommendations.go
Labels: ServicePR, review

#2354 [AutoPR containerinstance/resource-manager] Add Contaienr Group Stop and Restart API
  Gopkg.lock
Labels: RestPRMerged, review

#2356 [AutoPR servicefabricmesh/resource-manager] Azure Service Fabric Mesh Preview 2018-07-01 REST API specification
  services/preview/servicefabricmesh/mgmt/2018-07-01-preview/servicefabricmesh/models.go
Labels: RestPRMerged, review
