Repository Azure/azure-sdk-for-go, pull requests merged in 2018-05, with the labels that each got.

#1746 [AutoPR eventhub/resource-manager] EventHub: added $skip and $top to list calls
  services/eventhub/mgmt/2015-08-01/eventhub/consumergroups.go
  services/eventhub/mgmt/2015-08-01/eventhub/eventhubs.go
  services/eventhub/mgmt/2015-08-01/eventhub/namespaces.go
  services/eventhub/mgmt/2017-04-01/eventhub/consumergroups.go
  services/eventhub/mgmt/2017-04-01/eventhub/disasterrecoveryconfigs.go
  services/eventhub/mgmt/2017-04-01/eventhub/eventhubs.go
  services/eventhub/mgmt/2017-04-01/eventhub/namespaces.go
  services/eventhub/mgmt/2017-04-01/eventhub/regions.go
  services/preview/eventhub/mgmt/2018-01-01-preview/eventhub/clusters.go
  services/preview/eventhub/mgmt/2018-01-01-preview/eventhub/configuration.go
Labels: RestPRMerged, review

#1749 Add keyvault auth
  Gopkg.lock
  Gopkg.toml
  services/keyvault/auth/auth.go
Labels: review

#1754 [AutoPR web/resource-manager] Fix for https://github.com/Azure/azure-rest-api-specs/issues/2907
  services/web/mgmt/2015-08-preview/web/certificateorders.go
  services/web/mgmt/2015-08-preview/web/certificates.go
  services/web/mgmt/2015-08-preview/web/classicmobileservices.go
  services/web/mgmt/2015-08-preview/web/client.go
  services/web/mgmt/2015-08-preview/web/connections.go
  services/web/mgmt/2015-08-preview/web/domains.go
  services/web/mgmt/2015-08-preview/web/global.go
  services/web/mgmt/2015-08-preview/web/globalcertificateorder.go
  services/web/mgmt/2015-08-preview/web/globaldomainregistration.go
  services/web/mgmt/2015-08-preview/web/globalresourcegroups.go
  services/web/mgmt/2015-08-preview/web/hostingenvironments.go
  services/web/mgmt/2015-08-preview/web/managedapis.go
  services/web/mgmt/2015-08-preview/web/managedhostingenvironments.go
  services/web/mgmt/2015-08-preview/web/models.go
  services/web/mgmt/2015-08-preview/web/provider.go
  services/web/mgmt/2015-08-preview/web/recommendations.go
  services/web/mgmt/2015-08-preview/web/serverfarms.go
  services/web/mgmt/2015-08-preview/web/sites.go
  services/web/mgmt/2015-08-preview/web/topleveldomains.go
  services/web/mgmt/2015-08-preview/web/usage.go
  services/web/mgmt/2015-08-preview/web/version.go
  services/web/mgmt/2016-09-01/web/apps.go
  services/web/mgmt/2016-09-01/web/appserviceenvironments.go
Labels: RestPRMerged, review

#1757 [AutoPR compute/resource-manager] fixed formatting
  services/compute/mgmt/2018-04-01/compute/models.go
Labels: RestPRMerged, review

#1758 [AutoPR] compute/resource-manager
  services/compute/mgmt/2018-04-01/compute/models.go
Labels: ServicePR, review

#1762 [AutoPR datamigration/resource-manager] Changes for Microsoft.DataMigration GA stable version 2018-04-19.
  services/datamigration/mgmt/2017-11-15-preview/datamigration/client.go
  services/datamigration/mgmt/2017-11-15-preview/datamigration/models.go
  services/datamigration/mgmt/2017-11-15-preview/datamigration/operations.go
  services/datamigration/mgmt/2017-11-15-preview/datamigration/projects.go
  services/datamigration/mgmt/2017-11-15-preview/datamigration/resourceskus.go
  services/datamigration/mgmt/2017-11-15-preview/datamigration/services.go
  services/datamigration/mgmt/2017-11-15-preview/datamigration/tasks.go
  services/datamigration/mgmt/2017-11-15-preview/datamigration/usages.go
  services/datamigration/mgmt/2017-11-15-preview/datamigration/version.go
  services/preview/datamigration/mgmt/2017-11-15-preview/datamigration/models.go
  services/preview/datamigration/mgmt/2018-03-31-preview/datamigration/models.go
Labels: RestPRMerged, review

#1760 [AutoPR cognitiveservices/data-plane/TextAnalytics] Update CognitiveServices/Text-Analytics Swagger with new /entities endpoint
  profiles/latest/cognitiveservices/textanalytics/models.go
  profiles/preview/cognitiveservices/textanalytics/models.go
  services/cognitiveservices/v2.0/textanalytics/client.go
  services/cognitiveservices/v2.0/textanalytics/models.go
Labels: RestPRMerged, review

#1764 [AutoPR monitor/resource-manager] Minor Updates - description text
  services/monitor/mgmt/2017-05-01-preview/insights/actiongroups.go
  services/monitor/mgmt/2017-05-01-preview/insights/activitylogalerts.go
  services/monitor/mgmt/2017-05-01-preview/insights/alertruleincidents.go
  services/monitor/mgmt/2017-05-01-preview/insights/alertrules.go
  services/monitor/mgmt/2017-05-01-preview/insights/autoscalesettings.go
  services/monitor/mgmt/2017-05-01-preview/insights/client.go
  services/monitor/mgmt/2017-05-01-preview/insights/diagnosticsettings.go
  services/monitor/mgmt/2017-05-01-preview/insights/diagnosticsettingscategory.go
  services/monitor/mgmt/2017-05-01-preview/insights/logprofiles.go
  services/monitor/mgmt/2017-05-01-preview/insights/models.go
  services/monitor/mgmt/2017-05-01-preview/insights/operations.go
  services/monitor/mgmt/2017-05-01-preview/insights/version.go
  services/monitor/mgmt/2018-03-01/insights/actiongroups.go
  services/monitor/mgmt/2018-03-01/insights/activitylogalerts.go
  services/monitor/mgmt/2018-03-01/insights/activitylogs.go
  services/monitor/mgmt/2018-03-01/insights/alertruleincidents.go
  services/monitor/mgmt/2018-03-01/insights/alertrules.go
  services/monitor/mgmt/2018-03-01/insights/autoscalesettings.go
  services/monitor/mgmt/2018-03-01/insights/client.go
  services/monitor/mgmt/2018-03-01/insights/diagnosticsettings.go
  services/monitor/mgmt/2018-03-01/insights/diagnosticsettingscategory.go
  services/monitor/mgmt/2018-03-01/insights/eventcategories.go
  services/monitor/mgmt/2018-03-01/insights/logprofiles.go
  services/monitor/mgmt/2018-03-01/insights/metricbaseline.go
  services/monitor/mgmt/2018-03-01/insights/metricdefinitions.go
  services/monitor/mgmt/2018-03-01/insights/metrics.go
  services/monitor/mgmt/2018-03-01/insights/models.go
  services/monitor/mgmt/2018-03-01/insights/operations.go
  services/monitor/mgmt/2018-03-01/insights/tenantactivitylogs.go
  services/monitor/mgmt/2018-03-01/insights/version.go
  services/preview/monitor/mgmt/2018-03-01/insights/models.go
  services/preview/monitor/mgmt/2018-03-01/insights/scheduledqueryrules.go
Labels: RestPRMerged, review

#1773 [AutoPR signalr/resource-manager] update CheckNameAvailability resource to add extra location in its route
  services/preview/signalr/mgmt/2018-03-01-preview/signalr/signalr.go
Labels: RestPRMerged, review

#1769 [AutoPR] cognitiveservices/data-plane/TextAnalytics
  profiles/latest/cognitiveservices/textanalytics/models.go
  profiles/preview/cognitiveservices/textanalytics/models.go
  services/cognitiveservices/v2.0/textanalytics/client.go
  services/cognitiveservices/v2.0/textanalytics/models.go
Labels: ServicePR, review

#1775 [AutoPR] signalr/resource-manager
  services/preview/signalr/mgmt/2018-03-01-preview/signalr/signalr.go
Labels: ServicePR, review

#1779 [AutoPR eventgrid/resource-manager/trafficmanager/resource-manager] Move preview Go packages to preview subdirectory
  profiles/preview/preview/eventgrid/mgmt/eventgrid/models.go
  services/preview/eventgrid/mgmt/2018-05-01-preview/eventgrid/client.go
  services/preview/eventgrid/mgmt/2018-05-01-preview/eventgrid/eventsubscriptions.go
  services/preview/eventgrid/mgmt/2018-05-01-preview/eventgrid/models.go
  services/preview/eventgrid/mgmt/2018-05-01-preview/eventgrid/operations.go
  services/preview/eventgrid/mgmt/2018-05-01-preview/eventgrid/topics.go
  services/preview/eventgrid/mgmt/2018-05-01-preview/eventgrid/topictypes.go
  services/preview/eventgrid/mgmt/2018-05-01-preview/eventgrid/version.go
  services/trafficmanager/mgmt/2018-03/trafficmanager/client.go
  services/trafficmanager/mgmt/2018-03/trafficmanager/endpoints.go
  services/trafficmanager/mgmt/2018-03/trafficmanager/geographichierarchies.go
  services/trafficmanager/mgmt/2018-03/trafficmanager/heatmap.go
  services/trafficmanager/mgmt/2018-03/trafficmanager/models.go
  services/trafficmanager/mgmt/2018-03/trafficmanager/profiles.go
  services/trafficmanager/mgmt/2018-03/trafficmanager/version.go
Labels: review

#1783 [AutoPR trafficmanager/resource-manager] fix trafficmanager API version directory for Go
  profiles/preview/trafficmanager/mgmt/trafficmanager/models.go
Labels: RestPRMerged, review

#1785 [AutoPR] trafficmanager/resource-manager
  profiles/preview/trafficmanager/mgmt/trafficmanager/models.go
Labels: ServicePR, review

#1791 [AutoPR recoveryservicessiterecovery/resource-manager] BugFixes: Representing enums as string and moving away from complex odata fields.
  profiles/latest/recoveryservices/mgmt/siterecovery/models.go
  profiles/preview/recoveryservices/mgmt/siterecovery/models.go
  services/recoveryservices/mgmt/2018-01-10/siterecovery/models.go
  services/recoveryservices/mgmt/2018-01-10/siterecovery/replicationprotectableitems.go
Labels: RestPRMerged, review

#1792 [AutoPR] recoveryservicessiterecovery/resource-manager
  profiles/latest/recoveryservices/mgmt/siterecovery/models.go
  profiles/preview/recoveryservices/mgmt/siterecovery/models.go
  services/recoveryservices/mgmt/2018-01-10/siterecovery/models.go
  services/recoveryservices/mgmt/2018-01-10/siterecovery/replicationprotectableitems.go
Labels: ServicePR, review

#1793 [AutoPR web/resource-manager] Fix for https://github.com/Azure/azure-rest-api-specs/issues/2907. Missed the production slot APIs earlier.
  services/web/mgmt/2016-09-01/web/apps.go
  services/web/mgmt/2018-02-01/web/apps.go
Labels: RestPRMerged, review

#1794 [AutoPR] web/resource-manager
  services/web/mgmt/2016-09-01/web/apps.go
  services/web/mgmt/2018-02-01/web/apps.go
Labels: ServicePR, review

#1753 [AutoPR cognitiveservices/data-plane/LUIS/Authoring] Add patterns and regex related APIs to LUIS
  profiles/latest/cognitiveservices/luis/programmatic/models.go
  profiles/preview/cognitiveservices/luis/programmatic/models.go
  services/cognitiveservices/v2.0/luis/programmatic/model.go
  services/cognitiveservices/v2.0/luis/programmatic/models.go
  services/cognitiveservices/v2.0/luis/programmatic/pattern.go
Labels: RestPRMerged, review

#1797 [AutoPR] cognitiveservices/data-plane/LUIS/Authoring
  profiles/latest/cognitiveservices/luis/programmatic/models.go
  profiles/preview/cognitiveservices/luis/programmatic/models.go
  services/cognitiveservices/v2.0/luis/programmatic/model.go
  services/cognitiveservices/v2.0/luis/programmatic/models.go
  services/cognitiveservices/v2.0/luis/programmatic/pattern.go
Labels: ServicePR, review

#1801 [AutoPR cognitiveservices/data-plane/LUIS/Runtime] Update sentiment signature in the endpoint reponse
  services/cognitiveservices/v2.0/luis/runtime/models.go
Labels: review

#1807 [AutoPR hanaonazure/resource-manager] Update Swagger constraints to allow HANA Very Large Instances
  profiles/preview/preview/hanaonazure/mgmt/hanaonazure/models.go
  services/preview/hanaonazure/mgmt/2017-11-03-preview/hanaonazure/models.go
Labels: review

#1767 [AutoPR compute/resource-manager] added autoOSUpgradePolicy to UpgradePolicy
  profiles/latest/compute/mgmt/compute/models.go
  profiles/preview/compute/mgmt/compute/models.go
  services/compute/mgmt/2018-04-01/compute/models.go
Labels: RestPRMerged, review

#1814 [AutoPR containerservices/resource-manager] [AKS] remove unsupported VM types
  profiles/latest/containerservice/mgmt/containerservice/models.go
  profiles/preview/containerservice/mgmt/containerservice/models.go
  services/containerservice/mgmt/2017-07-01/containerservice/models.go
  services/containerservice/mgmt/2017-08-31/containerservice/models.go
  services/containerservice/mgmt/2017-09-30/containerservice/models.go
Labels: review

#1765 [AutoPR cognitiveservices/data-plane/CustomImageSearch] Adding custom image search swagger spec
  profiles/preview/cognitiveservices/customimagesearch/models.go
  services/cognitiveservices/v1.0/customimagesearch/client.go
  services/cognitiveservices/v1.0/customimagesearch/custominstance.go
  services/cognitiveservices/v1.0/customimagesearch/models.go
  services/cognitiveservices/v1.0/customimagesearch/version.go
Labels: RestPRMerged, review

#1816 [AutoPR managementgroups/resource-manager] Fix error in the possible values for an enum - Management Groups
  profiles/preview/preview/resources/mgmt/management/models.go
  services/preview/resources/mgmt/2018-01-01-preview/management/models.go
Labels: RestPRMerged, review

#1819 [AutoPR cognitiveservices/data-plane/LUIS/Authoring] Adding Settings APIs and examples
  profiles/preview/cognitiveservices/luis/Authoring/models.go
  services/cognitiveservices/v2.0/luis/Authoring/apps.go
  services/cognitiveservices/v2.0/luis/Authoring/client.go
  services/cognitiveservices/v2.0/luis/Authoring/examples.go
  services/cognitiveservices/v2.0/luis/Authoring/features.go
  services/cognitiveservices/v2.0/luis/Authoring/model.go
  services/cognitiveservices/v2.0/luis/Authoring/models.go
  services/cognitiveservices/v2.0/luis/Authoring/pattern.go
  services/cognitiveservices/v2.0/luis/Authoring/permissions.go
  services/cognitiveservices/v2.0/luis/Authoring/train.go
  services/cognitiveservices/v2.0/luis/Authoring/version.go
  services/cognitiveservices/v2.0/luis/Authoring/versions.go
Labels: RestPRMerged, review

#1751 [AutoPR cosmos-db/resource-manager] Swagger changes to introduce REST APIs for offline and online region for the Cosmos DB account
  profiles/latest/cosmos-db/mgmt/documentdb/models.go
  profiles/preview/cosmos-db/mgmt/documentdb/models.go
  services/cosmos-db/mgmt/2015-04-08/documentdb/databaseaccounts.go
  services/cosmos-db/mgmt/2015-04-08/documentdb/models.go
Labels: RestPRMerged, review

#1802 [AutoPR] cognitiveservices/data-plane/LUIS/Runtime
  services/cognitiveservices/v2.0/luis/runtime/models.go
Labels: ServicePR, review

#1790 [AutoPR storage/resource-manager] [Storage] Add Get Location Usage support
  services/storage/mgmt/2018-02-01/storage/usage.go
Labels: review

#1803 [AutoPR eventgrid/data-plane] Add ServiceBus Messaging Integration Events with EventGrid to the Eve…
  profiles/latest/eventgrid/eventgrid/models.go
  profiles/preview/eventgrid/eventgrid/models.go
  services/eventgrid/2018-01-01/eventgrid/models.go
Labels: RestPRInProgress, review

#1808 [AutoPR] hanaonazure/resource-manager
  profiles/preview/preview/hanaonazure/mgmt/hanaonazure/models.go
  services/preview/hanaonazure/mgmt/2017-11-03-preview/hanaonazure/models.go
Labels: ServicePR, review

#1813 [AutoPR] compute/resource-manager
  profiles/latest/compute/mgmt/compute/models.go
  profiles/preview/compute/mgmt/compute/models.go
  services/compute/mgmt/2018-04-01/compute/models.go
Labels: ServicePR, review

#1815 [AutoPR] containerservices/resource-manager
  profiles/latest/containerservice/mgmt/containerservice/models.go
  profiles/preview/containerservice/mgmt/containerservice/models.go
  services/containerservice/mgmt/2017-07-01/containerservice/models.go
  services/containerservice/mgmt/2017-08-31/containerservice/models.go
  services/containerservice/mgmt/2017-09-30/containerservice/models.go
Labels: ServicePR, review

#1817 [AutoPR] cognitiveservices/data-plane/CustomImageSearch
  profiles/preview/cognitiveservices/customimagesearch/models.go
  services/cognitiveservices/v1.0/customimagesearch/client.go
  services/cognitiveservices/v1.0/customimagesearch/custominstance.go
  services/cognitiveservices/v1.0/customimagesearch/models.go
  services/cognitiveservices/v1.0/customimagesearch/version.go
Labels: ServicePR, review

#1818 [AutoPR] managementgroups/resource-manager
  profiles/preview/preview/resources/mgmt/management/models.go
  services/preview/resources/mgmt/2018-01-01-preview/management/models.go
Labels: ServicePR, review

#1821 [AutoPR] cosmos-db/resource-manager
  profiles/latest/cosmos-db/mgmt/documentdb/models.go
  profiles/preview/cosmos-db/mgmt/documentdb/models.go
  services/cosmos-db/mgmt/2015-04-08/documentdb/databaseaccounts.go
  services/cosmos-db/mgmt/2015-04-08/documentdb/models.go
Labels: ServicePR, review

#1834 [AutoPR hanaonazure/resource-manager] HanaOnAzure: Remove incorrectly-added SKU from enum
  profiles/preview/preview/hanaonazure/mgmt/hanaonazure/models.go
  services/preview/hanaonazure/mgmt/2017-11-03-preview/hanaonazure/models.go
Labels: review

#1811 [AutoPR resources/resource-manager] Update Azure Governance Policy api-version to 2018-03-01
  profiles/preview/resources/mgmt/policy/models.go
  services/resources/mgmt/2018-03-01/policy/assignments.go
  services/resources/mgmt/2018-03-01/policy/client.go
  services/resources/mgmt/2018-03-01/policy/definitions.go
  services/resources/mgmt/2018-03-01/policy/models.go
  services/resources/mgmt/2018-03-01/policy/setdefinitions.go
  services/resources/mgmt/2018-03-01/policy/version.go
Labels: RestPRMerged, review

#1836 [AutoPR batchai/resource-manager] BatchAI. Several fixes
  services/batchai/mgmt/2018-05-01/batchai/experiments.go
  services/batchai/mgmt/2018-05-01/batchai/models.go
Labels: RestPRMerged, review

#1843 [AutoPR eventgrid/data-plane] EventGrid Dataplane: Added schemas corresponding to SubscriptionValidationEvent/Response and SubscriptionDeletedEvent
  profiles/latest/eventgrid/eventgrid/models.go
  profiles/preview/eventgrid/eventgrid/models.go
  services/eventgrid/2018-01-01/eventgrid/models.go
Labels: review

#1786 [AutoPR datafactory/resource-manager] [DataFactory] blob events trigger
  profiles/preview/preview/datafactory/mgmt/datafactory/models.go
  profiles/preview/trafficmanager/mgmt/trafficmanager/models.go
  services/preview/datafactory/mgmt/2017-09-01-preview/datafactory/models.go
Labels: RestPRMerged, review

#1849 [AutoPR network/resource-manager] Merge Network-2018-05-01 to master
  profiles/preview/network/mgmt/network/models.go
  services/network/mgmt/2018-04-01/network/models.go
  services/network/mgmt/2018-04-01/network/virtualnetworkgateways.go
Labels: RestPRMerged, review

#1831 [AutoPR compute/resource-manager] Added linuxConfiguration.provisionVMAgent and osProfile.allowExtensionOperations to Microsoft.Compute/stable/2018-06-01
  services/compute/mgmt/2018-04-01/compute/models.go
Labels: RestPRMerged, review

#1855 [AutoPR sql/resource-manager] [Do not merge - Waiting for public preview] Update jobs.json to latest generated swagger file as well as it's updated examples
  profiles/preview/preview/sql/mgmt/sql/models.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/databasevulnerabilityassessmentrulebaselines.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/databasevulnerabilityassessments.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/jobagents.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/jobcredentials.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/jobexecutions.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/jobs.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/jobstepexecutions.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/jobsteps.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/jobtargetexecutions.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/jobtargetgroups.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/jobversions.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/models.go
  services/preview/sql/mgmt/2017-10-01-preview/sql/databasevulnerabilityassessmentscans.go
  services/preview/sql/mgmt/2017-10-01-preview/sql/models.go
Labels: RestPRMerged, review

#1799 [AutoPR cognitiveservices/data-plane/CustomVision/Prediction/cognitiveservices/data-plane/CustomVision/Training] Add Custom vision 2.0 Swagger
  profiles/preview/cognitiveservices/customvision/prediction/models.go
  profiles/preview/cognitiveservices/customvision/training/models.go
  services/cognitiveservices/v1.1/customvision/prediction/client.go
  services/cognitiveservices/v1.1/customvision/prediction/models.go
  services/cognitiveservices/v1.1/customvision/prediction/version.go
  services/cognitiveservices/v1.2/customvision/training/client.go
  services/cognitiveservices/v1.2/customvision/training/models.go
  services/cognitiveservices/v1.2/customvision/training/version.go
Labels: review

#1835 [AutoPR] hanaonazure/resource-manager
  profiles/preview/preview/hanaonazure/mgmt/hanaonazure/models.go
  services/preview/hanaonazure/mgmt/2017-11-03-preview/hanaonazure/models.go
Labels: ServicePR, review

#1839 [AutoPR] resources/resource-manager
  profiles/preview/resources/mgmt/policy/models.go
  services/resources/mgmt/2018-03-01/policy/assignments.go
  services/resources/mgmt/2018-03-01/policy/client.go
  services/resources/mgmt/2018-03-01/policy/definitions.go
  services/resources/mgmt/2018-03-01/policy/models.go
  services/resources/mgmt/2018-03-01/policy/setdefinitions.go
  services/resources/mgmt/2018-03-01/policy/version.go
Labels: ServicePR, review

#1841 [AutoPR] batchai/resource-manager
  services/batchai/mgmt/2018-05-01/batchai/experiments.go
  services/batchai/mgmt/2018-05-01/batchai/models.go
Labels: ServicePR, review

#1844 [AutoPR] eventgrid/data-plane
  profiles/latest/eventgrid/eventgrid/models.go
  profiles/preview/eventgrid/eventgrid/models.go
  services/eventgrid/2018-01-01/eventgrid/models.go
Labels: ServicePR, review

#1864 [AutoPR cognitiveservices/data-plane/LUIS/Authoring] Fix naming for Go and Java packages
  profiles/preview/cognitiveservices/luis/authoring/models.go
  services/cognitiveservices/v2.0/luis/authoring/apps.go
  services/cognitiveservices/v2.0/luis/authoring/client.go
  services/cognitiveservices/v2.0/luis/authoring/examples.go
  services/cognitiveservices/v2.0/luis/authoring/features.go
  services/cognitiveservices/v2.0/luis/authoring/model.go
  services/cognitiveservices/v2.0/luis/authoring/models.go
  services/cognitiveservices/v2.0/luis/authoring/pattern.go
  services/cognitiveservices/v2.0/luis/authoring/permissions.go
  services/cognitiveservices/v2.0/luis/authoring/train.go
  services/cognitiveservices/v2.0/luis/authoring/version.go
  services/cognitiveservices/v2.0/luis/authoring/versions.go
Labels: RestPRMerged, review

#1852 [AutoPR] network/resource-manager
  profiles/preview/network/mgmt/network/models.go
  services/network/mgmt/2018-04-01/network/models.go
  services/network/mgmt/2018-04-01/network/virtualnetworkgateways.go
Labels: ServicePR, review

#1858 [AutoPR] sql/resource-manager
  profiles/preview/preview/sql/mgmt/sql/models.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/databasevulnerabilityassessmentrulebaselines.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/databasevulnerabilityassessments.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/jobagents.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/jobcredentials.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/jobexecutions.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/jobs.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/jobstepexecutions.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/jobsteps.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/jobtargetexecutions.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/jobtargetgroups.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/jobversions.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/models.go
  services/preview/sql/mgmt/2017-10-01-preview/sql/databasevulnerabilityassessmentscans.go
  services/preview/sql/mgmt/2017-10-01-preview/sql/models.go
Labels: ServicePR, review

#1865 [AutoPR] cognitiveservices/data-plane/LUIS/Authoring
  profiles/preview/cognitiveservices/luis/authoring/models.go
  services/cognitiveservices/v2.0/luis/authoring/apps.go
  services/cognitiveservices/v2.0/luis/authoring/client.go
  services/cognitiveservices/v2.0/luis/authoring/examples.go
  services/cognitiveservices/v2.0/luis/authoring/features.go
  services/cognitiveservices/v2.0/luis/authoring/model.go
  services/cognitiveservices/v2.0/luis/authoring/models.go
  services/cognitiveservices/v2.0/luis/authoring/pattern.go
  services/cognitiveservices/v2.0/luis/authoring/permissions.go
  services/cognitiveservices/v2.0/luis/authoring/train.go
  services/cognitiveservices/v2.0/luis/authoring/version.go
  services/cognitiveservices/v2.0/luis/authoring/versions.go
Labels: ServicePR, review

#1866 [AutoPR network/resource-manager] Add latest network API version to Go SDK
  profiles/preview/network/mgmt/network/models.go
  services/network/mgmt/2018-05-01/network/applicationgateways.go
  services/network/mgmt/2018-05-01/network/applicationsecuritygroups.go
  services/network/mgmt/2018-05-01/network/availableendpointservices.go
  services/network/mgmt/2018-05-01/network/bgpservicecommunities.go
  services/network/mgmt/2018-05-01/network/client.go
  services/network/mgmt/2018-05-01/network/connectionmonitors.go
  services/network/mgmt/2018-05-01/network/ddosprotectionplans.go
  services/network/mgmt/2018-05-01/network/defaultsecurityrules.go
  services/network/mgmt/2018-05-01/network/expressroutecircuitauthorizations.go
  services/network/mgmt/2018-05-01/network/expressroutecircuitconnections.go
  services/network/mgmt/2018-05-01/network/expressroutecircuitpeerings.go
  services/network/mgmt/2018-05-01/network/expressroutecircuits.go
  services/network/mgmt/2018-05-01/network/expressroutecrossconnectionpeerings.go
  services/network/mgmt/2018-05-01/network/expressroutecrossconnections.go
  services/network/mgmt/2018-05-01/network/expressrouteserviceproviders.go
  services/network/mgmt/2018-05-01/network/inboundnatrules.go
  services/network/mgmt/2018-05-01/network/interfaceipconfigurations.go
  services/network/mgmt/2018-05-01/network/interfaceloadbalancers.go
  services/network/mgmt/2018-05-01/network/interfaces.go
  services/network/mgmt/2018-05-01/network/loadbalancerbackendaddresspools.go
  services/network/mgmt/2018-05-01/network/loadbalancerfrontendipconfigurations.go
  services/network/mgmt/2018-05-01/network/loadbalancerloadbalancingrules.go
  services/network/mgmt/2018-05-01/network/loadbalancernetworkinterfaces.go
  services/network/mgmt/2018-05-01/network/loadbalancerprobes.go
  services/network/mgmt/2018-05-01/network/loadbalancers.go
  services/network/mgmt/2018-05-01/network/localnetworkgateways.go
  services/network/mgmt/2018-05-01/network/models.go
  services/network/mgmt/2018-05-01/network/operations.go
  services/network/mgmt/2018-05-01/network/packetcaptures.go
  services/network/mgmt/2018-05-01/network/publicipaddresses.go
  services/network/mgmt/2018-05-01/network/routefilterrules.go
  services/network/mgmt/2018-05-01/network/routefilters.go
  services/network/mgmt/2018-05-01/network/routes.go
  services/network/mgmt/2018-05-01/network/routetables.go
  services/network/mgmt/2018-05-01/network/securitygroups.go
  services/network/mgmt/2018-05-01/network/securityrules.go
  services/network/mgmt/2018-05-01/network/subnets.go
  services/network/mgmt/2018-05-01/network/usages.go
  services/network/mgmt/2018-05-01/network/version.go
  services/network/mgmt/2018-05-01/network/virtualnetworkgatewayconnections.go
  services/network/mgmt/2018-05-01/network/virtualnetworkgateways.go
  services/network/mgmt/2018-05-01/network/virtualnetworkpeerings.go
  services/network/mgmt/2018-05-01/network/virtualnetworks.go
  services/network/mgmt/2018-05-01/network/watchers.go
Labels: RestPRInProgress, review

#1860 [AutoPR managementgroups/resource-manager] Add Management Groups 2018-03-01-preview version
  profiles/preview/preview/resources/mgmt/management/models.go
  services/preview/resources/mgmt/2018-03-01-preview/management/client.go
  services/preview/resources/mgmt/2018-03-01-preview/management/entities.go
  services/preview/resources/mgmt/2018-03-01-preview/management/managementgroups.go
  services/preview/resources/mgmt/2018-03-01-preview/management/models.go
  services/preview/resources/mgmt/2018-03-01-preview/management/operations.go
  services/preview/resources/mgmt/2018-03-01-preview/management/subscriptions.go
  services/preview/resources/mgmt/2018-03-01-preview/management/version.go
Labels: RestPRMerged, review

#1869 [AutoPR eventgrid/data-plane] Adding Media Services Event Grid schema
  profiles/latest/eventgrid/eventgrid/models.go
  profiles/preview/eventgrid/eventgrid/models.go
  services/eventgrid/2018-01-01/eventgrid/models.go
Labels: RestPRMerged, review

#1878 [AutoPR monitor/resource-manager] Add "autoMitigate" to Metric Alert API spec for 2018-03-01
  profiles/preview/preview/monitor/mgmt/insights/models.go
  services/preview/monitor/mgmt/2018-03-01/insights/metricalerts.go
  services/preview/monitor/mgmt/2018-03-01/insights/metricalertsstatus.go
  services/preview/monitor/mgmt/2018-03-01/insights/metricdefinitions.go
  services/preview/monitor/mgmt/2018-03-01/insights/metrics.go
  services/preview/monitor/mgmt/2018-03-01/insights/models.go
  services/preview/monitor/mgmt/2018-03-01/insights/scheduledqueryrules.go
Labels: RestPRInProgress, RestPRMerged, review

#1854 [AutoPR compute/resource-manager] Upgrade Compute API version and Fix the response of POST response
  profiles/latest/compute/mgmt/compute/models.go
  profiles/preview/compute/mgmt/compute/models.go
  services/compute/mgmt/2018-04-01/compute/disks.go
  services/compute/mgmt/2018-04-01/compute/models.go
  services/compute/mgmt/2018-04-01/compute/snapshots.go
Labels: RestPRMerged, review

#1863 [AutoPR containerservices/resource-manager] [AKS] add POST endpoint for fetching accessProfiles
  services/containerservice/mgmt/2017-08-31/containerservice/managedclusters.go
  services/containerservice/mgmt/2017-09-30/containerservice/managedclusters.go
Labels: RestPRMerged, review

#1883 [AutoPR managementgroups/resource-manager] Fix typo in enum
  profiles/preview/preview/resources/mgmt/management/models.go
  services/preview/resources/mgmt/2018-03-01-preview/management/models.go
Labels: RestPRMerged, review

#1891 [AutoPR notificationhubs/resource-manager] Add suppressions for linting errors. Approved by Gaurav
  profiles/latest/notificationhubs/mgmt/notificationhubs/models.go
  profiles/preview/notificationhubs/mgmt/notificationhubs/models.go
  services/notificationhubs/mgmt/2017-04-01/notificationhubs/hubs.go
  services/notificationhubs/mgmt/2017-04-01/notificationhubs/models.go
  services/notificationhubs/mgmt/2017-04-01/notificationhubs/name.go
  services/notificationhubs/mgmt/2017-04-01/notificationhubs/namespaces.go
  services/notificationhubs/mgmt/2017-04-01/notificationhubs/notificationhubs.go
  services/notificationhubs/mgmt/2017-04-01/notificationhubs/operations.go
Labels: review

#1889 [AutoPR sql/resource-manager] Rename resource "ShortTermRetentionPolicy"->"BackupShortTermRetentionPolicy" to align with "BackupLongTermRetentionPolicy"
  profiles/preview/preview/sql/mgmt/sql/models.go
  services/preview/sql/mgmt/2017-10-01-preview/sql/backupshorttermretentionpolicies.go
  services/preview/sql/mgmt/2017-10-01-preview/sql/models.go
Labels: RestPRInProgress, review

#1868 [AutoPR] managementgroups/resource-manager
  profiles/preview/preview/resources/mgmt/management/models.go
  services/preview/resources/mgmt/2018-03-01-preview/management/client.go
  services/preview/resources/mgmt/2018-03-01-preview/management/entities.go
  services/preview/resources/mgmt/2018-03-01-preview/management/managementgroups.go
  services/preview/resources/mgmt/2018-03-01-preview/management/models.go
  services/preview/resources/mgmt/2018-03-01-preview/management/operations.go
  services/preview/resources/mgmt/2018-03-01-preview/management/subscriptions.go
  services/preview/resources/mgmt/2018-03-01-preview/management/version.go
Labels: ServicePR, review

#1870 [AutoPR] eventgrid/data-plane
  profiles/latest/eventgrid/eventgrid/models.go
  profiles/preview/eventgrid/eventgrid/models.go
  services/eventgrid/2018-01-01/eventgrid/models.go
Labels: ServicePR, review

#1881 [AutoPR] containerservices/resource-manager
  services/containerservice/mgmt/2017-08-31/containerservice/managedclusters.go
  services/containerservice/mgmt/2017-09-30/containerservice/managedclusters.go
Labels: ServicePR, review

#1892 [AutoPR] notificationhubs/resource-manager
  profiles/latest/notificationhubs/mgmt/notificationhubs/models.go
  profiles/preview/notificationhubs/mgmt/notificationhubs/models.go
  services/notificationhubs/mgmt/2017-04-01/notificationhubs/hubs.go
  services/notificationhubs/mgmt/2017-04-01/notificationhubs/models.go
  services/notificationhubs/mgmt/2017-04-01/notificationhubs/name.go
  services/notificationhubs/mgmt/2017-04-01/notificationhubs/namespaces.go
  services/notificationhubs/mgmt/2017-04-01/notificationhubs/notificationhubs.go
  services/notificationhubs/mgmt/2017-04-01/notificationhubs/operations.go
Labels: ServicePR, review

#1850 [AutoPR cognitiveservices/data-plane/ComputerVision] Update CognitiveService ComputerVision Swagger for new extensions
  profiles/latest/cognitiveservices/computervision/models.go
  profiles/preview/cognitiveservices/computervision/models.go
  services/cognitiveservices/v1.0/computervision/client.go
  services/cognitiveservices/v1.0/computervision/models.go
Labels: RestPRMerged, review

#1861 [AutoPR web/resource-manager] Update Web Apps swagger with restore deleted site APIs
  profiles/preview/web/mgmt/web/models.go
  services/web/mgmt/2018-02-01/web/apps.go
  services/web/mgmt/2018-02-01/web/models.go
Labels: RestPRMerged, review

#1896 [AutoPR applicationinsights/resource-manager] [AppInsights] Added webtests-by-component API to 2015-05-01
  services/appinsights/mgmt/2015-05-01/insights/webtests.go
Labels: RestPRMerged, review

#1894 [AutoPR sql/resource-manager] New for swagger update
  profiles/preview/preview/sql/mgmt/sql/models.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/databasevulnerabilityassessments.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/jobagents.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/jobcredentials.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/jobexecutions.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/jobs.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/jobstepexecutions.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/jobsteps.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/jobtargetexecutions.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/jobtargetgroups.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/jobversions.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/models.go
  services/preview/sql/mgmt/2017-10-01-preview/sql/databasevulnerabilityassessmentscans.go
  services/preview/sql/mgmt/2017-10-01-preview/sql/models.go
Labels: RestPRMerged, review

#1847 [AutoPR botservice/resource-manager] Update botservice swagger to perform crud operations on connection settings
  profiles/preview/preview/botservice/mgmt/botservices/models.go
  services/preview/botservice/mgmt/2017-12-01/botservices/botconnection.go
  services/preview/botservice/mgmt/2017-12-01/botservices/bots.go
  services/preview/botservice/mgmt/2017-12-01/botservices/channels.go
  services/preview/botservice/mgmt/2017-12-01/botservices/models.go
Labels: RestPRMerged, review

#1901 [AutoPR monitor/resource-manager] [Monitor] Deconflict "Action" name in MetricAlert
  profiles/preview/preview/monitor/mgmt/insights/models.go
  services/preview/monitor/mgmt/2018-03-01/insights/metricalerts.go
  services/preview/monitor/mgmt/2018-03-01/insights/metricalertsstatus.go
  services/preview/monitor/mgmt/2018-03-01/insights/metricdefinitions.go
  services/preview/monitor/mgmt/2018-03-01/insights/metrics.go
  services/preview/monitor/mgmt/2018-03-01/insights/models.go
  services/preview/monitor/mgmt/2018-03-01/insights/scheduledqueryrules.go
Labels: RestPRMerged, review

#1905 [AutoPR sql/resource-manager] Use common Resource & Sku definitions in all Sql specs
  services/preview/sql/mgmt/2015-05-01-preview/sql/models.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/jobagents.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/jobcredentials.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/jobexecutions.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/jobs.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/jobstepexecutions.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/jobsteps.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/jobtargetexecutions.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/jobtargetgroups.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/jobversions.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/models.go
  services/preview/sql/mgmt/2017-10-01-preview/sql/models.go
  services/sql/mgmt/2014-04-01/sql/models.go
Labels: RestPRMerged, review

#1908 [AutoPR keyvault/data-plane] RSA key size examples, ECC descriptions
  services/keyvault/2016-10-01/keyvault/models.go
Labels: RestPRMerged, review

#1853 [AutoPR] compute/resource-manager
  profiles/latest/compute/mgmt/compute/models.go
  profiles/preview/compute/mgmt/compute/models.go
  services/compute/mgmt/2018-04-01/compute/disks.go
  services/compute/mgmt/2018-04-01/compute/models.go
  services/compute/mgmt/2018-04-01/compute/snapshots.go
Labels: ServicePR, review

#1857 [AutoPR] web/resource-manager
  profiles/preview/web/mgmt/web/models.go
  services/web/mgmt/2018-02-01/web/apps.go
  services/web/mgmt/2018-02-01/web/models.go
Labels: ServicePR, review

#1900 [AutoPR] applicationinsights/resource-manager
  services/appinsights/mgmt/2015-05-01/insights/webtests.go
Labels: ServicePR, review

#1903 [AutoPR] botservice/resource-manager
  profiles/preview/preview/botservice/mgmt/botservices/models.go
  services/preview/botservice/mgmt/2017-12-01/botservices/botconnection.go
  services/preview/botservice/mgmt/2017-12-01/botservices/bots.go
  services/preview/botservice/mgmt/2017-12-01/botservices/channels.go
  services/preview/botservice/mgmt/2017-12-01/botservices/models.go
Labels: ServicePR, review

#1909 [AutoPR] keyvault/data-plane
  services/keyvault/2016-10-01/keyvault/models.go
Labels: ServicePR, review

#1914 [AutoPR network/resource-manager] Fix foir Azure Networking swagger
  services/network/mgmt/2018-04-01/network/models.go
  services/network/mgmt/2018-04-01/network/watchers.go
Labels: RestPRMerged, review

#1879 [AutoPR] monitor/resource-manager
  profiles/preview/preview/monitor/mgmt/insights/models.go
  services/preview/monitor/mgmt/2018-03-01/insights/models.go
  services/preview/monitor/mgmt/2018-03-01/insights/scheduledqueryrules.go
Labels: ServicePR, review

#1897 [AutoPR] cognitiveservices/data-plane/ComputerVision
  profiles/latest/cognitiveservices/computervision/models.go
  profiles/preview/cognitiveservices/computervision/models.go
  services/cognitiveservices/v1.0/computervision/client.go
  services/cognitiveservices/v1.0/computervision/models.go
Labels: ServicePR, review

#1902 [AutoPR] sql/resource-manager
  profiles/preview/preview/sql/mgmt/sql/models.go
  services/preview/sql/mgmt/2015-05-01-preview/sql/models.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/databasevulnerabilityassessments.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/models.go
  services/preview/sql/mgmt/2017-10-01-preview/sql/backupshorttermretentionpolicies.go
  services/preview/sql/mgmt/2017-10-01-preview/sql/databasevulnerabilityassessmentscans.go
  services/preview/sql/mgmt/2017-10-01-preview/sql/models.go
  services/sql/mgmt/2014-04-01/sql/models.go
Labels: ServicePR, review

#1923 [AutoPR storage/resource-manager] Fix go tag for storage management plane 2018-03-01 api version
  profiles/preview/preview/storage/mgmt/storage/models.go
  services/preview/storage/mgmt/2018-03-01-preview/storage/accounts.go
  services/preview/storage/mgmt/2018-03-01-preview/storage/blobcontainers.go
  services/preview/storage/mgmt/2018-03-01-preview/storage/client.go
  services/preview/storage/mgmt/2018-03-01-preview/storage/models.go
  services/preview/storage/mgmt/2018-03-01-preview/storage/operations.go
  services/preview/storage/mgmt/2018-03-01-preview/storage/skus.go
  services/preview/storage/mgmt/2018-03-01-preview/storage/usages.go
  services/preview/storage/mgmt/2018-03-01-preview/storage/version.go
Labels: review

#1912 [AutoPR machinelearningservices/resource-manager] Add specs for machine learning services provider
  profiles/preview/preview/machinelearning/mgmt/services/models.go
  services/preview/machinelearning/mgmt/2018-03-01-preview/services/client.go
  services/preview/machinelearning/mgmt/2018-03-01-preview/services/machinelearningcompute.go
  services/preview/machinelearning/mgmt/2018-03-01-preview/services/models.go
  services/preview/machinelearning/mgmt/2018-03-01-preview/services/operations.go
  services/preview/machinelearning/mgmt/2018-03-01-preview/services/version.go
  services/preview/machinelearning/mgmt/2018-03-01-preview/services/workspaces.go
Labels: RestPRMerged, review

#1929 [AutoPR network/resource-manager] reverted methods removal
  services/network/mgmt/2018-04-01/network/models.go
  services/network/mgmt/2018-04-01/network/virtualnetworkgateways.go
Labels: RestPRMerged, review

#1926 [AutoPR compute/resource-manager] [Disk swagger] Removing resourceUpdate, adding contents to diskupdate and snapshotupdate
  profiles/latest/compute/mgmt/compute/models.go
  profiles/preview/compute/mgmt/compute/models.go
  services/compute/mgmt/2018-04-01/compute/models.go
Labels: RestPRMerged, review

#1907 [AutoPR sql/resource-manager] Adding new value to VA baseline name
  services/preview/sql/mgmt/2017-03-01-preview/sql/databasevulnerabilityassessmentrulebaselines.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/models.go
Labels: RestPRMerged, review

#1933 [AutoPR] compute/resource-manager
  profiles/latest/compute/mgmt/compute/models.go
  profiles/preview/compute/mgmt/compute/models.go
  services/compute/mgmt/2018-04-01/compute/models.go
Labels: ServicePR, review

#1906 [AutoPR postgresql/resource-manager/mysql/resource-manager] ORCASQL VNET with API Version 2017-12-01 for Public Preview.
  profiles/latest/mysql/mgmt/mysql/models.go
  profiles/latest/postgresql/mgmt/postgresql/models.go
  profiles/preview/mysql/mgmt/mysql/models.go
  profiles/preview/postgresql/mgmt/postgresql/models.go
  services/mysql/mgmt/2017-12-01/mysql/checknameavailability.go
  services/mysql/mgmt/2017-12-01/mysql/client.go
  services/mysql/mgmt/2017-12-01/mysql/configurations.go
  services/mysql/mgmt/2017-12-01/mysql/databases.go
  services/mysql/mgmt/2017-12-01/mysql/firewallrules.go
  services/mysql/mgmt/2017-12-01/mysql/locationbasedperformancetier.go
  services/mysql/mgmt/2017-12-01/mysql/logfiles.go
  services/mysql/mgmt/2017-12-01/mysql/models.go
  services/mysql/mgmt/2017-12-01/mysql/operations.go
  services/mysql/mgmt/2017-12-01/mysql/servers.go
  services/mysql/mgmt/2017-12-01/mysql/virtualnetworkrules.go
  services/postgresql/mgmt/2017-12-01/postgresql/checknameavailability.go
  services/postgresql/mgmt/2017-12-01/postgresql/client.go
  services/postgresql/mgmt/2017-12-01/postgresql/configurations.go
  services/postgresql/mgmt/2017-12-01/postgresql/databases.go
  services/postgresql/mgmt/2017-12-01/postgresql/firewallrules.go
  services/postgresql/mgmt/2017-12-01/postgresql/locationbasedperformancetier.go
  services/postgresql/mgmt/2017-12-01/postgresql/logfiles.go
  services/postgresql/mgmt/2017-12-01/postgresql/models.go
  services/postgresql/mgmt/2017-12-01/postgresql/operations.go
  services/postgresql/mgmt/2017-12-01/postgresql/servers.go
  services/postgresql/mgmt/2017-12-01/postgresql/serversecurityalertpolicies.go
  services/postgresql/mgmt/2017-12-01/postgresql/virtualnetworkrules.go
Labels: RestPRMerged, review

#1925 [AutoPR] machinelearningservices/resource-manager
  profiles/preview/preview/machinelearning/mgmt/services/models.go
  services/preview/machinelearning/mgmt/2018-03-01-preview/services/client.go
  services/preview/machinelearning/mgmt/2018-03-01-preview/services/machinelearningcompute.go
  services/preview/machinelearning/mgmt/2018-03-01-preview/services/models.go
  services/preview/machinelearning/mgmt/2018-03-01-preview/services/operations.go
  services/preview/machinelearning/mgmt/2018-03-01-preview/services/version.go
  services/preview/machinelearning/mgmt/2018-03-01-preview/services/workspaces.go
Labels: ServicePR, review
