Repository Azure/azure-sdk-for-go, pull requests merged in 2018-11, with the labels that each got.

#3201 [AutoPR] cosmos-db/resource-manager
  services/cosmos-db/mgmt/2015-04-08/documentdb/models.go
Labels: ServicePR, review

#3202 [AutoPR web/resource-manager] Fix network trace API bugs (Retake)
  services/web/mgmt/2018-02-01/web/apps.go
  services/web/mgmt/2018-02-01/web/models.go
Labels: RestPRMerged, review

#3205 update generator to latest build
  swagger_to_sdk_config.json
Labels: review

#3206 [AutoPR storage/resource-manager] Support for SRP BlobServiceProperties API
  profiles/preview/storage/mgmt/storage/models.go
  services/storage/mgmt/2018-07-01/storage/blobservices.go
  services/storage/mgmt/2018-07-01/storage/models.go
Labels: RestPRMerged

#3207 [AutoPR] storage/resource-manager
  profiles/preview/storage/mgmt/storage/models.go
  services/storage/mgmt/2018-07-01/storage/blobservices.go
  services/storage/mgmt/2018-07-01/storage/models.go
Labels: ServicePR, review

#3211 [AutoPR containerinstance/resource-manager] Update Microsoft.Containerinstance swagger with DNSConfig and GPU
  profiles/preview/containerinstance/mgmt/containerinstance/models.go
  services/containerinstance/mgmt/2018-10-01/containerinstance/containergroups.go
  services/containerinstance/mgmt/2018-10-01/containerinstance/models.go
Labels: RestPRMerged, review

#3212 [AutoPR] containerinstance/resource-manager
  profiles/preview/containerinstance/mgmt/containerinstance/models.go
  services/containerinstance/mgmt/2018-10-01/containerinstance/containergroups.go
  services/containerinstance/mgmt/2018-10-01/containerinstance/models.go
Labels: ServicePR, review

#3216 fix regression in resource group name regex
  services/preview/resources/mgmt/2015-10-01-preview/policy/assignments.go
  services/preview/resources/mgmt/2016-09-01-preview/managedapplications/appliancedefinitions.go
  services/preview/resources/mgmt/2016-09-01-preview/managedapplications/appliances.go
  services/preview/resources/mgmt/2017-06-01-preview/policy/assignments.go
  services/resources/mgmt/2015-01-01/locks/managementlocks.go
  services/resources/mgmt/2015-11-01/resources/deploymentoperations.go
  services/resources/mgmt/2015-11-01/resources/deployments.go
  services/resources/mgmt/2015-11-01/resources/groups.go
  services/resources/mgmt/2015-11-01/resources/policyassignments.go
  services/resources/mgmt/2015-11-01/resources/resources.go
  services/resources/mgmt/2016-02-01/resources/deploymentoperations.go
  services/resources/mgmt/2016-02-01/resources/deployments.go
  services/resources/mgmt/2016-02-01/resources/groups.go
  services/resources/mgmt/2016-02-01/resources/resources.go
  services/resources/mgmt/2016-04-01/policy/assignments.go
  services/resources/mgmt/2016-07-01/resources/deploymentoperations.go
  services/resources/mgmt/2016-07-01/resources/deployments.go
  services/resources/mgmt/2016-07-01/resources/groups.go
  services/resources/mgmt/2016-07-01/resources/resources.go
  services/resources/mgmt/2016-09-01/locks/managementlocks.go
  services/resources/mgmt/2016-09-01/resources/deploymentoperations.go
  services/resources/mgmt/2016-09-01/resources/deployments.go
  services/resources/mgmt/2016-09-01/resources/groups.go
  services/resources/mgmt/2016-09-01/resources/resources.go
  services/resources/mgmt/2016-12-01/policy/assignments.go
  services/resources/mgmt/2017-05-10/resources/deploymentoperations.go
  services/resources/mgmt/2017-05-10/resources/deployments.go
  services/resources/mgmt/2017-05-10/resources/groups.go
  services/resources/mgmt/2017-05-10/resources/resources.go
  services/resources/mgmt/2017-09-01/managedapplications/applicationdefinitions.go
  services/resources/mgmt/2017-09-01/managedapplications/applications.go
  services/resources/mgmt/2018-02-01/resources/deploymentoperations.go
  services/resources/mgmt/2018-02-01/resources/deployments.go
  services/resources/mgmt/2018-02-01/resources/groups.go
  services/resources/mgmt/2018-02-01/resources/resources.go
  services/resources/mgmt/2018-03-01/policy/assignments.go
  services/resources/mgmt/2018-05-01/policy/assignments.go
  services/resources/mgmt/2018-05-01/resources/deploymentoperations.go
  services/resources/mgmt/2018-05-01/resources/deployments.go
  services/resources/mgmt/2018-05-01/resources/groups.go
  services/resources/mgmt/2018-05-01/resources/resources.go
  services/resources/mgmt/2018-06-01/managedapplications/applicationdefinitions.go
  services/resources/mgmt/2018-06-01/managedapplications/applications.go
Labels: review

#3215 [AutoPR reservations/resource-manager] Reservations RP 2018-06-01 Preview: Add new reserved resource enum type RedHat
  profiles/preview/preview/reservations/mgmt/reservations/models.go
  services/preview/reservations/mgmt/2018-06-01/reservations/client.go
  services/preview/reservations/mgmt/2018-06-01/reservations/models.go
  services/preview/reservations/mgmt/2018-06-01/reservations/operation.go
  services/preview/reservations/mgmt/2018-06-01/reservations/order.go
  services/preview/reservations/mgmt/2018-06-01/reservations/reservation.go
  services/preview/reservations/mgmt/2018-06-01/reservations/version.go
Labels: RestPRMerged

#3221 [AutoPR visualstudio/resource-manager] Added patch API to swagger doc in Visual studio RP
  profiles/preview/preview/visualstudio/mgmt/visualstudio/models.go
  services/preview/visualstudio/mgmt/2014-04-01-preview/visualstudio/accounts.go
  services/preview/visualstudio/mgmt/2014-04-01-preview/visualstudio/models.go
Labels: review

#3219 [AutoPR containerregistry/resource-manager] ACR: Add contextAccessToken to Task step
  services/containerregistry/mgmt/2018-09-01/containerregistry/models.go
Labels: RestPRMerged, review

#3224 [AutoPR domainservices/resource-manager] Domain Services Swagger: Fix Put and Patch Domain Service Input
  profiles/latest/domainservices/mgmt/aad/models.go
  profiles/preview/domainservices/mgmt/aad/models.go
  services/domainservices/mgmt/2017-01-01/aad/domainservices.go
  services/domainservices/mgmt/2017-01-01/aad/models.go
  services/domainservices/mgmt/2017-06-01/aad/domainservices.go
  services/domainservices/mgmt/2017-06-01/aad/models.go
Labels: RestPRMerged, review

#3218 [AutoPR] reservations/resource-manager
  profiles/preview/preview/reservations/mgmt/reservations/models.go
  services/preview/reservations/mgmt/2018-06-01/reservations/client.go
  services/preview/reservations/mgmt/2018-06-01/reservations/models.go
  services/preview/reservations/mgmt/2018-06-01/reservations/operation.go
  services/preview/reservations/mgmt/2018-06-01/reservations/order.go
  services/preview/reservations/mgmt/2018-06-01/reservations/reservation.go
  services/preview/reservations/mgmt/2018-06-01/reservations/version.go
Labels: ServicePR, review

#3222 [AutoPR] visualstudio/resource-manager
  profiles/preview/preview/visualstudio/mgmt/visualstudio/models.go
  services/preview/visualstudio/mgmt/2014-04-01-preview/visualstudio/accounts.go
  services/preview/visualstudio/mgmt/2014-04-01-preview/visualstudio/models.go
Labels: ServicePR, review

#3223 [AutoPR] containerregistry/resource-manager
  services/containerregistry/mgmt/2018-09-01/containerregistry/models.go
Labels: ServicePR, review

#3226 [AutoPR datamigration/resource-manager] add datamigration tags to Go SDK build
  profiles/preview/datamigration/mgmt/datamigration/models.go
  profiles/preview/preview/datamigration/mgmt/datamigration/models.go
  services/datamigration/mgmt/2018-04-19/datamigration/client.go
  services/datamigration/mgmt/2018-04-19/datamigration/models.go
  services/datamigration/mgmt/2018-04-19/datamigration/operations.go
  services/datamigration/mgmt/2018-04-19/datamigration/projects.go
  services/datamigration/mgmt/2018-04-19/datamigration/resourceskus.go
  services/datamigration/mgmt/2018-04-19/datamigration/services.go
  services/datamigration/mgmt/2018-04-19/datamigration/tasks.go
  services/datamigration/mgmt/2018-04-19/datamigration/usages.go
  services/datamigration/mgmt/2018-04-19/datamigration/version.go
  services/preview/datamigration/mgmt/2018-07-15-preview/datamigration/client.go
  services/preview/datamigration/mgmt/2018-07-15-preview/datamigration/files.go
  services/preview/datamigration/mgmt/2018-07-15-preview/datamigration/models.go
  services/preview/datamigration/mgmt/2018-07-15-preview/datamigration/operations.go
  services/preview/datamigration/mgmt/2018-07-15-preview/datamigration/projects.go
  services/preview/datamigration/mgmt/2018-07-15-preview/datamigration/resourceskus.go
  services/preview/datamigration/mgmt/2018-07-15-preview/datamigration/services.go
  services/preview/datamigration/mgmt/2018-07-15-preview/datamigration/tasks.go
  services/preview/datamigration/mgmt/2018-07-15-preview/datamigration/usages.go
  services/preview/datamigration/mgmt/2018-07-15-preview/datamigration/version.go
Labels: RestPRMerged, review

#3227 [AutoPR] datamigration/resource-manager
  profiles/preview/datamigration/mgmt/datamigration/models.go
  profiles/preview/preview/datamigration/mgmt/datamigration/models.go
  services/datamigration/mgmt/2018-04-19/datamigration/client.go
  services/datamigration/mgmt/2018-04-19/datamigration/models.go
  services/datamigration/mgmt/2018-04-19/datamigration/operations.go
  services/datamigration/mgmt/2018-04-19/datamigration/projects.go
  services/datamigration/mgmt/2018-04-19/datamigration/resourceskus.go
  services/datamigration/mgmt/2018-04-19/datamigration/services.go
  services/datamigration/mgmt/2018-04-19/datamigration/tasks.go
  services/datamigration/mgmt/2018-04-19/datamigration/usages.go
  services/datamigration/mgmt/2018-04-19/datamigration/version.go
  services/preview/datamigration/mgmt/2018-07-15-preview/datamigration/client.go
  services/preview/datamigration/mgmt/2018-07-15-preview/datamigration/files.go
  services/preview/datamigration/mgmt/2018-07-15-preview/datamigration/models.go
  services/preview/datamigration/mgmt/2018-07-15-preview/datamigration/operations.go
  services/preview/datamigration/mgmt/2018-07-15-preview/datamigration/projects.go
  services/preview/datamigration/mgmt/2018-07-15-preview/datamigration/resourceskus.go
  services/preview/datamigration/mgmt/2018-07-15-preview/datamigration/services.go
  services/preview/datamigration/mgmt/2018-07-15-preview/datamigration/tasks.go
  services/preview/datamigration/mgmt/2018-07-15-preview/datamigration/usages.go
  services/preview/datamigration/mgmt/2018-07-15-preview/datamigration/version.go
Labels: ServicePR, review

#3232 [AutoPR cognitiveservices/data-plane/VisualSearch] enable swagger-to-sdk in visual search for Go SDK
  services/preview/cognitiveservices/v1.0/visualsearch/models.go
Labels: RestPRMerged, review

#3238 [AutoPR datamigration/resource-manager] Fix Version value to fix Ruby SDK Generation
  services/preview/datamigration/mgmt/2018-07-15-preview/datamigration/client.go
Labels: RestPRMerged, review

#3236 [AutoPR] cognitiveservices/data-plane/VisualSearch
  services/preview/cognitiveservices/v1.0/visualsearch/models.go
Labels: ServicePR, review

#3239 [AutoPR] datamigration/resource-manager
  services/preview/datamigration/mgmt/2018-07-15-preview/datamigration/client.go
Labels: ServicePR, review

#3241 [AutoPR network/resource-manager] Add java multi api versions for network
  services/network/mgmt/2018-08-01/network/virtualnetworks.go
Labels: RestPRMerged, review

#3235 [AutoPR authorization/resource-manager] Grlin/adding principal typeto ra
  services/preview/authorization/mgmt/2018-01-01-preview/authorization/classicadministrators.go
  services/preview/authorization/mgmt/2018-01-01-preview/authorization/client.go
  services/preview/authorization/mgmt/2018-01-01-preview/authorization/permissions.go
  services/preview/authorization/mgmt/2018-01-01-preview/authorization/provideroperationsmetadata.go
  services/preview/authorization/mgmt/2018-01-01-preview/authorization/roleassignments.go
  services/preview/authorization/mgmt/2018-01-01-preview/authorization/roledefinitions.go
  services/preview/authorization/mgmt/2018-09-01-preview/authorization/permissions.go
  services/preview/authorization/mgmt/2018-09-01-preview/authorization/provideroperationsmetadata.go
  services/preview/authorization/mgmt/2018-09-01-preview/authorization/roledefinitions.go
Labels: RestPRMerged, review

#3240 update swagger->sdk to latest generator
  swagger_to_sdk_config.json
Labels: review

#3245 [AutoPR sql/resource-manager] Fix blob auditing documentation
  profiles/preview/preview/sql/mgmt/sql/models.go
  services/preview/sql/mgmt/2015-05-01-preview/sql/models.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/databasevulnerabilityassessments.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/models.go
  services/preview/sql/mgmt/2017-10-01-preview/sql/manageddatabasevulnerabilityassessments.go
  services/preview/sql/mgmt/2017-10-01-preview/sql/models.go
Labels: RestPRMerged, review

#3225 [AutoPR] domainservices/resource-manager
  profiles/latest/domainservices/mgmt/aad/models.go
  profiles/preview/domainservices/mgmt/aad/models.go
  services/domainservices/mgmt/2017-01-01/aad/domainservices.go
  services/domainservices/mgmt/2017-01-01/aad/models.go
  services/domainservices/mgmt/2017-06-01/aad/domainservices.go
  services/domainservices/mgmt/2017-06-01/aad/models.go
Labels: ServicePR, review

#3242 [AutoPR] network/resource-manager
  services/network/mgmt/2018-08-01/network/virtualnetworks.go
Labels: ServicePR, review

#3254 [AutoPR sql/resource-manager] Managed Instance short term retention
  services/preview/sql/mgmt/2017-03-01-preview/sql/managedbackupshorttermretentionpolicies.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/models.go
Labels: RestPRMerged, review

#3250 [AutoPR authorization/resource-manager] remove duplicate entry for Go SDK build
  services/preview/authorization/mgmt/2018-01-01-preview/authorization/classicadministrators.go
  services/preview/authorization/mgmt/2018-01-01-preview/authorization/client.go
  services/preview/authorization/mgmt/2018-01-01-preview/authorization/permissions.go
  services/preview/authorization/mgmt/2018-01-01-preview/authorization/provideroperationsmetadata.go
  services/preview/authorization/mgmt/2018-01-01-preview/authorization/roleassignments.go
  services/preview/authorization/mgmt/2018-01-01-preview/authorization/roledefinitions.go
  services/preview/authorization/mgmt/2018-09-01-preview/authorization/permissions.go
  services/preview/authorization/mgmt/2018-09-01-preview/authorization/provideroperationsmetadata.go
  services/preview/authorization/mgmt/2018-09-01-preview/authorization/roledefinitions.go
Labels: RestPRMerged, review

#3265 [AutoPR migrateprojects/resource-manager] Swagger closure for Azure Migration Hub Operations
  profiles/preview/preview/migrate/mgmt/migrate/models.go
  services/preview/migrate/mgmt/2018-09-01-preview/migrate/client.go
  services/preview/migrate/mgmt/2018-09-01-preview/migrate/errors.go
  services/preview/migrate/mgmt/2018-09-01-preview/migrate/machines.go
  services/preview/migrate/mgmt/2018-09-01-preview/migrate/models.go
  services/preview/migrate/mgmt/2018-09-01-preview/migrate/operations.go
  services/preview/migrate/mgmt/2018-09-01-preview/migrate/projects.go
  services/preview/migrate/mgmt/2018-09-01-preview/migrate/solutions.go
  services/preview/migrate/mgmt/2018-09-01-preview/migrate/version.go
Labels: RestPRMerged, review

#3268 [AutoPR web/resource-manager] WebApps: Snapshots API for DR stamps
  services/web/mgmt/2018-02-01/web/apps.go
  services/web/mgmt/2018-02-01/web/models.go
Labels: RestPRMerged, review

#3266 [AutoPR] migrateprojects/resource-manager
  profiles/preview/preview/migrate/mgmt/migrate/models.go
  services/preview/migrate/mgmt/2018-09-01-preview/migrate/client.go
  services/preview/migrate/mgmt/2018-09-01-preview/migrate/errors.go
  services/preview/migrate/mgmt/2018-09-01-preview/migrate/machines.go
  services/preview/migrate/mgmt/2018-09-01-preview/migrate/models.go
  services/preview/migrate/mgmt/2018-09-01-preview/migrate/operations.go
  services/preview/migrate/mgmt/2018-09-01-preview/migrate/projects.go
  services/preview/migrate/mgmt/2018-09-01-preview/migrate/solutions.go
  services/preview/migrate/mgmt/2018-09-01-preview/migrate/version.go
Labels: ServicePR, review

#3273 [AutoPR security/resource-manager] Add Allowed Connections REST API
  profiles/preview/preview/security/mgmt/security/models.go
  services/preview/security/mgmt/2017-08-01-preview/security/allowedconnections.go
  services/preview/security/mgmt/2017-08-01-preview/security/models.go
Labels: RestPRMerged, review

#3260 [AutoPR containerinstance/resource-manager] Azure Container Instance: Add start container group API
  profiles/preview/containerinstance/mgmt/containerinstance/models.go
  services/containerinstance/mgmt/2018-10-01/containerinstance/containergroups.go
  services/containerinstance/mgmt/2018-10-01/containerinstance/models.go
Labels: RestPRMerged, review

#3276 update swagger->sdk code generator
  swagger_to_sdk_config.json
Labels: review

#3277 Fix sdk tracing env variable
  Gopkg.lock
  Gopkg.toml
  README.md
Labels: review

#3278 update swagger->sdk generator to latest version
  swagger_to_sdk_config.json
  tools/profileBuilder/model/transforms.go
Labels: review

#3280 [AutoPR web/resource-manager] Add GeoRegion property to DeletedSite model
  services/web/mgmt/2018-02-01/web/models.go
Labels: RestPRMerged, review

#3289 [AutoPR storage/resource-manager] Adds storage account Quick Failover API
  profiles/2017-03-09/network/mgmt/network/models.go
  profiles/latest/network/mgmt/network/models.go
  profiles/preview/network/mgmt/network/models.go
  profiles/preview/preview/network/mgmt/network/models.go
  profiles/preview/storage/mgmt/storage/models.go
  services/preview/storage/mgmt/2015-05-01-preview/storage/models.go
  services/preview/storage/mgmt/2015-05-01-preview/storage/storageapi/interfaces.go
  services/preview/storage/mgmt/2018-03-01-preview/storage/storageapi/interfaces.go
  services/storage/mgmt/2015-06-15/storage/storageapi/interfaces.go
  services/storage/mgmt/2016-01-01/storage/storageapi/interfaces.go
  services/storage/mgmt/2016-05-01/storage/storageapi/interfaces.go
  services/storage/mgmt/2016-12-01/storage/storageapi/interfaces.go
  services/storage/mgmt/2017-06-01/storage/storageapi/interfaces.go
  services/storage/mgmt/2017-10-01/storage/storageapi/interfaces.go
  services/storage/mgmt/2018-02-01/storage/storageapi/interfaces.go
  services/storage/mgmt/2018-07-01/storage/accounts.go
  services/storage/mgmt/2018-07-01/storage/models.go
  services/storage/mgmt/2018-07-01/storage/storageapi/interfaces.go
Labels: RestPRMerged, review

#3299 [AutoPR datalake-store/data-plane] Add maximum chunk size to data lake store docs.
  profiles/2017-03-09/network/mgmt/network/models.go
  profiles/latest/network/mgmt/network/models.go
  profiles/preview/network/mgmt/network/models.go
  profiles/preview/preview/network/mgmt/network/models.go
  services/datalake/store/2016-11-01/filesystem/filesystem.go
  services/datalake/store/2016-11-01/filesystem/filesystemapi/interfaces.go
  services/preview/datalake/store/2015-10-01-preview/filesystem/filesystem.go
  services/preview/datalake/store/2015-10-01-preview/filesystem/filesystemapi/interfaces.go
Labels: RestPRInProgress, review

#3301 [AutoPR datalake-store/data-plane] Add maximum chunk size to data lake store docs.
  services/preview/datalake/store/2015-10-01-preview/filesystem/filesystem.go
Labels: RestPRMerged, review

#3305 Remove migrate service as it's not live
  profiles/preview/preview/migrate/mgmt/migrate/migrateapi/models.go
  profiles/preview/preview/migrate/mgmt/migrate/models.go
  services/preview/migrate/mgmt/2018-09-01-preview/migrate/client.go
  services/preview/migrate/mgmt/2018-09-01-preview/migrate/errors.go
  services/preview/migrate/mgmt/2018-09-01-preview/migrate/machines.go
  services/preview/migrate/mgmt/2018-09-01-preview/migrate/migrateapi/interfaces.go
  services/preview/migrate/mgmt/2018-09-01-preview/migrate/models.go
  services/preview/migrate/mgmt/2018-09-01-preview/migrate/operations.go
  services/preview/migrate/mgmt/2018-09-01-preview/migrate/projects.go
  services/preview/migrate/mgmt/2018-09-01-preview/migrate/solutions.go
  services/preview/migrate/mgmt/2018-09-01-preview/migrate/version.go
Labels: review

#3309 [AutoPR storage/resource-manager] Adds Geo Replication Stats in Azure Storage Account's properties
  profiles/preview/storage/mgmt/storage/models.go
  services/storage/mgmt/2018-07-01/storage/accounts.go
  services/storage/mgmt/2018-07-01/storage/models.go
  services/storage/mgmt/2018-07-01/storage/storageapi/interfaces.go
Labels: RestPRMerged, review

#3310 [AutoPR] storage/resource-manager
  profiles/preview/storage/mgmt/storage/models.go
  services/storage/mgmt/2018-07-01/storage/accounts.go
  services/storage/mgmt/2018-07-01/storage/models.go
  services/storage/mgmt/2018-07-01/storage/storageapi/interfaces.go
Labels: ServicePR, review

#3311 [AutoPR] logic/resource-manager
  profiles/latest/logic/mgmt/logic/models.go
  profiles/preview/logic/mgmt/logic/logicapi/models.go
  profiles/preview/logic/mgmt/logic/models.go
  profiles/preview/preview/logic/mgmt/logic/logicapi/models.go
  profiles/preview/preview/logic/mgmt/logic/models.go
  services/logic/mgmt/2016-06-01/logic/logicapi/interfaces.go
  services/logic/mgmt/2016-06-01/logic/models.go
  services/logic/mgmt/2016-06-01/logic/workflowrunactionrepetitionsrequesthistories.go
  services/logic/mgmt/2016-06-01/logic/workflowrunactionrequesthistories.go
  services/preview/logic/mgmt/2018-07-01-preview/logic/logicapi/interfaces.go
  services/preview/logic/mgmt/2018-07-01-preview/logic/models.go
  services/preview/logic/mgmt/2018-07-01-preview/logic/workflowrunactionrepetitionsrequesthistories.go
  services/preview/logic/mgmt/2018-07-01-preview/logic/workflowrunactionrequesthistories.go
Labels: ServicePR, review

#3316 update swagger->sdk to latest generator
  swagger_to_sdk_config.json
Labels: review

#3319 [AutoPR hdinsight/resource-manager] [HDInsight] - Support KV URL
  profiles/preview/preview/hdinsight/mgmt/hdinsight/models.go
  services/preview/hdinsight/mgmt/2015-03-01-preview/hdinsight/clusters.go
  services/preview/hdinsight/mgmt/2015-03-01-preview/hdinsight/hdinsightapi/interfaces.go
  services/preview/hdinsight/mgmt/2015-03-01-preview/hdinsight/models.go
  services/preview/hdinsight/mgmt/2018-06-01-preview/hdinsight/clusters.go
  services/preview/hdinsight/mgmt/2018-06-01-preview/hdinsight/hdinsightapi/interfaces.go
  services/preview/hdinsight/mgmt/2018-06-01-preview/hdinsight/models.go
Labels: RestPRMerged, review

#3315 [AutoPR cognitiveservices/data-plane/AutoSuggest] Description of Autosuggest usage needs improvement.
  services/cognitiveservices/v1.0/autosuggest/client.go
Labels: RestPRMerged, review

#3320 [AutoPR] hdinsight/resource-manager
  profiles/preview/preview/hdinsight/mgmt/hdinsight/models.go
  services/preview/hdinsight/mgmt/2015-03-01-preview/hdinsight/clusters.go
  services/preview/hdinsight/mgmt/2015-03-01-preview/hdinsight/hdinsightapi/interfaces.go
  services/preview/hdinsight/mgmt/2015-03-01-preview/hdinsight/models.go
  services/preview/hdinsight/mgmt/2018-06-01-preview/hdinsight/clusters.go
  services/preview/hdinsight/mgmt/2018-06-01-preview/hdinsight/hdinsightapi/interfaces.go
  services/preview/hdinsight/mgmt/2018-06-01-preview/hdinsight/models.go
Labels: ServicePR, review

#3321 [AutoPR] cognitiveservices/data-plane/AutoSuggest
  services/cognitiveservices/v1.0/autosuggest/client.go
Labels: ServicePR, review

#3327 [AutoPR storagesync/resource-manager] Microsoft.StorageSync : Update ApiVersion 2018-10-01
  profiles/preview/preview/storagesync/mgmt/storagesync/models.go
  services/preview/storagesync/mgmt/2018-10-01/storagesync/models.go
Labels: RestPRMerged

#3329 [AutoPR blueprint/resource-manager] split swagger to multiple area for easy upgrade
  profiles/preview/preview/blueprint/mgmt/blueprint/blueprintapi/models.go
  services/preview/blueprint/mgmt/2017-11-11-preview/blueprint/blueprintapi/interfaces.go
Labels: RestPRMerged, review

#3331 [AutoPR engagementfabric/resource-manager] Add new resource provider Microsoft.EngagementFabric
  services/preview/engagementfabric/mgmt/2018-09-preview/engagementfabric/accounts.go
  services/preview/engagementfabric/mgmt/2018-09-preview/engagementfabric/channels.go
  services/preview/engagementfabric/mgmt/2018-09-preview/engagementfabric/client.go
  services/preview/engagementfabric/mgmt/2018-09-preview/engagementfabric/engagementfabricapi/interfaces.go
  services/preview/engagementfabric/mgmt/2018-09-preview/engagementfabric/models.go
  services/preview/engagementfabric/mgmt/2018-09-preview/engagementfabric/operations.go
  services/preview/engagementfabric/mgmt/2018-09-preview/engagementfabric/skus.go
  services/preview/engagementfabric/mgmt/2018-09-preview/engagementfabric/version.go
Labels: RestPRMerged, review

#3314 [AutoPR cognitiveservices/data-plane/QnAMaker] Adding API For QnAMaker v4.0
  profiles/preview/cognitiveservices/qnamaker/models.go
  profiles/preview/cognitiveservices/qnamaker/qnamakerapi/models.go
  services/cognitiveservices/v4.0/qnamaker/alterations.go
  services/cognitiveservices/v4.0/qnamaker/client.go
  services/cognitiveservices/v4.0/qnamaker/endpoint.go
  services/cognitiveservices/v4.0/qnamaker/knowledgebase.go
  services/cognitiveservices/v4.0/qnamaker/models.go
  services/cognitiveservices/v4.0/qnamaker/operations.go
  services/cognitiveservices/v4.0/qnamaker/qnamakerapi/interfaces.go
  services/cognitiveservices/v4.0/qnamaker/version.go
Labels: RestPRMerged, review

#3323 [AutoPR] datamigration/resource-manager
  services/preview/datamigration/mgmt/2018-07-15-preview/datamigration/models.go
Labels: ServicePR, review

#3328 [AutoPR] storagesync/resource-manager
  profiles/preview/preview/storagesync/mgmt/storagesync/models.go
  services/preview/storagesync/mgmt/2018-10-01/storagesync/models.go
Labels: ServicePR, review

#3330 [AutoPR] blueprint/resource-manager
  profiles/preview/preview/blueprint/mgmt/blueprint/blueprintapi/models.go
  services/preview/blueprint/mgmt/2017-11-11-preview/blueprint/blueprintapi/interfaces.go
Labels: ServicePR, review

#3333 [AutoPR] cognitiveservices/data-plane/QnAMaker
  profiles/preview/cognitiveservices/qnamaker/models.go
  profiles/preview/cognitiveservices/qnamaker/qnamakerapi/models.go
  services/cognitiveservices/v4.0/qnamaker/alterations.go
  services/cognitiveservices/v4.0/qnamaker/client.go
  services/cognitiveservices/v4.0/qnamaker/endpoint.go
  services/cognitiveservices/v4.0/qnamaker/knowledgebase.go
  services/cognitiveservices/v4.0/qnamaker/models.go
  services/cognitiveservices/v4.0/qnamaker/operations.go
  services/cognitiveservices/v4.0/qnamaker/qnamakerapi/interfaces.go
  services/cognitiveservices/v4.0/qnamaker/version.go
Labels: ServicePR, review

#3335 [AutoPR engagementfabric/resource-manager] fix Go SDK codegen for engagementfabric
  profiles/preview/preview/engagementfabric/mgmt/engagementfabric/engagementfabricapi/models.go
  profiles/preview/preview/engagementfabric/mgmt/engagementfabric/models.go
  services/preview/engagementfabric/mgmt/2018-09-01/engagementfabric/accounts.go
  services/preview/engagementfabric/mgmt/2018-09-01/engagementfabric/channels.go
  services/preview/engagementfabric/mgmt/2018-09-01/engagementfabric/client.go
  services/preview/engagementfabric/mgmt/2018-09-01/engagementfabric/engagementfabricapi/interfaces.go
  services/preview/engagementfabric/mgmt/2018-09-01/engagementfabric/models.go
  services/preview/engagementfabric/mgmt/2018-09-01/engagementfabric/operations.go
  services/preview/engagementfabric/mgmt/2018-09-01/engagementfabric/skus.go
  services/preview/engagementfabric/mgmt/2018-09-01/engagementfabric/version.go
Labels: RestPRMerged, review

#3349 [AutoPR cdn/resource-manager] typo: cdn/resource-manager/Microsoft.Cdn/cdn.json
  services/cdn/mgmt/2016-10-02/cdn/customdomains.go
  services/cdn/mgmt/2016-10-02/cdn/endpoints.go
  services/cdn/mgmt/2016-10-02/cdn/models.go
  services/cdn/mgmt/2016-10-02/cdn/profiles.go
  services/cdn/mgmt/2017-04-02/cdn/customdomains.go
  services/cdn/mgmt/2017-04-02/cdn/endpoints.go
  services/cdn/mgmt/2017-04-02/cdn/models.go
  services/cdn/mgmt/2017-04-02/cdn/profiles.go
  services/cdn/mgmt/2017-10-12/cdn/customdomains.go
  services/cdn/mgmt/2017-10-12/cdn/endpoints.go
  services/cdn/mgmt/2017-10-12/cdn/models.go
  services/cdn/mgmt/2017-10-12/cdn/profiles.go
Labels: RestPRMerged, review

#3352 [AutoPR] cdn/resource-manager
  services/cdn/mgmt/2016-10-02/cdn/customdomains.go
  services/cdn/mgmt/2016-10-02/cdn/endpoints.go
  services/cdn/mgmt/2016-10-02/cdn/models.go
  services/cdn/mgmt/2016-10-02/cdn/profiles.go
  services/cdn/mgmt/2017-04-02/cdn/customdomains.go
  services/cdn/mgmt/2017-04-02/cdn/endpoints.go
  services/cdn/mgmt/2017-04-02/cdn/models.go
  services/cdn/mgmt/2017-04-02/cdn/profiles.go
  services/cdn/mgmt/2017-10-12/cdn/customdomains.go
  services/cdn/mgmt/2017-10-12/cdn/endpoints.go
  services/cdn/mgmt/2017-10-12/cdn/models.go
  services/cdn/mgmt/2017-10-12/cdn/profiles.go
Labels: ServicePR, review

#3355 Generated from c757b7600abc32b49013fb661fc148ce46a10d2d
  profiles/preview/preview/kusto/mgmt/kusto/kustoapi/models.go
  profiles/preview/preview/kusto/mgmt/kusto/models.go
  services/preview/kusto/mgmt/2018-09-07-preview/kusto/client.go
  services/preview/kusto/mgmt/2018-09-07-preview/kusto/clusters.go
  services/preview/kusto/mgmt/2018-09-07-preview/kusto/databases.go
  services/preview/kusto/mgmt/2018-09-07-preview/kusto/eventhubconnections.go
  services/preview/kusto/mgmt/2018-09-07-preview/kusto/kustoapi/interfaces.go
  services/preview/kusto/mgmt/2018-09-07-preview/kusto/models.go
  services/preview/kusto/mgmt/2018-09-07-preview/kusto/operations.go
  services/preview/kusto/mgmt/2018-09-07-preview/kusto/version.go
Labels: review

#3347 [AutoPR cosmos-db/resource-manager] typo: cosmos-db/resource-manager/Microsoft.DocumentDB/cosmos-db.json
  services/cosmos-db/mgmt/2015-04-08/documentdb/collection.go
  services/cosmos-db/mgmt/2015-04-08/documentdb/database.go
  services/cosmos-db/mgmt/2015-04-08/documentdb/models.go
Labels: RestPRMerged, review

#3356 [AutoPR authorization/resource-manager] Grlin/adding principal typeto ra
  services/preview/authorization/mgmt/2018-09-01-preview/authorization/models.go
Labels: RestPRMerged, review

#3358 [AutoPR] authorization/resource-manager
  services/preview/authorization/mgmt/2018-09-01-preview/authorization/models.go
Labels: ServicePR, review

#3357 [AutoPR] cosmos-db/resource-manager
  services/cosmos-db/mgmt/2015-04-08/documentdb/collection.go
  services/cosmos-db/mgmt/2015-04-08/documentdb/database.go
  services/cosmos-db/mgmt/2015-04-08/documentdb/models.go
Labels: ServicePR, review

#3354 [AutoPR network/resource-manager] Application gateway Identity and Keyvault support
  profiles/preview/network/mgmt/network/models.go
  services/network/mgmt/2018-10-01/network/models.go
Labels: RestPRMerged, review

#3344 [AutoPR apimanagement/resource-manager] typo: Fix apimanagement/resource-manager/Microsoft.ApiManagement/apimbackends.json
  profiles/preview/apimanagement/mgmt/apimanagement/models.go
  profiles/preview/preview/apimanagement/mgmt/apimanagement/models.go
  services/apimanagement/mgmt/2017-03-01/apimanagement/models.go
  services/apimanagement/mgmt/2018-01-01/apimanagement/apiissue.go
  services/apimanagement/mgmt/2018-01-01/apimanagement/apimanagementapi/interfaces.go
  services/apimanagement/mgmt/2018-01-01/apimanagement/models.go
  services/apimanagement/mgmt/2018-01-01/apimanagement/user.go
  services/preview/apimanagement/mgmt/2018-06-01-preview/apimanagement/apiissue.go
  services/preview/apimanagement/mgmt/2018-06-01-preview/apimanagement/apimanagementapi/interfaces.go
  services/preview/apimanagement/mgmt/2018-06-01-preview/apimanagement/models.go
  services/preview/apimanagement/mgmt/2018-06-01-preview/apimanagement/user.go
Labels: RestPRMerged, review

#3339 [AutoPR web/resource-manager] typo: Fix Microsoft.Web/CommonDefinitions.json
  services/web/mgmt/2016-09-01/web/models.go
  services/web/mgmt/2018-02-01/web/models.go
Labels: RestPRMerged, review

#3346 [AutoPR iothub/resource-manager] typo: iothub/resource-manager/Microsoft.Devices/iothub.json
  services/iothub/mgmt/2016-02-03/devices/models.go
  services/iothub/mgmt/2017-01-19/devices/models.go
Labels: RestPRMerged, review

#3361 [AutoPR] apimanagement/resource-manager
  profiles/preview/apimanagement/mgmt/apimanagement/models.go
  profiles/preview/preview/apimanagement/mgmt/apimanagement/models.go
  services/apimanagement/mgmt/2017-03-01/apimanagement/models.go
  services/apimanagement/mgmt/2018-01-01/apimanagement/apiissue.go
  services/apimanagement/mgmt/2018-01-01/apimanagement/apimanagementapi/interfaces.go
  services/apimanagement/mgmt/2018-01-01/apimanagement/models.go
  services/apimanagement/mgmt/2018-01-01/apimanagement/user.go
  services/preview/apimanagement/mgmt/2018-06-01-preview/apimanagement/apiissue.go
  services/preview/apimanagement/mgmt/2018-06-01-preview/apimanagement/apimanagementapi/interfaces.go
  services/preview/apimanagement/mgmt/2018-06-01-preview/apimanagement/models.go
  services/preview/apimanagement/mgmt/2018-06-01-preview/apimanagement/user.go
Labels: ServicePR, review

#3364 [AutoPR databox/resource-manager] DataBox : Swagger and example changes for next version of client DLL
  profiles/preview/databox/mgmt/databox/models.go
  services/databox/mgmt/2018-01-01/databox/models.go
Labels: RestPRMerged, review

#3370 [AutoPR storage/resource-manager] Adds canFailover boolean flag under storage account's GeoReplicationS…
  services/storage/mgmt/2018-07-01/storage/models.go
Labels: RestPRMerged, review

#3366 [AutoPR web/resource-manager] typo: web/resource-manager/Microsoft.Web/AppServiceEnvironments
  services/web/mgmt/2016-09-01/web/models.go
  services/web/mgmt/2018-02-01/web/models.go
Labels: RestPRMerged, review

#3350 [AutoPR customer-insights/resource-manager] typo: Fix customer-insights/resource-manager/Microsoft.CustomerInsights/customer-insights
  services/customerinsights/mgmt/2017-01-01/customerinsights/models.go
  services/customerinsights/mgmt/2017-01-01/customerinsights/views.go
  services/customerinsights/mgmt/2017-04-26/customerinsights/models.go
  services/customerinsights/mgmt/2017-04-26/customerinsights/views.go
Labels: RestPRMerged, review

#3374 [AutoPR policyinsights/resource-manager] typo: policyinsights/resource-manager/Microsoft.PolicyInsights/policyEvents
  services/policyinsights/mgmt/2018-04-04/policyinsights/models.go
  services/preview/policyinsights/mgmt/2017-08-09-preview/policyinsights/models.go
  services/preview/policyinsights/mgmt/2017-10-17-preview/policyinsights/models.go
  services/preview/policyinsights/mgmt/2017-12-12-preview/policyinsights/models.go
  services/preview/policyinsights/mgmt/2018-07-01-preview/policyinsights/models.go
Labels: RestPRMerged, review

#3381 [AutoPR network/resource-manager] Ported fix from master branch
  services/network/mgmt/2018-08-01/network/networkapi/interfaces.go
  services/network/mgmt/2018-08-01/network/virtualnetworks.go
  services/network/mgmt/2018-10-01/network/networkapi/interfaces.go
  services/network/mgmt/2018-10-01/network/virtualnetworks.go
Labels: RestPRMerged, review

#3380 [AutoPR batchai/resource-manager] typo: batchai/resource-manager/Microsoft.BatchAI/BatchAI
  services/batchai/mgmt/2018-03-01/batchai/clusters.go
  services/batchai/mgmt/2018-03-01/batchai/fileservers.go
  services/batchai/mgmt/2018-03-01/batchai/jobs.go
  services/batchai/mgmt/2018-03-01/batchai/models.go
  services/batchai/mgmt/2018-05-01/batchai/models.go
  services/preview/batchai/mgmt/2017-09-01-preview/batchai/clusters.go
  services/preview/batchai/mgmt/2017-09-01-preview/batchai/fileservers.go
  services/preview/batchai/mgmt/2017-09-01-preview/batchai/jobs.go
  services/preview/batchai/mgmt/2017-09-01-preview/batchai/models.go
Labels: RestPRMerged, review

#3377 [AutoPR datalake-store/data-plane] typo: datalake-store/data-plane/Microsoft.DataLakeStore/filesystem
  services/datalake/store/2016-11-01/filesystem/filesystem.go
  services/preview/datalake/store/2015-10-01-preview/filesystem/filesystem.go
  services/preview/datalake/store/2015-10-01-preview/filesystem/models.go
Labels: RestPRMerged, review

#3367 [AutoPR servicefabric/data-plane] typo: servicefabric/data-plane/Microsoft.ServiceFabric/servicefabric
  services/servicefabric/6.2/servicefabric/client.go
  services/servicefabric/6.2/servicefabric/models.go
Labels: RestPRMerged, review

#3345 [AutoPR apimanagement/control-plane] typo: apimanagement/control-plane/Microsoft.ApiManagement/apimbackends.json
  services/preview/apimanagement/ctrl/2017-03-01/apimanagement/models.go
Labels: RestPRMerged, review

#3391 [AutoPR applicationinsights/resource-manager] typo: applicationinsights/resource-manager/Microsoft.Insights/componentFeaturesAndPricing_API
  services/appinsights/mgmt/2015-05-01/insights/componentfeaturecapabilities.go
  services/appinsights/mgmt/2015-05-01/insights/models.go
Labels: RestPRMerged, review

#3390 [AutoPR storage/resource-manager] typo: storage/resource-manager/Microsoft.Storage/blob
  services/preview/storage/mgmt/2018-03-01-preview/storage/blobcontainers.go
  services/storage/mgmt/2018-02-01/storage/blobcontainers.go
  services/storage/mgmt/2018-07-01/storage/blobcontainers.go
Labels: RestPRMerged, review

#3363 [AutoPR] iothub/resource-manager
  services/iothub/mgmt/2016-02-03/devices/models.go
  services/iothub/mgmt/2017-01-19/devices/models.go
Labels: ServicePR, review

#3365 [AutoPR] databox/resource-manager
  profiles/preview/databox/mgmt/databox/models.go
  services/databox/mgmt/2018-01-01/databox/models.go
Labels: ServicePR, review

#3362 [AutoPR] web/resource-manager
  services/web/mgmt/2016-09-01/web/models.go
  services/web/mgmt/2018-02-01/web/models.go
Labels: ServicePR, review

#3375 [AutoPR] policyinsights/resource-manager
  services/policyinsights/mgmt/2018-04-04/policyinsights/models.go
  services/preview/policyinsights/mgmt/2017-08-09-preview/policyinsights/models.go
  services/preview/policyinsights/mgmt/2017-10-17-preview/policyinsights/models.go
  services/preview/policyinsights/mgmt/2017-12-12-preview/policyinsights/models.go
  services/preview/policyinsights/mgmt/2018-07-01-preview/policyinsights/models.go
Labels: ServicePR, review

#3385 [AutoPR] batchai/resource-manager
  services/batchai/mgmt/2018-03-01/batchai/clusters.go
  services/batchai/mgmt/2018-03-01/batchai/fileservers.go
  services/batchai/mgmt/2018-03-01/batchai/jobs.go
  services/batchai/mgmt/2018-03-01/batchai/models.go
  services/batchai/mgmt/2018-05-01/batchai/models.go
  services/preview/batchai/mgmt/2017-09-01-preview/batchai/clusters.go
  services/preview/batchai/mgmt/2017-09-01-preview/batchai/fileservers.go
  services/preview/batchai/mgmt/2017-09-01-preview/batchai/jobs.go
  services/preview/batchai/mgmt/2017-09-01-preview/batchai/models.go
Labels: ServicePR, review

#3387 [AutoPR] servicefabric/data-plane
  services/servicefabric/6.2/servicefabric/client.go
  services/servicefabric/6.2/servicefabric/models.go
Labels: ServicePR, review

#3396 [AutoPR] applicationinsights/resource-manager
  services/appinsights/mgmt/2015-05-01/insights/componentfeaturecapabilities.go
  services/appinsights/mgmt/2015-05-01/insights/models.go
Labels: ServicePR, review

#3372 [AutoPR] customer-insights/resource-manager
  services/customerinsights/mgmt/2017-01-01/customerinsights/models.go
  services/customerinsights/mgmt/2017-01-01/customerinsights/views.go
  services/customerinsights/mgmt/2017-04-26/customerinsights/models.go
  services/customerinsights/mgmt/2017-04-26/customerinsights/views.go
Labels: ServicePR, review

#3386 [AutoPR] datalake-store/data-plane
  services/datalake/store/2016-11-01/filesystem/filesystem.go
  services/preview/datalake/store/2015-10-01-preview/filesystem/filesystem.go
  services/preview/datalake/store/2015-10-01-preview/filesystem/models.go
Labels: ServicePR, review

#3388 [AutoPR] apimanagement/control-plane
  services/preview/apimanagement/ctrl/2017-03-01/apimanagement/models.go
Labels: ServicePR, review

#3384 [AutoPR storage/resource-manager] typo: storage/resource-manager/Microsoft.Storage/storage
  services/preview/storage/mgmt/2018-03-01-preview/storage/models.go
  services/storage/mgmt/2016-05-01/storage/models.go
  services/storage/mgmt/2016-12-01/storage/models.go
  services/storage/mgmt/2017-06-01/storage/models.go
  services/storage/mgmt/2017-10-01/storage/models.go
  services/storage/mgmt/2018-02-01/storage/models.go
  services/storage/mgmt/2018-07-01/storage/accounts.go
  services/storage/mgmt/2018-07-01/storage/models.go
Labels: RestPRInProgress, review

#3398 [AutoPR] mediaservices/resource-manager
  services/mediaservices/mgmt/2018-07-01/media/models.go
  services/preview/mediaservices/mgmt/2018-03-30-preview/media/models.go
  services/preview/mediaservices/mgmt/2018-06-01-preview/media/models.go
Labels: ServicePR, review

#3392 [AutoPR eventhub/resource-manager] typo: eventhub/resource-manager/Microsoft.EventHub/EventHub
  services/eventhub/mgmt/2017-04-01/eventhub/disasterrecoveryconfigs.go
  services/eventhub/mgmt/2017-04-01/eventhub/models.go
  services/preview/eventhub/mgmt/2018-01-01-preview/eventhub/models.go
Labels: RestPRMerged, review

#3337 [AutoPR resources/resource-manager] Add type for DeploymentExtend and ResourceGroup
  services/resources/mgmt/2018-05-01/resources/models.go
Labels: RestPRMerged, review

#3400 [AutoPR] eventhub/resource-manager
  services/eventhub/mgmt/2017-04-01/eventhub/disasterrecoveryconfigs.go
  services/eventhub/mgmt/2017-04-01/eventhub/models.go
  services/preview/eventhub/mgmt/2018-01-01-preview/eventhub/models.go
Labels: ServicePR, review

#3401 [AutoPR] resources/resource-manager
  services/resources/mgmt/2018-05-01/resources/models.go
Labels: ServicePR, review

#3402 [AutoPR] mediaservices/resource-manager
  services/mediaservices/mgmt/2018-07-01/media/models.go
  services/mediaservices/mgmt/2018-07-01/media/streaminglocators.go
  services/mediaservices/mgmt/2018-07-01/media/streamingpolicies.go
  services/preview/mediaservices/mgmt/2018-03-30-preview/media/models.go
  services/preview/mediaservices/mgmt/2018-03-30-preview/media/streaminglocators.go
  services/preview/mediaservices/mgmt/2018-03-30-preview/media/streamingpolicies.go
  services/preview/mediaservices/mgmt/2018-06-01-preview/media/models.go
  services/preview/mediaservices/mgmt/2018-06-01-preview/media/streaminglocators.go
  services/preview/mediaservices/mgmt/2018-06-01-preview/media/streamingpolicies.go
Labels: ServicePR, review

#3348 [AutoPR alertsmanagement/resource-manager] typo: alertsmanagement/resource-manager/Microsoft.AlertsManagement/AlertsManagement.json
  services/alertsmanagement/mgmt/2018-05-05/alertsmanagement/alerts.go
  services/alertsmanagement/mgmt/2018-05-05/alertsmanagement/smartgroups.go
Labels: RestPRMerged, review

#3404 [AutoPR] alertsmanagement/resource-manager
  services/alertsmanagement/mgmt/2018-05-05/alertsmanagement/alerts.go
  services/alertsmanagement/mgmt/2018-05-05/alertsmanagement/smartgroups.go
Labels: ServicePR

#3405 [AutoPR] cognitiveservices/data-plane/QnAMaker
  profiles/preview/cognitiveservices/qnamaker/models.go
  profiles/preview/cognitiveservices/qnamaker/qnamakerapi/models.go
  services/cognitiveservices/v4.0/qnamaker/endpointkeys.go
  services/cognitiveservices/v4.0/qnamaker/qnamakerapi/interfaces.go
Labels: ServicePR, review

#3411 [AutoPR adhybridhealthservice/resource-manager] Fix type-o in adhybridhealthservice model
  services/adhybridhealthservice/mgmt/2014-01-01/adhybridhealthservice/models.go
Labels: RestPRMerged, review

#3413 [AutoPR sqlvirtualmachine/resource-manager] Add Go SDK build for sqlvirtualmachine
  profiles/preview/preview/sqlvirtualmachine/mgmt/sqlvirtualmachine/models.go
  profiles/preview/preview/sqlvirtualmachine/mgmt/sqlvirtualmachine/sqlvirtualmachineapi/models.go
  services/preview/sqlvirtualmachine/mgmt/2017-03-01-preview/sqlvirtualmachine/availabilitygrouplisteners.go
  services/preview/sqlvirtualmachine/mgmt/2017-03-01-preview/sqlvirtualmachine/client.go
  services/preview/sqlvirtualmachine/mgmt/2017-03-01-preview/sqlvirtualmachine/groups.go
  services/preview/sqlvirtualmachine/mgmt/2017-03-01-preview/sqlvirtualmachine/models.go
  services/preview/sqlvirtualmachine/mgmt/2017-03-01-preview/sqlvirtualmachine/operations.go
  services/preview/sqlvirtualmachine/mgmt/2017-03-01-preview/sqlvirtualmachine/sqlvirtualmachineapi/interfaces.go
  services/preview/sqlvirtualmachine/mgmt/2017-03-01-preview/sqlvirtualmachine/sqlvirtualmachines.go
  services/preview/sqlvirtualmachine/mgmt/2017-03-01-preview/sqlvirtualmachine/version.go
Labels: RestPRMerged, review

#3412 [AutoPR] adhybridhealthservice/resource-manager
  services/adhybridhealthservice/mgmt/2014-01-01/adhybridhealthservice/models.go
Labels: ServicePR, review

#3414 [AutoPR] sqlvirtualmachine/resource-manager
  profiles/preview/preview/sqlvirtualmachine/mgmt/sqlvirtualmachine/models.go
  profiles/preview/preview/sqlvirtualmachine/mgmt/sqlvirtualmachine/sqlvirtualmachineapi/models.go
  services/preview/sqlvirtualmachine/mgmt/2017-03-01-preview/sqlvirtualmachine/availabilitygrouplisteners.go
  services/preview/sqlvirtualmachine/mgmt/2017-03-01-preview/sqlvirtualmachine/client.go
  services/preview/sqlvirtualmachine/mgmt/2017-03-01-preview/sqlvirtualmachine/groups.go
  services/preview/sqlvirtualmachine/mgmt/2017-03-01-preview/sqlvirtualmachine/models.go
  services/preview/sqlvirtualmachine/mgmt/2017-03-01-preview/sqlvirtualmachine/operations.go
  services/preview/sqlvirtualmachine/mgmt/2017-03-01-preview/sqlvirtualmachine/sqlvirtualmachineapi/interfaces.go
  services/preview/sqlvirtualmachine/mgmt/2017-03-01-preview/sqlvirtualmachine/sqlvirtualmachines.go
  services/preview/sqlvirtualmachine/mgmt/2017-03-01-preview/sqlvirtualmachine/version.go
Labels: ServicePR, review

#3342 [AutoPR graphrbac/data-plane] add customKeyIdentifier to password credential
  services/graphrbac/1.6/graphrbac/models.go
Labels: RestPRMerged, review

#3403 [AutoPR storagesync/resource-manager] Microsoft.StorageSync - Fix Issue 4559 and other known problems with preview version
  profiles/preview/preview/storagesync/mgmt/storagesync/models.go
  services/preview/storagesync/mgmt/2018-10-01/storagesync/models.go
Labels: RestPRMerged, review

#3409 [AutoPR analysisservices/resource-manager] typo: analysisservices/resource-manager/Microsoft.AnalysisServices
  services/analysisservices/mgmt/2016-05-16/analysisservices/models.go
  services/analysisservices/mgmt/2016-05-16/analysisservices/servers.go
  services/analysisservices/mgmt/2017-07-14/analysisservices/models.go
  services/analysisservices/mgmt/2017-07-14/analysisservices/servers.go
  services/analysisservices/mgmt/2017-08-01/analysisservices/models.go
  services/analysisservices/mgmt/2017-08-01/analysisservices/servers.go
Labels: RestPRMerged, review

#3406 add Slack link to README
  README.md
Labels: docs, review

#3417 [AutoPR] graphrbac/data-plane
  services/graphrbac/1.6/graphrbac/models.go
Labels: ServicePR, review

#3419 [AutoPR] analysisservices/resource-manager
  services/analysisservices/mgmt/2016-05-16/analysisservices/models.go
  services/analysisservices/mgmt/2016-05-16/analysisservices/servers.go
  services/analysisservices/mgmt/2017-07-14/analysisservices/models.go
  services/analysisservices/mgmt/2017-07-14/analysisservices/servers.go
  services/analysisservices/mgmt/2017-08-01/analysisservices/models.go
  services/analysisservices/mgmt/2017-08-01/analysisservices/servers.go
Labels: ServicePR, review

#3418 [AutoPR] storagesync/resource-manager
  profiles/preview/preview/storagesync/mgmt/storagesync/models.go
  services/preview/storagesync/mgmt/2018-10-01/storagesync/models.go
Labels: ServicePR, review

#3423 Fix packages command for apidiff tool
  tools/apidiff/cmd/packages.go
Labels: review

#3317 [AutoPR msi/resource-manager] Update manage service identity api version
  profiles/preview/msi/mgmt/msi/models.go
  profiles/preview/msi/mgmt/msi/msiapi/models.go
  services/msi/mgmt/2018-11-30/msi/client.go
  services/msi/mgmt/2018-11-30/msi/models.go
  services/msi/mgmt/2018-11-30/msi/msiapi/interfaces.go
  services/msi/mgmt/2018-11-30/msi/operations.go
  services/msi/mgmt/2018-11-30/msi/userassignedidentities.go
  services/msi/mgmt/2018-11-30/msi/version.go
Labels: RestPRMerged, review

#3338 [AutoPR web/resource-manager] typo: Fix AppServiceCertificateOrders.json
  services/web/mgmt/2016-09-01/web/appservicecertificateorders.go
  services/web/mgmt/2016-09-01/web/models.go
  services/web/mgmt/2018-02-01/web/appservicecertificateorders.go
  services/web/mgmt/2018-02-01/web/models.go
Labels: RestPRMerged

#3450 [AutoPR cdn/resource-manager] typo: Microsoft.Cdn
  services/cdn/mgmt/2016-10-02/cdn/models.go
  services/cdn/mgmt/2017-04-02/cdn/models.go
  services/cdn/mgmt/2017-10-12/cdn/models.go
Labels: RestPRMerged, review

#3449 [AutoPR botservice/resource-manager] typo: Microsoft.BotService
  services/preview/botservice/mgmt/2017-12-01/botservice/models.go
  services/preview/botservice/mgmt/2018-07-12/botservice/models.go
Labels: RestPRMerged

#3341 [AutoPR containerregistry/resource-manager] [ACR] Add empty resource group name validation, minor cleanup
  profiles/latest/containerregistry/mgmt/containerregistry/models.go
  profiles/preview/containerregistry/mgmt/containerregistry/models.go
  profiles/preview/preview/containerregistry/mgmt/containerregistry/models.go
  services/containerregistry/mgmt/2017-03-01/containerregistry/registries.go
  services/containerregistry/mgmt/2017-10-01/containerregistry/models.go
  services/containerregistry/mgmt/2017-10-01/containerregistry/registries.go
  services/containerregistry/mgmt/2017-10-01/containerregistry/replications.go
  services/containerregistry/mgmt/2017-10-01/containerregistry/webhooks.go
  services/containerregistry/mgmt/2018-09-01/containerregistry/models.go
  services/containerregistry/mgmt/2018-09-01/containerregistry/registries.go
  services/containerregistry/mgmt/2018-09-01/containerregistry/replications.go
  services/containerregistry/mgmt/2018-09-01/containerregistry/runs.go
  services/containerregistry/mgmt/2018-09-01/containerregistry/tasks.go
  services/containerregistry/mgmt/2018-09-01/containerregistry/webhooks.go
  services/preview/containerregistry/mgmt/2017-06-01-preview/containerregistry/models.go
  services/preview/containerregistry/mgmt/2018-02-01/containerregistry/models.go
  services/preview/containerregistry/mgmt/2018-02-01/containerregistry/registries.go
  services/preview/containerregistry/mgmt/2018-02-01/containerregistry/replications.go
  services/preview/containerregistry/mgmt/2018-02-01/containerregistry/webhooks.go
Labels: RestPRMerged, review

#3454 [AutoPR apimanagement/resource-manager] Added example for template params
  services/apimanagement/mgmt/2016-07-07/apimanagement/models.go
  services/apimanagement/mgmt/2016-07-07/apimanagement/property.go
  services/apimanagement/mgmt/2016-07-07/apimanagement/reports.go
  services/apimanagement/mgmt/2016-07-07/apimanagement/subscriptions.go
  services/apimanagement/mgmt/2016-10-10/apimanagement/models.go
  services/apimanagement/mgmt/2016-10-10/apimanagement/property.go
  services/apimanagement/mgmt/2016-10-10/apimanagement/reports.go
  services/apimanagement/mgmt/2016-10-10/apimanagement/subscriptions.go
  services/apimanagement/mgmt/2017-03-01/apimanagement/diagnosticlogger.go
  services/apimanagement/mgmt/2017-03-01/apimanagement/models.go
  services/apimanagement/mgmt/2017-03-01/apimanagement/property.go
  services/apimanagement/mgmt/2017-03-01/apimanagement/reports.go
  services/apimanagement/mgmt/2017-03-01/apimanagement/subscription.go
  services/apimanagement/mgmt/2017-03-01/apimanagement/tagdescription.go
  services/apimanagement/mgmt/2018-01-01/apimanagement/apidiagnosticlogger.go
  services/apimanagement/mgmt/2018-01-01/apimanagement/apiissue.go
  services/apimanagement/mgmt/2018-01-01/apimanagement/apiissueattachment.go
  services/apimanagement/mgmt/2018-01-01/apimanagement/apiissuecomment.go
  services/apimanagement/mgmt/2018-01-01/apimanagement/diagnosticlogger.go
  services/apimanagement/mgmt/2018-01-01/apimanagement/models.go
  services/apimanagement/mgmt/2018-01-01/apimanagement/property.go
  services/apimanagement/mgmt/2018-01-01/apimanagement/reports.go
  services/apimanagement/mgmt/2018-01-01/apimanagement/subscription.go
  services/apimanagement/mgmt/2018-01-01/apimanagement/tagdescription.go
  services/preview/apimanagement/mgmt/2018-06-01-preview/apimanagement/apiissue.go
  services/preview/apimanagement/mgmt/2018-06-01-preview/apimanagement/apiissueattachment.go
  services/preview/apimanagement/mgmt/2018-06-01-preview/apimanagement/apiissuecomment.go
  services/preview/apimanagement/mgmt/2018-06-01-preview/apimanagement/models.go
  services/preview/apimanagement/mgmt/2018-06-01-preview/apimanagement/property.go
  services/preview/apimanagement/mgmt/2018-06-01-preview/apimanagement/reports.go
  services/preview/apimanagement/mgmt/2018-06-01-preview/apimanagement/subscription.go
  services/preview/apimanagement/mgmt/2018-06-01-preview/apimanagement/tagdescription.go
Labels: RestPRMerged, review

#3456 [AutoPR] blueprint/resource-manager
  services/preview/blueprint/mgmt/2017-11-11-preview/blueprint/models.go
Labels: ServicePR, review

#3455 [AutoPR] automation/resource-manager
  services/automation/mgmt/2015-10-31/automation/connectiontype.go
  services/automation/mgmt/2015-10-31/automation/models.go
  services/preview/automation/mgmt/2017-05-15-preview/automation/connectiontype.go
  services/preview/automation/mgmt/2017-05-15-preview/automation/models.go
  services/preview/automation/mgmt/2018-01-15-preview/automation/connectiontype.go
  services/preview/automation/mgmt/2018-01-15-preview/automation/models.go
  services/preview/automation/mgmt/2018-06-30-preview/automation/connectiontype.go
  services/preview/automation/mgmt/2018-06-30-preview/automation/models.go
Labels: ServicePR, review

#3451 [AutoPR] cdn/resource-manager
  services/cdn/mgmt/2016-10-02/cdn/models.go
  services/cdn/mgmt/2017-04-02/cdn/models.go
  services/cdn/mgmt/2017-10-12/cdn/models.go
Labels: ServicePR, review

#3446 [AutoPR batch/resource-manager/batch/data-plane] typo: Microsoft.Batch
  services/batch/2017-05-01.5.0/batch/computenode.go
  services/batch/2017-05-01.5.0/batch/job.go
  services/batch/2017-05-01.5.0/batch/jobschedule.go
  services/batch/2017-05-01.5.0/batch/models.go
  services/batch/2017-05-01.5.0/batch/pool.go
  services/batch/2018-03-01.6.1/batch/computenode.go
  services/batch/2018-03-01.6.1/batch/job.go
  services/batch/2018-03-01.6.1/batch/jobschedule.go
  services/batch/2018-03-01.6.1/batch/models.go
  services/batch/2018-03-01.6.1/batch/pool.go
  services/batch/2018-08-01.7.0/batch/computenode.go
  services/batch/2018-08-01.7.0/batch/job.go
  services/batch/2018-08-01.7.0/batch/jobschedule.go
  services/batch/2018-08-01.7.0/batch/models.go
  services/batch/2018-08-01.7.0/batch/pool.go
Labels: RestPRMerged, review

#3429 [AutoPR] web/resource-manager
  services/web/mgmt/2016-09-01/web/appservicecertificateorders.go
  services/web/mgmt/2016-09-01/web/models.go
  services/web/mgmt/2018-02-01/web/appservicecertificateorders.go
  services/web/mgmt/2018-02-01/web/models.go
Labels: ServicePR, review

#3452 [AutoPR] botservice/resource-manager
  services/preview/botservice/mgmt/2017-12-01/botservice/models.go
  services/preview/botservice/mgmt/2018-07-12/botservice/models.go
Labels: ServicePR, review
