Repository Azure/azure-sdk-for-go, pull requests merged in 2018-08, with the labels that each got.

#2361 update dep to v0.5.0
  .travis.yml
Labels: review

#2281 [AutoPR apimanagement/resource-manager] updated formatting for externalid description
  Gopkg.lock
  services/preview/apimanagement/mgmt/2018-06-01-preview/apimanagement/models.go
Labels: RestPRMerged, review

#2366 [AutoPR storage/resource-manager] [Storage] Set the SignedResource as optional in ListServiceSAS
  services/preview/storage/mgmt/2018-03-01-preview/storage/models.go
  services/storage/mgmt/2017-06-01/storage/models.go
  services/storage/mgmt/2017-10-01/storage/models.go
  services/storage/mgmt/2018-02-01/storage/models.go
Labels: RestPRMerged

#2367 [AutoPR] storage/resource-manager
  services/preview/storage/mgmt/2018-03-01-preview/storage/models.go
  services/storage/mgmt/2017-06-01/storage/models.go
  services/storage/mgmt/2017-10-01/storage/models.go
  services/storage/mgmt/2018-02-01/storage/models.go
Labels: ServicePR, review

#2376 [AutoPR datafactory/resource-manager] [Datafactory] Remove readOnly flag on github hostName property
  services/datafactory/mgmt/2018-06-01/datafactory/models.go
Labels: RestPRMerged

#2377 [AutoPR] datafactory/resource-manager
  services/datafactory/mgmt/2018-06-01/datafactory/models.go
Labels: ServicePR, review

#2379 do CI builds only on release branches
  .travis.yml
Labels: review

#2329 [AutoPR botservice/resource-manager] BotService Preview: new API version for MsTeams and CheckNameavailability
  Gopkg.lock
  profiles/preview/preview/botservice/mgmt/botservices/models.go
  services/preview/botservice/mgmt/2018-07-12/botservices/botconnection.go
  services/preview/botservice/mgmt/2018-07-12/botservices/bots.go
  services/preview/botservice/mgmt/2018-07-12/botservices/channels.go
  services/preview/botservice/mgmt/2018-07-12/botservices/client.go
  services/preview/botservice/mgmt/2018-07-12/botservices/models.go
  services/preview/botservice/mgmt/2018-07-12/botservices/operations.go
  services/preview/botservice/mgmt/2018-07-12/botservices/version.go
Labels: RestPRMerged, review

#2381 [AutoPR cost-management/resource-manager] Add Connector resource type as preview to CostManagement RP
  profiles/preview/costmanagement/mgmt/costmanagement/models.go
  services/costmanagement/mgmt/2018-09-01-preview/costmanagement/billingaccountdimensions.go
  services/costmanagement/mgmt/2018-09-01-preview/costmanagement/client.go
  services/costmanagement/mgmt/2018-09-01-preview/costmanagement/connector.go
  services/costmanagement/mgmt/2018-09-01-preview/costmanagement/models.go
  services/costmanagement/mgmt/2018-09-01-preview/costmanagement/reportconfig.go
  services/costmanagement/mgmt/2018-09-01-preview/costmanagement/resourcegroupdimensions.go
  services/costmanagement/mgmt/2018-09-01-preview/costmanagement/subscriptiondimensions.go
  services/costmanagement/mgmt/2018-09-01-preview/costmanagement/version.go
Labels: RestPRMerged, review

#2380 [AutoPR] botservice/resource-manager
  profiles/preview/preview/botservice/mgmt/botservices/models.go
  services/preview/botservice/mgmt/2018-07-12/botservices/botconnection.go
  services/preview/botservice/mgmt/2018-07-12/botservices/bots.go
  services/preview/botservice/mgmt/2018-07-12/botservices/channels.go
  services/preview/botservice/mgmt/2018-07-12/botservices/client.go
  services/preview/botservice/mgmt/2018-07-12/botservices/models.go
  services/preview/botservice/mgmt/2018-07-12/botservices/operations.go
  services/preview/botservice/mgmt/2018-07-12/botservices/version.go
Labels: ServicePR, review

#2383 [AutoPR hanaonazure/resource-manager] Added power state to Hana Instance
  profiles/preview/preview/hanaonazure/mgmt/hanaonazure/models.go
  services/preview/hanaonazure/mgmt/2017-11-03-preview/hanaonazure/models.go
Labels: RestPRMerged, review

#2385 [AutoPR] cost-management/resource-manager
  profiles/preview/preview/costmanagement/mgmt/costmanagement/models.go
  services/preview/costmanagement/mgmt/2018-09-01-preview/costmanagement/billingaccountdimensions.go
  services/preview/costmanagement/mgmt/2018-09-01-preview/costmanagement/client.go
  services/preview/costmanagement/mgmt/2018-09-01-preview/costmanagement/connector.go
  services/preview/costmanagement/mgmt/2018-09-01-preview/costmanagement/models.go
  services/preview/costmanagement/mgmt/2018-09-01-preview/costmanagement/reportconfig.go
  services/preview/costmanagement/mgmt/2018-09-01-preview/costmanagement/resourcegroupdimensions.go
  services/preview/costmanagement/mgmt/2018-09-01-preview/costmanagement/subscriptiondimensions.go
  services/preview/costmanagement/mgmt/2018-09-01-preview/costmanagement/version.go
Labels: ServicePR, review

#2365 [AutoPR hdinsight/resource-manager] [HDInsight] Fixed PUT application parameter
  services/preview/hdinsight/mgmt/2015-03-01-preview/hdinsight/applications.go
  services/preview/hdinsight/mgmt/2018-06-01-preview/hdinsight/applications.go
Labels: RestPRMerged, review

#2386 [AutoPR] hanaonazure/resource-manager
  profiles/preview/preview/hanaonazure/mgmt/hanaonazure/models.go
  services/preview/hanaonazure/mgmt/2017-11-03-preview/hanaonazure/models.go
Labels: ServicePR, review

#2388 [AutoPR] hdinsight/resource-manager
  services/preview/hdinsight/mgmt/2015-03-01-preview/hdinsight/applications.go
  services/preview/hdinsight/mgmt/2018-06-01-preview/hdinsight/applications.go
Labels: ServicePR, review

#2391 [AutoPR web/resource-manager] Add API for adding external storage account configurations to a web app
  profiles/preview/web/mgmt/web/models.go
  services/web/mgmt/2018-02-01/web/apps.go
  services/web/mgmt/2018-02-01/web/models.go
Labels: RestPRMerged

#2396 [AutoPR automation/resource-manager] Updating PUT operation requirements for SourceControls and SourceControlSyncJobs, updating streams’ value property, and updating examples.
  Gopkg.lock
  profiles/preview/preview/automation/mgmt/automation/models.go
  services/automation/mgmt/2015-10-31/automation/runbookdraft.go
  services/preview/automation/mgmt/2017-05-15-preview/automation/models.go
  services/preview/automation/mgmt/2017-05-15-preview/automation/runbookdraft.go
  services/preview/automation/mgmt/2017-05-15-preview/automation/sourcecontrol.go
  services/preview/automation/mgmt/2017-05-15-preview/automation/sourcecontrolsyncjob.go
  services/preview/automation/mgmt/2018-01-preview/automation/models.go
  services/preview/automation/mgmt/2018-01-preview/automation/runbookdraft.go
  services/preview/automation/mgmt/2018-01-preview/automation/sourcecontrol.go
  services/preview/automation/mgmt/2018-01-preview/automation/sourcecontrolsyncjob.go
Labels: RestPRMerged, review

#2392 [AutoPR] web/resource-manager
  profiles/preview/web/mgmt/web/models.go
  services/web/mgmt/2018-02-01/web/apps.go
  services/web/mgmt/2018-02-01/web/models.go
Labels: ServicePR, review

#2398 [AutoPR] automation/resource-manager
  profiles/preview/preview/automation/mgmt/automation/models.go
  services/preview/automation/mgmt/2017-05-15-preview/automation/models.go
  services/preview/automation/mgmt/2017-05-15-preview/automation/sourcecontrol.go
  services/preview/automation/mgmt/2017-05-15-preview/automation/sourcecontrolsyncjob.go
  services/preview/automation/mgmt/2018-01-preview/automation/models.go
  services/preview/automation/mgmt/2018-01-preview/automation/sourcecontrol.go
  services/preview/automation/mgmt/2018-01-preview/automation/sourcecontrolsyncjob.go
Labels: ServicePR, review

#2378 [AutoPR azurestack/resource-manager] Fix AzureStack swagger specs lint errors
  Gopkg.lock
  profiles/preview/azurestack/mgmt/azurestack/models.go
  services/azurestack/mgmt/2017-06-01/azurestack/customersubscriptions.go
  services/azurestack/mgmt/2017-06-01/azurestack/models.go
  services/azurestack/mgmt/2017-06-01/azurestack/products.go
  services/azurestack/mgmt/2017-06-01/azurestack/registrations.go
Labels: RestPRMerged, review

#2400 [AutoPR] advisor/resource-manager
  services/advisor/mgmt/2017-04-19/advisor/models.go
Labels: ServicePR, review

#2402 [AutoPR monitor/resource-manager] [Monitor] Fix issue #3585: revert previous commit since it is a brealing change
  profiles/preview/preview/monitor/mgmt/insights/models.go
  services/preview/monitor/mgmt/2017-05-01-preview/insights/models.go
  services/preview/monitor/mgmt/2018-03-01/insights/models.go
Labels: RestPRMerged, review

#2406 [AutoPR] monitor/resource-manager
  profiles/preview/preview/monitor/mgmt/insights/models.go
  services/preview/monitor/mgmt/2017-05-01-preview/insights/models.go
  services/preview/monitor/mgmt/2018-03-01/insights/models.go
Labels: ServicePR, review

#2401 [AutoPR] azurestack/resource-manager
  profiles/preview/azurestack/mgmt/azurestack/models.go
  services/azurestack/mgmt/2017-06-01/azurestack/customersubscriptions.go
  services/azurestack/mgmt/2017-06-01/azurestack/models.go
  services/azurestack/mgmt/2017-06-01/azurestack/products.go
  services/azurestack/mgmt/2017-06-01/azurestack/registrations.go
Labels: ServicePR, review

#2328 [AutoPR signalr/resource-manager] Add api to list usages of Azure SignalR resources
  Gopkg.lock
  profiles/preview/preview/signalr/mgmt/signalr/models.go
  services/preview/signalr/mgmt/2018-03-01-preview/signalr/models.go
  services/preview/signalr/mgmt/2018-03-01-preview/signalr/usages.go
Labels: RestPRMerged, review

#2409 [AutoPR network/resource-manager] add x-ms-long-running-operation-options to query packet capture status
  Gopkg.lock
Labels: RestPRMerged, review

#2410 [AutoPR] signalr/resource-manager
  profiles/preview/preview/signalr/mgmt/signalr/models.go
  services/preview/signalr/mgmt/2018-03-01-preview/signalr/models.go
  services/preview/signalr/mgmt/2018-03-01-preview/signalr/usages.go
Labels: ServicePR, review

#2416 [AutoPR containerservices/resource-manager] [AKS] regex bug fix for LinuxProfile.AdminUser
  services/containerservice/mgmt/2017-07-01/containerservice/containerservices.go
  services/containerservice/mgmt/2017-08-31/containerservice/containerservices.go
  services/containerservice/mgmt/2017-08-31/containerservice/managedclusters.go
  services/containerservice/mgmt/2017-09-30/containerservice/containerservices.go
  services/containerservice/mgmt/2017-09-30/containerservice/managedclusters.go
  services/containerservice/mgmt/2018-03-31/containerservice/containerservices.go
  services/containerservice/mgmt/2018-03-31/containerservice/managedclusters.go
Labels: RestPRMerged, review

#2417 [AutoPR] containerservices/resource-manager
  services/containerservice/mgmt/2017-07-01/containerservice/containerservices.go
  services/containerservice/mgmt/2017-08-31/containerservice/containerservices.go
  services/containerservice/mgmt/2017-08-31/containerservice/managedclusters.go
  services/containerservice/mgmt/2017-09-30/containerservice/containerservices.go
  services/containerservice/mgmt/2017-09-30/containerservice/managedclusters.go
  services/containerservice/mgmt/2018-03-31/containerservice/containerservices.go
  services/containerservice/mgmt/2018-03-31/containerservice/managedclusters.go
Labels: ServicePR, review

#2420 [AutoPR containerservices/resource-manager] [AKS]modify credentialResults keyName to kubeconfigs
  services/containerservice/mgmt/2018-03-31/containerservice/models.go
Labels: RestPRMerged, review

#2423 [AutoPR apimanagement/resource-manager] Bug fix on readonly property
  services/preview/apimanagement/mgmt/2018-06-01-preview/apimanagement/models.go
Labels: RestPRMerged, review

#2427 [AutoPR containerservices/resource-manager] [AKS] fix CredentialResult value format
  services/containerservice/mgmt/2018-03-31/containerservice/models.go
Labels: RestPRMerged, review

#2422 [AutoPR] containerservices/resource-manager
  services/containerservice/mgmt/2018-03-31/containerservice/models.go
Labels: ServicePR, review

#2424 [AutoPR] apimanagement/resource-manager
  services/preview/apimanagement/mgmt/2018-06-01-preview/apimanagement/models.go
Labels: ServicePR, review

#2404 [AutoPR web/resource-manager] Include DRSecondary endpoint for GetPublishingProfileXml
  services/web/mgmt/2018-02-01/web/models.go
Labels: RestPRMerged, review

#2418 [AutoPR consumption/resource-manager] Introducing UsageDetails and Aggregated Cost by Managment Group Scope. Also updated some existing examples to include missing billingperiod in billingPeriodId Property.
  profiles/preview/consumption/mgmt/consumption/models.go
  services/consumption/mgmt/2018-06-30/consumption/aggregatedcost.go
  services/consumption/mgmt/2018-06-30/consumption/models.go
  services/consumption/mgmt/2018-06-30/consumption/usagedetails.go
Labels: RestPRMerged, review

#2432 [AutoPR logic/resource-manager] Fix for extra / on the end of the triggers endpoint
  services/logic/mgmt/2016-06-01/logic/workflowtriggers.go
Labels: RestPRMerged, review

#2412 [AutoPR sql/resource-manager] Adding VA support for manged instance
  profiles/preview/preview/sql/mgmt/sql/models.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/databasevulnerabilityassessments.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/models.go
  services/preview/sql/mgmt/2017-10-01-preview/sql/models.go
Labels: RestPRMerged, review

#2434 [AutoPR] logic/resource-manager
  services/logic/mgmt/2016-06-01/logic/workflowtriggers.go
Labels: ServicePR, review

#2311 [AutoPR cognitiveservices/data-plane/ContentModerator] [Cognitive Services] Update endpoint URL template for Content Moderator.
  Gopkg.lock
  profiles/latest/cognitiveservices/contentmoderator/models.go
  profiles/preview/cognitiveservices/contentmoderator/models.go
  services/cognitiveservices/v1.0/contentmoderator/client.go
  services/cognitiveservices/v1.0/contentmoderator/imagemoderation.go
  services/cognitiveservices/v1.0/contentmoderator/listmanagementimage.go
  services/cognitiveservices/v1.0/contentmoderator/listmanagementimagelists.go
  services/cognitiveservices/v1.0/contentmoderator/listmanagementterm.go
  services/cognitiveservices/v1.0/contentmoderator/listmanagementtermlists.go
  services/cognitiveservices/v1.0/contentmoderator/models.go
  services/cognitiveservices/v1.0/contentmoderator/reviews.go
  services/cognitiveservices/v1.0/contentmoderator/textmoderation.go
Labels: RestPRMerged, review

#2430 [AutoPR] web/resource-manager
  services/web/mgmt/2018-02-01/web/models.go
Labels: ServicePR, review

#2435 [AutoPR] sql/resource-manager
  profiles/preview/preview/sql/mgmt/sql/models.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/databasevulnerabilityassessments.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/models.go
  services/preview/sql/mgmt/2017-10-01-preview/sql/models.go
Labels: ServicePR, review

#2438 [AutoPR] cognitiveservices/data-plane/ContentModerator
  profiles/latest/cognitiveservices/contentmoderator/models.go
  profiles/preview/cognitiveservices/contentmoderator/models.go
  services/cognitiveservices/v1.0/contentmoderator/client.go
  services/cognitiveservices/v1.0/contentmoderator/imagemoderation.go
  services/cognitiveservices/v1.0/contentmoderator/listmanagementimage.go
  services/cognitiveservices/v1.0/contentmoderator/listmanagementimagelists.go
  services/cognitiveservices/v1.0/contentmoderator/listmanagementterm.go
  services/cognitiveservices/v1.0/contentmoderator/listmanagementtermlists.go
  services/cognitiveservices/v1.0/contentmoderator/models.go
  services/cognitiveservices/v1.0/contentmoderator/reviews.go
  services/cognitiveservices/v1.0/contentmoderator/textmoderation.go
Labels: ServicePR, review

#2408 [AutoPR recoveryservicessiterecovery/resource-manager] Changes to support Azure Disk Encryption & Accelerated Networking
  profiles/latest/recoveryservices/mgmt/siterecovery/models.go
  profiles/preview/recoveryservices/mgmt/siterecovery/models.go
  services/recoveryservices/mgmt/2018-01-10/siterecovery/models.go
Labels: RestPRMerged, review

#2437 [AutoPR compute/resource-manager/network/resource-manager] Publicipprefixaugust
  services/compute/mgmt/2018-06-01/compute/models.go
Labels: RestPRMerged, review

#2442 [AutoPR automation/resource-manager] Updating SourceControlSyncJobs and SourceControlSyncJobStreams properties and examples.
  profiles/preview/preview/automation/mgmt/automation/models.go
  services/preview/automation/mgmt/2017-05-15-preview/automation/models.go
  services/preview/automation/mgmt/2018-01-preview/automation/models.go
Labels: RestPRMerged, review

#2441 [AutoPR] recoveryservicessiterecovery/resource-manager
  profiles/latest/recoveryservices/mgmt/siterecovery/models.go
  profiles/preview/recoveryservices/mgmt/siterecovery/models.go
  services/recoveryservices/mgmt/2018-01-10/siterecovery/models.go
Labels: ServicePR, review

#2443 [AutoPR] automation/resource-manager
  profiles/preview/preview/automation/mgmt/automation/models.go
  services/preview/automation/mgmt/2017-05-15-preview/automation/models.go
  services/preview/automation/mgmt/2018-01-preview/automation/models.go
Labels: ServicePR, review

#2453 [AutoPR compute/resource-manager/network/resource-manager] Publicipprefixaugust
  services/compute/mgmt/2018-06-01/compute/models.go
Labels: RestPRInProgress, review

#2452 [AutoPR iotcentral/resource-manager] move stable iotcentral Go SDK package out of preview directory
  profiles/preview/iotcentral/mgmt/iotcentral/models.go
  services/iotcentral/mgmt/2018-09-01/iotcentral/apps.go
  services/iotcentral/mgmt/2018-09-01/iotcentral/client.go
  services/iotcentral/mgmt/2018-09-01/iotcentral/models.go
  services/iotcentral/mgmt/2018-09-01/iotcentral/operations.go
  services/iotcentral/mgmt/2018-09-01/iotcentral/version.go
  services/preview/iotcentral/mgmt/2018-09-01/iotcentral/apps.go
  services/preview/iotcentral/mgmt/2018-09-01/iotcentral/client.go
  services/preview/iotcentral/mgmt/2018-09-01/iotcentral/models.go
  services/preview/iotcentral/mgmt/2018-09-01/iotcentral/operations.go
  services/preview/iotcentral/mgmt/2018-09-01/iotcentral/version.go
Labels: RestPRMerged, review

#2440 [AutoPR containerregistry/resource-manager] add option to import images from public registries
  services/containerregistry/mgmt/2017-10-01/containerregistry/models.go
  services/containerregistry/mgmt/2017-10-01/containerregistry/registries.go
  services/preview/containerregistry/mgmt/2018-02-01/containerregistry/models.go
  services/preview/containerregistry/mgmt/2018-02-01/containerregistry/registries.go
Labels: RestPRMerged, review

#2415 [AutoPR network/resource-manager] Added NetworkConfigurationDiagnostic rest API + example
  profiles/preview/network/mgmt/network/models.go
  services/network/mgmt/2018-06-01/network/models.go
  services/network/mgmt/2018-06-01/network/watchers.go
Labels: RestPRMerged, review

#2459 [AutoPR] containerregistry/resource-manager
  services/containerregistry/mgmt/2017-10-01/containerregistry/models.go
  services/containerregistry/mgmt/2017-10-01/containerregistry/registries.go
  services/preview/containerregistry/mgmt/2018-02-01/containerregistry/models.go
  services/preview/containerregistry/mgmt/2018-02-01/containerregistry/registries.go
Labels: ServicePR, review

#2446 [AutoPR sql/resource-manager] [DO NOT MERGE]
  services/preview/sql/mgmt/2017-03-01-preview/sql/sensitivitylabels.go
Labels: RestPRMerged, review

#2469 [AutoPR] network/resource-manager
  profiles/preview/network/mgmt/network/models.go
  services/network/mgmt/2018-06-01/network/models.go
  services/network/mgmt/2018-06-01/network/watchers.go
Labels: ServicePR, review

#2470 [AutoPR] sql/resource-manager
  services/preview/sql/mgmt/2017-03-01-preview/sql/sensitivitylabels.go
Labels: ServicePR, review

#2302 [AutoPR cognitiveservices/data-plane/LUIS/Runtime/cognitiveservices/data-plane/LUIS/Authoring] [Cognitive Services] Update endpoint URL template for LUIS.
  profiles/latest/cognitiveservices/luis/runtime/models.go
  profiles/preview/cognitiveservices/luis/authoring/models.go
  profiles/preview/cognitiveservices/luis/runtime/models.go
  services/cognitiveservices/v2.0/luis/authoring/apps.go
  services/cognitiveservices/v2.0/luis/authoring/client.go
  services/cognitiveservices/v2.0/luis/authoring/examples.go
  services/cognitiveservices/v2.0/luis/authoring/features.go
  services/cognitiveservices/v2.0/luis/authoring/model.go
  services/cognitiveservices/v2.0/luis/authoring/pattern.go
  services/cognitiveservices/v2.0/luis/authoring/permissions.go
  services/cognitiveservices/v2.0/luis/authoring/train.go
  services/cognitiveservices/v2.0/luis/authoring/versions.go
  services/cognitiveservices/v2.0/luis/runtime/client.go
  services/cognitiveservices/v2.0/luis/runtime/prediction.go
Labels: RestPRMerged, review

#2472 [AutoPR batch/data-plane] New Batch data plane API version 2018-08-01.7.0
  profiles/preview/batch/batch/models.go
  services/batch/2018-08-01.7.0/batch/account.go
  services/batch/2018-08-01.7.0/batch/application.go
  services/batch/2018-08-01.7.0/batch/certificate.go
  services/batch/2018-08-01.7.0/batch/client.go
  services/batch/2018-08-01.7.0/batch/computenode.go
  services/batch/2018-08-01.7.0/batch/file.go
  services/batch/2018-08-01.7.0/batch/job.go
  services/batch/2018-08-01.7.0/batch/jobschedule.go
  services/batch/2018-08-01.7.0/batch/models.go
  services/batch/2018-08-01.7.0/batch/pool.go
  services/batch/2018-08-01.7.0/batch/task.go
  services/batch/2018-08-01.7.0/batch/version.go
Labels: RestPRMerged, review

#2464 [AutoPR compute/resource-manager] [Compute] add zone and rolling upgrade.
  profiles/latest/compute/mgmt/compute/models.go
  profiles/preview/compute/mgmt/compute/models.go
  services/compute/mgmt/2017-12-01/compute/models.go
  services/compute/mgmt/2018-04-01/compute/models.go
  services/compute/mgmt/2018-06-01/compute/galleryimages.go
  services/compute/mgmt/2018-06-01/compute/galleryimageversions.go
  services/compute/mgmt/2018-06-01/compute/models.go
  services/compute/mgmt/2018-06-01/compute/virtualmachinescalesetrollingupgrades.go
  services/compute/mgmt/2018-06-01/compute/virtualmachinescalesets.go
Labels: RestPRMerged, review

#2485 [AutoPR] web/resource-manager
  services/web/mgmt/2018-02-01/web/models.go
Labels: ServicePR, review

#2494 [AutoPR cognitiveservices/data-plane/ContentModerator] [Cognitive Services] Fix metadata types for Content Moderator.
  profiles/latest/cognitiveservices/contentmoderator/models.go
  profiles/preview/cognitiveservices/contentmoderator/models.go
  services/cognitiveservices/v1.0/contentmoderator/models.go
Labels: RestPRMerged, review

#2491 [AutoPR] powerbidedicated/resource-manager
  profiles/latest/powerbidedicated/mgmt/powerbidedicated/models.go
  profiles/preview/powerbidedicated/mgmt/powerbidedicated/models.go
  services/powerbidedicated/mgmt/2017-10-01/powerbidedicated/capacities.go
  services/powerbidedicated/mgmt/2017-10-01/powerbidedicated/models.go
Labels: ServicePR, review

#2492 [AutoPR] batch/data-plane
  profiles/preview/batch/batch/models.go
  services/batch/2018-08-01.7.0/batch/account.go
  services/batch/2018-08-01.7.0/batch/application.go
  services/batch/2018-08-01.7.0/batch/certificate.go
  services/batch/2018-08-01.7.0/batch/client.go
  services/batch/2018-08-01.7.0/batch/computenode.go
  services/batch/2018-08-01.7.0/batch/file.go
  services/batch/2018-08-01.7.0/batch/job.go
  services/batch/2018-08-01.7.0/batch/jobschedule.go
  services/batch/2018-08-01.7.0/batch/models.go
  services/batch/2018-08-01.7.0/batch/pool.go
  services/batch/2018-08-01.7.0/batch/task.go
  services/batch/2018-08-01.7.0/batch/version.go
Labels: ServicePR, review

#2493 [AutoPR] compute/resource-manager
  profiles/latest/compute/mgmt/compute/models.go
  profiles/preview/compute/mgmt/compute/models.go
  services/compute/mgmt/2017-12-01/compute/models.go
  services/compute/mgmt/2018-04-01/compute/models.go
  services/compute/mgmt/2018-06-01/compute/galleryimages.go
  services/compute/mgmt/2018-06-01/compute/galleryimageversions.go
  services/compute/mgmt/2018-06-01/compute/models.go
  services/compute/mgmt/2018-06-01/compute/virtualmachinescalesetrollingupgrades.go
  services/compute/mgmt/2018-06-01/compute/virtualmachinescalesets.go
Labels: ServicePR, review

#2501 [AutoPR] cognitiveservices/data-plane/ContentModerator
  profiles/latest/cognitiveservices/contentmoderator/models.go
  profiles/preview/cognitiveservices/contentmoderator/models.go
  services/cognitiveservices/v1.0/contentmoderator/models.go
Labels: ServicePR, review

#2499 [AutoPR signalr/resource-manager] return more perperties of SignalR resource
  profiles/preview/preview/signalr/mgmt/signalr/models.go
  services/preview/signalr/mgmt/2018-03-01-preview/signalr/models.go
Labels: RestPRMerged, review

#2504 [AutoPR] signalr/resource-manager
  profiles/preview/preview/signalr/mgmt/signalr/models.go
  services/preview/signalr/mgmt/2018-03-01-preview/signalr/models.go
Labels: ServicePR, review

#2407 [AutoPR graphrbac/data-plane] Added OAuth2 GET and POST to GraphRBAC.json spec
  Gopkg.lock
  profiles/latest/graphrbac/graphrbac/models.go
  profiles/preview/graphrbac/graphrbac/models.go
  services/graphrbac/1.6/graphrbac/models.go
  services/graphrbac/1.6/graphrbac/oauth2.go
  services/graphrbac/1.6/graphrbac/serviceprincipals.go
Labels: RestPRMerged, review

#2477 [AutoPR datafactory/resource-manager] Add two API-s to integration runtime
  profiles/preview/datafactory/mgmt/datafactory/models.go
  services/datafactory/mgmt/2018-06-01/datafactory/integrationruntimenodes.go
  services/datafactory/mgmt/2018-06-01/datafactory/integrationruntimes.go
  services/datafactory/mgmt/2018-06-01/datafactory/models.go
Labels: RestPRMerged, review

#2467 [AutoPR mysql/resource-manager] Add serverSecurityAlertPolicies APIs for MySQL servers
  Gopkg.lock
  profiles/latest/mysql/mgmt/mysql/models.go
  profiles/preview/mysql/mgmt/mysql/models.go
  services/mysql/mgmt/2017-12-01/mysql/models.go
  services/mysql/mgmt/2017-12-01/mysql/serversecurityalertpolicies.go
Labels: RestPRMerged, review

#2515 [AutoPR batch/data-plane] Update Batch docs
  services/batch/2018-08-01.7.0/batch/models.go
Labels: RestPRMerged, review

#2450 [AutoPR cdn/resource-manager] adding standard_microsoft in pricing tier
  profiles/preview/cdn/mgmt/cdn/models.go
  services/cdn/mgmt/2017-10-12/cdn/models.go
Labels: RestPRMerged, review

#2503 [AutoPR reservations/resource-manager] Add new reserved resource type CosmosDb
  profiles/preview/reservations/mgmt/reservations/models.go
  services/reservations/mgmt/2018-06-01/reservations/models.go
Labels: RestPRMerged, review

#2513 [AutoPR] datafactory/resource-manager
  profiles/preview/datafactory/mgmt/datafactory/models.go
  services/datafactory/mgmt/2018-06-01/datafactory/integrationruntimenodes.go
  services/datafactory/mgmt/2018-06-01/datafactory/integrationruntimes.go
  services/datafactory/mgmt/2018-06-01/datafactory/models.go
Labels: ServicePR, review

#2516 [AutoPR] batch/data-plane
  services/batch/2018-08-01.7.0/batch/models.go
Labels: ServicePR, review

#2517 [AutoPR] cdn/resource-manager
  profiles/preview/cdn/mgmt/cdn/models.go
  services/cdn/mgmt/2017-10-12/cdn/models.go
Labels: ServicePR, review

#2514 [AutoPR] mysql/resource-manager
  profiles/latest/mysql/mgmt/mysql/models.go
  profiles/preview/mysql/mgmt/mysql/models.go
  services/mysql/mgmt/2017-12-01/mysql/models.go
  services/mysql/mgmt/2017-12-01/mysql/serversecurityalertpolicies.go
Labels: ServicePR, review

#2512 [AutoPR] graphrbac/data-plane
  profiles/latest/graphrbac/graphrbac/models.go
  profiles/preview/graphrbac/graphrbac/models.go
  services/graphrbac/1.6/graphrbac/models.go
  services/graphrbac/1.6/graphrbac/oauth2.go
  services/graphrbac/1.6/graphrbac/serviceprincipals.go
Labels: ServicePR, review

#2518 [AutoPR] reservations/resource-manager
  profiles/preview/reservations/mgmt/reservations/models.go
  services/reservations/mgmt/2018-06-01/reservations/models.go
Labels: ServicePR, review

#2520 [AutoPR resources/resource-manager] [Portal Generated] Add managed identity to Microsoft.Authorization/policyAssignments (2018-05-01)
  profiles/preview/resources/mgmt/policy/models.go
  services/resources/mgmt/2018-05-01/policy/assignments.go
  services/resources/mgmt/2018-05-01/policy/client.go
  services/resources/mgmt/2018-05-01/policy/definitions.go
  services/resources/mgmt/2018-05-01/policy/models.go
  services/resources/mgmt/2018-05-01/policy/setdefinitions.go
  services/resources/mgmt/2018-05-01/policy/version.go
Labels: RestPRMerged, review

#2521 [AutoPR] cost-management/resource-manager
  services/preview/costmanagement/mgmt/2018-08-01-preview/costmanagement/billingaccountdimensions.go
  services/preview/costmanagement/mgmt/2018-08-01-preview/costmanagement/client.go
  services/preview/costmanagement/mgmt/2018-08-01-preview/costmanagement/connector.go
  services/preview/costmanagement/mgmt/2018-08-01-preview/costmanagement/models.go
  services/preview/costmanagement/mgmt/2018-08-01-preview/costmanagement/reportconfig.go
  services/preview/costmanagement/mgmt/2018-08-01-preview/costmanagement/resourcegroupdimensions.go
  services/preview/costmanagement/mgmt/2018-08-01-preview/costmanagement/subscriptiondimensions.go
  services/preview/costmanagement/mgmt/2018-08-01-preview/costmanagement/version.go
Labels: ServicePR, review

#2523 [AutoPR] resources/resource-manager
  profiles/preview/resources/mgmt/policy/models.go
  services/resources/mgmt/2018-05-01/policy/assignments.go
  services/resources/mgmt/2018-05-01/policy/client.go
  services/resources/mgmt/2018-05-01/policy/definitions.go
  services/resources/mgmt/2018-05-01/policy/models.go
  services/resources/mgmt/2018-05-01/policy/setdefinitions.go
  services/resources/mgmt/2018-05-01/policy/version.go
Labels: ServicePR, review

#2524 delete renamed service
  profiles/preview/preview/costmanagement/mgmt/costmanagement/models.go
  services/preview/costmanagement/mgmt/2018-09-01-preview/costmanagement/billingaccountdimensions.go
  services/preview/costmanagement/mgmt/2018-09-01-preview/costmanagement/client.go
  services/preview/costmanagement/mgmt/2018-09-01-preview/costmanagement/connector.go
  services/preview/costmanagement/mgmt/2018-09-01-preview/costmanagement/models.go
  services/preview/costmanagement/mgmt/2018-09-01-preview/costmanagement/reportconfig.go
  services/preview/costmanagement/mgmt/2018-09-01-preview/costmanagement/resourcegroupdimensions.go
  services/preview/costmanagement/mgmt/2018-09-01-preview/costmanagement/subscriptiondimensions.go
  services/preview/costmanagement/mgmt/2018-09-01-preview/costmanagement/version.go
Labels: review

#2484 [AutoPR web/resource-manager] Add HyperV property for AppServicePlan and Site model and deprecating…
  services/web/mgmt/2018-02-01/web/models.go
Labels: RestPRMerged, review

#2527 [AutoPR] web/resource-manager
  services/web/mgmt/2018-02-01/web/models.go
Labels: ServicePR, review

#2532 [AutoPR containerregistry/resource-manager] Azure container registry build feature GA API specification and examples.
  profiles/preview/containerregistry/mgmt/containerregistry/models.go
  services/containerregistry/mgmt/2018-09-01/containerregistry/client.go
  services/containerregistry/mgmt/2018-09-01/containerregistry/models.go
  services/containerregistry/mgmt/2018-09-01/containerregistry/operations.go
  services/containerregistry/mgmt/2018-09-01/containerregistry/registries.go
  services/containerregistry/mgmt/2018-09-01/containerregistry/replications.go
  services/containerregistry/mgmt/2018-09-01/containerregistry/runs.go
  services/containerregistry/mgmt/2018-09-01/containerregistry/tasks.go
  services/containerregistry/mgmt/2018-09-01/containerregistry/version.go
  services/containerregistry/mgmt/2018-09-01/containerregistry/webhooks.go
Labels: RestPRMerged, review

#2528 [AutoPR network/resource-manager] Update required properties for Outbound Rules
  profiles/preview/network/mgmt/network/models.go
  services/network/mgmt/2018-06-01/network/models.go
  services/network/mgmt/2018-06-01/network/watchers.go
Labels: RestPRMerged, review

#2539 [AutoPR compute/resource-manager] RDBug 13056055 - Update description to deprecated.
  services/compute/mgmt/2018-06-01/compute/virtualmachinesizes.go
Labels: RestPRMerged, review

#2533 [AutoPR] containerregistry/resource-manager
  profiles/preview/containerregistry/mgmt/containerregistry/models.go
  services/containerregistry/mgmt/2018-09-01/containerregistry/client.go
  services/containerregistry/mgmt/2018-09-01/containerregistry/models.go
  services/containerregistry/mgmt/2018-09-01/containerregistry/operations.go
  services/containerregistry/mgmt/2018-09-01/containerregistry/registries.go
  services/containerregistry/mgmt/2018-09-01/containerregistry/replications.go
  services/containerregistry/mgmt/2018-09-01/containerregistry/runs.go
  services/containerregistry/mgmt/2018-09-01/containerregistry/tasks.go
  services/containerregistry/mgmt/2018-09-01/containerregistry/version.go
  services/containerregistry/mgmt/2018-09-01/containerregistry/webhooks.go
Labels: ServicePR, review

#2530 [AutoPR logic/resource-manager] Add new microsoft.logic version
  services/logic/mgmt/package-2018-07-preview/logic/client.go
  services/logic/mgmt/package-2018-07-preview/logic/integrationaccountagreements.go
  services/logic/mgmt/package-2018-07-preview/logic/integrationaccountassemblies.go
  services/logic/mgmt/package-2018-07-preview/logic/integrationaccountbatchconfigurations.go
  services/logic/mgmt/package-2018-07-preview/logic/integrationaccountcertificates.go
  services/logic/mgmt/package-2018-07-preview/logic/integrationaccountmaps.go
  services/logic/mgmt/package-2018-07-preview/logic/integrationaccountpartners.go
  services/logic/mgmt/package-2018-07-preview/logic/integrationaccounts.go
  services/logic/mgmt/package-2018-07-preview/logic/integrationaccountschemas.go
  services/logic/mgmt/package-2018-07-preview/logic/integrationaccountsessions.go
  services/logic/mgmt/package-2018-07-preview/logic/models.go
  services/logic/mgmt/package-2018-07-preview/logic/operations.go
  services/logic/mgmt/package-2018-07-preview/logic/version.go
  services/logic/mgmt/package-2018-07-preview/logic/workflowrunactionrepetitions.go
  services/logic/mgmt/package-2018-07-preview/logic/workflowrunactions.go
  services/logic/mgmt/package-2018-07-preview/logic/workflowrunactionscoperepetitions.go
  services/logic/mgmt/package-2018-07-preview/logic/workflowrunoperations.go
  services/logic/mgmt/package-2018-07-preview/logic/workflowruns.go
  services/logic/mgmt/package-2018-07-preview/logic/workflows.go
  services/logic/mgmt/package-2018-07-preview/logic/workflowtriggerhistories.go
  services/logic/mgmt/package-2018-07-preview/logic/workflowtriggers.go
  services/logic/mgmt/package-2018-07-preview/logic/workflowversions.go
  services/logic/mgmt/package-2018-07-preview/logic/workflowversiontriggers.go
Labels: RestPRMerged, review

#2548 [AutoPR containerinstance/resource-manager] Fix Go SDK codegen for containerinstance
  profiles/preview/containerinstance/mgmt/containerinstance/models.go
  services/containerinstance/mgmt/2018-06-01/containerinstance/client.go
  services/containerinstance/mgmt/2018-06-01/containerinstance/container.go
  services/containerinstance/mgmt/2018-06-01/containerinstance/containergroups.go
  services/containerinstance/mgmt/2018-06-01/containerinstance/containergroupusage.go
  services/containerinstance/mgmt/2018-06-01/containerinstance/containerlogs.go
  services/containerinstance/mgmt/2018-06-01/containerinstance/models.go
  services/containerinstance/mgmt/2018-06-01/containerinstance/operations.go
  services/containerinstance/mgmt/2018-06-01/containerinstance/startcontainer.go
  services/containerinstance/mgmt/2018-06-01/containerinstance/version.go
Labels: RestPRMerged, review

#2526 [AutoPR iothub/resource-manager] Add Twin property to TestRouteAPI and TestAllRoutes API. This is an optional parameter to these APIs.
  profiles/preview/iothub/mgmt/devices/models.go
  services/iothub/mgmt/2018-04-01/devices/models.go
Labels: RestPRMerged, review

#2550 [AutoPR logic/resource-manager] Fix Go SDK codegen for logic
  services/preview/logic/mgmt/package-2018-07-preview/logic/client.go
  services/preview/logic/mgmt/package-2018-07-preview/logic/integrationaccountagreements.go
  services/preview/logic/mgmt/package-2018-07-preview/logic/integrationaccountassemblies.go
  services/preview/logic/mgmt/package-2018-07-preview/logic/integrationaccountbatchconfigurations.go
  services/preview/logic/mgmt/package-2018-07-preview/logic/integrationaccountcertificates.go
  services/preview/logic/mgmt/package-2018-07-preview/logic/integrationaccountmaps.go
  services/preview/logic/mgmt/package-2018-07-preview/logic/integrationaccountpartners.go
  services/preview/logic/mgmt/package-2018-07-preview/logic/integrationaccounts.go
  services/preview/logic/mgmt/package-2018-07-preview/logic/integrationaccountschemas.go
  services/preview/logic/mgmt/package-2018-07-preview/logic/integrationaccountsessions.go
  services/preview/logic/mgmt/package-2018-07-preview/logic/models.go
  services/preview/logic/mgmt/package-2018-07-preview/logic/operations.go
  services/preview/logic/mgmt/package-2018-07-preview/logic/version.go
  services/preview/logic/mgmt/package-2018-07-preview/logic/workflowrunactionrepetitions.go
  services/preview/logic/mgmt/package-2018-07-preview/logic/workflowrunactions.go
  services/preview/logic/mgmt/package-2018-07-preview/logic/workflowrunactionscoperepetitions.go
  services/preview/logic/mgmt/package-2018-07-preview/logic/workflowrunoperations.go
  services/preview/logic/mgmt/package-2018-07-preview/logic/workflowruns.go
  services/preview/logic/mgmt/package-2018-07-preview/logic/workflows.go
  services/preview/logic/mgmt/package-2018-07-preview/logic/workflowtriggerhistories.go
  services/preview/logic/mgmt/package-2018-07-preview/logic/workflowtriggers.go
  services/preview/logic/mgmt/package-2018-07-preview/logic/workflowversions.go
  services/preview/logic/mgmt/package-2018-07-preview/logic/workflowversiontriggers.go
Labels: RestPRMerged, review

#2505 [AutoPR web/resource-manager] WebApps - Add ResourceHealthMetadata.json to readme.md for SDK generation
  profiles/preview/web/mgmt/web/models.go
  services/web/mgmt/2018-02-01/web/models.go
  services/web/mgmt/2018-02-01/web/resourcehealthmetadata.go
Labels: RestPRMerged, review

#2549 [AutoPR] containerinstance/resource-manager
  profiles/preview/containerinstance/mgmt/containerinstance/models.go
  services/containerinstance/mgmt/2018-06-01/containerinstance/client.go
  services/containerinstance/mgmt/2018-06-01/containerinstance/container.go
  services/containerinstance/mgmt/2018-06-01/containerinstance/containergroups.go
  services/containerinstance/mgmt/2018-06-01/containerinstance/containergroupusage.go
  services/containerinstance/mgmt/2018-06-01/containerinstance/containerlogs.go
  services/containerinstance/mgmt/2018-06-01/containerinstance/models.go
  services/containerinstance/mgmt/2018-06-01/containerinstance/operations.go
  services/containerinstance/mgmt/2018-06-01/containerinstance/startcontainer.go
  services/containerinstance/mgmt/2018-06-01/containerinstance/version.go
Labels: ServicePR, review

#2552 [AutoPR] iothub/resource-manager
  profiles/preview/iothub/mgmt/devices/models.go
  services/iothub/mgmt/2018-04-01/devices/models.go
Labels: ServicePR, review

#2553 [AutoPR containerregistry/resource-manager] Renamed BuildTask to FileTask and RunTask to EncodedTask in Azure Container registry Build GA swagger
  profiles/preview/containerregistry/mgmt/containerregistry/models.go
  services/containerregistry/mgmt/2018-09-01/containerregistry/models.go
Labels: RestPRMerged, review

#2554 [AutoPR] logic/resource-manager
  services/preview/logic/mgmt/package-2018-07-preview/logic/client.go
  services/preview/logic/mgmt/package-2018-07-preview/logic/integrationaccountagreements.go
  services/preview/logic/mgmt/package-2018-07-preview/logic/integrationaccountassemblies.go
  services/preview/logic/mgmt/package-2018-07-preview/logic/integrationaccountbatchconfigurations.go
  services/preview/logic/mgmt/package-2018-07-preview/logic/integrationaccountcertificates.go
  services/preview/logic/mgmt/package-2018-07-preview/logic/integrationaccountmaps.go
  services/preview/logic/mgmt/package-2018-07-preview/logic/integrationaccountpartners.go
  services/preview/logic/mgmt/package-2018-07-preview/logic/integrationaccounts.go
  services/preview/logic/mgmt/package-2018-07-preview/logic/integrationaccountschemas.go
  services/preview/logic/mgmt/package-2018-07-preview/logic/integrationaccountsessions.go
  services/preview/logic/mgmt/package-2018-07-preview/logic/models.go
  services/preview/logic/mgmt/package-2018-07-preview/logic/operations.go
  services/preview/logic/mgmt/package-2018-07-preview/logic/version.go
  services/preview/logic/mgmt/package-2018-07-preview/logic/workflowrunactionrepetitions.go
  services/preview/logic/mgmt/package-2018-07-preview/logic/workflowrunactions.go
  services/preview/logic/mgmt/package-2018-07-preview/logic/workflowrunactionscoperepetitions.go
  services/preview/logic/mgmt/package-2018-07-preview/logic/workflowrunoperations.go
  services/preview/logic/mgmt/package-2018-07-preview/logic/workflowruns.go
  services/preview/logic/mgmt/package-2018-07-preview/logic/workflows.go
  services/preview/logic/mgmt/package-2018-07-preview/logic/workflowtriggerhistories.go
  services/preview/logic/mgmt/package-2018-07-preview/logic/workflowtriggers.go
  services/preview/logic/mgmt/package-2018-07-preview/logic/workflowversions.go
  services/preview/logic/mgmt/package-2018-07-preview/logic/workflowversiontriggers.go
Labels: ServicePR, review

#2562 [AutoPR compute/resource-manager] Update Go SDK for compute
  profiles/preview/compute/mgmt/compute/models.go
  services/compute/mgmt/2018-06-01/compute/client.go
  services/compute/mgmt/2018-06-01/compute/containerservices.go
  services/compute/mgmt/2018-06-01/compute/disks.go
  services/compute/mgmt/2018-06-01/compute/models.go
  services/compute/mgmt/2018-06-01/compute/resourceskus.go
  services/compute/mgmt/2018-06-01/compute/snapshots.go
Labels: RestPRMerged, review

#2559 [AutoPR] containerregistry/resource-manager
  profiles/preview/containerregistry/mgmt/containerregistry/models.go
  services/containerregistry/mgmt/2018-09-01/containerregistry/models.go
Labels: ServicePR, review

#2563 [AutoPR] compute/resource-manager
  profiles/preview/compute/mgmt/compute/models.go
  services/compute/mgmt/2018-06-01/compute/client.go
  services/compute/mgmt/2018-06-01/compute/containerservices.go
  services/compute/mgmt/2018-06-01/compute/disks.go
  services/compute/mgmt/2018-06-01/compute/models.go
  services/compute/mgmt/2018-06-01/compute/resourceskus.go
  services/compute/mgmt/2018-06-01/compute/snapshots.go
Labels: ServicePR, review

#2557 [AutoPR automation/resource-manager] Fixing the spec for DSCConfigurations.
  services/automation/mgmt/2015-10-31/automation/dscconfiguration.go
  services/preview/automation/mgmt/2017-05-15-preview/automation/dscconfiguration.go
  services/preview/automation/mgmt/2018-01-preview/automation/dscconfiguration.go
Labels: RestPRMerged, review

#2565 [AutoPR] automation/resource-manager
  services/automation/mgmt/2015-10-31/automation/dscconfiguration.go
  services/preview/automation/mgmt/2017-05-15-preview/automation/dscconfiguration.go
  services/preview/automation/mgmt/2018-01-preview/automation/dscconfiguration.go
Labels: ServicePR, review

#2566 [AutoPR] datafactory/resource-manager
  profiles/preview/datafactory/mgmt/datafactory/models.go
  services/datafactory/mgmt/2018-06-01/datafactory/models.go
Labels: ServicePR, review

#2568 Add Go 1.11 to CI and update dependencies.
  .travis.yml
  Gopkg.lock
  services/web/mgmt/2016-09-01/web/apps.go
  services/web/mgmt/2018-02-01/web/apps.go
  storage/authorization_test.go
Labels: review

#2572 update from latest swaggers
  profiles/preview/preview/cognitiveservices/visualsearch/models.go
  profiles/preview/preview/costmanagement/mgmt/costmanagement/models.go
  profiles/preview/web/mgmt/web/models.go
  services/powerbiembedded/mgmt/2016-01-29/powerbiembedded/models.go
  services/preview/cognitiveservices/v1.0/visualsearch/images.go
  services/preview/cognitiveservices/v1.0/visualsearch/models.go
  services/preview/costmanagement/mgmt/2018-08-01-preview/costmanagement/client.go
  services/preview/costmanagement/mgmt/2018-08-01-preview/costmanagement/models.go
  services/preview/costmanagement/mgmt/2018-08-01-preview/costmanagement/report.go
  services/preview/costmanagement/mgmt/2018-08-01-preview/costmanagement/reportconfig.go
  services/streamanalytics/mgmt/2016-03-01/streamanalytics/functions.go
  services/streamanalytics/mgmt/2016-03-01/streamanalytics/inputs.go
  services/streamanalytics/mgmt/2016-03-01/streamanalytics/outputs.go
  services/web/mgmt/2018-02-01/web/models.go
  services/web/mgmt/2018-02-01/web/resourcehealthmetadata.go
Labels: review

#2545 [AutoPR] security/resource-manager
  profiles/preview/preview/security/mgmt/security/models.go
  services/preview/security/mgmt/2017-08-01-preview/security/models.go
  services/preview/security/mgmt/2017-08-01-preview/security/settings.go
Labels: ServicePR, review

#2581 [AutoPR logic/resource-manager] Fix Go SDK package directory for logic 2018-07-01-preview
  profiles/preview/preview/logic/mgmt/logic/models.go
  services/preview/logic/mgmt/2018-07-01-preview/logic/client.go
  services/preview/logic/mgmt/2018-07-01-preview/logic/integrationaccountagreements.go
  services/preview/logic/mgmt/2018-07-01-preview/logic/integrationaccountassemblies.go
  services/preview/logic/mgmt/2018-07-01-preview/logic/integrationaccountbatchconfigurations.go
  services/preview/logic/mgmt/2018-07-01-preview/logic/integrationaccountcertificates.go
  services/preview/logic/mgmt/2018-07-01-preview/logic/integrationaccountmaps.go
  services/preview/logic/mgmt/2018-07-01-preview/logic/integrationaccountpartners.go
  services/preview/logic/mgmt/2018-07-01-preview/logic/integrationaccounts.go
  services/preview/logic/mgmt/2018-07-01-preview/logic/integrationaccountschemas.go
  services/preview/logic/mgmt/2018-07-01-preview/logic/integrationaccountsessions.go
  services/preview/logic/mgmt/2018-07-01-preview/logic/models.go
  services/preview/logic/mgmt/2018-07-01-preview/logic/operations.go
  services/preview/logic/mgmt/2018-07-01-preview/logic/version.go
  services/preview/logic/mgmt/2018-07-01-preview/logic/workflowrunactionrepetitions.go
  services/preview/logic/mgmt/2018-07-01-preview/logic/workflowrunactions.go
  services/preview/logic/mgmt/2018-07-01-preview/logic/workflowrunactionscoperepetitions.go
  services/preview/logic/mgmt/2018-07-01-preview/logic/workflowrunoperations.go
  services/preview/logic/mgmt/2018-07-01-preview/logic/workflowruns.go
  services/preview/logic/mgmt/2018-07-01-preview/logic/workflows.go
  services/preview/logic/mgmt/2018-07-01-preview/logic/workflowtriggerhistories.go
  services/preview/logic/mgmt/2018-07-01-preview/logic/workflowtriggers.go
  services/preview/logic/mgmt/2018-07-01-preview/logic/workflowversions.go
  services/preview/logic/mgmt/2018-07-01-preview/logic/workflowversiontriggers.go
Labels: RestPRMerged, review

#2582 [AutoPR] logic/resource-manager
  profiles/preview/preview/logic/mgmt/logic/models.go
  services/preview/logic/mgmt/2018-07-01-preview/logic/client.go
  services/preview/logic/mgmt/2018-07-01-preview/logic/integrationaccountagreements.go
  services/preview/logic/mgmt/2018-07-01-preview/logic/integrationaccountassemblies.go
  services/preview/logic/mgmt/2018-07-01-preview/logic/integrationaccountbatchconfigurations.go
  services/preview/logic/mgmt/2018-07-01-preview/logic/integrationaccountcertificates.go
  services/preview/logic/mgmt/2018-07-01-preview/logic/integrationaccountmaps.go
  services/preview/logic/mgmt/2018-07-01-preview/logic/integrationaccountpartners.go
  services/preview/logic/mgmt/2018-07-01-preview/logic/integrationaccounts.go
  services/preview/logic/mgmt/2018-07-01-preview/logic/integrationaccountschemas.go
  services/preview/logic/mgmt/2018-07-01-preview/logic/integrationaccountsessions.go
  services/preview/logic/mgmt/2018-07-01-preview/logic/models.go
  services/preview/logic/mgmt/2018-07-01-preview/logic/operations.go
  services/preview/logic/mgmt/2018-07-01-preview/logic/version.go
  services/preview/logic/mgmt/2018-07-01-preview/logic/workflowrunactionrepetitions.go
  services/preview/logic/mgmt/2018-07-01-preview/logic/workflowrunactions.go
  services/preview/logic/mgmt/2018-07-01-preview/logic/workflowrunactionscoperepetitions.go
  services/preview/logic/mgmt/2018-07-01-preview/logic/workflowrunoperations.go
  services/preview/logic/mgmt/2018-07-01-preview/logic/workflowruns.go
  services/preview/logic/mgmt/2018-07-01-preview/logic/workflows.go
  services/preview/logic/mgmt/2018-07-01-preview/logic/workflowtriggerhistories.go
  services/preview/logic/mgmt/2018-07-01-preview/logic/workflowtriggers.go
  services/preview/logic/mgmt/2018-07-01-preview/logic/workflowversions.go
  services/preview/logic/mgmt/2018-07-01-preview/logic/workflowversiontriggers.go
Labels: ServicePR, review

#2587 update dependencies
  Gopkg.lock
  Gopkg.toml
Labels: review

#2594 [AutoPR network/resource-manager] Azure Firewall FQDN Tag top level resource
  services/web/mgmt/2016-09-01/web/apps.go
  services/web/mgmt/2018-02-01/web/apps.go
Labels: RestPRMerged
