Repository Azure/azure-sdk-for-go, pull requests merged in 2018-12, with the labels that each got.

#3458 [AutoPR compute/resource-manager] updated Reimage API documentation in compute json for ephemeral os disks
  services/compute/mgmt/2018-06-01/compute/models.go
  services/compute/mgmt/2018-06-01/compute/virtualmachines.go
  services/compute/mgmt/2018-06-01/compute/virtualmachinescalesets.go
  services/compute/mgmt/2018-10-01/compute/models.go
  services/compute/mgmt/2018-10-01/compute/virtualmachines.go
  services/compute/mgmt/2018-10-01/compute/virtualmachinescalesets.go
Labels: RestPRMerged, review

#3487 [AutoPR eventgrid/resource-manager] typo: eventgrid/Microsoft.EventGrid
  services/eventgrid/mgmt/2018-01-01/eventgrid/models.go
  services/preview/eventgrid/mgmt/2017-06-15-preview/eventgrid/models.go
  services/preview/eventgrid/mgmt/2017-09-15-preview/eventgrid/models.go
  services/preview/eventgrid/mgmt/2018-05-01-preview/eventgrid/models.go
  services/preview/eventgrid/mgmt/2018-09-15-preview/eventgrid/models.go
Labels: RestPRMerged, review

#3481 [AutoPR datamigration/resource-manager] typo: Microsoft.DataMigration
  services/datamigration/mgmt/2018-04-19/datamigration/models.go
  services/datamigration/mgmt/2018-04-19/datamigration/tasks.go
  services/preview/datamigration/mgmt/2017-11-15-preview/datamigration/models.go
  services/preview/datamigration/mgmt/2017-11-15-preview/datamigration/tasks.go
  services/preview/datamigration/mgmt/2018-03-31-preview/datamigration/models.go
  services/preview/datamigration/mgmt/2018-03-31-preview/datamigration/tasks.go
  services/preview/datamigration/mgmt/2018-07-15-preview/datamigration/models.go
  services/preview/datamigration/mgmt/2018-07-15-preview/datamigration/tasks.go
Labels: RestPRMerged, review

#3477 [AutoPR databox/resource-manager] typo: Microsoft.DataBox
  services/databox/mgmt/2018-01-01/databox/models.go
Labels: RestPRMerged, review

#3469 [AutoPR compute/resource-manager] typo: Microsoft.ContainerService
  services/compute/mgmt/2018-06-01/compute/models.go
  services/compute/mgmt/2018-10-01/compute/models.go
  services/containerservice/mgmt/2016-03-30/containerservice/models.go
  services/containerservice/mgmt/2016-09-30/containerservice/models.go
  services/containerservice/mgmt/2017-01-31/containerservice/models.go
  services/preview/containerservice/mgmt/2015-11-01-preview/containerservice/models.go
Labels: RestPRMerged, review

#3462 [AutoPR cognitiveservices/data-plane/ContentModerator] typo: ContentModerator
  services/cognitiveservices/v1.0/contentmoderator/models.go
Labels: RestPRMerged, review

#3510 [AutoPR] monitor/resource-manager
  services/preview/monitor/mgmt/2017-05-01-preview/insights/models.go
  services/preview/monitor/mgmt/2018-03-01/insights/metricalerts.go
  services/preview/monitor/mgmt/2018-03-01/insights/models.go
  services/preview/monitor/mgmt/2018-09-01/insights/metricalerts.go
  services/preview/monitor/mgmt/2018-09-01/insights/models.go
Labels: ServicePR, review

#3512 [AutoPR] hdinsight/resource-manager
  services/preview/hdinsight/mgmt/2015-03-01-preview/hdinsight/models.go
Labels: ServicePR, review

#3513 [AutoPR] eventgrid/resource-manager
  services/eventgrid/mgmt/2018-01-01/eventgrid/models.go
  services/preview/eventgrid/mgmt/2017-06-15-preview/eventgrid/models.go
  services/preview/eventgrid/mgmt/2017-09-15-preview/eventgrid/models.go
  services/preview/eventgrid/mgmt/2018-05-01-preview/eventgrid/models.go
  services/preview/eventgrid/mgmt/2018-09-15-preview/eventgrid/models.go
Labels: ServicePR, review

#3514 [AutoPR] datamigration/resource-manager
  services/datamigration/mgmt/2018-04-19/datamigration/models.go
  services/datamigration/mgmt/2018-04-19/datamigration/tasks.go
  services/preview/datamigration/mgmt/2017-11-15-preview/datamigration/models.go
  services/preview/datamigration/mgmt/2017-11-15-preview/datamigration/tasks.go
  services/preview/datamigration/mgmt/2018-03-31-preview/datamigration/models.go
  services/preview/datamigration/mgmt/2018-03-31-preview/datamigration/tasks.go
  services/preview/datamigration/mgmt/2018-07-15-preview/datamigration/models.go
  services/preview/datamigration/mgmt/2018-07-15-preview/datamigration/tasks.go
Labels: ServicePR, review

#3516 [AutoPR] cognitiveservices/data-plane/ContentModerator
  services/cognitiveservices/v1.0/contentmoderator/models.go
Labels: ServicePR, review

#3518 [AutoPR operationalinsights/resource-manager] typo: operationalinsights/resource-manager/Microsoft.OperationalInsights
  services/operationalinsights/mgmt/2015-03-20/operationalinsights/models.go
  services/preview/operationalinsights/mgmt/2015-11-01-preview/operationalinsights/models.go
Labels: RestPRMerged, review

#3505 [AutoPR marketplaceordering/resource-manager] typo: marketplaceordering/resource-manager/Microsoft.MarketplaceOrdering
  services/marketplaceordering/mgmt/2015-06-01/marketplaceordering/models.go
Labels: RestPRMerged, review

#3494 [AutoPR keyvault/resource-manager] typo: resource-manager/Microsoft.KeyVault
  services/keyvault/mgmt/2016-10-01/keyvault/models.go
  services/keyvault/mgmt/2018-02-14/keyvault/models.go
Labels: RestPRMerged

#3475 [AutoPR cosmos-db/resource-manager] typo: Microsoft.DocumentDB
  services/cosmos-db/mgmt/2015-04-08/documentdb/databaseaccounts.go
Labels: RestPRMerged

#3515 [AutoPR] databox/resource-manager
  services/databox/mgmt/2018-01-01/databox/models.go
Labels: ServicePR, review

#3527 [AutoPR] marketplaceordering/resource-manager
  services/marketplaceordering/mgmt/2015-06-01/marketplaceordering/models.go
Labels: ServicePR, review

#3529 [AutoPR] graphrbac/data-plane
  services/graphrbac/1.6/graphrbac/models.go
  services/graphrbac/1.6/graphrbac/oauth2.go
Labels: ServicePR, review

#3530 [AutoPR] cosmos-db/resource-manager
  services/cosmos-db/mgmt/2015-04-08/documentdb/databaseaccounts.go
Labels: ServicePR, review

#3528 [AutoPR] keyvault/resource-manager
  services/keyvault/mgmt/2016-10-01/keyvault/models.go
  services/keyvault/mgmt/2018-02-14/keyvault/models.go
Labels: ServicePR, review

#3532 [AutoPR] deploymentmanager/resource-manager
  services/preview/deploymentmanager/mgmt/2018-09-01-preview/deploymentmanager/models.go
Labels: ServicePR, review

#3531 [AutoPR recoveryservicessiterecovery/resource-manager] Migration APIs
  profiles/latest/recoveryservices/mgmt/siterecovery/models.go
  profiles/preview/recoveryservices/mgmt/siterecovery/models.go
  profiles/preview/recoveryservices/mgmt/siterecovery/siterecoveryapi/models.go
  services/recoveryservices/mgmt/2018-01-10/siterecovery/migrationrecoverypoints.go
  services/recoveryservices/mgmt/2018-01-10/siterecovery/models.go
  services/recoveryservices/mgmt/2018-01-10/siterecovery/replicationmigrationitems.go
  services/recoveryservices/mgmt/2018-01-10/siterecovery/replicationrecoveryservicesproviders.go
  services/recoveryservices/mgmt/2018-01-10/siterecovery/siterecoveryapi/interfaces.go
Labels: RestPRMerged, review

#3521 [AutoPR policyinsights/resource-manager] typo: policyinsights/resource-manager/Microsoft.PolicyInsights
  services/preview/policyinsights/mgmt/2018-07-01-preview/policyinsights/models.go
Labels: RestPRMerged, review

#3499 [AutoPR logic/resource-manager] typo: logic/resource-manager/Microsoft.Logic
  services/preview/logic/mgmt/2015-08-01-preview/logic/models.go
Labels: RestPRMerged, review

#3484 [AutoPR devtestlabs/resource-manager] typo: Microsoft.DevTestLab
  services/devtestlabs/mgmt/2016-05-15/dtl/models.go
  services/devtestlabs/mgmt/2016-05-15/dtl/notificationchannels.go
  services/preview/devtestlabs/mgmt/2015-05-21-preview/dtl/models.go
Labels: RestPRMerged, review

#3471 [AutoPR consumption/resource-manager] typo: Microsoft.Consumption
  services/consumption/mgmt/2017-11-30/consumption/models.go
  services/consumption/mgmt/2017-11-30/consumption/usagedetails.go
  services/consumption/mgmt/2018-01-31/consumption/marketplaces.go
  services/consumption/mgmt/2018-01-31/consumption/models.go
  services/consumption/mgmt/2018-03-31/consumption/costtags.go
  services/consumption/mgmt/2018-03-31/consumption/marketplaces.go
  services/consumption/mgmt/2018-03-31/consumption/models.go
  services/consumption/mgmt/2018-03-31/consumption/reservationrecommendations.go
  services/consumption/mgmt/2018-06-30/consumption/costtags.go
  services/consumption/mgmt/2018-06-30/consumption/marketplaces.go
  services/consumption/mgmt/2018-06-30/consumption/models.go
  services/consumption/mgmt/2018-06-30/consumption/reservationrecommendations.go
  services/consumption/mgmt/2018-08-31/consumption/marketplaces.go
  services/consumption/mgmt/2018-08-31/consumption/models.go
  services/consumption/mgmt/2018-08-31/consumption/reservationrecommendations.go
  services/consumption/mgmt/2018-10-01/consumption/marketplaces.go
  services/consumption/mgmt/2018-10-01/consumption/models.go
  services/consumption/mgmt/2018-10-01/consumption/reservationrecommendations.go
  services/preview/consumption/mgmt/2017-04-24-preview/consumption/usagedetails.go
  services/preview/consumption/mgmt/2017-12-30-preview/consumption/models.go
Labels: RestPRMerged, review

#3463 [AutoPR cognitiveservices/data-plane/EntitySearch] typo: cognitiveservices/data-plane/EntitySearch
  services/cognitiveservices/v1.0/entitysearch/models.go
Labels: RestPRMerged, review

#3539 [AutoPR azurestack/resource-manager] typo: Microsoft.AzureStack
  services/azurestack/mgmt/2017-06-01/azurestack/models.go
Labels: RestPRMerged, review

#3533 [AutoPR] recoveryservicessiterecovery/resource-manager
  profiles/latest/recoveryservices/mgmt/siterecovery/models.go
  profiles/preview/recoveryservices/mgmt/siterecovery/models.go
  profiles/preview/recoveryservices/mgmt/siterecovery/siterecoveryapi/models.go
  services/recoveryservices/mgmt/2018-01-10/siterecovery/migrationrecoverypoints.go
  services/recoveryservices/mgmt/2018-01-10/siterecovery/models.go
  services/recoveryservices/mgmt/2018-01-10/siterecovery/replicationmigrationitems.go
  services/recoveryservices/mgmt/2018-01-10/siterecovery/replicationrecoveryservicesproviders.go
  services/recoveryservices/mgmt/2018-01-10/siterecovery/siterecoveryapi/interfaces.go
Labels: ServicePR, review

#3535 [AutoPR] logic/resource-manager
  services/preview/logic/mgmt/2015-08-01-preview/logic/models.go
Labels: ServicePR, review

#3536 [AutoPR] devtestlabs/resource-manager
  services/devtestlabs/mgmt/2016-05-15/dtl/models.go
  services/devtestlabs/mgmt/2016-05-15/dtl/notificationchannels.go
  services/preview/devtestlabs/mgmt/2015-05-21-preview/dtl/models.go
Labels: ServicePR, review

#3537 [AutoPR] consumption/resource-manager
  services/consumption/mgmt/2017-11-30/consumption/models.go
  services/consumption/mgmt/2017-11-30/consumption/usagedetails.go
  services/consumption/mgmt/2018-01-31/consumption/marketplaces.go
  services/consumption/mgmt/2018-01-31/consumption/models.go
  services/consumption/mgmt/2018-03-31/consumption/costtags.go
  services/consumption/mgmt/2018-03-31/consumption/marketplaces.go
  services/consumption/mgmt/2018-03-31/consumption/models.go
  services/consumption/mgmt/2018-03-31/consumption/reservationrecommendations.go
  services/consumption/mgmt/2018-06-30/consumption/costtags.go
  services/consumption/mgmt/2018-06-30/consumption/marketplaces.go
  services/consumption/mgmt/2018-06-30/consumption/models.go
  services/consumption/mgmt/2018-06-30/consumption/reservationrecommendations.go
  services/consumption/mgmt/2018-08-31/consumption/marketplaces.go
  services/consumption/mgmt/2018-08-31/consumption/models.go
  services/consumption/mgmt/2018-08-31/consumption/reservationrecommendations.go
  services/consumption/mgmt/2018-10-01/consumption/marketplaces.go
  services/consumption/mgmt/2018-10-01/consumption/models.go
  services/consumption/mgmt/2018-10-01/consumption/reservationrecommendations.go
  services/preview/consumption/mgmt/2017-04-24-preview/consumption/usagedetails.go
  services/preview/consumption/mgmt/2017-12-30-preview/consumption/models.go
Labels: ServicePR

#3538 [AutoPR] cognitiveservices/data-plane/EntitySearch
  services/cognitiveservices/v1.0/entitysearch/models.go
Labels: ServicePR, review

#3540 [AutoPR] azurestack/resource-manager
  services/azurestack/mgmt/2017-06-01/azurestack/models.go
Labels: ServicePR, review

#3464 [AutoPR cognitiveservices/data-plane/ImageSearch] typo: cognitiveservices/data-plane/ImageSearch
  services/cognitiveservices/v1.0/imagesearch/models.go
Labels: RestPRMerged, review

#3492 [AutoPR iothub/resource-manager] typo: iothub/Microsoft.Devices
  services/iothub/mgmt/2017-07-01/devices/models.go
  services/iothub/mgmt/2018-01-22/devices/models.go
  services/iothub/mgmt/2018-04-01/devices/models.go
Labels: RestPRMerged, review

#3507 [AutoPR migrate/resource-manager] typo: migrate/resource-manager/Microsoft.Migrate
  services/migrate/mgmt/2018-02-02/migrate/assessedmachines.go
  services/migrate/mgmt/2018-02-02/migrate/assessments.go
  services/migrate/mgmt/2018-02-02/migrate/models.go
Labels: RestPRMerged, review

#3524 [AutoPR recoveryservices/resource-manager] typo: recoveryservices/resource-manager/Microsoft.RecoveryServices
  services/recoveryservices/mgmt/2016-06-01/recoveryservices/models.go
Labels: RestPRMerged, review

#3485 [AutoPR dns/resource-manager] typo: dns/Microsoft.Network
  services/dns/mgmt/2016-04-01/dns/recordsets.go
  services/dns/mgmt/2016-04-01/dns/zones.go
  services/dns/mgmt/2017-09-01/dns/recordsets.go
  services/dns/mgmt/2017-09-01/dns/zones.go
  services/dns/mgmt/2017-10-01/dns/recordsets.go
  services/dns/mgmt/2017-10-01/dns/zones.go
  services/preview/dns/mgmt/2015-05-04-preview/dns/models.go
  services/preview/dns/mgmt/2018-03-01-preview/dns/recordsets.go
  services/preview/dns/mgmt/2018-03-01-preview/dns/zones.go
Labels: RestPRMerged, review

#3542 [AutoPR] cognitiveservices/data-plane/ImageSearch
  services/cognitiveservices/v1.0/imagesearch/models.go
Labels: ServicePR, review

#3525 [AutoPR recoveryservicesbackup/resource-manager] typo: recoveryservicesbackup/resource-manager/Microsoft.RecoveryServices
  services/recoveryservices/mgmt/2016-06-01/backup/models.go
  services/recoveryservices/mgmt/2016-06-01/backup/protecteditems.go
  services/recoveryservices/mgmt/2016-12-01/backup/models.go
  services/recoveryservices/mgmt/2017-07-01/backup/jobdetails.go
  services/recoveryservices/mgmt/2017-07-01/backup/models.go
Labels: RestPRMerged, review

#3520 [AutoPR operationsmanagement/resource-manager] typo: operationsmanagement/resource-manager/Microsoft.OperationsManagement
  services/preview/operationsmanagement/mgmt/2015-11-01-preview/operationsmanagement/managementassociations.go
  services/preview/operationsmanagement/mgmt/2015-11-01-preview/operationsmanagement/models.go
Labels: RestPRMerged, review

#3543 [AutoPR] iothub/resource-manager
  services/iothub/mgmt/2017-07-01/devices/models.go
  services/iothub/mgmt/2018-01-22/devices/models.go
  services/iothub/mgmt/2018-04-01/devices/models.go
Labels: ServicePR, review

#3544 [AutoPR] migrate/resource-manager
  services/migrate/mgmt/2018-02-02/migrate/assessedmachines.go
  services/migrate/mgmt/2018-02-02/migrate/assessments.go
  services/migrate/mgmt/2018-02-02/migrate/models.go
Labels: ServicePR, review

#3545 [AutoPR] recoveryservices/resource-manager
  services/recoveryservices/mgmt/2016-06-01/recoveryservices/models.go
Labels: ServicePR, review

#3546 [AutoPR] dns/resource-manager
  services/dns/mgmt/2016-04-01/dns/recordsets.go
  services/dns/mgmt/2016-04-01/dns/zones.go
  services/dns/mgmt/2017-09-01/dns/recordsets.go
  services/dns/mgmt/2017-09-01/dns/zones.go
  services/dns/mgmt/2017-10-01/dns/recordsets.go
  services/dns/mgmt/2017-10-01/dns/zones.go
  services/preview/dns/mgmt/2015-05-04-preview/dns/models.go
  services/preview/dns/mgmt/2018-03-01-preview/dns/recordsets.go
  services/preview/dns/mgmt/2018-03-01-preview/dns/zones.go
Labels: ServicePR, review

#3547 [AutoPR] recoveryservicesbackup/resource-manager
  services/recoveryservices/mgmt/2016-06-01/backup/models.go
  services/recoveryservices/mgmt/2016-06-01/backup/protecteditems.go
  services/recoveryservices/mgmt/2016-12-01/backup/models.go
  services/recoveryservices/mgmt/2017-07-01/backup/jobdetails.go
  services/recoveryservices/mgmt/2017-07-01/backup/models.go
Labels: ServicePR, review

#3548 [AutoPR] operationsmanagement/resource-manager
  services/preview/operationsmanagement/mgmt/2015-11-01-preview/operationsmanagement/managementassociations.go
  services/preview/operationsmanagement/mgmt/2015-11-01-preview/operationsmanagement/models.go
Labels: ServicePR, review

#3472 [AutoPR containerinstance/resource-manager] typo: Microsoft.ConainterInstance
  services/containerinstance/mgmt/2018-06-01/containerinstance/containergroups.go
Labels: RestPRMerged, review

#3486 [AutoPR eventgrid/data-plane] typo: Microsoft.Media
  services/eventgrid/2018-01-01/eventgrid/models.go
Labels: RestPRMerged, review

#3493 [AutoPR keyvault/data-plane] typo: data-plane/Microsoft.KeyVault
  services/keyvault/2015-06-01/keyvault/models.go
  services/keyvault/2016-10-01/keyvault/client.go
  services/keyvault/2016-10-01/keyvault/models.go
  services/keyvault/v7.0/keyvault/client.go
  services/keyvault/v7.0/keyvault/models.go
Labels: RestPRMerged, review

#3504 [AutoPR mariadb/resource-manager] typo: mariadb/resource-manager/Microsoft.DBforMariaDB
  services/preview/mariadb/mgmt/2018-06-01-preview/mariadb/models.go
Labels: RestPRMerged, review

#3554 [AutoPR labservices/resource-manager] Add first GA LabServices API
  profiles/preview/labservices/mgmt/ML/mlapi/models.go
  profiles/preview/labservices/mgmt/ML/models.go
  services/labservices/mgmt/2018-10-15/ML/client.go
  services/labservices/mgmt/2018-10-15/ML/environments.go
  services/labservices/mgmt/2018-10-15/ML/environmentsettings.go
  services/labservices/mgmt/2018-10-15/ML/galleryimages.go
  services/labservices/mgmt/2018-10-15/ML/globalusers.go
  services/labservices/mgmt/2018-10-15/ML/labaccounts.go
  services/labservices/mgmt/2018-10-15/ML/labs.go
  services/labservices/mgmt/2018-10-15/ML/mlapi/interfaces.go
  services/labservices/mgmt/2018-10-15/ML/models.go
  services/labservices/mgmt/2018-10-15/ML/operations.go
  services/labservices/mgmt/2018-10-15/ML/provideroperations.go
  services/labservices/mgmt/2018-10-15/ML/users.go
  services/labservices/mgmt/2018-10-15/ML/version.go
Labels: RestPRMerged, review

#3551 [AutoPR] eventgrid/data-plane
  services/eventgrid/2018-01-01/eventgrid/models.go
Labels: ServicePR, review

#3552 [AutoPR] keyvault/data-plane
  services/keyvault/2015-06-01/keyvault/models.go
  services/keyvault/2016-10-01/keyvault/client.go
  services/keyvault/2016-10-01/keyvault/models.go
  services/keyvault/v7.0/keyvault/client.go
  services/keyvault/v7.0/keyvault/models.go
Labels: ServicePR, review

#3553 [AutoPR] mariadb/resource-manager
  services/preview/mariadb/mgmt/2018-06-01-preview/mariadb/models.go
Labels: ServicePR, review

#3550 [AutoPR] containerinstance/resource-manager
  services/containerinstance/mgmt/2018-06-01/containerinstance/containergroups.go
Labels: ServicePR, review

#3467 [AutoPR cognitiveservices/resource-manager] typo: Microsoft.CognitiveServices
  services/cognitiveservices/mgmt/2017-04-18/cognitiveservices/checkskuavailability.go
  services/preview/cognitiveservices/mgmt/2016-02-01-preview/cognitiveservices/accounts.go
Labels: RestPRMerged, review

#3517 [AutoPR notificationhubs/resource-manager] typo: notificationhubs/resource-manager/Microsoft.NotificationHubs
  services/notificationhubs/mgmt/2014-09-01/notificationhubs/models.go
  services/notificationhubs/mgmt/2014-09-01/notificationhubs/namespaces.go
  services/notificationhubs/mgmt/2016-03-01/notificationhubs/models.go
  services/notificationhubs/mgmt/2016-03-01/notificationhubs/namespaces.go
  services/notificationhubs/mgmt/2017-04-01/notificationhubs/models.go
  services/notificationhubs/mgmt/2017-04-01/notificationhubs/namespaces.go
Labels: RestPRMerged, review

#3476 [AutoPR cost-management/resource-manager] typo: Microsoft.CostManagement
  services/costmanagement/mgmt/2018-05-31/costmanagement/billingaccountdimensions.go
  services/costmanagement/mgmt/2018-05-31/costmanagement/models.go
  services/costmanagement/mgmt/2018-05-31/costmanagement/resourcegroupdimensions.go
  services/costmanagement/mgmt/2018-05-31/costmanagement/subscriptiondimensions.go
  services/preview/costmanagement/mgmt/2018-08-01-preview/costmanagement/billingaccountdimensions.go
  services/preview/costmanagement/mgmt/2018-08-01-preview/costmanagement/models.go
  services/preview/costmanagement/mgmt/2018-08-01-preview/costmanagement/reports.go
  services/preview/costmanagement/mgmt/2018-08-01-preview/costmanagement/resourcegroupdimensions.go
  services/preview/costmanagement/mgmt/2018-08-01-preview/costmanagement/subscriptiondimensions.go
Labels: RestPRMerged, review

#3480 [AutoPR datalake-store/data-plane] typo: Microsoft.DataLakeStore
  services/datalake/store/2016-11-01/filesystem/filesystem.go
Labels: RestPRMerged, review

#3574 [AutoPR resources/resource-manager] typo: resources/resource-manager/Microsoft.Resources
  services/resources/mgmt/2015-11-01/resources/models.go
  services/resources/mgmt/2016-02-01/resources/models.go
  services/resources/mgmt/2016-07-01/resources/models.go
  services/resources/mgmt/2016-09-01/links/resourcelinks.go
  services/resources/mgmt/2016-09-01/resources/models.go
  services/resources/mgmt/2016-09-01/resources/resources.go
  services/resources/mgmt/2017-05-10/resources/models.go
  services/resources/mgmt/2018-02-01/resources/models.go
  services/resources/mgmt/2018-05-01/resources/models.go
Labels: RestPRMerged, review

#3560 [AutoPR] cognitiveservices/resource-manager
  services/cognitiveservices/mgmt/2017-04-18/cognitiveservices/checkskuavailability.go
  services/preview/cognitiveservices/mgmt/2016-02-01-preview/cognitiveservices/accounts.go
Labels: ServicePR, review

#3567 [AutoPR] notificationhubs/resource-manager
  services/notificationhubs/mgmt/2014-09-01/notificationhubs/models.go
  services/notificationhubs/mgmt/2014-09-01/notificationhubs/namespaces.go
  services/notificationhubs/mgmt/2016-03-01/notificationhubs/models.go
  services/notificationhubs/mgmt/2016-03-01/notificationhubs/namespaces.go
  services/notificationhubs/mgmt/2017-04-01/notificationhubs/models.go
  services/notificationhubs/mgmt/2017-04-01/notificationhubs/namespaces.go
Labels: ServicePR, review

#3568 [AutoPR] cost-management/resource-manager
  services/costmanagement/mgmt/2018-05-31/costmanagement/billingaccountdimensions.go
  services/costmanagement/mgmt/2018-05-31/costmanagement/models.go
  services/costmanagement/mgmt/2018-05-31/costmanagement/resourcegroupdimensions.go
  services/costmanagement/mgmt/2018-05-31/costmanagement/subscriptiondimensions.go
  services/preview/costmanagement/mgmt/2018-08-01-preview/costmanagement/billingaccountdimensions.go
  services/preview/costmanagement/mgmt/2018-08-01-preview/costmanagement/models.go
  services/preview/costmanagement/mgmt/2018-08-01-preview/costmanagement/reports.go
  services/preview/costmanagement/mgmt/2018-08-01-preview/costmanagement/resourcegroupdimensions.go
  services/preview/costmanagement/mgmt/2018-08-01-preview/costmanagement/subscriptiondimensions.go
Labels: ServicePR, review

#3570 [AutoPR] apimanagement/resource-manager
  profiles/preview/apimanagement/mgmt/apimanagement/apimanagementapi/models.go
  profiles/preview/apimanagement/mgmt/apimanagement/models.go
  profiles/preview/preview/apimanagement/mgmt/apimanagement/apimanagementapi/models.go
  profiles/preview/preview/apimanagement/mgmt/apimanagement/models.go
  services/apimanagement/mgmt/2016-07-07/apimanagement/models.go
  services/apimanagement/mgmt/2016-07-07/apimanagement/property.go
  services/apimanagement/mgmt/2016-07-07/apimanagement/reports.go
  services/apimanagement/mgmt/2016-07-07/apimanagement/subscriptions.go
  services/apimanagement/mgmt/2016-10-10/apimanagement/models.go
  services/apimanagement/mgmt/2016-10-10/apimanagement/property.go
  services/apimanagement/mgmt/2016-10-10/apimanagement/reports.go
  services/apimanagement/mgmt/2016-10-10/apimanagement/subscriptions.go
  services/apimanagement/mgmt/2017-03-01/apimanagement/diagnosticlogger.go
  services/apimanagement/mgmt/2017-03-01/apimanagement/models.go
  services/apimanagement/mgmt/2017-03-01/apimanagement/property.go
  services/apimanagement/mgmt/2017-03-01/apimanagement/reports.go
  services/apimanagement/mgmt/2017-03-01/apimanagement/subscription.go
  services/apimanagement/mgmt/2017-03-01/apimanagement/tagdescription.go
  services/apimanagement/mgmt/2018-01-01/apimanagement/apidiagnosticlogger.go
  services/apimanagement/mgmt/2018-01-01/apimanagement/apiissue.go
  services/apimanagement/mgmt/2018-01-01/apimanagement/apiissueattachment.go
  services/apimanagement/mgmt/2018-01-01/apimanagement/apiissuecomment.go
  services/apimanagement/mgmt/2018-01-01/apimanagement/apimanagementapi/interfaces.go
  services/apimanagement/mgmt/2018-01-01/apimanagement/diagnosticlogger.go
  services/apimanagement/mgmt/2018-01-01/apimanagement/models.go
  services/apimanagement/mgmt/2018-01-01/apimanagement/property.go
  services/apimanagement/mgmt/2018-01-01/apimanagement/reports.go
  services/apimanagement/mgmt/2018-01-01/apimanagement/serviceskus.go
  services/apimanagement/mgmt/2018-01-01/apimanagement/subscription.go
  services/apimanagement/mgmt/2018-01-01/apimanagement/tagdescription.go
  services/preview/apimanagement/mgmt/2018-06-01-preview/apimanagement/apiissue.go
  services/preview/apimanagement/mgmt/2018-06-01-preview/apimanagement/apiissueattachment.go
  services/preview/apimanagement/mgmt/2018-06-01-preview/apimanagement/apiissuecomment.go
  services/preview/apimanagement/mgmt/2018-06-01-preview/apimanagement/apimanagementapi/interfaces.go
  services/preview/apimanagement/mgmt/2018-06-01-preview/apimanagement/models.go
  services/preview/apimanagement/mgmt/2018-06-01-preview/apimanagement/property.go
  services/preview/apimanagement/mgmt/2018-06-01-preview/apimanagement/reports.go
  services/preview/apimanagement/mgmt/2018-06-01-preview/apimanagement/serviceskus.go
  services/preview/apimanagement/mgmt/2018-06-01-preview/apimanagement/subscription.go
  services/preview/apimanagement/mgmt/2018-06-01-preview/apimanagement/tagdescription.go
Labels: ServicePR, review

#3572 [AutoPR] machinelearningservices/resource-manager
  services/preview/machinelearning/mgmt/2018-03-01-preview/services/models.go
Labels: ServicePR, review

#3573 [AutoPR] datalake-store/data-plane
  services/datalake/store/2016-11-01/filesystem/filesystem.go
Labels: ServicePR, review

#3580 [AutoPR] resources/resource-manager
  services/resources/mgmt/2015-11-01/resources/models.go
  services/resources/mgmt/2016-02-01/resources/models.go
  services/resources/mgmt/2016-07-01/resources/models.go
  services/resources/mgmt/2016-09-01/links/resourcelinks.go
  services/resources/mgmt/2016-09-01/resources/models.go
  services/resources/mgmt/2016-09-01/resources/resources.go
  services/resources/mgmt/2017-05-10/resources/models.go
  services/resources/mgmt/2018-02-01/resources/models.go
  services/resources/mgmt/2018-05-01/resources/models.go
Labels: ServicePR, review

#3575 [AutoPR search/resource-manager] typo: search/resource-manager/Microsoft.Search
  services/search/mgmt/2015-08-19/search/models.go
Labels: RestPRMerged, review

#3581 [AutoPR] search/resource-manager
  services/search/mgmt/2015-08-19/search/models.go
Labels: ServicePR, review

#3582 [AutoPR labservices/resource-manager] fix Go SDK codegen for labservices
  profiles/preview/labservices/mgmt/labservices/labservicesapi/models.go
  profiles/preview/labservices/mgmt/labservices/models.go
  services/labservices/mgmt/2018-10-15/labservices/client.go
  services/labservices/mgmt/2018-10-15/labservices/environments.go
  services/labservices/mgmt/2018-10-15/labservices/environmentsettings.go
  services/labservices/mgmt/2018-10-15/labservices/galleryimages.go
  services/labservices/mgmt/2018-10-15/labservices/globalusers.go
  services/labservices/mgmt/2018-10-15/labservices/labaccounts.go
  services/labservices/mgmt/2018-10-15/labservices/labs.go
  services/labservices/mgmt/2018-10-15/labservices/labservicesapi/interfaces.go
  services/labservices/mgmt/2018-10-15/labservices/models.go
  services/labservices/mgmt/2018-10-15/labservices/operations.go
  services/labservices/mgmt/2018-10-15/labservices/provideroperations.go
  services/labservices/mgmt/2018-10-15/labservices/users.go
  services/labservices/mgmt/2018-10-15/labservices/version.go
Labels: RestPRMerged, review

#3566 [AutoPR redis/resource-manager] typo: redis/resource-manager/Microsoft.Cache
  services/redis/mgmt/2015-08-01/redis/models.go
  services/redis/mgmt/2016-04-01/redis/models.go
  services/redis/mgmt/2017-02-01/redis/models.go
  services/redis/mgmt/2017-10-01/redis/models.go
  services/redis/mgmt/2018-03-01/redis/models.go
Labels: RestPRMerged, review

#3583 [AutoPR] labservices/resource-manager
  profiles/preview/labservices/mgmt/labservices/labservicesapi/models.go
  profiles/preview/labservices/mgmt/labservices/models.go
  services/labservices/mgmt/2018-10-15/labservices/client.go
  services/labservices/mgmt/2018-10-15/labservices/environments.go
  services/labservices/mgmt/2018-10-15/labservices/environmentsettings.go
  services/labservices/mgmt/2018-10-15/labservices/galleryimages.go
  services/labservices/mgmt/2018-10-15/labservices/globalusers.go
  services/labservices/mgmt/2018-10-15/labservices/labaccounts.go
  services/labservices/mgmt/2018-10-15/labservices/labs.go
  services/labservices/mgmt/2018-10-15/labservices/labservicesapi/interfaces.go
  services/labservices/mgmt/2018-10-15/labservices/models.go
  services/labservices/mgmt/2018-10-15/labservices/operations.go
  services/labservices/mgmt/2018-10-15/labservices/provideroperations.go
  services/labservices/mgmt/2018-10-15/labservices/users.go
  services/labservices/mgmt/2018-10-15/labservices/version.go
Labels: ServicePR, review

#3586 [AutoPR] redis/resource-manager
  services/redis/mgmt/2015-08-01/redis/models.go
  services/redis/mgmt/2016-04-01/redis/models.go
  services/redis/mgmt/2017-02-01/redis/models.go
  services/redis/mgmt/2017-10-01/redis/models.go
  services/redis/mgmt/2018-03-01/redis/models.go
Labels: ServicePR

#3509 [AutoPR mysql/resource-manager] typo: mysql/resource-manager/Microsoft.DBforMySQL
  services/mysql/mgmt/2017-12-01/mysql/models.go
Labels: RestPRMerged

#3522 [AutoPR postgresql/resource-manager] typo: postgresql/resource-manager/Microsoft.DBforPostgreSQL
  services/postgresql/mgmt/2017-12-01/postgresql/models.go
Labels: RestPRMerged, review

#3500 [AutoPR managementgroups/resource-manager] typo: managementgroups/resource-manager/Microsoft.Management
  services/preview/resources/mgmt/2018-03-01-preview/managementgroups/entities.go
Labels: RestPRMerged, review

#3490 [AutoPR hanaonazure/resource-manager] typo: Microsoft.HanaOnAzure
  services/preview/hanaonazure/mgmt/2017-11-03-preview/hanaonazure/models.go
Labels: RestPRMerged

#3589 [AutoPR] postgresql/resource-manager
  services/postgresql/mgmt/2017-12-01/postgresql/models.go
Labels: ServicePR, review

#3590 [AutoPR] managementgroups/resource-manager
  services/preview/resources/mgmt/2018-03-01-preview/managementgroups/entities.go
Labels: ServicePR, review

#3591 [AutoPR] hanaonazure/resource-manager
  services/preview/hanaonazure/mgmt/2017-11-03-preview/hanaonazure/models.go
Labels: ServicePR, review

#3587 [AutoPR] workloadmonitor/resource-manager
  services/preview/workloadmonitor/mgmt/2018-08-31-preview/workloadmonitor/models.go
  services/preview/workloadmonitor/mgmt/2018-08-31-preview/workloadmonitor/notificationsettings.go
  services/preview/workloadmonitor/mgmt/2018-08-31-preview/workloadmonitor/workloadmonitorapi/interfaces.go
Labels: ServicePR, review

#3588 [AutoPR] mysql/resource-manager
  services/mysql/mgmt/2017-12-01/mysql/models.go
Labels: ServicePR, review

#3478 [AutoPR datafactory/resource-manager] typo: Microsoft.DataFactory
  services/preview/datafactory/mgmt/2017-09-01-preview/datafactory/models.go
Labels: RestPRMerged, review

#3565 [AutoPR recoveryservicessiterecovery/resource-manager] typo: recoveryservicessiterecovery/resource-manager/Microsoft.RecoveryServices
  services/recoveryservices/mgmt/2016-08-10/siterecovery/models.go
  services/recoveryservices/mgmt/2016-08-10/siterecovery/replicationjobs.go
  services/recoveryservices/mgmt/2016-08-10/siterecovery/replicationstorageclassificationmappings.go
  services/recoveryservices/mgmt/2016-08-10/siterecovery/replicationvcenters.go
  services/recoveryservices/mgmt/2018-01-10/siterecovery/models.go
  services/recoveryservices/mgmt/2018-01-10/siterecovery/replicationjobs.go
  services/recoveryservices/mgmt/2018-01-10/siterecovery/replicationstorageclassificationmappings.go
  services/recoveryservices/mgmt/2018-01-10/siterecovery/replicationvcenters.go
Labels: RestPRMerged, review

#3488 [AutoPR frontdoor/resource-manager] typo: frontdoor/Microsoft.Network
  services/preview/frontdoor/mgmt/2018-08-01-preview/frontdoor/models.go
  services/preview/frontdoor/mgmt/2018-08-01-preview/frontdoor/policies.go
Labels: RestPRMerged, review

#3483 [AutoPR deviceprovisioningservices/resource-manager] typo: Microsoft.Devices
  services/preview/provisioningservices/mgmt/2017-08-21-preview/iothub/models.go
  services/provisioningservices/mgmt/2017-11-15/iothub/dpscertificate.go
  services/provisioningservices/mgmt/2017-11-15/iothub/models.go
  services/provisioningservices/mgmt/2018-01-22/iothub/dpscertificate.go
  services/provisioningservices/mgmt/2018-01-22/iothub/models.go
Labels: RestPRMerged, review

#3594 [AutoPR] datafactory/resource-manager
  services/preview/datafactory/mgmt/2017-09-01-preview/datafactory/models.go
Labels: ServicePR, review

#3595 [AutoPR] recoveryservicessiterecovery/resource-manager
  services/recoveryservices/mgmt/2016-08-10/siterecovery/models.go
  services/recoveryservices/mgmt/2016-08-10/siterecovery/replicationjobs.go
  services/recoveryservices/mgmt/2016-08-10/siterecovery/replicationstorageclassificationmappings.go
  services/recoveryservices/mgmt/2016-08-10/siterecovery/replicationvcenters.go
  services/recoveryservices/mgmt/2018-01-10/siterecovery/models.go
  services/recoveryservices/mgmt/2018-01-10/siterecovery/replicationjobs.go
  services/recoveryservices/mgmt/2018-01-10/siterecovery/replicationstorageclassificationmappings.go
  services/recoveryservices/mgmt/2018-01-10/siterecovery/replicationvcenters.go
Labels: ServicePR, review

#3597 [AutoPR] frontdoor/resource-manager
  services/preview/frontdoor/mgmt/2018-08-01-preview/frontdoor/models.go
  services/preview/frontdoor/mgmt/2018-08-01-preview/frontdoor/policies.go
Labels: ServicePR, review

#3598 [AutoPR] deviceprovisioningservices/resource-manager
  services/preview/provisioningservices/mgmt/2017-08-21-preview/iothub/models.go
  services/provisioningservices/mgmt/2017-11-15/iothub/dpscertificate.go
  services/provisioningservices/mgmt/2017-11-15/iothub/models.go
  services/provisioningservices/mgmt/2018-01-22/iothub/dpscertificate.go
  services/provisioningservices/mgmt/2018-01-22/iothub/models.go
Labels: ServicePR, review

#3466 [AutoPR cognitiveservices/data-plane/LUIS/Authoring/cognitiveservices/data-plane/LUIS/Runtime] typo: cognitiveservices/data-plane/LUIS
  services/cognitiveservices/v2.0/luis/authoring/apps.go
  services/cognitiveservices/v2.0/luis/authoring/models.go
  services/cognitiveservices/v2.0/luis/runtime/models.go
Labels: RestPRMerged, review

#3479 [AutoPR datalake-analytics/resource-manager/datalake-store/resource-manager/datalake-analytics/data-plane] typo: Microsoft.DataLakeAnalytics
  services/datalake/analytics/2016-11-01-preview/catalog/models.go
  services/datalake/analytics/2016-11-01/job/models.go
  services/preview/datalake/analytics/2015-10-01-preview/catalog/models.go
  services/preview/datalake/analytics/2015-11-01-preview/job/job.go
  services/preview/datalake/analytics/2015-11-01-preview/job/models.go
  services/preview/datalake/analytics/2016-03-20-preview/job/job.go
  services/preview/datalake/analytics/2016-03-20-preview/job/models.go
  services/preview/datalake/analytics/2017-09-01-preview/job/models.go
  services/preview/datalake/analytics/mgmt/2015-10-01-preview/account/account.go
  services/preview/datalake/analytics/mgmt/2015-10-01-preview/account/models.go
  services/preview/datalake/store/mgmt/2015-10-01-preview/account/account.go
  services/preview/datalake/store/mgmt/2015-10-01-preview/account/models.go
Labels: RestPRMerged, review

#3473 [AutoPR containerregistry/data-plane/containerregistry/resource-manager] typo: Microsoft.ContainerRegistry
  profiles/latest/containerregistry/mgmt/containerregistry/models.go
  profiles/preview/containerregistry/mgmt/containerregistry/models.go
  profiles/preview/preview/containerregistry/mgmt/containerregistry/models.go
  services/containerregistry/mgmt/2017-03-01/containerregistry/registries.go
  services/containerregistry/mgmt/2017-10-01/containerregistry/models.go
  services/containerregistry/mgmt/2017-10-01/containerregistry/registries.go
  services/containerregistry/mgmt/2017-10-01/containerregistry/replications.go
  services/containerregistry/mgmt/2017-10-01/containerregistry/webhooks.go
  services/containerregistry/mgmt/2018-09-01/containerregistry/models.go
  services/containerregistry/mgmt/2018-09-01/containerregistry/registries.go
  services/containerregistry/mgmt/2018-09-01/containerregistry/replications.go
  services/containerregistry/mgmt/2018-09-01/containerregistry/runs.go
  services/containerregistry/mgmt/2018-09-01/containerregistry/tasks.go
  services/containerregistry/mgmt/2018-09-01/containerregistry/webhooks.go
  services/preview/containerregistry/mgmt/2017-06-01-preview/containerregistry/models.go
  services/preview/containerregistry/mgmt/2018-02-01/containerregistry/models.go
  services/preview/containerregistry/mgmt/2018-02-01/containerregistry/registries.go
  services/preview/containerregistry/mgmt/2018-02-01/containerregistry/replications.go
  services/preview/containerregistry/mgmt/2018-02-01/containerregistry/webhooks.go
Labels: RestPRMerged, review

#3564 [AutoPR servicefabric/data-plane] Swagger specification for Service Fabric runtime version 6.4
  profiles/preview/servicefabric/servicefabric/models.go
  profiles/preview/servicefabric/servicefabric/servicefabricapi/models.go
  services/servicefabric/6.3/servicefabric/client.go
  services/servicefabric/6.3/servicefabric/models.go
  services/servicefabric/6.3/servicefabric/servicefabricapi/interfaces.go
  services/servicefabric/6.3/servicefabric/version.go
  services/servicefabric/6.4/servicefabric/client.go
  services/servicefabric/6.4/servicefabric/meshapplication.go
  services/servicefabric/6.4/servicefabric/meshcodepackage.go
  services/servicefabric/6.4/servicefabric/meshgateway.go
  services/servicefabric/6.4/servicefabric/meshnetwork.go
  services/servicefabric/6.4/servicefabric/meshsecret.go
  services/servicefabric/6.4/servicefabric/meshsecretvalue.go
  services/servicefabric/6.4/servicefabric/meshservice.go
  services/servicefabric/6.4/servicefabric/meshservicereplica.go
  services/servicefabric/6.4/servicefabric/meshvolume.go
  services/servicefabric/6.4/servicefabric/models.go
  services/servicefabric/6.4/servicefabric/servicefabricapi/interfaces.go
  services/servicefabric/6.4/servicefabric/version.go
Labels: RestPRMerged, review

#3605 [AutoPR signalr/resource-manager] typo: signalr/resource-manager/Microsoft.SignalRService
  services/preview/signalr/mgmt/2018-03-01-preview/signalr/models.go
  services/signalr/mgmt/2018-10-01/signalr/models.go
Labels: RestPRMerged, review

#3612 [AutoPR] signalr/resource-manager
  services/preview/signalr/mgmt/2018-03-01-preview/signalr/models.go
  services/signalr/mgmt/2018-10-01/signalr/models.go
Labels: ServicePR, review

#3584 [AutoPR msi/resource-manager] MSI move 2018-11-30 version in stable folder
  profiles/preview/msi/mgmt/msi/models.go
  profiles/preview/msi/mgmt/msi/msiapi/models.go
  services/msi/mgmt/2018-11-30/msi/client.go
  services/msi/mgmt/2018-11-30/msi/models.go
  services/msi/mgmt/2018-11-30/msi/msiapi/interfaces.go
  services/msi/mgmt/2018-11-30/msi/operations.go
  services/msi/mgmt/2018-11-30/msi/userassignedidentities.go
  services/msi/mgmt/2018-11-30/msi/version.go
Labels: RestPRMerged, review

#3614 [AutoPR] msi/resource-manager
  profiles/preview/msi/mgmt/msi/models.go
  profiles/preview/msi/mgmt/msi/msiapi/models.go
  services/msi/mgmt/2018-11-30/msi/client.go
  services/msi/mgmt/2018-11-30/msi/models.go
  services/msi/mgmt/2018-11-30/msi/msiapi/interfaces.go
  services/msi/mgmt/2018-11-30/msi/operations.go
  services/msi/mgmt/2018-11-30/msi/userassignedidentities.go
  services/msi/mgmt/2018-11-30/msi/version.go
Labels: ServicePR, review

#3609 [AutoPR storagesync/resource-manager] typo: storagesync/resource-manager/Microsoft.StorageSync
  profiles/preview/preview/storagesync/mgmt/storagesync/models.go
  services/preview/storagesync/mgmt/2018-10-01/storagesync/models.go
  services/preview/storagesync/mgmt/2018-10-01/storagesync/serverendpoints.go
  services/storagesync/mgmt/2018-04-02/storagesync/models.go
  services/storagesync/mgmt/2018-04-02/storagesync/serverendpoints.go
  services/storagesync/mgmt/2018-07-01/storagesync/models.go
  services/storagesync/mgmt/2018-07-01/storagesync/serverendpoints.go
Labels: RestPRMerged, review

#3577 [AutoPR security/resource-manager] typo: security/resource-manager/Microsoft.Security
  services/preview/security/mgmt/2017-08-01-preview/security/alerts.go
  services/preview/security/mgmt/2017-08-01-preview/security/models.go
Labels: RestPRMerged, review

#3600 [AutoPR hanaonazure/resource-manager] Update HanaOnAzure Swagger to support new SKU: S96
  profiles/preview/preview/hanaonazure/mgmt/hanaonazure/models.go
  services/preview/hanaonazure/mgmt/2017-11-03-preview/hanaonazure/models.go
Labels: RestPRMerged, review

#3578 [AutoPR service-map/resource-manager] typo: service-map/resource-manager/Microsoft.OperationalInsights
  services/preview/operationalinsights/mgmt/2015-11-01-preview/servicemap/models.go
Labels: RestPRMerged

#3616 [AutoPR] storagesync/resource-manager
  profiles/preview/preview/storagesync/mgmt/storagesync/models.go
  services/preview/storagesync/mgmt/2018-10-01/storagesync/models.go
  services/preview/storagesync/mgmt/2018-10-01/storagesync/serverendpoints.go
  services/storagesync/mgmt/2018-04-02/storagesync/models.go
  services/storagesync/mgmt/2018-04-02/storagesync/serverendpoints.go
  services/storagesync/mgmt/2018-07-01/storagesync/models.go
  services/storagesync/mgmt/2018-07-01/storagesync/serverendpoints.go
Labels: ServicePR

#3617 [AutoPR] security/resource-manager
  services/preview/security/mgmt/2017-08-01-preview/security/alerts.go
  services/preview/security/mgmt/2017-08-01-preview/security/models.go
Labels: ServicePR, review

#3618 [AutoPR devtestlabs/resource-manager] fix Go SDK codegen for devtestlabs package-2018-09
  profiles/preview/devtestlabs/mgmt/dtl/dtlapi/models.go
  profiles/preview/devtestlabs/mgmt/dtl/models.go
  services/devtestlabs/mgmt/2018-09-15/dtl/armtemplates.go
  services/devtestlabs/mgmt/2018-09-15/dtl/artifacts.go
  services/devtestlabs/mgmt/2018-09-15/dtl/artifactsources.go
  services/devtestlabs/mgmt/2018-09-15/dtl/client.go
  services/devtestlabs/mgmt/2018-09-15/dtl/costs.go
  services/devtestlabs/mgmt/2018-09-15/dtl/customimages.go
  services/devtestlabs/mgmt/2018-09-15/dtl/disks.go
  services/devtestlabs/mgmt/2018-09-15/dtl/dtlapi/interfaces.go
  services/devtestlabs/mgmt/2018-09-15/dtl/environments.go
  services/devtestlabs/mgmt/2018-09-15/dtl/formulas.go
  services/devtestlabs/mgmt/2018-09-15/dtl/galleryimages.go
  services/devtestlabs/mgmt/2018-09-15/dtl/globalschedules.go
  services/devtestlabs/mgmt/2018-09-15/dtl/labs.go
  services/devtestlabs/mgmt/2018-09-15/dtl/models.go
  services/devtestlabs/mgmt/2018-09-15/dtl/notificationchannels.go
  services/devtestlabs/mgmt/2018-09-15/dtl/operations.go
  services/devtestlabs/mgmt/2018-09-15/dtl/policies.go
  services/devtestlabs/mgmt/2018-09-15/dtl/policysets.go
  services/devtestlabs/mgmt/2018-09-15/dtl/provideroperations.go
  services/devtestlabs/mgmt/2018-09-15/dtl/schedules.go
  services/devtestlabs/mgmt/2018-09-15/dtl/secrets.go
  services/devtestlabs/mgmt/2018-09-15/dtl/servicefabrics.go
  services/devtestlabs/mgmt/2018-09-15/dtl/servicefabricschedules.go
  services/devtestlabs/mgmt/2018-09-15/dtl/servicerunners.go
  services/devtestlabs/mgmt/2018-09-15/dtl/users.go
  services/devtestlabs/mgmt/2018-09-15/dtl/version.go
  services/devtestlabs/mgmt/2018-09-15/dtl/virtualmachines.go
  services/devtestlabs/mgmt/2018-09-15/dtl/virtualmachineschedules.go
  services/devtestlabs/mgmt/2018-09-15/dtl/virtualnetworks.go
Labels: RestPRMerged

#3621 [AutoPR] service-map/resource-manager
  services/preview/operationalinsights/mgmt/2015-11-01-preview/servicemap/models.go
Labels: ServicePR, review

#3602 [AutoPR servicefabricmesh/resource-manager] typo: servicefabricmesh/resource-manager/Microsoft.ServiceFabricMesh
  services/preview/servicefabricmesh/mgmt/2018-09-01-preview/servicefabricmesh/models.go
Labels: RestPRMerged, review

#3634 [AutoPR web/resource-manager] typo: web/resource-manager/Microsoft.CertificateRegistration
  services/web/mgmt/2016-09-01/web/models.go
  services/web/mgmt/2018-02-01/web/models.go
Labels: RestPRMerged, review

#3625 [AutoPR billing/resource-manager] Microsoft.Billing: Rolling back the incorrect version merged in master branch.
  services/preview/billing/mgmt/2017-04-24-preview/billing/models.go
  services/preview/billing/mgmt/2018-03-01-preview/billing/models.go
Labels: RestPRMerged, review

#3627 [AutoPR] servicefabricmesh/resource-manager
  services/preview/servicefabricmesh/mgmt/2018-09-01-preview/servicefabricmesh/models.go
Labels: ServicePR, review

#3640 [AutoPR] billing/resource-manager
  services/preview/billing/mgmt/2017-04-24-preview/billing/models.go
  services/preview/billing/mgmt/2018-03-01-preview/billing/models.go
Labels: ServicePR, review

#3556 [AutoPR sqlvirtualmachine/resource-manager] [Portal Generated] Review request for Microsoft.SqlVirtualMachine to add version 2017-03-01-preview
  profiles/preview/preview/sqlvirtualmachine/mgmt/sqlvirtualmachine/models.go
  services/preview/sqlvirtualmachine/mgmt/2017-03-01-preview/sqlvirtualmachine/models.go
Labels: RestPRMerged, review

#3624 [AutoPR labservices/resource-manager] [LabServices] Fix typo, remove required from optional param
  profiles/preview/labservices/mgmt/labservices/models.go
  services/labservices/mgmt/2018-10-15/labservices/environments.go
  services/labservices/mgmt/2018-10-15/labservices/environmentsettings.go
  services/labservices/mgmt/2018-10-15/labservices/globalusers.go
  services/labservices/mgmt/2018-10-15/labservices/labservicesapi/interfaces.go
  services/labservices/mgmt/2018-10-15/labservices/models.go
Labels: RestPRMerged, review

#3641 [AutoPR] sqlvirtualmachine/resource-manager
  profiles/preview/preview/sqlvirtualmachine/mgmt/sqlvirtualmachine/models.go
  services/preview/sqlvirtualmachine/mgmt/2017-03-01-preview/sqlvirtualmachine/models.go
Labels: ServicePR, review

#3643 [AutoPR] labservices/resource-manager
  profiles/preview/labservices/mgmt/labservices/models.go
  services/labservices/mgmt/2018-10-15/labservices/environments.go
  services/labservices/mgmt/2018-10-15/labservices/environmentsettings.go
  services/labservices/mgmt/2018-10-15/labservices/globalusers.go
  services/labservices/mgmt/2018-10-15/labservices/labservicesapi/interfaces.go
  services/labservices/mgmt/2018-10-15/labservices/models.go
Labels: ServicePR, review

#3593 [AutoPR compute/resource-manager] [Please do not merge] Adding provisionAfterExtensions property for ex…
  services/compute/mgmt/2018-06-01/compute/models.go
  services/compute/mgmt/2018-10-01/compute/models.go
Labels: RestPRMerged, review

#3592 [AutoPR logic/resource-manager] Bugfix for swagger/sdk not matching the underlying service API
  services/preview/logic/mgmt/2018-07-01-preview/logic/integrationaccountagreements.go
  services/preview/logic/mgmt/2018-07-01-preview/logic/models.go
Labels: RestPRMerged, review

#3645 [AutoPR] compute/resource-manager
  services/compute/mgmt/2018-06-01/compute/models.go
  services/compute/mgmt/2018-10-01/compute/models.go
Labels: ServicePR, review

#3646 [AutoPR] logic/resource-manager
  services/preview/logic/mgmt/2018-07-01-preview/logic/integrationaccountagreements.go
  services/preview/logic/mgmt/2018-07-01-preview/logic/models.go
Labels: ServicePR, review

#3607 [AutoPR] servicefabric/data-plane
  profiles/preview/servicefabric/servicefabric/models.go
  profiles/preview/servicefabric/servicefabric/servicefabricapi/models.go
  services/servicefabric/6.3/servicefabric/client.go
  services/servicefabric/6.3/servicefabric/models.go
  services/servicefabric/6.3/servicefabric/servicefabricapi/interfaces.go
  services/servicefabric/6.3/servicefabric/version.go
  services/servicefabric/6.4/servicefabric/client.go
  services/servicefabric/6.4/servicefabric/meshapplication.go
  services/servicefabric/6.4/servicefabric/meshcodepackage.go
  services/servicefabric/6.4/servicefabric/meshgateway.go
  services/servicefabric/6.4/servicefabric/meshnetwork.go
  services/servicefabric/6.4/servicefabric/meshsecret.go
  services/servicefabric/6.4/servicefabric/meshsecretvalue.go
  services/servicefabric/6.4/servicefabric/meshservice.go
  services/servicefabric/6.4/servicefabric/meshservicereplica.go
  services/servicefabric/6.4/servicefabric/meshvolume.go
  services/servicefabric/6.4/servicefabric/models.go
  services/servicefabric/6.4/servicefabric/servicefabricapi/interfaces.go
  services/servicefabric/6.4/servicefabric/version.go
Labels: ServicePR, review

#3636 [AutoPR workloadmonitor/resource-manager] typo: workloadmonitor/resource-manager/Microsoft.WorkloadMonitor
  services/preview/workloadmonitor/mgmt/2018-08-31-preview/workloadmonitor/models.go
Labels: RestPRMerged, review

#3629 [AutoPR storsimple8000series/resource-manager] typo: storsimple8000series/resource-manager/Microsoft.StorSimple
  services/storsimple8000series/mgmt/2017-06-01/storsimple/models.go
  services/storsimple8000series/mgmt/2017-06-01/storsimple/operations.go
Labels: RestPRMerged, review

#3615 [AutoPR blueprint/resource-manager] Fix typo
  services/preview/blueprint/mgmt/2017-11-11-preview/blueprint/blueprints.go
Labels: RestPRMerged, review

#3608 [AutoPR storage/resource-manager] typo: storage/resource-manager/Microsoft.Storage
  services/storage/mgmt/2015-06-15/storage/models.go
Labels: RestPRMerged, review

#3496 [AutoPR machinelearning/resource-manager] typo: machinelearning/resource-manager/Microsoft.MachineLearning
  services/machinelearning/mgmt/2017-01-01/webservices/models.go
  services/preview/machinelearning/mgmt/2016-05-01-preview/commitmentplans/models.go
  services/preview/machinelearning/mgmt/2016-05-01-preview/webservices/models.go
  services/preview/machinelearning/mgmt/2016-05-01-preview/webservices/webservices.go
Labels: RestPRMerged, review

#3655 [AutoPR cognitiveservices/data-plane/Face] typo: cognitiveservices/data-plane/Face
  services/cognitiveservices/v1.0/face/largefacelist.go
  services/cognitiveservices/v1.0/face/list.go
Labels: RestPRMerged, review

#3661 [AutoPR batch/data-plane] typo: batch/data-plane/Microsoft.Batch
  services/batch/2017-05-01.5.0/batch/models.go
  services/batch/2018-03-01.6.1/batch/models.go
  services/batch/2018-08-01.7.0/batch/models.go
Labels: RestPRMerged, review

#3649 [AutoPR] workloadmonitor/resource-manager
  services/preview/workloadmonitor/mgmt/2018-08-31-preview/workloadmonitor/models.go
Labels: ServicePR, review

#3650 [AutoPR] storsimple8000series/resource-manager
  services/storsimple8000series/mgmt/2017-06-01/storsimple/models.go
  services/storsimple8000series/mgmt/2017-06-01/storsimple/operations.go
Labels: ServicePR, review

#3651 [AutoPR] blueprint/resource-manager
  services/preview/blueprint/mgmt/2017-11-11-preview/blueprint/blueprints.go
Labels: ServicePR, review

#3652 [AutoPR] storage/resource-manager
  services/storage/mgmt/2015-06-15/storage/models.go
Labels: ServicePR, review

#3653 [AutoPR] machinelearning/resource-manager
  services/machinelearning/mgmt/2017-01-01/webservices/models.go
  services/preview/machinelearning/mgmt/2016-05-01-preview/commitmentplans/models.go
  services/preview/machinelearning/mgmt/2016-05-01-preview/webservices/models.go
  services/preview/machinelearning/mgmt/2016-05-01-preview/webservices/webservices.go
Labels: ServicePR, review

#3659 [AutoPR] cognitiveservices/data-plane/Face
  services/cognitiveservices/v1.0/face/largefacelist.go
  services/cognitiveservices/v1.0/face/list.go
Labels: ServicePR, review

#3662 [AutoPR] batch/data-plane
  services/batch/2017-05-01.5.0/batch/models.go
  services/batch/2018-03-01.6.1/batch/models.go
  services/batch/2018-08-01.7.0/batch/models.go
Labels: ServicePR, review

#3663 [AutoPR cognitiveservices/data-plane/LocalSearch] add Go SDK codegen for cognitive services localsearch
  profiles/preview/cognitiveservices/localsearch/localsearchapi/models.go
  profiles/preview/cognitiveservices/localsearch/models.go
  services/cognitiveservices/v1.0/localsearch/client.go
  services/cognitiveservices/v1.0/localsearch/local.go
  services/cognitiveservices/v1.0/localsearch/localsearchapi/interfaces.go
  services/cognitiveservices/v1.0/localsearch/models.go
  services/cognitiveservices/v1.0/localsearch/version.go
Labels: RestPRMerged, review

#3631 [AutoPR subscription/resource-manager] typo: subscription/resource-manager/Microsoft.Subscription
  services/preview/subscription/mgmt/2017-11-01-preview/subscription/models.go
Labels: review

#3664 [AutoPR] cognitiveservices/data-plane/LocalSearch
  profiles/preview/cognitiveservices/localsearch/localsearchapi/models.go
  profiles/preview/cognitiveservices/localsearch/models.go
  services/cognitiveservices/v1.0/localsearch/client.go
  services/cognitiveservices/v1.0/localsearch/local.go
  services/cognitiveservices/v1.0/localsearch/localsearchapi/interfaces.go
  services/cognitiveservices/v1.0/localsearch/models.go
  services/cognitiveservices/v1.0/localsearch/version.go
Labels: ServicePR, review

#3665 Generated from 739894c24e928412aa4c219485762d0382590d93 (#3465)
  services/cognitiveservices/v4.0/qnamaker/models.go
Labels: review

#3666 Restapi auto machinelearningservices/resource manager
  services/cognitiveservices/v4.0/qnamaker/models.go
Labels: review

#3667 Generated from 68d1f6c363e859a0074d3cdf2fa926ec169d0d64 (#3631)
  services/preview/subscription/mgmt/2017-11-01-preview/subscription/models.go
Labels: review

#3637 [AutoPR cognitiveservices/data-plane/CustomVision/Training] typo: CustomVision/Training
  services/cognitiveservices/v1.2/customvision/training/client.go
  services/cognitiveservices/v1.2/customvision/training/models.go
  services/cognitiveservices/v2.1/customvision/training/client.go
  services/cognitiveservices/v2.1/customvision/training/models.go
  services/cognitiveservices/v2.2/customvision/training/client.go
  services/cognitiveservices/v2.2/customvision/training/models.go
Labels: RestPRMerged, review

#3523 [AutoPR powerbidedicated/resource-manager] typo: powerbidedicated/resource-manager/Microsoft.PowerBIdedicated
  services/powerbidedicated/mgmt/2017-10-01/powerbidedicated/models.go
Labels: RestPRMerged, review

#3671 [AutoPR] cognitiveservices/data-plane/CustomVision/Training
  services/cognitiveservices/v1.2/customvision/training/client.go
  services/cognitiveservices/v1.2/customvision/training/models.go
  services/cognitiveservices/v2.1/customvision/training/client.go
  services/cognitiveservices/v2.1/customvision/training/models.go
  services/cognitiveservices/v2.2/customvision/training/client.go
  services/cognitiveservices/v2.2/customvision/training/models.go
Labels: ServicePR, review

#3672 [AutoPR] powerbidedicated/resource-manager
  services/powerbidedicated/mgmt/2017-10-01/powerbidedicated/models.go
Labels: ServicePR, review

#3675 update code generator for swagger->sdk
  swagger_to_sdk_config.json
Labels: review

#3656 [AutoPR cognitiveservices/data-plane/VisualSearch] typo: cognitiveservices/data-plane/VisualSearch
  services/preview/cognitiveservices/v1.0/visualsearch/models.go
Labels: RestPRMerged, review

#3670 [AutoPR] servicefabric/data-plane
  services/servicefabric/6.2/servicefabric/models.go
  services/servicefabric/6.3/servicefabric/models.go
  services/servicefabric/6.4/servicefabric/models.go
Labels: ServicePR, review

#3676 [AutoPR] cognitiveservices/data-plane/VisualSearch
  services/preview/cognitiveservices/v1.0/visualsearch/models.go
Labels: ServicePR, review
