Repository Azure/azure-sdk-for-go, pull requests merged in 2018-02, with the labels that each got.

#1067 [AutoPR monitor/resource-manager] Added the new Voice action and increased the API version for this change
  services/monitor/mgmt/2017-05-01-preview/insights/version.go
Labels: RestPRMerged, review

#1070 Add version package for SDK-wide version information.
  version/version.go
Labels: review

#1073 +Viper instances for each profileBuilder command.
  tools/profileBuilder/cmd/latest.go
  tools/profileBuilder/cmd/list.go
Labels: review

#1075 update storage README to reflect preview state
  storage/README.md
Labels: docs, review, storage

#1074 update README for v14.0.0
  README.md
Labels: docs, review, versioning

#1086 v14.0.1
  CHANGELOG.md
  profiles/latest/search/search/models.go
  profiles/preview/search/search/models.go
  services/search/2016-09-01/search/client.go
  services/search/2016-09-01/search/datasources.go
  services/search/2016-09-01/search/documentsproxy.go
  services/search/2016-09-01/search/indexers.go
  services/search/2016-09-01/search/indexes.go
  services/search/2016-09-01/search/models.go
  services/search/2016-09-01/search/version.go
  version/version.go
Labels: review

#1081 Update Profile Builder to allow a specified file for list input
  profiles/2017-03-09/generate.go
  swagger_to_sdk_config.json
  tools/profileBuilder/README.md
  tools/profileBuilder/cmd/list.go
Labels: review

#1087 [DO NOT MERGE] Reducing the noise in CI.
  .travis.yml
  findTestedPackages.sh
  tools/profileBuilder/model/defaults.go
  tools/profileBuilder/model/noop_test.go
  tools/profileBuilder/model/transforms.go
  tools/profileBuilder/model/transforms_test.go
  tools/profileBuilder/test.sh
Labels: review

#1078 [AutoPR automation/resource-manager] Adding examples and fixing the DSC related lint issues
  services/automation/mgmt/2015-10-31/automation/dsccompilationjobstream.go
  services/automation/mgmt/2015-10-31/automation/dscnodeconfiguration.go
  services/automation/mgmt/2015-10-31/automation/models.go
  services/automation/mgmt/2015-10-31/automation/runbookdraft.go
  services/automation/mgmt/2015-10-31/automation/version.go
  services/automation/mgmt/2017-05-15-preview/dsccompilationjobstream.go
  services/automation/mgmt/2017-05-15-preview/dscnodeconfiguration.go
  services/automation/mgmt/2017-05-15-preview/models.go
  services/automation/mgmt/2017-05-15-preview/runbookdraft.go
  services/automation/mgmt/2017-05-15-preview/sourcecontrol.go
  services/automation/mgmt/2017-05-15-preview/sourcecontrolsyncjob.go
  services/automation/mgmt/2017-05-15-preview/version.go
Labels: RestPRMerged, review

#1095 Update profileBuilder to delete profile contents before generating.
  CHANGELOG.md
  profiles/2017-03-09/generate.go
  profiles/latest/generate.go
  profiles/preview/generate.go
  swagger_to_sdk_config.json
  tools/profileBuilder/cmd/latest.go
  tools/profileBuilder/cmd/list.go
  tools/profileBuilder/cmd/root.go
  tools/profileBuilder/model/delete.go
  version/version.go
Labels: review

#1084 update storage README to reflect recommended practices
  storage/README.md
Labels: review

#1102 Removing `profileBuilder` portion of Swagger->SDK
  swagger_to_sdk_config.json
Labels: review

#1121 [AutoPR web/resource-manager] Suppress RPC R3019 per discussion at https://github.com/Azure/azure-r…
  services/web/mgmt/2015-08-preview/web/certificatesgroup.go
  services/web/mgmt/2015-08-preview/web/domainsgroup.go
  services/web/mgmt/2015-08-preview/web/providergroup.go
  services/web/mgmt/2015-08-preview/web/recommendationsgroup.go
  services/web/mgmt/2015-08-preview/web/topleveldomainsgroup.go
  services/web/mgmt/2015-08-preview/web/version.go
  services/web/mgmt/2016-09-01/web/models.go
  services/web/mgmt/2016-09-01/web/provider.go
  services/web/mgmt/2016-09-01/web/version.go
Labels: RestPRMerged, review

#1141 [AutoPR locationbasedservices/resource-manager] locationbasedservices py conf
  services/location/mgmt/2017-01-01-preview/location/version.go
Labels: RestPRMerged, review

#1134 [AutoPR eventhub/resource-manager] Event Hub: Added missing API to respective API version Swaggers
  services/eventhub/mgmt/2015-08-01/eventhub/eventhubs.go
  services/eventhub/mgmt/2015-08-01/eventhub/version.go
  services/eventhub/mgmt/2017-04-01/eventhub/messagingplan.go
  services/eventhub/mgmt/2017-04-01/eventhub/models.go
  services/eventhub/mgmt/2017-04-01/eventhub/regions.go
  services/eventhub/mgmt/2017-04-01/eventhub/version.go
Labels: RestPRMerged, review

#1143 [AutoPR servicebus/resource-manager] ServiceBus: Added enableBatchedOperations property to ServiceBus Queue
  services/servicebus/mgmt/2015-08-01/servicebus/version.go
  services/servicebus/mgmt/2017-04-01/servicebus/models.go
  services/servicebus/mgmt/2017-04-01/servicebus/version.go
Labels: RestPRMerged, review

#1162 [AutoPR marketplaceordering/resource-manager] Add a directive for node and TS to delete format: "date-time".
  services/marketplaceordering/mgmt/2015-06-01/marketplaceordering/version.go
Labels: RestPRMerged, review

#1164 [AutoPR datamigration/resource-manager] DataMigration py conf
  services/datamigration/mgmt/2017-11-15-preview/datamigration/models.go
  services/datamigration/mgmt/2017-11-15-preview/datamigration/version.go
Labels: RestPRMerged, review

#1160 [AutoPR web/resource-manager] Fix recommendation resource properties, add disable recommendation APIs
  services/web/mgmt/2016-09-01/web/models.go
  services/web/mgmt/2016-09-01/web/recommendations.go
Labels: RestPRMerged, review

#1163 [AutoPR compute/resource-manager] Compute spec change for zone resilient images
  services/compute/mgmt/2015-06-15/compute/version.go
  services/compute/mgmt/2016-03-30/compute/version.go
  services/compute/mgmt/2016-04-30-preview/compute/version.go
  services/compute/mgmt/2017-03-30/compute/version.go
  services/compute/mgmt/2017-12-01/compute/models.go
  services/compute/mgmt/2017-12-01/compute/version.go
  services/containerservice/mgmt/2015-11-01-preview/containerservice/version.go
  services/containerservice/mgmt/2016-03-30/containerservice/version.go
  services/containerservice/mgmt/2016-09-30/containerservice/version.go
  services/containerservice/mgmt/2017-01-31/containerservice/version.go
Labels: RestPRMerged, review
