Repository Azure/azure-sdk-for-go, pull requests merged in 2018-06, with the labels that each got.

#1934 [AutoPR iotcentral/resource-manager] Add specs for Microsoft.IoTCentral RP
  profiles/preview/preview/iotcentral/mgmt/iotcentral/models.go
  services/preview/iotcentral/mgmt/2017-07-01-privatepreview/iotcentral/apps.go
  services/preview/iotcentral/mgmt/2017-07-01-privatepreview/iotcentral/client.go
  services/preview/iotcentral/mgmt/2017-07-01-privatepreview/iotcentral/models.go
  services/preview/iotcentral/mgmt/2017-07-01-privatepreview/iotcentral/operations.go
  services/preview/iotcentral/mgmt/2017-07-01-privatepreview/iotcentral/version.go
Labels: RestPRMerged, review

#1940 [AutoPR compute/resource-manager] Compute Py conf
  services/compute/mgmt/2015-06-15/compute/models.go
  services/compute/mgmt/2015-06-15/compute/virtualmachineextensions.go
  services/compute/mgmt/2015-06-15/compute/virtualmachines.go
  services/compute/mgmt/2015-06-15/compute/virtualmachinescalesets.go
  services/compute/mgmt/2015-06-15/compute/virtualmachinescalesetvms.go
  services/compute/mgmt/2016-03-30/compute/models.go
  services/compute/mgmt/2016-03-30/compute/virtualmachineextensions.go
  services/compute/mgmt/2016-03-30/compute/virtualmachines.go
  services/compute/mgmt/2016-03-30/compute/virtualmachinescalesets.go
  services/compute/mgmt/2016-03-30/compute/virtualmachinescalesetvms.go
  services/compute/mgmt/2017-03-30/compute/containerservices.go
  services/compute/mgmt/2017-03-30/compute/disks.go
  services/compute/mgmt/2017-03-30/compute/images.go
  services/compute/mgmt/2017-03-30/compute/models.go
  services/compute/mgmt/2017-03-30/compute/snapshots.go
  services/compute/mgmt/2017-03-30/compute/virtualmachineextensions.go
  services/compute/mgmt/2017-03-30/compute/virtualmachines.go
  services/compute/mgmt/2017-03-30/compute/virtualmachinescalesetextensions.go
  services/compute/mgmt/2017-03-30/compute/virtualmachinescalesetrollingupgrades.go
  services/compute/mgmt/2017-03-30/compute/virtualmachinescalesets.go
  services/compute/mgmt/2017-03-30/compute/virtualmachinescalesetvms.go
  services/compute/mgmt/2018-04-01/compute/containerservices.go
  services/compute/mgmt/2018-04-01/compute/disks.go
  services/compute/mgmt/2018-04-01/compute/images.go
  services/compute/mgmt/2018-04-01/compute/loganalytics.go
  services/compute/mgmt/2018-04-01/compute/models.go
  services/compute/mgmt/2018-04-01/compute/snapshots.go
  services/compute/mgmt/2018-04-01/compute/virtualmachineextensions.go
  services/compute/mgmt/2018-04-01/compute/virtualmachines.go
  services/compute/mgmt/2018-04-01/compute/virtualmachinescalesetextensions.go
  services/compute/mgmt/2018-04-01/compute/virtualmachinescalesetrollingupgrades.go
  services/compute/mgmt/2018-04-01/compute/virtualmachinescalesets.go
  services/compute/mgmt/2018-04-01/compute/virtualmachinescalesetvms.go
  services/containerservice/mgmt/2016-03-30/containerservice/containerservices.go
  services/containerservice/mgmt/2016-03-30/containerservice/models.go
  services/containerservice/mgmt/2016-09-30/containerservice/containerservices.go
  services/containerservice/mgmt/2016-09-30/containerservice/models.go
  services/containerservice/mgmt/2017-01-31/containerservice/containerservices.go
  services/containerservice/mgmt/2017-01-31/containerservice/models.go
  services/preview/compute/mgmt/2016-04-30-preview/compute/disks.go
  services/preview/compute/mgmt/2016-04-30-preview/compute/images.go
  services/preview/compute/mgmt/2016-04-30-preview/compute/models.go
  services/preview/compute/mgmt/2016-04-30-preview/compute/snapshots.go
  services/preview/compute/mgmt/2016-04-30-preview/compute/virtualmachineextensions.go
  services/preview/compute/mgmt/2016-04-30-preview/compute/virtualmachines.go
  services/preview/compute/mgmt/2016-04-30-preview/compute/virtualmachinescalesets.go
  services/preview/compute/mgmt/2016-04-30-preview/compute/virtualmachinescalesetvms.go
  services/preview/containerservice/mgmt/2015-11-01-preview/containerservice/containerservice.go
  services/preview/containerservice/mgmt/2015-11-01-preview/containerservice/models.go
Labels: RestPRMerged, review

#1949 [AutoPR compute/resource-manager] [Compute] Fix List VM Extension API name, description updates and other fixes.
  profiles/latest/compute/mgmt/compute/models.go
  profiles/preview/compute/mgmt/compute/models.go
  services/compute/mgmt/2018-04-01/compute/models.go
Labels: RestPRMerged, review

#1951 [AutoPR] compute/resource-manager
  profiles/latest/compute/mgmt/compute/models.go
  profiles/preview/compute/mgmt/compute/models.go
  services/compute/mgmt/2018-04-01/compute/models.go
Labels: ServicePR, review

#1947 [AutoPR eventgrid/data-plane] Replacing # with &#35;
  services/eventgrid/2018-01-01/eventgrid/models.go
Labels: RestPRMerged, review

#1957 [AutoPR] eventgrid/data-plane
  services/eventgrid/2018-01-01/eventgrid/models.go
Labels: ServicePR, review

#1963 [AutoPR monitor/resource-manager] Adding patch support for SQR API
  profiles/preview/preview/monitor/mgmt/insights/models.go
  services/preview/monitor/mgmt/2018-03-01/insights/models.go
  services/preview/monitor/mgmt/2018-03-01/insights/scheduledqueryrules.go
Labels: RestPRMerged, review

#1960 [AutoPR resources/resource-manager] 2018-05-01 APIs for Microsoft.Resources
  profiles/preview/resources/mgmt/resources/models.go
  services/resources/mgmt/2018-05-01/resources/client.go
  services/resources/mgmt/2018-05-01/resources/deploymentoperations.go
  services/resources/mgmt/2018-05-01/resources/deployments.go
  services/resources/mgmt/2018-05-01/resources/groups.go
  services/resources/mgmt/2018-05-01/resources/models.go
  services/resources/mgmt/2018-05-01/resources/providers.go
  services/resources/mgmt/2018-05-01/resources/resources.go
  services/resources/mgmt/2018-05-01/resources/tags.go
  services/resources/mgmt/2018-05-01/resources/version.go
Labels: RestPRMerged, review

#1964 [AutoPR resources/resource-manager] Remove uiDefinitionUri property from managed app responses and add new api version
  profiles/preview/resources/mgmt/managedapplications/models.go
  services/resources/mgmt/2018-06-01/managedapplications/applicationdefinitions.go
  services/resources/mgmt/2018-06-01/managedapplications/applications.go
  services/resources/mgmt/2018-06-01/managedapplications/client.go
  services/resources/mgmt/2018-06-01/managedapplications/models.go
  services/resources/mgmt/2018-06-01/managedapplications/version.go
Labels: RestPRMerged, review

#1980 Fix SecurityGroupClient.ListNetworkSecurityGroups()
  services/classic/management/networksecuritygroup/client.go
Labels: review

#1970 [AutoPR] resources/resource-manager
  profiles/preview/resources/mgmt/managedapplications/models.go
  profiles/preview/resources/mgmt/resources/models.go
  services/resources/mgmt/2018-05-01/resources/client.go
  services/resources/mgmt/2018-05-01/resources/deploymentoperations.go
  services/resources/mgmt/2018-05-01/resources/deployments.go
  services/resources/mgmt/2018-05-01/resources/groups.go
  services/resources/mgmt/2018-05-01/resources/models.go
  services/resources/mgmt/2018-05-01/resources/providers.go
  services/resources/mgmt/2018-05-01/resources/resources.go
  services/resources/mgmt/2018-05-01/resources/tags.go
  services/resources/mgmt/2018-05-01/resources/version.go
  services/resources/mgmt/2018-06-01/managedapplications/applicationdefinitions.go
  services/resources/mgmt/2018-06-01/managedapplications/applications.go
  services/resources/mgmt/2018-06-01/managedapplications/client.go
  services/resources/mgmt/2018-06-01/managedapplications/models.go
  services/resources/mgmt/2018-06-01/managedapplications/version.go
Labels: ServicePR, review

#1959 [AutoPR reservations/resource-manager] Reservations RP 2018-06-01 specs
  profiles/preview/reservations/mgmt/reservations/models.go
  services/reservations/mgmt/2018-06-01/reservations/client.go
  services/reservations/mgmt/2018-06-01/reservations/models.go
  services/reservations/mgmt/2018-06-01/reservations/operation.go
  services/reservations/mgmt/2018-06-01/reservations/order.go
  services/reservations/mgmt/2018-06-01/reservations/reservation.go
  services/reservations/mgmt/2018-06-01/reservations/version.go
Labels: RestPRMerged, review

#1975 [AutoPR iotcentral/resource-manager] Remove subscriptionId uuid format for IotCentral
  profiles/preview/preview/iotcentral/mgmt/iotcentral/models.go
  services/preview/iotcentral/mgmt/2017-07-01-privatepreview/iotcentral/apps.go
  services/preview/iotcentral/mgmt/2017-07-01-privatepreview/iotcentral/client.go
  services/preview/iotcentral/mgmt/2017-07-01-privatepreview/iotcentral/operations.go
Labels: RestPRMerged, review

#1967 [AutoPR containerinstance/resource-manager] Adding June Swagger Update - Azure Container Instance
  profiles/preview/containerinstance/mgmt/containerinstance/models.go
  services/containerinstance/mgmt/2018-06-01/containerinstance/client.go
  services/containerinstance/mgmt/2018-06-01/containerinstance/containergroups.go
  services/containerinstance/mgmt/2018-06-01/containerinstance/containergroupusage.go
  services/containerinstance/mgmt/2018-06-01/containerinstance/containerlogs.go
  services/containerinstance/mgmt/2018-06-01/containerinstance/models.go
  services/containerinstance/mgmt/2018-06-01/containerinstance/operations.go
  services/containerinstance/mgmt/2018-06-01/containerinstance/startcontainer.go
  services/containerinstance/mgmt/2018-06-01/containerinstance/version.go
Labels: RestPRMerged, review

#1989 [AutoPR network/resource-manager] appgwv2 changes
  services/network/mgmt/2018-04-01/network/models.go
  services/network/mgmt/2018-04-01/network/virtualnetworkgateways.go
  services/network/mgmt/2018-04-01/network/watchers.go
Labels: RestPRMerged, review

#1966 [AutoPR] cognitiveservices/data-plane/ComputerVision
  profiles/latest/cognitiveservices/computervision/models.go
  profiles/preview/cognitiveservices/computervision/models.go
  services/cognitiveservices/v1.0/computervision/client.go
  services/cognitiveservices/v1.0/computervision/models.go
Labels: ServicePR, review

#1968 [AutoPR] monitor/resource-manager
  profiles/preview/preview/monitor/mgmt/insights/models.go
  services/preview/monitor/mgmt/2018-03-01/insights/models.go
  services/preview/monitor/mgmt/2018-03-01/insights/scheduledqueryrules.go
Labels: ServicePR, review

#1982 [AutoPR] reservations/resource-manager
  profiles/preview/reservations/mgmt/reservations/models.go
  services/reservations/mgmt/2018-06-01/reservations/client.go
  services/reservations/mgmt/2018-06-01/reservations/models.go
  services/reservations/mgmt/2018-06-01/reservations/operation.go
  services/reservations/mgmt/2018-06-01/reservations/order.go
  services/reservations/mgmt/2018-06-01/reservations/reservation.go
  services/reservations/mgmt/2018-06-01/reservations/version.go
Labels: ServicePR, review

#1985 [AutoPR] iotcentral/resource-manager
  profiles/preview/preview/iotcentral/mgmt/iotcentral/models.go
  services/preview/iotcentral/mgmt/2017-07-01-privatepreview/iotcentral/apps.go
  services/preview/iotcentral/mgmt/2017-07-01-privatepreview/iotcentral/client.go
  services/preview/iotcentral/mgmt/2017-07-01-privatepreview/iotcentral/operations.go
Labels: ServicePR, review

#1978 [AutoPR datafactory/resource-manager] [Data Factory]Add schema mapping for hierarchical data
  services/preview/datafactory/mgmt/2017-09-01-preview/datafactory/models.go
Labels: RestPRMerged, review

#1999 [AutoPR network/resource-manager] Add primary flag to 2015-06-15 NetworkInterfaceIPConfiguration
  services/network/mgmt/2015-06-15/network/models.go
Labels: RestPRMerged, review

#1990 [AutoPR] containerinstance/resource-manager
  profiles/preview/containerinstance/mgmt/containerinstance/models.go
  services/containerinstance/mgmt/2018-06-01/containerinstance/client.go
  services/containerinstance/mgmt/2018-06-01/containerinstance/containergroups.go
  services/containerinstance/mgmt/2018-06-01/containerinstance/containergroupusage.go
  services/containerinstance/mgmt/2018-06-01/containerinstance/containerlogs.go
  services/containerinstance/mgmt/2018-06-01/containerinstance/models.go
  services/containerinstance/mgmt/2018-06-01/containerinstance/operations.go
  services/containerinstance/mgmt/2018-06-01/containerinstance/startcontainer.go
  services/containerinstance/mgmt/2018-06-01/containerinstance/version.go
Labels: ServicePR, review

#1998 [AutoPR] datafactory/resource-manager
  services/preview/datafactory/mgmt/2017-09-01-preview/datafactory/models.go
Labels: ServicePR, review

#2001 [AutoPR] network/resource-manager
  services/network/mgmt/2015-06-15/network/models.go
Labels: ServicePR, review

#1984 [AutoPR adhybridhealthservice/resource-manager] Adding few more function to ADHybridHealth swagger spec
  profiles/preview/adhybridhealthservice/mgmt/adhybridhealthservice/models.go
  services/adhybridhealthservice/mgmt/2014-01-01/adhybridhealthservice/addsservice.go
  services/adhybridhealthservice/mgmt/2014-01-01/adhybridhealthservice/addsservicemembers.go
  services/adhybridhealthservice/mgmt/2014-01-01/adhybridhealthservice/addsservices.go
  services/adhybridhealthservice/mgmt/2014-01-01/adhybridhealthservice/addsservicesreplicationstatus.go
  services/adhybridhealthservice/mgmt/2014-01-01/adhybridhealthservice/addsservicesservicemembers.go
  services/adhybridhealthservice/mgmt/2014-01-01/adhybridhealthservice/addsservicesuserpreference.go
  services/adhybridhealthservice/mgmt/2014-01-01/adhybridhealthservice/models.go
  services/adhybridhealthservice/mgmt/2014-01-01/adhybridhealthservice/reports.go
  services/adhybridhealthservice/mgmt/2014-01-01/adhybridhealthservice/service.go
  services/adhybridhealthservice/mgmt/2014-01-01/adhybridhealthservice/servicemembers.go
Labels: RestPRMerged, review

#1956 [AutoPR cognitiveservices/data-plane/AutoSuggest] Add bing AutoSuggest Spec
  profiles/preview/cognitiveservices/autosuggest/models.go
  services/cognitiveservices/v1.0/autosuggest/client.go
  services/cognitiveservices/v1.0/autosuggest/models.go
  services/cognitiveservices/v1.0/autosuggest/version.go
Labels: RestPRMerged, review

#1976 [AutoPR consumption/resource-manager] Added new api versions for PriceSheet and UsageDetail
  profiles/preview/consumption/mgmt/consumption/models.go
  services/consumption/mgmt/2018-05-31/consumption/models.go
  services/consumption/mgmt/2018-05-31/consumption/pricesheet.go
  services/consumption/mgmt/2018-05-31/consumption/usagedetails.go
Labels: RestPRMerged, review

#1986 [AutoPR sql/resource-manager] Adding serverSecurityAlertPolicies.json from pr
  services/preview/sql/mgmt/2017-03-01-preview/sql/models.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/serversecurityalertpolicies.go
Labels: RestPRMerged, review

#2010 [AutoPR resources/resource-manager] Minor updates to description properties to improve docs
  services/resources/mgmt/2018-03-01/policy/definitions.go
  services/resources/mgmt/2018-03-01/policy/models.go
Labels: RestPRMerged, review

#2021 [AutoPR dns/resource-manager] Move DNS to use the common definition for resource groups
  services/dns/mgmt/2016-04-01/dns/recordsets.go
  services/dns/mgmt/2016-04-01/dns/zones.go
  services/dns/mgmt/2017-09-01/dns/recordsets.go
  services/dns/mgmt/2017-09-01/dns/zones.go
  services/dns/mgmt/2017-10-01/dns/recordsets.go
  services/dns/mgmt/2017-10-01/dns/zones.go
  services/preview/dns/mgmt/2015-05-04-preview/dns/recordsets.go
  services/preview/dns/mgmt/2015-05-04-preview/dns/zones.go
  services/preview/dns/mgmt/2018-03-01-preview/dns/recordsets.go
  services/preview/dns/mgmt/2018-03-01-preview/dns/zones.go
Labels: RestPRMerged, review

#2004 [AutoPR] adhybridhealthservice/resource-manager
  profiles/preview/adhybridhealthservice/mgmt/adhybridhealthservice/models.go
  services/adhybridhealthservice/mgmt/2014-01-01/adhybridhealthservice/addsservice.go
  services/adhybridhealthservice/mgmt/2014-01-01/adhybridhealthservice/addsservicemembers.go
  services/adhybridhealthservice/mgmt/2014-01-01/adhybridhealthservice/addsservices.go
  services/adhybridhealthservice/mgmt/2014-01-01/adhybridhealthservice/addsservicesreplicationstatus.go
  services/adhybridhealthservice/mgmt/2014-01-01/adhybridhealthservice/addsservicesservicemembers.go
  services/adhybridhealthservice/mgmt/2014-01-01/adhybridhealthservice/addsservicesuserpreference.go
  services/adhybridhealthservice/mgmt/2014-01-01/adhybridhealthservice/models.go
  services/adhybridhealthservice/mgmt/2014-01-01/adhybridhealthservice/reports.go
  services/adhybridhealthservice/mgmt/2014-01-01/adhybridhealthservice/service.go
  services/adhybridhealthservice/mgmt/2014-01-01/adhybridhealthservice/servicemembers.go
Labels: ServicePR, review

#2005 [AutoPR] cognitiveservices/data-plane/AutoSuggest
  profiles/preview/cognitiveservices/autosuggest/models.go
  services/cognitiveservices/v1.0/autosuggest/client.go
  services/cognitiveservices/v1.0/autosuggest/models.go
  services/cognitiveservices/v1.0/autosuggest/version.go
Labels: ServicePR, review

#2011 [AutoPR] consumption/resource-manager
  profiles/preview/consumption/mgmt/consumption/models.go
  services/consumption/mgmt/2018-05-31/consumption/models.go
  services/consumption/mgmt/2018-05-31/consumption/pricesheet.go
  services/consumption/mgmt/2018-05-31/consumption/usagedetails.go
Labels: ServicePR, review

#2012 [AutoPR] sql/resource-manager
  services/preview/sql/mgmt/2017-03-01-preview/sql/models.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/serversecurityalertpolicies.go
Labels: ServicePR, review

#2025 [AutoPR reservations/resource-manager] Reservations RP: adding x-ms-enum
  profiles/preview/reservations/mgmt/reservations/models.go
  services/reservations/mgmt/2018-06-01/reservations/models.go
Labels: RestPRMerged, review

#2017 [AutoPR notificationhubs/resource-manager] Add missing debugsend and patch operation for NotificationHub resource
  profiles/latest/notificationhubs/mgmt/notificationhubs/models.go
  profiles/preview/notificationhubs/mgmt/notificationhubs/models.go
  services/notificationhubs/mgmt/2017-04-01/notificationhubs/models.go
  services/notificationhubs/mgmt/2017-04-01/notificationhubs/namespaces.go
  services/notificationhubs/mgmt/2017-04-01/notificationhubs/notificationhubs.go
Labels: RestPRMerged, review

#2038 [AutoPR network/resource-manager] network: add https probe which was missing in the spec
  profiles/preview/network/mgmt/network/models.go
  services/network/mgmt/2018-02-01/network/models.go
  services/network/mgmt/2018-04-01/network/models.go
  services/network/mgmt/2018-05-01/network/models.go
Labels: RestPRMerged, review

#2023 [AutoPR] resources/resource-manager
  services/resources/mgmt/2018-03-01/policy/definitions.go
  services/resources/mgmt/2018-03-01/policy/models.go
Labels: ServicePR, review

#2024 [AutoPR] dns/resource-manager
  services/dns/mgmt/2016-04-01/dns/recordsets.go
  services/dns/mgmt/2016-04-01/dns/zones.go
  services/dns/mgmt/2017-09-01/dns/recordsets.go
  services/dns/mgmt/2017-09-01/dns/zones.go
  services/dns/mgmt/2017-10-01/dns/recordsets.go
  services/dns/mgmt/2017-10-01/dns/zones.go
  services/preview/dns/mgmt/2015-05-04-preview/dns/recordsets.go
  services/preview/dns/mgmt/2015-05-04-preview/dns/zones.go
  services/preview/dns/mgmt/2018-03-01-preview/dns/recordsets.go
  services/preview/dns/mgmt/2018-03-01-preview/dns/zones.go
Labels: ServicePR, review

#2036 [AutoPR] notificationhubs/resource-manager
  profiles/latest/notificationhubs/mgmt/notificationhubs/models.go
  profiles/preview/notificationhubs/mgmt/notificationhubs/models.go
  services/notificationhubs/mgmt/2017-04-01/notificationhubs/models.go
  services/notificationhubs/mgmt/2017-04-01/notificationhubs/namespaces.go
  services/notificationhubs/mgmt/2017-04-01/notificationhubs/notificationhubs.go
Labels: ServicePR, review

#2040 [AutoPR] network/resource-manager
  profiles/preview/network/mgmt/network/models.go
  services/network/mgmt/2018-02-01/network/models.go
  services/network/mgmt/2018-04-01/network/models.go
  services/network/mgmt/2018-05-01/network/models.go
Labels: ServicePR, review

#2048 [AutoPR sql/resource-manager] adding new state value to keep backward competiblity
  services/preview/sql/mgmt/2017-03-01-preview/sql/models.go
Labels: RestPRMerged, review

#2045 [AutoPR reservations/resource-manager] Reservations RP: adding x-ms-enum and changing some enums to type string
  profiles/preview/reservations/mgmt/reservations/models.go
  services/reservations/mgmt/2018-06-01/reservations/models.go
Labels: RestPRMerged, review

#2034 [AutoPR operationsmanagement/resource-manager] Change Response for Solution PUT call
  profiles/preview/preview/operationsmanagement/mgmt/operationsmanagement/models.go
  services/preview/operationsmanagement/mgmt/2015-11-01-preview/operationsmanagement/models.go
  services/preview/operationsmanagement/mgmt/2015-11-01-preview/operationsmanagement/solutions.go
Labels: RestPRMerged, review

#2052 [AutoPR cognitiveservices/data-plane/ComputerVision] Update CognitiveService ComputerVision API to V2
  profiles/preview/cognitiveservices/computervision/models.go
  services/cognitiveservices/v2.0/computervision/client.go
  services/cognitiveservices/v2.0/computervision/models.go
  services/cognitiveservices/v2.0/computervision/version.go
Labels: RestPRMerged, review

#2051 [AutoPR monitor/resource-manager] Changing Case
  profiles/preview/preview/monitor/mgmt/insights/models.go
  services/preview/monitor/mgmt/2018-03-01/insights/models.go
Labels: RestPRMerged, review

#2050 [AutoPR operationalinsights/data-plane] Add nodejs generation for Operational Insights
  services/operationalinsights/v1/operationalinsights/client.go
Labels: RestPRMerged, review

#2058 [AutoPR batchai/resource-manager] [Service deployed in prod with feature flag, waiting to be public] BatchAI. Remove API for list clusters and fileservers
  profiles/preview/batchai/mgmt/batchai/models.go
  services/batchai/mgmt/2018-05-01/batchai/clusters.go
  services/batchai/mgmt/2018-05-01/batchai/fileservers.go
  services/batchai/mgmt/2018-05-01/batchai/models.go
  services/batchai/mgmt/2018-05-01/batchai/workspaces.go
Labels: RestPRMerged, review

#1991 [AutoPR operationalinsights/data-plane/applicationinsights/data-plane] [App Insights/Operational Insights] New Data Plane API versions, bug fixes, and cleanup
  services/operationalinsights/v1/operationalinsights/client.go
Labels: RestPRMerged, review

#2039 [AutoPR applicationinsights/resource-manager/operationalinsights/resource-manager] App Insights/Operational Insights Purge API fixes
  profiles/latest/appinsights/mgmt/insights/models.go
  profiles/latest/operationalinsights/mgmt/operationalinsights/models.go
  profiles/preview/appinsights/mgmt/insights/models.go
  services/appinsights/mgmt/2015-05-01/insights/components.go
  services/appinsights/mgmt/2015-05-01/insights/models.go
  services/operationalinsights/mgmt/2015-03-20/operationalinsights/models.go
  services/operationalinsights/mgmt/2015-03-20/operationalinsights/workspaces.go
Labels: RestPRMerged, review

#2053 [AutoPR] operationsmanagement/resource-manager
  profiles/preview/preview/operationsmanagement/mgmt/operationsmanagement/models.go
  services/preview/operationsmanagement/mgmt/2015-11-01-preview/operationsmanagement/models.go
  services/preview/operationsmanagement/mgmt/2015-11-01-preview/operationsmanagement/solutions.go
Labels: ServicePR, review

#2065 [AutoPR] batchai/resource-manager
  profiles/preview/batchai/mgmt/batchai/models.go
  services/batchai/mgmt/2018-05-01/batchai/clusters.go
  services/batchai/mgmt/2018-05-01/batchai/fileservers.go
  services/batchai/mgmt/2018-05-01/batchai/models.go
  services/batchai/mgmt/2018-05-01/batchai/workspaces.go
Labels: ServicePR, review

#2062 [AutoPR apimanagement/resource-manager] Fix the validation Check for apiId parameter in the productapis
  services/preview/apimanagement/mgmt/2018-01-01/apimanagement/productapi.go
Labels: RestPRMerged, review

#2042 [AutoPR cosmos-db/resource-manager] Cosmos DB - POST operation for retrieving read only keys
  services/cosmos-db/mgmt/2015-04-08/documentdb/databaseaccounts.go
Labels: RestPRMerged, review

#2049 [AutoPR] sql/resource-manager
  services/preview/sql/mgmt/2017-03-01-preview/sql/models.go
Labels: ServicePR, review

#2067 [AutoPR logic/resource-manager] Adding in description of available filter options
  services/logic/mgmt/2016-06-01/logic/agreements.go
  services/logic/mgmt/2016-06-01/logic/maps.go
  services/logic/mgmt/2016-06-01/logic/partners.go
  services/logic/mgmt/2016-06-01/logic/schemas.go
  services/logic/mgmt/2016-06-01/logic/sessions.go
  services/logic/mgmt/2016-06-01/logic/workflowrunactions.go
  services/logic/mgmt/2016-06-01/logic/workflowruns.go
  services/logic/mgmt/2016-06-01/logic/workflows.go
  services/logic/mgmt/2016-06-01/logic/workflowtriggerhistories.go
Labels: RestPRMerged, review

#2072 Diff'ing packages can contain incorrect information
  tools/apidiff/cmd/packages.go
Labels: review

#2070 [AutoPR] apimanagement/resource-manager
  services/preview/apimanagement/mgmt/2018-01-01/apimanagement/productapi.go
Labels: ServicePR, review

#2063 add Service Bus to list of Azure packages
  README.md
Labels: docs, review

#2026 [AutoPR] reservations/resource-manager
  profiles/preview/reservations/mgmt/reservations/models.go
  services/reservations/mgmt/2018-06-01/reservations/models.go
Labels: ServicePR, review

#2071 [AutoPR] cosmos-db/resource-manager
  services/cosmos-db/mgmt/2015-04-08/documentdb/databaseaccounts.go
Labels: ServicePR, review

#2073 [AutoPR] logic/resource-manager
  services/logic/mgmt/2016-06-01/logic/agreements.go
  services/logic/mgmt/2016-06-01/logic/maps.go
  services/logic/mgmt/2016-06-01/logic/partners.go
  services/logic/mgmt/2016-06-01/logic/schemas.go
  services/logic/mgmt/2016-06-01/logic/sessions.go
  services/logic/mgmt/2016-06-01/logic/workflowrunactions.go
  services/logic/mgmt/2016-06-01/logic/workflowruns.go
  services/logic/mgmt/2016-06-01/logic/workflows.go
  services/logic/mgmt/2016-06-01/logic/workflowtriggerhistories.go
Labels: ServicePR, review

#2054 [AutoPR] monitor/resource-manager
  profiles/preview/preview/monitor/mgmt/insights/models.go
  services/preview/monitor/mgmt/2018-03-01/insights/models.go
Labels: ServicePR, review

#2075 [AutoPR consumption/resource-manager] Consumption specifications for cost insights and reporting operations
  profiles/preview/consumption/mgmt/consumption/models.go
  services/consumption/mgmt/2018-05-31/consumption/billingaccountdimensions.go
  services/consumption/mgmt/2018-05-31/consumption/client.go
  services/consumption/mgmt/2018-05-31/consumption/models.go
  services/consumption/mgmt/2018-05-31/consumption/reportconfig.go
  services/consumption/mgmt/2018-05-31/consumption/resourcegroupdimensions.go
  services/consumption/mgmt/2018-05-31/consumption/subscriptiondimensions.go
Labels: RestPRMerged, review

#2066 [AutoPR cognitiveservices/data-plane/ComputerVision] ComputerVision add tag.hint
  services/cognitiveservices/v2.0/computervision/models.go
Labels: RestPRMerged, review

#2081 [AutoPR apimanagement/resource-manager] Fix contract for Error in OperationResultContract
  services/preview/apimanagement/mgmt/2018-01-01/apimanagement/models.go
Labels: RestPRMerged, review

#2088 [AutoPR keyvault/data-plane] Moving 7.0 from preview to stable
  services/keyvault/v7.0/keyvault/client.go
  services/keyvault/v7.0/keyvault/models.go
  services/keyvault/v7.0/keyvault/version.go
Labels: RestPRMerged, review

#2096 [AutoPR mediaservices/resource-manager] Adding Azure Media Services version 2018-06-01-preview version
  profiles/preview/preview/mediaservices/mgmt/media/models.go
  services/preview/mediaservices/mgmt/2018-06-01-preview/media/assets.go
  services/preview/mediaservices/mgmt/2018-06-01-preview/media/client.go
  services/preview/mediaservices/mgmt/2018-06-01-preview/media/contentkeypolicies.go
  services/preview/mediaservices/mgmt/2018-06-01-preview/media/jobs.go
  services/preview/mediaservices/mgmt/2018-06-01-preview/media/liveevents.go
  services/preview/mediaservices/mgmt/2018-06-01-preview/media/liveoutputs.go
  services/preview/mediaservices/mgmt/2018-06-01-preview/media/locations.go
  services/preview/mediaservices/mgmt/2018-06-01-preview/media/mediaservices.go
  services/preview/mediaservices/mgmt/2018-06-01-preview/media/models.go
  services/preview/mediaservices/mgmt/2018-06-01-preview/media/operations.go
  services/preview/mediaservices/mgmt/2018-06-01-preview/media/streamingendpoints.go
  services/preview/mediaservices/mgmt/2018-06-01-preview/media/streaminglocators.go
  services/preview/mediaservices/mgmt/2018-06-01-preview/media/streamingpolicies.go
  services/preview/mediaservices/mgmt/2018-06-01-preview/media/transforms.go
  services/preview/mediaservices/mgmt/2018-06-01-preview/media/version.go
Labels: RestPRMerged, review

#2092 [AutoPR sql/resource-manager] Adding Swagger for POST APIs used to upload a customer TDE certificates
  profiles/preview/preview/sql/mgmt/sql/models.go
  services/preview/sql/mgmt/2015-05-01-preview/sql/databaseblobauditingpolicies.go
  services/preview/sql/mgmt/2015-05-01-preview/sql/models.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/databaseblobauditingpolicies.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/databasevulnerabilityassessmentrulebaselines.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/extendeddatabaseblobauditingpolicies.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/extendedserverblobauditingpolicies.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/models.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/serverblobauditingpolicies.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/serversecurityalertpolicies.go
  services/preview/sql/mgmt/2017-10-01-preview/sql/backupshorttermretentionpolicies.go
  services/preview/sql/mgmt/2017-10-01-preview/sql/managedinstancetdecertificates.go
  services/preview/sql/mgmt/2017-10-01-preview/sql/models.go
  services/preview/sql/mgmt/2017-10-01-preview/sql/tdecertificates.go
Labels: RestPRMerged, review

#2100 [AutoPR] mediaservices/resource-manager
  profiles/preview/preview/mediaservices/mgmt/media/models.go
  services/preview/mediaservices/mgmt/2018-06-01-preview/media/assets.go
  services/preview/mediaservices/mgmt/2018-06-01-preview/media/client.go
  services/preview/mediaservices/mgmt/2018-06-01-preview/media/contentkeypolicies.go
  services/preview/mediaservices/mgmt/2018-06-01-preview/media/jobs.go
  services/preview/mediaservices/mgmt/2018-06-01-preview/media/liveevents.go
  services/preview/mediaservices/mgmt/2018-06-01-preview/media/liveoutputs.go
  services/preview/mediaservices/mgmt/2018-06-01-preview/media/locations.go
  services/preview/mediaservices/mgmt/2018-06-01-preview/media/mediaservices.go
  services/preview/mediaservices/mgmt/2018-06-01-preview/media/models.go
  services/preview/mediaservices/mgmt/2018-06-01-preview/media/operations.go
  services/preview/mediaservices/mgmt/2018-06-01-preview/media/streamingendpoints.go
  services/preview/mediaservices/mgmt/2018-06-01-preview/media/streaminglocators.go
  services/preview/mediaservices/mgmt/2018-06-01-preview/media/streamingpolicies.go
  services/preview/mediaservices/mgmt/2018-06-01-preview/media/transforms.go
  services/preview/mediaservices/mgmt/2018-06-01-preview/media/version.go
Labels: ServicePR, review

#2068 [AutoPR network/resource-manager] Release of Azure Networking Network-2018-06-01 (api-version 2018-04-01)
  services/network/mgmt/2018-04-01/network/applicationgateways.go
  services/network/mgmt/2018-04-01/network/expressroutecircuitpeerings.go
  services/network/mgmt/2018-04-01/network/hubvirtualnetworkconnections.go
  services/network/mgmt/2018-04-01/network/models.go
  services/network/mgmt/2018-04-01/network/virtualhubs.go
  services/network/mgmt/2018-04-01/network/virtualnetworkgatewayconnections.go
  services/network/mgmt/2018-04-01/network/virtualwans.go
  services/network/mgmt/2018-04-01/network/vpnconnections.go
  services/network/mgmt/2018-04-01/network/vpngateways.go
  services/network/mgmt/2018-04-01/network/vpnsites.go
  services/network/mgmt/2018-04-01/network/vpnsitesconfiguration.go
Labels: RestPRInProgress, review

#2104 update go-autorest dependency
  Gopkg.lock
  Gopkg.toml
Labels: review

#2107 [AutoPR storage/resource-manager] [Storage] Support HDFS feature and web endpoint in Account properties
  services/preview/storage/mgmt/2018-03-01-preview/storage/models.go
  services/storage/mgmt/2018-02-01/storage/models.go
Labels: RestPRMerged, review

#2106 [AutoPR datafactory/resource-manager] Creating new API version for ADF
  profiles/preview/stable/datafactory/mgmt/datafactory/models.go
  services/stable/datafactory/mgmt/2018-06-01/datafactory/activityruns.go
  services/stable/datafactory/mgmt/2018-06-01/datafactory/client.go
  services/stable/datafactory/mgmt/2018-06-01/datafactory/datasets.go
  services/stable/datafactory/mgmt/2018-06-01/datafactory/factories.go
  services/stable/datafactory/mgmt/2018-06-01/datafactory/integrationruntimenodes.go
  services/stable/datafactory/mgmt/2018-06-01/datafactory/integrationruntimes.go
  services/stable/datafactory/mgmt/2018-06-01/datafactory/linkedservices.go
  services/stable/datafactory/mgmt/2018-06-01/datafactory/models.go
  services/stable/datafactory/mgmt/2018-06-01/datafactory/operations.go
  services/stable/datafactory/mgmt/2018-06-01/datafactory/pipelineruns.go
  services/stable/datafactory/mgmt/2018-06-01/datafactory/pipelines.go
  services/stable/datafactory/mgmt/2018-06-01/datafactory/triggerruns.go
  services/stable/datafactory/mgmt/2018-06-01/datafactory/triggers.go
  services/stable/datafactory/mgmt/2018-06-01/datafactory/version.go
Labels: RestPRMerged, review

#2097 [AutoPR monitor/resource-manager] Add two missing "by subscription" operations for completeness and compliance
  services/preview/monitor/mgmt/2017-05-01-preview/insights/alertrules.go
  services/preview/monitor/mgmt/2017-05-01-preview/insights/autoscalesettings.go
  services/preview/monitor/mgmt/2017-05-01-preview/insights/models.go
  services/preview/monitor/mgmt/2018-03-01/insights/alertrules.go
  services/preview/monitor/mgmt/2018-03-01/insights/autoscalesettings.go
  services/preview/monitor/mgmt/2018-03-01/insights/models.go
Labels: RestPRMerged, review

#2086 [AutoPR network/resource-manager] Add AzureFirewall swagger and examples
  services/network/mgmt/2016-09-01/network/virtualnetworkgatewayconnections.go
  services/network/mgmt/2016-12-01/network/virtualnetworkgatewayconnections.go
  services/network/mgmt/2017-03-01/network/virtualnetworkgatewayconnections.go
  services/network/mgmt/2017-06-01/network/virtualnetworkgatewayconnections.go
  services/network/mgmt/2017-08-01/network/virtualnetworkgatewayconnections.go
  services/network/mgmt/2017-09-01/network/virtualnetworkgatewayconnections.go
  services/network/mgmt/2017-10-01/network/expressroutecircuitpeerings.go
  services/network/mgmt/2017-10-01/network/virtualnetworkgatewayconnections.go
  services/network/mgmt/2017-11-01/network/expressroutecircuitpeerings.go
  services/network/mgmt/2017-11-01/network/virtualnetworkgatewayconnections.go
  services/network/mgmt/2018-01-01/network/applicationgateways.go
  services/network/mgmt/2018-01-01/network/expressroutecircuitpeerings.go
  services/network/mgmt/2018-01-01/network/virtualnetworkgatewayconnections.go
  services/network/mgmt/2018-02-01/network/applicationgateways.go
  services/network/mgmt/2018-02-01/network/expressroutecircuitpeerings.go
  services/network/mgmt/2018-02-01/network/expressroutecrossconnectionpeerings.go
  services/network/mgmt/2018-02-01/network/virtualnetworkgatewayconnections.go
  services/network/mgmt/2018-04-01/network/applicationgateways.go
  services/network/mgmt/2018-04-01/network/azurefirewalls.go
  services/network/mgmt/2018-04-01/network/expressroutecircuitpeerings.go
  services/network/mgmt/2018-04-01/network/expressroutecrossconnectionpeerings.go
  services/network/mgmt/2018-04-01/network/models.go
  services/network/mgmt/2018-04-01/network/virtualnetworkgatewayconnections.go
  services/network/mgmt/2018-05-01/network/applicationgateways.go
  services/network/mgmt/2018-05-01/network/expressroutecircuitpeerings.go
  services/network/mgmt/2018-05-01/network/expressroutecrossconnectionpeerings.go
  services/network/mgmt/2018-05-01/network/virtualnetworkgatewayconnections.go
Labels: RestPRMerged, review

#2123 Fixes for blob storage SAS URI parsing
  storage/blobserviceclient.go
  storage/client.go
Labels: review

#2079 [AutoPR operationalinsights/data-plane] Update Java configuration for Log Analytics
  services/operationalinsights/v1/operationalinsights/client.go
Labels: RestPRMerged, review

#2116 [AutoPR] storage/resource-manager
  services/preview/storage/mgmt/2018-03-01-preview/storage/models.go
  services/storage/mgmt/2018-02-01/storage/models.go
Labels: ServicePR, review

#2117 [AutoPR] network/resource-manager
  services/network/mgmt/2016-09-01/network/virtualnetworkgatewayconnections.go
  services/network/mgmt/2016-12-01/network/virtualnetworkgatewayconnections.go
  services/network/mgmt/2017-03-01/network/virtualnetworkgatewayconnections.go
  services/network/mgmt/2017-06-01/network/virtualnetworkgatewayconnections.go
  services/network/mgmt/2017-08-01/network/virtualnetworkgatewayconnections.go
  services/network/mgmt/2017-09-01/network/virtualnetworkgatewayconnections.go
  services/network/mgmt/2017-10-01/network/expressroutecircuitpeerings.go
  services/network/mgmt/2017-10-01/network/virtualnetworkgatewayconnections.go
  services/network/mgmt/2017-11-01/network/expressroutecircuitpeerings.go
  services/network/mgmt/2017-11-01/network/virtualnetworkgatewayconnections.go
  services/network/mgmt/2018-01-01/network/applicationgateways.go
  services/network/mgmt/2018-01-01/network/expressroutecircuitpeerings.go
  services/network/mgmt/2018-01-01/network/virtualnetworkgatewayconnections.go
  services/network/mgmt/2018-02-01/network/applicationgateways.go
  services/network/mgmt/2018-02-01/network/expressroutecircuitpeerings.go
  services/network/mgmt/2018-02-01/network/expressroutecrossconnectionpeerings.go
  services/network/mgmt/2018-02-01/network/virtualnetworkgatewayconnections.go
  services/network/mgmt/2018-04-01/network/applicationgateways.go
  services/network/mgmt/2018-04-01/network/azurefirewalls.go
  services/network/mgmt/2018-04-01/network/expressroutecircuitpeerings.go
  services/network/mgmt/2018-04-01/network/expressroutecrossconnectionpeerings.go
  services/network/mgmt/2018-04-01/network/hubvirtualnetworkconnections.go
  services/network/mgmt/2018-04-01/network/models.go
  services/network/mgmt/2018-04-01/network/virtualhubs.go
  services/network/mgmt/2018-04-01/network/virtualnetworkgatewayconnections.go
  services/network/mgmt/2018-04-01/network/virtualwans.go
  services/network/mgmt/2018-04-01/network/vpnconnections.go
  services/network/mgmt/2018-04-01/network/vpngateways.go
  services/network/mgmt/2018-04-01/network/vpnsites.go
  services/network/mgmt/2018-04-01/network/vpnsitesconfiguration.go
  services/network/mgmt/2018-05-01/network/applicationgateways.go
  services/network/mgmt/2018-05-01/network/expressroutecircuitpeerings.go
  services/network/mgmt/2018-05-01/network/expressroutecrossconnectionpeerings.go
  services/network/mgmt/2018-05-01/network/virtualnetworkgatewayconnections.go
Labels: ServicePR, review

#2120 [AutoPR] monitor/resource-manager
  services/preview/monitor/mgmt/2017-05-01-preview/insights/alertrules.go
  services/preview/monitor/mgmt/2017-05-01-preview/insights/autoscalesettings.go
  services/preview/monitor/mgmt/2017-05-01-preview/insights/models.go
  services/preview/monitor/mgmt/2018-03-01/insights/alertrules.go
  services/preview/monitor/mgmt/2018-03-01/insights/autoscalesettings.go
  services/preview/monitor/mgmt/2018-03-01/insights/models.go
Labels: ServicePR, review

#2126 [AutoPR] operationalinsights/data-plane
  services/operationalinsights/v1/operationalinsights/client.go
Labels: ServicePR, review

#2125 [AutoPR containerregistry/resource-manager] [ACR] Add 2018-02-preview version to Java SDK
  services/preview/containerregistry/mgmt/2018-02-01/containerregistry/buildtasks.go
Labels: RestPRMerged, review

#2136 [AutoPR containerregistry/resource-manager] [ACR] Fix list builds odata query
  services/preview/containerregistry/mgmt/2018-02-01/containerregistry/models.go
Labels: RestPRMerged, review

#2137 [AutoPR eventhub/resource-manager] Event Hubs : Added property pendingReplicationOperationsCount to GeoDR
  services/eventhub/mgmt/2017-04-01/eventhub/consumergroups.go
  services/eventhub/mgmt/2017-04-01/eventhub/eventhubs.go
  services/eventhub/mgmt/2017-04-01/eventhub/models.go
  services/eventhub/mgmt/2017-04-01/eventhub/namespaces.go
Labels: RestPRMerged, review

#2139 [AutoPR signalr/resource-manager] Add a new tier for Azure SignalR serivce
  profiles/preview/preview/signalr/mgmt/signalr/models.go
  services/preview/signalr/mgmt/2018-03-01-preview/signalr/models.go
Labels: RestPRMerged, review

#2121 [AutoPR consumption/resource-manager/cost-management/resource-manager] Created a new provider Microsoft.CostManagement and moved reports and query api documentation from Microsoft.Consumption to it
  profiles/preview/consumption/mgmt/consumption/models.go
  services/consumption/mgmt/2018-05-31/consumption/billingaccountdimensions.go
  services/consumption/mgmt/2018-05-31/consumption/client.go
  services/consumption/mgmt/2018-05-31/consumption/models.go
  services/consumption/mgmt/2018-05-31/consumption/reportconfig.go
  services/consumption/mgmt/2018-05-31/consumption/resourcegroupdimensions.go
  services/consumption/mgmt/2018-05-31/consumption/subscriptiondimensions.go
Labels: RestPRMerged, review

#2129 [AutoPR] containerregistry/resource-manager
  services/preview/containerregistry/mgmt/2018-02-01/containerregistry/buildtasks.go
  services/preview/containerregistry/mgmt/2018-02-01/containerregistry/models.go
Labels: ServicePR, review

#2142 [AutoPR] eventhub/resource-manager
  services/eventhub/mgmt/2017-04-01/eventhub/consumergroups.go
  services/eventhub/mgmt/2017-04-01/eventhub/eventhubs.go
  services/eventhub/mgmt/2017-04-01/eventhub/models.go
  services/eventhub/mgmt/2017-04-01/eventhub/namespaces.go
Labels: ServicePR, review

#2144 [AutoPR] signalr/resource-manager
  profiles/preview/preview/signalr/mgmt/signalr/models.go
  services/preview/signalr/mgmt/2018-03-01-preview/signalr/models.go
Labels: ServicePR, review

#2143 Fix QueueMessage Update method
  storage/message.go
Labels: review

#2138 [AutoPR servicebus/resource-manager] ServiceBus: Added property pendingReplicationOperationsCount to GeoDR and Migration
  services/servicebus/mgmt/2017-04-01/servicebus/models.go
  services/servicebus/mgmt/2017-04-01/servicebus/queues.go
  services/servicebus/mgmt/2017-04-01/servicebus/rules.go
  services/servicebus/mgmt/2017-04-01/servicebus/subscriptions.go
  services/servicebus/mgmt/2017-04-01/servicebus/topics.go
Labels: RestPRMerged, review

#2056 [AutoPR advisor/resource-manager] Add C# SDK generation settings for Advisor
  profiles/latest/advisor/mgmt/advisor/models.go
  profiles/preview/advisor/mgmt/advisor/models.go
  services/advisor/mgmt/2017-04-19/advisor/models.go
  services/advisor/mgmt/2017-04-19/advisor/recommendations.go
Labels: RestPRMerged, review

#2158 [AutoPR servicebus/resource-manager] ServiceBus: Removed space from pendingReplicationOperationsCount
  services/servicebus/mgmt/2017-04-01/servicebus/models.go
Labels: RestPRMerged, review

#2155 [AutoPR batchai/resource-manager] Rename MPI to CustomMPI to match Batch AI service
  profiles/preview/batchai/mgmt/batchai/models.go
  services/batchai/mgmt/2018-05-01/batchai/models.go
Labels: RestPRMerged, review

#2157 [AutoPR eventhub/resource-manager] EventHub: Removed space from pendingReplicationOperationsCount
  services/eventhub/mgmt/2017-04-01/eventhub/models.go
Labels: RestPRMerged, review
