Repository Azure/azure-sdk-for-go, pull requests merged in 2018-09, with the labels that each got.

#2570 [AutoPR hanaonazure/resource-manager] Added HANA instance restart API
  services/preview/hanaonazure/mgmt/2017-11-03-preview/hanaonazure/hanainstances.go
Labels: RestPRMerged, review

#2599 [AutoPR botservice/resource-manager] fix check name availabilty method for botservice
  services/preview/botservice/mgmt/2018-07-12/botservices/bots.go
  services/web/mgmt/2016-09-01/web/apps.go
  services/web/mgmt/2018-02-01/web/apps.go
Labels: RestPRMerged, review

#2567 [AutoPR compute/resource-manager] Added the replica count API change to Shared Image Gallery swagger file.
  profiles/preview/compute/mgmt/compute/models.go
  services/compute/mgmt/2018-06-01/compute/models.go
  services/web/mgmt/2016-09-01/web/apps.go
  services/web/mgmt/2018-02-01/web/apps.go
Labels: RestPRMerged, review

#2551 [AutoPR authorization/resource-manager] Grlin/Adding Principal Type to RA
  profiles/preview/preview/authorization/mgmt/authorization/models.go
  services/preview/authorization/mgmt/2018-09-01-preview/authorization/classicadministrators.go
  services/preview/authorization/mgmt/2018-09-01-preview/authorization/client.go
  services/preview/authorization/mgmt/2018-09-01-preview/authorization/models.go
  services/preview/authorization/mgmt/2018-09-01-preview/authorization/permissions.go
  services/preview/authorization/mgmt/2018-09-01-preview/authorization/provideroperationsmetadata.go
  services/preview/authorization/mgmt/2018-09-01-preview/authorization/roleassignments.go
  services/preview/authorization/mgmt/2018-09-01-preview/authorization/roledefinitions.go
  services/preview/authorization/mgmt/2018-09-01-preview/authorization/version.go
  services/web/mgmt/2016-09-01/web/apps.go
  services/web/mgmt/2018-02-01/web/apps.go
Labels: RestPRMerged, review

#2578 [AutoPR consumption/resource-manager] Adding swagger for new api-version consumption 2018-08-31
  profiles/preview/consumption/mgmt/consumption/models.go
  services/consumption/mgmt/2018-08-31/consumption/aggregatedcost.go
  services/consumption/mgmt/2018-08-31/consumption/balances.go
  services/consumption/mgmt/2018-08-31/consumption/budgets.go
  services/consumption/mgmt/2018-08-31/consumption/charges.go
  services/consumption/mgmt/2018-08-31/consumption/client.go
  services/consumption/mgmt/2018-08-31/consumption/forecasts.go
  services/consumption/mgmt/2018-08-31/consumption/marketplaces.go
  services/consumption/mgmt/2018-08-31/consumption/models.go
  services/consumption/mgmt/2018-08-31/consumption/operations.go
  services/consumption/mgmt/2018-08-31/consumption/pricesheet.go
  services/consumption/mgmt/2018-08-31/consumption/reservationrecommendations.go
  services/consumption/mgmt/2018-08-31/consumption/reservationsdetails.go
  services/consumption/mgmt/2018-08-31/consumption/reservationssummaries.go
  services/consumption/mgmt/2018-08-31/consumption/tags.go
  services/consumption/mgmt/2018-08-31/consumption/usagedetails.go
  services/consumption/mgmt/2018-08-31/consumption/version.go
  services/web/mgmt/2016-09-01/web/apps.go
  services/web/mgmt/2018-02-01/web/apps.go
Labels: RestPRMerged, review

#2615 [AutoPR containerinstance/resource-manager] Container Instance: Adding September Update
  profiles/preview/containerinstance/mgmt/containerinstance/models.go
  services/containerinstance/mgmt/2018-09-01/containerinstance/client.go
  services/containerinstance/mgmt/2018-09-01/containerinstance/container.go
  services/containerinstance/mgmt/2018-09-01/containerinstance/containergroups.go
  services/containerinstance/mgmt/2018-09-01/containerinstance/containergroupusage.go
  services/containerinstance/mgmt/2018-09-01/containerinstance/models.go
  services/containerinstance/mgmt/2018-09-01/containerinstance/operations.go
  services/containerinstance/mgmt/2018-09-01/containerinstance/version.go
Labels: RestPRMerged, review

#2624 [AutoPR compute/resource-manager] Fix description for disk size
  services/compute/mgmt/2015-06-15/compute/models.go
  services/compute/mgmt/2016-03-30/compute/models.go
  services/compute/mgmt/2017-03-30/compute/models.go
  services/compute/mgmt/2017-12-01/compute/models.go
  services/compute/mgmt/2018-04-01/compute/models.go
  services/compute/mgmt/2018-06-01/compute/models.go
  services/preview/compute/mgmt/2016-04-30-preview/compute/models.go
Labels: RestPRMerged, review

#2622 [AutoPR datafactory/resource-manager] [Datafactory] Update FactoryGitHubConfiguration discriminator value (#3643)
  profiles/preview/datafactory/mgmt/datafactory/models.go
  services/datafactory/mgmt/2018-06-01/datafactory/models.go
Labels: RestPRMerged, review

#2616 [AutoPR monitor/resource-manager] Adding MetricNamespacesAPI for version 2017-12-01-preview/Fix metrics_API.json format issue
  services/monitor/mgmt/2017-05-01-preview/insights/actiongroups.go
  services/monitor/mgmt/2017-05-01-preview/insights/activitylogalerts.go
  services/monitor/mgmt/2017-05-01-preview/insights/alertruleincidents.go
  services/monitor/mgmt/2017-05-01-preview/insights/alertrules.go
  services/monitor/mgmt/2017-05-01-preview/insights/autoscalesettings.go
  services/monitor/mgmt/2017-05-01-preview/insights/client.go
  services/monitor/mgmt/2017-05-01-preview/insights/diagnosticsettings.go
  services/monitor/mgmt/2017-05-01-preview/insights/diagnosticsettingscategory.go
  services/monitor/mgmt/2017-05-01-preview/insights/logprofiles.go
  services/monitor/mgmt/2017-05-01-preview/insights/models.go
  services/monitor/mgmt/2017-05-01-preview/insights/operations.go
  services/monitor/mgmt/2017-05-01-preview/insights/version.go
  services/web/mgmt/2016-09-01/web/apps.go
  services/web/mgmt/2018-02-01/web/apps.go
Labels: RestPRMerged, review

#2625 [AutoPR botservice/resource-manager] add security fields to directline channel site for botservice
  services/preview/botservice/mgmt/2018-07-12/botservices/models.go
Labels: RestPRMerged, review

#2632 [AutoPR containerinstance/resource-manager] Container Instance: Add Private for Ip Address Enum
  profiles/preview/containerinstance/mgmt/containerinstance/models.go
  services/containerinstance/mgmt/2018-09-01/containerinstance/containergroups.go
  services/containerinstance/mgmt/2018-09-01/containerinstance/models.go
Labels: RestPRMerged, review

#2634 [AutoPR datafactory/resource-manager] [Datafactory] Adding new API to get GitHub access token
  profiles/preview/datafactory/mgmt/datafactory/models.go
  services/datafactory/mgmt/2018-06-01/datafactory/factories.go
  services/datafactory/mgmt/2018-06-01/datafactory/models.go
Labels: RestPRMerged, review

#2641 [AutoPR containerservices/resource-manager] [AKS] note that only one agent pool is currently supported
  services/containerservice/mgmt/2018-03-31/containerservice/models.go
Labels: RestPRMerged, review

#2644 [AutoPR resources/resource-manager] Fix ARMViolation Error for Microsoft.Authorization
  profiles/latest/resources/mgmt/locks/models.go
  profiles/preview/resources/mgmt/locks/models.go
  services/resources/mgmt/2016-09-01/locks/client.go
  services/resources/mgmt/2016-09-01/locks/models.go
Labels: RestPRMerged, review

#2595 [AutoPR] eventhub/resource-manager
  services/preview/eventhub/mgmt/2018-01-01-preview/eventhub/models.go
Labels: ServicePR, review

#2605 [AutoPR] hanaonazure/resource-manager
  services/preview/hanaonazure/mgmt/2017-11-03-preview/hanaonazure/hanainstances.go
Labels: ServicePR, review

#2593 [AutoPR logic/resource-manager] Change some string Microsoft.Logic modeled enums back into enums
  profiles/preview/preview/logic/mgmt/logic/models.go
  services/preview/logic/mgmt/2018-07-01-preview/logic/models.go
Labels: RestPRMerged, review

#2606 [AutoPR] botservice/resource-manager
  profiles/preview/preview/botservice/mgmt/botservices/models.go
  services/preview/botservice/mgmt/2018-07-12/botservices/bots.go
  services/preview/botservice/mgmt/2018-07-12/botservices/enterprisechannels.go
  services/preview/botservice/mgmt/2018-07-12/botservices/models.go
Labels: ServicePR, review

#2600 [AutoPR cost-management/resource-manager] Add swagger for above subscription scope: billing account and department
  profiles/preview/preview/costmanagement/mgmt/costmanagement/models.go
  services/preview/costmanagement/mgmt/2018-08-01-preview/costmanagement/reports.go
Labels: RestPRMerged, review

#2649 [AutoPR authorization/resource-manager] Grlin/updatingReqsforRA
  services/authorization/mgmt/2015-07-01/authorization/roleassignments.go
  services/preview/authorization/mgmt/2018-01-01-preview/authorization/roleassignments.go
  services/preview/authorization/mgmt/2018-09-01-preview/authorization/roleassignments.go
Labels: RestPRMerged, review

#2640 [AutoPR sql/resource-manager] Remove sensitivityLabels from sql readme.md
  services/preview/sql/mgmt/2017-03-01-preview/sql/models.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/sensitivitylabels.go
Labels: RestPRMerged, review

#2607 [AutoPR] compute/resource-manager
  profiles/preview/compute/mgmt/compute/models.go
  services/compute/mgmt/2015-06-15/compute/models.go
  services/compute/mgmt/2016-03-30/compute/models.go
  services/compute/mgmt/2017-03-30/compute/models.go
  services/compute/mgmt/2017-12-01/compute/models.go
  services/compute/mgmt/2018-04-01/compute/models.go
  services/compute/mgmt/2018-06-01/compute/models.go
  services/preview/compute/mgmt/2016-04-30-preview/compute/models.go
Labels: ServicePR, review

#2612 [AutoPR cognitiveservices/data-plane/CustomImageSearch/cognitiveservices/data-plane/CustomWebSearch] Changing customConfig to a string
  services/cognitiveservices/v1.0/customimagesearch/custominstance.go
  services/cognitiveservices/v1.0/customsearch/custominstance.go
Labels: RestPRMerged, review

#2614 [AutoPR] sql/resource-manager
  profiles/preview/preview/sql/mgmt/sql/models.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/models.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/sensitivitylabels.go
  services/preview/sql/mgmt/2017-10-01-preview/sql/managedinstanceencryptionprotectors.go
  services/preview/sql/mgmt/2017-10-01-preview/sql/managedinstancekeys.go
  services/preview/sql/mgmt/2017-10-01-preview/sql/models.go
Labels: ServicePR, review

#2620 [AutoPR] network/resource-manager
  services/network/mgmt/2018-06-01/network/models.go
  services/network/mgmt/2018-06-01/network/virtualnetworkgateways.go
Labels: ServicePR, review

#2621 [AutoPR] consumption/resource-manager
  profiles/preview/consumption/mgmt/consumption/models.go
  services/consumption/mgmt/2018-08-31/consumption/aggregatedcost.go
  services/consumption/mgmt/2018-08-31/consumption/balances.go
  services/consumption/mgmt/2018-08-31/consumption/budgets.go
  services/consumption/mgmt/2018-08-31/consumption/charges.go
  services/consumption/mgmt/2018-08-31/consumption/client.go
  services/consumption/mgmt/2018-08-31/consumption/forecasts.go
  services/consumption/mgmt/2018-08-31/consumption/marketplaces.go
  services/consumption/mgmt/2018-08-31/consumption/models.go
  services/consumption/mgmt/2018-08-31/consumption/operations.go
  services/consumption/mgmt/2018-08-31/consumption/pricesheet.go
  services/consumption/mgmt/2018-08-31/consumption/reservationrecommendations.go
  services/consumption/mgmt/2018-08-31/consumption/reservationsdetails.go
  services/consumption/mgmt/2018-08-31/consumption/reservationssummaries.go
  services/consumption/mgmt/2018-08-31/consumption/tags.go
  services/consumption/mgmt/2018-08-31/consumption/usagedetails.go
  services/consumption/mgmt/2018-08-31/consumption/version.go
Labels: ServicePR, review

#2623 [AutoPR] containerinstance/resource-manager
  profiles/preview/containerinstance/mgmt/containerinstance/models.go
  services/containerinstance/mgmt/2018-09-01/containerinstance/client.go
  services/containerinstance/mgmt/2018-09-01/containerinstance/container.go
  services/containerinstance/mgmt/2018-09-01/containerinstance/containergroups.go
  services/containerinstance/mgmt/2018-09-01/containerinstance/containergroupusage.go
  services/containerinstance/mgmt/2018-09-01/containerinstance/models.go
  services/containerinstance/mgmt/2018-09-01/containerinstance/operations.go
  services/containerinstance/mgmt/2018-09-01/containerinstance/version.go
Labels: ServicePR, review

#2655 [AutoPR cost-management/resource-manager] Add swagger for above subscription scope: billing account and department
  profiles/preview/preview/costmanagement/mgmt/costmanagement/models.go
  services/preview/costmanagement/mgmt/2018-08-01-preview/costmanagement/report.go
  services/preview/costmanagement/mgmt/2018-08-01-preview/costmanagement/reports.go
Labels: RestPRMerged, review

#2630 [AutoPR] datafactory/resource-manager
  profiles/preview/datafactory/mgmt/datafactory/models.go
  services/datafactory/mgmt/2018-06-01/datafactory/factories.go
  services/datafactory/mgmt/2018-06-01/datafactory/models.go
Labels: ServicePR, review

#2629 [AutoPR storSimple1200Series/resource-manager] StorSimple1200Series Azure Rest API Spec
  profiles/preview/storsimple1200series/mgmt/storsimple/models.go
  services/storsimple1200series/mgmt/2016-10-01/storsimple/accesscontrolrecords.go
  services/storsimple1200series/mgmt/2016-10-01/storsimple/alerts.go
  services/storsimple1200series/mgmt/2016-10-01/storsimple/availableprovideroperations.go
  services/storsimple1200series/mgmt/2016-10-01/storsimple/backups.go
  services/storsimple1200series/mgmt/2016-10-01/storsimple/backupschedulegroups.go
  services/storsimple1200series/mgmt/2016-10-01/storsimple/chapsettings.go
  services/storsimple1200series/mgmt/2016-10-01/storsimple/client.go
  services/storsimple1200series/mgmt/2016-10-01/storsimple/devices.go
  services/storsimple1200series/mgmt/2016-10-01/storsimple/fileservers.go
  services/storsimple1200series/mgmt/2016-10-01/storsimple/fileshares.go
  services/storsimple1200series/mgmt/2016-10-01/storsimple/iscsidisks.go
  services/storsimple1200series/mgmt/2016-10-01/storsimple/iscsiservers.go
  services/storsimple1200series/mgmt/2016-10-01/storsimple/jobs.go
  services/storsimple1200series/mgmt/2016-10-01/storsimple/managers.go
  services/storsimple1200series/mgmt/2016-10-01/storsimple/models.go
  services/storsimple1200series/mgmt/2016-10-01/storsimple/storageaccountcredentials.go
  services/storsimple1200series/mgmt/2016-10-01/storsimple/storagedomains.go
  services/storsimple1200series/mgmt/2016-10-01/storsimple/version.go
Labels: RestPRMerged, review

#2642 [AutoPR] containerservices/resource-manager
  services/containerservice/mgmt/2018-03-31/containerservice/models.go
Labels: ServicePR, review

#2648 [AutoPR] resources/resource-manager
  profiles/latest/resources/mgmt/locks/models.go
  profiles/preview/resources/mgmt/locks/models.go
  services/resources/mgmt/2016-09-01/locks/client.go
  services/resources/mgmt/2016-09-01/locks/models.go
Labels: ServicePR, review

#2650 [AutoPR] logic/resource-manager
  profiles/preview/preview/logic/mgmt/logic/models.go
  services/preview/logic/mgmt/2018-07-01-preview/logic/models.go
Labels: ServicePR, review

#2656 [AutoPR] cost-management/resource-manager
  profiles/preview/preview/costmanagement/mgmt/costmanagement/models.go
  services/preview/costmanagement/mgmt/2018-08-01-preview/costmanagement/report.go
  services/preview/costmanagement/mgmt/2018-08-01-preview/costmanagement/reports.go
Labels: ServicePR, review

#2662 [AutoPR eventgrid/resource-manager] EventGrid: Updated README.MD configuration to include the new preview API version.
  profiles/preview/preview/eventgrid/mgmt/eventgrid/models.go
  services/preview/eventgrid/mgmt/2018-09-15-preview/eventgrid/client.go
  services/preview/eventgrid/mgmt/2018-09-15-preview/eventgrid/domains.go
  services/preview/eventgrid/mgmt/2018-09-15-preview/eventgrid/domaintopics.go
  services/preview/eventgrid/mgmt/2018-09-15-preview/eventgrid/eventsubscriptions.go
  services/preview/eventgrid/mgmt/2018-09-15-preview/eventgrid/models.go
  services/preview/eventgrid/mgmt/2018-09-15-preview/eventgrid/operations.go
  services/preview/eventgrid/mgmt/2018-09-15-preview/eventgrid/topics.go
  services/preview/eventgrid/mgmt/2018-09-15-preview/eventgrid/topictypes.go
  services/preview/eventgrid/mgmt/2018-09-15-preview/eventgrid/version.go
Labels: RestPRMerged

#2663 [AutoPR] eventgrid/resource-manager
  profiles/preview/preview/eventgrid/mgmt/eventgrid/models.go
  services/preview/eventgrid/mgmt/2018-09-15-preview/eventgrid/client.go
  services/preview/eventgrid/mgmt/2018-09-15-preview/eventgrid/domains.go
  services/preview/eventgrid/mgmt/2018-09-15-preview/eventgrid/domaintopics.go
  services/preview/eventgrid/mgmt/2018-09-15-preview/eventgrid/eventsubscriptions.go
  services/preview/eventgrid/mgmt/2018-09-15-preview/eventgrid/models.go
  services/preview/eventgrid/mgmt/2018-09-15-preview/eventgrid/operations.go
  services/preview/eventgrid/mgmt/2018-09-15-preview/eventgrid/topics.go
  services/preview/eventgrid/mgmt/2018-09-15-preview/eventgrid/topictypes.go
  services/preview/eventgrid/mgmt/2018-09-15-preview/eventgrid/version.go
Labels: ServicePR, review

#2666 [AutoPR monitor/resource-manager] Fix Go SDK generation
  profiles/preview/preview/monitor/mgmt/insights/models.go
  services/preview/monitor/mgmt/2018-09-01/insights/actiongroups.go
  services/preview/monitor/mgmt/2018-09-01/insights/activitylogalerts.go
  services/preview/monitor/mgmt/2018-09-01/insights/activitylogs.go
  services/preview/monitor/mgmt/2018-09-01/insights/alertruleincidents.go
  services/preview/monitor/mgmt/2018-09-01/insights/alertrules.go
  services/preview/monitor/mgmt/2018-09-01/insights/autoscalesettings.go
  services/preview/monitor/mgmt/2018-09-01/insights/client.go
  services/preview/monitor/mgmt/2018-09-01/insights/diagnosticsettings.go
  services/preview/monitor/mgmt/2018-09-01/insights/diagnosticsettingscategory.go
  services/preview/monitor/mgmt/2018-09-01/insights/eventcategories.go
  services/preview/monitor/mgmt/2018-09-01/insights/logprofiles.go
  services/preview/monitor/mgmt/2018-09-01/insights/metricalerts.go
  services/preview/monitor/mgmt/2018-09-01/insights/metricalertsstatus.go
  services/preview/monitor/mgmt/2018-09-01/insights/metricbaseline.go
  services/preview/monitor/mgmt/2018-09-01/insights/metricdefinitions.go
  services/preview/monitor/mgmt/2018-09-01/insights/metricnamespaces.go
  services/preview/monitor/mgmt/2018-09-01/insights/metrics.go
  services/preview/monitor/mgmt/2018-09-01/insights/models.go
  services/preview/monitor/mgmt/2018-09-01/insights/operations.go
  services/preview/monitor/mgmt/2018-09-01/insights/scheduledqueryrules.go
  services/preview/monitor/mgmt/2018-09-01/insights/tenantactivitylogs.go
  services/preview/monitor/mgmt/2018-09-01/insights/version.go
Labels: RestPRMerged, review

#2669 [AutoPR operationalinsights/data-plane/applicationinsights/data-plane] [App Insights/Operational Insights] Add GET /query operation, fix operationId inconsistency
  services/operationalinsights/v1/operationalinsights/client.go
  services/operationalinsights/v1/operationalinsights/query.go
Labels: RestPRMerged, review

#2658 [AutoPR] storSimple1200Series/resource-manager
  profiles/preview/storsimple1200series/mgmt/storsimple/models.go
  services/storsimple1200series/mgmt/2016-10-01/storsimple/accesscontrolrecords.go
  services/storsimple1200series/mgmt/2016-10-01/storsimple/alerts.go
  services/storsimple1200series/mgmt/2016-10-01/storsimple/availableprovideroperations.go
  services/storsimple1200series/mgmt/2016-10-01/storsimple/backups.go
  services/storsimple1200series/mgmt/2016-10-01/storsimple/backupschedulegroups.go
  services/storsimple1200series/mgmt/2016-10-01/storsimple/chapsettings.go
  services/storsimple1200series/mgmt/2016-10-01/storsimple/client.go
  services/storsimple1200series/mgmt/2016-10-01/storsimple/devices.go
  services/storsimple1200series/mgmt/2016-10-01/storsimple/fileservers.go
  services/storsimple1200series/mgmt/2016-10-01/storsimple/fileshares.go
  services/storsimple1200series/mgmt/2016-10-01/storsimple/iscsidisks.go
  services/storsimple1200series/mgmt/2016-10-01/storsimple/iscsiservers.go
  services/storsimple1200series/mgmt/2016-10-01/storsimple/jobs.go
  services/storsimple1200series/mgmt/2016-10-01/storsimple/managers.go
  services/storsimple1200series/mgmt/2016-10-01/storsimple/models.go
  services/storsimple1200series/mgmt/2016-10-01/storsimple/storageaccountcredentials.go
  services/storsimple1200series/mgmt/2016-10-01/storsimple/storagedomains.go
  services/storsimple1200series/mgmt/2016-10-01/storsimple/version.go
Labels: ServicePR, review

#2681 [AutoPR compute/resource-manager] Swagger spec for disk.json + compute.json 2018-06
  profiles/preview/compute/mgmt/compute/models.go
  services/compute/mgmt/2018-06-01/compute/disks.go
  services/compute/mgmt/2018-06-01/compute/models.go
  services/compute/mgmt/2018-06-01/compute/snapshots.go
Labels: RestPRMerged, review

#2685 [AutoPR] compute/resource-manager
  profiles/preview/compute/mgmt/compute/models.go
  services/compute/mgmt/2018-06-01/compute/disks.go
  services/compute/mgmt/2018-06-01/compute/models.go
  services/compute/mgmt/2018-06-01/compute/snapshots.go
Labels: ServicePR, review

#2689 [AutoPR mariadb/resource-manager] Fix Go SDK codegen for mariadb
  profiles/preview/preview/mariadb/mgmt/mariadb/models.go
  services/preview/mariadb/mgmt/2018-06-01-preview/mariadb/checknameavailability.go
  services/preview/mariadb/mgmt/2018-06-01-preview/mariadb/client.go
  services/preview/mariadb/mgmt/2018-06-01-preview/mariadb/configurations.go
  services/preview/mariadb/mgmt/2018-06-01-preview/mariadb/databases.go
  services/preview/mariadb/mgmt/2018-06-01-preview/mariadb/firewallrules.go
  services/preview/mariadb/mgmt/2018-06-01-preview/mariadb/locationbasedperformancetier.go
  services/preview/mariadb/mgmt/2018-06-01-preview/mariadb/logfiles.go
  services/preview/mariadb/mgmt/2018-06-01-preview/mariadb/models.go
  services/preview/mariadb/mgmt/2018-06-01-preview/mariadb/operations.go
  services/preview/mariadb/mgmt/2018-06-01-preview/mariadb/servers.go
  services/preview/mariadb/mgmt/2018-06-01-preview/mariadb/serversecurityalertpolicies.go
  services/preview/mariadb/mgmt/2018-06-01-preview/mariadb/version.go
Labels: RestPRMerged, review

#2690 [AutoPR] mariadb/resource-manager
  profiles/preview/preview/mariadb/mgmt/mariadb/models.go
  services/preview/mariadb/mgmt/2018-06-01-preview/mariadb/checknameavailability.go
  services/preview/mariadb/mgmt/2018-06-01-preview/mariadb/client.go
  services/preview/mariadb/mgmt/2018-06-01-preview/mariadb/configurations.go
  services/preview/mariadb/mgmt/2018-06-01-preview/mariadb/databases.go
  services/preview/mariadb/mgmt/2018-06-01-preview/mariadb/firewallrules.go
  services/preview/mariadb/mgmt/2018-06-01-preview/mariadb/locationbasedperformancetier.go
  services/preview/mariadb/mgmt/2018-06-01-preview/mariadb/logfiles.go
  services/preview/mariadb/mgmt/2018-06-01-preview/mariadb/models.go
  services/preview/mariadb/mgmt/2018-06-01-preview/mariadb/operations.go
  services/preview/mariadb/mgmt/2018-06-01-preview/mariadb/servers.go
  services/preview/mariadb/mgmt/2018-06-01-preview/mariadb/serversecurityalertpolicies.go
  services/preview/mariadb/mgmt/2018-06-01-preview/mariadb/version.go
Labels: ServicePR, review

#2670 [AutoPR adhybridhealthservice/resource-manager] Update ADHybridHealthService.json
  services/adhybridhealthservice/mgmt/2014-01-01/adhybridhealthservice/models.go
Labels: RestPRMerged, review

#2667 [AutoPR datalake-analytics/data-plane] Add
  services/datalake/analytics/2016-11-01/job/models.go
Labels: RestPRMerged, review

#2668 [AutoPR monitor/data-plane] Publish public preview swagger spec for "Azure metrics Ingestion REST API"
  profiles/preview/preview/monitor/monitor/models.go
  services/preview/monitor/2018-09-01-preview/monitor/client.go
  services/preview/monitor/2018-09-01-preview/monitor/models.go
  services/preview/monitor/2018-09-01-preview/monitor/version.go
Labels: RestPRMerged, review

#2698 [AutoPR automation/resource-manager] New tag for 2018-06 APIs for Automation
  services/preview/automation/mgmt/2018-06-preview/automation/account.go
  services/preview/automation/mgmt/2018-06-preview/automation/activity.go
  services/preview/automation/mgmt/2018-06-preview/automation/agentregistrationinformation.go
  services/preview/automation/mgmt/2018-06-preview/automation/certificate.go
  services/preview/automation/mgmt/2018-06-preview/automation/client.go
  services/preview/automation/mgmt/2018-06-preview/automation/connection.go
  services/preview/automation/mgmt/2018-06-preview/automation/connectiontype.go
  services/preview/automation/mgmt/2018-06-preview/automation/credential.go
  services/preview/automation/mgmt/2018-06-preview/automation/dsccompilationjob.go
  services/preview/automation/mgmt/2018-06-preview/automation/dsccompilationjobstream.go
  services/preview/automation/mgmt/2018-06-preview/automation/dscconfiguration.go
  services/preview/automation/mgmt/2018-06-preview/automation/dscnode.go
  services/preview/automation/mgmt/2018-06-preview/automation/dscnodeconfiguration.go
  services/preview/automation/mgmt/2018-06-preview/automation/fields.go
  services/preview/automation/mgmt/2018-06-preview/automation/hybridrunbookworkergroup.go
  services/preview/automation/mgmt/2018-06-preview/automation/job.go
  services/preview/automation/mgmt/2018-06-preview/automation/jobschedule.go
  services/preview/automation/mgmt/2018-06-preview/automation/jobstream.go
  services/preview/automation/mgmt/2018-06-preview/automation/keys.go
  services/preview/automation/mgmt/2018-06-preview/automation/linkedworkspace.go
  services/preview/automation/mgmt/2018-06-preview/automation/models.go
  services/preview/automation/mgmt/2018-06-preview/automation/module.go
  services/preview/automation/mgmt/2018-06-preview/automation/nodecountinformation.go
  services/preview/automation/mgmt/2018-06-preview/automation/nodereports.go
  services/preview/automation/mgmt/2018-06-preview/automation/objectdatatypes.go
  services/preview/automation/mgmt/2018-06-preview/automation/operations.go
  services/preview/automation/mgmt/2018-06-preview/automation/runbook.go
  services/preview/automation/mgmt/2018-06-preview/automation/runbookdraft.go
  services/preview/automation/mgmt/2018-06-preview/automation/schedule.go
  services/preview/automation/mgmt/2018-06-preview/automation/softwareupdateconfigurationmachineruns.go
  services/preview/automation/mgmt/2018-06-preview/automation/softwareupdateconfigurationruns.go
  services/preview/automation/mgmt/2018-06-preview/automation/softwareupdateconfigurations.go
  services/preview/automation/mgmt/2018-06-preview/automation/sourcecontrol.go
  services/preview/automation/mgmt/2018-06-preview/automation/sourcecontrolsyncjob.go
  services/preview/automation/mgmt/2018-06-preview/automation/sourcecontrolsyncjobstreams.go
  services/preview/automation/mgmt/2018-06-preview/automation/statistics.go
  services/preview/automation/mgmt/2018-06-preview/automation/testjob.go
  services/preview/automation/mgmt/2018-06-preview/automation/testjobstreams.go
  services/preview/automation/mgmt/2018-06-preview/automation/usages.go
  services/preview/automation/mgmt/2018-06-preview/automation/variable.go
  services/preview/automation/mgmt/2018-06-preview/automation/version.go
  services/preview/automation/mgmt/2018-06-preview/automation/watcher.go
  services/preview/automation/mgmt/2018-06-preview/automation/webhook.go
Labels: RestPRMerged

#2701 [AutoPR monitor/data-plane] Fix the swagger spec to ensure the documentaiton generation works as expected
  profiles/preview/preview/monitor/monitor/models.go
  services/preview/monitor/2018-09-01-preview/monitor/client.go
  services/preview/monitor/2018-09-01-preview/monitor/metrics.go
Labels: RestPRMerged, review

#2699 [AutoPR] automation/resource-manager
  services/preview/automation/mgmt/2018-06-preview/automation/account.go
  services/preview/automation/mgmt/2018-06-preview/automation/activity.go
  services/preview/automation/mgmt/2018-06-preview/automation/agentregistrationinformation.go
  services/preview/automation/mgmt/2018-06-preview/automation/certificate.go
  services/preview/automation/mgmt/2018-06-preview/automation/client.go
  services/preview/automation/mgmt/2018-06-preview/automation/connection.go
  services/preview/automation/mgmt/2018-06-preview/automation/connectiontype.go
  services/preview/automation/mgmt/2018-06-preview/automation/credential.go
  services/preview/automation/mgmt/2018-06-preview/automation/dsccompilationjob.go
  services/preview/automation/mgmt/2018-06-preview/automation/dsccompilationjobstream.go
  services/preview/automation/mgmt/2018-06-preview/automation/dscconfiguration.go
  services/preview/automation/mgmt/2018-06-preview/automation/dscnode.go
  services/preview/automation/mgmt/2018-06-preview/automation/dscnodeconfiguration.go
  services/preview/automation/mgmt/2018-06-preview/automation/fields.go
  services/preview/automation/mgmt/2018-06-preview/automation/hybridrunbookworkergroup.go
  services/preview/automation/mgmt/2018-06-preview/automation/job.go
  services/preview/automation/mgmt/2018-06-preview/automation/jobschedule.go
  services/preview/automation/mgmt/2018-06-preview/automation/jobstream.go
  services/preview/automation/mgmt/2018-06-preview/automation/keys.go
  services/preview/automation/mgmt/2018-06-preview/automation/linkedworkspace.go
  services/preview/automation/mgmt/2018-06-preview/automation/models.go
  services/preview/automation/mgmt/2018-06-preview/automation/module.go
  services/preview/automation/mgmt/2018-06-preview/automation/nodecountinformation.go
  services/preview/automation/mgmt/2018-06-preview/automation/nodereports.go
  services/preview/automation/mgmt/2018-06-preview/automation/objectdatatypes.go
  services/preview/automation/mgmt/2018-06-preview/automation/operations.go
  services/preview/automation/mgmt/2018-06-preview/automation/runbook.go
  services/preview/automation/mgmt/2018-06-preview/automation/runbookdraft.go
  services/preview/automation/mgmt/2018-06-preview/automation/schedule.go
  services/preview/automation/mgmt/2018-06-preview/automation/softwareupdateconfigurationmachineruns.go
  services/preview/automation/mgmt/2018-06-preview/automation/softwareupdateconfigurationruns.go
  services/preview/automation/mgmt/2018-06-preview/automation/softwareupdateconfigurations.go
  services/preview/automation/mgmt/2018-06-preview/automation/sourcecontrol.go
  services/preview/automation/mgmt/2018-06-preview/automation/sourcecontrolsyncjob.go
  services/preview/automation/mgmt/2018-06-preview/automation/sourcecontrolsyncjobstreams.go
  services/preview/automation/mgmt/2018-06-preview/automation/statistics.go
  services/preview/automation/mgmt/2018-06-preview/automation/testjob.go
  services/preview/automation/mgmt/2018-06-preview/automation/testjobstreams.go
  services/preview/automation/mgmt/2018-06-preview/automation/usages.go
  services/preview/automation/mgmt/2018-06-preview/automation/variable.go
  services/preview/automation/mgmt/2018-06-preview/automation/version.go
  services/preview/automation/mgmt/2018-06-preview/automation/watcher.go
  services/preview/automation/mgmt/2018-06-preview/automation/webhook.go
Labels: ServicePR, review

#2709 [AutoPR security/resource-manager] [Do Not Merge Until September 15th] Introducing new API for Advanced Threat Protection
  profiles/preview/preview/security/mgmt/security/models.go
  services/preview/security/mgmt/2017-08-01-preview/security/advancedthreatprotection.go
  services/preview/security/mgmt/2017-08-01-preview/security/models.go
Labels: RestPRMerged, review

#2673 [AutoPR sql/resource-manager] Add algorithm types to threat detection disabled alerts description
  services/preview/sql/mgmt/2015-05-01-preview/sql/models.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/models.go
  services/sql/mgmt/2014-04-01/sql/models.go
Labels: RestPRMerged, review

#2697 [AutoPR machinelearningservices/resource-manager] Masable/update workspace
  services/preview/machinelearning/mgmt/2018-03-01-preview/services/models.go
Labels: RestPRMerged, review

#2710 [AutoPR] security/resource-manager
  profiles/preview/preview/security/mgmt/security/models.go
  services/preview/security/mgmt/2017-08-01-preview/security/advancedthreatprotection.go
  services/preview/security/mgmt/2017-08-01-preview/security/models.go
Labels: ServicePR, review

#2711 [AutoPR] sql/resource-manager
  services/preview/sql/mgmt/2015-05-01-preview/sql/models.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/models.go
  services/sql/mgmt/2014-04-01/sql/models.go
Labels: ServicePR, review

#2713 [AutoPR] machinelearningservices/resource-manager
  services/preview/machinelearning/mgmt/2018-03-01-preview/services/models.go
Labels: ServicePR, review

#2700 [AutoPR dns/resource-manager] Add readme.typescript.md for DNS
  services/preview/machinelearning/mgmt/2018-03-01-preview/services/models.go
Labels: RestPRMerged, review

#2717 [AutoPR] datalake-analytics/data-plane
  swagger_to_sdk_config.json
Labels: ServicePR, review

#2727 [AutoPR storagesync/resource-manager] StorageSync : Clone existing ApiVersion 2018-04-02 for creating a new version 2018-07-01
  profiles/preview/storagesync/mgmt/storagesync/models.go
  services/storagesync/mgmt/2018-04-02/storagesync/client.go
  services/storagesync/mgmt/2018-04-02/storagesync/cloudendpointsgroup.go
  services/storagesync/mgmt/2018-04-02/storagesync/models.go
  services/storagesync/mgmt/2018-04-02/storagesync/operationsgroup.go
  services/storagesync/mgmt/2018-04-02/storagesync/registeredserversgroup.go
  services/storagesync/mgmt/2018-04-02/storagesync/serverendpointsgroup.go
  services/storagesync/mgmt/2018-04-02/storagesync/storagesyncservicesgroup.go
  services/storagesync/mgmt/2018-04-02/storagesync/syncgroupsgroup.go
  services/storagesync/mgmt/2018-04-02/storagesync/version.go
  services/storagesync/mgmt/2018-04-02/storagesync/workflowsgroup.go
  services/storagesync/mgmt/2018-07-01/storagesync/client.go
  services/storagesync/mgmt/2018-07-01/storagesync/cloudendpoints.go
  services/storagesync/mgmt/2018-07-01/storagesync/models.go
  services/storagesync/mgmt/2018-07-01/storagesync/operations.go
  services/storagesync/mgmt/2018-07-01/storagesync/registeredservers.go
  services/storagesync/mgmt/2018-07-01/storagesync/serverendpoints.go
  services/storagesync/mgmt/2018-07-01/storagesync/storagesyncservices.go
  services/storagesync/mgmt/2018-07-01/storagesync/syncgroups.go
  services/storagesync/mgmt/2018-07-01/storagesync/version.go
  services/storagesync/mgmt/2018-07-01/storagesync/workflows.go
Labels: RestPRMerged, review

#2733 [AutoPR storagesync/resource-manager] Fix Go SDK for storagesync
  profiles/preview/preview/storagesync/mgmt/storagesync/models.go
  profiles/preview/storagesync/mgmt/storagesync/models.go
  services/preview/storagesync/mgmt/2018-07-01/storagesync/client.go
  services/preview/storagesync/mgmt/2018-07-01/storagesync/cloudendpoints.go
  services/preview/storagesync/mgmt/2018-07-01/storagesync/models.go
  services/preview/storagesync/mgmt/2018-07-01/storagesync/operations.go
  services/preview/storagesync/mgmt/2018-07-01/storagesync/registeredservers.go
  services/preview/storagesync/mgmt/2018-07-01/storagesync/serverendpoints.go
  services/preview/storagesync/mgmt/2018-07-01/storagesync/services.go
  services/preview/storagesync/mgmt/2018-07-01/storagesync/syncgroups.go
  services/preview/storagesync/mgmt/2018-07-01/storagesync/version.go
  services/preview/storagesync/mgmt/2018-07-01/storagesync/workflows.go
  services/storagesync/mgmt/2018-04-02/storagesync/client.go
  services/storagesync/mgmt/2018-04-02/storagesync/cloudendpointsgroup.go
  services/storagesync/mgmt/2018-04-02/storagesync/models.go
  services/storagesync/mgmt/2018-04-02/storagesync/operationsgroup.go
  services/storagesync/mgmt/2018-04-02/storagesync/registeredserversgroup.go
  services/storagesync/mgmt/2018-04-02/storagesync/serverendpointsgroup.go
  services/storagesync/mgmt/2018-04-02/storagesync/servicesgroup.go
  services/storagesync/mgmt/2018-04-02/storagesync/syncgroupsgroup.go
  services/storagesync/mgmt/2018-04-02/storagesync/version.go
  services/storagesync/mgmt/2018-04-02/storagesync/workflowsgroup.go
Labels: RestPRMerged, review

#2721 [AutoPR sql/resource-manager] Swagger Changes to Add DnsZonePartner and Collation into Managed Instance
  services/preview/sql/mgmt/2015-05-01-preview/sql/models.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/models.go
Labels: RestPRMerged, review

#2735 [AutoPR web/resource-manager] Add readme.typescript.md to web/resource-manager
  profiles/preview/web/mgmt/web/models.go
  services/web/mgmt/2018-02-01/web/apps.go
  services/web/mgmt/2018-02-01/web/models.go
Labels: RestPRMerged, review

#2737 [AutoPR] storagesync/resource-manager
  profiles/preview/preview/storagesync/mgmt/storagesync/models.go
  profiles/preview/storagesync/mgmt/storagesync/models.go
  services/preview/storagesync/mgmt/2018-07-01/storagesync/client.go
  services/preview/storagesync/mgmt/2018-07-01/storagesync/cloudendpoints.go
  services/preview/storagesync/mgmt/2018-07-01/storagesync/models.go
  services/preview/storagesync/mgmt/2018-07-01/storagesync/operations.go
  services/preview/storagesync/mgmt/2018-07-01/storagesync/registeredservers.go
  services/preview/storagesync/mgmt/2018-07-01/storagesync/serverendpoints.go
  services/preview/storagesync/mgmt/2018-07-01/storagesync/services.go
  services/preview/storagesync/mgmt/2018-07-01/storagesync/syncgroups.go
  services/preview/storagesync/mgmt/2018-07-01/storagesync/version.go
  services/preview/storagesync/mgmt/2018-07-01/storagesync/workflows.go
  services/storagesync/mgmt/2018-04-02/storagesync/client.go
  services/storagesync/mgmt/2018-04-02/storagesync/cloudendpointsgroup.go
  services/storagesync/mgmt/2018-04-02/storagesync/models.go
  services/storagesync/mgmt/2018-04-02/storagesync/operationsgroup.go
  services/storagesync/mgmt/2018-04-02/storagesync/registeredserversgroup.go
  services/storagesync/mgmt/2018-04-02/storagesync/serverendpointsgroup.go
  services/storagesync/mgmt/2018-04-02/storagesync/servicesgroup.go
  services/storagesync/mgmt/2018-04-02/storagesync/syncgroupsgroup.go
  services/storagesync/mgmt/2018-04-02/storagesync/version.go
  services/storagesync/mgmt/2018-04-02/storagesync/workflowsgroup.go
Labels: ServicePR, review

#2738 [AutoPR] sql/resource-manager
  services/preview/sql/mgmt/2015-05-01-preview/sql/models.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/models.go
Labels: ServicePR, review

#2741 [AutoPR monitor/data-plane] Update Azure metrics data plane swagger to address few doc generation bugs
  services/preview/monitor/2018-09-01-preview/monitor/metrics.go
Labels: RestPRMerged, review

#2742 [AutoPR] monitor/data-plane
  services/preview/monitor/2018-09-01-preview/monitor/metrics.go
Labels: ServicePR, review

#2724 [AutoPR databox/resource-manager] specs changes for azure databox ga
  profiles/preview/databox/mgmt/databox/models.go
  services/databox/mgmt/2018-01-01/databox/jobs.go
  services/databox/mgmt/2018-01-01/databox/models.go
  services/databox/mgmt/2018-01-01/databox/service.go
Labels: RestPRMerged, review

#2747 [AutoPR storSimple1200Series/resource-manager] Fixed GetOperations route to not have subId
  services/storsimple1200series/mgmt/2016-10-01/storsimple/availableprovideroperations.go
Labels: RestPRMerged, review

#2725 [AutoPR cognitiveservices/data-plane/LUIS/Authoring] Modifying app version setting name.
  profiles/preview/cognitiveservices/luis/authoring/models.go
  services/cognitiveservices/v2.0/luis/authoring/models.go
  services/cognitiveservices/v2.0/luis/authoring/settings.go
Labels: RestPRMerged, review

#2731 [AutoPR monitor/resource-manager] [Azure monitor] Add missing enum for aggregation type
  profiles/preview/preview/monitor/mgmt/insights/models.go
  services/preview/monitor/mgmt/2017-05-01-preview/insights/models.go
  services/preview/monitor/mgmt/2018-03-01/insights/models.go
  services/preview/monitor/mgmt/2018-09-01/insights/models.go
Labels: RestPRMerged, review

#2746 [AutoPR containerservices/resource-manager] Remove serverAppSecret which is not required for AKS cluster updates
  services/containerservice/mgmt/2018-03-31/containerservice/managedclusters.go
Labels: RestPRMerged, review

#2759 [AutoPR datafactory/resource-manager] [Datafactory] Add SecureInput property to Activity. Add recursive option to cancel API
  services/datafactory/mgmt/2018-06-01/datafactory/models.go
  services/datafactory/mgmt/2018-06-01/datafactory/pipelineruns.go
Labels: RestPRMerged

#2761 [AutoPR machinelearningservices/resource-manager] update machine learning compute portion of the machine learning services swagger
  profiles/preview/preview/machinelearning/mgmt/services/models.go
  services/preview/machinelearning/mgmt/2018-03-01-preview/services/machinelearningcompute.go
  services/preview/machinelearning/mgmt/2018-03-01-preview/services/models.go
Labels: RestPRMerged, review

#2756 [AutoPR compute/resource-manager] More detail added to the descriptions.
  services/compute/mgmt/2018-06-01/compute/galleries.go
  services/compute/mgmt/2018-06-01/compute/galleryimages.go
  services/compute/mgmt/2018-06-01/compute/galleryimageversions.go
  services/compute/mgmt/2018-06-01/compute/models.go
Labels: RestPRMerged, review

#2765 [AutoPR resources/resource-manager] Fix typo, the provider should be Microsoft.Authorization
  services/resources/mgmt/2016-09-01/locks/client.go
Labels: RestPRMerged, review

#2734 [AutoPR datalake-analytics/data-plane] Add hierarchyQueueNode into JobInformation(Basic)
  services/datalake/analytics/2016-11-01/job/models.go
  services/preview/datalake/analytics/2015-11-01-preview/job/models.go
  services/preview/datalake/analytics/2016-03-20-preview/job/models.go
  services/preview/datalake/analytics/2017-09-01-preview/job/models.go
Labels: RestPRMerged, review

#2771 [AutoPR resources/resource-manager] Fix ARMViolations for Microsoft.Solutions
  profiles/preview/preview/resources/mgmt/managedapplications/models.go
  services/preview/resources/mgmt/2016-09-01-preview/managedapplications/appliances.go
  services/preview/resources/mgmt/2016-09-01-preview/managedapplications/client.go
  services/preview/resources/mgmt/2016-09-01-preview/managedapplications/models.go
Labels: RestPRMerged

#2750 [AutoPR] storSimple1200Series/resource-manager
  services/storsimple1200series/mgmt/2016-10-01/storsimple/availableprovideroperations.go
Labels: ServicePR, review

#2751 [AutoPR] cognitiveservices/data-plane/LUIS/Authoring
  profiles/preview/cognitiveservices/luis/authoring/models.go
  services/cognitiveservices/v2.0/luis/authoring/models.go
  services/cognitiveservices/v2.0/luis/authoring/settings.go
Labels: ServicePR, review

#2753 [AutoPR] monitor/resource-manager
  profiles/preview/preview/monitor/mgmt/insights/models.go
  services/preview/monitor/mgmt/2017-05-01-preview/insights/models.go
  services/preview/monitor/mgmt/2018-03-01/insights/models.go
  services/preview/monitor/mgmt/2018-09-01/insights/models.go
Labels: ServicePR, review

#2762 [AutoPR] machinelearningservices/resource-manager
  profiles/preview/preview/machinelearning/mgmt/services/models.go
  services/preview/machinelearning/mgmt/2018-03-01-preview/services/machinelearningcompute.go
  services/preview/machinelearning/mgmt/2018-03-01-preview/services/models.go
Labels: ServicePR, review

#2768 [AutoPR] datalake-analytics/data-plane
  services/datalake/analytics/2016-11-01/job/models.go
  services/preview/datalake/analytics/2015-11-01-preview/job/models.go
  services/preview/datalake/analytics/2016-03-20-preview/job/models.go
  services/preview/datalake/analytics/2017-09-01-preview/job/models.go
Labels: ServicePR, review

#2760 [AutoPR] datafactory/resource-manager
  services/datafactory/mgmt/2018-06-01/datafactory/models.go
  services/datafactory/mgmt/2018-06-01/datafactory/pipelineruns.go
Labels: ServicePR, review

#2764 [AutoPR] compute/resource-manager
  services/compute/mgmt/2018-06-01/compute/galleries.go
  services/compute/mgmt/2018-06-01/compute/galleryimages.go
  services/compute/mgmt/2018-06-01/compute/galleryimageversions.go
  services/compute/mgmt/2018-06-01/compute/models.go
Labels: ServicePR, review

#2745 [AutoPR] databox/resource-manager
  profiles/preview/databox/mgmt/databox/models.go
  services/databox/mgmt/2018-01-01/databox/jobs.go
  services/databox/mgmt/2018-01-01/databox/models.go
  services/databox/mgmt/2018-01-01/databox/service.go
  swagger_to_sdk_config.json
Labels: ServicePR, review

#2777 [AutoPR resources/resource-manager] Change operationId of Microsoft.Authorization
  profiles/latest/resources/mgmt/locks/models.go
  profiles/preview/resources/mgmt/locks/models.go
  services/resources/mgmt/2016-09-01/locks/authorizationoperations.go
  services/resources/mgmt/2016-09-01/locks/client.go
Labels: RestPRMerged, review

#2763 Add changelog command to apidiff tool
  tools/apidiff/cmd/changelog.go
  tools/apidiff/cmd/packages.go
Labels: review

#2783 [AutoPR recoveryservicesbackup/resource-manager] Move Go SDK config for back to its own config file
  profiles/latest/recoveryservices/mgmt/backup/models.go
  profiles/preview/recoveryservices/mgmt/backup/models.go
  services/recoveryservices/mgmt/2016-06-01/backup/models.go
  services/recoveryservices/mgmt/2017-07-01/backup/models.go
Labels: RestPRMerged, review

#2785 [AutoPR] recoveryservicesbackup/resource-manager
  profiles/latest/recoveryservices/mgmt/backup/models.go
  profiles/preview/recoveryservices/mgmt/backup/models.go
  services/recoveryservices/mgmt/2016-06-01/backup/models.go
  services/recoveryservices/mgmt/2017-07-01/backup/models.go
Labels: ServicePR, review

#2782 [AutoPR automation/resource-manager] Quick fix to response type of runbookdraftcontent get
  services/preview/automation/mgmt/2018-06-preview/automation/runbookdraft.go
Labels: RestPRMerged, review

#2779 [AutoPR compute/resource-manager] Updated comments and introduced AvailabilitySetSkuType …
  profiles/preview/compute/mgmt/compute/models.go
  services/compute/mgmt/2018-06-01/compute/models.go
Labels: RestPRMerged, review

#2793 [AutoPR compute/resource-manager] Improve gallery swagger by improving one description and mark one param as required.
  services/compute/mgmt/2018-06-01/compute/galleries.go
Labels: RestPRMerged, review

#2786 update dependencies
  Gopkg.lock
  Gopkg.toml
Labels: review

#2796 [AutoPR compute/resource-manager] Add compute 2018-10-01 to Go SDK
  profiles/preview/compute/mgmt/compute/models.go
  services/compute/mgmt/2018-10-01/compute/availabilitysets.go
  services/compute/mgmt/2018-10-01/compute/client.go
  services/compute/mgmt/2018-10-01/compute/containerservices.go
  services/compute/mgmt/2018-10-01/compute/disks.go
  services/compute/mgmt/2018-10-01/compute/galleries.go
  services/compute/mgmt/2018-10-01/compute/galleryimages.go
  services/compute/mgmt/2018-10-01/compute/galleryimageversions.go
  services/compute/mgmt/2018-10-01/compute/images.go
  services/compute/mgmt/2018-10-01/compute/loganalytics.go
  services/compute/mgmt/2018-10-01/compute/models.go
  services/compute/mgmt/2018-10-01/compute/operations.go
  services/compute/mgmt/2018-10-01/compute/resourceskus.go
  services/compute/mgmt/2018-10-01/compute/snapshots.go
  services/compute/mgmt/2018-10-01/compute/usage.go
  services/compute/mgmt/2018-10-01/compute/version.go
  services/compute/mgmt/2018-10-01/compute/virtualmachineextensionimages.go
  services/compute/mgmt/2018-10-01/compute/virtualmachineextensions.go
  services/compute/mgmt/2018-10-01/compute/virtualmachineimages.go
  services/compute/mgmt/2018-10-01/compute/virtualmachineruncommands.go
  services/compute/mgmt/2018-10-01/compute/virtualmachines.go
  services/compute/mgmt/2018-10-01/compute/virtualmachinescalesetextensions.go
  services/compute/mgmt/2018-10-01/compute/virtualmachinescalesetrollingupgrades.go
  services/compute/mgmt/2018-10-01/compute/virtualmachinescalesets.go
  services/compute/mgmt/2018-10-01/compute/virtualmachinescalesetvms.go
  services/compute/mgmt/2018-10-01/compute/virtualmachinesizes.go
Labels: RestPRMerged, review

#2781 [AutoPR frontdoor/resource-manager] Front Door publicpreview
  profiles/preview/preview/frontdoor/mgmt/frontdoor/models.go
  services/preview/frontdoor/mgmt/2018-08-01-preview/frontdoor/backendpools.go
  services/preview/frontdoor/mgmt/2018-08-01-preview/frontdoor/client.go
  services/preview/frontdoor/mgmt/2018-08-01-preview/frontdoor/endpoints.go
  services/preview/frontdoor/mgmt/2018-08-01-preview/frontdoor/frontdoors.go
  services/preview/frontdoor/mgmt/2018-08-01-preview/frontdoor/frontendendpoints.go
  services/preview/frontdoor/mgmt/2018-08-01-preview/frontdoor/healthprobesettings.go
  services/preview/frontdoor/mgmt/2018-08-01-preview/frontdoor/loadbalancingsettings.go
  services/preview/frontdoor/mgmt/2018-08-01-preview/frontdoor/models.go
  services/preview/frontdoor/mgmt/2018-08-01-preview/frontdoor/policies.go
  services/preview/frontdoor/mgmt/2018-08-01-preview/frontdoor/routingrules.go
  services/preview/frontdoor/mgmt/2018-08-01-preview/frontdoor/version.go
Labels: RestPRMerged, review

#2801 [AutoPR] frontdoor/resource-manager
  profiles/preview/preview/frontdoor/mgmt/frontdoor/models.go
  services/preview/frontdoor/mgmt/2018-08-01-preview/frontdoor/backendpools.go
  services/preview/frontdoor/mgmt/2018-08-01-preview/frontdoor/client.go
  services/preview/frontdoor/mgmt/2018-08-01-preview/frontdoor/endpoints.go
  services/preview/frontdoor/mgmt/2018-08-01-preview/frontdoor/frontdoors.go
  services/preview/frontdoor/mgmt/2018-08-01-preview/frontdoor/frontendendpoints.go
  services/preview/frontdoor/mgmt/2018-08-01-preview/frontdoor/healthprobesettings.go
  services/preview/frontdoor/mgmt/2018-08-01-preview/frontdoor/loadbalancingsettings.go
  services/preview/frontdoor/mgmt/2018-08-01-preview/frontdoor/models.go
  services/preview/frontdoor/mgmt/2018-08-01-preview/frontdoor/policies.go
  services/preview/frontdoor/mgmt/2018-08-01-preview/frontdoor/routingrules.go
  services/preview/frontdoor/mgmt/2018-08-01-preview/frontdoor/version.go
Labels: ServicePR, review

#2802 [AutoPR] deploymentmanager/resource-manager
  profiles/preview/preview/deploymentmanager/mgmt/deploymentmanager/models.go
  services/preview/deploymentmanager/mgmt/2018-09-01-preview/deploymentmanager/artifactsources.go
  services/preview/deploymentmanager/mgmt/2018-09-01-preview/deploymentmanager/client.go
  services/preview/deploymentmanager/mgmt/2018-09-01-preview/deploymentmanager/models.go
  services/preview/deploymentmanager/mgmt/2018-09-01-preview/deploymentmanager/operations.go
  services/preview/deploymentmanager/mgmt/2018-09-01-preview/deploymentmanager/rollouts.go
  services/preview/deploymentmanager/mgmt/2018-09-01-preview/deploymentmanager/services.go
  services/preview/deploymentmanager/mgmt/2018-09-01-preview/deploymentmanager/servicetopologies.go
  services/preview/deploymentmanager/mgmt/2018-09-01-preview/deploymentmanager/serviceunits.go
  services/preview/deploymentmanager/mgmt/2018-09-01-preview/deploymentmanager/steps.go
  services/preview/deploymentmanager/mgmt/2018-09-01-preview/deploymentmanager/version.go
Labels: ServicePR, review

#2807 [AutoPR compute/resource-manager] Swagger changes for adding diffdisksettings property for the Ephemeral OS Disks
  profiles/preview/compute/mgmt/compute/models.go
  services/compute/mgmt/2018-06-01/compute/models.go
  services/compute/mgmt/2018-10-01/compute/models.go
Labels: RestPRMerged, review

#2787 [AutoPR] automation/resource-manager
  services/preview/automation/mgmt/2018-06-preview/automation/runbookdraft.go
Labels: ServicePR, review

#2814 [AutoPR compute/resource-manager] Swagger change for adding status to BootDiagnosticsInstanceView
  services/compute/mgmt/2015-06-15/compute/models.go
  services/compute/mgmt/2016-03-30/compute/models.go
  services/compute/mgmt/2017-03-30/compute/models.go
  services/compute/mgmt/2017-12-01/compute/models.go
  services/compute/mgmt/2018-04-01/compute/models.go
  services/compute/mgmt/2018-06-01/compute/models.go
  services/compute/mgmt/2018-10-01/compute/models.go
  services/preview/compute/mgmt/2016-04-30-preview/compute/models.go
Labels: RestPRMerged, review

#2817 [AutoPR resources/resource-manager] Fix ARMViolations for Microsoft.Resources
  profiles/2017-03-09/resources/mgmt/links/models.go
  profiles/2017-03-09/resources/mgmt/subscriptions/models.go
  profiles/latest/resources/mgmt/links/models.go
  profiles/latest/resources/mgmt/subscriptions/models.go
  profiles/preview/resources/mgmt/links/models.go
  profiles/preview/resources/mgmt/resources/models.go
  profiles/preview/resources/mgmt/subscriptions/models.go
  services/resources/mgmt/2016-06-01/subscriptions/models.go
  services/resources/mgmt/2016-06-01/subscriptions/operations.go
  services/resources/mgmt/2016-09-01/links/models.go
  services/resources/mgmt/2016-09-01/links/operations.go
  services/resources/mgmt/2018-05-01/resources/models.go
  services/resources/mgmt/2018-05-01/resources/operations.go
Labels: RestPRMerged, review

#2820 [AutoPR compute/resource-manager] Set location for the final state option of the POST long running disk…
  services/compute/mgmt/2017-03-30/compute/virtualmachines.go
  services/compute/mgmt/2017-12-01/compute/virtualmachines.go
  services/compute/mgmt/2018-04-01/compute/virtualmachines.go
  services/compute/mgmt/2018-06-01/compute/virtualmachines.go
  services/compute/mgmt/2018-10-01/compute/virtualmachines.go
Labels: RestPRMerged, review

#2827 [AutoPR compute/resource-manager] Fix typo in Compute ImageDiskReference::id description
  services/compute/mgmt/2017-03-30/compute/models.go
  services/compute/mgmt/2018-04-01/compute/models.go
  services/compute/mgmt/2018-06-01/compute/models.go
  services/compute/mgmt/2018-10-01/compute/models.go
  services/preview/compute/mgmt/2016-04-30-preview/compute/models.go
Labels: RestPRMerged, review

#2821 [AutoPR web/resource-manager] Updated the AppService Swagger to include ElasticPremium and ElasticIsolated Skus, and a new MaximumElasticWorkerCount parameter.
  profiles/preview/web/mgmt/web/models.go
  services/web/mgmt/2018-02-01/web/models.go
Labels: RestPRMerged, review

#2816 [AutoPR frontdoor/resource-manager] Update regex for Front Door name
  services/preview/frontdoor/mgmt/2018-08-01-preview/frontdoor/backendpools.go
  services/preview/frontdoor/mgmt/2018-08-01-preview/frontdoor/endpoints.go
  services/preview/frontdoor/mgmt/2018-08-01-preview/frontdoor/frontdoors.go
  services/preview/frontdoor/mgmt/2018-08-01-preview/frontdoor/frontendendpoints.go
  services/preview/frontdoor/mgmt/2018-08-01-preview/frontdoor/healthprobesettings.go
  services/preview/frontdoor/mgmt/2018-08-01-preview/frontdoor/loadbalancingsettings.go
  services/preview/frontdoor/mgmt/2018-08-01-preview/frontdoor/routingrules.go
Labels: RestPRMerged, review

#2826 [AutoPR] servicebus/resource-manager
  services/servicebus/mgmt/2017-04-01/servicebus/models.go
Labels: ServicePR, review

#2829 [AutoPR] frontdoor/resource-manager
  services/preview/frontdoor/mgmt/2018-08-01-preview/frontdoor/backendpools.go
  services/preview/frontdoor/mgmt/2018-08-01-preview/frontdoor/endpoints.go
  services/preview/frontdoor/mgmt/2018-08-01-preview/frontdoor/frontdoors.go
  services/preview/frontdoor/mgmt/2018-08-01-preview/frontdoor/frontendendpoints.go
  services/preview/frontdoor/mgmt/2018-08-01-preview/frontdoor/healthprobesettings.go
  services/preview/frontdoor/mgmt/2018-08-01-preview/frontdoor/loadbalancingsettings.go
  services/preview/frontdoor/mgmt/2018-08-01-preview/frontdoor/routingrules.go
Labels: ServicePR, review

#2805 [AutoPR authorization/resource-manager] Add swagger spec for "Microsoft.Authorization/denyAssignments"
  profiles/preview/preview/authorization/mgmt/authorization/models.go
  services/preview/authorization/mgmt/2018-09-01-preview/authorization/classicadministrators.go
  services/preview/authorization/mgmt/2018-09-01-preview/authorization/client.go
  services/preview/authorization/mgmt/2018-09-01-preview/authorization/denyassignments.go
  services/preview/authorization/mgmt/2018-09-01-preview/authorization/models.go
  services/preview/authorization/mgmt/2018-09-01-preview/authorization/permissions.go
  services/preview/authorization/mgmt/2018-09-01-preview/authorization/provideroperationsmetadata.go
  services/preview/authorization/mgmt/2018-09-01-preview/authorization/roleassignments.go
  services/preview/authorization/mgmt/2018-09-01-preview/authorization/roledefinitions.go
Labels: RestPRMerged, review

#2833 [AutoPR] authorization/resource-manager
  profiles/preview/preview/authorization/mgmt/authorization/models.go
  services/preview/authorization/mgmt/2018-09-01-preview/authorization/classicadministrators.go
  services/preview/authorization/mgmt/2018-09-01-preview/authorization/client.go
  services/preview/authorization/mgmt/2018-09-01-preview/authorization/denyassignments.go
  services/preview/authorization/mgmt/2018-09-01-preview/authorization/models.go
  services/preview/authorization/mgmt/2018-09-01-preview/authorization/permissions.go
  services/preview/authorization/mgmt/2018-09-01-preview/authorization/provideroperationsmetadata.go
  services/preview/authorization/mgmt/2018-09-01-preview/authorization/roleassignments.go
  services/preview/authorization/mgmt/2018-09-01-preview/authorization/roledefinitions.go
Labels: ServicePR, review

#2830 [AutoPR web/resource-manager] Add Microsoft.Web georegions filter parameter LinuxDynamicWorkersEnabled
  services/web/mgmt/2018-02-01/web/client.go
Labels: RestPRMerged, review

#2792 [AutoPR mediaservices/resource-manager] Adding version 2018-07-01 for Microsoft.Media
  profiles/preview/mediaservices/mgmt/media/models.go
  profiles/preview/preview/mediaservices/mgmt/media/models.go
  services/mediaservices/mgmt/2018-07-01/media/accountfilters.go
  services/mediaservices/mgmt/2018-07-01/media/assetfilters.go
  services/mediaservices/mgmt/2018-07-01/media/assets.go
  services/mediaservices/mgmt/2018-07-01/media/client.go
  services/mediaservices/mgmt/2018-07-01/media/contentkeypolicies.go
  services/mediaservices/mgmt/2018-07-01/media/jobs.go
  services/mediaservices/mgmt/2018-07-01/media/liveevents.go
  services/mediaservices/mgmt/2018-07-01/media/liveoutputs.go
  services/mediaservices/mgmt/2018-07-01/media/locations.go
  services/mediaservices/mgmt/2018-07-01/media/mediaservices.go
  services/mediaservices/mgmt/2018-07-01/media/models.go
  services/mediaservices/mgmt/2018-07-01/media/operations.go
  services/mediaservices/mgmt/2018-07-01/media/streamingendpoints.go
  services/mediaservices/mgmt/2018-07-01/media/streaminglocators.go
  services/mediaservices/mgmt/2018-07-01/media/streamingpolicies.go
  services/mediaservices/mgmt/2018-07-01/media/transforms.go
  services/mediaservices/mgmt/2018-07-01/media/version.go
  services/preview/mediaservices/mgmt/2018-07-01/media/accountfilters.go
  services/preview/mediaservices/mgmt/2018-07-01/media/assetfilters.go
  services/preview/mediaservices/mgmt/2018-07-01/media/assets.go
  services/preview/mediaservices/mgmt/2018-07-01/media/client.go
  services/preview/mediaservices/mgmt/2018-07-01/media/contentkeypolicies.go
  services/preview/mediaservices/mgmt/2018-07-01/media/jobs.go
  services/preview/mediaservices/mgmt/2018-07-01/media/liveevents.go
  services/preview/mediaservices/mgmt/2018-07-01/media/liveoutputs.go
  services/preview/mediaservices/mgmt/2018-07-01/media/locations.go
  services/preview/mediaservices/mgmt/2018-07-01/media/mediaservices.go
  services/preview/mediaservices/mgmt/2018-07-01/media/models.go
  services/preview/mediaservices/mgmt/2018-07-01/media/operations.go
  services/preview/mediaservices/mgmt/2018-07-01/media/streamingendpoints.go
  services/preview/mediaservices/mgmt/2018-07-01/media/streaminglocators.go
  services/preview/mediaservices/mgmt/2018-07-01/media/streamingpolicies.go
  services/preview/mediaservices/mgmt/2018-07-01/media/transforms.go
  services/preview/mediaservices/mgmt/2018-07-01/media/version.go
Labels: RestPRMerged, review

#2784 [AutoPR policyinsights/resource-manager] Microsoft.PolicyInsights/remediations API
  profiles/preview/policyinsights/mgmt/policyinsights/models.go
  services/policyinsights/mgmt/2018-07-01-preview/policyinsights/client.go
  services/policyinsights/mgmt/2018-07-01-preview/policyinsights/models.go
  services/policyinsights/mgmt/2018-07-01-preview/policyinsights/operations.go
  services/policyinsights/mgmt/2018-07-01-preview/policyinsights/policyevents.go
  services/policyinsights/mgmt/2018-07-01-preview/policyinsights/policystates.go
  services/policyinsights/mgmt/2018-07-01-preview/policyinsights/policytrackedresources.go
  services/policyinsights/mgmt/2018-07-01-preview/policyinsights/remediations.go
  services/policyinsights/mgmt/2018-07-01-preview/policyinsights/version.go
Labels: RestPRMerged, review

#2844 [AutoPR storage/resource-manager] Add storage package-2018-07 to Go SDK
  profiles/preview/storage/mgmt/storage/models.go
  services/storage/mgmt/2018-07-01/storage/accounts.go
  services/storage/mgmt/2018-07-01/storage/blobcontainers.go
  services/storage/mgmt/2018-07-01/storage/client.go
  services/storage/mgmt/2018-07-01/storage/managementpolicies.go
  services/storage/mgmt/2018-07-01/storage/models.go
  services/storage/mgmt/2018-07-01/storage/operations.go
  services/storage/mgmt/2018-07-01/storage/skus.go
  services/storage/mgmt/2018-07-01/storage/usages.go
  services/storage/mgmt/2018-07-01/storage/version.go
Labels: RestPRMerged, review

#2846 [AutoPR] storage/resource-manager
  profiles/preview/storage/mgmt/storage/models.go
  services/storage/mgmt/2018-07-01/storage/accounts.go
  services/storage/mgmt/2018-07-01/storage/blobcontainers.go
  services/storage/mgmt/2018-07-01/storage/client.go
  services/storage/mgmt/2018-07-01/storage/managementpolicies.go
  services/storage/mgmt/2018-07-01/storage/models.go
  services/storage/mgmt/2018-07-01/storage/operations.go
  services/storage/mgmt/2018-07-01/storage/skus.go
  services/storage/mgmt/2018-07-01/storage/usages.go
  services/storage/mgmt/2018-07-01/storage/version.go
Labels: ServicePR, review

#2847 [AutoPR mediaservices/resource-manager] Adding version 2018-07-01 for Microsoft.Media
  profiles/preview/mediaservices/mgmt/media/models.go
  services/mediaservices/mgmt/2018-07-01/media/accountfilters.go
  services/mediaservices/mgmt/2018-07-01/media/assetfilters.go
  services/mediaservices/mgmt/2018-07-01/media/assets.go
  services/mediaservices/mgmt/2018-07-01/media/client.go
  services/mediaservices/mgmt/2018-07-01/media/contentkeypolicies.go
  services/mediaservices/mgmt/2018-07-01/media/jobs.go
  services/mediaservices/mgmt/2018-07-01/media/liveevents.go
  services/mediaservices/mgmt/2018-07-01/media/liveoutputs.go
  services/mediaservices/mgmt/2018-07-01/media/locations.go
  services/mediaservices/mgmt/2018-07-01/media/mediaservices.go
  services/mediaservices/mgmt/2018-07-01/media/models.go
  services/mediaservices/mgmt/2018-07-01/media/operations.go
  services/mediaservices/mgmt/2018-07-01/media/streamingendpoints.go
  services/mediaservices/mgmt/2018-07-01/media/streaminglocators.go
  services/mediaservices/mgmt/2018-07-01/media/streamingpolicies.go
  services/mediaservices/mgmt/2018-07-01/media/transforms.go
  services/mediaservices/mgmt/2018-07-01/media/version.go
Labels: RestPRMerged

#2848 [AutoPR] mediaservices/resource-manager
  profiles/preview/mediaservices/mgmt/media/models.go
  services/mediaservices/mgmt/2018-07-01/media/accountfilters.go
  services/mediaservices/mgmt/2018-07-01/media/assetfilters.go
  services/mediaservices/mgmt/2018-07-01/media/assets.go
  services/mediaservices/mgmt/2018-07-01/media/client.go
  services/mediaservices/mgmt/2018-07-01/media/contentkeypolicies.go
  services/mediaservices/mgmt/2018-07-01/media/jobs.go
  services/mediaservices/mgmt/2018-07-01/media/liveevents.go
  services/mediaservices/mgmt/2018-07-01/media/liveoutputs.go
  services/mediaservices/mgmt/2018-07-01/media/locations.go
  services/mediaservices/mgmt/2018-07-01/media/mediaservices.go
  services/mediaservices/mgmt/2018-07-01/media/models.go
  services/mediaservices/mgmt/2018-07-01/media/operations.go
  services/mediaservices/mgmt/2018-07-01/media/streamingendpoints.go
  services/mediaservices/mgmt/2018-07-01/media/streaminglocators.go
  services/mediaservices/mgmt/2018-07-01/media/streamingpolicies.go
  services/mediaservices/mgmt/2018-07-01/media/transforms.go
  services/mediaservices/mgmt/2018-07-01/media/version.go
Labels: ServicePR, review

#2849 [AutoPR datafactory/resource-manager] [Datafactory] Adding script actions support for HDI on demand linked service
  profiles/preview/datafactory/mgmt/datafactory/models.go
  services/datafactory/mgmt/2018-06-01/datafactory/models.go
Labels: RestPRMerged, review

#2856 [AutoPR compute/resource-manager] Add AutomaticOSUpgradeProperties in GET VMImageVersion API
  profiles/preview/compute/mgmt/compute/models.go
  services/compute/mgmt/2018-10-01/compute/models.go
Labels: RestPRMerged, review

#2831 [AutoPR hdinsight/resource-manager] [HDInsight] Added additional parameters for security profile
  services/preview/hdinsight/mgmt/2015-03-01-preview/hdinsight/models.go
  services/preview/hdinsight/mgmt/2018-06-01-preview/hdinsight/models.go
Labels: RestPRMerged, review

#2845 [AutoPR policyinsights/resource-manager] Refactor policyinsights for Go SDK
  profiles/preview/preview/policyinsights/mgmt/policyinsights/models.go
  services/preview/policyinsights/mgmt/2018-07-01-preview/policyinsights/client.go
  services/preview/policyinsights/mgmt/2018-07-01-preview/policyinsights/models.go
  services/preview/policyinsights/mgmt/2018-07-01-preview/policyinsights/operations.go
  services/preview/policyinsights/mgmt/2018-07-01-preview/policyinsights/policyevents.go
  services/preview/policyinsights/mgmt/2018-07-01-preview/policyinsights/policystates.go
  services/preview/policyinsights/mgmt/2018-07-01-preview/policyinsights/policytrackedresources.go
  services/preview/policyinsights/mgmt/2018-07-01-preview/policyinsights/remediations.go
  services/preview/policyinsights/mgmt/2018-07-01-preview/policyinsights/version.go
Labels: RestPRMerged, review

#2860 [AutoPR] hdinsight/resource-manager
  services/preview/hdinsight/mgmt/2015-03-01-preview/hdinsight/models.go
  services/preview/hdinsight/mgmt/2018-06-01-preview/hdinsight/models.go
Labels: ServicePR, review

#2861 [AutoPR] policyinsights/resource-manager
  profiles/preview/preview/policyinsights/mgmt/policyinsights/models.go
  services/preview/policyinsights/mgmt/2018-07-01-preview/policyinsights/client.go
  services/preview/policyinsights/mgmt/2018-07-01-preview/policyinsights/models.go
  services/preview/policyinsights/mgmt/2018-07-01-preview/policyinsights/operations.go
  services/preview/policyinsights/mgmt/2018-07-01-preview/policyinsights/policyevents.go
  services/preview/policyinsights/mgmt/2018-07-01-preview/policyinsights/policystates.go
  services/preview/policyinsights/mgmt/2018-07-01-preview/policyinsights/policytrackedresources.go
  services/preview/policyinsights/mgmt/2018-07-01-preview/policyinsights/remediations.go
  services/preview/policyinsights/mgmt/2018-07-01-preview/policyinsights/version.go
Labels: ServicePR, review

#2862 [AutoPR] operationalinsights/resource-manager
  profiles/latest/operationalinsights/mgmt/operationalinsights/models.go
  services/operationalinsights/mgmt/2015-03-20/operationalinsights/models.go
  services/operationalinsights/mgmt/2015-03-20/operationalinsights/savedsearches.go
  services/operationalinsights/mgmt/2015-03-20/operationalinsights/storageinsights.go
  services/operationalinsights/mgmt/2015-03-20/operationalinsights/workspaces.go
Labels: ServicePR, review

#2839 [AutoPR recoveryservicesbackup/resource-manager] Protection intent changes and bug fixes
  profiles/latest/recoveryservices/mgmt/backup/models.go
  profiles/preview/recoveryservices/mgmt/backup/models.go
  services/recoveryservices/mgmt/2016-12-01/backup/models.go
  services/recoveryservices/mgmt/2016-12-01/backup/protectablecontainers.go
  services/recoveryservices/mgmt/2016-12-01/backup/protecteditems.go
  services/recoveryservices/mgmt/2016-12-01/backup/protectioncontainers.go
  services/recoveryservices/mgmt/2017-07-01/backup/models.go
  services/recoveryservices/mgmt/2017-07-01/backup/protectablecontainers.go
  services/recoveryservices/mgmt/2017-07-01/backup/protecteditemsgroup.go
  services/recoveryservices/mgmt/2017-07-01/backup/protectioncontainers.go
  services/recoveryservices/mgmt/2017-07-01/backup/protectionintent.go
  services/recoveryservices/mgmt/2017-07-01/backup/protectionintentgroup.go
Labels: RestPRMerged, review
