Repository Azure/azure-sdk-for-go, pull requests merged in 2018-10, with the labels that each got.

#2853 [AutoPR containerregistry/resource-manager] Add ContextPath and source location URL for encode task and run type, support for pull request based triggers
  profiles/preview/containerregistry/mgmt/containerregistry/models.go
  services/containerregistry/mgmt/2018-09-01/containerregistry/models.go
Labels: RestPRMerged, review

#2872 [AutoPR mysql/resource-manager] Add mysql replica APIs into spec
  profiles/latest/mysql/mgmt/mysql/models.go
  profiles/preview/mysql/mgmt/mysql/models.go
  services/mysql/mgmt/2017-12-01/mysql/models.go
  services/mysql/mgmt/2017-12-01/mysql/replicas.go
Labels: RestPRMerged

#2871 [AutoPR] containerregistry/resource-manager
  profiles/preview/containerregistry/mgmt/containerregistry/models.go
  services/containerregistry/mgmt/2018-09-01/containerregistry/models.go
Labels: ServicePR, review

#2873 [AutoPR] mysql/resource-manager
  profiles/latest/mysql/mgmt/mysql/models.go
  profiles/preview/mysql/mgmt/mysql/models.go
  services/mysql/mgmt/2017-12-01/mysql/models.go
  services/mysql/mgmt/2017-12-01/mysql/replicas.go
Labels: ServicePR, review

#2876 [AutoPR deploymentmanager/resource-manager] DeploymentManager: Fix property name and enhance descriptions
  services/preview/deploymentmanager/mgmt/2018-09-01-preview/deploymentmanager/models.go
  services/preview/deploymentmanager/mgmt/2018-09-01-preview/deploymentmanager/rollouts.go
  services/preview/deploymentmanager/mgmt/2018-09-01-preview/deploymentmanager/services.go
  services/preview/deploymentmanager/mgmt/2018-09-01-preview/deploymentmanager/steps.go
Labels: RestPRMerged, review

#2878 [AutoPR] deploymentmanager/resource-manager
  services/preview/deploymentmanager/mgmt/2018-09-01-preview/deploymentmanager/models.go
  services/preview/deploymentmanager/mgmt/2018-09-01-preview/deploymentmanager/rollouts.go
  services/preview/deploymentmanager/mgmt/2018-09-01-preview/deploymentmanager/services.go
  services/preview/deploymentmanager/mgmt/2018-09-01-preview/deploymentmanager/steps.go
Labels: ServicePR, review

#2882 [AutoPR operationalinsights/resource-manager/applicationinsights/resource-manager] [Application Insights/OperationalInsights] Add key filter for purge parameters
  services/appinsights/mgmt/2015-05-01/insights/models.go
  services/operationalinsights/mgmt/2015-03-20/operationalinsights/models.go
Labels: RestPRMerged, review

#2875 [AutoPR keyvault/resource-manager] Add keyvault/resource-manager/readme.typescript.md
  services/appinsights/mgmt/2015-05-01/insights/models.go
  services/operationalinsights/mgmt/2015-03-20/operationalinsights/models.go
Labels: RestPRMerged, review

#2773 [AutoPR security/resource-manager] Add Information Protection APIs
  profiles/preview/preview/security/mgmt/security/models.go
  services/preview/security/mgmt/2017-08-01-preview/security/informationprotectionpolicies.go
  services/preview/security/mgmt/2017-08-01-preview/security/models.go
Labels: RestPRMerged, review

#2887 [AutoPR] security/resource-manager
  profiles/preview/preview/security/mgmt/security/models.go
  services/preview/security/mgmt/2017-08-01-preview/security/informationprotectionpolicies.go
  services/preview/security/mgmt/2017-08-01-preview/security/models.go
Labels: ServicePR, review

#2888 deprecate scheduler packages in favor of logic
  services/scheduler/mgmt/2014-08-01-preview/scheduler/client.go
  services/scheduler/mgmt/2014-08-01-preview/scheduler/jobcollections.go
  services/scheduler/mgmt/2014-08-01-preview/scheduler/jobs.go
  services/scheduler/mgmt/2014-08-01-preview/scheduler/models.go
  services/scheduler/mgmt/2014-08-01-preview/scheduler/version.go
  services/scheduler/mgmt/2016-01-01/scheduler/client.go
  services/scheduler/mgmt/2016-01-01/scheduler/jobcollections.go
  services/scheduler/mgmt/2016-01-01/scheduler/jobs.go
  services/scheduler/mgmt/2016-01-01/scheduler/models.go
  services/scheduler/mgmt/2016-01-01/scheduler/version.go
  services/scheduler/mgmt/2016-03-01/scheduler/client.go
  services/scheduler/mgmt/2016-03-01/scheduler/jobcollections.go
  services/scheduler/mgmt/2016-03-01/scheduler/jobs.go
  services/scheduler/mgmt/2016-03-01/scheduler/models.go
  services/scheduler/mgmt/2016-03-01/scheduler/version.go
Labels: review

#2743 [AutoPR blueprint/resource-manager] add swagger for new Azure Blueprint ResourceProvider
  profiles/preview/blueprint/mgmt/blueprint/models.go
  services/blueprint/mgmt/2017-11-11-preview/blueprint/artifacts.go
  services/blueprint/mgmt/2017-11-11-preview/blueprint/assignments.go
  services/blueprint/mgmt/2017-11-11-preview/blueprint/blueprints.go
  services/blueprint/mgmt/2017-11-11-preview/blueprint/client.go
  services/blueprint/mgmt/2017-11-11-preview/blueprint/models.go
  services/blueprint/mgmt/2017-11-11-preview/blueprint/operations.go
  services/blueprint/mgmt/2017-11-11-preview/blueprint/publishedartifacts.go
  services/blueprint/mgmt/2017-11-11-preview/blueprint/publishedblueprints.go
  services/blueprint/mgmt/2017-11-11-preview/blueprint/version.go
Labels: RestPRMerged, review

#2890 [AutoPR] cosmos-db/resource-manager
  services/cosmos-db/mgmt/2015-04-08/documentdb/models.go
Labels: ServicePR, review

#2895 [AutoPR blueprint/resource-manager] Fix Go SDK config for blueprint
  profiles/preview/preview/blueprint/mgmt/blueprint/models.go
  services/preview/blueprint/mgmt/2017-11-11-preview/blueprint/artifacts.go
  services/preview/blueprint/mgmt/2017-11-11-preview/blueprint/assignments.go
  services/preview/blueprint/mgmt/2017-11-11-preview/blueprint/blueprints.go
  services/preview/blueprint/mgmt/2017-11-11-preview/blueprint/client.go
  services/preview/blueprint/mgmt/2017-11-11-preview/blueprint/models.go
  services/preview/blueprint/mgmt/2017-11-11-preview/blueprint/operations.go
  services/preview/blueprint/mgmt/2017-11-11-preview/blueprint/publishedartifacts.go
  services/preview/blueprint/mgmt/2017-11-11-preview/blueprint/publishedblueprints.go
  services/preview/blueprint/mgmt/2017-11-11-preview/blueprint/version.go
Labels: RestPRMerged, review

#2894 [AutoPR] containerinstance/resource-manager
  profiles/preview/containerinstance/mgmt/containerinstance/models.go
  services/containerinstance/mgmt/2018-10-01/containerinstance/client.go
  services/containerinstance/mgmt/2018-10-01/containerinstance/container.go
  services/containerinstance/mgmt/2018-10-01/containerinstance/containergroups.go
  services/containerinstance/mgmt/2018-10-01/containerinstance/containergroupusage.go
  services/containerinstance/mgmt/2018-10-01/containerinstance/models.go
  services/containerinstance/mgmt/2018-10-01/containerinstance/operations.go
  services/containerinstance/mgmt/2018-10-01/containerinstance/serviceassociationlink.go
  services/containerinstance/mgmt/2018-10-01/containerinstance/version.go
Labels: ServicePR, review

#2883 [AutoPR cost-management/resource-manager] Fixing examples and adding missed properties
  profiles/preview/costmanagement/mgmt/costmanagement/models.go
  services/costmanagement/mgmt/2018-05-31/costmanagement/models.go
  services/costmanagement/mgmt/2018-05-31/costmanagement/operations.go
Labels: RestPRMerged, review

#2896 [AutoPR] blueprint/resource-manager
  profiles/preview/preview/blueprint/mgmt/blueprint/models.go
  services/preview/blueprint/mgmt/2017-11-11-preview/blueprint/artifacts.go
  services/preview/blueprint/mgmt/2017-11-11-preview/blueprint/assignments.go
  services/preview/blueprint/mgmt/2017-11-11-preview/blueprint/blueprints.go
  services/preview/blueprint/mgmt/2017-11-11-preview/blueprint/client.go
  services/preview/blueprint/mgmt/2017-11-11-preview/blueprint/models.go
  services/preview/blueprint/mgmt/2017-11-11-preview/blueprint/operations.go
  services/preview/blueprint/mgmt/2017-11-11-preview/blueprint/publishedartifacts.go
  services/preview/blueprint/mgmt/2017-11-11-preview/blueprint/publishedblueprints.go
  services/preview/blueprint/mgmt/2017-11-11-preview/blueprint/version.go
Labels: ServicePR, review

#2897 [AutoPR] cost-management/resource-manager
  profiles/preview/costmanagement/mgmt/costmanagement/models.go
  services/costmanagement/mgmt/2018-05-31/costmanagement/models.go
  services/costmanagement/mgmt/2018-05-31/costmanagement/operations.go
Labels: ServicePR, review

#2886 [AutoPR sql/resource-manager] Adding VA support for manged instance - Update readme.md
  profiles/preview/preview/sql/mgmt/sql/models.go
  services/preview/sql/mgmt/2017-10-01-preview/sql/manageddatabasevulnerabilityassessmentrulebaselines.go
  services/preview/sql/mgmt/2017-10-01-preview/sql/manageddatabasevulnerabilityassessments.go
  services/preview/sql/mgmt/2017-10-01-preview/sql/manageddatabasevulnerabilityassessmentscans.go
  services/preview/sql/mgmt/2017-10-01-preview/sql/models.go
Labels: RestPRMerged, review

#2912 Clarify feature request template
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/service_package_request.md
Labels: review

#2914 [AutoPR apimanagement/resource-manager] api management tags and subscriptions changes
  services/apimanagement/mgmt/2017-03-01/apimanagement/service.go
  services/preview/apimanagement/mgmt/2018-06-01-preview/apimanagement/api.go
  services/preview/apimanagement/mgmt/2018-06-01-preview/apimanagement/models.go
  services/preview/apimanagement/mgmt/2018-06-01-preview/apimanagement/operation.go
  services/preview/apimanagement/mgmt/2018-06-01-preview/apimanagement/product.go
  services/preview/apimanagement/mgmt/2018-06-01-preview/apimanagement/subscription.go
  services/preview/apimanagement/mgmt/2018-06-01-preview/apimanagement/tag.go
Labels: RestPRMerged, review

#2908 remove deprecated management packages
  profiles/preview/resources/mgmt/management/models.go
  services/resources/mgmt/2017-08-31-preview/management/client.go
  services/resources/mgmt/2017-08-31-preview/management/managementgroups.go
  services/resources/mgmt/2017-08-31-preview/management/models.go
  services/resources/mgmt/2017-08-31-preview/management/operations.go
  services/resources/mgmt/2017-08-31-preview/management/version.go
  services/resources/mgmt/2017-11-01-preview/management/client.go
  services/resources/mgmt/2017-11-01-preview/management/managementgroups.go
  services/resources/mgmt/2017-11-01-preview/management/models.go
  services/resources/mgmt/2017-11-01-preview/management/operations.go
  services/resources/mgmt/2017-11-01-preview/management/subscriptions.go
  services/resources/mgmt/2017-11-01-preview/management/version.go
  services/resources/mgmt/2018-01-01-preview/management/client.go
  services/resources/mgmt/2018-01-01-preview/management/entities.go
  services/resources/mgmt/2018-01-01-preview/management/managementgroups.go
  services/resources/mgmt/2018-01-01-preview/management/models.go
  services/resources/mgmt/2018-01-01-preview/management/operations.go
  services/resources/mgmt/2018-01-01-preview/management/subscriptions.go
  services/resources/mgmt/2018-01-01-preview/management/version.go
Labels: review

#2913 [AutoPR] sql/resource-manager
  profiles/preview/preview/sql/mgmt/sql/models.go
  services/preview/sql/mgmt/2017-10-01-preview/sql/manageddatabasevulnerabilityassessmentrulebaselines.go
  services/preview/sql/mgmt/2017-10-01-preview/sql/manageddatabasevulnerabilityassessments.go
  services/preview/sql/mgmt/2017-10-01-preview/sql/manageddatabasevulnerabilityassessmentscans.go
  services/preview/sql/mgmt/2017-10-01-preview/sql/models.go
Labels: ServicePR, review

#2915 [AutoPR] apimanagement/resource-manager
  services/apimanagement/mgmt/2017-03-01/apimanagement/service.go
  services/preview/apimanagement/mgmt/2018-06-01-preview/apimanagement/api.go
  services/preview/apimanagement/mgmt/2018-06-01-preview/apimanagement/models.go
  services/preview/apimanagement/mgmt/2018-06-01-preview/apimanagement/operation.go
  services/preview/apimanagement/mgmt/2018-06-01-preview/apimanagement/product.go
  services/preview/apimanagement/mgmt/2018-06-01-preview/apimanagement/subscription.go
  services/preview/apimanagement/mgmt/2018-06-01-preview/apimanagement/tag.go
Labels: ServicePR, review

#2884 [AutoPR domainservices/resource-manager] DomainServices: Add missing properties, add examples, and fix linting errors
  profiles/latest/domainservices/mgmt/aad/models.go
  profiles/preview/domainservices/mgmt/aad/models.go
  services/domainservices/mgmt/2017-01-01/aad/domainserviceoperations.go
  services/domainservices/mgmt/2017-01-01/aad/domainservices.go
  services/domainservices/mgmt/2017-01-01/aad/models.go
  services/domainservices/mgmt/2017-06-01/aad/domainserviceoperations.go
  services/domainservices/mgmt/2017-06-01/aad/domainservices.go
  services/domainservices/mgmt/2017-06-01/aad/models.go
Labels: RestPRMerged, review

#2917 [AutoPR] domainservices/resource-manager
  profiles/latest/domainservices/mgmt/aad/models.go
  profiles/preview/domainservices/mgmt/aad/models.go
  services/domainservices/mgmt/2017-01-01/aad/domainserviceoperations.go
  services/domainservices/mgmt/2017-01-01/aad/domainservices.go
  services/domainservices/mgmt/2017-01-01/aad/models.go
  services/domainservices/mgmt/2017-06-01/aad/domainserviceoperations.go
  services/domainservices/mgmt/2017-06-01/aad/domainservices.go
  services/domainservices/mgmt/2017-06-01/aad/models.go
Labels: ServicePR, review

#2924 update dependencies
  Gopkg.lock
  Gopkg.toml
Labels: review

#2923 Updated README.MD with NewAuthorizerFromCLI() details
  README.md
Labels: review

#2898 [AutoPR monitor/resource-manager] Add Multi Resource Alert changes for Metric Alert API
  profiles/preview/preview/monitor/mgmt/insights/models.go
  services/preview/monitor/mgmt/2018-03-01/insights/models.go
  services/preview/monitor/mgmt/2018-03-01/insights/scheduledqueryrules.go
  services/preview/monitor/mgmt/2018-09-01/insights/models.go
  services/preview/monitor/mgmt/2018-09-01/insights/scheduledqueryrules.go
Labels: RestPRInProgress, review

#2834 [AutoPR frontdoor/resource-manager] rename frontdoor to frontDoor in readme
  profiles/preview/preview/frontDoor/mgmt/frontDoor/models.go
  services/preview/frontDoor/mgmt/2018-08-01-preview/frontDoor/backendpools.go
  services/preview/frontDoor/mgmt/2018-08-01-preview/frontDoor/client.go
  services/preview/frontDoor/mgmt/2018-08-01-preview/frontDoor/endpoints.go
  services/preview/frontDoor/mgmt/2018-08-01-preview/frontDoor/frontdoors.go
  services/preview/frontDoor/mgmt/2018-08-01-preview/frontDoor/frontendendpoints.go
  services/preview/frontDoor/mgmt/2018-08-01-preview/frontDoor/healthprobesettings.go
  services/preview/frontDoor/mgmt/2018-08-01-preview/frontDoor/loadbalancingsettings.go
  services/preview/frontDoor/mgmt/2018-08-01-preview/frontDoor/models.go
  services/preview/frontDoor/mgmt/2018-08-01-preview/frontDoor/policies.go
  services/preview/frontDoor/mgmt/2018-08-01-preview/frontDoor/routingrules.go
  services/preview/frontDoor/mgmt/2018-08-01-preview/frontDoor/version.go
Labels: RestPRInProgress, review

#2841 [AutoPR automation/resource-manager] Fix the runbook resource schema issues
  services/preview/automation/mgmt/2018-06-preview/automation/models.go
  services/preview/automation/mgmt/2018-06-preview/automation/runbook.go
  services/preview/automation/mgmt/2018-06-preview/automation/runbookdraft.go
Labels: review

#2881 [AutoPR network/resource-manager] change appgw custom error status code enum and fix a typo of customErrorConfigurations
  profiles/preview/network/mgmt/network/models.go
  services/network/mgmt/2018-08-01/network/models.go
Labels: RestPRInProgress, review

#2925 Add pkgchk tool and integrate into CI
  .travis.yml
  swagger_to_sdk_config.json
  tools/pkgchk/cmd/root.go
  tools/pkgchk/exceptions.txt
  tools/pkgchk/main.go
Labels: review

#2942 [AutoPR graphrbac/data-plane] [GraphRBAC] Add delete owner
  profiles/latest/graphrbac/graphrbac/models.go
  profiles/preview/graphrbac/graphrbac/models.go
  services/graphrbac/1.6/graphrbac/applications.go
  services/graphrbac/1.6/graphrbac/deletedapplications.go
  services/graphrbac/1.6/graphrbac/groups.go
  services/graphrbac/1.6/graphrbac/models.go
  services/graphrbac/1.6/graphrbac/oauth2.go
  services/graphrbac/1.6/graphrbac/objects.go
  services/graphrbac/1.6/graphrbac/serviceprincipals.go
  services/graphrbac/1.6/graphrbac/signedinuser.go
Labels: RestPRMerged, review

#2929 Ensure branch is clean in CI
  .travis.yml
  Gopkg.lock
Labels: review

#2988 [AutoPR hdinsight/resource-manager] [HDInsight] Added support for MSI
  profiles/preview/preview/hdinsight/mgmt/hdinsight/models.go
  services/preview/hdinsight/mgmt/2015-03-01-preview/hdinsight/models.go
  services/preview/hdinsight/mgmt/2018-06-01-preview/hdinsight/models.go
Labels: RestPRMerged

#2989 [AutoPR] hdinsight/resource-manager
  profiles/preview/preview/hdinsight/mgmt/hdinsight/models.go
  services/preview/hdinsight/mgmt/2015-03-01-preview/hdinsight/models.go
  services/preview/hdinsight/mgmt/2018-06-01-preview/hdinsight/models.go
Labels: ServicePR, review

#2994 [AutoPR automation/resource-manager] Add automation/resource-manager/readme.typescript.md
  services/preview/automation/mgmt/2018-01-15-preview/automation/version.go
  services/preview/automation/mgmt/2018-06-30-preview/automation/models.go
  services/preview/automation/mgmt/2018-06-30-preview/automation/runbook.go
  services/preview/automation/mgmt/2018-06-30-preview/automation/runbookdraft.go
  services/preview/automation/mgmt/2018-06-30-preview/automation/version.go
Labels: review

#2987 [AutoPR containerregistry/resource-manager] Revert the previous change: remove the identity properties
  profiles/latest/containerregistry/mgmt/containerregistry/models.go
  profiles/preview/containerregistry/mgmt/containerregistry/models.go
  profiles/preview/preview/containerregistry/mgmt/containerregistry/models.go
  services/containerregistry/mgmt/2017-10-01/containerregistry/models.go
  services/containerregistry/mgmt/2017-10-01/containerregistry/registries.go
  services/containerregistry/mgmt/2018-09-01/containerregistry/models.go
  services/containerregistry/mgmt/2018-09-01/containerregistry/registries.go
  services/preview/containerregistry/mgmt/2018-02-01/containerregistry/models.go
  services/preview/containerregistry/mgmt/2018-02-01/containerregistry/registries.go
Labels: RestPRMerged, review

#2995 [AutoPR frontdoor/resource-manager] Add frontdoor/resource-manager/readme.typescript.md
  services/preview/frontdoor/mgmt/2018-08-01-preview/frontdoor/backendpools.go
  services/preview/frontdoor/mgmt/2018-08-01-preview/frontdoor/client.go
  services/preview/frontdoor/mgmt/2018-08-01-preview/frontdoor/endpoints.go
  services/preview/frontdoor/mgmt/2018-08-01-preview/frontdoor/frontdoors.go
  services/preview/frontdoor/mgmt/2018-08-01-preview/frontdoor/frontendendpoints.go
  services/preview/frontdoor/mgmt/2018-08-01-preview/frontdoor/healthprobesettings.go
  services/preview/frontdoor/mgmt/2018-08-01-preview/frontdoor/loadbalancingsettings.go
  services/preview/frontdoor/mgmt/2018-08-01-preview/frontdoor/policies.go
  services/preview/frontdoor/mgmt/2018-08-01-preview/frontdoor/routingrules.go
Labels: RestPRMerged, review

#3003 [AutoPR] containerregistry/resource-manager
  profiles/latest/containerregistry/mgmt/containerregistry/models.go
  profiles/preview/containerregistry/mgmt/containerregistry/models.go
  profiles/preview/preview/containerregistry/mgmt/containerregistry/models.go
  services/containerregistry/mgmt/2017-10-01/containerregistry/models.go
  services/containerregistry/mgmt/2017-10-01/containerregistry/registries.go
  services/containerregistry/mgmt/2018-09-01/containerregistry/models.go
  services/containerregistry/mgmt/2018-09-01/containerregistry/registries.go
  services/preview/containerregistry/mgmt/2018-02-01/containerregistry/models.go
  services/preview/containerregistry/mgmt/2018-02-01/containerregistry/registries.go
Labels: ServicePR, review

#3009 [AutoPR monitor/resource-manager] Add monitor/resource-manager/readme.typescript.md
  profiles/preview/preview/monitor/mgmt/insights/models.go
  services/preview/monitor/mgmt/2018-03-01/insights/models.go
  services/preview/monitor/mgmt/2018-03-01/insights/scheduledqueryrules.go
  services/preview/monitor/mgmt/2018-09-01/insights/models.go
  services/preview/monitor/mgmt/2018-09-01/insights/scheduledqueryrules.go
Labels: RestPRMerged, review

#3008 Update README.md to mention testing with 1.11
  README.md
Labels: review

#2819 [AutoPR containerservices/resource-manager] Container Service - Add OpenShift support
  profiles/preview/containerservice/mgmt/containerservice/models.go
  services/containerservice/mgmt/2018-09-30-preview/containerservice/client.go
  services/containerservice/mgmt/2018-09-30-preview/containerservice/containerservices.go
  services/containerservice/mgmt/2018-09-30-preview/containerservice/managedclusters.go
  services/containerservice/mgmt/2018-09-30-preview/containerservice/models.go
  services/containerservice/mgmt/2018-09-30-preview/containerservice/openshiftmanagedclusters.go
  services/containerservice/mgmt/2018-09-30-preview/containerservice/operations.go
  services/containerservice/mgmt/2018-09-30-preview/containerservice/version.go
Labels: RestPRMerged, review

#2991 [AutoPR datalake-analytics/data-plane] Adding Scope job states to job spec
  profiles/preview/preview/datalake/analytics/job/models.go
  services/preview/datalake/analytics/2017-09-01-preview/job/models.go
Labels: RestPRMerged, review

#3016 [AutoPR security/resource-manager] Add topology Rest API
  profiles/preview/preview/security/mgmt/security/models.go
  services/preview/security/mgmt/2017-08-01-preview/security/models.go
  services/preview/security/mgmt/2017-08-01-preview/security/topology.go
Labels: RestPRMerged, review

#3014 Docs: Added notes on using RequestInspector and ResponseInspector (#1…
  README.md
Labels: review

#3015 [AutoPR] datalake-analytics/data-plane
  profiles/preview/preview/datalake/analytics/job/models.go
  services/preview/datalake/analytics/2017-09-01-preview/job/models.go
Labels: ServicePR, review

#3017 [AutoPR] security/resource-manager
  profiles/preview/preview/security/mgmt/security/models.go
  services/preview/security/mgmt/2017-08-01-preview/security/models.go
  services/preview/security/mgmt/2017-08-01-preview/security/topology.go
Labels: ServicePR, review

#3006 [AutoPR apimanagement/resource-manager] add openid connect in authentication settings
  profiles/preview/preview/apimanagement/mgmt/apimanagement/models.go
  services/preview/apimanagement/mgmt/2018-01-01/apimanagement/models.go
  services/preview/apimanagement/mgmt/2018-06-01-preview/apimanagement/models.go
Labels: RestPRMerged, review

#3022 [AutoPR network/resource-manager] Remove error code from swagger
  services/network/mgmt/2018-08-01/network/expressroutegateways.go
Labels: RestPRMerged, review

#3023 [AutoPR] network/resource-manager
  services/network/mgmt/2018-08-01/network/expressroutegateways.go
Labels: ServicePR, review

#3021 [AutoPR] apimanagement/resource-manager
  profiles/preview/preview/apimanagement/mgmt/apimanagement/models.go
  services/preview/apimanagement/mgmt/2018-01-01/apimanagement/models.go
  services/preview/apimanagement/mgmt/2018-06-01-preview/apimanagement/models.go
Labels: ServicePR, review

#3027 [AutoPR consumption/resource-manager] Back out bad merge in Go config file
  profiles/preview/consumption/mgmt/consumption/models.go
  services/consumption/mgmt/2018-10-01/consumption/aggregatedcost.go
  services/consumption/mgmt/2018-10-01/consumption/balances.go
  services/consumption/mgmt/2018-10-01/consumption/budgets.go
  services/consumption/mgmt/2018-10-01/consumption/charges.go
  services/consumption/mgmt/2018-10-01/consumption/client.go
  services/consumption/mgmt/2018-10-01/consumption/forecasts.go
  services/consumption/mgmt/2018-10-01/consumption/marketplaces.go
  services/consumption/mgmt/2018-10-01/consumption/models.go
  services/consumption/mgmt/2018-10-01/consumption/operations.go
  services/consumption/mgmt/2018-10-01/consumption/pricesheet.go
  services/consumption/mgmt/2018-10-01/consumption/reservationrecommendations.go
  services/consumption/mgmt/2018-10-01/consumption/reservationsdetails.go
  services/consumption/mgmt/2018-10-01/consumption/reservationssummaries.go
  services/consumption/mgmt/2018-10-01/consumption/tags.go
  services/consumption/mgmt/2018-10-01/consumption/usagedetails.go
  services/consumption/mgmt/2018-10-01/consumption/version.go
Labels: RestPRMerged, review

#3028 [AutoPR] consumption/resource-manager
  profiles/preview/consumption/mgmt/consumption/models.go
  services/consumption/mgmt/2018-10-01/consumption/aggregatedcost.go
  services/consumption/mgmt/2018-10-01/consumption/balances.go
  services/consumption/mgmt/2018-10-01/consumption/budgets.go
  services/consumption/mgmt/2018-10-01/consumption/charges.go
  services/consumption/mgmt/2018-10-01/consumption/client.go
  services/consumption/mgmt/2018-10-01/consumption/forecasts.go
  services/consumption/mgmt/2018-10-01/consumption/marketplaces.go
  services/consumption/mgmt/2018-10-01/consumption/models.go
  services/consumption/mgmt/2018-10-01/consumption/operations.go
  services/consumption/mgmt/2018-10-01/consumption/pricesheet.go
  services/consumption/mgmt/2018-10-01/consumption/reservationrecommendations.go
  services/consumption/mgmt/2018-10-01/consumption/reservationsdetails.go
  services/consumption/mgmt/2018-10-01/consumption/reservationssummaries.go
  services/consumption/mgmt/2018-10-01/consumption/tags.go
  services/consumption/mgmt/2018-10-01/consumption/usagedetails.go
  services/consumption/mgmt/2018-10-01/consumption/version.go
Labels: ServicePR, review

#3031 [AutoPR automation/resource-manager] Swagger change for Update configuration dynamic group
  profiles/preview/preview/automation/mgmt/automation/models.go
  services/preview/automation/mgmt/2017-05-15-preview/automation/models.go
  services/preview/automation/mgmt/2018-01-15-preview/automation/models.go
  services/preview/automation/mgmt/2018-06-30-preview/automation/models.go
Labels: RestPRMerged, review

#3032 [AutoPR] automation/resource-manager
  profiles/preview/preview/automation/mgmt/automation/models.go
  services/preview/automation/mgmt/2017-05-15-preview/automation/models.go
  services/preview/automation/mgmt/2018-01-15-preview/automation/models.go
  services/preview/automation/mgmt/2018-06-30-preview/automation/models.go
Labels: ServicePR, review

#3033 update swagger->sdk generator to latest version
  swagger_to_sdk_config.json
Labels: review

#3038 [AutoPR eventgrid/data-plane] Update the MediaServices.json file in the EventGrid DataPlane SDK
  profiles/latest/eventgrid/eventgrid/models.go
  profiles/preview/eventgrid/eventgrid/models.go
  services/eventgrid/2018-01-01/eventgrid/models.go
Labels: RestPRMerged, review

#3043 [AutoPR automation/resource-manager] Updating sync type property from PartialSync to IncrementalSync.
  profiles/preview/preview/automation/mgmt/automation/models.go
  services/automation/mgmt/2015-10-31/automation/runbookdraft.go
  services/preview/automation/mgmt/2017-05-15-preview/automation/models.go
  services/preview/automation/mgmt/2017-05-15-preview/automation/runbookdraft.go
  services/preview/automation/mgmt/2018-01-15-preview/automation/dsccompilationjob.go
  services/preview/automation/mgmt/2018-01-15-preview/automation/dscnodeconfiguration.go
  services/preview/automation/mgmt/2018-01-15-preview/automation/models.go
  services/preview/automation/mgmt/2018-01-15-preview/automation/runbookdraft.go
  services/preview/automation/mgmt/2018-06-30-preview/automation/dsccompilationjob.go
  services/preview/automation/mgmt/2018-06-30-preview/automation/dscnodeconfiguration.go
  services/preview/automation/mgmt/2018-06-30-preview/automation/models.go
  services/preview/automation/mgmt/2018-06-30-preview/automation/runbook.go
  services/preview/automation/mgmt/2018-06-30-preview/automation/runbookdraft.go
Labels: RestPRMerged, review

#3044 [AutoPR] eventgrid/data-plane
  profiles/latest/eventgrid/eventgrid/models.go
  profiles/preview/eventgrid/eventgrid/models.go
  services/eventgrid/2018-01-01/eventgrid/models.go
Labels: ServicePR, review

#3045 [AutoPR] automation/resource-manager
  profiles/preview/preview/automation/mgmt/automation/models.go
  services/automation/mgmt/2015-10-31/automation/runbookdraft.go
  services/preview/automation/mgmt/2017-05-15-preview/automation/models.go
  services/preview/automation/mgmt/2017-05-15-preview/automation/runbookdraft.go
  services/preview/automation/mgmt/2018-01-15-preview/automation/dsccompilationjob.go
  services/preview/automation/mgmt/2018-01-15-preview/automation/dscnodeconfiguration.go
  services/preview/automation/mgmt/2018-01-15-preview/automation/models.go
  services/preview/automation/mgmt/2018-01-15-preview/automation/runbookdraft.go
  services/preview/automation/mgmt/2018-06-30-preview/automation/dsccompilationjob.go
  services/preview/automation/mgmt/2018-06-30-preview/automation/dscnodeconfiguration.go
  services/preview/automation/mgmt/2018-06-30-preview/automation/models.go
  services/preview/automation/mgmt/2018-06-30-preview/automation/runbook.go
  services/preview/automation/mgmt/2018-06-30-preview/automation/runbookdraft.go
Labels: ServicePR, review

#3048 [AutoPR resources/resource-manager] added descriptions for filter and expand
  services/preview/resources/mgmt/2016-09-01-preview/managedapplications/appliancedefinitions.go
  services/preview/resources/mgmt/2016-09-01-preview/managedapplications/appliances.go
  services/resources/mgmt/2015-11-01/resources/deployments.go
  services/resources/mgmt/2015-11-01/resources/groups.go
  services/resources/mgmt/2015-11-01/resources/resources.go
  services/resources/mgmt/2016-02-01/resources/deployments.go
  services/resources/mgmt/2016-02-01/resources/groups.go
  services/resources/mgmt/2016-02-01/resources/resources.go
  services/resources/mgmt/2016-07-01/resources/deployments.go
  services/resources/mgmt/2016-07-01/resources/groups.go
  services/resources/mgmt/2016-07-01/resources/resources.go
  services/resources/mgmt/2016-09-01/resources/deployments.go
  services/resources/mgmt/2016-09-01/resources/groups.go
  services/resources/mgmt/2016-09-01/resources/resources.go
  services/resources/mgmt/2017-05-10/resources/deployments.go
  services/resources/mgmt/2017-05-10/resources/groups.go
  services/resources/mgmt/2017-05-10/resources/resources.go
  services/resources/mgmt/2017-09-01/managedapplications/applicationdefinitions.go
  services/resources/mgmt/2017-09-01/managedapplications/applications.go
  services/resources/mgmt/2018-02-01/resources/deployments.go
  services/resources/mgmt/2018-02-01/resources/groups.go
  services/resources/mgmt/2018-02-01/resources/resources.go
  services/resources/mgmt/2018-05-01/resources/deployments.go
  services/resources/mgmt/2018-05-01/resources/groups.go
  services/resources/mgmt/2018-05-01/resources/resources.go
  services/resources/mgmt/2018-06-01/managedapplications/applicationdefinitions.go
  services/resources/mgmt/2018-06-01/managedapplications/applications.go
Labels: RestPRMerged

#3049 [AutoPR] resources/resource-manager
  services/preview/resources/mgmt/2016-09-01-preview/managedapplications/appliancedefinitions.go
  services/preview/resources/mgmt/2016-09-01-preview/managedapplications/appliances.go
  services/resources/mgmt/2015-11-01/resources/deployments.go
  services/resources/mgmt/2015-11-01/resources/groups.go
  services/resources/mgmt/2015-11-01/resources/resources.go
  services/resources/mgmt/2016-02-01/resources/deployments.go
  services/resources/mgmt/2016-02-01/resources/groups.go
  services/resources/mgmt/2016-02-01/resources/resources.go
  services/resources/mgmt/2016-07-01/resources/deployments.go
  services/resources/mgmt/2016-07-01/resources/groups.go
  services/resources/mgmt/2016-07-01/resources/resources.go
  services/resources/mgmt/2016-09-01/resources/deployments.go
  services/resources/mgmt/2016-09-01/resources/groups.go
  services/resources/mgmt/2016-09-01/resources/resources.go
  services/resources/mgmt/2017-05-10/resources/deployments.go
  services/resources/mgmt/2017-05-10/resources/groups.go
  services/resources/mgmt/2017-05-10/resources/resources.go
  services/resources/mgmt/2017-09-01/managedapplications/applicationdefinitions.go
  services/resources/mgmt/2017-09-01/managedapplications/applications.go
  services/resources/mgmt/2018-02-01/resources/deployments.go
  services/resources/mgmt/2018-02-01/resources/groups.go
  services/resources/mgmt/2018-02-01/resources/resources.go
  services/resources/mgmt/2018-05-01/resources/deployments.go
  services/resources/mgmt/2018-05-01/resources/groups.go
  services/resources/mgmt/2018-05-01/resources/resources.go
  services/resources/mgmt/2018-06-01/managedapplications/applicationdefinitions.go
  services/resources/mgmt/2018-06-01/managedapplications/applications.go
Labels: ServicePR, review

#3039 [AutoPR servicebus/resource-manager] Service Bus: moved VNet and IpFilter rules from 2018-preview to 2017 API version
  profiles/latest/servicebus/mgmt/servicebus/models.go
  profiles/preview/servicebus/mgmt/servicebus/models.go
  services/servicebus/mgmt/2015-08-01/servicebus/namespaces.go
  services/servicebus/mgmt/2017-04-01/servicebus/migrationconfigs.go
  services/servicebus/mgmt/2017-04-01/servicebus/models.go
  services/servicebus/mgmt/2017-04-01/servicebus/namespaces.go
Labels: RestPRMerged, review

#3052 [AutoPR] servicebus/resource-manager
  profiles/latest/servicebus/mgmt/servicebus/models.go
  profiles/preview/servicebus/mgmt/servicebus/models.go
  services/servicebus/mgmt/2015-08-01/servicebus/namespaces.go
  services/servicebus/mgmt/2017-04-01/servicebus/migrationconfigs.go
  services/servicebus/mgmt/2017-04-01/servicebus/models.go
  services/servicebus/mgmt/2017-04-01/servicebus/namespaces.go
Labels: ServicePR, review

#3041 [AutoPR cognitiveservices/data-plane/CustomVision/Prediction/cognitiveservices/data-plane/CustomVision/Training] Customvision v2.2
  profiles/preview/cognitiveservices/customvision/prediction/models.go
  profiles/preview/cognitiveservices/customvision/training/models.go
  services/cognitiveservices/v1.1/customvision/prediction/client.go
  services/cognitiveservices/v2.2/customvision/training/client.go
  services/cognitiveservices/v2.2/customvision/training/models.go
  services/cognitiveservices/v2.2/customvision/training/version.go
Labels: RestPRMerged, review

#3035 [AutoPR eventgrid/resource-manager] EventGrid: Update README files to include the current new preview api…
  services/eventgrid/mgmt/2018-01-01/eventgrid/eventsubscriptions.go
  services/eventgrid/mgmt/2018-01-01/eventgrid/topics.go
  services/preview/eventgrid/mgmt/2017-06-15-preview/eventgrid/eventsubscriptions.go
  services/preview/eventgrid/mgmt/2017-06-15-preview/eventgrid/topics.go
  services/preview/eventgrid/mgmt/2017-09-15-preview/eventgrid/eventsubscriptions.go
  services/preview/eventgrid/mgmt/2017-09-15-preview/eventgrid/topics.go
  services/preview/eventgrid/mgmt/2018-05-01-preview/eventgrid/eventsubscriptions.go
  services/preview/eventgrid/mgmt/2018-05-01-preview/eventgrid/topics.go
  services/preview/eventgrid/mgmt/2018-09-15-preview/eventgrid/domains.go
  services/preview/eventgrid/mgmt/2018-09-15-preview/eventgrid/eventsubscriptions.go
  services/preview/eventgrid/mgmt/2018-09-15-preview/eventgrid/topics.go
Labels: RestPRMerged, review

#3067 [AutoPR] eventgrid/resource-manager
  services/eventgrid/mgmt/2018-01-01/eventgrid/eventsubscriptions.go
  services/eventgrid/mgmt/2018-01-01/eventgrid/topics.go
  services/preview/eventgrid/mgmt/2017-06-15-preview/eventgrid/eventsubscriptions.go
  services/preview/eventgrid/mgmt/2017-06-15-preview/eventgrid/topics.go
  services/preview/eventgrid/mgmt/2017-09-15-preview/eventgrid/eventsubscriptions.go
  services/preview/eventgrid/mgmt/2017-09-15-preview/eventgrid/topics.go
  services/preview/eventgrid/mgmt/2018-05-01-preview/eventgrid/eventsubscriptions.go
  services/preview/eventgrid/mgmt/2018-05-01-preview/eventgrid/topics.go
  services/preview/eventgrid/mgmt/2018-09-15-preview/eventgrid/domains.go
  services/preview/eventgrid/mgmt/2018-09-15-preview/eventgrid/eventsubscriptions.go
  services/preview/eventgrid/mgmt/2018-09-15-preview/eventgrid/topics.go
Labels: ServicePR, review

#3069 [AutoPR cognitiveservices/data-plane/TextAnalytics] Add cognitiveservices\data-plane\TextAnalytics\readme.typescript.md
  profiles/preview/cognitiveservices/textanalytics/models.go
  services/cognitiveservices/v2.1/textanalytics/client.go
  services/cognitiveservices/v2.1/textanalytics/models.go
  services/cognitiveservices/v2.1/textanalytics/version.go
Labels: RestPRMerged, review

#3073 [AutoPR] cost-management/resource-manager
  profiles/preview/preview/costmanagement/mgmt/costmanagement/models.go
  services/preview/costmanagement/mgmt/2018-08-01-preview/costmanagement/alerts.go
  services/preview/costmanagement/mgmt/2018-08-01-preview/costmanagement/models.go
Labels: ServicePR, review

#3082 [AutoPR iotcentral/resource-manager] [Do not merge] IoTCentral - Add ARM endpoint, update model responses/inputs to align with expected values
  profiles/preview/iotcentral/mgmt/iotcentral/models.go
  services/iotcentral/mgmt/2018-09-01/iotcentral/apps.go
  services/iotcentral/mgmt/2018-09-01/iotcentral/models.go
Labels: RestPRMerged

#3081 [AutoPR containerservices/resource-manager] Support two apiversion for container service
  services/preview/containerservice/mgmt/2018-08-01-preview/containerservice/client.go
  services/preview/containerservice/mgmt/2018-08-01-preview/containerservice/containerservices.go
  services/preview/containerservice/mgmt/2018-08-01-preview/containerservice/managedclusters.go
  services/preview/containerservice/mgmt/2018-08-01-preview/containerservice/models.go
  services/preview/containerservice/mgmt/2018-08-01-preview/containerservice/openshiftmanagedclusters.go
  services/preview/containerservice/mgmt/2018-08-01-preview/containerservice/operations.go
  services/preview/containerservice/mgmt/2018-08-01-preview/containerservice/version.go
Labels: RestPRMerged, review

#3086 remove golint as it fails to build on older versions of Go
  .travis.yml
Labels: review

#3088 [AutoPR containerservices/resource-manager] Support two apiversion for container service
  services/preview/containerservice/mgmt/2018-08-01-preview/containerservice/client.go
  services/preview/containerservice/mgmt/2018-08-01-preview/containerservice/containerservices.go
  services/preview/containerservice/mgmt/2018-08-01-preview/containerservice/managedclusters.go
  services/preview/containerservice/mgmt/2018-08-01-preview/containerservice/models.go
  services/preview/containerservice/mgmt/2018-08-01-preview/containerservice/openshiftmanagedclusters.go
  services/preview/containerservice/mgmt/2018-08-01-preview/containerservice/operations.go
  services/preview/containerservice/mgmt/2018-08-01-preview/containerservice/version.go
Labels: RestPRMerged, review

#3040 [AutoPR eventhub/resource-manager] EventHub: moved VNet, IpFilter rules and Kafka from 2018-preview to 2017 API Version
  profiles/latest/eventhub/mgmt/eventhub/models.go
  profiles/preview/eventhub/mgmt/eventhub/models.go
  services/eventhub/mgmt/2015-08-01/eventhub/namespaces.go
  services/eventhub/mgmt/2017-04-01/eventhub/models.go
  services/eventhub/mgmt/2017-04-01/eventhub/namespaces.go
  services/preview/eventhub/mgmt/2018-01-01-preview/eventhub/clusters.go
  services/preview/eventhub/mgmt/2018-01-01-preview/eventhub/namespaces.go
Labels: RestPRMerged, review

#3085 [AutoPR resources/resource-manager] added to description of allowed characters for resource group name
  services/resources/mgmt/2018-05-01/resources/groups.go
Labels: RestPRMerged, review

#3059 [AutoPR eventgrid/data-plane] Added missing discriminator property to MediaJobOutput
  profiles/latest/eventgrid/eventgrid/models.go
  profiles/preview/eventgrid/eventgrid/models.go
  services/eventgrid/2018-01-01/eventgrid/models.go
Labels: RestPRMerged, review

#3087 remove golint as it fails to build on older versions of Go
  .travis.yml
Labels: review

#3095 [AutoPR] resources/resource-manager
  services/resources/mgmt/2018-05-01/resources/groups.go
Labels: ServicePR, review

#3096 [AutoPR] eventgrid/data-plane
  profiles/latest/eventgrid/eventgrid/models.go
  profiles/preview/eventgrid/eventgrid/models.go
  services/eventgrid/2018-01-01/eventgrid/models.go
Labels: ServicePR, review

#3071 [AutoPR servicefabricmesh/resource-manager] Swagger specification and examples for Service Fabric Mesh 2018-09-01-preview release.
  profiles/preview/preview/servicefabricmesh/mgmt/servicefabricmesh/models.go
  services/preview/servicefabricmesh/mgmt/2018-09-01-preview/servicefabricmesh/application.go
  services/preview/servicefabricmesh/mgmt/2018-09-01-preview/servicefabricmesh/client.go
  services/preview/servicefabricmesh/mgmt/2018-09-01-preview/servicefabricmesh/codepackage.go
  services/preview/servicefabricmesh/mgmt/2018-09-01-preview/servicefabricmesh/gateway.go
  services/preview/servicefabricmesh/mgmt/2018-09-01-preview/servicefabricmesh/models.go
  services/preview/servicefabricmesh/mgmt/2018-09-01-preview/servicefabricmesh/network.go
  services/preview/servicefabricmesh/mgmt/2018-09-01-preview/servicefabricmesh/operations.go
  services/preview/servicefabricmesh/mgmt/2018-09-01-preview/servicefabricmesh/secret.go
  services/preview/servicefabricmesh/mgmt/2018-09-01-preview/servicefabricmesh/secretvalue.go
  services/preview/servicefabricmesh/mgmt/2018-09-01-preview/servicefabricmesh/service.go
  services/preview/servicefabricmesh/mgmt/2018-09-01-preview/servicefabricmesh/servicereplica.go
  services/preview/servicefabricmesh/mgmt/2018-09-01-preview/servicefabricmesh/version.go
  services/preview/servicefabricmesh/mgmt/2018-09-01-preview/servicefabricmesh/volume.go
Labels: RestPRMerged, review

#3065 [AutoPR monitor/resource-manager] add armRoleReceiver to ActionGroup API and update API version to 2018-09-01
  profiles/preview/preview/monitor/mgmt/insights/models.go
  services/preview/monitor/mgmt/2017-05-01-preview/insights/actiongroups.go
  services/preview/monitor/mgmt/2017-05-01-preview/insights/models.go
  services/preview/monitor/mgmt/2018-03-01/insights/actiongroups.go
  services/preview/monitor/mgmt/2018-03-01/insights/models.go
  services/preview/monitor/mgmt/2018-09-01/insights/actiongroups.go
  services/preview/monitor/mgmt/2018-09-01/insights/models.go
Labels: RestPRMerged, review

#3054 [AutoPR servicebus/resource-manager] ServiceBus : Added namespace Migrate API reported in ARMs Fundamental dashboard
  profiles/latest/servicebus/mgmt/servicebus/models.go
  profiles/preview/servicebus/mgmt/servicebus/models.go
  services/servicebus/mgmt/2017-04-01/servicebus/models.go
  services/servicebus/mgmt/2017-04-01/servicebus/namespaces.go
Labels: RestPRMerged, review

#3098 [AutoPR automation/resource-manager] Reverting change: Replacing PartialSync for IncrementalSync for sync type and updating examples.
  profiles/preview/preview/automation/mgmt/automation/models.go
  services/preview/automation/mgmt/2017-05-15-preview/automation/models.go
  services/preview/automation/mgmt/2018-01-15-preview/automation/models.go
  services/preview/automation/mgmt/2018-06-30-preview/automation/models.go
Labels: RestPRMerged, review

#3102 [AutoPR] servicefabricmesh/resource-manager
  profiles/preview/preview/servicefabricmesh/mgmt/servicefabricmesh/models.go
  services/preview/servicefabricmesh/mgmt/2018-09-01-preview/servicefabricmesh/application.go
  services/preview/servicefabricmesh/mgmt/2018-09-01-preview/servicefabricmesh/client.go
  services/preview/servicefabricmesh/mgmt/2018-09-01-preview/servicefabricmesh/codepackage.go
  services/preview/servicefabricmesh/mgmt/2018-09-01-preview/servicefabricmesh/gateway.go
  services/preview/servicefabricmesh/mgmt/2018-09-01-preview/servicefabricmesh/models.go
  services/preview/servicefabricmesh/mgmt/2018-09-01-preview/servicefabricmesh/network.go
  services/preview/servicefabricmesh/mgmt/2018-09-01-preview/servicefabricmesh/operations.go
  services/preview/servicefabricmesh/mgmt/2018-09-01-preview/servicefabricmesh/secret.go
  services/preview/servicefabricmesh/mgmt/2018-09-01-preview/servicefabricmesh/secretvalue.go
  services/preview/servicefabricmesh/mgmt/2018-09-01-preview/servicefabricmesh/service.go
  services/preview/servicefabricmesh/mgmt/2018-09-01-preview/servicefabricmesh/servicereplica.go
  services/preview/servicefabricmesh/mgmt/2018-09-01-preview/servicefabricmesh/version.go
  services/preview/servicefabricmesh/mgmt/2018-09-01-preview/servicefabricmesh/volume.go
Labels: ServicePR, review

#3112 [AutoPR] servicebus/resource-manager
  profiles/latest/servicebus/mgmt/servicebus/models.go
  profiles/preview/servicebus/mgmt/servicebus/models.go
  services/servicebus/mgmt/2017-04-01/servicebus/models.go
  services/servicebus/mgmt/2017-04-01/servicebus/namespaces.go
Labels: ServicePR, review

#3113 [AutoPR] automation/resource-manager
  profiles/preview/preview/automation/mgmt/automation/models.go
  services/preview/automation/mgmt/2017-05-15-preview/automation/models.go
  services/preview/automation/mgmt/2018-01-15-preview/automation/models.go
  services/preview/automation/mgmt/2018-06-30-preview/automation/models.go
Labels: ServicePR, review

#3091 [AutoPR automation/resource-manager] Swagger change for pre and post script
  profiles/preview/preview/automation/mgmt/automation/models.go
  services/preview/automation/mgmt/2017-05-15-preview/automation/models.go
  services/preview/automation/mgmt/2018-01-15-preview/automation/models.go
  services/preview/automation/mgmt/2018-06-30-preview/automation/models.go
Labels: RestPRMerged, review

#3046 [AutoPR apimanagement/resource-manager] enableHttpCorrelationHeaders property is added to the Diagnostic entity
  services/apimanagement/mgmt/2016-07-07/apimanagement/services.go
  services/apimanagement/mgmt/2016-07-07/apimanagement/tenantconfiguration.go
  services/apimanagement/mgmt/2016-10-10/apimanagement/services.go
  services/apimanagement/mgmt/2016-10-10/apimanagement/tenantconfiguration.go
  services/apimanagement/mgmt/2017-03-01/apimanagement/service.go
  services/apimanagement/mgmt/2017-03-01/apimanagement/tenantconfiguration.go
  services/preview/apimanagement/mgmt/2018-01-01/apimanagement/service.go
  services/preview/apimanagement/mgmt/2018-01-01/apimanagement/tenantconfiguration.go
  services/preview/apimanagement/mgmt/2018-06-01-preview/apimanagement/models.go
  services/preview/apimanagement/mgmt/2018-06-01-preview/apimanagement/service.go
  services/preview/apimanagement/mgmt/2018-06-01-preview/apimanagement/tenantconfiguration.go
Labels: RestPRMerged, review

#3115 [AutoPR] automation/resource-manager
  profiles/preview/preview/automation/mgmt/automation/models.go
  services/preview/automation/mgmt/2017-05-15-preview/automation/models.go
  services/preview/automation/mgmt/2018-01-15-preview/automation/models.go
  services/preview/automation/mgmt/2018-06-30-preview/automation/models.go
Labels: ServicePR, review

#3116 [AutoPR] apimanagement/resource-manager
  services/apimanagement/mgmt/2016-07-07/apimanagement/services.go
  services/apimanagement/mgmt/2016-07-07/apimanagement/tenantconfiguration.go
  services/apimanagement/mgmt/2016-10-10/apimanagement/services.go
  services/apimanagement/mgmt/2016-10-10/apimanagement/tenantconfiguration.go
  services/apimanagement/mgmt/2017-03-01/apimanagement/service.go
  services/apimanagement/mgmt/2017-03-01/apimanagement/tenantconfiguration.go
  services/preview/apimanagement/mgmt/2018-01-01/apimanagement/service.go
  services/preview/apimanagement/mgmt/2018-01-01/apimanagement/tenantconfiguration.go
  services/preview/apimanagement/mgmt/2018-06-01-preview/apimanagement/models.go
  services/preview/apimanagement/mgmt/2018-06-01-preview/apimanagement/service.go
  services/preview/apimanagement/mgmt/2018-06-01-preview/apimanagement/tenantconfiguration.go
Labels: ServicePR, review

#3119 [AutoPR sql/resource-manager] Fixed spelling mistake in SQL documentation
  services/preview/sql/mgmt/2015-05-01-preview/sql/backuplongtermretentionpolicies.go
  services/preview/sql/mgmt/2015-05-01-preview/sql/backuplongtermretentionvaults.go
  services/preview/sql/mgmt/2015-05-01-preview/sql/databases.go
  services/preview/sql/mgmt/2015-05-01-preview/sql/elasticpools.go
  services/preview/sql/mgmt/2015-05-01-preview/sql/encryptionprotectors.go
  services/preview/sql/mgmt/2015-05-01-preview/sql/failovergroups.go
  services/preview/sql/mgmt/2015-05-01-preview/sql/managedinstances.go
  services/preview/sql/mgmt/2015-05-01-preview/sql/replicationlinks.go
  services/preview/sql/mgmt/2015-05-01-preview/sql/serverazureadadministrators.go
  services/preview/sql/mgmt/2015-05-01-preview/sql/servercommunicationlinks.go
  services/preview/sql/mgmt/2015-05-01-preview/sql/serverkeys.go
  services/preview/sql/mgmt/2015-05-01-preview/sql/servers.go
  services/preview/sql/mgmt/2015-05-01-preview/sql/syncagents.go
  services/preview/sql/mgmt/2015-05-01-preview/sql/syncgroups.go
  services/preview/sql/mgmt/2015-05-01-preview/sql/syncmembers.go
  services/preview/sql/mgmt/2015-05-01-preview/sql/virtualnetworkrules.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/backuplongtermretentionpolicies.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/backuplongtermretentionvaults.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/databases.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/elasticpools.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/encryptionprotectors.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/extendedserverblobauditingpolicies.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/failovergroups.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/jobagents.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/jobexecutions.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/manageddatabases.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/managedinstances.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/replicationlinks.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/restorepoints.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/serverazureadadministrators.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/serverblobauditingpolicies.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/servercommunicationlinks.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/serverdnsaliases.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/serverkeys.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/servers.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/serversecurityalertpolicies.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/syncagents.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/syncgroups.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/syncmembers.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/virtualnetworkrules.go
  services/preview/sql/mgmt/2017-10-01-preview/sql/backupshorttermretentionpolicies.go
  services/preview/sql/mgmt/2017-10-01-preview/sql/databases.go
  services/preview/sql/mgmt/2017-10-01-preview/sql/databasevulnerabilityassessmentscans.go
  services/preview/sql/mgmt/2017-10-01-preview/sql/elasticpools.go
  services/preview/sql/mgmt/2017-10-01-preview/sql/instancefailovergroups.go
  services/preview/sql/mgmt/2017-10-01-preview/sql/manageddatabasevulnerabilityassessmentscans.go
  services/preview/sql/mgmt/2017-10-01-preview/sql/managedinstanceencryptionprotectors.go
  services/preview/sql/mgmt/2017-10-01-preview/sql/managedinstancekeys.go
  services/preview/sql/mgmt/2017-10-01-preview/sql/managedinstancetdecertificates.go
  services/preview/sql/mgmt/2017-10-01-preview/sql/tdecertificates.go
  services/sql/mgmt/2014-04-01/sql/databases.go
  services/sql/mgmt/2014-04-01/sql/elasticpools.go
  services/sql/mgmt/2014-04-01/sql/replicationlinks.go
Labels: RestPRMerged, review

#3097 [AutoPR datamigration/resource-manager] Updates to Schema migration, project files resource and MongoDb scenario.
  services/preview/datamigration/mgmt/2017-11-15-preview/datamigration/services.go
  services/preview/datamigration/mgmt/2018-03-31-preview/datamigration/services.go
Labels: RestPRMerged, review

#3133 [AutoPR consumption/resource-manager] Introducing Marketplaces at Management Group Level
  services/consumption/mgmt/2018-10-01/consumption/marketplaces.go
Labels: RestPRMerged, review

#3072 [AutoPR web/resource-manager] Fix network trace API REST format
  profiles/preview/web/mgmt/web/models.go
  services/preview/web/mgmt/2015-08-01-preview/web/hostingenvironments.go
  services/preview/web/mgmt/2015-08-01-preview/web/managedhostingenvironments.go
  services/preview/web/mgmt/2015-08-01-preview/web/serverfarms.go
  services/preview/web/mgmt/2015-08-01-preview/web/sites.go
  services/preview/web/mgmt/2015-08-01-preview/web/version.go
  services/web/mgmt/2016-09-01/web/apps.go
  services/web/mgmt/2016-09-01/web/appservicecertificateorders.go
  services/web/mgmt/2016-09-01/web/appserviceenvironments.go
  services/web/mgmt/2016-09-01/web/appserviceplans.go
  services/web/mgmt/2016-09-01/web/domains.go
  services/web/mgmt/2018-02-01/web/apps.go
  services/web/mgmt/2018-02-01/web/appservicecertificateorders.go
  services/web/mgmt/2018-02-01/web/appserviceenvironments.go
  services/web/mgmt/2018-02-01/web/appserviceplans.go
  services/web/mgmt/2018-02-01/web/domains.go
  services/web/mgmt/2018-02-01/web/models.go
Labels: RestPRMerged, review

#3143 [AutoPR mariadb/resource-manager] Add Vnet resource for Microsoft.DBforMariaDB
  profiles/preview/preview/mariadb/mgmt/mariadb/models.go
  services/preview/mariadb/mgmt/2018-06-01-preview/mariadb/configurations.go
  services/preview/mariadb/mgmt/2018-06-01-preview/mariadb/databases.go
  services/preview/mariadb/mgmt/2018-06-01-preview/mariadb/firewallrules.go
  services/preview/mariadb/mgmt/2018-06-01-preview/mariadb/models.go
  services/preview/mariadb/mgmt/2018-06-01-preview/mariadb/servers.go
  services/preview/mariadb/mgmt/2018-06-01-preview/mariadb/serversecurityalertpolicies.go
  services/preview/mariadb/mgmt/2018-06-01-preview/mariadb/virtualnetworkrules.go
Labels: RestPRMerged, review

#3129 [AutoPR eventhub/resource-manager] EventHub : Revert PR 4246 from 2017 and added Kafka enabled
  profiles/latest/eventhub/mgmt/eventhub/models.go
  profiles/preview/eventhub/mgmt/eventhub/models.go
  services/eventhub/mgmt/2017-04-01/eventhub/models.go
  services/eventhub/mgmt/2017-04-01/eventhub/namespaces.go
Labels: RestPRMerged, review

#3140 [AutoPR cost-management/resource-manager] Microsoft.CostManagement - Add supression command into readme
  profiles/preview/preview/costmanagement/mgmt/costmanagement/models.go
  services/preview/costmanagement/mgmt/2018-08-01-preview/costmanagement/models.go
  services/preview/costmanagement/mgmt/2018-08-01-preview/costmanagement/operations.go
Labels: RestPRMerged, review

#3132 [AutoPR servicebus/resource-manager] Service Bus: Revert PR 4245 from 2017
  profiles/latest/servicebus/mgmt/servicebus/models.go
  profiles/preview/servicebus/mgmt/servicebus/models.go
  services/servicebus/mgmt/2017-04-01/servicebus/models.go
  services/servicebus/mgmt/2017-04-01/servicebus/namespaces.go
Labels: RestPRMerged, review

#3161 Add documentation for built-in loggic facilities.
  README.md
Labels: review

#3162 [AutoPR graphrbac/data-plane] Fix #4346 - RequiredResourceAccess missing on GET
  profiles/latest/graphrbac/graphrbac/models.go
  profiles/preview/graphrbac/graphrbac/models.go
  services/graphrbac/1.6/graphrbac/applications.go
  services/graphrbac/1.6/graphrbac/deletedapplications.go
  services/graphrbac/1.6/graphrbac/groups.go
  services/graphrbac/1.6/graphrbac/models.go
  services/graphrbac/1.6/graphrbac/oauth2.go
  services/graphrbac/1.6/graphrbac/objects.go
  services/graphrbac/1.6/graphrbac/serviceprincipals.go
  services/graphrbac/1.6/graphrbac/signedinuser.go
Labels: RestPRMerged, review

#3131 [AutoPR network/resource-manager] Changes to add operation id for outbound rules
  profiles/preview/network/mgmt/network/models.go
  services/network/mgmt/2018-08-01/network/loadbalanceroutboundrules.go
  services/network/mgmt/2018-08-01/network/models.go
Labels: RestPRMerged, review

#3125 [AutoPR storage/resource-manager] Support for SRP BlobServiceProperties API
  profiles/preview/storage/mgmt/storage/models.go
  services/preview/storage/mgmt/2015-05-01-preview/storage/accounts.go
  services/preview/storage/mgmt/2018-03-01-preview/storage/accounts.go
  services/storage/mgmt/2015-06-15/storage/accounts.go
  services/storage/mgmt/2016-01-01/storage/accounts.go
  services/storage/mgmt/2016-05-01/storage/accounts.go
  services/storage/mgmt/2016-12-01/storage/accounts.go
  services/storage/mgmt/2017-06-01/storage/accounts.go
  services/storage/mgmt/2017-10-01/storage/accounts.go
  services/storage/mgmt/2018-02-01/storage/accounts.go
  services/storage/mgmt/2018-07-01/storage/accounts.go
  services/storage/mgmt/2018-07-01/storage/blobservices.go
  services/storage/mgmt/2018-07-01/storage/models.go
Labels: RestPRMerged, review

#3147 [AutoPR sql/resource-manager] Update BlobAuditing swaggers to support Azure Monitor audit target
  services/preview/sql/mgmt/2015-05-01-preview/sql/models.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/models.go
Labels: RestPRMerged, review

#3177 Update changelog and add tracing docs
  CONTRIBUTING.md
  README.md
Labels: review

#3185 [AutoPR hdinsight/resource-manager] [HDInsight] Fixed non-existent extra parameter (bug)
  services/preview/hdinsight/mgmt/2015-03-01-preview/hdinsight/models.go
  services/preview/hdinsight/mgmt/2018-06-01-preview/hdinsight/models.go
Labels: RestPRMerged, review

#3188 [AutoPR] alertsmanagement/resource-manager
  profiles/preview/alertsmanagement/mgmt/alertsmanagement/models.go
  services/alertsmanagement/mgmt/2018-05-05/alertsmanagement/alerts.go
  services/alertsmanagement/mgmt/2018-05-05/alertsmanagement/client.go
  services/alertsmanagement/mgmt/2018-05-05/alertsmanagement/models.go
  services/alertsmanagement/mgmt/2018-05-05/alertsmanagement/operations.go
  services/alertsmanagement/mgmt/2018-05-05/alertsmanagement/smartgroups.go
  services/alertsmanagement/mgmt/2018-05-05/alertsmanagement/version.go
Labels: ServicePR, review

#3181 [AutoPR operationalinsights/data-plane/applicationinsights/data-plane] Add example with nested segmentation, fix number types, remove extraneous `produces`
  services/operationalinsights/v1/operationalinsights/models.go
  services/preview/appinsights/v1/insights/client.go
  services/preview/appinsights/v1/insights/events.go
  services/preview/appinsights/v1/insights/metrics.go
  services/preview/appinsights/v1/insights/models.go
  services/preview/appinsights/v1/insights/query.go
  services/preview/appinsights/v1/insights/version.go
Labels: RestPRMerged, review

#3189 [AutoPR] hdinsight/resource-manager
  services/preview/hdinsight/mgmt/2015-03-01-preview/hdinsight/models.go
  services/preview/hdinsight/mgmt/2018-06-01-preview/hdinsight/models.go
Labels: ServicePR, review

#3190 add README change from master
  README.md
Labels: review

#3175 [AutoPR devtestlabs/resource-manager] Add Devtestlabs/2018-09-15
  services/devtestlabs/mgmt/2016-05-15/dtl/customimages.go
  services/devtestlabs/mgmt/2016-05-15/dtl/disks.go
  services/devtestlabs/mgmt/2016-05-15/dtl/environments.go
  services/devtestlabs/mgmt/2016-05-15/dtl/formulas.go
  services/devtestlabs/mgmt/2016-05-15/dtl/globalschedules.go
  services/devtestlabs/mgmt/2016-05-15/dtl/labs.go
  services/devtestlabs/mgmt/2016-05-15/dtl/schedules.go
  services/devtestlabs/mgmt/2016-05-15/dtl/users.go
  services/devtestlabs/mgmt/2016-05-15/dtl/virtualmachines.go
  services/devtestlabs/mgmt/2016-05-15/dtl/virtualmachineschedules.go
  services/devtestlabs/mgmt/2016-05-15/dtl/virtualnetworks.go
  services/preview/devtestlabs/mgmt/2015-05-21-preview/dtl/cost.go
  services/preview/devtestlabs/mgmt/2015-05-21-preview/dtl/costinsight.go
  services/preview/devtestlabs/mgmt/2015-05-21-preview/dtl/customimage.go
  services/preview/devtestlabs/mgmt/2015-05-21-preview/dtl/formula.go
  services/preview/devtestlabs/mgmt/2015-05-21-preview/dtl/lab.go
  services/preview/devtestlabs/mgmt/2015-05-21-preview/dtl/schedule.go
  services/preview/devtestlabs/mgmt/2015-05-21-preview/dtl/virtualmachine.go
  services/preview/devtestlabs/mgmt/2015-05-21-preview/dtl/virtualnetwork.go
Labels: RestPRMerged, review
