Repository Azure/azure-sdk-for-go, pull requests merged in 2018-03, with the labels that each got.

#1175 [AutoPR hanaonazure/resource-manager] Remove unused HANA API
  services/hanaonazure/mgmt/2017-11-03-preview/hanaonazure/models.go
  services/hanaonazure/mgmt/2017-11-03-preview/hanaonazure/version.go
Labels: RestPRMerged, review

#1178 [AutoPR datafactory/resource-manager] Add AzureDatabricks Linked Service and DatabricksNote Activity
  services/datafactory/mgmt/2017-09-01-preview/datafactory/models.go
  services/datafactory/mgmt/2017-09-01-preview/datafactory/version.go
Labels: RestPRMerged, review

#1148 [AutoPR redis/resource-manager] Swagger completeness for Redis Cache
  services/redis/mgmt/2015-08-01/redis/version.go
  services/redis/mgmt/2016-04-01/redis/version.go
  services/redis/mgmt/2017-02-01/redis/version.go
  services/redis/mgmt/2017-10-01/redis/models.go
  services/redis/mgmt/2017-10-01/redis/patchschedules.go
  services/redis/mgmt/2017-10-01/redis/redis.go
  services/redis/mgmt/2017-10-01/redis/version.go
Labels: RestPRMerged, review

#1184 [AutoPR web/resource-manager] Add missing type specifier to enum definition.
  services/web/mgmt/2016-09-01/web/models.go
Labels: RestPRMerged, review

#1188 Fixes to blob storage containers.
  CHANGELOG.md
  storage/container.go
  storage/container_test.go
  storage/recordings/ContainerSuite/TestGetContainerProperties.yaml
  version/version.go
Labels: review

#1195 [AutoPR sql/resource-manager] Sksinghspecs
  services/sql/mgmt/2017-03-01-preview/sql/restorepoints.go
Labels: RestPRMerged, review

#1196 Update travis build matrix with Go 1.10.x
  .travis.yml
Labels: review

#1203 Updating version number in latest branch
  swagger_to_sdk_config.json
  version/version.go
Labels: review

#1197 [AutoPR policyinsights/resource-manager] Reorganize policyinsights; change modelAsString for x-ms-enum to true
  services/policyinsights/mgmt/2017-08-09-preview/policyinsights/client.go
  services/policyinsights/mgmt/2017-08-09-preview/policyinsights/models.go
  services/policyinsights/mgmt/2017-08-09-preview/policyinsights/operations.go
  services/policyinsights/mgmt/2017-08-09-preview/policyinsights/policyevents.go
  services/policyinsights/mgmt/2017-08-09-preview/policyinsights/policystates.go
  services/policyinsights/mgmt/2017-08-09-preview/policyinsights/version.go
  services/policyinsights/mgmt/2017-10-17-preview/policyinsights/client.go
  services/policyinsights/mgmt/2017-10-17-preview/policyinsights/models.go
  services/policyinsights/mgmt/2017-10-17-preview/policyinsights/operations.go
  services/policyinsights/mgmt/2017-10-17-preview/policyinsights/policyevents.go
  services/policyinsights/mgmt/2017-10-17-preview/policyinsights/policystates.go
  services/policyinsights/mgmt/2017-10-17-preview/policyinsights/version.go
  services/policyinsights/mgmt/2017-12-12-preview/policyinsights/client.go
  services/policyinsights/mgmt/2017-12-12-preview/policyinsights/models.go
  services/policyinsights/mgmt/2017-12-12-preview/policyinsights/operations.go
  services/policyinsights/mgmt/2017-12-12-preview/policyinsights/policyevents.go
  services/policyinsights/mgmt/2017-12-12-preview/policyinsights/policystates.go
  services/policyinsights/mgmt/2017-12-12-preview/policyinsights/version.go
Labels: RestPRMerged, review

#1189 [AutoPR authorization/resource-manager] update roledefinition filters to be in sync with the filters present in service
  services/authorization/mgmt/2015-07-01/authorization/version.go
  services/authorization/mgmt/2017-10-01-preview/authorization/classicadministrators.go
  services/authorization/mgmt/2017-10-01-preview/authorization/version.go
  services/authorization/mgmt/2018-01-01-preview/authorization/classicadministratorsgroup.go
  services/authorization/mgmt/2018-01-01-preview/authorization/models.go
  services/authorization/mgmt/2018-01-01-preview/authorization/permissionsgroup.go
  services/authorization/mgmt/2018-01-01-preview/authorization/provideroperationsmetadatagroup.go
  services/authorization/mgmt/2018-01-01-preview/authorization/roleassignmentsgroup.go
  services/authorization/mgmt/2018-01-01-preview/authorization/roledefinitionsgroup.go
  services/authorization/mgmt/2018-01-01-preview/authorization/version.go
Labels: RestPRMerged, review

#1214 Update autorest.go generator version.
  swagger_to_sdk_config.json
Labels: review

#1215 [AutoPR resources/resource-manager] Fix java code generation for resources
  services/resources/mgmt/2015-01-01/locks/models.go
  services/resources/mgmt/2015-10-01-preview/policy/models.go
  services/resources/mgmt/2015-11-01/resources/models.go
  services/resources/mgmt/2016-02-01/resources/models.go
  services/resources/mgmt/2016-04-01/policy/models.go
  services/resources/mgmt/2016-06-01/subscriptions/models.go
  services/resources/mgmt/2016-07-01/resources/models.go
  services/resources/mgmt/2016-09-01-preview/managedapplications/models.go
  services/resources/mgmt/2016-09-01/links/models.go
  services/resources/mgmt/2016-09-01/locks/models.go
  services/resources/mgmt/2016-09-01/resources/models.go
  services/resources/mgmt/2016-12-01/policy/models.go
  services/resources/mgmt/2017-05-10/resources/models.go
  services/resources/mgmt/2017-06-01-preview/policy/models.go
Labels: RestPRMerged

#1193 [AutoPR compute/resource-manager] Adding 2 new APIs for VMSS: Redeploy and PerformMaintenance
  services/compute/mgmt/2015-06-15/compute/models.go
  services/compute/mgmt/2016-03-30/compute/models.go
  services/compute/mgmt/2016-04-30-preview/compute/models.go
  services/compute/mgmt/2017-03-30/compute/models.go
  services/compute/mgmt/2017-12-01/compute/models.go
  services/compute/mgmt/2017-12-01/compute/virtualmachinescalesets.go
  services/compute/mgmt/2017-12-01/compute/virtualmachinescalesetvms.go
  services/containerservice/mgmt/2015-11-01-preview/containerservice/models.go
  services/containerservice/mgmt/2016-03-30/containerservice/models.go
  services/containerservice/mgmt/2016-09-30/containerservice/models.go
  services/containerservice/mgmt/2017-01-31/containerservice/models.go
Labels: RestPRMerged, review

#1211 [AutoPR dns/resource-manager] Fix SDK breaking change in 2017-10-01 DNS Swagger
  services/dns/mgmt/2015-05-04-preview/dns/models.go
  services/dns/mgmt/2016-04-01/dns/models.go
  services/dns/mgmt/2017-09-01/dns/models.go
  services/dns/mgmt/2017-10-01/dns/models.go
  services/dns/mgmt/2017-10-01/dns/zones.go
Labels: RestPRMerged, review

#1191 [AutoPR cdn/resource-manager] Change the default tag to 2017-10
  services/cdn/mgmt/2015-06-01/cdn/models.go
  services/cdn/mgmt/2015-06-01/cdn/version.go
  services/cdn/mgmt/2016-04-02/cdn/models.go
  services/cdn/mgmt/2016-04-02/cdn/version.go
  services/cdn/mgmt/2016-10-02/cdn/models.go
  services/cdn/mgmt/2016-10-02/cdn/version.go
  services/cdn/mgmt/2017-04-02/cdn/models.go
  services/cdn/mgmt/2017-04-02/cdn/version.go
  services/cdn/mgmt/2017-10-12/cdn/models.go
  services/cdn/mgmt/2017-10-12/cdn/version.go
Labels: RestPRMerged, review

#1179 Add apidiff tool.
  tools/apidiff/cmd/common.go
  tools/apidiff/cmd/package.go
  tools/apidiff/cmd/packages.go
  tools/apidiff/cmd/root.go
  tools/apidiff/delta/delta.go
  tools/apidiff/delta/delta_test.go
  tools/apidiff/delta/testdata/breaking/new/new.go
  tools/apidiff/delta/testdata/breaking/old/old.go
  tools/apidiff/delta/testdata/nonbreaking/new/new.go
  tools/apidiff/delta/testdata/nonbreaking/old/old.go
  tools/apidiff/exports/exports.go
  tools/apidiff/exports/package.go
  tools/apidiff/exports/package_test.go
  tools/apidiff/exports/testdata/td.go
  tools/apidiff/main.go
  tools/apidiff/repo/repo.go
Labels: review

#1154 [AutoPR operationalinsights/resource-manager] Adding OperationalInsights Purge, PurgeStatus operations
  services/operationalinsights/mgmt/2015-03-20/operationalinsights/client.go
  services/operationalinsights/mgmt/2015-03-20/operationalinsights/models.go
  services/operationalinsights/mgmt/2015-03-20/operationalinsights/operations.go
  services/operationalinsights/mgmt/2015-03-20/operationalinsights/savedsearches.go
  services/operationalinsights/mgmt/2015-03-20/operationalinsights/storageinsights.go
  services/operationalinsights/mgmt/2015-03-20/operationalinsights/version.go
  services/operationalinsights/mgmt/2015-03-20/operationalinsights/workspace.go
  services/operationalinsights/mgmt/2015-03-20/operationalinsights/workspaces.go
  services/operationalinsights/mgmt/2015-11-01-preview/operationalinsights/models.go
  services/operationalinsights/mgmt/2015-11-01-preview/operationalinsights/version.go
Labels: RestPRMerged, review

#1225 [AutoPR cognitiveservices/resource-manager] [Cognitive Services] Change type of limit/currentValue to double from integer
  services/cognitiveservices/mgmt/2016-02-01-preview/cognitiveservices/models.go
  services/cognitiveservices/mgmt/2016-02-01-preview/cognitiveservices/version.go
  services/cognitiveservices/mgmt/2017-04-18/cognitiveservices/accounts.go
  services/cognitiveservices/mgmt/2017-04-18/cognitiveservices/checkskuavailability.go
  services/cognitiveservices/mgmt/2017-04-18/cognitiveservices/client.go
  services/cognitiveservices/mgmt/2017-04-18/cognitiveservices/models.go
  services/cognitiveservices/mgmt/2017-04-18/cognitiveservices/operations.go
  services/cognitiveservices/mgmt/2017-04-18/cognitiveservices/version.go
Labels: RestPRMerged, review

#1223 [AutoPR billing/resource-manager] [Billing RP] Rename BillingAccount->EnrollmentAccount.
  services/billing/mgmt/2018-03-01-preview/billing/enrollmentaccounts.go
  services/billing/mgmt/2018-03-01-preview/billing/models.go
Labels: RestPRMerged, review

#1207 [AutoPR containerinstance/resource-manager] Adding Container Exec Spec
  services/containerinstance/mgmt/2017-08-01-preview/containerinstance/models.go
  services/containerinstance/mgmt/2017-10-01-preview/containerinstance/models.go
  services/containerinstance/mgmt/2017-12-01-preview/containerinstance/models.go
  services/containerinstance/mgmt/2018-02-01-preview/containerinstance/containergroups.go
  services/containerinstance/mgmt/2018-02-01-preview/containerinstance/models.go
  services/containerinstance/mgmt/2018-02-01-preview/containerinstance/startcontainer.go
Labels: RestPRMerged, review

#1244 [AutoPR cognitiveservices/resource-manager] Remove advisor Java block from CognitiveServices readme.md
  services/cognitiveservices/mgmt/2016-02-01-preview/cognitiveservices/models.go
  services/cognitiveservices/mgmt/2017-04-18/cognitiveservices/accounts.go
  services/cognitiveservices/mgmt/2017-04-18/cognitiveservices/checkskuavailability.go
  services/cognitiveservices/mgmt/2017-04-18/cognitiveservices/client.go
  services/cognitiveservices/mgmt/2017-04-18/cognitiveservices/models.go
  services/cognitiveservices/mgmt/2017-04-18/cognitiveservices/operations.go
Labels: RestPRMerged, review

#1248 [AutoPR deviceprovisioningservices/resource-manager] Group DPSCertificate->List with other operations
  services/provisioningservices/mgmt/2017-08-21-preview/iothub/models.go
  services/provisioningservices/mgmt/2017-08-21-preview/iothub/version.go
  services/provisioningservices/mgmt/2017-11-15/iothub/dpscertificate.go
  services/provisioningservices/mgmt/2017-11-15/iothub/dpscertificates.go
  services/provisioningservices/mgmt/2017-11-15/iothub/models.go
  services/provisioningservices/mgmt/2017-11-15/iothub/version.go
Labels: RestPRMerged, review

#1235 [AutoPR operationalinsights/resource-manager] [OperationalInsights] Fix generated doc structure
  services/operationalinsights/mgmt/2015-03-20/operationalinsights/models.go
  services/operationalinsights/mgmt/2015-03-20/operationalinsights/workspace.go
  services/operationalinsights/mgmt/2015-03-20/operationalinsights/workspaces.go
Labels: RestPRMerged, review

#1226 [AutoPR postgresql/resource-manager] correct tier enum for postgres
  services/postgresql/mgmt/2017-04-30-preview/postgresql/models.go
Labels: RestPRMerged, review

#1252 [AutoPR keyvault/resource-manager] Add node config to keyvault for Swagger to SDK
  services/keyvault/mgmt/2015-06-01/keyvault/models.go
  services/keyvault/mgmt/2015-06-01/keyvault/version.go
  services/keyvault/mgmt/2016-10-01/keyvault/models.go
  services/keyvault/mgmt/2016-10-01/keyvault/version.go
Labels: RestPRMerged, review

#1255 [AutoPR dns/resource-manager] Fix SDK breaking change in 2017-10-01 DNS Swagger ref https://github.…
  services/dns/mgmt/2018-03-01-preview/dns/models.go
  services/dns/mgmt/2018-03-01-preview/dns/zones.go
Labels: RestPRMerged, review

#1243 [AutoPR sql/resource-manager] Refactor sql readme.md
  services/sql/mgmt/2014-04-01/sql/models.go
  services/sql/mgmt/2015-05-01-preview/sql/models.go
  services/sql/mgmt/2017-03-01-preview/sql/datawarehouseuseractivities.go
  services/sql/mgmt/2017-03-01-preview/sql/models.go
  services/sql/mgmt/2017-10-01-preview/sql/client.go
  services/sql/mgmt/2017-10-01-preview/sql/databaseoperations.go
  services/sql/mgmt/2017-10-01-preview/sql/elasticpooloperations.go
  services/sql/mgmt/2017-10-01-preview/sql/models.go
  services/sql/mgmt/2017-10-01-preview/sql/version.go
  services/sql/mgmt/2017-103-01-preview/sql/client.go
  services/sql/mgmt/2017-103-01-preview/sql/databaseoperations.go
  services/sql/mgmt/2017-103-01-preview/sql/elasticpooloperations.go
  services/sql/mgmt/2017-103-01-preview/sql/models.go
  services/sql/mgmt/2017-103-01-preview/sql/version.go
Labels: RestPRMerged, review

#1238 [AutoPR applicationinsights/resource-manager] Improve Microsoft.Insights schema generation
  services/appinsights/mgmt/2015-05-01/insights/annotations.go
  services/appinsights/mgmt/2015-05-01/insights/apikeys.go
  services/appinsights/mgmt/2015-05-01/insights/componentavailablefeatures.go
  services/appinsights/mgmt/2015-05-01/insights/componentcurrentbillingfeatures.go
  services/appinsights/mgmt/2015-05-01/insights/componentfeaturecapabilities.go
  services/appinsights/mgmt/2015-05-01/insights/componentquotastatus.go
  services/appinsights/mgmt/2015-05-01/insights/components.go
  services/appinsights/mgmt/2015-05-01/insights/exportconfigurations.go
  services/appinsights/mgmt/2015-05-01/insights/favorite.go
  services/appinsights/mgmt/2015-05-01/insights/favorites.go
  services/appinsights/mgmt/2015-05-01/insights/models.go
  services/appinsights/mgmt/2015-05-01/insights/operations.go
  services/appinsights/mgmt/2015-05-01/insights/proactivedetectionconfigurations.go
  services/appinsights/mgmt/2015-05-01/insights/webtestlocations.go
  services/appinsights/mgmt/2015-05-01/insights/webtests.go
  services/appinsights/mgmt/2015-05-01/insights/workitemconfigurations.go
Labels: RestPRMerged, review

#1266 [AutoPR managementpartner/resource-manager] Add partner name for managmentparnter action response
  services/managementpartner/mgmt/2018-02-01/managementpartner/models.go
Labels: RestPRMerged, review

#1242 [AutoPR eventhub/resource-manager] [DO NOT MERGE UNTIL SERVICE TEAM DECIDES] Adding preview version of Event Hubs Cluster to Azure REST API specs.
  services/eventhub/mgmt/2015-08-01/eventhub/models.go
  services/eventhub/mgmt/2017-04-01/eventhub/models.go
Labels: RestPRMerged, review

#1271 [AutoPR containerservices/resource-manager] [AKS] update list of supported VM sizes
  services/containerservice/mgmt/2017-07-01/containerservice/containerservices.go
  services/containerservice/mgmt/2017-07-01/containerservice/models.go
  services/containerservice/mgmt/2017-08-31/containerservice/containerservicesgroup.go
  services/containerservice/mgmt/2017-08-31/containerservice/managedclustersgroup.go
  services/containerservice/mgmt/2017-08-31/containerservice/models.go
  services/containerservice/mgmt/2017-09-30/containerservice/containerservices.go
  services/containerservice/mgmt/2017-09-30/containerservice/managedclusters.go
  services/containerservice/mgmt/2017-09-30/containerservice/models.go
Labels: RestPRMerged, review

#1279 [AutoPR datafactory/resource-manager] Add package-version for ADF
  services/datafactory/mgmt/2017-09-01-preview/datafactory/models.go
Labels: RestPRMerged, review

#1273 [AutoPR] containerinstance/resource-manager
  services/containerinstance/mgmt/2018-02-01-preview/containerinstance/models.go
Labels: ServicePR, review

#1308 [AutoPR redis/resource-manager] New api version for redis 2018-03-01
  services/redis/mgmt/2018-03-01/redis/client.go
  services/redis/mgmt/2018-03-01/redis/firewallrules.go
  services/redis/mgmt/2018-03-01/redis/linkedserver.go
  services/redis/mgmt/2018-03-01/redis/models.go
  services/redis/mgmt/2018-03-01/redis/operations.go
  services/redis/mgmt/2018-03-01/redis/patchschedules.go
  services/redis/mgmt/2018-03-01/redis/redis.go
  services/redis/mgmt/2018-03-01/redis/version.go
Labels: RestPRMerged, review

#1320 [AutoPR postgresql/resource-manager/mysql/resource-manager] [Do Not Merge. Merge on 3/18]Add GA version of APIs for MySQL and PGSQL
  services/postgresql/mgmt/2017-12-01/postgresql/checknameavailability.go
  services/postgresql/mgmt/2017-12-01/postgresql/client.go
  services/postgresql/mgmt/2017-12-01/postgresql/configurations.go
  services/postgresql/mgmt/2017-12-01/postgresql/databases.go
  services/postgresql/mgmt/2017-12-01/postgresql/firewallrules.go
  services/postgresql/mgmt/2017-12-01/postgresql/locationbasedperformancetier.go
  services/postgresql/mgmt/2017-12-01/postgresql/logfiles.go
  services/postgresql/mgmt/2017-12-01/postgresql/models.go
  services/postgresql/mgmt/2017-12-01/postgresql/operations.go
  services/postgresql/mgmt/2017-12-01/postgresql/servers.go
  services/postgresql/mgmt/2017-12-01/postgresql/version.go
Labels: RestPRMerged, review

#1316 [AutoPR consumption/resource-manager] Added reservation recommendations and tags
  services/consumption/mgmt/2018-03-31/consumption/models.go
  services/consumption/mgmt/2018-03-31/consumption/reservationrecommendations.go
  services/consumption/mgmt/2018-03-31/consumption/usagedetails.go
Labels: RestPRMerged, review

#1312 [AutoPR] redis/resource-manager
  services/redis/mgmt/2018-03-01/redis/client.go
  services/redis/mgmt/2018-03-01/redis/firewallrules.go
  services/redis/mgmt/2018-03-01/redis/linkedserver.go
  services/redis/mgmt/2018-03-01/redis/models.go
  services/redis/mgmt/2018-03-01/redis/operations.go
  services/redis/mgmt/2018-03-01/redis/patchschedules.go
  services/redis/mgmt/2018-03-01/redis/redis.go
  services/redis/mgmt/2018-03-01/redis/version.go
Labels: ServicePR, review

#1328 [AutoPR] consumption/resource-manager
  services/consumption/mgmt/2018-03-31/consumption/models.go
  services/consumption/mgmt/2018-03-31/consumption/reservationrecommendations.go
  services/consumption/mgmt/2018-03-31/consumption/usagedetails.go
Labels: ServicePR

#1334 [AutoPR resources/resource-manager] Move subscriptionId to global
  services/resources/mgmt/2016-06-01/subscriptions/client.go
  services/resources/mgmt/2016-06-01/subscriptions/subscriptions.go
  services/resources/mgmt/2016-06-01/subscriptions/tenants.go
Labels: RestPRMerged, review

#1342 [AutoPR cdn/resource-manager] Add example for checkNameAvailability
  services/cdn/mgmt/2015-06-01/cdn/customdomains.go
  services/cdn/mgmt/2015-06-01/cdn/endpoints.go
  services/cdn/mgmt/2015-06-01/cdn/models.go
  services/cdn/mgmt/2015-06-01/cdn/nameavailability.go
  services/cdn/mgmt/2015-06-01/cdn/origins.go
  services/cdn/mgmt/2015-06-01/cdn/profiles.go
  services/cdn/mgmt/2016-04-02/cdn/customdomains.go
  services/cdn/mgmt/2016-04-02/cdn/endpoints.go
  services/cdn/mgmt/2016-04-02/cdn/models.go
  services/cdn/mgmt/2016-04-02/cdn/nameavailability.go
  services/cdn/mgmt/2016-04-02/cdn/origins.go
  services/cdn/mgmt/2016-04-02/cdn/profiles.go
  services/cdn/mgmt/2016-10-02/cdn/client.go
  services/cdn/mgmt/2016-10-02/cdn/customdomains.go
  services/cdn/mgmt/2016-10-02/cdn/endpoints.go
  services/cdn/mgmt/2016-10-02/cdn/models.go
  services/cdn/mgmt/2016-10-02/cdn/origins.go
  services/cdn/mgmt/2016-10-02/cdn/profiles.go
  services/cdn/mgmt/2017-04-02/cdn/client.go
  services/cdn/mgmt/2017-04-02/cdn/customdomains.go
  services/cdn/mgmt/2017-04-02/cdn/endpoints.go
  services/cdn/mgmt/2017-04-02/cdn/models.go
  services/cdn/mgmt/2017-04-02/cdn/origins.go
  services/cdn/mgmt/2017-04-02/cdn/profiles.go
  services/cdn/mgmt/2017-10-12/cdn/client.go
  services/cdn/mgmt/2017-10-12/cdn/customdomains.go
  services/cdn/mgmt/2017-10-12/cdn/endpoints.go
  services/cdn/mgmt/2017-10-12/cdn/models.go
  services/cdn/mgmt/2017-10-12/cdn/origins.go
  services/cdn/mgmt/2017-10-12/cdn/profiles.go
Labels: RestPRMerged, review

#1343 [AutoPR] cdn/resource-manager
  services/cdn/mgmt/2015-06-01/cdn/customdomains.go
  services/cdn/mgmt/2015-06-01/cdn/endpoints.go
  services/cdn/mgmt/2015-06-01/cdn/models.go
  services/cdn/mgmt/2015-06-01/cdn/nameavailability.go
  services/cdn/mgmt/2015-06-01/cdn/origins.go
  services/cdn/mgmt/2015-06-01/cdn/profiles.go
  services/cdn/mgmt/2016-04-02/cdn/customdomains.go
  services/cdn/mgmt/2016-04-02/cdn/endpoints.go
  services/cdn/mgmt/2016-04-02/cdn/models.go
  services/cdn/mgmt/2016-04-02/cdn/nameavailability.go
  services/cdn/mgmt/2016-04-02/cdn/origins.go
  services/cdn/mgmt/2016-04-02/cdn/profiles.go
  services/cdn/mgmt/2016-10-02/cdn/client.go
  services/cdn/mgmt/2016-10-02/cdn/customdomains.go
  services/cdn/mgmt/2016-10-02/cdn/endpoints.go
  services/cdn/mgmt/2016-10-02/cdn/models.go
  services/cdn/mgmt/2016-10-02/cdn/origins.go
  services/cdn/mgmt/2016-10-02/cdn/profiles.go
  services/cdn/mgmt/2017-04-02/cdn/client.go
  services/cdn/mgmt/2017-04-02/cdn/customdomains.go
  services/cdn/mgmt/2017-04-02/cdn/endpoints.go
  services/cdn/mgmt/2017-04-02/cdn/models.go
  services/cdn/mgmt/2017-04-02/cdn/origins.go
  services/cdn/mgmt/2017-04-02/cdn/profiles.go
  services/cdn/mgmt/2017-10-12/cdn/client.go
  services/cdn/mgmt/2017-10-12/cdn/customdomains.go
  services/cdn/mgmt/2017-10-12/cdn/endpoints.go
  services/cdn/mgmt/2017-10-12/cdn/models.go
  services/cdn/mgmt/2017-10-12/cdn/origins.go
  services/cdn/mgmt/2017-10-12/cdn/profiles.go
Labels: ServicePR, review

#1339 [AutoPR billing/resource-manager] [Billing RP] Minor EnrollmentAccount API consistency tweaks
  services/billing/mgmt/2018-03-01-preview/billing/enrollmentaccounts.go
  services/billing/mgmt/2018-03-01-preview/billing/models.go
Labels: RestPRMerged, review

#1323 [AutoPR network/resource-manager] Adding optional traffic analytics config fields to network watcher config object for enhancing the Network Watcher cmdlets
  services/network/mgmt/2018-01-01/network/models.go
  services/network/mgmt/2018-01-01/network/watchers.go
Labels: RestPRMerged, review

#1348 [AutoPR] network/resource-manager
  services/network/mgmt/2018-01-01/network/models.go
  services/network/mgmt/2018-01-01/network/watchers.go
Labels: ServicePR, review

#1347 [AutoPR] billing/resource-manager
  services/billing/mgmt/2018-03-01-preview/billing/enrollmentaccounts.go
  services/billing/mgmt/2018-03-01-preview/billing/models.go
Labels: ServicePR, review

#1346 [AutoPR cosmos-db/resource-manager] added descriptions to include Cosmos DB ARM template values
  services/cosmos-db/mgmt/2015-04-08/documentdb/models.go
Labels: RestPRMerged

#1350 [AutoPR] cosmos-db/resource-manager
  services/cosmos-db/mgmt/2015-04-08/documentdb/models.go
Labels: ServicePR, review

#1345 [AutoPR applicationinsights/resource-manager] migrate from apis in private repo to preview (new pricing model api and migration apis)
  services/appinsights/mgmt/2015-05-01/insights/annotations.go
  services/appinsights/mgmt/2015-05-01/insights/apikeys.go
  services/appinsights/mgmt/2015-05-01/insights/client.go
  services/appinsights/mgmt/2015-05-01/insights/componentavailablefeatures.go
  services/appinsights/mgmt/2015-05-01/insights/componentcurrentbillingfeatures.go
  services/appinsights/mgmt/2015-05-01/insights/componentfeaturecapabilities.go
  services/appinsights/mgmt/2015-05-01/insights/componentquotastatus.go
  services/appinsights/mgmt/2015-05-01/insights/components.go
  services/appinsights/mgmt/2015-05-01/insights/exportconfigurations.go
  services/appinsights/mgmt/2015-05-01/insights/favorite.go
  services/appinsights/mgmt/2015-05-01/insights/favorites.go
  services/appinsights/mgmt/2015-05-01/insights/operations.go
  services/appinsights/mgmt/2015-05-01/insights/proactivedetectionconfigurations.go
  services/appinsights/mgmt/2015-05-01/insights/webtestlocations.go
  services/appinsights/mgmt/2015-05-01/insights/webtests.go
  services/appinsights/mgmt/2015-05-01/insights/workitemconfigurations.go
Labels: RestPRMerged, review

#1352 [AutoPR] applicationinsights/resource-manager
  services/appinsights/mgmt/2015-05-01/insights/annotations.go
  services/appinsights/mgmt/2015-05-01/insights/apikeys.go
  services/appinsights/mgmt/2015-05-01/insights/client.go
  services/appinsights/mgmt/2015-05-01/insights/componentavailablefeatures.go
  services/appinsights/mgmt/2015-05-01/insights/componentcurrentbillingfeatures.go
  services/appinsights/mgmt/2015-05-01/insights/componentfeaturecapabilities.go
  services/appinsights/mgmt/2015-05-01/insights/componentquotastatus.go
  services/appinsights/mgmt/2015-05-01/insights/components.go
  services/appinsights/mgmt/2015-05-01/insights/exportconfigurations.go
  services/appinsights/mgmt/2015-05-01/insights/favorite.go
  services/appinsights/mgmt/2015-05-01/insights/favorites.go
  services/appinsights/mgmt/2015-05-01/insights/operations.go
  services/appinsights/mgmt/2015-05-01/insights/proactivedetectionconfigurations.go
  services/appinsights/mgmt/2015-05-01/insights/webtestlocations.go
  services/appinsights/mgmt/2015-05-01/insights/webtests.go
  services/appinsights/mgmt/2015-05-01/insights/workitemconfigurations.go
Labels: ServicePR, review

#1355 [AutoPR sql/resource-manager] [DO NOT MERGE] Adding InstanceFailoverGroups
  services/sql/mgmt/2017-03-01-preview/sql/datawarehouseuseractivities.go
  services/sql/mgmt/2017-03-01-preview/sql/models.go
Labels: review

#1356 [AutoPR] sql/resource-manager
  services/sql/mgmt/2017-03-01-preview/sql/datawarehouseuseractivities.go
  services/sql/mgmt/2017-03-01-preview/sql/models.go
Labels: ServicePR, review

#1357 [AutoPR sql/resource-manager] Removing instanceFailoverGroup from readme
  services/sql/mgmt/2017-03-01-preview/sql/datawarehouseuseractivities.go
  services/sql/mgmt/2017-03-01-preview/sql/models.go
Labels: review

#1360 [AutoPR resources/resource-manager] Fix subscription paramter in SubscriptionClient
  services/resources/mgmt/2016-06-01/subscriptions/client.go
  services/resources/mgmt/2016-06-01/subscriptions/subscriptions.go
  services/resources/mgmt/2016-06-01/subscriptions/tenants.go
Labels: review

#1358 [AutoPR] sql/resource-manager
  services/sql/mgmt/2017-03-01-preview/sql/datawarehouseuseractivities.go
  services/sql/mgmt/2017-03-01-preview/sql/models.go
Labels: ServicePR, review

#1329 [AutoPR cognitiveservices/data-plane/CustomVision/Prediction] Add missing config options for Go
  services/cognitiveservices/v1.1/customvision/prediction/client.go
  services/cognitiveservices/v1.1/customvision/prediction/models.go
  services/cognitiveservices/v1.1/customvision/prediction/version.go
Labels: RestPRMerged

#1362 [AutoPR] cognitiveservices/data-plane/CustomVision/Prediction
  services/cognitiveservices/v1.1/customvision/prediction/client.go
  services/cognitiveservices/v1.1/customvision/prediction/models.go
  services/cognitiveservices/v1.1/customvision/prediction/version.go
Labels: ServicePR, review

#1363 [AutoPR subscription/resource-manager] Update subscription creation ARM API in Microsoft.Subscription RP
  services/subscription/mgmt/2018-03-01-preview/subscription/client.go
  services/subscription/mgmt/2018-03-01-preview/subscription/factory.go
  services/subscription/mgmt/2018-03-01-preview/subscription/models.go
  services/subscription/mgmt/2018-03-01-preview/subscription/operations.go
  services/subscription/mgmt/2018-03-01-preview/subscription/operationsgroup.go
  services/subscription/mgmt/2018-03-01-preview/subscription/version.go
Labels: review

#1365 [AutoPR compute/resource-manager] added missing Swagger
  services/compute/mgmt/2017-12-01/compute/availabilitysets.go
  services/compute/mgmt/2017-12-01/compute/containerservices.go
  services/compute/mgmt/2017-12-01/compute/disks.go
  services/compute/mgmt/2017-12-01/compute/images.go
  services/compute/mgmt/2017-12-01/compute/loganalytics.go
  services/compute/mgmt/2017-12-01/compute/models.go
  services/compute/mgmt/2017-12-01/compute/operations.go
  services/compute/mgmt/2017-12-01/compute/snapshots.go
  services/compute/mgmt/2017-12-01/compute/virtualmachineextensions.go
  services/compute/mgmt/2017-12-01/compute/virtualmachines.go
  services/compute/mgmt/2017-12-01/compute/virtualmachinescalesetextensions.go
  services/compute/mgmt/2017-12-01/compute/virtualmachinescalesets.go
  services/compute/mgmt/2017-12-01/compute/virtualmachinescalesetvms.go
Labels: review

#1366 [AutoPR] compute/resource-manager
  services/compute/mgmt/2017-12-01/compute/availabilitysets.go
  services/compute/mgmt/2017-12-01/compute/containerservices.go
  services/compute/mgmt/2017-12-01/compute/disks.go
  services/compute/mgmt/2017-12-01/compute/images.go
  services/compute/mgmt/2017-12-01/compute/loganalytics.go
  services/compute/mgmt/2017-12-01/compute/models.go
  services/compute/mgmt/2017-12-01/compute/operations.go
  services/compute/mgmt/2017-12-01/compute/snapshots.go
  services/compute/mgmt/2017-12-01/compute/virtualmachineextensions.go
  services/compute/mgmt/2017-12-01/compute/virtualmachines.go
  services/compute/mgmt/2017-12-01/compute/virtualmachinescalesetextensions.go
  services/compute/mgmt/2017-12-01/compute/virtualmachinescalesets.go
  services/compute/mgmt/2017-12-01/compute/virtualmachinescalesetvms.go
Labels: ServicePR, review

#1364 [AutoPR] subscription/resource-manager
  services/subscription/mgmt/2018-03-01-preview/subscription/client.go
  services/subscription/mgmt/2018-03-01-preview/subscription/factory.go
  services/subscription/mgmt/2018-03-01-preview/subscription/models.go
  services/subscription/mgmt/2018-03-01-preview/subscription/operations.go
  services/subscription/mgmt/2018-03-01-preview/subscription/operationsgroup.go
  services/subscription/mgmt/2018-03-01-preview/subscription/version.go
Labels: ServicePR, review

#1379 [AutoPR apimanagement/resource-manager] Fix issue with 2017-03-01 version of api-management
  services/apimanagement/mgmt/2017-03-01/apimanagement/apirevisions.go
Labels: review

#1380 [AutoPR] apimanagement/resource-manager
  services/apimanagement/mgmt/2017-03-01/apimanagement/apirevisions.go
Labels: ServicePR, review

#1382 [AutoPR resources/resource-manager] Fix some of the error in ARM swagger spec
  services/resources/mgmt/2017-05-10/resources/models.go
Labels: RestPRMerged, review

#1397 [AutoPR iotspaces/resource-manager] Onboarding IoTSpaces.
  services/preview/iotspaces/mgmt/2017-10-01-preview/iotspaces/client.go
  services/preview/iotspaces/mgmt/2017-10-01-preview/iotspaces/iotspaces.go
  services/preview/iotspaces/mgmt/2017-10-01-preview/iotspaces/models.go
  services/preview/iotspaces/mgmt/2017-10-01-preview/iotspaces/operations.go
  services/preview/iotspaces/mgmt/2017-10-01-preview/iotspaces/version.go
Labels: RestPRMerged, review

#1398 [AutoPR] iotspaces/resource-manager
  services/preview/iotspaces/mgmt/2017-10-01-preview/iotspaces/client.go
  services/preview/iotspaces/mgmt/2017-10-01-preview/iotspaces/iotspaces.go
  services/preview/iotspaces/mgmt/2017-10-01-preview/iotspaces/models.go
  services/preview/iotspaces/mgmt/2017-10-01-preview/iotspaces/operations.go
  services/preview/iotspaces/mgmt/2017-10-01-preview/iotspaces/version.go
Labels: ServicePR, review

#1396 [AutoPR subscription/resource-manager] [Subscription RP] Add AdditionalParameters property to SubscriptionCreationParameters
  services/preview/subscription/mgmt/2018-03-01-preview/subscription/models.go
Labels: RestPRMerged, review

#1390 Fixes to apidiff tool.
  tools/apidiff/cmd/common.go
  tools/apidiff/cmd/root.go
  tools/apidiff/delta/delta.go
  tools/apidiff/delta/delta_test.go
  tools/apidiff/ioext/ioext.go
Labels: review

#1391 [AutoPR servicebus/resource-manager] ServiceBus: added 'properties' to CorrelationFilter
  services/servicebus/mgmt/2017-04-01/servicebus/models.go
Labels: RestPRMerged, review

#1402 [AutoPR network/resource-manager] Merge Network-2018-02-01 to Master Networking Swagger Changes for Feb 2018
  services/network/mgmt/2018-01-01/network/models.go
  services/network/mgmt/2018-01-01/network/watchers.go
Labels: RestPRMerged, review

#1409 [AutoPR subscription/resource-manager] fix readme.md to include 2016/06/01 with 2018/03/01 always
  services/preview/subscription/mgmt/2018-03-01-preview/subscription/client.go
  services/preview/subscription/mgmt/2018-03-01-preview/subscription/factory.go
  services/preview/subscription/mgmt/2018-03-01-preview/subscription/models.go
  services/preview/subscription/mgmt/2018-03-01-preview/subscription/operations.go
  services/preview/subscription/mgmt/2018-03-01-preview/subscription/operationsgroup.go
  services/preview/subscription/mgmt/2018-03-01-preview/subscription/subscriptions.go
  services/preview/subscription/mgmt/2018-03-01-preview/subscription/tenants.go
Labels: RestPRMerged, review

#1412 [AutoPR monitor/resource-manager] [Monitoring] Add metric alerts api 2018-03-01
  services/monitor/mgmt/2018-03-01/insights/models.go
Labels: review

#1415 Revert "[AutoPR network/resource-manager] Merge Network-2018-02-01 to Master Networking Swagger Changes for Feb 2018"
  services/network/mgmt/2018-01-01/network/models.go
  services/network/mgmt/2018-01-01/network/watchers.go
Labels: review

#1408 Add breaking changes detection to travis CI.
  .travis.yml
Labels: review

#1385 [AutoPR databricks/resource-manager] Add config section for swagger->sdk for Go
  services/databricks/mgmt/2018-04-01/databricks/client.go
  services/databricks/mgmt/2018-04-01/databricks/models.go
  services/databricks/mgmt/2018-04-01/databricks/version.go
  services/databricks/mgmt/2018-04-01/databricks/workspaces.go
Labels: RestPRMerged, review

#1387 [AutoPR azurestack/resource-manager] Add config section for swagger->sdk for Go
  services/$(azurestack)/mgmt/2017-06-01/$(azurestack)/client.go
  services/$(azurestack)/mgmt/2017-06-01/$(azurestack)/customersubscriptions.go
  services/$(azurestack)/mgmt/2017-06-01/$(azurestack)/models.go
  services/$(azurestack)/mgmt/2017-06-01/$(azurestack)/operations.go
  services/$(azurestack)/mgmt/2017-06-01/$(azurestack)/products.go
  services/$(azurestack)/mgmt/2017-06-01/$(azurestack)/registrations.go
  services/$(azurestack)/mgmt/2017-06-01/$(azurestack)/version.go
Labels: RestPRMerged, review

#1389 [AutoPR apimanagement/control-plane] Add config section for swagger->sdk for Go
  services/preview/apimanagement/ctrl/2017-03-01/apimanagement/api.go
  services/preview/apimanagement/ctrl/2017-03-01/apimanagement/apiexport.go
  services/preview/apimanagement/ctrl/2017-03-01/apimanagement/apioperation.go
  services/preview/apimanagement/ctrl/2017-03-01/apimanagement/apioperationpolicy.go
  services/preview/apimanagement/ctrl/2017-03-01/apimanagement/apipolicy.go
  services/preview/apimanagement/ctrl/2017-03-01/apimanagement/apiproduct.go
  services/preview/apimanagement/ctrl/2017-03-01/apimanagement/apischema.go
  services/preview/apimanagement/ctrl/2017-03-01/apimanagement/authorizationserver.go
  services/preview/apimanagement/ctrl/2017-03-01/apimanagement/backend.go
  services/preview/apimanagement/ctrl/2017-03-01/apimanagement/certificate.go
  services/preview/apimanagement/ctrl/2017-03-01/apimanagement/client.go
  services/preview/apimanagement/ctrl/2017-03-01/apimanagement/delegationsettings.go
  services/preview/apimanagement/ctrl/2017-03-01/apimanagement/emailtemplate.go
  services/preview/apimanagement/ctrl/2017-03-01/apimanagement/group.go
  services/preview/apimanagement/ctrl/2017-03-01/apimanagement/groupuser.go
  services/preview/apimanagement/ctrl/2017-03-01/apimanagement/identityprovider.go
  services/preview/apimanagement/ctrl/2017-03-01/apimanagement/logger.go
  services/preview/apimanagement/ctrl/2017-03-01/apimanagement/models.go
  services/preview/apimanagement/ctrl/2017-03-01/apimanagement/openidconnectprovider.go
  services/preview/apimanagement/ctrl/2017-03-01/apimanagement/policy.go
  services/preview/apimanagement/ctrl/2017-03-01/apimanagement/policysnippets.go
  services/preview/apimanagement/ctrl/2017-03-01/apimanagement/product.go
  services/preview/apimanagement/ctrl/2017-03-01/apimanagement/productapi.go
  services/preview/apimanagement/ctrl/2017-03-01/apimanagement/productgroup.go
  services/preview/apimanagement/ctrl/2017-03-01/apimanagement/productpolicy.go
  services/preview/apimanagement/ctrl/2017-03-01/apimanagement/productsubscriptions.go
  services/preview/apimanagement/ctrl/2017-03-01/apimanagement/property.go
  services/preview/apimanagement/ctrl/2017-03-01/apimanagement/quotabycounterkeys.go
  services/preview/apimanagement/ctrl/2017-03-01/apimanagement/quotabyperiodkeys.go
  services/preview/apimanagement/ctrl/2017-03-01/apimanagement/regions.go
  services/preview/apimanagement/ctrl/2017-03-01/apimanagement/reports.go
  services/preview/apimanagement/ctrl/2017-03-01/apimanagement/signinsettings.go
  services/preview/apimanagement/ctrl/2017-03-01/apimanagement/signupsettings.go
  services/preview/apimanagement/ctrl/2017-03-01/apimanagement/subscription.go
  services/preview/apimanagement/ctrl/2017-03-01/apimanagement/tenantaccess.go
  services/preview/apimanagement/ctrl/2017-03-01/apimanagement/tenantaccessgit.go
  services/preview/apimanagement/ctrl/2017-03-01/apimanagement/tenantconfiguration.go
  services/preview/apimanagement/ctrl/2017-03-01/apimanagement/user.go
  services/preview/apimanagement/ctrl/2017-03-01/apimanagement/usergroup.go
  services/preview/apimanagement/ctrl/2017-03-01/apimanagement/useridentities.go
  services/preview/apimanagement/ctrl/2017-03-01/apimanagement/usersubscription.go
  services/preview/apimanagement/ctrl/2017-03-01/apimanagement/version.go
Labels: RestPRMerged, review

#1418 [AutoPR] apimanagement/control-plane
  services/preview/apimanagement/ctrl/2017-03-01/apimanagement/api.go
  services/preview/apimanagement/ctrl/2017-03-01/apimanagement/apiexport.go
  services/preview/apimanagement/ctrl/2017-03-01/apimanagement/apioperation.go
  services/preview/apimanagement/ctrl/2017-03-01/apimanagement/apioperationpolicy.go
  services/preview/apimanagement/ctrl/2017-03-01/apimanagement/apipolicy.go
  services/preview/apimanagement/ctrl/2017-03-01/apimanagement/apiproduct.go
  services/preview/apimanagement/ctrl/2017-03-01/apimanagement/apischema.go
  services/preview/apimanagement/ctrl/2017-03-01/apimanagement/authorizationserver.go
  services/preview/apimanagement/ctrl/2017-03-01/apimanagement/backend.go
  services/preview/apimanagement/ctrl/2017-03-01/apimanagement/certificate.go
  services/preview/apimanagement/ctrl/2017-03-01/apimanagement/client.go
  services/preview/apimanagement/ctrl/2017-03-01/apimanagement/delegationsettings.go
  services/preview/apimanagement/ctrl/2017-03-01/apimanagement/emailtemplate.go
  services/preview/apimanagement/ctrl/2017-03-01/apimanagement/group.go
  services/preview/apimanagement/ctrl/2017-03-01/apimanagement/groupuser.go
  services/preview/apimanagement/ctrl/2017-03-01/apimanagement/identityprovider.go
  services/preview/apimanagement/ctrl/2017-03-01/apimanagement/logger.go
  services/preview/apimanagement/ctrl/2017-03-01/apimanagement/models.go
  services/preview/apimanagement/ctrl/2017-03-01/apimanagement/openidconnectprovider.go
  services/preview/apimanagement/ctrl/2017-03-01/apimanagement/policy.go
  services/preview/apimanagement/ctrl/2017-03-01/apimanagement/policysnippets.go
  services/preview/apimanagement/ctrl/2017-03-01/apimanagement/product.go
  services/preview/apimanagement/ctrl/2017-03-01/apimanagement/productapi.go
  services/preview/apimanagement/ctrl/2017-03-01/apimanagement/productgroup.go
  services/preview/apimanagement/ctrl/2017-03-01/apimanagement/productpolicy.go
  services/preview/apimanagement/ctrl/2017-03-01/apimanagement/productsubscriptions.go
  services/preview/apimanagement/ctrl/2017-03-01/apimanagement/property.go
  services/preview/apimanagement/ctrl/2017-03-01/apimanagement/quotabycounterkeys.go
  services/preview/apimanagement/ctrl/2017-03-01/apimanagement/quotabyperiodkeys.go
  services/preview/apimanagement/ctrl/2017-03-01/apimanagement/regions.go
  services/preview/apimanagement/ctrl/2017-03-01/apimanagement/reports.go
  services/preview/apimanagement/ctrl/2017-03-01/apimanagement/signinsettings.go
  services/preview/apimanagement/ctrl/2017-03-01/apimanagement/signupsettings.go
  services/preview/apimanagement/ctrl/2017-03-01/apimanagement/subscription.go
  services/preview/apimanagement/ctrl/2017-03-01/apimanagement/tenantaccess.go
  services/preview/apimanagement/ctrl/2017-03-01/apimanagement/tenantaccessgit.go
  services/preview/apimanagement/ctrl/2017-03-01/apimanagement/tenantconfiguration.go
  services/preview/apimanagement/ctrl/2017-03-01/apimanagement/user.go
  services/preview/apimanagement/ctrl/2017-03-01/apimanagement/usergroup.go
  services/preview/apimanagement/ctrl/2017-03-01/apimanagement/useridentities.go
  services/preview/apimanagement/ctrl/2017-03-01/apimanagement/usersubscription.go
  services/preview/apimanagement/ctrl/2017-03-01/apimanagement/version.go
Labels: ServicePR, review

#1416 [AutoPR] databricks/resource-manager
  services/databricks/mgmt/2018-04-01/databricks/client.go
  services/databricks/mgmt/2018-04-01/databricks/models.go
  services/databricks/mgmt/2018-04-01/databricks/version.go
  services/databricks/mgmt/2018-04-01/databricks/workspaces.go
Labels: ServicePR, review

#1419 [AutoPR migrate/resource-manager] Add config section for swagger->sdk for Go
  services/migrate/mgmt/2018-02-02/migrate/assessedmachines.go
  services/migrate/mgmt/2018-02-02/migrate/assessments.go
  services/migrate/mgmt/2018-02-02/migrate/client.go
  services/migrate/mgmt/2018-02-02/migrate/groups.go
  services/migrate/mgmt/2018-02-02/migrate/machines.go
  services/migrate/mgmt/2018-02-02/migrate/models.go
  services/migrate/mgmt/2018-02-02/migrate/operations.go
  services/migrate/mgmt/2018-02-02/migrate/projects.go
  services/migrate/mgmt/2018-02-02/migrate/version.go
Labels: RestPRMerged, review

#1410 [AutoPR] servicebus/resource-manager
  services/servicebus/mgmt/2017-04-01/servicebus/models.go
Labels: ServicePR, review

#1421 [AutoPR] migrate/resource-manager
  services/migrate/mgmt/2018-02-02/migrate/assessedmachines.go
  services/migrate/mgmt/2018-02-02/migrate/assessments.go
  services/migrate/mgmt/2018-02-02/migrate/client.go
  services/migrate/mgmt/2018-02-02/migrate/groups.go
  services/migrate/mgmt/2018-02-02/migrate/machines.go
  services/migrate/mgmt/2018-02-02/migrate/models.go
  services/migrate/mgmt/2018-02-02/migrate/operations.go
  services/migrate/mgmt/2018-02-02/migrate/projects.go
  services/migrate/mgmt/2018-02-02/migrate/version.go
Labels: ServicePR, review

#1420 [AutoPR azurestack/resource-manager] Fix Go package path error
  services/azurestack/mgmt/2017-06-01/azurestack/client.go
  services/azurestack/mgmt/2017-06-01/azurestack/customersubscriptions.go
  services/azurestack/mgmt/2017-06-01/azurestack/models.go
  services/azurestack/mgmt/2017-06-01/azurestack/operations.go
  services/azurestack/mgmt/2017-06-01/azurestack/products.go
  services/azurestack/mgmt/2017-06-01/azurestack/registrations.go
  services/azurestack/mgmt/2017-06-01/azurestack/version.go
Labels: RestPRMerged, review

#1424 [AutoPR] azurestack/resource-manager
  services/azurestack/mgmt/2017-06-01/azurestack/client.go
  services/azurestack/mgmt/2017-06-01/azurestack/customersubscriptions.go
  services/azurestack/mgmt/2017-06-01/azurestack/models.go
  services/azurestack/mgmt/2017-06-01/azurestack/operations.go
  services/azurestack/mgmt/2017-06-01/azurestack/products.go
  services/azurestack/mgmt/2017-06-01/azurestack/registrations.go
  services/azurestack/mgmt/2017-06-01/azurestack/version.go
Labels: ServicePR, review

#1429 [AutoPR web/resource-manager] Fix for https://github.com/Azure/azure-rest-api-specs/issues/1697#iss…
  services/web/mgmt/2016-09-01/web/apps.go
  services/web/mgmt/2016-09-01/web/models.go
  services/web/mgmt/2016-09-01/web/resourcehealthmetadata.go
Labels: RestPRMerged, review

#1393 [AutoPR automation/resource-manager] Adding patch API for Configurations
  services/automation/mgmt/2015-10-31/automation/dscconfiguration.go
  services/automation/mgmt/2015-10-31/automation/models.go
  services/automation/mgmt/2017-05-15-preview/automation/dscconfiguration.go
  services/automation/mgmt/2017-05-15-preview/automation/models.go
Labels: RestPRMerged, review

#1430 [AutoPR] web/resource-manager
  services/web/mgmt/2016-09-01/web/apps.go
  services/web/mgmt/2016-09-01/web/models.go
  services/web/mgmt/2016-09-01/web/resourcehealthmetadata.go
Labels: ServicePR, review

#1413 [AutoPR] monitor/resource-manager
  services/monitor/mgmt/2018-03-01/insights/models.go
Labels: ServicePR, review

#1404 [AutoPR] subscription/resource-manager
  services/preview/subscription/mgmt/2018-03-01-preview/subscription/client.go
  services/preview/subscription/mgmt/2018-03-01-preview/subscription/factory.go
  services/preview/subscription/mgmt/2018-03-01-preview/subscription/models.go
  services/preview/subscription/mgmt/2018-03-01-preview/subscription/operations.go
  services/preview/subscription/mgmt/2018-03-01-preview/subscription/operationsgroup.go
  services/preview/subscription/mgmt/2018-03-01-preview/subscription/subscriptions.go
  services/preview/subscription/mgmt/2018-03-01-preview/subscription/tenants.go
Labels: ServicePR, review

#1153 Docs: Added notes on using RequestInspector and ResponseInspector
  README.md
Labels: docs

#1310 add root doc.go
  CHANGELOG.md
  doc.go
Labels: docs, review

#1438 [AutoPR automation/resource-manager] Adding ListKeys support for Automation Account
  services/automation/mgmt/2015-10-31/automation/keys.go
  services/automation/mgmt/2015-10-31/automation/models.go
  services/automation/mgmt/2017-05-15-preview/automation/keys.go
  services/automation/mgmt/2017-05-15-preview/automation/models.go
Labels: RestPRMerged

#1436 [AutoPR] automation/resource-manager
  services/automation/mgmt/2015-10-31/automation/keys.go
  services/automation/mgmt/2015-10-31/automation/models.go
  services/automation/mgmt/2017-05-15-preview/automation/keys.go
  services/automation/mgmt/2017-05-15-preview/automation/models.go
Labels: ServicePR, review

#1422 [AutoPR automation/resource-manager] Runbook Linting issues fixed
  services/automation/mgmt/2015-10-31/automation/models.go
  services/automation/mgmt/2015-10-31/automation/runbookdraft.go
  services/automation/mgmt/2017-05-15-preview/automation/models.go
  services/automation/mgmt/2017-05-15-preview/automation/runbookdraft.go
Labels: RestPRMerged, review

#1394 [AutoPR sql/resource-manager] SQL database, elastic pool, and capabilities 2017-10-01-preview
  services/sql/mgmt/2015-05-01-preview/sql/models.go
  services/sql/mgmt/2015-05-01-preview/sql/recommendedelasticpools.go
  services/sql/mgmt/2017-03-01-preview/sql/models.go
  services/sql/mgmt/2017-03-01-preview/sql/recommendedelasticpools.go
Labels: RestPRMerged, review

#1447 Use binary release of dep
  .travis.yml
Labels: review

#1454 [AutoPR datamigration/resource-manager] Remove TaskOutput base object.
  services/datamigration/mgmt/2017-11-15-preview/datamigration/models.go
Labels: RestPRMerged, review

#1459 [AutoPR datafactory/resource-manager] [ADF] Swagger Change for Responsys Source
  services/datafactory/mgmt/2017-09-01-preview/datafactory/models.go
Labels: RestPRMerged, review

#1448 [AutoPR compute/resource-manager] Adding PATCH for virtualMachines/{vmName}/extensions/{extName} and GET for virtualMachines/{vmName}/extensions to older Compute API versions
  services/compute/mgmt/2015-06-15/compute/models.go
  services/compute/mgmt/2015-06-15/compute/virtualmachineextensions.go
  services/compute/mgmt/2016-03-30/compute/models.go
  services/compute/mgmt/2016-03-30/compute/virtualmachineextensions.go
  services/compute/mgmt/2016-03-30/compute/virtualmachines.go
  services/compute/mgmt/2016-04-30-preview/compute/models.go
  services/compute/mgmt/2016-04-30-preview/compute/virtualmachineextensions.go
  services/compute/mgmt/2016-04-30-preview/compute/virtualmachines.go
  services/compute/mgmt/2017-03-30/compute/models.go
  services/compute/mgmt/2017-03-30/compute/virtualmachineextensions.go
  services/compute/mgmt/2017-03-30/compute/virtualmachines.go
  services/compute/mgmt/2018-04-01/compute/models.go
  services/compute/mgmt/2018-04-01/compute/virtualmachineextensions.go
  services/compute/mgmt/2018-04-01/compute/virtualmachines.go
Labels: RestPRMerged, review

#1465 [AutoPR mysql/resource-manager/postgresql/resource-manager] Add GeoRestore to MySQL and PostgreSQL
  services/mysql/mgmt/2017-12-01/mysql/models.go
  services/postgresql/mgmt/2017-12-01/postgresql/models.go
Labels: RestPRMerged, review

#1460 [AutoPR] datafactory/resource-manager
  services/datafactory/mgmt/2017-09-01-preview/datafactory/models.go
Labels: ServicePR, review

#1457 [AutoPR] datamigration/resource-manager
  services/datamigration/mgmt/2017-11-15-preview/datamigration/models.go
Labels: ServicePR, review

#1473 [AutoPR datamigration/resource-manager] Add Agent Jobs and Login migration for SQL to MI public preview scenario
  services/preview/datamigration/mgmt/2018-03-31-preview/datamigration/client.go
  services/preview/datamigration/mgmt/2018-03-31-preview/datamigration/models.go
  services/preview/datamigration/mgmt/2018-03-31-preview/datamigration/operations.go
  services/preview/datamigration/mgmt/2018-03-31-preview/datamigration/projects.go
  services/preview/datamigration/mgmt/2018-03-31-preview/datamigration/resourceskus.go
  services/preview/datamigration/mgmt/2018-03-31-preview/datamigration/services.go
  services/preview/datamigration/mgmt/2018-03-31-preview/datamigration/tasks.go
  services/preview/datamigration/mgmt/2018-03-31-preview/datamigration/usages.go
  services/preview/datamigration/mgmt/2018-03-31-preview/datamigration/version.go
Labels: RestPRMerged, review

#1474 [AutoPR] datamigration/resource-manager
  services/preview/datamigration/mgmt/2018-03-31-preview/datamigration/client.go
  services/preview/datamigration/mgmt/2018-03-31-preview/datamigration/models.go
  services/preview/datamigration/mgmt/2018-03-31-preview/datamigration/operations.go
  services/preview/datamigration/mgmt/2018-03-31-preview/datamigration/projects.go
  services/preview/datamigration/mgmt/2018-03-31-preview/datamigration/resourceskus.go
  services/preview/datamigration/mgmt/2018-03-31-preview/datamigration/services.go
  services/preview/datamigration/mgmt/2018-03-31-preview/datamigration/tasks.go
  services/preview/datamigration/mgmt/2018-03-31-preview/datamigration/usages.go
  services/preview/datamigration/mgmt/2018-03-31-preview/datamigration/version.go
Labels: ServicePR, review

#1476 [AutoPR network/resource-manager] Network 2018-02 for Go and Python
  services/network/mgmt/2018-02-01/network/applicationgateways.go
  services/network/mgmt/2018-02-01/network/applicationsecuritygroups.go
  services/network/mgmt/2018-02-01/network/availableendpointservices.go
  services/network/mgmt/2018-02-01/network/bgpservicecommunities.go
  services/network/mgmt/2018-02-01/network/client.go
  services/network/mgmt/2018-02-01/network/connectionmonitors.go
  services/network/mgmt/2018-02-01/network/ddosprotectionplans.go
  services/network/mgmt/2018-02-01/network/defaultsecurityrules.go
  services/network/mgmt/2018-02-01/network/expressroutecircuitauthorizations.go
  services/network/mgmt/2018-02-01/network/expressroutecircuitconnections.go
  services/network/mgmt/2018-02-01/network/expressroutecircuitpeerings.go
  services/network/mgmt/2018-02-01/network/expressroutecircuits.go
  services/network/mgmt/2018-02-01/network/expressroutecrossconnectionpeerings.go
  services/network/mgmt/2018-02-01/network/expressroutecrossconnections.go
  services/network/mgmt/2018-02-01/network/expressrouteserviceproviders.go
  services/network/mgmt/2018-02-01/network/inboundnatrules.go
  services/network/mgmt/2018-02-01/network/interfaceipconfigurations.go
  services/network/mgmt/2018-02-01/network/interfaceloadbalancers.go
  services/network/mgmt/2018-02-01/network/interfaces.go
  services/network/mgmt/2018-02-01/network/loadbalancerbackendaddresspools.go
  services/network/mgmt/2018-02-01/network/loadbalancerfrontendipconfigurations.go
  services/network/mgmt/2018-02-01/network/loadbalancerloadbalancingrules.go
  services/network/mgmt/2018-02-01/network/loadbalancernetworkinterfaces.go
  services/network/mgmt/2018-02-01/network/loadbalancerprobes.go
  services/network/mgmt/2018-02-01/network/loadbalancers.go
  services/network/mgmt/2018-02-01/network/localnetworkgateways.go
  services/network/mgmt/2018-02-01/network/models.go
  services/network/mgmt/2018-02-01/network/operations.go
  services/network/mgmt/2018-02-01/network/packetcaptures.go
  services/network/mgmt/2018-02-01/network/publicipaddresses.go
  services/network/mgmt/2018-02-01/network/routefilterrules.go
  services/network/mgmt/2018-02-01/network/routefilters.go
  services/network/mgmt/2018-02-01/network/routes.go
  services/network/mgmt/2018-02-01/network/routetables.go
  services/network/mgmt/2018-02-01/network/securitygroups.go
  services/network/mgmt/2018-02-01/network/securityrules.go
  services/network/mgmt/2018-02-01/network/subnets.go
  services/network/mgmt/2018-02-01/network/usages.go
  services/network/mgmt/2018-02-01/network/version.go
  services/network/mgmt/2018-02-01/network/virtualnetworkgatewayconnections.go
  services/network/mgmt/2018-02-01/network/virtualnetworkgateways.go
  services/network/mgmt/2018-02-01/network/virtualnetworkpeerings.go
  services/network/mgmt/2018-02-01/network/virtualnetworks.go
  services/network/mgmt/2018-02-01/network/watchers.go
Labels: RestPRMerged, review

#1423 [AutoPR web/resource-manager] Adding BillingMeters API
  services/web/mgmt/2016-09-01/web/billingmeters.go
  services/web/mgmt/2016-09-01/web/models.go
Labels: RestPRMerged, review

#1478 [AutoPR cognitiveservices/resource-manager] Make filter a method parameter
  services/cognitiveservices/mgmt/2017-04-18/cognitiveservices/accounts.go
  services/cognitiveservices/mgmt/2017-04-18/cognitiveservices/checkskuavailability.go
  services/cognitiveservices/mgmt/2017-04-18/cognitiveservices/client.go
  services/cognitiveservices/mgmt/2017-04-18/cognitiveservices/operations.go
Labels: RestPRMerged, review

#1477 [AutoPR] network/resource-manager
  services/network/mgmt/2018-02-01/network/applicationgateways.go
  services/network/mgmt/2018-02-01/network/applicationsecuritygroups.go
  services/network/mgmt/2018-02-01/network/availableendpointservices.go
  services/network/mgmt/2018-02-01/network/bgpservicecommunities.go
  services/network/mgmt/2018-02-01/network/client.go
  services/network/mgmt/2018-02-01/network/connectionmonitors.go
  services/network/mgmt/2018-02-01/network/ddosprotectionplans.go
  services/network/mgmt/2018-02-01/network/defaultsecurityrules.go
  services/network/mgmt/2018-02-01/network/expressroutecircuitauthorizations.go
  services/network/mgmt/2018-02-01/network/expressroutecircuitconnections.go
  services/network/mgmt/2018-02-01/network/expressroutecircuitpeerings.go
  services/network/mgmt/2018-02-01/network/expressroutecircuits.go
  services/network/mgmt/2018-02-01/network/expressroutecrossconnectionpeerings.go
  services/network/mgmt/2018-02-01/network/expressroutecrossconnections.go
  services/network/mgmt/2018-02-01/network/expressrouteserviceproviders.go
  services/network/mgmt/2018-02-01/network/inboundnatrules.go
  services/network/mgmt/2018-02-01/network/interfaceipconfigurations.go
  services/network/mgmt/2018-02-01/network/interfaceloadbalancers.go
  services/network/mgmt/2018-02-01/network/interfaces.go
  services/network/mgmt/2018-02-01/network/loadbalancerbackendaddresspools.go
  services/network/mgmt/2018-02-01/network/loadbalancerfrontendipconfigurations.go
  services/network/mgmt/2018-02-01/network/loadbalancerloadbalancingrules.go
  services/network/mgmt/2018-02-01/network/loadbalancernetworkinterfaces.go
  services/network/mgmt/2018-02-01/network/loadbalancerprobes.go
  services/network/mgmt/2018-02-01/network/loadbalancers.go
  services/network/mgmt/2018-02-01/network/localnetworkgateways.go
  services/network/mgmt/2018-02-01/network/models.go
  services/network/mgmt/2018-02-01/network/operations.go
  services/network/mgmt/2018-02-01/network/packetcaptures.go
  services/network/mgmt/2018-02-01/network/publicipaddresses.go
  services/network/mgmt/2018-02-01/network/routefilterrules.go
  services/network/mgmt/2018-02-01/network/routefilters.go
  services/network/mgmt/2018-02-01/network/routes.go
  services/network/mgmt/2018-02-01/network/routetables.go
  services/network/mgmt/2018-02-01/network/securitygroups.go
  services/network/mgmt/2018-02-01/network/securityrules.go
  services/network/mgmt/2018-02-01/network/subnets.go
  services/network/mgmt/2018-02-01/network/usages.go
  services/network/mgmt/2018-02-01/network/version.go
  services/network/mgmt/2018-02-01/network/virtualnetworkgatewayconnections.go
  services/network/mgmt/2018-02-01/network/virtualnetworkgateways.go
  services/network/mgmt/2018-02-01/network/virtualnetworkpeerings.go
  services/network/mgmt/2018-02-01/network/virtualnetworks.go
  services/network/mgmt/2018-02-01/network/watchers.go
Labels: ServicePR, review

#1480 [AutoPR] cognitiveservices/resource-manager
  services/cognitiveservices/mgmt/2017-04-18/cognitiveservices/accounts.go
  services/cognitiveservices/mgmt/2017-04-18/cognitiveservices/checkskuavailability.go
  services/cognitiveservices/mgmt/2017-04-18/cognitiveservices/client.go
  services/cognitiveservices/mgmt/2017-04-18/cognitiveservices/operations.go
Labels: ServicePR, review
