Repository Azure/azure-sdk-for-go, pull requests merged in 2019-01, with the labels that each got.

#3775 [AutoPR] storage/resource-manager
  services/preview/storage/mgmt/2015-05-01-preview/storage/models.go
  services/preview/storage/mgmt/2018-03-01-preview/storage/models.go
  services/storage/mgmt/2015-06-15/storage/models.go
  services/storage/mgmt/2016-01-01/storage/models.go
  services/storage/mgmt/2016-05-01/storage/models.go
  services/storage/mgmt/2016-12-01/storage/models.go
  services/storage/mgmt/2017-06-01/storage/models.go
  services/storage/mgmt/2017-10-01/storage/models.go
  services/storage/mgmt/2018-02-01/storage/models.go
  services/storage/mgmt/2018-07-01/storage/models.go
Labels: ServicePR, review

#3811 [AutoPR network/resource-manager] Fix errors in old Network API version
  services/network/mgmt/2016-03-30/network/networkapi/interfaces.go
  services/network/mgmt/2016-03-30/network/virtualnetworkgatewayconnections.go
  services/network/mgmt/2016-06-01/network/networkapi/interfaces.go
  services/network/mgmt/2016-06-01/network/virtualnetworkgatewayconnections.go
Labels: RestPRMerged, review

#3814 [AutoPR edgegateway/resource-manager] Swagger and examples for Microsoft.DataBoxEdge RP
  profiles/latest/edgegateway/mgmt/edgegateway/edgegatewayapi/models.go
  profiles/latest/edgegateway/mgmt/edgegateway/models.go
  profiles/preview/edgegateway/mgmt/edgegateway/edgegatewayapi/models.go
  profiles/preview/edgegateway/mgmt/edgegateway/models.go
  services/edgegateway/mgmt/2018-07-01/edgegateway/alerts.go
  services/edgegateway/mgmt/2018-07-01/edgegateway/bandwidthschedules.go
  services/edgegateway/mgmt/2018-07-01/edgegateway/client.go
  services/edgegateway/mgmt/2018-07-01/edgegateway/devices.go
  services/edgegateway/mgmt/2018-07-01/edgegateway/edgegatewayapi/interfaces.go
  services/edgegateway/mgmt/2018-07-01/edgegateway/models.go
  services/edgegateway/mgmt/2018-07-01/edgegateway/operations.go
  services/edgegateway/mgmt/2018-07-01/edgegateway/operationsstatus.go
  services/edgegateway/mgmt/2018-07-01/edgegateway/orders.go
  services/edgegateway/mgmt/2018-07-01/edgegateway/roles.go
  services/edgegateway/mgmt/2018-07-01/edgegateway/shares.go
  services/edgegateway/mgmt/2018-07-01/edgegateway/storageaccountcredentials.go
  services/edgegateway/mgmt/2018-07-01/edgegateway/triggers.go
  services/edgegateway/mgmt/2018-07-01/edgegateway/users.go
  services/edgegateway/mgmt/2018-07-01/edgegateway/version.go
Labels: RestPRMerged, review

#3817 [AutoPR frontdoor/resource-manager] fixing invalid paths in frontdoor
  services/preview/frontdoor/mgmt/2018-08-01-preview/frontdoor/frontendendpoints.go
Labels: review

#3812 [AutoPR] network/resource-manager
  services/network/mgmt/2016-03-30/network/networkapi/interfaces.go
  services/network/mgmt/2016-03-30/network/virtualnetworkgatewayconnections.go
  services/network/mgmt/2016-06-01/network/networkapi/interfaces.go
  services/network/mgmt/2016-06-01/network/virtualnetworkgatewayconnections.go
Labels: ServicePR, review

#3815 [AutoPR] edgegateway/resource-manager
  profiles/latest/edgegateway/mgmt/edgegateway/edgegatewayapi/models.go
  profiles/latest/edgegateway/mgmt/edgegateway/models.go
  profiles/preview/edgegateway/mgmt/edgegateway/edgegatewayapi/models.go
  profiles/preview/edgegateway/mgmt/edgegateway/models.go
  services/edgegateway/mgmt/2018-07-01/edgegateway/alerts.go
  services/edgegateway/mgmt/2018-07-01/edgegateway/bandwidthschedules.go
  services/edgegateway/mgmt/2018-07-01/edgegateway/client.go
  services/edgegateway/mgmt/2018-07-01/edgegateway/devices.go
  services/edgegateway/mgmt/2018-07-01/edgegateway/edgegatewayapi/interfaces.go
  services/edgegateway/mgmt/2018-07-01/edgegateway/models.go
  services/edgegateway/mgmt/2018-07-01/edgegateway/operations.go
  services/edgegateway/mgmt/2018-07-01/edgegateway/operationsstatus.go
  services/edgegateway/mgmt/2018-07-01/edgegateway/orders.go
  services/edgegateway/mgmt/2018-07-01/edgegateway/roles.go
  services/edgegateway/mgmt/2018-07-01/edgegateway/shares.go
  services/edgegateway/mgmt/2018-07-01/edgegateway/storageaccountcredentials.go
  services/edgegateway/mgmt/2018-07-01/edgegateway/triggers.go
  services/edgegateway/mgmt/2018-07-01/edgegateway/users.go
  services/edgegateway/mgmt/2018-07-01/edgegateway/version.go
Labels: ServicePR, review

#3829 [AutoPR containerservices/resource-manager] [AKS]: Remove 200/OK response from reset SP/AAD api
  services/containerservice/mgmt/2018-03-31/containerservice/managedclusters.go
  services/containerservice/mgmt/2018-03-31/containerservice/models.go
  services/preview/containerservice/mgmt/2018-08-01-preview/containerservice/managedclusters.go
  services/preview/containerservice/mgmt/2018-08-01-preview/containerservice/models.go
  services/preview/containerservice/mgmt/2018-09-30-preview/containerservice/managedclusters.go
  services/preview/containerservice/mgmt/2018-09-30-preview/containerservice/models.go
Labels: RestPRMerged, review

#3832 [AutoPR containerservices/resource-manager] [AKS] fix schema and example validation warnings
  services/containerservice/mgmt/2018-03-31/containerservice/models.go
  services/preview/containerservice/mgmt/2018-08-01-preview/containerservice/models.go
  services/preview/containerservice/mgmt/2018-09-30-preview/containerservice/models.go
Labels: RestPRMerged, review

#3835 [AutoPR network/resource-manager] Fix duplicate path in old Network API version
  services/network/mgmt/2015-06-15/network/networkapi/interfaces.go
  services/network/mgmt/2015-06-15/network/virtualnetworkgatewayconnections.go
Labels: RestPRMerged, review

#3831 [AutoPR] containerservices/resource-manager
  services/containerservice/mgmt/2018-03-31/containerservice/managedclusters.go
  services/containerservice/mgmt/2018-03-31/containerservice/models.go
  services/preview/containerservice/mgmt/2018-08-01-preview/containerservice/managedclusters.go
  services/preview/containerservice/mgmt/2018-08-01-preview/containerservice/models.go
  services/preview/containerservice/mgmt/2018-09-30-preview/containerservice/managedclusters.go
  services/preview/containerservice/mgmt/2018-09-30-preview/containerservice/models.go
Labels: ServicePR

#3836 [AutoPR] network/resource-manager
  services/network/mgmt/2015-06-15/network/networkapi/interfaces.go
  services/network/mgmt/2015-06-15/network/virtualnetworkgatewayconnections.go
Labels: ServicePR

#3826 [AutoPR apimanagement/resource-manager] OpenAPIv3 support documented
  profiles/preview/preview/apimanagement/mgmt/apimanagement/models.go
  services/preview/apimanagement/mgmt/2018-06-01-preview/apimanagement/models.go
Labels: RestPRMerged, review

#3833 [AutoPR eventgrid/resource-manager] Add tag: package-2019-01 to ruby and go readme files
  services/eventgrid/mgmt/2019-01-01/eventgrid/models.go
Labels: RestPRMerged, review

#3840 [AutoPR] apimanagement/resource-manager
  profiles/preview/preview/apimanagement/mgmt/apimanagement/models.go
  services/preview/apimanagement/mgmt/2018-06-01-preview/apimanagement/models.go
Labels: ServicePR, review

#3841 [AutoPR] eventgrid/resource-manager
  services/eventgrid/mgmt/2019-01-01/eventgrid/models.go
Labels: ServicePR, review

#3844 [AutoPR compute/resource-manager] Update ComputerName definition for OsProfile
  services/compute/mgmt/2015-06-15/compute/models.go
  services/compute/mgmt/2016-03-30/compute/models.go
  services/compute/mgmt/2017-03-30/compute/models.go
  services/compute/mgmt/2017-12-01/compute/models.go
  services/compute/mgmt/2018-04-01/compute/models.go
  services/compute/mgmt/2018-06-01/compute/models.go
  services/compute/mgmt/2018-10-01/compute/models.go
Labels: RestPRMerged, review

#3845 [AutoPR] compute/resource-manager
  services/compute/mgmt/2015-06-15/compute/models.go
  services/compute/mgmt/2016-03-30/compute/models.go
  services/compute/mgmt/2017-03-30/compute/models.go
  services/compute/mgmt/2017-12-01/compute/models.go
  services/compute/mgmt/2018-04-01/compute/models.go
  services/compute/mgmt/2018-06-01/compute/models.go
  services/compute/mgmt/2018-10-01/compute/models.go
Labels: ServicePR, review

#3846 [AutoPR logic/resource-manager] [LogicApps] Fix more acronyms that don't match API
  services/preview/logic/mgmt/2018-07-01-preview/logic/integrationaccountagreements.go
  services/preview/logic/mgmt/2018-07-01-preview/logic/models.go
Labels: RestPRMerged, review

#3855 [AutoPR] logic/resource-manager
  services/preview/logic/mgmt/2018-07-01-preview/logic/integrationaccountagreements.go
  services/preview/logic/mgmt/2018-07-01-preview/logic/models.go
Labels: ServicePR, review

#3849 [AutoPR batch/resource-manager/batch/data-plane] Update storageContainerUrl description
  services/batch/2018-12-01.8.0/batch/models.go
  services/batch/mgmt/2018-12-01/batch/models.go
Labels: RestPRMerged, review

#3878 [AutoPR hanaonazure/resource-manager] [Hub Generated] Review request for Microsoft.HanaOnAzure to add version 2017-11-03-preview
  profiles/preview/preview/hanaonazure/mgmt/hanaonazure/models.go
  services/preview/hanaonazure/mgmt/2017-11-03-preview/hanaonazure/hanainstances.go
  services/preview/hanaonazure/mgmt/2017-11-03-preview/hanaonazure/hanaonazureapi/interfaces.go
  services/preview/hanaonazure/mgmt/2017-11-03-preview/hanaonazure/models.go
Labels: RestPRMerged, review

#3881 [AutoPR] hanaonazure/resource-manager
  profiles/preview/preview/hanaonazure/mgmt/hanaonazure/models.go
  services/preview/hanaonazure/mgmt/2017-11-03-preview/hanaonazure/hanainstances.go
  services/preview/hanaonazure/mgmt/2017-11-03-preview/hanaonazure/hanaonazureapi/interfaces.go
  services/preview/hanaonazure/mgmt/2017-11-03-preview/hanaonazure/models.go
Labels: ServicePR, review

#3859 [AutoPR eventgrid/data-plane] Add MediaJobOutputProgressEventData in Media Services EventGrid swagger
  profiles/latest/eventgrid/eventgrid/models.go
  profiles/preview/eventgrid/eventgrid/models.go
  services/eventgrid/2018-01-01/eventgrid/models.go
Labels: RestPRMerged, review

#3896 [AutoPR blueprint/resource-manager] typo: blueprint/resource-manager/Microsoft.Blueprint
  services/preview/blueprint/mgmt/2017-11-11-preview/blueprint/models.go
Labels: RestPRMerged, review

#3894 [AutoPR containerregistry/resource-manager] Update swagger to add target and credentials flag to the requests, and add examples.
  profiles/latest/containerregistry/mgmt/containerregistry/models.go
  profiles/preview/containerregistry/mgmt/containerregistry/models.go
  services/containerregistry/mgmt/2018-09-01/containerregistry/models.go
Labels: RestPRMerged, review

#3909 [AutoPR sql/resource-manager] Added support for dropped databases on Managed Instance
  services/preview/sql/mgmt/2017-03-01-preview/sql/models.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/restorabledroppedmanageddatabases.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/sqlapi/interfaces.go
Labels: RestPRMerged, review

#3904 [AutoPR] containerregistry/resource-manager
  profiles/latest/containerregistry/mgmt/containerregistry/models.go
  profiles/preview/containerregistry/mgmt/containerregistry/models.go
  services/containerregistry/mgmt/2018-09-01/containerregistry/models.go
Labels: ServicePR, review

#3899 [AutoPR] blueprint/resource-manager
  services/preview/blueprint/mgmt/2017-11-11-preview/blueprint/models.go
Labels: ServicePR, review

#3910 [AutoPR] sql/resource-manager
  services/preview/sql/mgmt/2017-03-01-preview/sql/models.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/restorabledroppedmanageddatabases.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/sqlapi/interfaces.go
Labels: ServicePR, review

#3891 [AutoPR web/resource-manager] Merge changes from release microsoft.web ant79
  services/web/mgmt/2018-02-01/web/apps.go
  services/web/mgmt/2018-02-01/web/models.go
Labels: RestPRMerged, review

#3837 [AutoPR securityinsight/resource-manager] Creating first and basic swagger for new RP of ASI (Azure Security In…
  profiles/preview/preview/securityinsight/mgmt/securityinsight/models.go
  profiles/preview/preview/securityinsight/mgmt/securityinsight/securityinsightapi/models.go
  services/preview/securityinsight/mgmt/2017-08-01-preview/securityinsight/alertrules.go
  services/preview/securityinsight/mgmt/2017-08-01-preview/securityinsight/client.go
  services/preview/securityinsight/mgmt/2017-08-01-preview/securityinsight/models.go
  services/preview/securityinsight/mgmt/2017-08-01-preview/securityinsight/operations.go
  services/preview/securityinsight/mgmt/2017-08-01-preview/securityinsight/securityinsightapi/interfaces.go
  services/preview/securityinsight/mgmt/2017-08-01-preview/securityinsight/version.go
Labels: RestPRInProgress, review

#3839 [AutoPR recoveryservicesbackup/resource-manager] Generating latest spec
  profiles/latest/recoveryservices/mgmt/backup/models.go
  profiles/preview/recoveryservices/mgmt/backup/models.go
  services/recoveryservices/mgmt/2016-12-01/backup/backupapi/interfaces.go
  services/recoveryservices/mgmt/2016-12-01/backup/models.go
  services/recoveryservices/mgmt/2016-12-01/backup/protectablecontainers.go
  services/recoveryservices/mgmt/2016-12-01/backup/resourcestorageconfigs.go
  services/recoveryservices/mgmt/2017-07-01/backup/backupapi/interfaces.go
  services/recoveryservices/mgmt/2017-07-01/backup/models.go
  services/recoveryservices/mgmt/2017-07-01/backup/protectablecontainers.go
  services/recoveryservices/mgmt/2017-07-01/backup/resourcestorageconfigs.go
Labels: RestPRInProgress, review

#3916 Generated from 36aca1e97fc2907ffb6ddb2be9d32781c6d1cea0 (#3837)
  profiles/preview/preview/securityinsight/mgmt/securityinsight/models.go
  profiles/preview/preview/securityinsight/mgmt/securityinsight/securityinsightapi/models.go
  services/preview/securityinsight/mgmt/2017-08-01-preview/securityinsight/alertrules.go
  services/preview/securityinsight/mgmt/2017-08-01-preview/securityinsight/client.go
  services/preview/securityinsight/mgmt/2017-08-01-preview/securityinsight/models.go
  services/preview/securityinsight/mgmt/2017-08-01-preview/securityinsight/operations.go
  services/preview/securityinsight/mgmt/2017-08-01-preview/securityinsight/securityinsightapi/interfaces.go
  services/preview/securityinsight/mgmt/2017-08-01-preview/securityinsight/version.go
Labels: review

#3923 [AutoPR cognitiveservices/data-plane/Face] [Cogs Face] Align with latest released version of Face API with Snapshot features.
  profiles/latest/cognitiveservices/face/faceapi/models.go
  profiles/latest/cognitiveservices/face/models.go
  profiles/preview/cognitiveservices/face/faceapi/models.go
  profiles/preview/cognitiveservices/face/models.go
  services/cognitiveservices/v1.0/face/faceapi/interfaces.go
  services/cognitiveservices/v1.0/face/models.go
  services/cognitiveservices/v1.0/face/snapshot.go
Labels: RestPRMerged, review

#3895 [AutoPR servicebus/resource-manager] typo: servicebus/resource-manager/Microsoft.ServiceBus
  services/servicebus/mgmt/2015-08-01/servicebus/models.go
  services/servicebus/mgmt/2015-08-01/servicebus/namespaces.go
  services/servicebus/mgmt/2015-08-01/servicebus/queues.go
  services/servicebus/mgmt/2015-08-01/servicebus/topics.go
  services/servicebus/mgmt/2017-04-01/servicebus/disasterrecoveryconfigs.go
  services/servicebus/mgmt/2017-04-01/servicebus/migrationconfigs.go
  services/servicebus/mgmt/2017-04-01/servicebus/models.go
  services/servicebus/mgmt/2017-04-01/servicebus/namespaces.go
  services/servicebus/mgmt/2017-04-01/servicebus/queues.go
  services/servicebus/mgmt/2017-04-01/servicebus/topics.go
Labels: RestPRMerged, review

#3920 [AutoPR security/resource-manager] Add description to empty result in Workspace Settings Get
  services/preview/security/mgmt/2017-08-01-preview/security/workspacesettings.go
Labels: RestPRMerged, review

#3927 [AutoPR] cognitiveservices/data-plane/Face
  profiles/latest/cognitiveservices/face/faceapi/models.go
  profiles/latest/cognitiveservices/face/models.go
  profiles/preview/cognitiveservices/face/faceapi/models.go
  profiles/preview/cognitiveservices/face/models.go
  services/cognitiveservices/v1.0/face/faceapi/interfaces.go
  services/cognitiveservices/v1.0/face/models.go
  services/cognitiveservices/v1.0/face/snapshot.go
Labels: ServicePR, review

#3929 [AutoPR] security/resource-manager
  services/preview/security/mgmt/2017-08-01-preview/security/workspacesettings.go
Labels: ServicePR, review

#3922 [AutoPR hdinsight/resource-manager] [HDInsight] - Support MSI for ADLS gen2
  services/preview/hdinsight/mgmt/2015-03-01-preview/hdinsight/models.go
  services/preview/hdinsight/mgmt/2018-06-01-preview/hdinsight/models.go
Labels: RestPRMerged, review

#3871 [AutoPR cognitiveservices/resource-manager] Adding customSubDomainName property.
  services/cognitiveservices/mgmt/2017-04-18/cognitiveservices/models.go
Labels: review

#3928 [AutoPR] servicebus/resource-manager
  services/servicebus/mgmt/2015-08-01/servicebus/models.go
  services/servicebus/mgmt/2015-08-01/servicebus/namespaces.go
  services/servicebus/mgmt/2015-08-01/servicebus/queues.go
  services/servicebus/mgmt/2015-08-01/servicebus/topics.go
  services/servicebus/mgmt/2017-04-01/servicebus/disasterrecoveryconfigs.go
  services/servicebus/mgmt/2017-04-01/servicebus/migrationconfigs.go
  services/servicebus/mgmt/2017-04-01/servicebus/models.go
  services/servicebus/mgmt/2017-04-01/servicebus/namespaces.go
  services/servicebus/mgmt/2017-04-01/servicebus/queues.go
  services/servicebus/mgmt/2017-04-01/servicebus/topics.go
Labels: ServicePR, review

#3933 [AutoPR] hdinsight/resource-manager
  services/preview/hdinsight/mgmt/2015-03-01-preview/hdinsight/models.go
  services/preview/hdinsight/mgmt/2018-06-01-preview/hdinsight/models.go
Labels: ServicePR, review

#3935 [AutoPR] cognitiveservices/resource-manager
  services/cognitiveservices/mgmt/2017-04-18/cognitiveservices/models.go
Labels: ServicePR, review

#3941 [AutoPR cognitiveservices/data-plane/Face] [Cogs Face] Refine the documentation for Face API's new Snapshot features.
  services/cognitiveservices/v1.0/face/models.go
  services/cognitiveservices/v1.0/face/snapshot.go
Labels: RestPRMerged, review

#3952 [AutoPR web/resource-manager] typo: web/resource-manager/Microsoft.Web/stable/2018-02-01/WebApps.json
  services/web/mgmt/2018-02-01/web/models.go
Labels: RestPRMerged

#3947 [AutoPR containerservice/resource-manager] [AKS] add apiServerAuthorizedIPRanges property
  services/containerservice/mgmt/2018-03-31/containerservice/models.go
  services/preview/containerservice/mgmt/2018-08-01-preview/containerservice/models.go
  services/preview/containerservice/mgmt/2018-09-30-preview/containerservice/models.go
Labels: RestPRMerged, review

#3953 [AutoPR] web/resource-manager
  services/web/mgmt/2018-02-01/web/models.go
Labels: ServicePR, review

#3955 [AutoPR] containerservice/resource-manager
  services/containerservice/mgmt/2018-03-31/containerservice/models.go
  services/preview/containerservice/mgmt/2018-08-01-preview/containerservice/models.go
  services/preview/containerservice/mgmt/2018-09-30-preview/containerservice/models.go
Labels: ServicePR, review

#3957 update dependencies
  Gopkg.lock
Labels: review

#3959 [AutoPR hanaonazure/resource-manager] Add new field 'proximityPlacementGroup' to properties of HanaInstance
  services/preview/hanaonazure/mgmt/2017-11-03-preview/hanaonazure/models.go
Labels: RestPRMerged, review

#3946 [AutoPR cognitiveservices/data-plane/LUIS/Runtime] Add dispatch child to LUIS Runtime response
  services/cognitiveservices/v2.0/luis/runtime/models.go
Labels: RestPRMerged, review

#3964 Fix datalake storage packages
  profiles/latest/stable/storage/datalake/storagedatalake/models.go
  profiles/latest/stable/storage/datalake/storagedatalake/storagedatalakeapi/models.go
  profiles/latest/storage/datalake/storagedatalake/models.go
  profiles/latest/storage/datalake/storagedatalake/storagedatalakeapi/models.go
  profiles/preview/stable/storage/datalake/storagedatalake/models.go
  profiles/preview/stable/storage/datalake/storagedatalake/storagedatalakeapi/models.go
  profiles/preview/storage/datalake/storagedatalake/models.go
  profiles/preview/storage/datalake/storagedatalake/storagedatalakeapi/models.go
  services/storage/datalake/2018-06-17/storagedatalake/client.go
  services/storage/datalake/2018-06-17/storagedatalake/filesystem.go
  services/storage/datalake/2018-06-17/storagedatalake/models.go
  services/storage/datalake/2018-06-17/storagedatalake/path.go
  services/storage/datalake/2018-06-17/storagedatalake/storagedatalakeapi/interfaces.go
  services/storage/datalake/2018-06-17/storagedatalake/version.go
  services/storage/datalake/2018-11-09/storagedatalake/client.go
  services/storage/datalake/2018-11-09/storagedatalake/filesystem.go
  services/storage/datalake/2018-11-09/storagedatalake/models.go
  services/storage/datalake/2018-11-09/storagedatalake/path.go
  services/storage/datalake/2018-11-09/storagedatalake/storagedatalakeapi/interfaces.go
  services/storage/datalake/2018-11-09/storagedatalake/version.go
Labels: review

#3968 [AutoPR sql/resource-manager] Update managedInstances.json
  services/preview/sql/mgmt/2015-05-01-preview/sql/models.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/models.go
Labels: RestPRMerged, review

#3936 [AutoPR securityinsights/resource-manager] Creates the "real" API for Scheduled Alert Rules
  profiles/preview/preview/securityinsight/mgmt/securityinsight/models.go
  services/preview/securityinsight/mgmt/2017-08-01-preview/securityinsight/alertrules.go
  services/preview/securityinsight/mgmt/2017-08-01-preview/securityinsight/models.go
  services/preview/securityinsight/mgmt/2017-08-01-preview/securityinsight/securityinsightapi/interfaces.go
Labels: RestPRMerged, review

#3962 [AutoPR eventgrid/data-plane] Add Helm Events to ACR Schema for Event Grid
  profiles/latest/eventgrid/eventgrid/models.go
  profiles/preview/eventgrid/eventgrid/models.go
  services/eventgrid/2018-01-01/eventgrid/models.go
Labels: RestPRMerged, review

#3954 [AutoPR eventhub/resource-manager] Eventhub: Added skipEmptyArchives to Eventhub CaptureDescription
  services/eventhub/mgmt/2017-04-01/eventhub/models.go
Labels: RestPRMerged, review

#3982 [AutoPR] eventgrid/data-plane
  profiles/latest/eventgrid/eventgrid/models.go
  profiles/preview/eventgrid/eventgrid/models.go
  services/eventgrid/2018-01-01/eventgrid/models.go
Labels: ServicePR, review

#3971 [AutoPR] securityinsights/resource-manager
  profiles/preview/preview/securityinsight/mgmt/securityinsight/models.go
  services/preview/securityinsight/mgmt/2017-08-01-preview/securityinsight/alertrules.go
  services/preview/securityinsight/mgmt/2017-08-01-preview/securityinsight/models.go
  services/preview/securityinsight/mgmt/2017-08-01-preview/securityinsight/securityinsightapi/interfaces.go
Labels: ServicePR, review
