Repository Azure/azure-sdk-for-go, pull requests merged in 2019-02, with the labels that each got.

#3989 [AutoPR recoveryservicesbackup/resource-manager] Fixing a minor bug in Recovery Services (Backup)
  services/recoveryservices/mgmt/2016-12-01/backup/models.go
  services/recoveryservices/mgmt/2017-07-01/backup/models.go
Labels: RestPRMerged, review

#3985 [AutoPR] eventhub/resource-manager
  services/eventhub/mgmt/2017-04-01/eventhub/models.go
Labels: ServicePR, review

#3996 [AutoPR policyinsights/resource-manager] [Hub Generated] Review request for Microsoft.PolicyInsights to add version 2018-07-01-preview
  profiles/preview/preview/policyinsights/mgmt/policyinsights/models.go
  services/preview/policyinsights/mgmt/2018-07-01-preview/policyinsights/models.go
  services/preview/policyinsights/mgmt/2018-07-01-preview/policyinsights/operations.go
  services/preview/policyinsights/mgmt/2018-07-01-preview/policyinsights/policyinsightsapi/interfaces.go
  services/preview/policyinsights/mgmt/2018-07-01-preview/policyinsights/policystates.go
Labels: RestPRMerged, review

#3987 [AutoPR security/resource-manager] Adding new api-version to Microsoft.Security Alerts resource
  profiles/preview/preview/security/mgmt/security/models.go
  services/preview/security/mgmt/2017-08-01-preview/security/models.go
Labels: RestPRMerged, review

#3993 [AutoPR] recoveryservicesbackup/resource-manager
  services/recoveryservices/mgmt/2016-12-01/backup/models.go
  services/recoveryservices/mgmt/2017-07-01/backup/models.go
Labels: ServicePR, review

#3994 [AutoPR] compute/resource-manager
  services/compute/mgmt/2018-06-01/compute/models.go
  services/compute/mgmt/2018-10-01/compute/models.go
Labels: ServicePR, review

#3997 [AutoPR] policyinsights/resource-manager
  profiles/preview/preview/policyinsights/mgmt/policyinsights/models.go
  services/preview/policyinsights/mgmt/2018-07-01-preview/policyinsights/models.go
  services/preview/policyinsights/mgmt/2018-07-01-preview/policyinsights/operations.go
  services/preview/policyinsights/mgmt/2018-07-01-preview/policyinsights/policyinsightsapi/interfaces.go
  services/preview/policyinsights/mgmt/2018-07-01-preview/policyinsights/policystates.go
Labels: ServicePR, review

#3950 [AutoPR] cognitiveservices/data-plane/Face
  services/cognitiveservices/v1.0/face/models.go
  services/cognitiveservices/v1.0/face/snapshot.go
Labels: ServicePR, review

#4005 [AutoPR compute/resource-manager] Update compute.json to add ProtectFromScaleIn property to VMScaleSetVM properties
  services/compute/mgmt/2018-10-01/compute/models.go
Labels: RestPRMerged, review

#3981 [AutoPR cost-management/resource-manager] Export2
  profiles/latest/costmanagement/mgmt/costmanagement/costmanagementapi/models.go
  profiles/latest/costmanagement/mgmt/costmanagement/models.go
  profiles/preview/costmanagement/mgmt/costmanagement/costmanagementapi/models.go
  profiles/preview/costmanagement/mgmt/costmanagement/models.go
  profiles/preview/preview/costmanagement/mgmt/costmanagement/models.go
  services/costmanagement/mgmt/2019-01-01/costmanagement/client.go
  services/costmanagement/mgmt/2019-01-01/costmanagement/costmanagementapi/interfaces.go
  services/costmanagement/mgmt/2019-01-01/costmanagement/dimensions.go
  services/costmanagement/mgmt/2019-01-01/costmanagement/exports.go
  services/costmanagement/mgmt/2019-01-01/costmanagement/models.go
  services/costmanagement/mgmt/2019-01-01/costmanagement/operations.go
  services/costmanagement/mgmt/2019-01-01/costmanagement/query.go
  services/costmanagement/mgmt/2019-01-01/costmanagement/version.go
  services/preview/costmanagement/mgmt/2018-08-01-preview/costmanagement/models.go
Labels: RestPRMerged, review

#4011 [AutoPR containerservice/resource-manager] Revert "[AKS] add apiServerAuthorizedIPRanges property"
  services/containerservice/mgmt/2018-03-31/containerservice/models.go
  services/preview/containerservice/mgmt/2018-08-01-preview/containerservice/models.go
  services/preview/containerservice/mgmt/2018-09-30-preview/containerservice/models.go
Labels: RestPRMerged, review

#4006 [AutoPR] compute/resource-manager
  services/compute/mgmt/2018-10-01/compute/models.go
Labels: ServicePR, review

#4013 [AutoPR] cost-management/resource-manager
  profiles/latest/costmanagement/mgmt/costmanagement/costmanagementapi/models.go
  profiles/latest/costmanagement/mgmt/costmanagement/models.go
  profiles/preview/costmanagement/mgmt/costmanagement/costmanagementapi/models.go
  profiles/preview/costmanagement/mgmt/costmanagement/models.go
  profiles/preview/preview/costmanagement/mgmt/costmanagement/models.go
  services/costmanagement/mgmt/2019-01-01/costmanagement/client.go
  services/costmanagement/mgmt/2019-01-01/costmanagement/costmanagementapi/interfaces.go
  services/costmanagement/mgmt/2019-01-01/costmanagement/dimensions.go
  services/costmanagement/mgmt/2019-01-01/costmanagement/exports.go
  services/costmanagement/mgmt/2019-01-01/costmanagement/models.go
  services/costmanagement/mgmt/2019-01-01/costmanagement/operations.go
  services/costmanagement/mgmt/2019-01-01/costmanagement/query.go
  services/costmanagement/mgmt/2019-01-01/costmanagement/version.go
  services/preview/costmanagement/mgmt/2018-08-01-preview/costmanagement/models.go
Labels: ServicePR, review

#4017 [AutoPR azure-kusto/resource-manager] typo: specification/azure-kusto/resource-manager/Microsoft.Kusto/stable/2019-01-21/kusto.json
  profiles/latest/stable/kusto/mgmt/kusto/kustoapi/models.go
  profiles/latest/stable/kusto/mgmt/kusto/models.go
  profiles/preview/stable/kusto/mgmt/kusto/kustoapi/models.go
  profiles/preview/stable/kusto/mgmt/kusto/models.go
  services/stable/kusto/mgmt/2019-01-21/kusto/client.go
  services/stable/kusto/mgmt/2019-01-21/kusto/clusters.go
  services/stable/kusto/mgmt/2019-01-21/kusto/databases.go
  services/stable/kusto/mgmt/2019-01-21/kusto/dataconnections.go
  services/stable/kusto/mgmt/2019-01-21/kusto/kustoapi/interfaces.go
  services/stable/kusto/mgmt/2019-01-21/kusto/models.go
  services/stable/kusto/mgmt/2019-01-21/kusto/operations.go
  services/stable/kusto/mgmt/2019-01-21/kusto/version.go
Labels: RestPRMerged

#4020 [AutoPR azure-kusto/resource-manager] Fix Go SDK codegen for azure-kusto
  profiles/latest/kusto/mgmt/kusto/kustoapi/models.go
  profiles/latest/kusto/mgmt/kusto/models.go
  profiles/preview/kusto/mgmt/kusto/kustoapi/models.go
  profiles/preview/kusto/mgmt/kusto/models.go
  services/kusto/mgmt/2019-01-21/kusto/client.go
  services/kusto/mgmt/2019-01-21/kusto/clusters.go
  services/kusto/mgmt/2019-01-21/kusto/databases.go
  services/kusto/mgmt/2019-01-21/kusto/dataconnections.go
  services/kusto/mgmt/2019-01-21/kusto/kustoapi/interfaces.go
  services/kusto/mgmt/2019-01-21/kusto/models.go
  services/kusto/mgmt/2019-01-21/kusto/operations.go
  services/kusto/mgmt/2019-01-21/kusto/version.go
Labels: RestPRMerged, review

#4021 [AutoPR] azure-kusto/resource-manager
  profiles/latest/kusto/mgmt/kusto/kustoapi/models.go
  profiles/latest/kusto/mgmt/kusto/models.go
  profiles/preview/kusto/mgmt/kusto/kustoapi/models.go
  profiles/preview/kusto/mgmt/kusto/models.go
  services/kusto/mgmt/2019-01-21/kusto/client.go
  services/kusto/mgmt/2019-01-21/kusto/clusters.go
  services/kusto/mgmt/2019-01-21/kusto/databases.go
  services/kusto/mgmt/2019-01-21/kusto/dataconnections.go
  services/kusto/mgmt/2019-01-21/kusto/kustoapi/interfaces.go
  services/kusto/mgmt/2019-01-21/kusto/models.go
  services/kusto/mgmt/2019-01-21/kusto/operations.go
  services/kusto/mgmt/2019-01-21/kusto/version.go
Labels: ServicePR, review

#3980 [AutoPR securityinsights/resource-manager] Adding data connectors APIs
  profiles/preview/preview/securityinsight/mgmt/securityinsight/models.go
  profiles/preview/preview/securityinsight/mgmt/securityinsight/securityinsightapi/models.go
  services/preview/securityinsight/mgmt/2017-08-01-preview/securityinsight/dataconnectors.go
  services/preview/securityinsight/mgmt/2017-08-01-preview/securityinsight/models.go
  services/preview/securityinsight/mgmt/2017-08-01-preview/securityinsight/securityinsightapi/interfaces.go
Labels: RestPRMerged, review

#4030 [AutoPR compute/resource-manager] fixes for reference documentation
  services/compute/mgmt/2015-06-15/compute/models.go
  services/compute/mgmt/2016-03-30/compute/models.go
  services/compute/mgmt/2017-03-30/compute/models.go
  services/compute/mgmt/2017-12-01/compute/models.go
  services/compute/mgmt/2018-04-01/compute/models.go
  services/compute/mgmt/2018-06-01/compute/models.go
  services/compute/mgmt/2018-10-01/compute/models.go
Labels: RestPRMerged, review

#4035 [AutoPR azure-kusto/resource-manager] Ga kc 1
  profiles/latest/kusto/mgmt/kusto/models.go
  profiles/preview/kusto/mgmt/kusto/models.go
  services/kusto/mgmt/2019-01-21/kusto/models.go
Labels: RestPRMerged, review

#4024 [AutoPR authorization/resource-manager] Removed "x-ms-pageable" from the elevateAccess API
  profiles/2018-03-01/authorization/mgmt/authorization/authorizationapi/models.go
  profiles/2018-03-01/authorization/mgmt/authorization/models.go
  profiles/latest/authorization/mgmt/authorization/authorizationapi/models.go
  profiles/latest/authorization/mgmt/authorization/models.go
  profiles/preview/authorization/mgmt/authorization/authorizationapi/models.go
  profiles/preview/authorization/mgmt/authorization/models.go
  services/authorization/mgmt/2015-07-01/authorization/authorizationapi/interfaces.go
  services/authorization/mgmt/2015-07-01/authorization/elevateaccess.go
Labels: RestPRMerged, review

#4009 [AutoPR sql/resource-manager] Updating Data Classification Swaggers.
  services/preview/sql/mgmt/2017-03-01-preview/sql/models.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/sensitivitylabels.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/sqlapi/interfaces.go
Labels: RestPRMerged, review

#4038 [AutoPR] authorization/resource-manager
  profiles/2018-03-01/authorization/mgmt/authorization/authorizationapi/models.go
  profiles/2018-03-01/authorization/mgmt/authorization/models.go
  profiles/latest/authorization/mgmt/authorization/authorizationapi/models.go
  profiles/latest/authorization/mgmt/authorization/models.go
  profiles/preview/authorization/mgmt/authorization/authorizationapi/models.go
  profiles/preview/authorization/mgmt/authorization/models.go
  services/authorization/mgmt/2015-07-01/authorization/authorizationapi/interfaces.go
  services/authorization/mgmt/2015-07-01/authorization/elevateaccess.go
Labels: ServicePR, review

#4036 [AutoPR] azure-kusto/resource-manager
  profiles/latest/kusto/mgmt/kusto/models.go
  profiles/preview/kusto/mgmt/kusto/models.go
  services/kusto/mgmt/2019-01-21/kusto/models.go
Labels: ServicePR, review

#4034 [AutoPR] compute/resource-manager
  services/compute/mgmt/2015-06-15/compute/models.go
  services/compute/mgmt/2016-03-30/compute/models.go
  services/compute/mgmt/2017-03-30/compute/models.go
  services/compute/mgmt/2017-12-01/compute/models.go
  services/compute/mgmt/2018-04-01/compute/models.go
  services/compute/mgmt/2018-06-01/compute/models.go
  services/compute/mgmt/2018-10-01/compute/models.go
Labels: ServicePR, review

#4033 [AutoPR] consumption/resource-manager
  profiles/latest/consumption/mgmt/consumption/consumptionapi/models.go
  profiles/latest/consumption/mgmt/consumption/models.go
  profiles/preview/consumption/mgmt/consumption/consumptionapi/models.go
  profiles/preview/consumption/mgmt/consumption/models.go
  services/consumption/mgmt/2019-01-01/consumption/aggregatedcost.go
  services/consumption/mgmt/2019-01-01/consumption/balances.go
  services/consumption/mgmt/2019-01-01/consumption/budgets.go
  services/consumption/mgmt/2019-01-01/consumption/charges.go
  services/consumption/mgmt/2019-01-01/consumption/client.go
  services/consumption/mgmt/2019-01-01/consumption/consumptionapi/interfaces.go
  services/consumption/mgmt/2019-01-01/consumption/forecasts.go
  services/consumption/mgmt/2019-01-01/consumption/marketplaces.go
  services/consumption/mgmt/2019-01-01/consumption/models.go
  services/consumption/mgmt/2019-01-01/consumption/operations.go
  services/consumption/mgmt/2019-01-01/consumption/pricesheet.go
  services/consumption/mgmt/2019-01-01/consumption/reservationrecommendations.go
  services/consumption/mgmt/2019-01-01/consumption/reservationsdetails.go
  services/consumption/mgmt/2019-01-01/consumption/reservationssummaries.go
  services/consumption/mgmt/2019-01-01/consumption/tags.go
  services/consumption/mgmt/2019-01-01/consumption/usagedetails.go
  services/consumption/mgmt/2019-01-01/consumption/version.go
Labels: ServicePR, review

#4039 [AutoPR securityinsights/resource-manager] Adding data connectors APIs
  profiles/preview/preview/securityinsight/mgmt/securityinsight/models.go
  profiles/preview/preview/securityinsight/mgmt/securityinsight/securityinsightapi/models.go
  services/preview/securityinsight/mgmt/2017-08-01-preview/securityinsight/dataconnectors.go
  services/preview/securityinsight/mgmt/2017-08-01-preview/securityinsight/models.go
  services/preview/securityinsight/mgmt/2017-08-01-preview/securityinsight/securityinsightapi/interfaces.go
Labels: RestPRMerged

#4041 [AutoPR sql/resource-manager] Updating Data Classification Swaggers.
  services/preview/sql/mgmt/2017-03-01-preview/sql/models.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/sensitivitylabels.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/sqlapi/interfaces.go
Labels: RestPRMerged, review

#4040 [AutoPR] securityinsights/resource-manager
  profiles/preview/preview/securityinsight/mgmt/securityinsight/models.go
  profiles/preview/preview/securityinsight/mgmt/securityinsight/securityinsightapi/models.go
  services/preview/securityinsight/mgmt/2017-08-01-preview/securityinsight/dataconnectors.go
  services/preview/securityinsight/mgmt/2017-08-01-preview/securityinsight/models.go
  services/preview/securityinsight/mgmt/2017-08-01-preview/securityinsight/securityinsightapi/interfaces.go
Labels: ServicePR, review

#4042 [AutoPR] sql/resource-manager
  services/preview/sql/mgmt/2017-03-01-preview/sql/models.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/sensitivitylabels.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/sqlapi/interfaces.go
Labels: ServicePR, review

#4048 [AutoPR blueprint/resource-manager] [Hub Generated] Review request for Microsoft.Blueprint to add version 2018-11-01-preview
  profiles/preview/preview/blueprint/mgmt/blueprint/blueprintapi/models.go
  profiles/preview/preview/blueprint/mgmt/blueprint/models.go
  services/preview/blueprint/mgmt/2018-11-01-preview/blueprint/artifacts.go
  services/preview/blueprint/mgmt/2018-11-01-preview/blueprint/assignmentoperations.go
  services/preview/blueprint/mgmt/2018-11-01-preview/blueprint/assignments.go
  services/preview/blueprint/mgmt/2018-11-01-preview/blueprint/blueprintapi/interfaces.go
  services/preview/blueprint/mgmt/2018-11-01-preview/blueprint/blueprints.go
  services/preview/blueprint/mgmt/2018-11-01-preview/blueprint/client.go
  services/preview/blueprint/mgmt/2018-11-01-preview/blueprint/models.go
  services/preview/blueprint/mgmt/2018-11-01-preview/blueprint/publishedartifacts.go
  services/preview/blueprint/mgmt/2018-11-01-preview/blueprint/publishedblueprints.go
  services/preview/blueprint/mgmt/2018-11-01-preview/blueprint/version.go
Labels: RestPRMerged, review

#4049 [AutoPR] blueprint/resource-manager
  profiles/preview/preview/blueprint/mgmt/blueprint/blueprintapi/models.go
  profiles/preview/preview/blueprint/mgmt/blueprint/models.go
  services/preview/blueprint/mgmt/2018-11-01-preview/blueprint/artifacts.go
  services/preview/blueprint/mgmt/2018-11-01-preview/blueprint/assignmentoperations.go
  services/preview/blueprint/mgmt/2018-11-01-preview/blueprint/assignments.go
  services/preview/blueprint/mgmt/2018-11-01-preview/blueprint/blueprintapi/interfaces.go
  services/preview/blueprint/mgmt/2018-11-01-preview/blueprint/blueprints.go
  services/preview/blueprint/mgmt/2018-11-01-preview/blueprint/client.go
  services/preview/blueprint/mgmt/2018-11-01-preview/blueprint/models.go
  services/preview/blueprint/mgmt/2018-11-01-preview/blueprint/publishedartifacts.go
  services/preview/blueprint/mgmt/2018-11-01-preview/blueprint/publishedblueprints.go
  services/preview/blueprint/mgmt/2018-11-01-preview/blueprint/version.go
Labels: ServicePR, review

#4045 [AutoPR policyinsights/resource-manager] typo: aliase -> alias
  services/preview/policyinsights/mgmt/2018-07-01-preview/policyinsights/models.go
Labels: RestPRMerged, review

#4053 [AutoPR keyvault/resource-manager] add description of access policies required condition
  services/keyvault/mgmt/2016-10-01/keyvault/models.go
  services/keyvault/mgmt/2018-02-14/keyvault/models.go
Labels: RestPRMerged, review

#4050 [AutoPR sql/resource-manager] Updated managed instance swagger and examples
  services/preview/sql/mgmt/2015-05-01-preview/sql/models.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/models.go
Labels: RestPRMerged, review

#4051 [AutoPR] policyinsights/resource-manager
  services/preview/policyinsights/mgmt/2018-07-01-preview/policyinsights/models.go
Labels: ServicePR, review

#4054 [AutoPR] keyvault/resource-manager
  services/keyvault/mgmt/2016-10-01/keyvault/models.go
  services/keyvault/mgmt/2018-02-14/keyvault/models.go
Labels: ServicePR, review

#4057 [AutoPR] sql/resource-manager
  services/preview/sql/mgmt/2015-05-01-preview/sql/models.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/models.go
Labels: ServicePR, review

#4058 [AutoPR eventgrid/data-plane] EventGrid StorageBlobCreatedEventData: Make contentLength field long instead of int to account for blob sizes greater than 2 GB.
  services/eventgrid/2018-01-01/eventgrid/models.go
Labels: RestPRMerged, review

#4003 [AutoPR eventgrid/data-plane] [Event-Grid Maps] Add Maps publisher schema to EventGrid data-plane
  profiles/latest/eventgrid/eventgrid/models.go
  profiles/preview/eventgrid/eventgrid/models.go
  services/eventgrid/2018-01-01/eventgrid/models.go
Labels: RestPRMerged, review

#4061 [AutoPR operationalinsights/resource-manager] Add gateways API
  services/operationalinsights/mgmt/2015-03-20/operationalinsights/operationalinsightsapi/interfaces.go
  services/operationalinsights/mgmt/2015-03-20/operationalinsights/workspaces.go
Labels: RestPRMerged, review

#4004 [AutoPR cognitiveservices/data-plane/ComputerVision] Analyze brands
  profiles/latest/cognitiveservices/computervision/models.go
  profiles/preview/cognitiveservices/computervision/models.go
  services/cognitiveservices/v2.0/computervision/client.go
  services/cognitiveservices/v2.0/computervision/models.go
Labels: RestPRMerged, review

#4059 [AutoPR] eventgrid/data-plane
  profiles/latest/eventgrid/eventgrid/models.go
  profiles/preview/eventgrid/eventgrid/models.go
  services/eventgrid/2018-01-01/eventgrid/models.go
Labels: ServicePR, review

#4065 [AutoPR] operationalinsights/resource-manager
  services/operationalinsights/mgmt/2015-03-20/operationalinsights/operationalinsightsapi/interfaces.go
  services/operationalinsights/mgmt/2015-03-20/operationalinsights/workspaces.go
Labels: ServicePR, review

#4066 [AutoPR] cognitiveservices/data-plane/ComputerVision
  profiles/latest/cognitiveservices/computervision/models.go
  profiles/preview/cognitiveservices/computervision/models.go
  services/cognitiveservices/v2.0/computervision/client.go
  services/cognitiveservices/v2.0/computervision/models.go
Labels: ServicePR, review

#3988 [AutoPR web/resource-manager] [App Service] Update swagger spec for ANT80
  profiles/latest/web/mgmt/web/models.go
  profiles/preview/web/mgmt/web/models.go
  services/web/mgmt/2018-02-01/web/client.go
  services/web/mgmt/2018-02-01/web/models.go
  services/web/mgmt/2018-02-01/web/recommendations.go
  services/web/mgmt/2018-02-01/web/webapi/interfaces.go
Labels: RestPRMerged, review

#4078 [AutoPR privatedns/resource-manager] Adding Private DNS Swagger spec for API version 2018-09-01
  profiles/latest/privatedns/mgmt/privatedns/models.go
  profiles/latest/privatedns/mgmt/privatedns/privatednsapi/models.go
  profiles/preview/privatedns/mgmt/privatedns/models.go
  profiles/preview/privatedns/mgmt/privatedns/privatednsapi/models.go
  services/privatedns/mgmt/2018-09-01/privatedns/client.go
  services/privatedns/mgmt/2018-09-01/privatedns/models.go
  services/privatedns/mgmt/2018-09-01/privatedns/privatednsapi/interfaces.go
  services/privatedns/mgmt/2018-09-01/privatedns/privatezones.go
  services/privatedns/mgmt/2018-09-01/privatedns/recordsets.go
  services/privatedns/mgmt/2018-09-01/privatedns/version.go
  services/privatedns/mgmt/2018-09-01/privatedns/virtualnetworklinks.go
Labels: RestPRMerged, review

#4083 run indexer on pushes to master
  .travis.yml
Labels: review

#4084 Fix indexer run in CI
  .travis.yml
  tools/indexer/main.go
Labels: review

#4089 [AutoPR securityinsights/resource-manager] typo: securityinsights/resource-manager/Microsoft.SecurityInsights
  services/preview/securityinsight/mgmt/2017-08-01-preview/securityinsight/models.go
  services/preview/securityinsight/mgmt/2017-08-01-preview/securityinsight/productsettings.go
Labels: RestPRMerged, review

#4090 [AutoPR edgegateway/resource-manager] Update API version, update data contract for Order APIs
  profiles/latest/edgegateway/mgmt/edgegateway/edgegatewayapi/models.go
  profiles/latest/edgegateway/mgmt/edgegateway/models.go
  profiles/preview/edgegateway/mgmt/edgegateway/edgegatewayapi/models.go
  profiles/preview/edgegateway/mgmt/edgegateway/models.go
  services/edgegateway/mgmt/2019-03-01/edgegateway/alerts.go
  services/edgegateway/mgmt/2019-03-01/edgegateway/bandwidthschedules.go
  services/edgegateway/mgmt/2019-03-01/edgegateway/client.go
  services/edgegateway/mgmt/2019-03-01/edgegateway/devices.go
  services/edgegateway/mgmt/2019-03-01/edgegateway/edgegatewayapi/interfaces.go
  services/edgegateway/mgmt/2019-03-01/edgegateway/jobs.go
  services/edgegateway/mgmt/2019-03-01/edgegateway/models.go
  services/edgegateway/mgmt/2019-03-01/edgegateway/operations.go
  services/edgegateway/mgmt/2019-03-01/edgegateway/operationsstatus.go
  services/edgegateway/mgmt/2019-03-01/edgegateway/orders.go
  services/edgegateway/mgmt/2019-03-01/edgegateway/roles.go
  services/edgegateway/mgmt/2019-03-01/edgegateway/shares.go
  services/edgegateway/mgmt/2019-03-01/edgegateway/storageaccountcredentials.go
  services/edgegateway/mgmt/2019-03-01/edgegateway/triggers.go
  services/edgegateway/mgmt/2019-03-01/edgegateway/users.go
  services/edgegateway/mgmt/2019-03-01/edgegateway/version.go
Labels: RestPRMerged, review

#3979 [AutoPR cognitiveservices/data-plane/AnomalyFinder] Add cognitive service AnomalyFinder
  profiles/latest/cognitiveservices/anomalyfinder/anomalyfinderapi/models.go
  profiles/latest/cognitiveservices/anomalyfinder/models.go
  profiles/preview/cognitiveservices/anomalyfinder/anomalyfinderapi/models.go
  profiles/preview/cognitiveservices/anomalyfinder/models.go
  services/cognitiveservices/v2.0/anomalyfinder/anomalyfinderapi/interfaces.go
  services/cognitiveservices/v2.0/anomalyfinder/client.go
  services/cognitiveservices/v2.0/anomalyfinder/models.go
  services/cognitiveservices/v2.0/anomalyfinder/version.go
Labels: RestPRMerged, review

#4082 [AutoPR] privatedns/resource-manager
  profiles/latest/privatedns/mgmt/privatedns/models.go
  profiles/latest/privatedns/mgmt/privatedns/privatednsapi/models.go
  profiles/preview/privatedns/mgmt/privatedns/models.go
  profiles/preview/privatedns/mgmt/privatedns/privatednsapi/models.go
  services/privatedns/mgmt/2018-09-01/privatedns/client.go
  services/privatedns/mgmt/2018-09-01/privatedns/models.go
  services/privatedns/mgmt/2018-09-01/privatedns/privatednsapi/interfaces.go
  services/privatedns/mgmt/2018-09-01/privatedns/privatezones.go
  services/privatedns/mgmt/2018-09-01/privatedns/recordsets.go
  services/privatedns/mgmt/2018-09-01/privatedns/version.go
  services/privatedns/mgmt/2018-09-01/privatedns/virtualnetworklinks.go
Labels: ServicePR, review

#4079 [AutoPR] web/resource-manager
  profiles/latest/web/mgmt/web/models.go
  profiles/preview/web/mgmt/web/models.go
  services/web/mgmt/2018-02-01/web/client.go
  services/web/mgmt/2018-02-01/web/models.go
  services/web/mgmt/2018-02-01/web/recommendations.go
  services/web/mgmt/2018-02-01/web/webapi/interfaces.go
Labels: ServicePR, review

#4101 [AutoPR] cognitiveservices/data-plane/AnomalyFinder
  profiles/latest/cognitiveservices/anomalyfinder/anomalyfinderapi/models.go
  profiles/latest/cognitiveservices/anomalyfinder/models.go
  profiles/preview/cognitiveservices/anomalyfinder/anomalyfinderapi/models.go
  profiles/preview/cognitiveservices/anomalyfinder/models.go
  services/cognitiveservices/v2.0/anomalyfinder/anomalyfinderapi/interfaces.go
  services/cognitiveservices/v2.0/anomalyfinder/client.go
  services/cognitiveservices/v2.0/anomalyfinder/models.go
  services/cognitiveservices/v2.0/anomalyfinder/version.go
Labels: ServicePR, review

#4094 [AutoPR] edgegateway/resource-manager
  profiles/latest/edgegateway/mgmt/edgegateway/edgegatewayapi/models.go
  profiles/latest/edgegateway/mgmt/edgegateway/models.go
  profiles/preview/edgegateway/mgmt/edgegateway/edgegatewayapi/models.go
  profiles/preview/edgegateway/mgmt/edgegateway/models.go
  services/edgegateway/mgmt/2019-03-01/edgegateway/alerts.go
  services/edgegateway/mgmt/2019-03-01/edgegateway/bandwidthschedules.go
  services/edgegateway/mgmt/2019-03-01/edgegateway/client.go
  services/edgegateway/mgmt/2019-03-01/edgegateway/devices.go
  services/edgegateway/mgmt/2019-03-01/edgegateway/edgegatewayapi/interfaces.go
  services/edgegateway/mgmt/2019-03-01/edgegateway/jobs.go
  services/edgegateway/mgmt/2019-03-01/edgegateway/models.go
  services/edgegateway/mgmt/2019-03-01/edgegateway/operations.go
  services/edgegateway/mgmt/2019-03-01/edgegateway/operationsstatus.go
  services/edgegateway/mgmt/2019-03-01/edgegateway/orders.go
  services/edgegateway/mgmt/2019-03-01/edgegateway/roles.go
  services/edgegateway/mgmt/2019-03-01/edgegateway/shares.go
  services/edgegateway/mgmt/2019-03-01/edgegateway/storageaccountcredentials.go
  services/edgegateway/mgmt/2019-03-01/edgegateway/triggers.go
  services/edgegateway/mgmt/2019-03-01/edgegateway/users.go
  services/edgegateway/mgmt/2019-03-01/edgegateway/version.go
Labels: ServicePR, review

#4096 [AutoPR blueprint/resource-manager] [Hub Generated] Review request for Microsoft.Blueprint to add version 2018-11-01-preview
  services/preview/blueprint/mgmt/2018-11-01-preview/blueprint/models.go
Labels: RestPRMerged, review

#4092 [AutoPR cognitiveservices/data-plane/LUIS/Authoring] [Cogsvcs] LUIS - add text to simple entity description
  services/cognitiveservices/v2.0/luis/authoring/model.go
Labels: RestPRMerged, review

#4075 [AutoPR hanaonazure/resource-manager] Add hwRevision field to HanaInstance definition
  services/preview/hanaonazure/mgmt/2017-11-03-preview/hanaonazure/models.go
Labels: RestPRMerged, review

#4105 [AutoPR] blueprint/resource-manager
  services/preview/blueprint/mgmt/2018-11-01-preview/blueprint/models.go
Labels: ServicePR, review

#4106 [AutoPR] cognitiveservices/data-plane/LUIS/Authoring
  services/cognitiveservices/v2.0/luis/authoring/model.go
Labels: ServicePR, review

#4107 [AutoPR] hanaonazure/resource-manager
  services/preview/hanaonazure/mgmt/2017-11-03-preview/hanaonazure/models.go
Labels: ServicePR, review

#4068 [AutoPR cognitiveservices/data-plane/Face] [Cogs Face] Remove Face API reference of Gender::genderless to avoid confusion.
  profiles/latest/cognitiveservices/face/models.go
  profiles/preview/cognitiveservices/face/models.go
  services/cognitiveservices/v1.0/face/models.go
Labels: RestPRMerged, review

#4097 [AutoPR machinelearning/resource-manager] Add an Operations API for Commitment Plan RP
  profiles/preview/preview/machinelearning/mgmt/commitmentplans/commitmentplansapi/models.go
  profiles/preview/preview/machinelearning/mgmt/commitmentplans/models.go
  services/preview/machinelearning/mgmt/2016-05-01-preview/commitmentplans/commitmentplansapi/interfaces.go
  services/preview/machinelearning/mgmt/2016-05-01-preview/commitmentplans/models.go
  services/preview/machinelearning/mgmt/2016-05-01-preview/commitmentplans/operations.go
Labels: RestPRMerged, review

#4073 [AutoPR cognitiveservices/data-plane/TextAnalytics] Users/laramume/addv2.1 swagger
  profiles/latest/cognitiveservices/textanalytics/models.go
  profiles/preview/cognitiveservices/textanalytics/models.go
  services/cognitiveservices/v2.1/textanalytics/client.go
  services/cognitiveservices/v2.1/textanalytics/models.go
  services/cognitiveservices/v2.1/textanalytics/textanalyticsapi/interfaces.go
  services/cognitiveservices/v2.1/textanalytics/version.go
Labels: RestPRMerged, review

#4098 [AutoPR sql/resource-manager] Update swagger file and examples with time zone parameter [DO NOT MERGE]
  services/preview/sql/mgmt/2015-05-01-preview/sql/models.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/models.go
Labels: RestPRMerged, review

#4116 [AutoPR] cognitiveservices/data-plane/Face
  profiles/latest/cognitiveservices/face/models.go
  profiles/preview/cognitiveservices/face/models.go
  services/cognitiveservices/v1.0/face/models.go
Labels: ServicePR, review

#4117 [AutoPR] machinelearning/resource-manager
  profiles/preview/preview/machinelearning/mgmt/commitmentplans/commitmentplansapi/models.go
  profiles/preview/preview/machinelearning/mgmt/commitmentplans/models.go
  services/preview/machinelearning/mgmt/2016-05-01-preview/commitmentplans/commitmentplansapi/interfaces.go
  services/preview/machinelearning/mgmt/2016-05-01-preview/commitmentplans/models.go
  services/preview/machinelearning/mgmt/2016-05-01-preview/commitmentplans/operations.go
Labels: ServicePR, review

#4134 update dependencies
  Gopkg.lock
Labels: review

#4145 [AutoPR trafficmanager/resource-manager] Add trafficmanager 2018-04 API to Go SDK
  profiles/latest/trafficmanager/mgmt/trafficmanager/models.go
  profiles/latest/trafficmanager/mgmt/trafficmanager/trafficmanagerapi/models.go
  profiles/preview/trafficmanager/mgmt/trafficmanager/models.go
  profiles/preview/trafficmanager/mgmt/trafficmanager/trafficmanagerapi/models.go
  services/trafficmanager/mgmt/2018-04-01/trafficmanager/client.go
  services/trafficmanager/mgmt/2018-04-01/trafficmanager/endpoints.go
  services/trafficmanager/mgmt/2018-04-01/trafficmanager/geographichierarchies.go
  services/trafficmanager/mgmt/2018-04-01/trafficmanager/heatmap.go
  services/trafficmanager/mgmt/2018-04-01/trafficmanager/models.go
  services/trafficmanager/mgmt/2018-04-01/trafficmanager/profiles.go
  services/trafficmanager/mgmt/2018-04-01/trafficmanager/trafficmanagerapi/interfaces.go
  services/trafficmanager/mgmt/2018-04-01/trafficmanager/usermetricskeys.go
  services/trafficmanager/mgmt/2018-04-01/trafficmanager/version.go
Labels: RestPRMerged, review

#4146 [AutoPR] trafficmanager/resource-manager
  profiles/latest/trafficmanager/mgmt/trafficmanager/models.go
  profiles/latest/trafficmanager/mgmt/trafficmanager/trafficmanagerapi/models.go
  profiles/preview/trafficmanager/mgmt/trafficmanager/models.go
  profiles/preview/trafficmanager/mgmt/trafficmanager/trafficmanagerapi/models.go
  services/trafficmanager/mgmt/2018-04-01/trafficmanager/client.go
  services/trafficmanager/mgmt/2018-04-01/trafficmanager/endpoints.go
  services/trafficmanager/mgmt/2018-04-01/trafficmanager/geographichierarchies.go
  services/trafficmanager/mgmt/2018-04-01/trafficmanager/heatmap.go
  services/trafficmanager/mgmt/2018-04-01/trafficmanager/models.go
  services/trafficmanager/mgmt/2018-04-01/trafficmanager/profiles.go
  services/trafficmanager/mgmt/2018-04-01/trafficmanager/trafficmanagerapi/interfaces.go
  services/trafficmanager/mgmt/2018-04-01/trafficmanager/usermetricskeys.go
  services/trafficmanager/mgmt/2018-04-01/trafficmanager/version.go
Labels: ServicePR, review

#4152 [AutoPR blueprint/resource-manager] Update lock modes
  profiles/preview/preview/blueprint/mgmt/blueprint/models.go
  services/preview/blueprint/mgmt/2018-11-01-preview/blueprint/models.go
Labels: RestPRMerged, review

#4154 [AutoPR web/resource-manager] Add 201 response to AppServicePlans_CreateOrUpdate
  services/web/mgmt/2016-09-01/web/appserviceplans.go
  services/web/mgmt/2018-02-01/web/appserviceplans.go
Labels: RestPRMerged, review

#3977 [AutoPR search/resource-manager] [WaitForARMFeedback] Add api get_services_by_subscription of Azure Search
  services/search/mgmt/2015-08-19/search/searchapi/interfaces.go
  services/search/mgmt/2015-08-19/search/services.go
Labels: RestPRMerged, review

#4151 [AutoPR mixedreality/resource-manager] Add mixedreality 2019-02-28 API version to Go SDK
  profiles/preview/preview/mixedreality/mgmt/mixedreality/mixedrealityapi/models.go
  profiles/preview/preview/mixedreality/mgmt/mixedreality/models.go
  services/preview/mixedreality/mgmt/2019-02-28/mixedreality/client.go
  services/preview/mixedreality/mgmt/2019-02-28/mixedreality/mixedrealityapi/interfaces.go
  services/preview/mixedreality/mgmt/2019-02-28/mixedreality/models.go
  services/preview/mixedreality/mgmt/2019-02-28/mixedreality/operations.go
  services/preview/mixedreality/mgmt/2019-02-28/mixedreality/spatialanchorsaccounts.go
  services/preview/mixedreality/mgmt/2019-02-28/mixedreality/version.go
Labels: RestPRMerged, review

#4160 [AutoPR] mixedreality/resource-manager
  profiles/preview/preview/mixedreality/mgmt/mixedreality/mixedrealityapi/models.go
  profiles/preview/preview/mixedreality/mgmt/mixedreality/models.go
  services/preview/mixedreality/mgmt/2019-02-28/mixedreality/client.go
  services/preview/mixedreality/mgmt/2019-02-28/mixedreality/mixedrealityapi/interfaces.go
  services/preview/mixedreality/mgmt/2019-02-28/mixedreality/models.go
  services/preview/mixedreality/mgmt/2019-02-28/mixedreality/operations.go
  services/preview/mixedreality/mgmt/2019-02-28/mixedreality/spatialanchorsaccounts.go
  services/preview/mixedreality/mgmt/2019-02-28/mixedreality/version.go
Labels: ServicePR, review

#4156 [AutoPR] search/resource-manager
  services/search/mgmt/2015-08-19/search/searchapi/interfaces.go
  services/search/mgmt/2015-08-19/search/services.go
Labels: ServicePR, review

#4169 remove go 1.9 from CI and add 1.12
  .travis.yml
Labels: review

#4072 [AutoPR imagebuilder/resource-manager] Add private preview API for Azure Image Builder
  profiles/preview/preview/virtualmachineimagebuilder/mgmt/virtualmachineimagebuilder/models.go
  profiles/preview/preview/virtualmachineimagebuilder/mgmt/virtualmachineimagebuilder/virtualmachineimagebuilderapi/models.go
  services/preview/virtualmachineimagebuilder/mgmt/2018-02-01-preview/virtualmachineimagebuilder/client.go
  services/preview/virtualmachineimagebuilder/mgmt/2018-02-01-preview/virtualmachineimagebuilder/models.go
  services/preview/virtualmachineimagebuilder/mgmt/2018-02-01-preview/virtualmachineimagebuilder/operations.go
  services/preview/virtualmachineimagebuilder/mgmt/2018-02-01-preview/virtualmachineimagebuilder/version.go
  services/preview/virtualmachineimagebuilder/mgmt/2018-02-01-preview/virtualmachineimagebuilder/virtualmachineimagebuilderapi/interfaces.go
  services/preview/virtualmachineimagebuilder/mgmt/2018-02-01-preview/virtualmachineimagebuilder/virtualmachineimagetemplate.go
Labels: RestPRMerged, review

#4159 [AutoPR cdn/resource-manager] Enable SSL on custom domains for CDN using users certificate or CDN managed c…
  profiles/latest/cdn/mgmt/cdn/models.go
  profiles/preview/cdn/mgmt/cdn/models.go
  services/cdn/mgmt/2017-10-12/cdn/cdnapi/interfaces.go
  services/cdn/mgmt/2017-10-12/cdn/customdomains.go
  services/cdn/mgmt/2017-10-12/cdn/models.go
Labels: RestPRMerged, review

#4157 [AutoPR cognitiveservices/data-plane/TranslatorText] Translator Text API V3
  profiles/latest/cognitiveservices/translatortext/models.go
  profiles/latest/cognitiveservices/translatortext/translatortextapi/models.go
  profiles/preview/cognitiveservices/translatortext/models.go
  profiles/preview/cognitiveservices/translatortext/translatortextapi/models.go
  services/cognitiveservices/v3.0/translatortext/client.go
  services/cognitiveservices/v3.0/translatortext/models.go
  services/cognitiveservices/v3.0/translatortext/translator.go
  services/cognitiveservices/v3.0/translatortext/translatortextapi/interfaces.go
  services/cognitiveservices/v3.0/translatortext/version.go
Labels: RestPRMerged, review

#4165 [AutoPR mariadb/resource-manager] Update MariaDB api version
  profiles/latest/stable/mariadb/mgmt/mariadb/mariadbapi/models.go
  profiles/latest/stable/mariadb/mgmt/mariadb/models.go
  profiles/preview/stable/mariadb/mgmt/mariadb/mariadbapi/models.go
  profiles/preview/stable/mariadb/mgmt/mariadb/models.go
  services/stable/mariadb/mgmt/2018-06-01/mariadb/checknameavailability.go
  services/stable/mariadb/mgmt/2018-06-01/mariadb/client.go
  services/stable/mariadb/mgmt/2018-06-01/mariadb/configurations.go
  services/stable/mariadb/mgmt/2018-06-01/mariadb/databases.go
  services/stable/mariadb/mgmt/2018-06-01/mariadb/firewallrules.go
  services/stable/mariadb/mgmt/2018-06-01/mariadb/locationbasedperformancetier.go
  services/stable/mariadb/mgmt/2018-06-01/mariadb/logfiles.go
  services/stable/mariadb/mgmt/2018-06-01/mariadb/mariadbapi/interfaces.go
  services/stable/mariadb/mgmt/2018-06-01/mariadb/models.go
  services/stable/mariadb/mgmt/2018-06-01/mariadb/operations.go
  services/stable/mariadb/mgmt/2018-06-01/mariadb/replicas.go
  services/stable/mariadb/mgmt/2018-06-01/mariadb/servers.go
  services/stable/mariadb/mgmt/2018-06-01/mariadb/serversecurityalertpolicies.go
  services/stable/mariadb/mgmt/2018-06-01/mariadb/version.go
  services/stable/mariadb/mgmt/2018-06-01/mariadb/virtualnetworkrules.go
Labels: RestPRMerged, review

#4150 [AutoPR sql/resource-manager] Adding Swagger and examples for VirtualClusters operation group
  services/preview/sql/mgmt/2015-05-01-preview/sql/models.go
  services/preview/sql/mgmt/2015-05-01-preview/sql/sqlapi/interfaces.go
  services/preview/sql/mgmt/2015-05-01-preview/sql/virtualclusters.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/models.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/sqlapi/interfaces.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/virtualclusters.go
Labels: RestPRMerged, review

#4148 [AutoPR security/resource-manager] Security - Updating API versions of alerts and pricing types
  profiles/preview/preview/security/mgmt/security/models.go
  profiles/preview/preview/security/mgmt/security/securityapi/models.go
  services/preview/security/mgmt/v1.0/security/advancedthreatprotection.go
  services/preview/security/mgmt/v1.0/security/alerts.go
  services/preview/security/mgmt/v1.0/security/allowedconnections.go
  services/preview/security/mgmt/v1.0/security/autoprovisioningsettings.go
  services/preview/security/mgmt/v1.0/security/client.go
  services/preview/security/mgmt/v1.0/security/compliances.go
  services/preview/security/mgmt/v1.0/security/contacts.go
  services/preview/security/mgmt/v1.0/security/discoveredsecuritysolutions.go
  services/preview/security/mgmt/v1.0/security/externalsecuritysolutions.go
  services/preview/security/mgmt/v1.0/security/informationprotectionpolicies.go
  services/preview/security/mgmt/v1.0/security/jitnetworkaccesspolicies.go
  services/preview/security/mgmt/v1.0/security/locations.go
  services/preview/security/mgmt/v1.0/security/models.go
  services/preview/security/mgmt/v1.0/security/operations.go
  services/preview/security/mgmt/v1.0/security/pricings.go
  services/preview/security/mgmt/v1.0/security/securityapi/interfaces.go
  services/preview/security/mgmt/v1.0/security/settings.go
  services/preview/security/mgmt/v1.0/security/tasks.go
  services/preview/security/mgmt/v1.0/security/topology.go
  services/preview/security/mgmt/v1.0/security/version.go
  services/preview/security/mgmt/v1.0/security/workspacesettings.go
  services/preview/security/mgmt/v2.0/security/advancedthreatprotection.go
  services/preview/security/mgmt/v2.0/security/alerts.go
  services/preview/security/mgmt/v2.0/security/allowedconnections.go
  services/preview/security/mgmt/v2.0/security/autoprovisioningsettings.go
  services/preview/security/mgmt/v2.0/security/client.go
  services/preview/security/mgmt/v2.0/security/compliances.go
  services/preview/security/mgmt/v2.0/security/contacts.go
  services/preview/security/mgmt/v2.0/security/discoveredsecuritysolutions.go
  services/preview/security/mgmt/v2.0/security/externalsecuritysolutions.go
  services/preview/security/mgmt/v2.0/security/informationprotectionpolicies.go
  services/preview/security/mgmt/v2.0/security/jitnetworkaccesspolicies.go
  services/preview/security/mgmt/v2.0/security/locations.go
  services/preview/security/mgmt/v2.0/security/models.go
  services/preview/security/mgmt/v2.0/security/operations.go
  services/preview/security/mgmt/v2.0/security/pricings.go
  services/preview/security/mgmt/v2.0/security/securityapi/interfaces.go
  services/preview/security/mgmt/v2.0/security/settings.go
  services/preview/security/mgmt/v2.0/security/tasks.go
  services/preview/security/mgmt/v2.0/security/topology.go
  services/preview/security/mgmt/v2.0/security/version.go
  services/preview/security/mgmt/v2.0/security/workspacesettings.go
Labels: RestPRMerged, review

#4179 [AutoPR] cdn/resource-manager
  profiles/latest/cdn/mgmt/cdn/models.go
  profiles/preview/cdn/mgmt/cdn/models.go
  services/cdn/mgmt/2017-10-12/cdn/cdnapi/interfaces.go
  services/cdn/mgmt/2017-10-12/cdn/customdomains.go
  services/cdn/mgmt/2017-10-12/cdn/models.go
Labels: ServicePR, review

#4188 [AutoPR security/resource-manager] Security - Updating API versions of alerts and pricing types
  services/preview/security/mgmt/v1.0/security/advancedthreatprotection.go
  services/preview/security/mgmt/v1.0/security/alerts.go
  services/preview/security/mgmt/v1.0/security/allowedconnections.go
  services/preview/security/mgmt/v1.0/security/autoprovisioningsettings.go
  services/preview/security/mgmt/v1.0/security/client.go
  services/preview/security/mgmt/v1.0/security/compliances.go
  services/preview/security/mgmt/v1.0/security/contacts.go
  services/preview/security/mgmt/v1.0/security/discoveredsecuritysolutions.go
  services/preview/security/mgmt/v1.0/security/externalsecuritysolutions.go
  services/preview/security/mgmt/v1.0/security/informationprotectionpolicies.go
  services/preview/security/mgmt/v1.0/security/jitnetworkaccesspolicies.go
  services/preview/security/mgmt/v1.0/security/locations.go
  services/preview/security/mgmt/v1.0/security/models.go
  services/preview/security/mgmt/v1.0/security/operations.go
  services/preview/security/mgmt/v1.0/security/pricings.go
  services/preview/security/mgmt/v1.0/security/securityapi/interfaces.go
  services/preview/security/mgmt/v1.0/security/settings.go
  services/preview/security/mgmt/v1.0/security/tasks.go
  services/preview/security/mgmt/v1.0/security/topology.go
  services/preview/security/mgmt/v1.0/security/version.go
  services/preview/security/mgmt/v1.0/security/workspacesettings.go
  services/preview/security/mgmt/v2.0/security/advancedthreatprotection.go
  services/preview/security/mgmt/v2.0/security/alerts.go
  services/preview/security/mgmt/v2.0/security/allowedconnections.go
  services/preview/security/mgmt/v2.0/security/autoprovisioningsettings.go
  services/preview/security/mgmt/v2.0/security/client.go
  services/preview/security/mgmt/v2.0/security/compliances.go
  services/preview/security/mgmt/v2.0/security/contacts.go
  services/preview/security/mgmt/v2.0/security/discoveredsecuritysolutions.go
  services/preview/security/mgmt/v2.0/security/externalsecuritysolutions.go
  services/preview/security/mgmt/v2.0/security/informationprotectionpolicies.go
  services/preview/security/mgmt/v2.0/security/jitnetworkaccesspolicies.go
  services/preview/security/mgmt/v2.0/security/locations.go
  services/preview/security/mgmt/v2.0/security/models.go
  services/preview/security/mgmt/v2.0/security/operations.go
  services/preview/security/mgmt/v2.0/security/pricings.go
  services/preview/security/mgmt/v2.0/security/securityapi/interfaces.go
  services/preview/security/mgmt/v2.0/security/settings.go
  services/preview/security/mgmt/v2.0/security/tasks.go
  services/preview/security/mgmt/v2.0/security/topology.go
  services/preview/security/mgmt/v2.0/security/version.go
  services/preview/security/mgmt/v2.0/security/workspacesettings.go
Labels: RestPRMerged, review

#4184 [AutoPR] cognitiveservices/data-plane/TranslatorText
  profiles/latest/cognitiveservices/translatortext/models.go
  profiles/latest/cognitiveservices/translatortext/translatortextapi/models.go
  profiles/preview/cognitiveservices/translatortext/models.go
  profiles/preview/cognitiveservices/translatortext/translatortextapi/models.go
  services/cognitiveservices/v3.0/translatortext/client.go
  services/cognitiveservices/v3.0/translatortext/models.go
  services/cognitiveservices/v3.0/translatortext/translator.go
  services/cognitiveservices/v3.0/translatortext/translatortextapi/interfaces.go
  services/cognitiveservices/v3.0/translatortext/version.go
Labels: ServicePR, review

#4173 remove Go 1.9 from CI and add 1.12
  .travis.yml
Labels: review

#4190 [AutoPR mariadb/resource-manager] fix Go SDK package path for mariadb stable release
  profiles/latest/mariadb/mgmt/mariadb/mariadbapi/models.go
  profiles/latest/mariadb/mgmt/mariadb/models.go
  profiles/preview/mariadb/mgmt/mariadb/mariadbapi/models.go
  profiles/preview/mariadb/mgmt/mariadb/models.go
  services/mariadb/mgmt/2018-06-01/mariadb/checknameavailability.go
  services/mariadb/mgmt/2018-06-01/mariadb/client.go
  services/mariadb/mgmt/2018-06-01/mariadb/configurations.go
  services/mariadb/mgmt/2018-06-01/mariadb/databases.go
  services/mariadb/mgmt/2018-06-01/mariadb/firewallrules.go
  services/mariadb/mgmt/2018-06-01/mariadb/locationbasedperformancetier.go
  services/mariadb/mgmt/2018-06-01/mariadb/logfiles.go
  services/mariadb/mgmt/2018-06-01/mariadb/mariadbapi/interfaces.go
  services/mariadb/mgmt/2018-06-01/mariadb/models.go
  services/mariadb/mgmt/2018-06-01/mariadb/operations.go
  services/mariadb/mgmt/2018-06-01/mariadb/replicas.go
  services/mariadb/mgmt/2018-06-01/mariadb/servers.go
  services/mariadb/mgmt/2018-06-01/mariadb/serversecurityalertpolicies.go
  services/mariadb/mgmt/2018-06-01/mariadb/version.go
  services/mariadb/mgmt/2018-06-01/mariadb/virtualnetworkrules.go
Labels: RestPRMerged, review

#4177 [AutoPR iothub/resource-manager] changes to improve documentation of endpoint health statuses for routing
  services/iothub/mgmt/2018-04-01/devices/models.go
  services/preview/iothub/mgmt/2018-12-01-preview/devices/models.go
Labels: RestPRMerged, review
