Repository Azure/azure-sdk-for-go, pull requests merged in 2019-03, with the labels that each got.

#4191 [AutoPR] mariadb/resource-manager
  profiles/latest/mariadb/mgmt/mariadb/mariadbapi/models.go
  profiles/latest/mariadb/mgmt/mariadb/models.go
  profiles/preview/mariadb/mgmt/mariadb/mariadbapi/models.go
  profiles/preview/mariadb/mgmt/mariadb/models.go
  services/mariadb/mgmt/2018-06-01/mariadb/checknameavailability.go
  services/mariadb/mgmt/2018-06-01/mariadb/client.go
  services/mariadb/mgmt/2018-06-01/mariadb/configurations.go
  services/mariadb/mgmt/2018-06-01/mariadb/databases.go
  services/mariadb/mgmt/2018-06-01/mariadb/firewallrules.go
  services/mariadb/mgmt/2018-06-01/mariadb/locationbasedperformancetier.go
  services/mariadb/mgmt/2018-06-01/mariadb/logfiles.go
  services/mariadb/mgmt/2018-06-01/mariadb/mariadbapi/interfaces.go
  services/mariadb/mgmt/2018-06-01/mariadb/models.go
  services/mariadb/mgmt/2018-06-01/mariadb/operations.go
  services/mariadb/mgmt/2018-06-01/mariadb/replicas.go
  services/mariadb/mgmt/2018-06-01/mariadb/servers.go
  services/mariadb/mgmt/2018-06-01/mariadb/serversecurityalertpolicies.go
  services/mariadb/mgmt/2018-06-01/mariadb/version.go
  services/mariadb/mgmt/2018-06-01/mariadb/virtualnetworkrules.go
Labels: ServicePR, review

#4192 [AutoPR] iothub/resource-manager
  services/iothub/mgmt/2018-04-01/devices/models.go
  services/preview/iothub/mgmt/2018-12-01-preview/devices/models.go
Labels: ServicePR, review

#4194 [AutoPR netapp/resource-manager] add netapp to Go SDK
  profiles/preview/preview/netapp/mgmt/netapp/models.go
  profiles/preview/preview/netapp/mgmt/netapp/netappapi/models.go
  services/preview/netapp/mgmt/2017-08-15/netapp/accounts.go
  services/preview/netapp/mgmt/2017-08-15/netapp/client.go
  services/preview/netapp/mgmt/2017-08-15/netapp/models.go
  services/preview/netapp/mgmt/2017-08-15/netapp/mounttargets.go
  services/preview/netapp/mgmt/2017-08-15/netapp/netappapi/interfaces.go
  services/preview/netapp/mgmt/2017-08-15/netapp/operations.go
  services/preview/netapp/mgmt/2017-08-15/netapp/pools.go
  services/preview/netapp/mgmt/2017-08-15/netapp/snapshots.go
  services/preview/netapp/mgmt/2017-08-15/netapp/version.go
  services/preview/netapp/mgmt/2017-08-15/netapp/volumes.go
Labels: RestPRMerged, review

#4181 [AutoPR monitor/resource-manager] new application insignts api version for unified schema in action
  services/preview/monitor/mgmt/2018-03-01/insights/actiongroups.go
  services/preview/monitor/mgmt/2018-03-01/insights/models.go
Labels: RestPRMerged, review

#4186 [AutoPR] sql/resource-manager
  services/preview/sql/mgmt/2015-05-01-preview/sql/models.go
  services/preview/sql/mgmt/2015-05-01-preview/sql/sqlapi/interfaces.go
  services/preview/sql/mgmt/2015-05-01-preview/sql/virtualclusters.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/models.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/sqlapi/interfaces.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/virtualclusters.go
Labels: ServicePR, review

#4195 [AutoPR] netapp/resource-manager
  profiles/preview/preview/netapp/mgmt/netapp/models.go
  profiles/preview/preview/netapp/mgmt/netapp/netappapi/models.go
  services/preview/netapp/mgmt/2017-08-15/netapp/accounts.go
  services/preview/netapp/mgmt/2017-08-15/netapp/client.go
  services/preview/netapp/mgmt/2017-08-15/netapp/models.go
  services/preview/netapp/mgmt/2017-08-15/netapp/mounttargets.go
  services/preview/netapp/mgmt/2017-08-15/netapp/netappapi/interfaces.go
  services/preview/netapp/mgmt/2017-08-15/netapp/operations.go
  services/preview/netapp/mgmt/2017-08-15/netapp/pools.go
  services/preview/netapp/mgmt/2017-08-15/netapp/snapshots.go
  services/preview/netapp/mgmt/2017-08-15/netapp/version.go
  services/preview/netapp/mgmt/2017-08-15/netapp/volumes.go
Labels: ServicePR, review

#4200 [AutoPR eventgrid/data-plane] Added Azure App Configuration event data schema.
  profiles/latest/eventgrid/eventgrid/models.go
  profiles/preview/eventgrid/eventgrid/models.go
  services/eventgrid/2018-01-01/eventgrid/models.go
Labels: RestPRMerged, review

#4199 [AutoPR] monitor/resource-manager
  services/preview/monitor/mgmt/2018-03-01/insights/actiongroups.go
  services/preview/monitor/mgmt/2018-03-01/insights/models.go
Labels: ServicePR, review

#3885 [AutoPR adhybridhealthservice/resource-manager] Dev adhybridhealthservice microsoft.ad hybrid health service 2014 01 01 binilkk
  profiles/latest/adhybridhealthservice/mgmt/adhybridhealthservice/models.go
  profiles/preview/adhybridhealthservice/mgmt/adhybridhealthservice/models.go
  services/adhybridhealthservice/mgmt/2014-01-01/adhybridhealthservice/adhybridhealthserviceapi/interfaces.go
  services/adhybridhealthservice/mgmt/2014-01-01/adhybridhealthservice/models.go
  services/adhybridhealthservice/mgmt/2014-01-01/adhybridhealthservice/services.go
Labels: RestPRMerged, review

#4201 [AutoPR] eventgrid/data-plane
  profiles/latest/eventgrid/eventgrid/models.go
  profiles/preview/eventgrid/eventgrid/models.go
  services/eventgrid/2018-01-01/eventgrid/models.go
Labels: ServicePR, review

#4206 [AutoPR] adhybridhealthservice/resource-manager
  profiles/latest/adhybridhealthservice/mgmt/adhybridhealthservice/models.go
  profiles/preview/adhybridhealthservice/mgmt/adhybridhealthservice/models.go
  services/adhybridhealthservice/mgmt/2014-01-01/adhybridhealthservice/adhybridhealthserviceapi/interfaces.go
  services/adhybridhealthservice/mgmt/2014-01-01/adhybridhealthservice/models.go
  services/adhybridhealthservice/mgmt/2014-01-01/adhybridhealthservice/services.go
Labels: ServicePR, review

#4212 [AutoPR netapp/resource-manager] Bringing consistency between to "ResourceGroup" definition
  services/preview/netapp/mgmt/2017-08-15/netapp/accounts.go
  services/preview/netapp/mgmt/2017-08-15/netapp/mounttargets.go
  services/preview/netapp/mgmt/2017-08-15/netapp/netappapi/interfaces.go
  services/preview/netapp/mgmt/2017-08-15/netapp/pools.go
  services/preview/netapp/mgmt/2017-08-15/netapp/snapshots.go
  services/preview/netapp/mgmt/2017-08-15/netapp/volumes.go
Labels: RestPRMerged

#4219 [AutoPR marketplaceordering/resource-manager] Add missing MarketplaceOrdering operations to swagger
  profiles/latest/marketplaceordering/mgmt/marketplaceordering/models.go
  profiles/preview/marketplaceordering/mgmt/marketplaceordering/models.go
  services/marketplaceordering/mgmt/2015-06-01/marketplaceordering/marketplaceagreements.go
  services/marketplaceordering/mgmt/2015-06-01/marketplaceordering/marketplaceorderingapi/interfaces.go
  services/marketplaceordering/mgmt/2015-06-01/marketplaceordering/models.go
Labels: RestPRMerged, review

#4216 [AutoPR web/resource-manager] Fix Hosting Environment Network Dependencies pagination
  profiles/latest/web/mgmt/web/models.go
  profiles/preview/web/mgmt/web/models.go
  services/web/mgmt/2018-02-01/web/appserviceenvironments.go
  services/web/mgmt/2018-02-01/web/models.go
  services/web/mgmt/2018-02-01/web/webapi/interfaces.go
Labels: RestPRMerged, review

#4220 [AutoPR containerservice/resource-manager] Add regex validation for ManagedClusterAgentPoolProfile.name
  services/containerservice/mgmt/2018-03-31/containerservice/models.go
  services/preview/containerservice/mgmt/2018-08-01-preview/containerservice/models.go
  services/preview/containerservice/mgmt/2018-09-30-preview/containerservice/models.go
Labels: RestPRMerged, review

#4209 [AutoPR cognitiveservices/data-plane/ComputerVision] [Computer Vision] Add read to CV OCR API.
  profiles/latest/cognitiveservices/computervision/models.go
  profiles/preview/cognitiveservices/computervision/models.go
  services/cognitiveservices/v2.0/computervision/client.go
  services/cognitiveservices/v2.0/computervision/computervisionapi/interfaces.go
  services/cognitiveservices/v2.0/computervision/models.go
Labels: RestPRMerged, review

#4214 [AutoPR network/resource-manager] Add support for Local Sku
  profiles/latest/network/mgmt/network/models.go
  profiles/preview/network/mgmt/network/models.go
  services/network/mgmt/2018-12-01/network/models.go
Labels: RestPRMerged, review

#4213 [AutoPR] netapp/resource-manager
  services/preview/netapp/mgmt/2017-08-15/netapp/accounts.go
  services/preview/netapp/mgmt/2017-08-15/netapp/mounttargets.go
  services/preview/netapp/mgmt/2017-08-15/netapp/netappapi/interfaces.go
  services/preview/netapp/mgmt/2017-08-15/netapp/pools.go
  services/preview/netapp/mgmt/2017-08-15/netapp/snapshots.go
  services/preview/netapp/mgmt/2017-08-15/netapp/volumes.go
Labels: ServicePR, review

#4221 [AutoPR] marketplaceordering/resource-manager
  profiles/latest/marketplaceordering/mgmt/marketplaceordering/models.go
  profiles/preview/marketplaceordering/mgmt/marketplaceordering/models.go
  services/marketplaceordering/mgmt/2015-06-01/marketplaceordering/marketplaceagreements.go
  services/marketplaceordering/mgmt/2015-06-01/marketplaceordering/marketplaceorderingapi/interfaces.go
  services/marketplaceordering/mgmt/2015-06-01/marketplaceordering/models.go
Labels: ServicePR, review

#4223 [AutoPR] cognitiveservices/data-plane/ComputerVision
  profiles/latest/cognitiveservices/computervision/models.go
  profiles/preview/cognitiveservices/computervision/models.go
  services/cognitiveservices/v2.0/computervision/client.go
  services/cognitiveservices/v2.0/computervision/computervisionapi/interfaces.go
  services/cognitiveservices/v2.0/computervision/models.go
Labels: ServicePR, review

#4215 [AutoPR search/resource-manager] Azure Search: Resource Manager: Support 'None' Identity type
  profiles/latest/search/mgmt/search/models.go
  profiles/preview/search/mgmt/search/models.go
  services/search/mgmt/2015-08-19/search/models.go
Labels: RestPRMerged, review

#4224 [AutoPR datalake-analytics/data-plane] [ADLA] - Catalog - Add stream path to USqlTableFragment
  services/datalake/analytics/2016-11-01-preview/catalog/models.go
Labels: RestPRMerged, review

#4203 [AutoPR consumption/resource-manager] [Hub Generated] Review request for Microsoft.Consumption to add version 2019-01-01
  services/consumption/mgmt/2018-10-01/consumption/consumptionapi/interfaces.go
  services/consumption/mgmt/2018-10-01/consumption/models.go
  services/consumption/mgmt/2018-10-01/consumption/tenants.go
  services/consumption/mgmt/2019-01-01/consumption/budgets.go
Labels: RestPRMerged, review

#4230 [AutoPR] search/resource-manager
  profiles/latest/search/mgmt/search/models.go
  profiles/preview/search/mgmt/search/models.go
  services/search/mgmt/2015-08-19/search/models.go
Labels: ServicePR, review

#4241 [AutoPR eventgrid/resource-manager] Azure Event Grid: Add 2019-02-01-preview tags for Ruby and Go readme files
  profiles/preview/preview/eventgrid/mgmt/eventgrid/eventgridapi/models.go
  profiles/preview/preview/eventgrid/mgmt/eventgrid/models.go
  services/preview/eventgrid/mgmt/2019-02-01-preview/eventgrid/client.go
  services/preview/eventgrid/mgmt/2019-02-01-preview/eventgrid/domains.go
  services/preview/eventgrid/mgmt/2019-02-01-preview/eventgrid/domaintopics.go
  services/preview/eventgrid/mgmt/2019-02-01-preview/eventgrid/eventgridapi/interfaces.go
  services/preview/eventgrid/mgmt/2019-02-01-preview/eventgrid/eventsubscriptions.go
  services/preview/eventgrid/mgmt/2019-02-01-preview/eventgrid/models.go
  services/preview/eventgrid/mgmt/2019-02-01-preview/eventgrid/operations.go
  services/preview/eventgrid/mgmt/2019-02-01-preview/eventgrid/topics.go
  services/preview/eventgrid/mgmt/2019-02-01-preview/eventgrid/topictypes.go
  services/preview/eventgrid/mgmt/2019-02-01-preview/eventgrid/version.go
Labels: RestPRMerged, review

#4193 [AutoPR batch/data-plane] Update some descriptions.
  services/batch/2018-12-01.8.0/batch/models.go
Labels: RestPRMerged, review

#4231 [AutoPR] datalake-analytics/data-plane
  services/datalake/analytics/2016-11-01-preview/catalog/models.go
Labels: ServicePR, review

#4242 [AutoPR] eventgrid/resource-manager
  profiles/preview/preview/eventgrid/mgmt/eventgrid/eventgridapi/models.go
  profiles/preview/preview/eventgrid/mgmt/eventgrid/models.go
  services/preview/eventgrid/mgmt/2019-02-01-preview/eventgrid/client.go
  services/preview/eventgrid/mgmt/2019-02-01-preview/eventgrid/domains.go
  services/preview/eventgrid/mgmt/2019-02-01-preview/eventgrid/domaintopics.go
  services/preview/eventgrid/mgmt/2019-02-01-preview/eventgrid/eventgridapi/interfaces.go
  services/preview/eventgrid/mgmt/2019-02-01-preview/eventgrid/eventsubscriptions.go
  services/preview/eventgrid/mgmt/2019-02-01-preview/eventgrid/models.go
  services/preview/eventgrid/mgmt/2019-02-01-preview/eventgrid/operations.go
  services/preview/eventgrid/mgmt/2019-02-01-preview/eventgrid/topics.go
  services/preview/eventgrid/mgmt/2019-02-01-preview/eventgrid/topictypes.go
  services/preview/eventgrid/mgmt/2019-02-01-preview/eventgrid/version.go
Labels: ServicePR, review

#4228 [AutoPR compute/resource-manager] update description.
  services/preview/compute/mgmt/2016-04-30-preview/compute/models.go
Labels: RestPRMerged, review

#4243 [AutoPR] batch/data-plane
  services/batch/2018-12-01.8.0/batch/models.go
Labels: ServicePR, review

#4244 [AutoPR eventhub/resource-manager] EventHub: added VNet API to 2017 stable version
  profiles/latest/eventhub/mgmt/eventhub/models.go
  profiles/preview/eventhub/mgmt/eventhub/models.go
  services/eventhub/mgmt/2017-04-01/eventhub/eventhubapi/interfaces.go
  services/eventhub/mgmt/2017-04-01/eventhub/models.go
  services/eventhub/mgmt/2017-04-01/eventhub/namespaces.go
Labels: RestPRMerged, review

#4256 [AutoPR eventhub/resource-manager] EventHub : corrected typo
  services/eventhub/mgmt/2017-04-01/eventhub/namespaces.go
Labels: RestPRMerged

#4257 Remove `dep ensure` from swagger-to-sdk
  swagger_to_sdk_config.json
  tools/profileBuilder/Gopkg.lock
  tools/profileBuilder/Gopkg.toml
  tools/profileBuilder/README.md
Labels: review

#4260 [AutoPR edgegateway/resource-manager] Microsoft.DataBoxEdge RP: Corrected comments of trigger and extendedinfo APIs, corrected examples
  services/edgegateway/mgmt/2019-03-01/edgegateway/devices.go
  services/edgegateway/mgmt/2019-03-01/edgegateway/edgegatewayapi/interfaces.go
  services/edgegateway/mgmt/2019-03-01/edgegateway/models.go
  services/edgegateway/mgmt/2019-03-01/edgegateway/orders.go
  services/edgegateway/mgmt/2019-03-01/edgegateway/triggers.go
Labels: RestPRMerged, review

#4273 [AutoPR sql/resource-manager] Added List Policies API to SecurityAlerts
  services/preview/sql/mgmt/2015-05-01-preview/sql/models.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/models.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/serversecurityalertpolicies.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/sqlapi/interfaces.go
Labels: RestPRMerged, review

#4060 [AutoPR graphrbac/data-plane] [graphrbac]: fix bugs in permission grant apis
  profiles/latest/graphrbac/graphrbac/graphrbacapi/models.go
  profiles/latest/graphrbac/graphrbac/models.go
  profiles/preview/graphrbac/graphrbac/graphrbacapi/models.go
  profiles/preview/graphrbac/graphrbac/models.go
  services/graphrbac/1.6/graphrbac/applications.go
  services/graphrbac/1.6/graphrbac/graphrbacapi/interfaces.go
  services/graphrbac/1.6/graphrbac/models.go
  services/graphrbac/1.6/graphrbac/oauth2.go
  services/graphrbac/1.6/graphrbac/oauth2permissiongrant.go
Labels: RestPRMerged, review

#4271 [AutoPR monitor/resource-manager] Add insights 2019-03-01 package to Go SDK
  profiles/preview/preview/monitor/mgmt/insights/insightsapi/models.go
  profiles/preview/preview/monitor/mgmt/insights/models.go
  services/preview/monitor/mgmt/2019-03-01/insights/actiongroups.go
  services/preview/monitor/mgmt/2019-03-01/insights/activitylogalerts.go
  services/preview/monitor/mgmt/2019-03-01/insights/activitylogs.go
  services/preview/monitor/mgmt/2019-03-01/insights/alertruleincidents.go
  services/preview/monitor/mgmt/2019-03-01/insights/alertrules.go
  services/preview/monitor/mgmt/2019-03-01/insights/autoscalesettings.go
  services/preview/monitor/mgmt/2019-03-01/insights/client.go
  services/preview/monitor/mgmt/2019-03-01/insights/diagnosticsettings.go
  services/preview/monitor/mgmt/2019-03-01/insights/diagnosticsettingscategory.go
  services/preview/monitor/mgmt/2019-03-01/insights/eventcategories.go
  services/preview/monitor/mgmt/2019-03-01/insights/insightsapi/interfaces.go
  services/preview/monitor/mgmt/2019-03-01/insights/logprofiles.go
  services/preview/monitor/mgmt/2019-03-01/insights/metricalerts.go
  services/preview/monitor/mgmt/2019-03-01/insights/metricalertsstatus.go
  services/preview/monitor/mgmt/2019-03-01/insights/metricbaseline.go
  services/preview/monitor/mgmt/2019-03-01/insights/metricdefinitions.go
  services/preview/monitor/mgmt/2019-03-01/insights/metricnamespaces.go
  services/preview/monitor/mgmt/2019-03-01/insights/metrics.go
  services/preview/monitor/mgmt/2019-03-01/insights/models.go
  services/preview/monitor/mgmt/2019-03-01/insights/operations.go
  services/preview/monitor/mgmt/2019-03-01/insights/scheduledqueryrules.go
  services/preview/monitor/mgmt/2019-03-01/insights/tenantactivitylogs.go
  services/preview/monitor/mgmt/2019-03-01/insights/version.go
  services/preview/monitor/mgmt/2019-03-01/insights/vminsights.go
Labels: RestPRMerged, review

#4276 [AutoPR edgegateway/resource-manager] typo: upto -> up to
  services/edgegateway/mgmt/2019-03-01/edgegateway/models.go
Labels: RestPRMerged, review

#4275 [AutoPR graphrbac/data-plane] typo: graphrbac/data-plane/Microsoft.GraphRbac/stable/1.6
  services/graphrbac/1.6/graphrbac/models.go
Labels: RestPRMerged, review

#4277 [AutoPR postgresql/resource-manager] Add replica creation parameters to Postgres ResourceProvider for SDK
  profiles/latest/postgresql/mgmt/postgresql/models.go
  profiles/latest/postgresql/mgmt/postgresql/postgresqlapi/models.go
  profiles/preview/postgresql/mgmt/postgresql/models.go
  profiles/preview/postgresql/mgmt/postgresql/postgresqlapi/models.go
  services/postgresql/mgmt/2017-12-01/postgresql/models.go
  services/postgresql/mgmt/2017-12-01/postgresql/postgresqlapi/interfaces.go
  services/postgresql/mgmt/2017-12-01/postgresql/replicas.go
Labels: RestPRMerged, review

#4247 [AutoPR security/resource-manager] Correlation Key property added
  services/preview/security/mgmt/v1.0/security/models.go
  services/preview/security/mgmt/v2.0/security/models.go
Labels: RestPRMerged, review

#4233 [AutoPR mediaservices/resource-manager] Add filter to StreamingLocator and Streaming presets.
  profiles/latest/mediaservices/mgmt/media/models.go
  profiles/preview/mediaservices/mgmt/media/models.go
  services/mediaservices/mgmt/2018-07-01/media/models.go
Labels: RestPRMerged, review

#4284 enable verbose building of tests and fold the logs
  .travis.yml
Labels: review

#4183 [AutoPR cognitiveservices/data-plane/AnomalyDetector] [AnomalyDetector] add cognitive service AnomalyDetector [DO NOT MERGE]
  Gopkg.lock
  profiles/preview/cognitiveservices/anomalyfinder/anomalyfinderapi/models.go
  profiles/preview/cognitiveservices/anomalyfinder/models.go
  profiles/preview/preview/cognitiveservices/anomalydetector/anomalydetectorapi/models.go
  profiles/preview/preview/cognitiveservices/anomalydetector/models.go
  profiles/preview/preview/iotspaces/mgmt/iotspaces/models.go
  services/preview/cognitiveservices/v1.0/anomalydetector/anomalydetectorapi/interfaces.go
  services/preview/cognitiveservices/v1.0/anomalydetector/client.go
  services/preview/cognitiveservices/v1.0/anomalydetector/models.go
  services/preview/cognitiveservices/v1.0/anomalydetector/version.go
Labels: RestPRMerged, review

#4270 [AutoPR managedservices/resource-manager] Added Swagger Spec for ManagedServices
  profiles/preview/preview/managedservices/mgmt/managedservices/managedservicesapi/models.go
  profiles/preview/preview/managedservices/mgmt/managedservices/models.go
  services/preview/managedservices/mgmt/2018-06-preview/managedservices/client.go
  services/preview/managedservices/mgmt/2018-06-preview/managedservices/managedservicesapi/interfaces.go
  services/preview/managedservices/mgmt/2018-06-preview/managedservices/models.go
  services/preview/managedservices/mgmt/2018-06-preview/managedservices/operations.go
  services/preview/managedservices/mgmt/2018-06-preview/managedservices/registrationassignments.go
  services/preview/managedservices/mgmt/2018-06-preview/managedservices/registrationdefinitions.go
  services/preview/managedservices/mgmt/2018-06-preview/managedservices/version.go
Labels: RestPRMerged, review

#4298 [AutoPR storage/resource-manager] add storage package-2018-11 to Go SDK
  profiles/latest/storage/mgmt/storage/models.go
  profiles/latest/storage/mgmt/storage/storageapi/models.go
  profiles/preview/storage/mgmt/storage/models.go
  profiles/preview/storage/mgmt/storage/storageapi/models.go
  services/storage/mgmt/2018-11-01/storage/accounts.go
  services/storage/mgmt/2018-11-01/storage/blobcontainers.go
  services/storage/mgmt/2018-11-01/storage/blobservices.go
  services/storage/mgmt/2018-11-01/storage/client.go
  services/storage/mgmt/2018-11-01/storage/managementpolicies.go
  services/storage/mgmt/2018-11-01/storage/models.go
  services/storage/mgmt/2018-11-01/storage/operations.go
  services/storage/mgmt/2018-11-01/storage/skus.go
  services/storage/mgmt/2018-11-01/storage/storageapi/interfaces.go
  services/storage/mgmt/2018-11-01/storage/usages.go
  services/storage/mgmt/2018-11-01/storage/version.go
Labels: RestPRMerged, review

#4297 [AutoPR containerservice/resource-manager] Dev containerservice microsoft.container service 2019 02 01
  profiles/latest/containerservice/mgmt/containerservice/containerserviceapi/models.go
  profiles/latest/containerservice/mgmt/containerservice/models.go
  profiles/preview/containerservice/mgmt/containerservice/containerserviceapi/models.go
  profiles/preview/containerservice/mgmt/containerservice/models.go
  services/containerservice/mgmt/2019-02-01/containerservice/agentpools.go
  services/containerservice/mgmt/2019-02-01/containerservice/client.go
  services/containerservice/mgmt/2019-02-01/containerservice/containerserviceapi/interfaces.go
  services/containerservice/mgmt/2019-02-01/containerservice/containerservices.go
  services/containerservice/mgmt/2019-02-01/containerservice/managedclusters.go
  services/containerservice/mgmt/2019-02-01/containerservice/models.go
  services/containerservice/mgmt/2019-02-01/containerservice/openshiftmanagedclusters.go
  services/containerservice/mgmt/2019-02-01/containerservice/operations.go
  services/containerservice/mgmt/2019-02-01/containerservice/version.go
Labels: RestPRMerged, review

#4285 [AutoPR iothub/resource-manager] making the health status description shorter
  services/iothub/mgmt/2018-04-01/devices/models.go
Labels: RestPRMerged, review

#4283 [AutoPR search/resource-manager] Add L-Series SKU values to management plane
  profiles/latest/search/mgmt/search/models.go
  profiles/preview/search/mgmt/search/models.go
  services/search/mgmt/2015-08-19/search/models.go
Labels: RestPRMerged, review

#4299 [AutoPR] storage/resource-manager
  profiles/latest/storage/mgmt/storage/models.go
  profiles/latest/storage/mgmt/storage/storageapi/models.go
  profiles/preview/storage/mgmt/storage/models.go
  profiles/preview/storage/mgmt/storage/storageapi/models.go
  services/storage/mgmt/2018-11-01/storage/accounts.go
  services/storage/mgmt/2018-11-01/storage/blobcontainers.go
  services/storage/mgmt/2018-11-01/storage/blobservices.go
  services/storage/mgmt/2018-11-01/storage/client.go
  services/storage/mgmt/2018-11-01/storage/managementpolicies.go
  services/storage/mgmt/2018-11-01/storage/models.go
  services/storage/mgmt/2018-11-01/storage/operations.go
  services/storage/mgmt/2018-11-01/storage/skus.go
  services/storage/mgmt/2018-11-01/storage/storageapi/interfaces.go
  services/storage/mgmt/2018-11-01/storage/usages.go
  services/storage/mgmt/2018-11-01/storage/version.go
Labels: ServicePR, review

#4287 [AutoPR] postgresql/resource-manager
  profiles/latest/postgresql/mgmt/postgresql/models.go
  profiles/latest/postgresql/mgmt/postgresql/postgresqlapi/models.go
  profiles/preview/postgresql/mgmt/postgresql/models.go
  profiles/preview/postgresql/mgmt/postgresql/postgresqlapi/models.go
  services/postgresql/mgmt/2017-12-01/postgresql/models.go
  services/postgresql/mgmt/2017-12-01/postgresql/postgresqlapi/interfaces.go
  services/postgresql/mgmt/2017-12-01/postgresql/replicas.go
Labels: ServicePR, review

#4288 [AutoPR] security/resource-manager
  services/preview/security/mgmt/v1.0/security/models.go
  services/preview/security/mgmt/v2.0/security/models.go
Labels: ServicePR, review

#4307 [AutoPR] iothub/resource-manager
  services/iothub/mgmt/2018-04-01/devices/models.go
Labels: ServicePR, review

#4315 [AutoPR] search/resource-manager
  profiles/latest/search/mgmt/search/models.go
  profiles/preview/search/mgmt/search/models.go
  services/search/mgmt/2015-08-19/search/models.go
Labels: ServicePR, review

#4313 [AutoPR network/resource-manager] Network February release
  profiles/latest/network/mgmt/network/models.go
  profiles/latest/network/mgmt/network/networkapi/models.go
  profiles/preview/network/mgmt/network/models.go
  profiles/preview/network/mgmt/network/networkapi/models.go
  services/network/mgmt/2018-12-01/network/models.go
  services/network/mgmt/2018-12-01/network/networkapi/interfaces.go
  services/network/mgmt/2018-12-01/network/peerexpressroutecircuitconnections.go
  services/network/mgmt/2018-12-01/network/webapplicationfirewallpolicies.go
Labels: RestPRMerged, review

#4317 [AutoPR containerservice/resource-manager] Dev containerservice microsoft.container service 2019 02 01
  profiles/latest/containerservice/mgmt/containerservice/containerserviceapi/models.go
  profiles/latest/containerservice/mgmt/containerservice/models.go
  profiles/preview/containerservice/mgmt/containerservice/containerserviceapi/models.go
  profiles/preview/containerservice/mgmt/containerservice/models.go
  services/containerservice/mgmt/2019-02-01/containerservice/agentpools.go
  services/containerservice/mgmt/2019-02-01/containerservice/client.go
  services/containerservice/mgmt/2019-02-01/containerservice/containerserviceapi/interfaces.go
  services/containerservice/mgmt/2019-02-01/containerservice/containerservices.go
  services/containerservice/mgmt/2019-02-01/containerservice/managedclusters.go
  services/containerservice/mgmt/2019-02-01/containerservice/models.go
  services/containerservice/mgmt/2019-02-01/containerservice/openshiftmanagedclusters.go
  services/containerservice/mgmt/2019-02-01/containerservice/operations.go
  services/containerservice/mgmt/2019-02-01/containerservice/version.go
Labels: review

#4318 [AutoPR] containerservice/resource-manager
  profiles/latest/containerservice/mgmt/containerservice/containerserviceapi/models.go
  profiles/latest/containerservice/mgmt/containerservice/models.go
  profiles/preview/containerservice/mgmt/containerservice/containerserviceapi/models.go
  profiles/preview/containerservice/mgmt/containerservice/models.go
  services/containerservice/mgmt/2019-02-01/containerservice/agentpools.go
  services/containerservice/mgmt/2019-02-01/containerservice/client.go
  services/containerservice/mgmt/2019-02-01/containerservice/containerserviceapi/interfaces.go
  services/containerservice/mgmt/2019-02-01/containerservice/containerservices.go
  services/containerservice/mgmt/2019-02-01/containerservice/managedclusters.go
  services/containerservice/mgmt/2019-02-01/containerservice/models.go
  services/containerservice/mgmt/2019-02-01/containerservice/openshiftmanagedclusters.go
  services/containerservice/mgmt/2019-02-01/containerservice/operations.go
  services/containerservice/mgmt/2019-02-01/containerservice/version.go
Labels: ServicePR, review

#4323 [AutoPR cognitiveservices/data-plane/LUIS/Authoring] Luis swagger fixes
  profiles/latest/cognitiveservices/luis/authoring/models.go
  profiles/preview/cognitiveservices/luis/authoring/models.go
  services/cognitiveservices/v2.0/luis/authoring/apps.go
  services/cognitiveservices/v2.0/luis/authoring/authoringapi/interfaces.go
  services/cognitiveservices/v2.0/luis/authoring/azureaccounts.go
  services/cognitiveservices/v2.0/luis/authoring/client.go
  services/cognitiveservices/v2.0/luis/authoring/examples.go
  services/cognitiveservices/v2.0/luis/authoring/features.go
  services/cognitiveservices/v2.0/luis/authoring/model.go
  services/cognitiveservices/v2.0/luis/authoring/models.go
  services/cognitiveservices/v2.0/luis/authoring/pattern.go
  services/cognitiveservices/v2.0/luis/authoring/permissions.go
  services/cognitiveservices/v2.0/luis/authoring/settings.go
  services/cognitiveservices/v2.0/luis/authoring/train.go
  services/cognitiveservices/v2.0/luis/authoring/versions.go
Labels: RestPRMerged, review

#4325 add cognitive services anomalydetector v1.0
  profiles/preview/preview/cognitiveservices/anomalydetector/anomalydetectorapi/models.go
  profiles/preview/preview/cognitiveservices/anomalydetector/models.go
  services/preview/cognitiveservices/v1.0/anomalydetector/anomalydetectorapi/interfaces.go
  services/preview/cognitiveservices/v1.0/anomalydetector/client.go
  services/preview/cognitiveservices/v1.0/anomalydetector/models.go
  services/preview/cognitiveservices/v1.0/anomalydetector/version.go
Labels: review

#4304 [AutoPR marketplaceordering/resource-manager] [Hub Generated] Review request for Microsoft.MarketplaceOrdering to add version 2015-06-01
  services/marketplaceordering/mgmt/2015-06-01/marketplaceordering/marketplaceagreements.go
Labels: RestPRMerged, review

#4330 [AutoPR] marketplaceordering/resource-manager
  services/marketplaceordering/mgmt/2015-06-01/marketplaceordering/marketplaceagreements.go
Labels: ServicePR

#4327 [AutoPR] cognitiveservices/data-plane/LUIS/Authoring
  profiles/latest/cognitiveservices/luis/authoring/models.go
  profiles/preview/cognitiveservices/luis/authoring/models.go
  services/cognitiveservices/v2.0/luis/authoring/apps.go
  services/cognitiveservices/v2.0/luis/authoring/authoringapi/interfaces.go
  services/cognitiveservices/v2.0/luis/authoring/azureaccounts.go
  services/cognitiveservices/v2.0/luis/authoring/client.go
  services/cognitiveservices/v2.0/luis/authoring/examples.go
  services/cognitiveservices/v2.0/luis/authoring/features.go
  services/cognitiveservices/v2.0/luis/authoring/model.go
  services/cognitiveservices/v2.0/luis/authoring/models.go
  services/cognitiveservices/v2.0/luis/authoring/pattern.go
  services/cognitiveservices/v2.0/luis/authoring/permissions.go
  services/cognitiveservices/v2.0/luis/authoring/settings.go
  services/cognitiveservices/v2.0/luis/authoring/train.go
  services/cognitiveservices/v2.0/luis/authoring/versions.go
Labels: ServicePR, review

#4320 [AutoPR graphrbac/data-plane] graph: identifierUris should not be required
  services/graphrbac/1.6/graphrbac/applications.go
Labels: RestPRMerged, review

#4311 [AutoPR graphrbac/data-plane] Add service principals by app id microsoft.graph rbac
  profiles/latest/graphrbac/graphrbac/models.go
  profiles/preview/graphrbac/graphrbac/models.go
  services/graphrbac/1.6/graphrbac/applications.go
  services/graphrbac/1.6/graphrbac/graphrbacapi/interfaces.go
  services/graphrbac/1.6/graphrbac/models.go
Labels: RestPRMerged, review

#4291 [AutoPR machinelearning/resource-manager] [Hub Generated] Review request for Microsoft.MachineLearning to add version 2017-01-01
  profiles/latest/machinelearning/mgmt/webservices/models.go
  profiles/preview/machinelearning/mgmt/webservices/models.go
  services/machinelearning/mgmt/2017-01-01/webservices/models.go
  services/machinelearning/mgmt/2017-01-01/webservices/webservices.go
  services/machinelearning/mgmt/2017-01-01/webservices/webservicesapi/interfaces.go
Labels: RestPRMerged, review

#4269 [AutoPR netapp/resource-manager] Update to Release 3.5 standard (pre GA)
  profiles/preview/preview/netapp/mgmt/netapp/models.go
  services/preview/netapp/mgmt/2017-08-15/netapp/models.go
Labels: RestPRMerged, review

#4331 [AutoPR] graphrbac/data-plane
  profiles/latest/graphrbac/graphrbac/models.go
  profiles/preview/graphrbac/graphrbac/models.go
  services/graphrbac/1.6/graphrbac/applications.go
  services/graphrbac/1.6/graphrbac/graphrbacapi/interfaces.go
  services/graphrbac/1.6/graphrbac/models.go
Labels: ServicePR

#4341 [AutoPR sql/resource-manager] typo: Winodws -> Windows
  services/preview/sql/mgmt/2015-05-01-preview/sql/models.go
  services/preview/sql/mgmt/2017-03-01-preview/sql/models.go
Labels: RestPRMerged

#4335 [AutoPR] machinelearning/resource-manager
  profiles/latest/machinelearning/mgmt/webservices/models.go
  profiles/preview/machinelearning/mgmt/webservices/models.go
  services/machinelearning/mgmt/2017-01-01/webservices/models.go
  services/machinelearning/mgmt/2017-01-01/webservices/webservices.go
  services/machinelearning/mgmt/2017-01-01/webservices/webservicesapi/interfaces.go
Labels: ServicePR

#4339 [AutoPR] netapp/resource-manager
  profiles/preview/preview/netapp/mgmt/netapp/models.go
  services/preview/netapp/mgmt/2017-08-15/netapp/models.go
Labels: ServicePR

#4340 [AutoPR managedservices/resource-manager] fix Go output folder for managed services
  profiles/preview/preview/managedservices/mgmt/managedservices/managedservicesapi/models.go
  profiles/preview/preview/managedservices/mgmt/managedservices/models.go
  services/preview/managedservices/mgmt/2018-06-01/managedservices/client.go
  services/preview/managedservices/mgmt/2018-06-01/managedservices/managedservicesapi/interfaces.go
  services/preview/managedservices/mgmt/2018-06-01/managedservices/models.go
  services/preview/managedservices/mgmt/2018-06-01/managedservices/operations.go
  services/preview/managedservices/mgmt/2018-06-01/managedservices/registrationassignments.go
  services/preview/managedservices/mgmt/2018-06-01/managedservices/registrationdefinitions.go
  services/preview/managedservices/mgmt/2018-06-01/managedservices/version.go
Labels: RestPRMerged

#4332 [AutoPR consumption/resource-manager] [Hub Generated] Review request for Microsoft.Consumption to add version 2018-11-01-preview
  services/consumption/mgmt/2019-01-01/consumption/budgets.go
Labels: RestPRMerged

#4286 [AutoPR containerregistry/resource-manager] [ACR] Update Webhook Event Target Schema to Add Name and Version
  services/containerregistry/mgmt/2017-10-01/containerregistry/models.go
  services/containerregistry/mgmt/2018-09-01/containerregistry/models.go
  services/preview/containerregistry/mgmt/2018-02-01/containerregistry/models.go
Labels: RestPRMerged, review

#4255 [AutoPR servicebus/resource-manager] Servicebus : NetworkruleSet
  profiles/latest/servicebus/mgmt/servicebus/models.go
  profiles/preview/servicebus/mgmt/servicebus/models.go
  services/servicebus/mgmt/2017-04-01/servicebus/models.go
  services/servicebus/mgmt/2017-04-01/servicebus/namespaces.go
  services/servicebus/mgmt/2017-04-01/servicebus/servicebusapi/interfaces.go
Labels: RestPRMerged, review

#4227 [AutoPR healthcareapis/resource-manager] Adding swagger spec for healthcareapis resource manager and examples.
  profiles/preview/preview/healthcareapis/mgmt/healthcareapis/healthcareapisapi/models.go
  profiles/preview/preview/healthcareapis/mgmt/healthcareapis/models.go
  services/preview/healthcareapis/mgmt/2018-08-20-preview/healthcareapis/client.go
  services/preview/healthcareapis/mgmt/2018-08-20-preview/healthcareapis/healthcareapisapi/interfaces.go
  services/preview/healthcareapis/mgmt/2018-08-20-preview/healthcareapis/models.go
  services/preview/healthcareapis/mgmt/2018-08-20-preview/healthcareapis/moveresourcesstatus.go
  services/preview/healthcareapis/mgmt/2018-08-20-preview/healthcareapis/operationresults.go
  services/preview/healthcareapis/mgmt/2018-08-20-preview/healthcareapis/operations.go
  services/preview/healthcareapis/mgmt/2018-08-20-preview/healthcareapis/services.go
  services/preview/healthcareapis/mgmt/2018-08-20-preview/healthcareapis/version.go
Labels: RestPRMerged, review

#4258 [AutoPR peering/resource-manager] Adding Specifications for Peering
  profiles/preview/preview/peering/mgmt/peering/models.go
  profiles/preview/preview/peering/mgmt/peering/peeringapi/models.go
  services/preview/peering/mgmt/2019-03-01-preview/peering/client.go
  services/preview/peering/mgmt/2019-03-01-preview/peering/legacypeerings.go
  services/preview/peering/mgmt/2019-03-01-preview/peering/locations.go
  services/preview/peering/mgmt/2019-03-01-preview/peering/models.go
  services/preview/peering/mgmt/2019-03-01-preview/peering/operations.go
  services/preview/peering/mgmt/2019-03-01-preview/peering/peerasns.go
  services/preview/peering/mgmt/2019-03-01-preview/peering/peeringapi/interfaces.go
  services/preview/peering/mgmt/2019-03-01-preview/peering/peerings.go
  services/preview/peering/mgmt/2019-03-01-preview/peering/version.go
Labels: RestPRMerged, review

#4306 [AutoPR mediaservices/resource-manager] Add preset enum ContentAwareEncodingExperimental
  profiles/latest/mediaservices/mgmt/media/models.go
  profiles/preview/mediaservices/mgmt/media/models.go
  services/mediaservices/mgmt/2018-07-01/media/models.go
Labels: RestPRMerged, review

#4352 [AutoPR containerregistry/resource-manager] [ACR] Add Readonly RunErrorMessage to RunProperties
  services/containerregistry/mgmt/2018-09-01/containerregistry/models.go
Labels: RestPRMerged

#4358 [AutoPR managedservices/resource-manager] Fixed typos
  services/preview/managedservices/mgmt/2018-06-01/managedservices/managedservicesapi/interfaces.go
  services/preview/managedservices/mgmt/2018-06-01/managedservices/models.go
  services/preview/managedservices/mgmt/2018-06-01/managedservices/registrationassignments.go
  services/preview/managedservices/mgmt/2018-06-01/managedservices/registrationdefinitions.go
Labels: RestPRMerged

#4359 [AutoPR storage/resource-manager] Added feature revoke user delegation key
  services/storage/mgmt/2018-11-01/storage/accounts.go
  services/storage/mgmt/2018-11-01/storage/storageapi/interfaces.go
Labels: RestPRMerged

#4361 [AutoPR cognitiveservices/data-plane/CustomVision/Prediction] enable release_3_0 for Go SDK
  profiles/latest/cognitiveservices/customvision/prediction/models.go
  profiles/latest/cognitiveservices/customvision/prediction/predictionapi/models.go
  profiles/preview/cognitiveservices/customvision/prediction/models.go
  profiles/preview/cognitiveservices/customvision/prediction/predictionapi/models.go
  services/cognitiveservices/v3.0/customvision/prediction/client.go
  services/cognitiveservices/v3.0/customvision/prediction/models.go
  services/cognitiveservices/v3.0/customvision/prediction/predictionapi/interfaces.go
  services/cognitiveservices/v3.0/customvision/prediction/version.go
Labels: RestPRMerged

#4289 [AutoPR] mediaservices/resource-manager
  profiles/latest/mediaservices/mgmt/media/models.go
  profiles/preview/mediaservices/mgmt/media/models.go
  services/mediaservices/mgmt/2018-07-01/media/models.go
Labels: ServicePR, review

#4348 [AutoPR] consumption/resource-manager
  services/consumption/mgmt/2019-01-01/consumption/budgets.go
Labels: ServicePR

#4353 [AutoPR] servicebus/resource-manager
  profiles/latest/servicebus/mgmt/servicebus/models.go
  profiles/preview/servicebus/mgmt/servicebus/models.go
  services/servicebus/mgmt/2017-04-01/servicebus/models.go
  services/servicebus/mgmt/2017-04-01/servicebus/namespaces.go
  services/servicebus/mgmt/2017-04-01/servicebus/servicebusapi/interfaces.go
Labels: ServicePR

#4354 [AutoPR] healthcareapis/resource-manager
  profiles/preview/preview/healthcareapis/mgmt/healthcareapis/healthcareapisapi/models.go
  profiles/preview/preview/healthcareapis/mgmt/healthcareapis/models.go
  services/preview/healthcareapis/mgmt/2018-08-20-preview/healthcareapis/client.go
  services/preview/healthcareapis/mgmt/2018-08-20-preview/healthcareapis/healthcareapisapi/interfaces.go
  services/preview/healthcareapis/mgmt/2018-08-20-preview/healthcareapis/models.go
  services/preview/healthcareapis/mgmt/2018-08-20-preview/healthcareapis/moveresourcesstatus.go
  services/preview/healthcareapis/mgmt/2018-08-20-preview/healthcareapis/operationresults.go
  services/preview/healthcareapis/mgmt/2018-08-20-preview/healthcareapis/operations.go
  services/preview/healthcareapis/mgmt/2018-08-20-preview/healthcareapis/services.go
  services/preview/healthcareapis/mgmt/2018-08-20-preview/healthcareapis/version.go
Labels: ServicePR

#4357 [AutoPR] peering/resource-manager
  profiles/preview/preview/peering/mgmt/peering/models.go
  profiles/preview/preview/peering/mgmt/peering/peeringapi/models.go
  services/preview/peering/mgmt/2019-03-01-preview/peering/client.go
  services/preview/peering/mgmt/2019-03-01-preview/peering/legacypeerings.go
  services/preview/peering/mgmt/2019-03-01-preview/peering/locations.go
  services/preview/peering/mgmt/2019-03-01-preview/peering/models.go
  services/preview/peering/mgmt/2019-03-01-preview/peering/operations.go
  services/preview/peering/mgmt/2019-03-01-preview/peering/peerasns.go
  services/preview/peering/mgmt/2019-03-01-preview/peering/peeringapi/interfaces.go
  services/preview/peering/mgmt/2019-03-01-preview/peering/peerings.go
  services/preview/peering/mgmt/2019-03-01-preview/peering/version.go
Labels: ServicePR

#4362 [AutoPR] storage/resource-manager
  services/storage/mgmt/2018-11-01/storage/accounts.go
  services/storage/mgmt/2018-11-01/storage/storageapi/interfaces.go
Labels: ServicePR

#4363 [AutoPR] cognitiveservices/data-plane/CustomVision/Prediction
  profiles/latest/cognitiveservices/customvision/prediction/models.go
  profiles/latest/cognitiveservices/customvision/prediction/predictionapi/models.go
  profiles/preview/cognitiveservices/customvision/prediction/models.go
  profiles/preview/cognitiveservices/customvision/prediction/predictionapi/models.go
  services/cognitiveservices/v3.0/customvision/prediction/client.go
  services/cognitiveservices/v3.0/customvision/prediction/models.go
  services/cognitiveservices/v3.0/customvision/prediction/predictionapi/interfaces.go
  services/cognitiveservices/v3.0/customvision/prediction/version.go
Labels: ServicePR

#4350 [AutoPR netapp/resource-manager] Small correction to list handling
  profiles/preview/preview/netapp/mgmt/netapp/models.go
  services/preview/netapp/mgmt/2017-08-15/netapp/models.go
Labels: RestPRMerged

#4364 [AutoPR] netapp/resource-manager
  profiles/preview/preview/netapp/mgmt/netapp/models.go
  services/preview/netapp/mgmt/2017-08-15/netapp/models.go
Labels: ServicePR

#4368 [AutoPR adhybridhealthservice/resource-manager] New operations for adhealth
  profiles/latest/adhybridhealthservice/mgmt/adhybridhealthservice/models.go
  profiles/preview/adhybridhealthservice/mgmt/adhybridhealthservice/models.go
  services/adhybridhealthservice/mgmt/2014-01-01/adhybridhealthservice/adhybridhealthserviceapi/interfaces.go
  services/adhybridhealthservice/mgmt/2014-01-01/adhybridhealthservice/models.go
  services/adhybridhealthservice/mgmt/2014-01-01/adhybridhealthservice/servicemembers.go
Labels: RestPRMerged

#4367 [AutoPR managedservices/resource-manager] typo: registraton -> registration
  services/preview/managedservices/mgmt/2018-06-01/managedservices/managedservicesapi/interfaces.go
  services/preview/managedservices/mgmt/2018-06-01/managedservices/registrationassignments.go
Labels: RestPRMerged

#4365 [AutoPR graphrbac/data-plane] typo: informations -> information about
  services/graphrbac/1.6/graphrbac/models.go
Labels: RestPRMerged

#4372 [AutoPR cognitiveservices/data-plane/CustomVision/Training] add training tag release_3_0 to Go SDK
  profiles/latest/cognitiveservices/customvision/training/models.go
  profiles/latest/cognitiveservices/customvision/training/trainingapi/models.go
  profiles/preview/cognitiveservices/customvision/training/models.go
  profiles/preview/cognitiveservices/customvision/training/trainingapi/models.go
  services/cognitiveservices/v3.0/customvision/training/client.go
  services/cognitiveservices/v3.0/customvision/training/models.go
  services/cognitiveservices/v3.0/customvision/training/trainingapi/interfaces.go
  services/cognitiveservices/v3.0/customvision/training/version.go
Labels: RestPRMerged

#4337 [AutoPR security/resource-manager] New security Regulatory compliance API
  profiles/preview/preview/security/mgmt/security/models.go
  profiles/preview/preview/security/mgmt/security/securityapi/models.go
  services/preview/security/mgmt/v1.0/security/models.go
  services/preview/security/mgmt/v1.0/security/regulatorycomplianceassessments.go
  services/preview/security/mgmt/v1.0/security/regulatorycompliancecontrols.go
  services/preview/security/mgmt/v1.0/security/regulatorycompliancestandards.go
  services/preview/security/mgmt/v1.0/security/securityapi/interfaces.go
  services/preview/security/mgmt/v2.0/security/models.go
  services/preview/security/mgmt/v2.0/security/regulatorycomplianceassessments.go
  services/preview/security/mgmt/v2.0/security/regulatorycompliancecontrols.go
  services/preview/security/mgmt/v2.0/security/regulatorycompliancestandards.go
  services/preview/security/mgmt/v2.0/security/securityapi/interfaces.go
Labels: RestPRMerged

#4377 [AutoPR security/resource-manager] Adding the NorthSouth API for Public Preview
  profiles/preview/preview/security/mgmt/security/models.go
  profiles/preview/preview/security/mgmt/security/securityapi/models.go
  services/preview/security/mgmt/v1.0/security/adaptivenetworkhardenings.go
  services/preview/security/mgmt/v1.0/security/devicesecuritygroups.go
  services/preview/security/mgmt/v1.0/security/models.go
  services/preview/security/mgmt/v1.0/security/securityapi/interfaces.go
  services/preview/security/mgmt/v2.0/security/adaptivenetworkhardenings.go
  services/preview/security/mgmt/v2.0/security/devicesecuritygroups.go
  services/preview/security/mgmt/v2.0/security/models.go
  services/preview/security/mgmt/v2.0/security/securityapi/interfaces.go
Labels: RestPRMerged

#4376 [AutoPR] cognitiveservices/data-plane/CustomVision/Training
  profiles/latest/cognitiveservices/customvision/training/models.go
  profiles/latest/cognitiveservices/customvision/training/trainingapi/models.go
  profiles/preview/cognitiveservices/customvision/training/models.go
  profiles/preview/cognitiveservices/customvision/training/trainingapi/models.go
  services/cognitiveservices/v3.0/customvision/training/client.go
  services/cognitiveservices/v3.0/customvision/training/models.go
  services/cognitiveservices/v3.0/customvision/training/trainingapi/interfaces.go
  services/cognitiveservices/v3.0/customvision/training/version.go
Labels: ServicePR

#4369 [AutoPR] adhybridhealthservice/resource-manager
  profiles/latest/adhybridhealthservice/mgmt/adhybridhealthservice/models.go
  profiles/preview/adhybridhealthservice/mgmt/adhybridhealthservice/models.go
  services/adhybridhealthservice/mgmt/2014-01-01/adhybridhealthservice/adhybridhealthserviceapi/interfaces.go
  services/adhybridhealthservice/mgmt/2014-01-01/adhybridhealthservice/models.go
  services/adhybridhealthservice/mgmt/2014-01-01/adhybridhealthservice/servicemembers.go
Labels: ServicePR

#4370 [AutoPR] managedservices/resource-manager
  services/preview/managedservices/mgmt/2018-06-01/managedservices/managedservicesapi/interfaces.go
  services/preview/managedservices/mgmt/2018-06-01/managedservices/registrationassignments.go
Labels: ServicePR

#4371 [AutoPR] graphrbac/data-plane
  services/graphrbac/1.6/graphrbac/models.go
Labels: ServicePR

#4326 [AutoPR network/resource-manager] Patch call for DDoS Protection plan
  profiles/latest/network/mgmt/network/models.go
  profiles/preview/network/mgmt/network/models.go
  services/network/mgmt/2018-11-01/network/ddosprotectionplans.go
  services/network/mgmt/2018-11-01/network/models.go
  services/network/mgmt/2018-11-01/network/networkapi/interfaces.go
  services/network/mgmt/2018-12-01/network/ddosprotectionplans.go
  services/network/mgmt/2018-12-01/network/models.go
  services/network/mgmt/2018-12-01/network/networkapi/interfaces.go
Labels: RestPRMerged, review

#4174 [AutoPR] imagebuilder/resource-manager
  profiles/preview/preview/virtualmachineimagebuilder/mgmt/virtualmachineimagebuilder/models.go
  profiles/preview/preview/virtualmachineimagebuilder/mgmt/virtualmachineimagebuilder/virtualmachineimagebuilderapi/models.go
  services/preview/virtualmachineimagebuilder/mgmt/2018-02-01-preview/virtualmachineimagebuilder/client.go
  services/preview/virtualmachineimagebuilder/mgmt/2018-02-01-preview/virtualmachineimagebuilder/models.go
  services/preview/virtualmachineimagebuilder/mgmt/2018-02-01-preview/virtualmachineimagebuilder/operations.go
  services/preview/virtualmachineimagebuilder/mgmt/2018-02-01-preview/virtualmachineimagebuilder/version.go
  services/preview/virtualmachineimagebuilder/mgmt/2018-02-01-preview/virtualmachineimagebuilder/virtualmachineimagebuilderapi/interfaces.go
  services/preview/virtualmachineimagebuilder/mgmt/2018-02-01-preview/virtualmachineimagebuilder/virtualmachineimagetemplate.go
Labels: ServicePR, review

#4390 [AutoPR frontdoor/resource-manager] Stable release of Front door API
  profiles/preview/preview/frontdoor/mgmt/frontdoor/frontdoorapi/models.go
  profiles/preview/preview/frontdoor/mgmt/frontdoor/models.go
  services/preview/frontdoor/mgmt/2019-04-01/frontdoor/backendpools.go
  services/preview/frontdoor/mgmt/2019-04-01/frontdoor/client.go
  services/preview/frontdoor/mgmt/2019-04-01/frontdoor/endpoints.go
  services/preview/frontdoor/mgmt/2019-04-01/frontdoor/frontdoorapi/interfaces.go
  services/preview/frontdoor/mgmt/2019-04-01/frontdoor/frontdoors.go
  services/preview/frontdoor/mgmt/2019-04-01/frontdoor/frontendendpoints.go
  services/preview/frontdoor/mgmt/2019-04-01/frontdoor/healthprobesettings.go
  services/preview/frontdoor/mgmt/2019-04-01/frontdoor/loadbalancingsettings.go
  services/preview/frontdoor/mgmt/2019-04-01/frontdoor/managedrulesets.go
  services/preview/frontdoor/mgmt/2019-04-01/frontdoor/models.go
  services/preview/frontdoor/mgmt/2019-04-01/frontdoor/policies.go
  services/preview/frontdoor/mgmt/2019-04-01/frontdoor/routingrules.go
  services/preview/frontdoor/mgmt/2019-04-01/frontdoor/version.go
Labels: RestPRMerged

#4392 [AutoPR cognitiveservices/data-plane/TranslatorText] typo: cognitiveservices/data-plane/TranslatorText
  services/cognitiveservices/v3.0/translatortext/translator.go
Labels: RestPRMerged

#4394 [AutoPR] frontdoor/resource-manager
  profiles/preview/preview/frontdoor/mgmt/frontdoor/frontdoorapi/models.go
  profiles/preview/preview/frontdoor/mgmt/frontdoor/models.go
  services/preview/frontdoor/mgmt/2019-04-01/frontdoor/backendpools.go
  services/preview/frontdoor/mgmt/2019-04-01/frontdoor/client.go
  services/preview/frontdoor/mgmt/2019-04-01/frontdoor/endpoints.go
  services/preview/frontdoor/mgmt/2019-04-01/frontdoor/frontdoorapi/interfaces.go
  services/preview/frontdoor/mgmt/2019-04-01/frontdoor/frontdoors.go
  services/preview/frontdoor/mgmt/2019-04-01/frontdoor/frontendendpoints.go
  services/preview/frontdoor/mgmt/2019-04-01/frontdoor/healthprobesettings.go
  services/preview/frontdoor/mgmt/2019-04-01/frontdoor/loadbalancingsettings.go
  services/preview/frontdoor/mgmt/2019-04-01/frontdoor/managedrulesets.go
  services/preview/frontdoor/mgmt/2019-04-01/frontdoor/models.go
  services/preview/frontdoor/mgmt/2019-04-01/frontdoor/policies.go
  services/preview/frontdoor/mgmt/2019-04-01/frontdoor/routingrules.go
  services/preview/frontdoor/mgmt/2019-04-01/frontdoor/version.go
Labels: ServicePR

#4395 [AutoPR] cognitiveservices/data-plane/TranslatorText
  services/cognitiveservices/v3.0/translatortext/translator.go
Labels: ServicePR

#4402 [AutoPR storagesync/resource-manager] [Hub Generated] Review request for Microsoft.StorageSync to add version 2019-02-01
  profiles/latest/storagesync/mgmt/storagesync/models.go
  profiles/latest/storagesync/mgmt/storagesync/storagesyncapi/models.go
  profiles/preview/storagesync/mgmt/storagesync/models.go
  profiles/preview/storagesync/mgmt/storagesync/storagesyncapi/models.go
  services/storagesync/mgmt/2019-02-01/storagesync/client.go
  services/storagesync/mgmt/2019-02-01/storagesync/cloudendpoints.go
  services/storagesync/mgmt/2019-02-01/storagesync/models.go
  services/storagesync/mgmt/2019-02-01/storagesync/operations.go
  services/storagesync/mgmt/2019-02-01/storagesync/registeredservers.go
  services/storagesync/mgmt/2019-02-01/storagesync/serverendpoints.go
  services/storagesync/mgmt/2019-02-01/storagesync/services.go
  services/storagesync/mgmt/2019-02-01/storagesync/storagesyncapi/interfaces.go
  services/storagesync/mgmt/2019-02-01/storagesync/syncgroups.go
  services/storagesync/mgmt/2019-02-01/storagesync/version.go
  services/storagesync/mgmt/2019-02-01/storagesync/workflows.go
Labels: RestPRMerged

#4388 [AutoPR billing/resource-manager] fix: billing/resource-manager/Microsoft.Billing
  profiles/preview/preview/billing/mgmt/billing/billingapi/models.go
  profiles/preview/preview/billing/mgmt/billing/models.go
  services/preview/billing/mgmt/2018-11-01-preview/billing/accountbillingpermissions.go
  services/preview/billing/mgmt/2018-11-01-preview/billing/accountbillingroleassignment.go
  services/preview/billing/mgmt/2018-11-01-preview/billing/accountbillingroledefinition.go
  services/preview/billing/mgmt/2018-11-01-preview/billing/accounts.go
  services/preview/billing/mgmt/2018-11-01-preview/billing/accountswithcreateinvoicesectionpermission.go
  services/preview/billing/mgmt/2018-11-01-preview/billing/availablebalancebybillingprofile.go
  services/preview/billing/mgmt/2018-11-01-preview/billing/billingapi/interfaces.go
  services/preview/billing/mgmt/2018-11-01-preview/billing/client.go
  services/preview/billing/mgmt/2018-11-01-preview/billing/departments.go
  services/preview/billing/mgmt/2018-11-01-preview/billing/departmentsbybillingaccountname.go
  services/preview/billing/mgmt/2018-11-01-preview/billing/enrollmentaccounts.go
  services/preview/billing/mgmt/2018-11-01-preview/billing/enrollmentaccountsbybillingaccountname.go
  services/preview/billing/mgmt/2018-11-01-preview/billing/invoice.go
  services/preview/billing/mgmt/2018-11-01-preview/billing/invoicepricesheet.go
  services/preview/billing/mgmt/2018-11-01-preview/billing/invoicesbybillingaccount.go
  services/preview/billing/mgmt/2018-11-01-preview/billing/invoicesbybillingprofile.go
  services/preview/billing/mgmt/2018-11-01-preview/billing/invoicesectionbillingroleassignment.go
  services/preview/billing/mgmt/2018-11-01-preview/billing/invoicesectionbillingroledefinition.go
  services/preview/billing/mgmt/2018-11-01-preview/billing/invoicesections.go
  services/preview/billing/mgmt/2018-11-01-preview/billing/invoicesectionsbillingpermissions.go
  services/preview/billing/mgmt/2018-11-01-preview/billing/invoicesectionsbybillingaccountname.go
  services/preview/billing/mgmt/2018-11-01-preview/billing/invoicesectionswithcreatesubscriptionpermission.go
  services/preview/billing/mgmt/2018-11-01-preview/billing/models.go
  services/preview/billing/mgmt/2018-11-01-preview/billing/operations.go
  services/preview/billing/mgmt/2018-11-01-preview/billing/paymentmethodsbybillingprofile.go
  services/preview/billing/mgmt/2018-11-01-preview/billing/policy.go
  services/preview/billing/mgmt/2018-11-01-preview/billing/products.go
  services/preview/billing/mgmt/2018-11-01-preview/billing/productsbybillingaccount.go
  services/preview/billing/mgmt/2018-11-01-preview/billing/productsbybillingsubscriptions.go
  services/preview/billing/mgmt/2018-11-01-preview/billing/productsbyinvoicesection.go
  services/preview/billing/mgmt/2018-11-01-preview/billing/profilebillingpermissions.go
  services/preview/billing/mgmt/2018-11-01-preview/billing/profilebillingroleassignment.go
  services/preview/billing/mgmt/2018-11-01-preview/billing/profilebillingroledefinition.go
  services/preview/billing/mgmt/2018-11-01-preview/billing/profiles.go
  services/preview/billing/mgmt/2018-11-01-preview/billing/profilesbybillingaccountname.go
  services/preview/billing/mgmt/2018-11-01-preview/billing/property.go
  services/preview/billing/mgmt/2018-11-01-preview/billing/recipienttransfers.go
  services/preview/billing/mgmt/2018-11-01-preview/billing/subscription.go
  services/preview/billing/mgmt/2018-11-01-preview/billing/subscriptionsbybillingprofile.go
  services/preview/billing/mgmt/2018-11-01-preview/billing/subscriptionsbyinvoicesection.go
  services/preview/billing/mgmt/2018-11-01-preview/billing/transactionsbybillingaccount.go
  services/preview/billing/mgmt/2018-11-01-preview/billing/transfers.go
  services/preview/billing/mgmt/2018-11-01-preview/billing/version.go
Labels: RestPRMerged

#4404 [AutoPR adhybridhealthservice/resource-manager] typo: adhybridhealthservice/resource-manager/Microsoft.ADHybridHealthService
  services/adhybridhealthservice/mgmt/2014-01-01/adhybridhealthservice/models.go
Labels: RestPRMerged

#4413 [AutoPR resourcegraph/resource-manager] add resourcegraph to Go SDK
  profiles/latest/resourcegraph/mgmt/resourcegraph/models.go
  profiles/latest/resourcegraph/mgmt/resourcegraph/resourcegraphapi/models.go
  profiles/preview/resourcegraph/mgmt/resourcegraph/models.go
  profiles/preview/resourcegraph/mgmt/resourcegraph/resourcegraphapi/models.go
  services/resourcegraph/mgmt/2019-04-01/resourcegraph/client.go
  services/resourcegraph/mgmt/2019-04-01/resourcegraph/models.go
  services/resourcegraph/mgmt/2019-04-01/resourcegraph/operations.go
  services/resourcegraph/mgmt/2019-04-01/resourcegraph/resourcegraphapi/interfaces.go
  services/resourcegraph/mgmt/2019-04-01/resourcegraph/version.go
Labels: RestPRMerged

#4416 [AutoPR] adhybridhealthservice/resource-manager
  services/adhybridhealthservice/mgmt/2014-01-01/adhybridhealthservice/models.go
Labels: ServicePR

#4419 [AutoPR] resourcegraph/resource-manager
  profiles/latest/resourcegraph/mgmt/resourcegraph/models.go
  profiles/latest/resourcegraph/mgmt/resourcegraph/resourcegraphapi/models.go
  profiles/preview/resourcegraph/mgmt/resourcegraph/models.go
  profiles/preview/resourcegraph/mgmt/resourcegraph/resourcegraphapi/models.go
  services/resourcegraph/mgmt/2019-04-01/resourcegraph/client.go
  services/resourcegraph/mgmt/2019-04-01/resourcegraph/models.go
  services/resourcegraph/mgmt/2019-04-01/resourcegraph/operations.go
  services/resourcegraph/mgmt/2019-04-01/resourcegraph/resourcegraphapi/interfaces.go
  services/resourcegraph/mgmt/2019-04-01/resourcegraph/version.go
Labels: ServicePR

#4422 [AutoPR billing/resource-manager] [Hub Generated] Review request for Microsoft.Billing to add version 2018-11-01-preview
  services/preview/billing/mgmt/2018-11-01-preview/billing/billingapi/interfaces.go
  services/preview/billing/mgmt/2018-11-01-preview/billing/invoicesections.go
  services/preview/billing/mgmt/2018-11-01-preview/billing/invoicesectionsbybillingaccountname.go
  services/preview/billing/mgmt/2018-11-01-preview/billing/invoicesectionswithcreatesubscriptionpermission.go
  services/preview/billing/mgmt/2018-11-01-preview/billing/models.go
Labels: RestPRMerged

#4414 [AutoPR compute/resource-manager] Adding doNotRunExtensionsOnOverprovisionedVMs property to swagger
  services/compute/mgmt/2018-10-01/compute/models.go
Labels: RestPRMerged

#4386 [AutoPR hanaonazure/resource-manager] [Hub Generated] Review request for Microsoft.HanaOnAzure to add version 2017-11-03-preview
  profiles/preview/preview/hanaonazure/mgmt/hanaonazure/hanaonazureapi/models.go
  profiles/preview/preview/hanaonazure/mgmt/hanaonazure/models.go
  services/preview/hanaonazure/mgmt/2017-11-03-preview/hanaonazure/hanaonazureapi/interfaces.go
  services/preview/hanaonazure/mgmt/2017-11-03-preview/hanaonazure/models.go
  services/preview/hanaonazure/mgmt/2017-11-03-preview/hanaonazure/monitoring.go
Labels: RestPRMerged

#4423 [AutoPR] billing/resource-manager
  services/preview/billing/mgmt/2018-11-01-preview/billing/billingapi/interfaces.go
  services/preview/billing/mgmt/2018-11-01-preview/billing/invoicesections.go
  services/preview/billing/mgmt/2018-11-01-preview/billing/invoicesectionsbybillingaccountname.go
  services/preview/billing/mgmt/2018-11-01-preview/billing/invoicesectionswithcreatesubscriptionpermission.go
  services/preview/billing/mgmt/2018-11-01-preview/billing/models.go
Labels: ServicePR

#4426 [AutoPR] hanaonazure/resource-manager
  profiles/preview/preview/hanaonazure/mgmt/hanaonazure/hanaonazureapi/models.go
  profiles/preview/preview/hanaonazure/mgmt/hanaonazure/models.go
  services/preview/hanaonazure/mgmt/2017-11-03-preview/hanaonazure/hanaonazureapi/interfaces.go
  services/preview/hanaonazure/mgmt/2017-11-03-preview/hanaonazure/models.go
  services/preview/hanaonazure/mgmt/2017-11-03-preview/hanaonazure/monitoring.go
Labels: ServicePR

#4429 [AutoPR imagebuilder/resource-manager] [Hub Generated] Review request for Microsoft.VirtualMachineImages to add version 2019-02-01-preview
  profiles/preview/preview/virtualmachineimagebuilder/mgmt/virtualmachineimagebuilder/models.go
  profiles/preview/preview/virtualmachineimagebuilder/mgmt/virtualmachineimagebuilder/virtualmachineimagebuilderapi/models.go
  services/preview/virtualmachineimagebuilder/mgmt/2019-02-01-preview/virtualmachineimagebuilder/client.go
  services/preview/virtualmachineimagebuilder/mgmt/2019-02-01-preview/virtualmachineimagebuilder/models.go
  services/preview/virtualmachineimagebuilder/mgmt/2019-02-01-preview/virtualmachineimagebuilder/operations.go
  services/preview/virtualmachineimagebuilder/mgmt/2019-02-01-preview/virtualmachineimagebuilder/version.go
  services/preview/virtualmachineimagebuilder/mgmt/2019-02-01-preview/virtualmachineimagebuilder/virtualmachineimagebuilderapi/interfaces.go
  services/preview/virtualmachineimagebuilder/mgmt/2019-02-01-preview/virtualmachineimagebuilder/virtualmachineimagetemplates.go
Labels: RestPRMerged

#4431 [AutoPR cognitiveservices/data-plane/LUIS/Authoring] Revert some changes in authoring
  profiles/latest/cognitiveservices/luis/authoring/models.go
  profiles/preview/cognitiveservices/luis/authoring/models.go
  services/cognitiveservices/v2.0/luis/authoring/apps.go
  services/cognitiveservices/v2.0/luis/authoring/authoringapi/interfaces.go
  services/cognitiveservices/v2.0/luis/authoring/azureaccounts.go
  services/cognitiveservices/v2.0/luis/authoring/client.go
  services/cognitiveservices/v2.0/luis/authoring/examples.go
  services/cognitiveservices/v2.0/luis/authoring/features.go
  services/cognitiveservices/v2.0/luis/authoring/model.go
  services/cognitiveservices/v2.0/luis/authoring/models.go
  services/cognitiveservices/v2.0/luis/authoring/pattern.go
  services/cognitiveservices/v2.0/luis/authoring/permissions.go
  services/cognitiveservices/v2.0/luis/authoring/settings.go
  services/cognitiveservices/v2.0/luis/authoring/train.go
  services/cognitiveservices/v2.0/luis/authoring/versions.go
Labels: RestPRMerged

#4433 [AutoPR blueprint/resource-manager] Blueprints API update for excludedPrincipals and whoIsBlueprint
  profiles/preview/preview/blueprint/mgmt/blueprint/models.go
  services/preview/blueprint/mgmt/2018-11-01-preview/blueprint/artifacts.go
  services/preview/blueprint/mgmt/2018-11-01-preview/blueprint/assignmentoperations.go
  services/preview/blueprint/mgmt/2018-11-01-preview/blueprint/assignments.go
  services/preview/blueprint/mgmt/2018-11-01-preview/blueprint/blueprintapi/interfaces.go
  services/preview/blueprint/mgmt/2018-11-01-preview/blueprint/blueprints.go
  services/preview/blueprint/mgmt/2018-11-01-preview/blueprint/models.go
  services/preview/blueprint/mgmt/2018-11-01-preview/blueprint/publishedartifacts.go
  services/preview/blueprint/mgmt/2018-11-01-preview/blueprint/publishedblueprints.go
Labels: RestPRMerged

#4434 [AutoPR security/resource-manager] Security: 2017-08-01-preview - Introduce IoT security groups resource
  profiles/preview/preview/security/mgmt/security/models.go
  profiles/preview/preview/security/mgmt/security/securityapi/models.go
  services/preview/security/mgmt/v1.0/security/adaptivenetworkhardenings.go
  services/preview/security/mgmt/v1.0/security/models.go
  services/preview/security/mgmt/v1.0/security/securityapi/interfaces.go
  services/preview/security/mgmt/v2.0/security/adaptivenetworkhardenings.go
  services/preview/security/mgmt/v2.0/security/models.go
  services/preview/security/mgmt/v2.0/security/securityapi/interfaces.go
Labels: RestPRMerged

#4430 [AutoPR] imagebuilder/resource-manager
  profiles/preview/preview/virtualmachineimagebuilder/mgmt/virtualmachineimagebuilder/models.go
  profiles/preview/preview/virtualmachineimagebuilder/mgmt/virtualmachineimagebuilder/virtualmachineimagebuilderapi/models.go
  services/preview/virtualmachineimagebuilder/mgmt/2019-02-01-preview/virtualmachineimagebuilder/client.go
  services/preview/virtualmachineimagebuilder/mgmt/2019-02-01-preview/virtualmachineimagebuilder/models.go
  services/preview/virtualmachineimagebuilder/mgmt/2019-02-01-preview/virtualmachineimagebuilder/operations.go
  services/preview/virtualmachineimagebuilder/mgmt/2019-02-01-preview/virtualmachineimagebuilder/version.go
  services/preview/virtualmachineimagebuilder/mgmt/2019-02-01-preview/virtualmachineimagebuilder/virtualmachineimagebuilderapi/interfaces.go
  services/preview/virtualmachineimagebuilder/mgmt/2019-02-01-preview/virtualmachineimagebuilder/virtualmachineimagetemplates.go
Labels: ServicePR

#4432 [AutoPR] cognitiveservices/data-plane/LUIS/Authoring
  profiles/latest/cognitiveservices/luis/authoring/models.go
  profiles/preview/cognitiveservices/luis/authoring/models.go
  services/cognitiveservices/v2.0/luis/authoring/apps.go
  services/cognitiveservices/v2.0/luis/authoring/authoringapi/interfaces.go
  services/cognitiveservices/v2.0/luis/authoring/azureaccounts.go
  services/cognitiveservices/v2.0/luis/authoring/client.go
  services/cognitiveservices/v2.0/luis/authoring/examples.go
  services/cognitiveservices/v2.0/luis/authoring/features.go
  services/cognitiveservices/v2.0/luis/authoring/model.go
  services/cognitiveservices/v2.0/luis/authoring/models.go
  services/cognitiveservices/v2.0/luis/authoring/pattern.go
  services/cognitiveservices/v2.0/luis/authoring/permissions.go
  services/cognitiveservices/v2.0/luis/authoring/settings.go
  services/cognitiveservices/v2.0/luis/authoring/train.go
  services/cognitiveservices/v2.0/luis/authoring/versions.go
Labels: ServicePR

#4437 [AutoPR network/resource-manager/frontdoor/resource-manager] typo: frontdoor/resource-manager/Microsoft.Network
  Gopkg.lock
  services/network/mgmt/2018-12-01/network/models.go
  services/preview/frontdoor/mgmt/2019-04-01/frontdoor/models.go
  services/preview/frontdoor/mgmt/2019-04-01/frontdoor/policies.go
Labels: RestPRMerged

#4435 [AutoPR] blueprint/resource-manager
  profiles/preview/preview/blueprint/mgmt/blueprint/models.go
  services/preview/blueprint/mgmt/2018-11-01-preview/blueprint/artifacts.go
  services/preview/blueprint/mgmt/2018-11-01-preview/blueprint/assignmentoperations.go
  services/preview/blueprint/mgmt/2018-11-01-preview/blueprint/assignments.go
  services/preview/blueprint/mgmt/2018-11-01-preview/blueprint/blueprintapi/interfaces.go
  services/preview/blueprint/mgmt/2018-11-01-preview/blueprint/blueprints.go
  services/preview/blueprint/mgmt/2018-11-01-preview/blueprint/models.go
  services/preview/blueprint/mgmt/2018-11-01-preview/blueprint/publishedartifacts.go
  services/preview/blueprint/mgmt/2018-11-01-preview/blueprint/publishedblueprints.go
Labels: ServicePR

#4436 [AutoPR] security/resource-manager
  profiles/preview/preview/security/mgmt/security/models.go
  profiles/preview/preview/security/mgmt/security/securityapi/models.go
  services/preview/security/mgmt/v1.0/security/adaptivenetworkhardenings.go
  services/preview/security/mgmt/v1.0/security/models.go
  services/preview/security/mgmt/v1.0/security/securityapi/interfaces.go
  services/preview/security/mgmt/v2.0/security/adaptivenetworkhardenings.go
  services/preview/security/mgmt/v2.0/security/models.go
  services/preview/security/mgmt/v2.0/security/securityapi/interfaces.go
Labels: ServicePR

#4438 [AutoPR cognitiveservices/data-plane/Face] typo: cognitiveservices/data-plane/Face/stable/v1
  services/cognitiveservices/v1.0/face/largefacelist.go
  services/cognitiveservices/v1.0/face/largepersongroup.go
  services/cognitiveservices/v1.0/face/persongroup.go
Labels: RestPRMerged

#4439 [AutoPR] cognitiveservices/data-plane/Face
  services/cognitiveservices/v1.0/face/largefacelist.go
  services/cognitiveservices/v1.0/face/largepersongroup.go
  services/cognitiveservices/v1.0/face/persongroup.go
Labels: ServicePR

#4420 [AutoPR applicationinsights/resource-manager] [App Insights control plane] fix: validate subId, apiVersion, rgName
  services/appinsights/mgmt/2015-05-01/insights/analyticsitems.go
  services/appinsights/mgmt/2015-05-01/insights/annotations.go
  services/appinsights/mgmt/2015-05-01/insights/apikeys.go
  services/appinsights/mgmt/2015-05-01/insights/componentavailablefeatures.go
  services/appinsights/mgmt/2015-05-01/insights/componentcurrentbillingfeatures.go
  services/appinsights/mgmt/2015-05-01/insights/componentfeaturecapabilities.go
  services/appinsights/mgmt/2015-05-01/insights/componentquotastatus.go
  services/appinsights/mgmt/2015-05-01/insights/components.go
  services/appinsights/mgmt/2015-05-01/insights/exportconfigurations.go
  services/appinsights/mgmt/2015-05-01/insights/favorites.go
  services/appinsights/mgmt/2015-05-01/insights/proactivedetectionconfigurations.go
  services/appinsights/mgmt/2015-05-01/insights/webtestlocations.go
  services/appinsights/mgmt/2015-05-01/insights/webtests.go
  services/appinsights/mgmt/2015-05-01/insights/workbooks.go
  services/appinsights/mgmt/2015-05-01/insights/workitemconfigurations.go
Labels: RestPRMerged

#4397 [AutoPR storage/resource-manager] [DO NOT REVIEW/MERGE] Swagger for Lease Container API from Oct17 to latest
  profiles/latest/storage/mgmt/storage/models.go
  profiles/preview/preview/storage/mgmt/storage/models.go
  profiles/preview/storage/mgmt/storage/models.go
  services/preview/storage/mgmt/2018-03-01-preview/storage/blobcontainers.go
  services/preview/storage/mgmt/2018-03-01-preview/storage/models.go
  services/preview/storage/mgmt/2018-03-01-preview/storage/storageapi/interfaces.go
  services/storage/mgmt/2018-02-01/storage/blobcontainers.go
  services/storage/mgmt/2018-02-01/storage/models.go
  services/storage/mgmt/2018-02-01/storage/storageapi/interfaces.go
  services/storage/mgmt/2018-07-01/storage/blobcontainers.go
  services/storage/mgmt/2018-07-01/storage/models.go
  services/storage/mgmt/2018-07-01/storage/storageapi/interfaces.go
  services/storage/mgmt/2018-11-01/storage/blobcontainers.go
  services/storage/mgmt/2018-11-01/storage/models.go
  services/storage/mgmt/2018-11-01/storage/storageapi/interfaces.go
Labels: RestPRMerged
