Repository Azure/azure-sdk-for-go, pull requests merged in 2020-10, with the labels that each got.

#12559 Sync eng/common directory with azure-sdk-tools for PR 1031
  eng/common/scripts/New-ReleaseAsset.ps1
Labels: Central-EngSys, EngSys

#12650 Sync eng/common directory with azure-sdk-tools for PR 1052
  eng/common/pipelines/templates/steps/create-pull-request.yml
  eng/common/scripts/Add-Issue-Comment.ps1
  eng/common/scripts/Queue-Pipeline.ps1
  eng/common/scripts/git-branch-push.ps1
  eng/common/scripts/modules/ChangeLog-Operations.psm1
  eng/common/scripts/modules/Package-Properties.psm1
Labels: Central-EngSys, EngSys

#12682 Sync eng/common directory with azure-sdk-tools for PR 1066
  eng/common/scripts/copy-docs-to-blobstorage.ps1
Labels: Central-EngSys, EngSys

#12681 Sync eng/common directory with azure-sdk-tools for PR 1077
  eng/common/TestResources/New-TestResources.ps1
  eng/common/TestResources/New-TestResources.ps1.md
  eng/common/TestResources/README.md
Labels: Central-EngSys, EngSys

#12693 Sync eng/common directory with azure-sdk-tools for PR 1083
  eng/common/TestResources/New-TestResources.ps1
  eng/common/TestResources/README.md
Labels: Central-EngSys, EngSys

#12727 Sync eng/common directory with azure-sdk-tools for PR 1081
  eng/common/README.md
  eng/common/scripts/Add-Issue-Comment.ps1
  eng/common/scripts/Add-IssueComment.ps1
  eng/common/scripts/Add-IssueLabels.ps1
  eng/common/scripts/Invoke-GitHubAPI.ps1
  eng/common/scripts/common.ps1
Labels: Central-EngSys, EngSys, auto-merge

#12750 Sync eng/common directory with azure-sdk-tools for PR 1088
  eng/common/scripts/Delete-RemoteBranches.ps1
  eng/common/scripts/Invoke-GitHubAPI.ps1
Labels: Central-EngSys, EngSys, auto-merge

#12708 Fixed 2 minor typos
  sdk/azidentity/aad_identity_client.go
  sdk/azidentity/authorization_code_credential.go
Labels: customer-reported

#12815 Sync eng/common directory with azure-sdk-tools for PR 1091
  eng/common/pipelines/templates/steps/create-pull-request.yml
  eng/common/scripts/Add-IssueComment.ps1
  eng/common/scripts/Add-IssueLabels.ps1
  eng/common/scripts/Delete-RemoteBranches.ps1
  eng/common/scripts/Get-PullRequestCreator.ps1
  eng/common/scripts/Invoke-GitHubAPI.ps1
  eng/common/scripts/Submit-PullRequest.ps1
  eng/common/scripts/add-pullrequest-reviewers.ps1
Labels: Central-EngSys, EngSys

#12808 Sync eng/common directory with azure-sdk-tools for PR 1062
  eng/common/scripts/Verify-Links.ps1
Labels: Central-EngSys, EngSys, auto-merge

#12833 Sync eng/common directory with azure-sdk-tools for PR 1103
  eng/common/scripts/copy-docs-to-blobstorage.ps1
Labels: Central-EngSys, EngSys

#12852 Sync eng/common directory with azure-sdk-tools for PR 1019
  eng/common/pipelines/templates/steps/verify-links.yml
Labels: Central-EngSys, EngSys

#12853 Sync eng/common directory with azure-sdk-tools for PR 1106
  eng/common/scripts/copy-docs-to-blobstorage.ps1
Labels: Central-EngSys, EngSys

#12854 Sync eng/common directory with azure-sdk-tools for PR 968
  eng/common/pipelines/templates/steps/publish-blobs.yml
  eng/common/scripts/Package-Properties.ps1
  eng/common/scripts/common.ps1
  eng/common/scripts/copy-docs-to-blobstorage.ps1
Labels: Central-EngSys, EngSys

#12876 Sync eng/common directory with azure-sdk-tools for PR 1102
  eng/common/pipelines/templates/steps/create-pull-request.yml
  eng/common/pipelines/templates/steps/docs-metadata-release.yml
  eng/common/scripts/Invoke-GitHubAPI.ps1
  eng/common/scripts/Submit-PullRequest.ps1
Labels: Central-EngSys, EngSys

#12883 Sync eng/common directory with azure-sdk-tools for PR 1128
  eng/common/scripts/modules/ChangeLog-Operations.psm1
Labels: Central-EngSys, EngSys

#12885 Sync eng/common directory with azure-sdk-tools for PR 1104
  eng/common/pipelines/templates/steps/install-pipeline-generation.yml
  eng/common/pipelines/templates/steps/prepare-pipelines.yml
Labels: Central-EngSys, EngSys

#12888 Sync eng/common directory with azure-sdk-tools for PR 1129
  eng/common/pipelines/templates/steps/prepare-pipelines.yml
Labels: Central-EngSys, EngSys

#12894 Sync eng/common directory with azure-sdk-tools for PR 1132
  eng/common/pipelines/templates/steps/install-pipeline-generation.yml
  eng/common/pipelines/templates/steps/prepare-pipelines.yml
Labels: Central-EngSys, EngSys

#12911 Sync eng/common directory with azure-sdk-tools for PR 1133
  eng/common/pipelines/templates/steps/prepare-pipelines.yml
Labels: Central-EngSys, EngSys

#12890 Sync eng/common directory with azure-sdk-tools for PR 1127
  eng/common/TestResources/New-TestResources.ps1
Labels: Central-EngSys, EngSys

#12931 Sync eng/common directory with azure-sdk-tools for PR 1131
  eng/common/pipelines/templates/steps/create-pull-request.yml
  eng/common/pipelines/templates/steps/docs-metadata-release.yml
  eng/common/scripts/Invoke-GitHubAPI.ps1
Labels: Central-EngSys, EngSys

#12961 Sync eng/common directory with azure-sdk-tools for PR 1109
  eng/common/pipelines/templates/steps/docs-metadata-release.yml
Labels: Central-EngSys, EngSys

#12967 Sync eng/common directory with azure-sdk-tools for PR 1136
  eng/common/scripts/Delete-RemoteBranches.ps1
Labels: Central-EngSys, EngSys

#12966 Sync eng/common directory with azure-sdk-tools for PR 1135
  eng/common/TestResources/New-TestResources.ps1.md
  eng/common/TestResources/Remove-TestResources.ps1.md
  eng/common/scripts/Verify-Links.ps1
Labels: Central-EngSys, EngSys

#12969 Sync eng/common directory with azure-sdk-tools for PR 1130
  eng/common/README.md
Labels: Central-EngSys, EngSys

#12968 Sync eng/common directory with azure-sdk-tools for PR 1137
  eng/common/TestResources/AzurePowerShellV4/Utility.ps1
  eng/common/TestResources/Import-AzModules.ps1
  eng/common/TestResources/deploy-test-resources.yml
  eng/common/TestResources/remove-test-resources.yml
  eng/common/TestResources/setup-az-modules.yml
Labels: Central-EngSys, EngSys

#12997 Sync eng/common directory with azure-sdk-tools for PR 1144
  eng/common/pipelines/templates/steps/install-pipeline-generation.yml
Labels: Central-EngSys, EngSys

#13033 Sync eng/common directory with azure-sdk-tools for PR 1146
  eng/common/TestResources/Remove-TestResources.ps1
Labels: Central-EngSys, EngSys

#13035 Sync eng/common directory with azure-sdk-tools for PR 1148
  eng/common/README.md
Labels: Central-EngSys, EngSys

#13092 Sync eng/common directory with azure-sdk-tools for PR 1158
  eng/common/pipelines/templates/steps/verify-path-length.yml
Labels: Central-EngSys, EngSys

#13093 Sync eng/common directory with azure-sdk-tools for PR 1154
  eng/common/scripts/git-branch-push.ps1
  eng/common/scripts/modules/ChangeLog-Operations.psm1
Labels: Central-EngSys, EngSys
