Repository Azure/azure-sdk-for-go, pull requests merged in 2021-07, with the labels that each got.

#14950 Sync eng/common directory with azure-sdk-tools for PR 1768
  eng/common/scripts/Update-DocsMsMetadata.ps1
Labels: Central-EngSys, EngSys

#14956 [Tables] ci fix
  sdk/tables/aztable/ci.yml
  sdk/tables/ci.yml
Labels: Tables, auto-merge

#14962 Sync eng/common directory with azure-sdk-tools for PR 1772
  eng/common/scripts/ChangeLog-Operations.ps1
Labels: Central-EngSys, EngSys

#14958 Skip live test generation in prepare-pipelines
  eng/pipelines/prepare-pipelines.yml
Labels: Central-EngSys

#14960 [Tables] Add post-request validation of entity
  sdk/tables/aztable/errors.go
  sdk/tables/aztable/recordings/TestTableClient_Cosmos/TestInvalidEntity-variables.yaml
  sdk/tables/aztable/recordings/TestTableClient_Cosmos/TestInvalidEntity.yaml
  sdk/tables/aztable/recordings/TestTableClient_Storage/TestInvalidEntity-variables.yaml
  sdk/tables/aztable/recordings/TestTableClient_Storage/TestInvalidEntity.yaml
  sdk/tables/aztable/table_client.go
  sdk/tables/aztable/table_client_test.go
  sdk/tables/aztable/zc_table_constants.go
Labels: Tables

#14988 onboard track2: containerregistry
  sdk/containerregistry/armcontainerregistry/LICENSE.txt
  sdk/containerregistry/armcontainerregistry/ci.yml
Labels: Container Registry

#14995 Sync eng/common directory with azure-sdk-tools for PR 1782
  eng/common/pipelines/templates/jobs/archetype-sdk-tests-generate.yml
Labels: Central-EngSys, EngSys

#14970 Sync eng/common directory with azure-sdk-tools for PR 1767
  eng/common/TestResources/New-TestResources.ps1
  eng/common/TestResources/deploy-test-resources.yml
Labels: Central-EngSys, EngSys

#14961 [Tables] changing QueryOptions param to be a ptr
  sdk/tables/aztable/table_client.go
  sdk/tables/aztable/table_client_test.go
  sdk/tables/aztable/table_service_client.go
  sdk/tables/aztable/table_service_client_test.go
  sdk/tables/aztable/zt_table_recorded_tests.go
Labels: Tables

#15021 Sync eng/common directory with azure-sdk-tools for PR 1780
  eng/common/pipelines/templates/steps/sparse-checkout.yml
Labels: Central-EngSys, EngSys

#15028 [Tables] linting Fixes
  sdk/tables/aztable/shared_policy_shared_key_credential.go
  sdk/tables/aztable/table_client.go
  sdk/tables/aztable/table_client_test.go
  sdk/tables/aztable/table_pagers.go
  sdk/tables/aztable/table_pagers_test.go
  sdk/tables/aztable/table_service_client.go
  sdk/tables/aztable/table_service_client_test.go
  sdk/tables/aztable/table_transactional_batch.go
  sdk/tables/aztable/zc_table_constants.go
  sdk/tables/aztable/zt_table_recorded_tests.go
Labels: Tables

#14872 azidentity: Add environment variable for resource ID
  sdk/azidentity/managed_identity_credential.go
  sdk/azidentity/managed_identity_credential_test.go
Labels: Azure.Identity, auto-merge

#15040 Update CODEOWNERS
  .github/CODEOWNERS
Labels: auto-merge

#15044 Sync eng/common directory with azure-sdk-tools for PR 1808
  eng/common/scripts/FilterPoliCheckResults.ps1
Labels: Central-EngSys, EngSys

#14992 Track2 release: containerregistry
  sdk/containerregistry/armcontainerregistry/CHANGELOG.md
  sdk/containerregistry/armcontainerregistry/README.md
  sdk/containerregistry/armcontainerregistry/_meta.json
  sdk/containerregistry/armcontainerregistry/go.mod
  sdk/containerregistry/armcontainerregistry/go.sum
  sdk/containerregistry/armcontainerregistry/go_mod_tidy_hack.go
  sdk/containerregistry/armcontainerregistry/zz_generated_agentpools_client.go
  sdk/containerregistry/armcontainerregistry/zz_generated_connectedregistries_client.go
  sdk/containerregistry/armcontainerregistry/zz_generated_constants.go
  sdk/containerregistry/armcontainerregistry/zz_generated_exportpipelines_client.go
  sdk/containerregistry/armcontainerregistry/zz_generated_importpipelines_client.go
  sdk/containerregistry/armcontainerregistry/zz_generated_models.go
  sdk/containerregistry/armcontainerregistry/zz_generated_operations_client.go
  sdk/containerregistry/armcontainerregistry/zz_generated_pagers.go
  sdk/containerregistry/armcontainerregistry/zz_generated_pipelineruns_client.go
  sdk/containerregistry/armcontainerregistry/zz_generated_pollers.go
  sdk/containerregistry/armcontainerregistry/zz_generated_polymorphic_helpers.go
  sdk/containerregistry/armcontainerregistry/zz_generated_privateendpointconnections_client.go
  sdk/containerregistry/armcontainerregistry/zz_generated_registries_client.go
  sdk/containerregistry/armcontainerregistry/zz_generated_replications_client.go
  sdk/containerregistry/armcontainerregistry/zz_generated_response_types.go
  sdk/containerregistry/armcontainerregistry/zz_generated_runs_client.go
  sdk/containerregistry/armcontainerregistry/zz_generated_scopemaps_client.go
  sdk/containerregistry/armcontainerregistry/zz_generated_taskruns_client.go
  sdk/containerregistry/armcontainerregistry/zz_generated_tasks_client.go
  sdk/containerregistry/armcontainerregistry/zz_generated_time_rfc3339.go
  sdk/containerregistry/armcontainerregistry/zz_generated_tokens_client.go
  sdk/containerregistry/armcontainerregistry/zz_generated_webhooks_client.go
Labels: Container Registry

#15016 [Tables] Adding swagger.md
  sdk/tables/autorest.md
  sdk/tables/aztable/table_service_client.go
  sdk/tables/aztable/zz_generated_connection.go
  sdk/tables/aztable/zz_generated_constants.go
  sdk/tables/aztable/zz_generated_models.go
Labels: Tables

#14930 Sync eng/common directory with azure-sdk-tools for PR 1748
  eng/common/pipelines/templates/steps/bypass-local-dns.yml
Labels: Central-EngSys, EngSys

#15086 [Cosmos DB] Base client struct and options
  .github/CODEOWNERS
  sdk/cosmos/azcosmos/consistency_level.go
  sdk/cosmos/azcosmos/cosmos_client.go
  sdk/cosmos/azcosmos/cosmos_client_connection.go
  sdk/cosmos/azcosmos/cosmos_client_options.go
  sdk/cosmos/azcosmos/cosmos_client_options_test.go
  sdk/cosmos/azcosmos/cosmos_headers.go
  sdk/cosmos/azcosmos/doc.go
  sdk/cosmos/azcosmos/resource_throttle_retry_policy.go
Labels: Cosmos

#15027 [Tables] Add get/set access policy
  sdk/tables/aztable/recordings/TestTableClient_Cosmos/TestSetAccessPolicy-variables.yaml
  sdk/tables/aztable/recordings/TestTableClient_Cosmos/TestSetEmptyAccessPolicy-variables.yaml
  sdk/tables/aztable/recordings/TestTableClient_Cosmos/TestSetMultipleAccessPolicies-variables.yaml
  sdk/tables/aztable/recordings/TestTableClient_Cosmos/TestSetNullAccessPolicy-variables.yaml
  sdk/tables/aztable/recordings/TestTableClient_Cosmos/TestSetTooManyAccessPolicies-variables.yaml
  sdk/tables/aztable/recordings/TestTableClient_Storage/TestSetAccessPolicy-variables.yaml
  sdk/tables/aztable/recordings/TestTableClient_Storage/TestSetAccessPolicy.yaml
  sdk/tables/aztable/recordings/TestTableClient_Storage/TestSetEmptyAccessPolicy-variables.yaml
  sdk/tables/aztable/recordings/TestTableClient_Storage/TestSetEmptyAccessPolicy.yaml
  sdk/tables/aztable/recordings/TestTableClient_Storage/TestSetMultipleAccessPolicies-variables.yaml
  sdk/tables/aztable/recordings/TestTableClient_Storage/TestSetMultipleAccessPolicies.yaml
  sdk/tables/aztable/recordings/TestTableClient_Storage/TestSetNullAccessPolicy-variables.yaml
  sdk/tables/aztable/recordings/TestTableClient_Storage/TestSetNullAccessPolicy.yaml
  sdk/tables/aztable/recordings/TestTableClient_Storage/TestSetTooManyAccessPolicies-variables.yaml
  sdk/tables/aztable/recordings/TestTableClient_Storage/TestSetTooManyAccessPolicies.yaml
  sdk/tables/aztable/table_access_policy_test.go
  sdk/tables/aztable/table_client.go
  sdk/tables/aztable/zc_table_constants.go
  sdk/tables/aztable/zt_table_recorded_tests.go
Labels: Tables

#15017 Build.ps1 improvements
  eng/scripts/build.ps1
Labels: CodeGen

#15103 [Core] Renamings for AuthPolicies
  sdk/azcore/credential.go
  sdk/azcore/policy_anonymous_credential.go
  sdk/azcore/policy_anonymous_credential_test.go
  sdk/azcore/request_test.go
Labels: Azure.Core

#15104 [Core] Rename AnonymousCredential
  sdk/azcore/policy_anonymous_credential.go
  sdk/azcore/policy_anonymous_credential_test.go
Labels: Azure.Core

#15085 [EngSys] Combine Build Build and Build Test pipelines
  eng/pipelines/templates/jobs/archetype-sdk-client-samples.yml
  eng/pipelines/templates/jobs/archetype-sdk-client.yml
  eng/pipelines/templates/steps/analyze.yml
  eng/pipelines/templates/steps/build-test.yml
  eng/pipelines/templates/steps/build.yml
  eng/scripts/build.ps1
  eng/scripts/get_test_dirs.ps1
  sdk/agfood/armagfood/ci.yml
  sdk/agrifood/armagrifood/ci.yml
  sdk/authorization/armauthorization/ci.yml
  sdk/azcore/ci.yml
  sdk/azidentity/ci.yml
  sdk/compute/armcompute/ci.yml
  sdk/containerregistry/armcontainerregistry/ci.yml
  sdk/containerservice/armcontainerservice/ci.yml
  sdk/keyvault/armkeyvault/ci.yml
  sdk/monitor/armmonitor/ci.yml
  sdk/network/armnetwork/ci.yml
  sdk/privatedns/armprivatedns/ci.yml
  sdk/profiles/ci.yml
  sdk/resources/armresources/ci.yml
  sdk/samples/azidentity/SDKV1Adapter/example_SDKV1_test.go
  sdk/samples/ci.yml
  sdk/storage/armstorage/ci.yml
  sdk/synapse/azartifacts/ci.yml
  sdk/web/armweb/ci.yml
Labels: EngSys

#15126 Sync eng/common directory with azure-sdk-tools for PR 1827
  eng/common/scripts/Update-DocsMsMetadata.ps1
  eng/common/scripts/update-docs-metadata.ps1
Labels: Central-EngSys, EngSys

#15132 track2 add servicebus ci.yml and LICENSE.txt file
  sdk/servicebus/armservicebus/LICENSE.txt
  sdk/servicebus/armservicebus/ci.yml
Labels: Service Bus

#15076 [EngSys] adding coverage tools
  eng/config.json
  eng/pipelines/templates/jobs/archetype-sdk-client.yml
  eng/pipelines/templates/steps/build-test.yml
  eng/scripts/create_coverage.ps1
  eng/scripts/get_module_dirs.ps1
  eng/scripts/get_test_dirs.ps1
  sdk/to/ci.yml
  sdk/to/to.go
  tools/internal/coverage/go.mod
  tools/internal/coverage/main.go
Labels: EngSys

#15099 [Tables] change Query to List
  sdk/tables/aztable/entity_test.go
  sdk/tables/aztable/models.go
  sdk/tables/aztable/recordings/TestServiceClient_Cosmos/TestListTables-variables.yaml
  sdk/tables/aztable/recordings/TestServiceClient_Cosmos/TestListTables.yaml
  sdk/tables/aztable/recordings/TestServiceClient_Storage/TestListTables-variables.yaml
  sdk/tables/aztable/recordings/TestServiceClient_Storage/TestListTables.yaml
  sdk/tables/aztable/recordings/TestTableClient_Cosmos/TestListEntities-variables.yaml
  sdk/tables/aztable/recordings/TestTableClient_Cosmos/TestListEntities.yaml
  sdk/tables/aztable/recordings/TestTableClient_Storage/TestListEntities-variables.yaml
  sdk/tables/aztable/recordings/TestTableClient_Storage/TestListEntities.yaml
  sdk/tables/aztable/table_batch_test.go
  sdk/tables/aztable/table_client.go
  sdk/tables/aztable/table_client_test.go
  sdk/tables/aztable/table_pagers.go
  sdk/tables/aztable/table_service_client.go
  sdk/tables/aztable/table_service_client_test.go
  sdk/tables/aztable/zt_table_recorded_tests.go
Labels: Tables

#15157 Sync eng/common directory with azure-sdk-tools for PR 1848
  eng/common/docgeneration/Generate-DocIndex.ps1
  eng/common/docgeneration/templates/matthews/partials/head.tmpl.partial
Labels: Central-EngSys, EngSys

#14980 Introduce the migration guide to track 2 modules
  documentation/MIGRATION_GUIDE.md
Labels: Mgmt

#15096 Add Documentation for Track 2 Management SDK
  README.md
  documentation/new-version-quickstart.md
  documentation/previous-versions-quickstart.md
Labels: Mgmt, docs

#15159 Sync eng/common directory with azure-sdk-tools for PR 1847
  eng/common/scripts/Create-APIReview.ps1
Labels: Central-EngSys, EngSys

#15162 [Internal] fixing lint issues
  sdk/internal/ci.yml
  sdk/internal/mock/mock.go
  sdk/internal/mock/mock_test.go
  sdk/internal/recording/recording.go
  sdk/internal/recording/recording_test.go
  sdk/internal/recording/request_matcher.go
  sdk/internal/recording/sanitizer.go
  sdk/internal/recording/sanitizer_test.go
  sdk/internal/uuid/uuid.go
Labels: auto-merge

#15189 Sync eng/common directory with azure-sdk-tools for PR 1851
  eng/common/scripts/stress-testing/deploy-stress-tests.ps1
  eng/common/scripts/stress-testing/find-all-stress-packages.ps1
Labels: Central-EngSys, EngSys
