Repository Azure/azure-sdk-for-go, pull requests merged in 2021-04, with the labels that each got.

#14481 Sync eng/common directory with azure-sdk-tools for PR 1525
  eng/common/TestResources/New-TestResources.ps1
  eng/common/TestResources/New-TestResources.ps1.md
  eng/common/TestResources/README.md
  eng/common/TestResources/Remove-TestResources.ps1
  eng/common/TestResources/Remove-TestResources.ps1.md
  eng/common/TestResources/Update-TestResources.cmd
  eng/common/TestResources/Update-TestResources.ps1
  eng/common/TestResources/Update-TestResources.ps1.md
Labels: Central-EngSys, EngSys

#14487 Sync eng/common directory with azure-sdk-tools for PR 1535
  eng/common/pipelines/templates/jobs/archetype-sdk-tests-generate.yml
  eng/common/scripts/job-matrix/samples/matrix-test.yml
Labels: Central-EngSys, EngSys

#14441 Initial generation of the aztables module
  sdk/tables/aztables/CHANGELOG.md
  sdk/tables/aztables/LICENSE
  sdk/tables/aztables/README.md
  sdk/tables/aztables/ci.yml
  sdk/tables/aztables/go.mod
  sdk/tables/aztables/go.sum
  sdk/tables/aztables/shared_policy_shared_key_credential.go
  sdk/tables/aztables/tableClient.go
  sdk/tables/aztables/tableClient_test.go
  sdk/tables/aztables/zc_client_options.go
  sdk/tables/aztables/zt_test.go
  sdk/tables/aztables/zz_generated_connection.go
  sdk/tables/aztables/zz_generated_constants.go
  sdk/tables/aztables/zz_generated_models.go
  sdk/tables/aztables/zz_generated_service.go
  sdk/tables/aztables/zz_generated_table.go
  sdk/tables/aztables/zz_generated_time_rfc1123.go
  sdk/tables/aztables/zz_generated_time_rfc3339.go
Labels: Tables

#14510 Sync eng/common directory with azure-sdk-tools for PR 1546
  eng/common/TestResources/Remove-TestResources.ps1
  eng/common/TestResources/Update-TestResources.ps1
Labels: Central-EngSys, EngSys

#14512 Sync eng/common directory with azure-sdk-tools for PR 1548
  eng/common/TestResources/New-TestResources.ps1
  eng/common/TestResources/Remove-TestResources.ps1
  eng/common/TestResources/Update-TestResources.ps1
Labels: Central-EngSys, EngSys

#14507 Sync eng/common directory with azure-sdk-tools for PR 1515
  eng/common/pipelines/templates/steps/retain-run.yml
  eng/common/scripts/Add-RetentionLease.ps1
  eng/common/scripts/Invoke-DevOpsAPI.ps1
Labels: Central-EngSys, EngSys

#14494 Migrate license to MIT
  README.md
Labels: customer-reported

#14495 Migrate license to MIT
  .github/PULL_REQUEST_TEMPLATE.md
Labels: customer-reported

#14514 Sync eng/common directory with azure-sdk-tools for PR 1534
  eng/common/pipelines/templates/steps/docs-metadata-release.yml
  eng/common/scripts/update-docs-ci.ps1
Labels: Central-EngSys, EngSys

#14515 Sync eng/common directory with azure-sdk-tools for PR 1551
  eng/common/pipelines/templates/steps/sparse-checkout.yml
Labels: Central-EngSys, EngSys

#14516 Sync eng/common directory with azure-sdk-tools for PR 1504
  eng/common/pipelines/templates/steps/daily-dev-build-variable.yml
Labels: Central-EngSys, EngSys

#14517 Sync eng/common directory with azure-sdk-tools for PR 1553
  eng/common/pipelines/templates/steps/retain-run.yml
Labels: Central-EngSys, EngSys

#14522 Sync eng/common directory with azure-sdk-tools for PR 1552
  eng/common/pipelines/templates/steps/docs-metadata-release.yml
Labels: Central-EngSys, EngSys

#14532 Sync eng/common directory with azure-sdk-tools for PR 1557
  eng/common/pipelines/templates/steps/verify-agent-os.yml
Labels: Central-EngSys, EngSys

#14533 Sync eng/common directory with azure-sdk-tools for PR 1555
  eng/common/pipelines/templates/steps/verify-samples.yml
  eng/common/scripts/Test-SampleMetadata.ps1
Labels: Central-EngSys, EngSys

#14535 Sync eng/common directory with azure-sdk-tools for PR 1559
  eng/common/pipelines/templates/steps/verify-samples.yml
  eng/common/scripts/Test-SampleMetadata.ps1
Labels: Central-EngSys, EngSys

#14496 Send the -d switch to gofmt
  azure-pipelines.yml
  eng/pipelines/templates/steps/analyze.yml
Labels: EngSys

#14546 Sync eng/common directory with azure-sdk-tools for PR 1560
  eng/common/TestResources/build-test-resource-config.yml
Labels: Central-EngSys, EngSys

#14551 Sync eng/common directory with azure-sdk-tools for PR 1563
  eng/common/TestResources/build-test-resource-config.yml
Labels: Central-EngSys, EngSys

#14549 Track2: azcore log remove some duplicate code
  sdk/azcore/log.go
Labels: Track2

#14557 Sync eng/common directory with azure-sdk-tools for PR 1564
  eng/common/scripts/Package-Properties.ps1
Labels: Central-EngSys, EngSys

#14558 Sync eng/common directory with azure-sdk-tools for PR 1558
  eng/common/pipelines/templates/steps/set-default-branch.yml
Labels: Central-EngSys, EngSys

#14553 Sync eng/common directory with azure-sdk-tools for PR 1565
  eng/common/pipelines/templates/steps/retain-run.yml
  eng/common/scripts/Add-RetentionLease.ps1
Labels: Central-EngSys, EngSys

#14342 [Go][Track2] Added Blob/Container Lease Client
  sdk/storage/azblob/zc_blobClient.go
  sdk/storage/azblob/zc_blobRequestOptions.go
  sdk/storage/azblob/zc_client_options.go
  sdk/storage/azblob/zc_containerClient.go
  sdk/storage/azblob/zc_containerRequestOptions.go
  sdk/storage/azblob/zc_leaseClient.go
  sdk/storage/azblob/zc_leaseRequestOptions.go
  sdk/storage/azblob/zc_list_blobs_wrapper.go
  sdk/storage/azblob/zc_list_containers_wrapper.go
  sdk/storage/azblob/zc_serviceClient.go
  sdk/storage/azblob/zc_serviceRequestOptions.go
  sdk/storage/azblob/zc_storage_error.go
  sdk/storage/azblob/zt_blob_client_test.go
  sdk/storage/azblob/zt_blob_versioning_test.go
  sdk/storage/azblob/zt_client_provided_key_test.go
  sdk/storage/azblob/zt_container_client_test.go
  sdk/storage/azblob/zt_examples_test.go
  sdk/storage/azblob/zt_lease_client_test.go
  sdk/storage/azblob/zt_page_blob_client_test.go
  sdk/storage/azblob/zt_test.go
  sdk/storage/azblob/zt_user_delegation_sas_test.go
Labels: Storage

#14566 Revert "[Go][Track2] Added Blob/Container Lease Client"
  sdk/storage/azblob/zc_blobClient.go
  sdk/storage/azblob/zc_blobRequestOptions.go
  sdk/storage/azblob/zc_client_options.go
  sdk/storage/azblob/zc_containerClient.go
  sdk/storage/azblob/zc_containerRequestOptions.go
  sdk/storage/azblob/zc_leaseClient.go
  sdk/storage/azblob/zc_leaseRequestOptions.go
  sdk/storage/azblob/zc_list_blobs_wrapper.go
  sdk/storage/azblob/zc_list_containers_wrapper.go
  sdk/storage/azblob/zc_serviceClient.go
  sdk/storage/azblob/zc_serviceRequestOptions.go
  sdk/storage/azblob/zc_storage_error.go
  sdk/storage/azblob/zt_blob_client_test.go
  sdk/storage/azblob/zt_blob_versioning_test.go
  sdk/storage/azblob/zt_client_provided_key_test.go
  sdk/storage/azblob/zt_container_client_test.go
  sdk/storage/azblob/zt_examples_test.go
  sdk/storage/azblob/zt_lease_client_test.go
  sdk/storage/azblob/zt_page_blob_client_test.go
  sdk/storage/azblob/zt_test.go
  sdk/storage/azblob/zt_user_delegation_sas_test.go
Labels: Storage

#14564 Adreed/presentation
  sdk/storage/azblob/.gitignore
  sdk/storage/azblob/go.mod
  sdk/storage/azblob/go.sum
  sdk/storage/azblob/highlevel.go
  sdk/storage/azblob/shared_policy_shared_key_credential.go
  sdk/storage/azblob/shared_storage_account_credential.go
  sdk/storage/azblob/shared_user_delegation_credential.go
  sdk/storage/azblob/zc_appendBlobClient.go
  sdk/storage/azblob/zc_appendBlobRequestOptions.go
  sdk/storage/azblob/zc_blobClient.go
  sdk/storage/azblob/zc_blobRequestOptions.go
  sdk/storage/azblob/zc_blockBlobClient.go
  sdk/storage/azblob/zc_blockBlobRequestOptions.go
  sdk/storage/azblob/zc_client_options.go
  sdk/storage/azblob/zc_containerClient.go
  sdk/storage/azblob/zc_containerRequestOptions.go
  sdk/storage/azblob/zc_credential_anonymous.go
  sdk/storage/azblob/zc_leaseClient.go
  sdk/storage/azblob/zc_leaseRequestOptions.go
  sdk/storage/azblob/zc_list_blobs_wrapper.go
  sdk/storage/azblob/zc_list_containers_wrapper.go
  sdk/storage/azblob/zc_pageBlobClient.go
  sdk/storage/azblob/zc_pageBlobRequestOptions.go
  sdk/storage/azblob/zc_response_helpers.go
  sdk/storage/azblob/zc_sas_service.go
  sdk/storage/azblob/zc_serviceClient.go
  sdk/storage/azblob/zc_serviceRequestOptions.go
  sdk/storage/azblob/zc_storage_error.go
  sdk/storage/azblob/zc_validators.go
  sdk/storage/azblob/zt_append_blob_client_test.go
  sdk/storage/azblob/zt_blob_client_test.go
  sdk/storage/azblob/zt_blob_tags_test.go
  sdk/storage/azblob/zt_blob_versioning_test.go
  sdk/storage/azblob/zt_block_blob_client_test.go
  sdk/storage/azblob/zt_client_provided_key_test.go
  sdk/storage/azblob/zt_container_client_test.go
  sdk/storage/azblob/zt_examples_test.go
  sdk/storage/azblob/zt_lease_client_test.go
  sdk/storage/azblob/zt_page_blob_client_test.go
  sdk/storage/azblob/zt_sas_blob_snapshot_test.go
  sdk/storage/azblob/zt_service_client_test.go
  sdk/storage/azblob/zt_test.go
  sdk/storage/azblob/zt_user_delegation_sas_test.go
  sdk/storage/azblob/zz_generated_appendblob_client.go
  sdk/storage/azblob/zz_generated_blob_client.go
  sdk/storage/azblob/zz_generated_blockblob_client.go
  sdk/storage/azblob/zz_generated_connection.go
  sdk/storage/azblob/zz_generated_constants.go
  sdk/storage/azblob/zz_generated_container_client.go
  sdk/storage/azblob/zz_generated_directory_client.go
  sdk/storage/azblob/zz_generated_enums.go
  sdk/storage/azblob/zz_generated_models.go
  sdk/storage/azblob/zz_generated_pageblob_client.go
  sdk/storage/azblob/zz_generated_pagers.go
  sdk/storage/azblob/zz_generated_service_client.go
  sdk/storage/azblob/zz_generated_time_rfc1123.go
  sdk/storage/azblob/zz_generated_time_rfc3339.go
  sdk/storage/azblob/zz_generated_xml_helper.go
Labels: Storage

#14491 Introduce internal/testFramework and test aztables with it
  sdk/internal/go.mod
  sdk/internal/go.sum
  sdk/internal/testframework/recording.go
  sdk/internal/testframework/recording_sanitizer.go
  sdk/internal/testframework/recording_sanitizer_test.go
  sdk/internal/testframework/recording_test.go
  sdk/internal/testframework/request_matcher.go
  sdk/internal/testframework/request_matcher_test.go
  sdk/internal/testframework/testcontext.go
  sdk/internal/uuid/uuid.go
  sdk/tables/aztables/tableClient.go
  sdk/tables/aztables/tableClient_test.go
  sdk/tables/aztables/zc_client_options.go
  sdk/tables/aztables/zz_generated_connection.go
Labels: Azure.Core, Tables

#14570 ArchBoard Review - 2
  sdk/storage/azblob/zc_blobClient.go
  sdk/storage/azblob/zc_containerClient.go
  sdk/storage/azblob/zc_leaseClient.go
  sdk/storage/azblob/zc_leaseRequestOptions.go
  sdk/storage/azblob/zc_serviceClient.go
  sdk/storage/azblob/zt_examples_test.go
  sdk/storage/azblob/zt_lease_client_test.go
Labels: Storage

#14581 Sync eng/common directory with azure-sdk-tools for PR 1562
  eng/common/pipelines/templates/steps/verify-links.yml
  eng/common/scripts/Verify-Links.ps1
Labels: Central-EngSys, EngSys

#14606 Sync eng/common directory with azure-sdk-tools for PR 1580
  eng/common/scripts/Verify-Links.ps1
Labels: Central-EngSys, EngSys

#14615 Sync eng/common directory with azure-sdk-tools for PR 1572
  eng/common/pipelines/templates/steps/prepare-pipelines.yml
Labels: Central-EngSys, EngSys

#14607 Sync eng/common directory with azure-sdk-tools for PR 1577
  eng/common/pipelines/templates/steps/sparse-checkout.yml
Labels: Central-EngSys, EngSys

#14619 Sync eng/common directory with azure-sdk-tools for PR 1584
  eng/common/scripts/Helpers/DevOps-WorkItem-Helpers.ps1
  eng/common/scripts/Update-DevOps-Release-WorkItem.ps1
Labels: Central-EngSys, EngSys

#14587 azidentity: simplify auth_code flow cb code
  sdk/azidentity/interactive_browser_server.go
Labels: Authentication, Track2
