Repository Azure/azure-sdk-for-go, pull requests merged in 2021-05, with the labels that each got.

#14614 Sync eng/common directory with azure-sdk-tools for PR 1579
  eng/common/pipelines/templates/steps/daily-dev-build-variable.yml
Labels: Central-EngSys, EngSys

#14620 Sync eng/common directory with azure-sdk-tools for PR 1524
  eng/common/scripts/ChangeLog-Operations.ps1
Labels: Central-EngSys, EngSys

#14635 Sync eng/common directory with azure-sdk-tools for PR 1596
  eng/common/pipelines/templates/steps/daily-dev-build-variable.yml
Labels: Central-EngSys, EngSys

#14643 Sync eng/common directory with azure-sdk-tools for PR 1597
  eng/common/scripts/Prepare-Release.ps1
  eng/common/scripts/Update-DevOps-Release-WorkItem.ps1
Labels: Central-EngSys, EngSys

#14647 Sync eng/common directory with azure-sdk-tools for PR 1594
  eng/common/pipelines/templates/steps/create-pull-request.yml
  eng/common/pipelines/templates/steps/sparse-checkout.yml
Labels: Central-EngSys, EngSys

#14671 Sync eng/common directory with azure-sdk-tools for PR 1598
  eng/common/pipelines/templates/jobs/archetype-sdk-tests-generate.yml
Labels: Central-EngSys, EngSys

#14675 Sync eng/common directory with azure-sdk-tools for PR 1585
  eng/common/pipelines/templates/steps/docs-metadata-release.yml
  eng/common/pipelines/templates/steps/sparse-checkout.yml
Labels: Central-EngSys, EngSys

#14677 azartifacts preview v0.1.0
  sdk/synapse/azartifacts/CHANGELOG.md
  sdk/synapse/azartifacts/LICENSE.txt
  sdk/synapse/azartifacts/README.md
  sdk/synapse/azartifacts/ci.yml
  sdk/synapse/azartifacts/go.mod
  sdk/synapse/azartifacts/go.sum
  sdk/synapse/azartifacts/zz_generated_bigdatapools_client.go
  sdk/synapse/azartifacts/zz_generated_connection.go
  sdk/synapse/azartifacts/zz_generated_constants.go
  sdk/synapse/azartifacts/zz_generated_dataflow_client.go
  sdk/synapse/azartifacts/zz_generated_dataflowdebugsession_client.go
  sdk/synapse/azartifacts/zz_generated_dataset_client.go
  sdk/synapse/azartifacts/zz_generated_integrationruntimes_client.go
  sdk/synapse/azartifacts/zz_generated_library_client.go
  sdk/synapse/azartifacts/zz_generated_linkedservice_client.go
  sdk/synapse/azartifacts/zz_generated_models.go
  sdk/synapse/azartifacts/zz_generated_notebook_client.go
  sdk/synapse/azartifacts/zz_generated_pagers.go
  sdk/synapse/azartifacts/zz_generated_pipeline_client.go
  sdk/synapse/azartifacts/zz_generated_pipelinerun_client.go
  sdk/synapse/azartifacts/zz_generated_pollers.go
  sdk/synapse/azartifacts/zz_generated_polymorphic_helpers.go
  sdk/synapse/azartifacts/zz_generated_response_types.go
  sdk/synapse/azartifacts/zz_generated_sparkjobdefinition_client.go
  sdk/synapse/azartifacts/zz_generated_sqlpools_client.go
  sdk/synapse/azartifacts/zz_generated_sqlscript_client.go
  sdk/synapse/azartifacts/zz_generated_time_rfc3339.go
  sdk/synapse/azartifacts/zz_generated_trigger_client.go
  sdk/synapse/azartifacts/zz_generated_triggerrun_client.go
  sdk/synapse/azartifacts/zz_generated_workspace_client.go
  sdk/synapse/azartifacts/zz_generated_workspacegitrepomanagement_client.go
Labels: Synapse

#14691 Sync eng/common directory with azure-sdk-tools for PR 1615
  eng/common/pipelines/templates/jobs/docindex.yml
Labels: Central-EngSys, EngSys

#14699 Carve out azartifacts module
  sdk/synapse/azartifacts/go_mod_tidy_hack.go
Labels: Synapse

#14705 Sync eng/common directory with azure-sdk-tools for PR 1627
  eng/common/pipelines/templates/steps/sparse-checkout.yml
Labels: Central-EngSys, EngSys

#14706 Sync eng/common directory with azure-sdk-tools for PR 1629
  eng/common/scripts/ChangeLog-Operations.ps1
Labels: Central-EngSys, EngSys

#14707 introduce license for keyvault track 2 module
  sdk/keyvault/armkeyvault/LICENSE.txt
  sdk/keyvault/armkeyvault/README.md
  sdk/keyvault/armkeyvault/example_secrets_test.go
  sdk/keyvault/armkeyvault/go.mod
  sdk/keyvault/armkeyvault/go.sum
  sdk/keyvault/armkeyvault/zz_generated_constants.go
  sdk/keyvault/armkeyvault/zz_generated_keys_client.go
  sdk/keyvault/armkeyvault/zz_generated_managedhsms_client.go
  sdk/keyvault/armkeyvault/zz_generated_mhsmprivateendpointconnections_client.go
  sdk/keyvault/armkeyvault/zz_generated_mhsmprivatelinkresources_client.go
  sdk/keyvault/armkeyvault/zz_generated_models.go
  sdk/keyvault/armkeyvault/zz_generated_operations_client.go
  sdk/keyvault/armkeyvault/zz_generated_pagers.go
  sdk/keyvault/armkeyvault/zz_generated_pollers.go
  sdk/keyvault/armkeyvault/zz_generated_privateendpointconnections_client.go
  sdk/keyvault/armkeyvault/zz_generated_privatelinkresources_client.go
  sdk/keyvault/armkeyvault/zz_generated_response_types.go
  sdk/keyvault/armkeyvault/zz_generated_secrets_client.go
  sdk/keyvault/armkeyvault/zz_generated_time_rfc3339.go
  sdk/keyvault/armkeyvault/zz_generated_vaults_client.go
Labels: KeyVault

#14711 add license for storage track 2 module
  sdk/storage/armstorage/LICENSE.txt
  sdk/storage/armstorage/README.md
Labels: Storage

#14712 go mod tidy for storage track 2 module
  sdk/storage/armstorage/go.mod
  sdk/storage/armstorage/go.sum
Labels: Storage

#14716 Sync eng/common directory with azure-sdk-tools for PR 1635
  eng/common/scripts/Update-DocsMsPackages.ps1
  eng/common/scripts/common.ps1
Labels: Central-EngSys, EngSys
