Repository Azure/azure-sdk-for-go, pull requests merged in 2021-08, with the labels that each got.

#15200 [engsys] remove race and covermode flags from test statement
  eng/pipelines/templates/steps/build-test.yml
Labels: EngSys, auto-merge

#15191 enhance build.ps1 script
  eng/scripts/build.ps1
Labels: EngSys

#15225 Cosmos DB: Adding CosmosContainer and CosmosDatabase
  sdk/cosmos/azcosmos/cosmos_client.go
  sdk/cosmos/azcosmos/cosmos_client_connection.go
  sdk/cosmos/azcosmos/cosmos_client_connection_test.go
  sdk/cosmos/azcosmos/cosmos_client_options_test.go
  sdk/cosmos/azcosmos/cosmos_container.go
  sdk/cosmos/azcosmos/cosmos_container_properties.go
  sdk/cosmos/azcosmos/cosmos_container_properties_test.go
  sdk/cosmos/azcosmos/cosmos_container_response.go
  sdk/cosmos/azcosmos/cosmos_container_response_test.go
  sdk/cosmos/azcosmos/cosmos_database.go
  sdk/cosmos/azcosmos/cosmos_database_properties.go
  sdk/cosmos/azcosmos/cosmos_database_properties_test.go
  sdk/cosmos/azcosmos/cosmos_database_response.go
  sdk/cosmos/azcosmos/cosmos_database_response_test.go
  sdk/cosmos/azcosmos/cosmos_headers.go
  sdk/cosmos/azcosmos/cosmos_paths.go
  sdk/cosmos/azcosmos/cosmos_response.go
  sdk/cosmos/azcosmos/go.mod
  sdk/cosmos/azcosmos/partition_key_definition.go
  sdk/cosmos/azcosmos/partition_key_definition_version.go
  sdk/cosmos/azcosmos/resource_throttle_retry_policy.go
  sdk/cosmos/azcosmos/resource_throttle_retry_policy_test.go
  sdk/cosmos/azcosmos/unixtime.go
Labels: Cosmos

#15207 [azcore] Add ETag type to Core
  sdk/azcore/etag.go
  sdk/azcore/etag_test.go
  sdk/azcore/go.mod
  sdk/azcore/go.sum
Labels: Azure.Core

#15240 [azidentity] adding a changelog to azidentity
  sdk/azidentity/CHANGELOG.md
Labels: Azure.Identity, auto-merge

#15239 [azcore] adding changelog
  sdk/azcore/CHANGELOG.md
Labels: Azure.Core, auto-merge

#14792 Release the track 2 `containerservice` module
  sdk/containerservice/armcontainerservice/CHANGELOG.md
  sdk/containerservice/armcontainerservice/README.md
  sdk/containerservice/armcontainerservice/autorest.md
  sdk/containerservice/armcontainerservice/build.go
  sdk/containerservice/armcontainerservice/ci.yml
  sdk/containerservice/armcontainerservice/go.mod
  sdk/containerservice/armcontainerservice/go.sum
  sdk/containerservice/armcontainerservice/go_mod_tidy_hack.go
  sdk/containerservice/armcontainerservice/zz_generated_agentpools_client.go
  sdk/containerservice/armcontainerservice/zz_generated_constants.go
  sdk/containerservice/armcontainerservice/zz_generated_maintenanceconfigurations_client.go
  sdk/containerservice/armcontainerservice/zz_generated_managedclusters_client.go
  sdk/containerservice/armcontainerservice/zz_generated_models.go
  sdk/containerservice/armcontainerservice/zz_generated_operations_client.go
  sdk/containerservice/armcontainerservice/zz_generated_pagers.go
  sdk/containerservice/armcontainerservice/zz_generated_pollers.go
  sdk/containerservice/armcontainerservice/zz_generated_privateendpointconnections_client.go
  sdk/containerservice/armcontainerservice/zz_generated_privatelinkresources_client.go
  sdk/containerservice/armcontainerservice/zz_generated_resolveprivatelinkserviceid_client.go
  sdk/containerservice/armcontainerservice/zz_generated_response_types.go
  sdk/containerservice/armcontainerservice/zz_generated_time_rfc3339.go
Labels: Container Service

#15214 track2 generator servicebus
  sdk/servicebus/armservicebus/CHANGELOG.md
  sdk/servicebus/armservicebus/README.md
  sdk/servicebus/armservicebus/autorest.md
  sdk/servicebus/armservicebus/build.go
  sdk/servicebus/armservicebus/go.mod
  sdk/servicebus/armservicebus/go.sum
  sdk/servicebus/armservicebus/go_mod_tidy_hack.go
  sdk/servicebus/armservicebus/zz_generated_constants.go
  sdk/servicebus/armservicebus/zz_generated_disasterrecoveryconfigs_client.go
  sdk/servicebus/armservicebus/zz_generated_eventhubs_client.go
  sdk/servicebus/armservicebus/zz_generated_migrationconfigs_client.go
  sdk/servicebus/armservicebus/zz_generated_models.go
  sdk/servicebus/armservicebus/zz_generated_namespaces_client.go
  sdk/servicebus/armservicebus/zz_generated_operations_client.go
  sdk/servicebus/armservicebus/zz_generated_pagers.go
  sdk/servicebus/armservicebus/zz_generated_pollers.go
  sdk/servicebus/armservicebus/zz_generated_premiummessagingregions_client.go
  sdk/servicebus/armservicebus/zz_generated_privateendpointconnections_client.go
  sdk/servicebus/armservicebus/zz_generated_privatelinkresources_client.go
  sdk/servicebus/armservicebus/zz_generated_queues_client.go
  sdk/servicebus/armservicebus/zz_generated_regions_client.go
  sdk/servicebus/armservicebus/zz_generated_response_types.go
  sdk/servicebus/armservicebus/zz_generated_rules_client.go
  sdk/servicebus/armservicebus/zz_generated_subscriptions_client.go
  sdk/servicebus/armservicebus/zz_generated_time_rfc3339.go
  sdk/servicebus/armservicebus/zz_generated_topics_client.go
Labels: Service Bus

#15218 Track2 generator cosmos db
  sdk/cosmos/armcosmos/CHANGELOG.md
  sdk/cosmos/armcosmos/LICENSE.txt
  sdk/cosmos/armcosmos/README.md
  sdk/cosmos/armcosmos/autorest.md
  sdk/cosmos/armcosmos/build.go
  sdk/cosmos/armcosmos/ci.yml
  sdk/cosmos/armcosmos/go.mod
  sdk/cosmos/armcosmos/go.sum
  sdk/cosmos/armcosmos/go_mod_tidy_hack.go
  sdk/cosmos/armcosmos/zz_generated_cassandraresources_client.go
  sdk/cosmos/armcosmos/zz_generated_collection_client.go
  sdk/cosmos/armcosmos/zz_generated_collectionpartition_client.go
  sdk/cosmos/armcosmos/zz_generated_collectionpartitionregion_client.go
  sdk/cosmos/armcosmos/zz_generated_collectionregion_client.go
  sdk/cosmos/armcosmos/zz_generated_constants.go
  sdk/cosmos/armcosmos/zz_generated_database_client.go
  sdk/cosmos/armcosmos/zz_generated_databaseaccountregion_client.go
  sdk/cosmos/armcosmos/zz_generated_databaseaccounts_client.go
  sdk/cosmos/armcosmos/zz_generated_gremlinresources_client.go
  sdk/cosmos/armcosmos/zz_generated_models.go
  sdk/cosmos/armcosmos/zz_generated_mongodbresources_client.go
  sdk/cosmos/armcosmos/zz_generated_notebookworkspaces_client.go
  sdk/cosmos/armcosmos/zz_generated_operations_client.go
  sdk/cosmos/armcosmos/zz_generated_pagers.go
  sdk/cosmos/armcosmos/zz_generated_partitionkeyrangeid_client.go
  sdk/cosmos/armcosmos/zz_generated_partitionkeyrangeidregion_client.go
  sdk/cosmos/armcosmos/zz_generated_percentile_client.go
  sdk/cosmos/armcosmos/zz_generated_percentilesourcetarget_client.go
  sdk/cosmos/armcosmos/zz_generated_percentiletarget_client.go
  sdk/cosmos/armcosmos/zz_generated_pollers.go
  sdk/cosmos/armcosmos/zz_generated_polymorphic_helpers.go
  sdk/cosmos/armcosmos/zz_generated_privateendpointconnections_client.go
  sdk/cosmos/armcosmos/zz_generated_privatelinkresources_client.go
  sdk/cosmos/armcosmos/zz_generated_response_types.go
  sdk/cosmos/armcosmos/zz_generated_restorabledatabaseaccounts_client.go
  sdk/cosmos/armcosmos/zz_generated_restorablemongodbcollections_client.go
  sdk/cosmos/armcosmos/zz_generated_restorablemongodbdatabases_client.go
  sdk/cosmos/armcosmos/zz_generated_restorablemongodbresources_client.go
  sdk/cosmos/armcosmos/zz_generated_restorablesqlcontainers_client.go
  sdk/cosmos/armcosmos/zz_generated_restorablesqldatabases_client.go
  sdk/cosmos/armcosmos/zz_generated_restorablesqlresources_client.go
  sdk/cosmos/armcosmos/zz_generated_sqlresources_client.go
  sdk/cosmos/armcosmos/zz_generated_tableresources_client.go
  sdk/cosmos/armcosmos/zz_generated_time_rfc3339.go
Labels: Cosmos, Mgmt

#15219 track2 generator postgresql
  sdk/postgresql/armpostgresql/CHANGELOG.md
  sdk/postgresql/armpostgresql/LICENSE.txt
  sdk/postgresql/armpostgresql/README.md
  sdk/postgresql/armpostgresql/autorest.md
  sdk/postgresql/armpostgresql/build.go
  sdk/postgresql/armpostgresql/ci.yml
  sdk/postgresql/armpostgresql/go.mod
  sdk/postgresql/armpostgresql/go.sum
  sdk/postgresql/armpostgresql/go_mod_tidy_hack.go
  sdk/postgresql/armpostgresql/zz_generated_checknameavailability_client.go
  sdk/postgresql/armpostgresql/zz_generated_configurations_client.go
  sdk/postgresql/armpostgresql/zz_generated_constants.go
  sdk/postgresql/armpostgresql/zz_generated_databases_client.go
  sdk/postgresql/armpostgresql/zz_generated_firewallrules_client.go
  sdk/postgresql/armpostgresql/zz_generated_locationbasedperformancetier_client.go
  sdk/postgresql/armpostgresql/zz_generated_logfiles_client.go
  sdk/postgresql/armpostgresql/zz_generated_models.go
  sdk/postgresql/armpostgresql/zz_generated_operations_client.go
  sdk/postgresql/armpostgresql/zz_generated_pagers.go
  sdk/postgresql/armpostgresql/zz_generated_pollers.go
  sdk/postgresql/armpostgresql/zz_generated_polymorphic_helpers.go
  sdk/postgresql/armpostgresql/zz_generated_privateendpointconnections_client.go
  sdk/postgresql/armpostgresql/zz_generated_privatelinkresources_client.go
  sdk/postgresql/armpostgresql/zz_generated_recoverableservers_client.go
  sdk/postgresql/armpostgresql/zz_generated_replicas_client.go
  sdk/postgresql/armpostgresql/zz_generated_response_types.go
  sdk/postgresql/armpostgresql/zz_generated_serveradministrators_client.go
  sdk/postgresql/armpostgresql/zz_generated_serverbasedperformancetier_client.go
  sdk/postgresql/armpostgresql/zz_generated_serverkeys_client.go
  sdk/postgresql/armpostgresql/zz_generated_serverparameters_client.go
  sdk/postgresql/armpostgresql/zz_generated_servers_client.go
  sdk/postgresql/armpostgresql/zz_generated_serversecurityalertpolicies_client.go
  sdk/postgresql/armpostgresql/zz_generated_time_rfc3339.go
  sdk/postgresql/armpostgresql/zz_generated_virtualnetworkrules_client.go
Labels: PostgreSQL, Mgmt

#15221 track2 generator postgresql flexible servers
  sdk/postgresql/armpostgresqlflexibleservers/CHANGELOG.md
  sdk/postgresql/armpostgresqlflexibleservers/LICENSE.txt
  sdk/postgresql/armpostgresqlflexibleservers/README.md
  sdk/postgresql/armpostgresqlflexibleservers/autorest.md
  sdk/postgresql/armpostgresqlflexibleservers/build.go
  sdk/postgresql/armpostgresqlflexibleservers/ci.yml
  sdk/postgresql/armpostgresqlflexibleservers/go.mod
  sdk/postgresql/armpostgresqlflexibleservers/go.sum
  sdk/postgresql/armpostgresqlflexibleservers/go_mod_tidy_hack.go
  sdk/postgresql/armpostgresqlflexibleservers/zz_generated_checknameavailability_client.go
  sdk/postgresql/armpostgresqlflexibleservers/zz_generated_configurations_client.go
  sdk/postgresql/armpostgresqlflexibleservers/zz_generated_constants.go
  sdk/postgresql/armpostgresqlflexibleservers/zz_generated_databases_client.go
  sdk/postgresql/armpostgresqlflexibleservers/zz_generated_firewallrules_client.go
  sdk/postgresql/armpostgresqlflexibleservers/zz_generated_getprivatednszonesuffix_client.go
  sdk/postgresql/armpostgresqlflexibleservers/zz_generated_locationbasedcapabilities_client.go
  sdk/postgresql/armpostgresqlflexibleservers/zz_generated_models.go
  sdk/postgresql/armpostgresqlflexibleservers/zz_generated_operations_client.go
  sdk/postgresql/armpostgresqlflexibleservers/zz_generated_pagers.go
  sdk/postgresql/armpostgresqlflexibleservers/zz_generated_pollers.go
  sdk/postgresql/armpostgresqlflexibleservers/zz_generated_response_types.go
  sdk/postgresql/armpostgresqlflexibleservers/zz_generated_servers_client.go
  sdk/postgresql/armpostgresqlflexibleservers/zz_generated_time_rfc3339.go
  sdk/postgresql/armpostgresqlflexibleservers/zz_generated_virtualnetworksubnetusage_client.go
Labels: PostgreSQL, Mgmt

#15246 [Cosmos DB] Adding Indexing Policy, Unique Key Policy, and Conflict Resolution Policy
  sdk/cosmos/azcosmos/composite_index_order.go
  sdk/cosmos/azcosmos/conflict_resolution_mode.go
  sdk/cosmos/azcosmos/conflict_resolution_policy.go
  sdk/cosmos/azcosmos/cosmos_container_properties.go
  sdk/cosmos/azcosmos/cosmos_container_properties_test.go
  sdk/cosmos/azcosmos/data_type.go
  sdk/cosmos/azcosmos/indexing_mode.go
  sdk/cosmos/azcosmos/indexing_policy.go
  sdk/cosmos/azcosmos/spatial_type.go
  sdk/cosmos/azcosmos/unique_key_policy.go
Labels: Cosmos

#15257 [EngSys] display output of go test
  eng/pipelines/templates/steps/build-test.yml
  sdk/postgresql/armpostgresql/go_mod_tidy_hack.go
Labels: EngSys, auto-merge

#15249 track2 generator event grid
  sdk/eventgrid/armeventgrid/CHANGELOG.md
  sdk/eventgrid/armeventgrid/LICENSE.txt
  sdk/eventgrid/armeventgrid/README.md
  sdk/eventgrid/armeventgrid/autorest.md
  sdk/eventgrid/armeventgrid/build.go
  sdk/eventgrid/armeventgrid/ci.yml
  sdk/eventgrid/armeventgrid/go.mod
  sdk/eventgrid/armeventgrid/go.sum
  sdk/eventgrid/armeventgrid/go_mod_tidy_hack.go
  sdk/eventgrid/armeventgrid/zz_generated_constants.go
  sdk/eventgrid/armeventgrid/zz_generated_domains_client.go
  sdk/eventgrid/armeventgrid/zz_generated_domaintopics_client.go
  sdk/eventgrid/armeventgrid/zz_generated_eventchannels_client.go
  sdk/eventgrid/armeventgrid/zz_generated_eventsubscriptions_client.go
  sdk/eventgrid/armeventgrid/zz_generated_extensiontopics_client.go
  sdk/eventgrid/armeventgrid/zz_generated_models.go
  sdk/eventgrid/armeventgrid/zz_generated_operations_client.go
  sdk/eventgrid/armeventgrid/zz_generated_pagers.go
  sdk/eventgrid/armeventgrid/zz_generated_partnernamespaces_client.go
  sdk/eventgrid/armeventgrid/zz_generated_partnerregistrations_client.go
  sdk/eventgrid/armeventgrid/zz_generated_partnertopiceventsubscriptions_client.go
  sdk/eventgrid/armeventgrid/zz_generated_partnertopics_client.go
  sdk/eventgrid/armeventgrid/zz_generated_pollers.go
  sdk/eventgrid/armeventgrid/zz_generated_polymorphic_helpers.go
  sdk/eventgrid/armeventgrid/zz_generated_privateendpointconnections_client.go
  sdk/eventgrid/armeventgrid/zz_generated_privatelinkresources_client.go
  sdk/eventgrid/armeventgrid/zz_generated_response_types.go
  sdk/eventgrid/armeventgrid/zz_generated_systemtopiceventsubscriptions_client.go
  sdk/eventgrid/armeventgrid/zz_generated_systemtopics_client.go
  sdk/eventgrid/armeventgrid/zz_generated_time_rfc3339.go
  sdk/eventgrid/armeventgrid/zz_generated_topics_client.go
  sdk/eventgrid/armeventgrid/zz_generated_topictypes_client.go
Labels: Event Grid

#15266 Fixed small bugs
  documentation/new-version-quickstart.md
Labels: auto-merge

#15261 Sync eng/common directory with azure-sdk-tools for PR 1866
  eng/common/scripts/stress-testing/deploy-stress-tests.ps1
Labels: EngSys, Central-EngSys

#15252 track2 release `armeventhub`
  sdk/eventhub/armeventhub/CHANGELOG.md
  sdk/eventhub/armeventhub/LICENSE.txt
  sdk/eventhub/armeventhub/README.md
  sdk/eventhub/armeventhub/autorest.md
  sdk/eventhub/armeventhub/build.go
  sdk/eventhub/armeventhub/ci.yml
  sdk/eventhub/armeventhub/go.mod
  sdk/eventhub/armeventhub/go.sum
  sdk/eventhub/armeventhub/go_mod_tidy_hack.go
  sdk/eventhub/armeventhub/zz_generated_clusters_client.go
  sdk/eventhub/armeventhub/zz_generated_configuration_client.go
  sdk/eventhub/armeventhub/zz_generated_constants.go
  sdk/eventhub/armeventhub/zz_generated_consumergroups_client.go
  sdk/eventhub/armeventhub/zz_generated_disasterrecoveryconfigs_client.go
  sdk/eventhub/armeventhub/zz_generated_eventhubs_client.go
  sdk/eventhub/armeventhub/zz_generated_models.go
  sdk/eventhub/armeventhub/zz_generated_namespaces_client.go
  sdk/eventhub/armeventhub/zz_generated_operations_client.go
  sdk/eventhub/armeventhub/zz_generated_pagers.go
  sdk/eventhub/armeventhub/zz_generated_pollers.go
  sdk/eventhub/armeventhub/zz_generated_privateendpointconnections_client.go
  sdk/eventhub/armeventhub/zz_generated_privatelinkresources_client.go
  sdk/eventhub/armeventhub/zz_generated_regions_client.go
  sdk/eventhub/armeventhub/zz_generated_response_types.go
  sdk/eventhub/armeventhub/zz_generated_time_rfc3339.go
Labels: Event Hubs

#15281 Sync eng/common directory with azure-sdk-tools for PR 1894
  eng/common/TestResources/Remove-TestResources.ps1
  eng/common/scripts/Helpers/Resource-Helpers.ps1
Labels: EngSys, Central-EngSys

#15258 [azcore] JoinPaths will preserve query parameters
  sdk/azcore/CHANGELOG.md
  sdk/azcore/request.go
  sdk/azcore/request_test.go
Labels: Azure.Core

#15279 Sync eng/common directory with azure-sdk-tools for PR 1876
  eng/common/TestResources/New-TestResources.ps1
Labels: EngSys, Central-EngSys

#15292 [Cosmos DB] add master key authentication
  eng/pipelines/templates/jobs/archetype-sdk-client.yml
  eng/pipelines/templates/steps/build-test.yml
  sdk/cosmos/azcosmos/cosmos_client.go
  sdk/cosmos/azcosmos/cosmos_client_connection.go
  sdk/cosmos/azcosmos/cosmos_client_connection_test.go
  sdk/cosmos/azcosmos/cosmos_client_options.go
  sdk/cosmos/azcosmos/cosmos_client_options_test.go
  sdk/cosmos/azcosmos/cosmos_container_properties_test.go
  sdk/cosmos/azcosmos/cosmos_container_response_test.go
  sdk/cosmos/azcosmos/cosmos_database_properties_test.go
  sdk/cosmos/azcosmos/cosmos_database_response_test.go
  sdk/cosmos/azcosmos/cosmos_operation_context.go
  sdk/cosmos/azcosmos/go.mod
  sdk/cosmos/azcosmos/go.sum
  sdk/cosmos/azcosmos/resource_throttle_retry_policy_test.go
  sdk/cosmos/azcosmos/shared_key_credential.go
  sdk/cosmos/azcosmos/shared_key_credential_test.go
  sdk/cosmos/ci.yml
Labels: Cosmos

#15290 Sync eng/common directory with azure-sdk-tools for PR 1884
  eng/common/scripts/Helpers/DevOps-WorkItem-Helpers.ps1
  eng/common/scripts/Update-DevOps-Release-WorkItem.ps1
Labels: EngSys, Central-EngSys

#15289 Sync eng/common directory with azure-sdk-tools for PR 1902
  eng/common/TestResources/Remove-TestResources.ps1
  eng/common/scripts/Helpers/Resource-Helpers.ps1
Labels: EngSys, Central-EngSys

#15293 [Cosmos DB] Yaml branch filtering
  eng/pipelines/templates/jobs/archetype-sdk-client.yml
  sdk/cosmos/ci.yml
Labels: Cosmos

#15256 [Tables] Add authentication via SAS credential
  eng/pipelines/templates/steps/build-test.yml
  eng/scripts/proxy-server.ps1
  sdk/azcore/request.go
  sdk/azcore/request_test.go
  sdk/tables/autorest.md
  sdk/tables/aztable/byte_array_response.go
  sdk/tables/aztable/cosmos_patch_transform_policy.go
  sdk/tables/aztable/entity.go
  sdk/tables/aztable/errors.go
  sdk/tables/aztable/go.mod
  sdk/tables/aztable/models.go
  sdk/tables/aztable/proxy_test.go
  sdk/tables/aztable/recordings/TestInsertEntity/TestInsertEntity_cosmos.json
  sdk/tables/aztable/recordings/TestInsertEntity/TestInsertEntity_storage.json
  sdk/tables/aztable/sas_account.go
  sdk/tables/aztable/sas_query_params.go
  sdk/tables/aztable/sas_service.go
  sdk/tables/aztable/shared_access_signature_test.go
  sdk/tables/aztable/table_batch_test.go
  sdk/tables/aztable/table_client.go
  sdk/tables/aztable/table_client_test.go
  sdk/tables/aztable/table_pagers.go
  sdk/tables/aztable/table_service_client.go
  sdk/tables/aztable/table_service_client_test.go
  sdk/tables/aztable/table_transactional_batch.go
  sdk/tables/aztable/zc_table_constants.go
  sdk/tables/aztable/zt_table_recorded_tests.go
Labels: Tables

#15286 Sync eng/common directory with azure-sdk-tools for PR 1901
  eng/common/pipelines/templates/steps/sparse-checkout.yml
Labels: EngSys, Central-EngSys

#15302 Sync eng/common directory with azure-sdk-tools for PR 1909
  eng/common/scripts/common.ps1
  eng/common/scripts/trust-proxy-certificate.ps1
  eng/common/testproxy/apply-dev-cert.sh
  eng/common/testproxy/docker-start-proxy.ps1
  eng/common/testproxy/dotnet-devcert.crt
  eng/common/testproxy/dotnet-devcert.pfx
  eng/common/testproxy/localhost.conf
  eng/common/testproxy/test-proxy-docker.yml
  eng/common/testproxy/test-proxy-tool.yml
Labels: EngSys, Central-EngSys

#15305 Sync eng/common directory with azure-sdk-tools for PR 1913
  eng/common/scripts/Create-APIReview.ps1
Labels: EngSys, Central-EngSys

#15296 Append Seal
  sdk/storage/azblob/recordings/Test/TestCopySealedBlob-variables.yaml
  sdk/storage/azblob/recordings/Test/TestCopySealedBlob.yaml
  sdk/storage/azblob/recordings/Test/TestCopyUnsealedBlob-variables.yaml
  sdk/storage/azblob/recordings/Test/TestCopyUnsealedBlob.yaml
  sdk/storage/azblob/recordings/Test/TestSealAppendBlob-variables.yaml
  sdk/storage/azblob/recordings/Test/TestSealAppendBlob.yaml
  sdk/storage/azblob/zc_append_blob_client.go
  sdk/storage/azblob/zc_storage_error.go
  sdk/storage/azblob/zm_append_blob_request_options.go
  sdk/storage/azblob/zt_append_blob_client_test.go
  sdk/storage/azblob/zt_test.go
  sdk/storage/azblob/zz_generated_constants.go
Labels: Storage

#14869 Added Container CreateIfNotExists/ DeleteIfExists APIs
  sdk/storage/azblob/recordings/Test/TestContainerCreateIfExists-variables.yaml
  sdk/storage/azblob/recordings/Test/TestContainerCreateIfExists.yaml
  sdk/storage/azblob/recordings/Test/TestContainerCreateIfNotExists-variables.yaml
  sdk/storage/azblob/recordings/Test/TestContainerCreateIfNotExists.yaml
  sdk/storage/azblob/recordings/Test/TestContainerDeleteIfExists-variables.yaml
  sdk/storage/azblob/recordings/Test/TestContainerDeleteIfExists.yaml
  sdk/storage/azblob/recordings/Test/TestContainerDeleteIfNotExists-variables.yaml
  sdk/storage/azblob/recordings/Test/TestContainerDeleteIfNotExists.yaml
  sdk/storage/azblob/zc_container_client.go
  sdk/storage/azblob/zt_blob_client_test.go
  sdk/storage/azblob/zt_container_client_test.go
Labels: Storage

#14877 Handling Anonymous Fields
  sdk/storage/azblob/highlevel.go
  sdk/storage/azblob/zc_access_conditions.go
  sdk/storage/azblob/zc_page_blob_request_options.go
  sdk/storage/azblob/zc_response_helpers.go
  sdk/storage/azblob/zm_append_blob_request_options.go
  sdk/storage/azblob/zm_blob_request_options.go
  sdk/storage/azblob/zm_block_blob_request_options.go
  sdk/storage/azblob/zt_append_blob_client_test.go
  sdk/storage/azblob/zt_blob_client_test.go
  sdk/storage/azblob/zt_blob_versioning_test.go
  sdk/storage/azblob/zt_block_blob_client_test.go
  sdk/storage/azblob/zt_examples_test.go
  sdk/storage/azblob/zt_page_blob_client_test.go
Labels: Storage

#15190 Update to crypto secure random number generation
  sdk/internal/recording/recording.go
  sdk/internal/recording/request_matcher_test.go
  sdk/internal/uuid/uuid.go
  sdk/internal/uuid/uuid_test.go
Labels: auto-merge

#15311 Sync eng/common directory with azure-sdk-tools for PR 1919
  eng/common/scripts/FilterPoliCheckResults.ps1
Labels: EngSys, Central-EngSys

#15301 Fixed bugs in Resource Group demo code
  documentation/new-version-quickstart.md
Labels: auto-merge

#15306 adding dates to existing changelogs
  sdk/azcore/CHANGELOG.md
  sdk/azidentity/CHANGELOG.md
  sdk/azidentity/doc.go
  sdk/azidentity/version.go
Labels: auto-merge

#15316 Fixes2
  sdk/azcore/request.go
Labels: auto-merge

#15314 Sync eng/common directory with azure-sdk-tools for PR 1912
  eng/common/TestResources/New-TestResources.ps1
  eng/common/TestResources/New-TestResources.ps1.md
  eng/common/scripts/Helpers/Resource-Helpers.ps1
Labels: EngSys, Central-EngSys

#15319 Sync eng/common directory with azure-sdk-tools for PR 1924
  eng/common/scripts/Helpers/DevOps-WorkItem-Helpers.ps1
Labels: EngSys, Central-EngSys

#15326 Sync eng/common directory with azure-sdk-tools for PR 1926
  eng/common/Update-Change-Log.ps1
Labels: EngSys, Central-EngSys

#15280 [service-bus] track 2 ServiceBusClient + ServiceBusProcessor
  sdk/servicebus/azservicebus/client.go
  sdk/servicebus/azservicebus/errors.go
  sdk/servicebus/azservicebus/go.mod
  sdk/servicebus/azservicebus/go.sum
  sdk/servicebus/azservicebus/internal/receiver.go
  sdk/servicebus/azservicebus/internal/utils/sync.go
  sdk/servicebus/azservicebus/message.go
  sdk/servicebus/azservicebus/processor.go
  sdk/servicebus/azservicebus/processor_test.go
  sdk/servicebus/azservicebus/receiver.go
  sdk/servicebus/azservicebus/retry.go
  sdk/servicebus/azservicebus/samples/processor/processor_sample.go
  sdk/servicebus/azservicebus/sender.go
  sdk/servicebus/azservicebus/stress/stress.go
Labels: Service Bus

#15333 [service-bus] Rename refactored ReceiveMode constants but didn't push the other files
  sdk/servicebus/azservicebus/processor.go
  sdk/servicebus/azservicebus/samples/processor/processor_sample.go
Labels: Service Bus, Client, auto-merge

#15331 Prevent ManagedIdentityCredential mutating GetToken arguments
  sdk/azidentity/CHANGELOG.md
  sdk/azidentity/managed_identity_credential.go
  sdk/azidentity/managed_identity_credential_test.go
Labels: Azure.Identity

#15348 [azidentity] bump azcore and internal dependencies
  sdk/azidentity/CHANGELOG.md
  sdk/azidentity/README.md
  sdk/azidentity/aad_identity_client.go
  sdk/azidentity/authorization_code_credential.go
  sdk/azidentity/azidentity.go
  sdk/azidentity/bearer_token_policy.go
  sdk/azidentity/bearer_token_policy_test.go
  sdk/azidentity/client_certificate_credential.go
  sdk/azidentity/client_secret_credential.go
  sdk/azidentity/default_azure_credential.go
  sdk/azidentity/device_code_credential.go
  sdk/azidentity/environment_credential.go
  sdk/azidentity/go.mod
  sdk/azidentity/go.sum
  sdk/azidentity/interactive_browser_credential.go
  sdk/azidentity/jwt.go
  sdk/azidentity/logging.go
  sdk/azidentity/managed_identity_client.go
  sdk/azidentity/managed_identity_credential.go
  sdk/azidentity/username_password_credential.go
Labels: auto-merge

#15357 Update CODEOWNERS
  .github/CODEOWNERS
Labels: auto-merge

#15187 [Tables] connection string parser
  eng/config.json
  eng/pipelines/templates/steps/build-test.yml
  eng/pipelines/templates/steps/configure-proxy.yml
  eng/scripts/proxy-server.ps1
  sdk/tables/aztable/byte_array_response.go
  sdk/tables/aztable/connection_string.go
  sdk/tables/aztable/connection_string_test.go
  sdk/tables/aztable/errors.go
  sdk/tables/aztable/table_client.go
  sdk/tables/aztable/table_pagers.go
  sdk/tables/ci.yml
Labels: Tables

#15317 Sync eng/common directory with azure-sdk-tools for PR 1918
  eng/common/scripts/stress-testing/deploy-stress-tests.ps1
Labels: EngSys, Central-EngSys

#15328 AsyncCache
  sdk/cosmos/azcosmos/async_cache.go
  sdk/cosmos/azcosmos/async_cache_test.go
  sdk/cosmos/azcosmos/go.mod
  sdk/cosmos/azcosmos/go.sum
Labels: Cosmos

#15406 Sync eng/common directory with azure-sdk-tools for PR 1943
  eng/common/TestResources/New-TestResources.ps1
Labels: EngSys, Central-EngSys

#15393 Update Contributing documentation
  CONTRIBUTING.md
Labels: auto-merge

#15391 Add CODE_OF_CONDUCT
  CODE_OF_CONDUCT.md
Labels: auto-merge

#15411 Sync eng/common directory with azure-sdk-tools for PR 1952
  eng/common/pipelines/templates/steps/eng-common-workflow-enforcer.yml
Labels: EngSys, Central-EngSys

#15413 Sync eng/common directory with azure-sdk-tools for PR 1953
  eng/common/TestResources/New-TestResources.ps1
Labels: EngSys, Central-EngSys

#15422 Cosmos DB - Add throughput handling and creation
  sdk/cosmos/azcosmos/cosmos_client.go
  sdk/cosmos/azcosmos/cosmos_client_connection.go
  sdk/cosmos/azcosmos/cosmos_container.go
  sdk/cosmos/azcosmos/cosmos_database.go
  sdk/cosmos/azcosmos/cosmos_error.go
  sdk/cosmos/azcosmos/cosmos_headers.go
  sdk/cosmos/azcosmos/cosmos_offers.go
  sdk/cosmos/azcosmos/cosmos_operation_context.go
  sdk/cosmos/azcosmos/emulator_cosmos_container_test.go
  sdk/cosmos/azcosmos/emulator_cosmos_database_test.go
  sdk/cosmos/azcosmos/emulator_cosmos_item_test.go
  sdk/cosmos/azcosmos/emulator_tests.go
  sdk/cosmos/azcosmos/shared_key_credential.go
  sdk/cosmos/azcosmos/shared_key_credential_test.go
  sdk/cosmos/azcosmos/throughput_properties.go
  sdk/cosmos/azcosmos/throughput_properties_test.go
  sdk/cosmos/azcosmos/throughput_request_options.go
  sdk/cosmos/azcosmos/throughput_request_options_test.go
  sdk/cosmos/azcosmos/throughput_response.go
  sdk/cosmos/azcosmos/throughput_response_test.go
Labels: Cosmos

#15377 Return CredentialUnavailableError when IMDS has no assigned identity
  sdk/azidentity/managed_identity_client.go
  sdk/azidentity/managed_identity_credential_test.go
Labels: Azure.Identity
