Repository Azure/azure-sdk-for-go, pull requests merged in 2021-01, with the labels that each got.

#14086 Fix typo in README.md
  README.md
Labels: customer-reported

#14075 Sync eng/common directory with azure-sdk-tools for PR 1299
  eng/common/scripts/Update-ChangeLog.ps1
Labels: Central-EngSys, EngSys

#14089 Sync eng/common directory with azure-sdk-tools for PR 1278
  eng/common/scripts/Helpers/DevOps-WorkItem-Helpers.ps1
  eng/common/scripts/SemVer.ps1
  eng/common/scripts/Update-DevOps-Release-WorkItem.ps1
Labels: Central-EngSys, EngSys

#14088 Sync eng/common directory with azure-sdk-tools for PR 1298
  eng/common/scripts/copy-docs-to-blobstorage.ps1
Labels: Central-EngSys, EngSys

#14094 Sync eng/common directory with azure-sdk-tools for PR 1302
  eng/common/scripts/Verify-Links.ps1
Labels: Central-EngSys, EngSys

#14093 Sync eng/common directory with azure-sdk-tools for PR 1301
  eng/common/Update-Change-Log.ps1
  eng/common/scripts/Update-ChangeLog.ps1
Labels: Central-EngSys, EngSys

#14113 Sync eng/common directory with azure-sdk-tools for PR 1306
  eng/common/scripts/update-docs-ci.ps1
  eng/common/scripts/update-docs-metadata.ps1
Labels: Central-EngSys, EngSys

#14115 Sync eng/common directory with azure-sdk-tools for PR 1308
  eng/common/Update-Change-Log.ps1
  eng/common/scripts/Update-ChangeLog.ps1
Labels: Central-EngSys, EngSys

#14122 Sync eng/common directory with azure-sdk-tools for PR 1304
  eng/common/pipelines/templates/steps/prepare-pipelines.yml
Labels: Central-EngSys, EngSys

#14123 Sync eng/common directory with azure-sdk-tools for PR 1304
  eng/common/pipelines/templates/steps/prepare-pipelines.yml
Labels: Central-EngSys, EngSys

#14142 Sync eng/common directory with azure-sdk-tools for PR 1314
  eng/common/pipelines/templates/steps/install-pipeline-generation.yml
Labels: Central-EngSys, EngSys

#14091 Test Cases for Gotrack2 Blob SDK
  sdk/storage/azblob/go.mod
  sdk/storage/azblob/go.sum
  sdk/storage/azblob/shared_policy_shared_key_credential.go
  sdk/storage/azblob/zc_access_conditions.go
  sdk/storage/azblob/zc_access_policy.go
  sdk/storage/azblob/zc_appendBlobClient.go
  sdk/storage/azblob/zc_appendBlobRequestOptions.go
  sdk/storage/azblob/zc_blobClient.go
  sdk/storage/azblob/zc_blobRequestOptions.go
  sdk/storage/azblob/zc_blockBlobClient.go
  sdk/storage/azblob/zc_blockBlobRequestOptions.go
  sdk/storage/azblob/zc_containerClient.go
  sdk/storage/azblob/zc_containerRequestOptions.go
  sdk/storage/azblob/zc_pageBlobClient.go
  sdk/storage/azblob/zc_pageBlobRequestOptions.go
  sdk/storage/azblob/zc_parsing_urls.go
  sdk/storage/azblob/zc_response_helpers.go
  sdk/storage/azblob/zc_retry_reader.go
  sdk/storage/azblob/zc_serviceClient.go
  sdk/storage/azblob/zc_validators.go
  sdk/storage/azblob/zt_append_blob_client_test.go
  sdk/storage/azblob/zt_blob_tags_test.go
  sdk/storage/azblob/zt_blob_versioning_test.go
  sdk/storage/azblob/zt_block_blob_client_test.go
  sdk/storage/azblob/zt_client_provided_key_test.go
  sdk/storage/azblob/zt_container_client_test.go
  sdk/storage/azblob/zt_page_blob_client_test.go
  sdk/storage/azblob/zt_service_client_test.go
  sdk/storage/azblob/zt_test.go
Labels: Storage

#14177 Sync eng/common directory with azure-sdk-tools for PR 1318
  eng/common/docgeneration/Generate-DocIndex.ps1
  eng/common/scripts/Create-APIReview.ps1
  eng/common/scripts/Package-Properties.ps1
  eng/common/scripts/artifact-metadata-parsing.ps1
  eng/common/scripts/copy-docs-to-blobstorage.ps1
  eng/common/scripts/update-docs-ci.ps1
Labels: Central-EngSys, EngSys

#14148 Enable 1ES hosted pools
  azure-pipelines.yml
  eng/pipelines/templates/jobs/archetype-sdk-client-samples.yml
  eng/pipelines/templates/jobs/archetype-sdk-client.yml
  sdk/armcore/ci.yml
Labels: Central-EngSys, EngSys

#14191 Sync eng/common directory with azure-sdk-tools for PR 1317
  eng/common/pipelines/templates/steps/get-pr-owners.yml
Labels: Central-EngSys, EngSys

#14194 Sync eng/common directory with azure-sdk-tools for PR 1327
  eng/common/pipelines/templates/steps/bypass-local-dns.yml
Labels: Central-EngSys, EngSys

#14197 Sync eng/common directory with azure-sdk-tools for PR 1251
  eng/common/docgeneration/Generate-DocIndex.ps1
  eng/common/scripts/Package-Properties.ps1
  eng/common/scripts/Prepare-Release.ps1
  eng/common/scripts/common.ps1
Labels: Central-EngSys, EngSys

#14212 Sync eng/common directory with azure-sdk-tools for PR 1335
  eng/common/scripts/ChangeLog-Operations.ps1
  eng/common/scripts/SemVer.ps1
  eng/common/scripts/Update-ChangeLog.ps1
Labels: Central-EngSys, EngSys

#14227 Sync eng/common directory with azure-sdk-tools for PR 1343
  eng/common/docgeneration/Generate-DocIndex.ps1
  eng/common/docgeneration/docfx.json
  eng/common/docgeneration/templates/matthews/styles/main.js
Labels: Central-EngSys, EngSys

#14230 Sync eng/common directory with azure-sdk-tools for PR 1341
  eng/common/pipelines/templates/steps/verify-links.yml
Labels: Central-EngSys, EngSys

#14239 Sync eng/common directory with azure-sdk-tools for PR 1345
  eng/common/pipelines/templates/steps/daily-dev-build-variable.yml
  eng/common/scripts/Create-APIReview.ps1
  eng/common/scripts/Package-Properties.ps1
  eng/common/scripts/Save-Package-Properties.ps1
Labels: Central-EngSys, EngSys
