Repository Azure/azure-sdk-for-go, pull requests merged in 2021-06, with the labels that each got.

#14714 Sync eng/common directory with azure-sdk-tools for PR 1611
  eng/common/scripts/Helpers/ApiView-Helpers.ps1
  eng/common/scripts/Prepare-Release.ps1
Labels: Central-EngSys, EngSys

#14740 Sync eng/common directory with azure-sdk-tools for PR 1658
  eng/common/scripts/Delete-RemoteBranches.ps1
Labels: Central-EngSys, EngSys

#14743 Sync eng/common directory with azure-sdk-tools for PR 1654
  eng/common/pipelines/templates/jobs/archetype-sdk-tests-generate.yml
Labels: Central-EngSys, EngSys

#14762 Sync eng/common directory with azure-sdk-tools for PR 1685
  eng/common/scripts/ChangeLog-Operations.ps1
  eng/common/scripts/Update-ChangeLog.ps1
  eng/common/scripts/Verify-ChangeLog.ps1
Labels: Central-EngSys, EngSys

#14780 Sync eng/common directory with azure-sdk-tools for PR 1688
  eng/common/scripts/ChangeLog-Operations.ps1
Labels: Central-EngSys, EngSys

#14776 update with latest code generator
  sdk/keyvault/armkeyvault/CHANGELOG.md
  sdk/storage/armstorage/_meta.json
  sdk/storage/armstorage/go.mod
  sdk/storage/armstorage/go.sum
  sdk/storage/armstorage/zz_generated_blobcontainers_client.go
  sdk/storage/armstorage/zz_generated_connection.go
  sdk/storage/armstorage/zz_generated_constants.go
  sdk/storage/armstorage/zz_generated_pagers.go
  sdk/storage/armstorage/zz_generated_pollers.go
  sdk/storage/armstorage/zz_generated_storageaccounts_client.go
Labels: Storage

#14797 Sync eng/common directory with azure-sdk-tools for PR 1711
  eng/common/pipelines/templates/steps/set-default-branch.yml
  eng/common/scripts/update-docs-metadata.ps1
Labels: Central-EngSys, EngSys

#14870 Sync eng/common directory with azure-sdk-tools for PR 1716
  eng/common/README.md
  eng/common/docgeneration/Generate-DocIndex.ps1
  eng/common/pipelines/templates/steps/check-spelling.yml
  eng/common/pipelines/templates/steps/docs-metadata-release.yml
  eng/common/pipelines/templates/steps/eng-common-workflow-enforcer.yml
  eng/common/scripts/Create-APIReview.ps1
  eng/common/scripts/Package-Properties.ps1
  eng/common/scripts/Prepare-Release.ps1
  eng/common/scripts/Update-DocsMsPackages.ps1
  eng/common/scripts/artifact-metadata-parsing.ps1
  eng/common/scripts/copy-docs-to-blobstorage.ps1
Labels: Central-EngSys, EngSys

#14871 Sync eng/common directory with azure-sdk-tools for PR 1719
  eng/common/pipelines/templates/steps/install-pipeline-generation.yml
Labels: Central-EngSys, EngSys

#14887 Sync eng/common directory with azure-sdk-tools for PR 1729
  eng/common/scripts/Create-APIReview.ps1
  eng/common/scripts/Package-Properties.ps1
  eng/common/scripts/Save-Package-Properties.ps1
Labels: Central-EngSys, EngSys

#14896 Sync eng/common directory with azure-sdk-tools for PR 1736
  eng/common/pipelines/templates/steps/bypass-local-dns.yml
Labels: Central-EngSys, EngSys

#14911 Sync eng/common directory with azure-sdk-tools for PR 1739
  eng/common/scripts/Verify-Links.ps1
  eng/common/scripts/update-docs-metadata.ps1
Labels: Central-EngSys, EngSys

#14934 Sync eng/common directory with azure-sdk-tools for PR 1759
  eng/common/scripts/Helpers/DevOps-WorkItem-Helpers.ps1
Labels: Central-EngSys, EngSys

#14947 Add prepare pipelines pipeline
  eng/pipelines/prepare-pipelines.yml
Labels: Central-EngSys

#14946 Adding CI file
  sdk/storage/azblob/ci.yml
Labels: Storage

#14938 Sync eng/common directory with azure-sdk-tools for PR 1763
  eng/common/scripts/Package-Properties.ps1
Labels: Central-EngSys, EngSys

#14888 [Tables] Update from testframework -> recording
  sdk/tables/aztable/ci.yml
  sdk/tables/aztable/table_client_test.go
  sdk/tables/aztable/table_service_client_test.go
  sdk/tables/aztable/zt_table_recorded_tests.go
Labels: Tables
