Repository Azure/azure-sdk-for-go, pull requests merged in 2021-12, with the labels that each got.

#16253 Release sdk/resourcemanger/containerinstance/armcontainerinstance v0.1.0
  sdk/resourcemanager/containerinstance/armcontainerinstance/CHANGELOG.md
  sdk/resourcemanager/containerinstance/armcontainerinstance/LICENSE.txt
  sdk/resourcemanager/containerinstance/armcontainerinstance/README.md
  sdk/resourcemanager/containerinstance/armcontainerinstance/autorest.md
  sdk/resourcemanager/containerinstance/armcontainerinstance/build.go
  sdk/resourcemanager/containerinstance/armcontainerinstance/ci.yml
  sdk/resourcemanager/containerinstance/armcontainerinstance/go.mod
  sdk/resourcemanager/containerinstance/armcontainerinstance/go.sum
  sdk/resourcemanager/containerinstance/armcontainerinstance/go_mod_tidy_hack.go
  sdk/resourcemanager/containerinstance/armcontainerinstance/ze_generated_example_containergroups_client_test.go
  sdk/resourcemanager/containerinstance/armcontainerinstance/ze_generated_example_containers_client_test.go
  sdk/resourcemanager/containerinstance/armcontainerinstance/ze_generated_example_location_client_test.go
  sdk/resourcemanager/containerinstance/armcontainerinstance/ze_generated_example_operations_client_test.go
  sdk/resourcemanager/containerinstance/armcontainerinstance/zz_generated_constants.go
  sdk/resourcemanager/containerinstance/armcontainerinstance/zz_generated_containergroups_client.go
  sdk/resourcemanager/containerinstance/armcontainerinstance/zz_generated_containers_client.go
  sdk/resourcemanager/containerinstance/armcontainerinstance/zz_generated_location_client.go
  sdk/resourcemanager/containerinstance/armcontainerinstance/zz_generated_models.go
  sdk/resourcemanager/containerinstance/armcontainerinstance/zz_generated_operations_client.go
  sdk/resourcemanager/containerinstance/armcontainerinstance/zz_generated_pagers.go
  sdk/resourcemanager/containerinstance/armcontainerinstance/zz_generated_pollers.go
  sdk/resourcemanager/containerinstance/armcontainerinstance/zz_generated_response_types.go
  sdk/resourcemanager/containerinstance/armcontainerinstance/zz_generated_time_rfc3339.go
Labels: Mgmt

#16252 Release sdk/resourcemanager/changeanalysis/armchangeanalysis v0.1.0
  sdk/resourcemanager/changeanalysis/armchangeanalysis/CHANGELOG.md
  sdk/resourcemanager/changeanalysis/armchangeanalysis/LICENSE.txt
  sdk/resourcemanager/changeanalysis/armchangeanalysis/README.md
  sdk/resourcemanager/changeanalysis/armchangeanalysis/autorest.md
  sdk/resourcemanager/changeanalysis/armchangeanalysis/build.go
  sdk/resourcemanager/changeanalysis/armchangeanalysis/ci.yml
  sdk/resourcemanager/changeanalysis/armchangeanalysis/go.mod
  sdk/resourcemanager/changeanalysis/armchangeanalysis/go.sum
  sdk/resourcemanager/changeanalysis/armchangeanalysis/go_mod_tidy_hack.go
  sdk/resourcemanager/changeanalysis/armchangeanalysis/ze_generated_example_changes_client_test.go
  sdk/resourcemanager/changeanalysis/armchangeanalysis/ze_generated_example_operations_client_test.go
  sdk/resourcemanager/changeanalysis/armchangeanalysis/ze_generated_example_resourcechanges_client_test.go
  sdk/resourcemanager/changeanalysis/armchangeanalysis/zz_generated_changes_client.go
  sdk/resourcemanager/changeanalysis/armchangeanalysis/zz_generated_constants.go
  sdk/resourcemanager/changeanalysis/armchangeanalysis/zz_generated_models.go
  sdk/resourcemanager/changeanalysis/armchangeanalysis/zz_generated_operations_client.go
  sdk/resourcemanager/changeanalysis/armchangeanalysis/zz_generated_pagers.go
  sdk/resourcemanager/changeanalysis/armchangeanalysis/zz_generated_resourcechanges_client.go
  sdk/resourcemanager/changeanalysis/armchangeanalysis/zz_generated_response_types.go
  sdk/resourcemanager/changeanalysis/armchangeanalysis/zz_generated_time_rfc3339.go
Labels: Mgmt

#16271 Release sdk/resourcemanager/azurearcdata/armazurearcdata v0.1.0
  sdk/resourcemanager/azurearcdata/armazurearcdata/CHANGELOG.md
  sdk/resourcemanager/azurearcdata/armazurearcdata/LICENSE.txt
  sdk/resourcemanager/azurearcdata/armazurearcdata/README.md
  sdk/resourcemanager/azurearcdata/armazurearcdata/autorest.md
  sdk/resourcemanager/azurearcdata/armazurearcdata/build.go
  sdk/resourcemanager/azurearcdata/armazurearcdata/ci.yml
  sdk/resourcemanager/azurearcdata/armazurearcdata/go.mod
  sdk/resourcemanager/azurearcdata/armazurearcdata/go.sum
  sdk/resourcemanager/azurearcdata/armazurearcdata/go_mod_tidy_hack.go
  sdk/resourcemanager/azurearcdata/armazurearcdata/ze_generated_example_datacontrollers_client_test.go
  sdk/resourcemanager/azurearcdata/armazurearcdata/ze_generated_example_operations_client_test.go
  sdk/resourcemanager/azurearcdata/armazurearcdata/ze_generated_example_sqlmanagedinstances_client_test.go
  sdk/resourcemanager/azurearcdata/armazurearcdata/ze_generated_example_sqlserverinstances_client_test.go
  sdk/resourcemanager/azurearcdata/armazurearcdata/zz_generated_constants.go
  sdk/resourcemanager/azurearcdata/armazurearcdata/zz_generated_datacontrollers_client.go
  sdk/resourcemanager/azurearcdata/armazurearcdata/zz_generated_models.go
  sdk/resourcemanager/azurearcdata/armazurearcdata/zz_generated_operations_client.go
  sdk/resourcemanager/azurearcdata/armazurearcdata/zz_generated_pagers.go
  sdk/resourcemanager/azurearcdata/armazurearcdata/zz_generated_pollers.go
  sdk/resourcemanager/azurearcdata/armazurearcdata/zz_generated_response_types.go
  sdk/resourcemanager/azurearcdata/armazurearcdata/zz_generated_sqlmanagedinstances_client.go
  sdk/resourcemanager/azurearcdata/armazurearcdata/zz_generated_sqlserverinstances_client.go
  sdk/resourcemanager/azurearcdata/armazurearcdata/zz_generated_time_rfc3339.go
Labels: Mgmt

#16272 Release sdk/resourcemanager/azuredata/armazuredata v0.1.0
  sdk/resourcemanager/azuredata/armazuredata/CHANGELOG.md
  sdk/resourcemanager/azuredata/armazuredata/LICENSE.txt
  sdk/resourcemanager/azuredata/armazuredata/README.md
  sdk/resourcemanager/azuredata/armazuredata/autorest.md
  sdk/resourcemanager/azuredata/armazuredata/build.go
  sdk/resourcemanager/azuredata/armazuredata/ci.yml
  sdk/resourcemanager/azuredata/armazuredata/go.mod
  sdk/resourcemanager/azuredata/armazuredata/go.sum
  sdk/resourcemanager/azuredata/armazuredata/go_mod_tidy_hack.go
  sdk/resourcemanager/azuredata/armazuredata/ze_generated_example_operations_client_test.go
  sdk/resourcemanager/azuredata/armazuredata/ze_generated_example_sqlserverregistrations_client_test.go
  sdk/resourcemanager/azuredata/armazuredata/ze_generated_example_sqlservers_client_test.go
  sdk/resourcemanager/azuredata/armazuredata/zz_generated_constants.go
  sdk/resourcemanager/azuredata/armazuredata/zz_generated_models.go
  sdk/resourcemanager/azuredata/armazuredata/zz_generated_operations_client.go
  sdk/resourcemanager/azuredata/armazuredata/zz_generated_pagers.go
  sdk/resourcemanager/azuredata/armazuredata/zz_generated_response_types.go
  sdk/resourcemanager/azuredata/armazuredata/zz_generated_sqlserverregistrations_client.go
  sdk/resourcemanager/azuredata/armazuredata/zz_generated_sqlservers_client.go
  sdk/resourcemanager/azuredata/armazuredata/zz_generated_time_rfc3339.go
Labels: Mgmt

#16274 Release sdk/resourcemanager/azurestackhci/armazurestackhci v0.1.0
  sdk/resourcemanager/azurestackhci/armazurestackhci/CHANGELOG.md
  sdk/resourcemanager/azurestackhci/armazurestackhci/LICENSE.txt
  sdk/resourcemanager/azurestackhci/armazurestackhci/README.md
  sdk/resourcemanager/azurestackhci/armazurestackhci/autorest.md
  sdk/resourcemanager/azurestackhci/armazurestackhci/build.go
  sdk/resourcemanager/azurestackhci/armazurestackhci/ci.yml
  sdk/resourcemanager/azurestackhci/armazurestackhci/go.mod
  sdk/resourcemanager/azurestackhci/armazurestackhci/go.sum
  sdk/resourcemanager/azurestackhci/armazurestackhci/go_mod_tidy_hack.go
  sdk/resourcemanager/azurestackhci/armazurestackhci/ze_generated_example_arcsettings_client_test.go
  sdk/resourcemanager/azurestackhci/armazurestackhci/ze_generated_example_clusters_client_test.go
  sdk/resourcemanager/azurestackhci/armazurestackhci/ze_generated_example_extensions_client_test.go
  sdk/resourcemanager/azurestackhci/armazurestackhci/zz_generated_arcsettings_client.go
  sdk/resourcemanager/azurestackhci/armazurestackhci/zz_generated_clusters_client.go
  sdk/resourcemanager/azurestackhci/armazurestackhci/zz_generated_constants.go
  sdk/resourcemanager/azurestackhci/armazurestackhci/zz_generated_extensions_client.go
  sdk/resourcemanager/azurestackhci/armazurestackhci/zz_generated_models.go
  sdk/resourcemanager/azurestackhci/armazurestackhci/zz_generated_operations_client.go
  sdk/resourcemanager/azurestackhci/armazurestackhci/zz_generated_pagers.go
  sdk/resourcemanager/azurestackhci/armazurestackhci/zz_generated_pollers.go
  sdk/resourcemanager/azurestackhci/armazurestackhci/zz_generated_response_types.go
  sdk/resourcemanager/azurestackhci/armazurestackhci/zz_generated_time_rfc3339.go
Labels: Mgmt

#16275 Release sdk/resourcemanager/baremetalinfrastructure/armbaremetalinfrastructure v0.1.0
  sdk/resourcemanager/baremetalinfrastructure/armbaremetalinfrastructure/CHANGELOG.md
  sdk/resourcemanager/baremetalinfrastructure/armbaremetalinfrastructure/LICENSE.txt
  sdk/resourcemanager/baremetalinfrastructure/armbaremetalinfrastructure/README.md
  sdk/resourcemanager/baremetalinfrastructure/armbaremetalinfrastructure/autorest.md
  sdk/resourcemanager/baremetalinfrastructure/armbaremetalinfrastructure/build.go
  sdk/resourcemanager/baremetalinfrastructure/armbaremetalinfrastructure/ci.yml
  sdk/resourcemanager/baremetalinfrastructure/armbaremetalinfrastructure/go.mod
  sdk/resourcemanager/baremetalinfrastructure/armbaremetalinfrastructure/go.sum
  sdk/resourcemanager/baremetalinfrastructure/armbaremetalinfrastructure/go_mod_tidy_hack.go
  sdk/resourcemanager/baremetalinfrastructure/armbaremetalinfrastructure/ze_generated_example_azurebaremetalinstances_client_test.go
  sdk/resourcemanager/baremetalinfrastructure/armbaremetalinfrastructure/ze_generated_example_operations_client_test.go
  sdk/resourcemanager/baremetalinfrastructure/armbaremetalinfrastructure/zz_generated_azurebaremetalinstances_client.go
  sdk/resourcemanager/baremetalinfrastructure/armbaremetalinfrastructure/zz_generated_constants.go
  sdk/resourcemanager/baremetalinfrastructure/armbaremetalinfrastructure/zz_generated_models.go
  sdk/resourcemanager/baremetalinfrastructure/armbaremetalinfrastructure/zz_generated_operations_client.go
  sdk/resourcemanager/baremetalinfrastructure/armbaremetalinfrastructure/zz_generated_pagers.go
  sdk/resourcemanager/baremetalinfrastructure/armbaremetalinfrastructure/zz_generated_response_types.go
  sdk/resourcemanager/baremetalinfrastructure/armbaremetalinfrastructure/zz_generated_time_rfc3339.go
Labels: Mgmt

#16276 Release sdk/resourcemanager/communication/armcommunication v0.1.0
  sdk/resourcemanager/communication/armcommunication/CHANGELOG.md
  sdk/resourcemanager/communication/armcommunication/LICENSE.txt
  sdk/resourcemanager/communication/armcommunication/README.md
  sdk/resourcemanager/communication/armcommunication/autorest.md
  sdk/resourcemanager/communication/armcommunication/build.go
  sdk/resourcemanager/communication/armcommunication/ci.yml
  sdk/resourcemanager/communication/armcommunication/go.mod
  sdk/resourcemanager/communication/armcommunication/go.sum
  sdk/resourcemanager/communication/armcommunication/go_mod_tidy_hack.go
  sdk/resourcemanager/communication/armcommunication/ze_generated_example_communicationservice_client_test.go
  sdk/resourcemanager/communication/armcommunication/zz_generated_communicationservice_client.go
  sdk/resourcemanager/communication/armcommunication/zz_generated_constants.go
  sdk/resourcemanager/communication/armcommunication/zz_generated_models.go
  sdk/resourcemanager/communication/armcommunication/zz_generated_operations_client.go
  sdk/resourcemanager/communication/armcommunication/zz_generated_pagers.go
  sdk/resourcemanager/communication/armcommunication/zz_generated_pollers.go
  sdk/resourcemanager/communication/armcommunication/zz_generated_response_types.go
  sdk/resourcemanager/communication/armcommunication/zz_generated_time_rfc3339.go
Labels: Mgmt

#16277 Release sdk/resourcemanager/confidentialledger/armconfidentialledger v0.1.0
  sdk/resourcemanager/confidentialledger/armconfidentialledger/CHANGELOG.md
  sdk/resourcemanager/confidentialledger/armconfidentialledger/LICENSE.txt
  sdk/resourcemanager/confidentialledger/armconfidentialledger/README.md
  sdk/resourcemanager/confidentialledger/armconfidentialledger/autorest.md
  sdk/resourcemanager/confidentialledger/armconfidentialledger/build.go
  sdk/resourcemanager/confidentialledger/armconfidentialledger/ci.yml
  sdk/resourcemanager/confidentialledger/armconfidentialledger/go.mod
  sdk/resourcemanager/confidentialledger/armconfidentialledger/go.sum
  sdk/resourcemanager/confidentialledger/armconfidentialledger/go_mod_tidy_hack.go
  sdk/resourcemanager/confidentialledger/armconfidentialledger/ze_generated_example_confidentialledger_client_test.go
  sdk/resourcemanager/confidentialledger/armconfidentialledger/ze_generated_example_ledger_client_test.go
  sdk/resourcemanager/confidentialledger/armconfidentialledger/ze_generated_example_operations_client_test.go
  sdk/resourcemanager/confidentialledger/armconfidentialledger/zz_generated_confidentialledger_client.go
  sdk/resourcemanager/confidentialledger/armconfidentialledger/zz_generated_constants.go
  sdk/resourcemanager/confidentialledger/armconfidentialledger/zz_generated_ledger_client.go
  sdk/resourcemanager/confidentialledger/armconfidentialledger/zz_generated_models.go
  sdk/resourcemanager/confidentialledger/armconfidentialledger/zz_generated_operations_client.go
  sdk/resourcemanager/confidentialledger/armconfidentialledger/zz_generated_pagers.go
  sdk/resourcemanager/confidentialledger/armconfidentialledger/zz_generated_pollers.go
  sdk/resourcemanager/confidentialledger/armconfidentialledger/zz_generated_response_types.go
  sdk/resourcemanager/confidentialledger/armconfidentialledger/zz_generated_time_rfc3339.go
Labels: Mgmt

#16278 Release sdk/resourcemanager/databox/armdatabox v0.1.0
  sdk/resourcemanager/databox/armdatabox/CHANGELOG.md
  sdk/resourcemanager/databox/armdatabox/LICENSE.txt
  sdk/resourcemanager/databox/armdatabox/README.md
  sdk/resourcemanager/databox/armdatabox/autorest.md
  sdk/resourcemanager/databox/armdatabox/build.go
  sdk/resourcemanager/databox/armdatabox/ci.yml
  sdk/resourcemanager/databox/armdatabox/go.mod
  sdk/resourcemanager/databox/armdatabox/go.sum
  sdk/resourcemanager/databox/armdatabox/go_mod_tidy_hack.go
  sdk/resourcemanager/databox/armdatabox/ze_generated_example_databoxmanagementclient_client_test.go
  sdk/resourcemanager/databox/armdatabox/ze_generated_example_jobs_client_test.go
  sdk/resourcemanager/databox/armdatabox/ze_generated_example_operations_client_test.go
  sdk/resourcemanager/databox/armdatabox/ze_generated_example_service_client_test.go
  sdk/resourcemanager/databox/armdatabox/zz_generated_constants.go
  sdk/resourcemanager/databox/armdatabox/zz_generated_databoxmanagementclient_client.go
  sdk/resourcemanager/databox/armdatabox/zz_generated_jobs_client.go
  sdk/resourcemanager/databox/armdatabox/zz_generated_models.go
  sdk/resourcemanager/databox/armdatabox/zz_generated_operations_client.go
  sdk/resourcemanager/databox/armdatabox/zz_generated_pagers.go
  sdk/resourcemanager/databox/armdatabox/zz_generated_pollers.go
  sdk/resourcemanager/databox/armdatabox/zz_generated_polymorphic_helpers.go
  sdk/resourcemanager/databox/armdatabox/zz_generated_response_types.go
  sdk/resourcemanager/databox/armdatabox/zz_generated_service_client.go
  sdk/resourcemanager/databox/armdatabox/zz_generated_time_rfc3339.go
Labels: Mgmt

#16279 Release sdk/resourcemanager/databoxedge/armdataboxedge v0.1.0
  sdk/resourcemanager/databoxedge/armdataboxedge/CHANGELOG.md
  sdk/resourcemanager/databoxedge/armdataboxedge/LICENSE.txt
  sdk/resourcemanager/databoxedge/armdataboxedge/README.md
  sdk/resourcemanager/databoxedge/armdataboxedge/autorest.md
  sdk/resourcemanager/databoxedge/armdataboxedge/build.go
  sdk/resourcemanager/databoxedge/armdataboxedge/ci.yml
  sdk/resourcemanager/databoxedge/armdataboxedge/go.mod
  sdk/resourcemanager/databoxedge/armdataboxedge/go.sum
  sdk/resourcemanager/databoxedge/armdataboxedge/go_mod_tidy_hack.go
  sdk/resourcemanager/databoxedge/armdataboxedge/ze_generated_example_addons_client_test.go
  sdk/resourcemanager/databoxedge/armdataboxedge/ze_generated_example_alerts_client_test.go
  sdk/resourcemanager/databoxedge/armdataboxedge/ze_generated_example_availableskus_client_test.go
  sdk/resourcemanager/databoxedge/armdataboxedge/ze_generated_example_bandwidthschedules_client_test.go
  sdk/resourcemanager/databoxedge/armdataboxedge/ze_generated_example_containers_client_test.go
  sdk/resourcemanager/databoxedge/armdataboxedge/ze_generated_example_devices_client_test.go
  sdk/resourcemanager/databoxedge/armdataboxedge/ze_generated_example_diagnosticsettings_client_test.go
  sdk/resourcemanager/databoxedge/armdataboxedge/ze_generated_example_jobs_client_test.go
  sdk/resourcemanager/databoxedge/armdataboxedge/ze_generated_example_monitoringconfig_client_test.go
  sdk/resourcemanager/databoxedge/armdataboxedge/ze_generated_example_nodes_client_test.go
  sdk/resourcemanager/databoxedge/armdataboxedge/ze_generated_example_operations_client_test.go
  sdk/resourcemanager/databoxedge/armdataboxedge/ze_generated_example_operationsstatus_client_test.go
  sdk/resourcemanager/databoxedge/armdataboxedge/ze_generated_example_orders_client_test.go
  sdk/resourcemanager/databoxedge/armdataboxedge/ze_generated_example_roles_client_test.go
  sdk/resourcemanager/databoxedge/armdataboxedge/ze_generated_example_shares_client_test.go
  sdk/resourcemanager/databoxedge/armdataboxedge/ze_generated_example_storageaccountcredentials_client_test.go
  sdk/resourcemanager/databoxedge/armdataboxedge/ze_generated_example_storageaccounts_client_test.go
  sdk/resourcemanager/databoxedge/armdataboxedge/ze_generated_example_supportpackages_client_test.go
  sdk/resourcemanager/databoxedge/armdataboxedge/ze_generated_example_triggers_client_test.go
  sdk/resourcemanager/databoxedge/armdataboxedge/ze_generated_example_users_client_test.go
  sdk/resourcemanager/databoxedge/armdataboxedge/zz_generated_addons_client.go
  sdk/resourcemanager/databoxedge/armdataboxedge/zz_generated_alerts_client.go
  sdk/resourcemanager/databoxedge/armdataboxedge/zz_generated_availableskus_client.go
  sdk/resourcemanager/databoxedge/armdataboxedge/zz_generated_bandwidthschedules_client.go
  sdk/resourcemanager/databoxedge/armdataboxedge/zz_generated_constants.go
  sdk/resourcemanager/databoxedge/armdataboxedge/zz_generated_containers_client.go
  sdk/resourcemanager/databoxedge/armdataboxedge/zz_generated_devices_client.go
  sdk/resourcemanager/databoxedge/armdataboxedge/zz_generated_diagnosticsettings_client.go
  sdk/resourcemanager/databoxedge/armdataboxedge/zz_generated_jobs_client.go
  sdk/resourcemanager/databoxedge/armdataboxedge/zz_generated_models.go
  sdk/resourcemanager/databoxedge/armdataboxedge/zz_generated_monitoringconfig_client.go
  sdk/resourcemanager/databoxedge/armdataboxedge/zz_generated_nodes_client.go
  sdk/resourcemanager/databoxedge/armdataboxedge/zz_generated_operations_client.go
  sdk/resourcemanager/databoxedge/armdataboxedge/zz_generated_operationsstatus_client.go
  sdk/resourcemanager/databoxedge/armdataboxedge/zz_generated_orders_client.go
  sdk/resourcemanager/databoxedge/armdataboxedge/zz_generated_pagers.go
  sdk/resourcemanager/databoxedge/armdataboxedge/zz_generated_pollers.go
  sdk/resourcemanager/databoxedge/armdataboxedge/zz_generated_polymorphic_helpers.go
  sdk/resourcemanager/databoxedge/armdataboxedge/zz_generated_response_types.go
  sdk/resourcemanager/databoxedge/armdataboxedge/zz_generated_roles_client.go
  sdk/resourcemanager/databoxedge/armdataboxedge/zz_generated_shares_client.go
  sdk/resourcemanager/databoxedge/armdataboxedge/zz_generated_storageaccountcredentials_client.go
  sdk/resourcemanager/databoxedge/armdataboxedge/zz_generated_storageaccounts_client.go
  sdk/resourcemanager/databoxedge/armdataboxedge/zz_generated_supportpackages_client.go
  sdk/resourcemanager/databoxedge/armdataboxedge/zz_generated_time_rfc3339.go
  sdk/resourcemanager/databoxedge/armdataboxedge/zz_generated_triggers_client.go
  sdk/resourcemanager/databoxedge/armdataboxedge/zz_generated_users_client.go
Labels: Mgmt

#16218 Sync eng/common directory with azure-sdk-tools for PR 2248
  eng/common/TestResources/New-TestResources.ps1
  eng/common/TestResources/SubConfig-Helpers.ps1
  eng/common/TestResources/build-test-resource-config.yml
Labels: EngSys, Central-EngSys

#16372 Sync eng/common directory with azure-sdk-tools for PR 2352
  eng/common/pipelines/templates/steps/check-spelling.yml
  eng/common/scripts/check-spelling-in-changed-files.ps1
  eng/common/spelling/Invoke-Cspell.ps1
  eng/common/spelling/package-lock.json
  eng/common/spelling/package.json
Labels: EngSys, Central-EngSys

#16391 Sync eng/common directory with azure-sdk-tools for PR 2372
  eng/common/TestResources/New-TestResources.ps1
Labels: EngSys, Central-EngSys

#16374 [Secrets] adding timeout test
  sdk/keyvault/azsecrets/client_test.go
Labels: KeyVault

#16395 Sync eng/common directory with azure-sdk-tools for PR 2380
  eng/common/scripts/Verify-Readme.ps1
Labels: EngSys, Central-EngSys

#16354 Adreed/fix pagers
  sdk/storage/azblob/zc_container_client.go
Labels: Storage

#16404 Sync eng/common directory with azure-sdk-tools for PR 2327
  eng/common/pipelines/templates/steps/update-docsms-metadata.yml
  eng/common/scripts/Update-DocsMsMetadata.ps1
  eng/common/scripts/common.ps1
Labels: EngSys, Central-EngSys

#16309 Release sdk/resourcemanager/confluent/armconfluent v0.1.0
  sdk/resourcemanager/confluent/armconfluent/CHANGELOG.md
  sdk/resourcemanager/confluent/armconfluent/LICENSE.txt
  sdk/resourcemanager/confluent/armconfluent/README.md
  sdk/resourcemanager/confluent/armconfluent/autorest.md
  sdk/resourcemanager/confluent/armconfluent/build.go
  sdk/resourcemanager/confluent/armconfluent/ci.yml
  sdk/resourcemanager/confluent/armconfluent/go.mod
  sdk/resourcemanager/confluent/armconfluent/go.sum
  sdk/resourcemanager/confluent/armconfluent/go_mod_tidy_hack.go
  sdk/resourcemanager/confluent/armconfluent/ze_generated_example_marketplaceagreements_client_test.go
  sdk/resourcemanager/confluent/armconfluent/ze_generated_example_organization_client_test.go
  sdk/resourcemanager/confluent/armconfluent/ze_generated_example_organizationoperations_client_test.go
  sdk/resourcemanager/confluent/armconfluent/ze_generated_example_validations_client_test.go
  sdk/resourcemanager/confluent/armconfluent/zz_generated_constants.go
  sdk/resourcemanager/confluent/armconfluent/zz_generated_marketplaceagreements_client.go
  sdk/resourcemanager/confluent/armconfluent/zz_generated_models.go
  sdk/resourcemanager/confluent/armconfluent/zz_generated_organization_client.go
  sdk/resourcemanager/confluent/armconfluent/zz_generated_organizationoperations_client.go
  sdk/resourcemanager/confluent/armconfluent/zz_generated_pagers.go
  sdk/resourcemanager/confluent/armconfluent/zz_generated_pollers.go
  sdk/resourcemanager/confluent/armconfluent/zz_generated_response_types.go
  sdk/resourcemanager/confluent/armconfluent/zz_generated_time_rfc3339.go
  sdk/resourcemanager/confluent/armconfluent/zz_generated_validations_client.go
Labels: Mgmt

#16310 Release sdk/resourcemanager/datacatalog/armdatacatalog v0.1.0
  sdk/resourcemanager/datacatalog/armdatacatalog/CHANGELOG.md
  sdk/resourcemanager/datacatalog/armdatacatalog/LICENSE.txt
  sdk/resourcemanager/datacatalog/armdatacatalog/README.md
  sdk/resourcemanager/datacatalog/armdatacatalog/autorest.md
  sdk/resourcemanager/datacatalog/armdatacatalog/build.go
  sdk/resourcemanager/datacatalog/armdatacatalog/ci.yml
  sdk/resourcemanager/datacatalog/armdatacatalog/go.mod
  sdk/resourcemanager/datacatalog/armdatacatalog/go.sum
  sdk/resourcemanager/datacatalog/armdatacatalog/go_mod_tidy_hack.go
  sdk/resourcemanager/datacatalog/armdatacatalog/ze_generated_example_adccatalogs_client_test.go
  sdk/resourcemanager/datacatalog/armdatacatalog/ze_generated_example_adcoperations_client_test.go
  sdk/resourcemanager/datacatalog/armdatacatalog/zz_generated_adccatalogs_client.go
  sdk/resourcemanager/datacatalog/armdatacatalog/zz_generated_adcoperations_client.go
  sdk/resourcemanager/datacatalog/armdatacatalog/zz_generated_constants.go
  sdk/resourcemanager/datacatalog/armdatacatalog/zz_generated_models.go
  sdk/resourcemanager/datacatalog/armdatacatalog/zz_generated_pollers.go
  sdk/resourcemanager/datacatalog/armdatacatalog/zz_generated_response_types.go
Labels: Mgmt

#16311 Release sdk/resourcemanager/dataprotection/armdataprotection v0.1.0
  sdk/resourcemanager/dataprotection/armdataprotection/CHANGELOG.md
  sdk/resourcemanager/dataprotection/armdataprotection/LICENSE.txt
  sdk/resourcemanager/dataprotection/armdataprotection/README.md
  sdk/resourcemanager/dataprotection/armdataprotection/autorest.md
  sdk/resourcemanager/dataprotection/armdataprotection/build.go
  sdk/resourcemanager/dataprotection/armdataprotection/ci.yml
  sdk/resourcemanager/dataprotection/armdataprotection/go.mod
  sdk/resourcemanager/dataprotection/armdataprotection/go.sum
  sdk/resourcemanager/dataprotection/armdataprotection/go_mod_tidy_hack.go
  sdk/resourcemanager/dataprotection/armdataprotection/ze_generated_example_backupinstances_client_test.go
  sdk/resourcemanager/dataprotection/armdataprotection/ze_generated_example_backuppolicies_client_test.go
  sdk/resourcemanager/dataprotection/armdataprotection/ze_generated_example_backupvaultoperationresults_client_test.go
  sdk/resourcemanager/dataprotection/armdataprotection/ze_generated_example_backupvaults_client_test.go
  sdk/resourcemanager/dataprotection/armdataprotection/ze_generated_example_dataprotection_client_test.go
  sdk/resourcemanager/dataprotection/armdataprotection/ze_generated_example_dataprotectionoperations_client_test.go
  sdk/resourcemanager/dataprotection/armdataprotection/ze_generated_example_exportjobs_client_test.go
  sdk/resourcemanager/dataprotection/armdataprotection/ze_generated_example_exportjobsoperationresult_client_test.go
  sdk/resourcemanager/dataprotection/armdataprotection/ze_generated_example_jobs_client_test.go
  sdk/resourcemanager/dataprotection/armdataprotection/ze_generated_example_operationresult_client_test.go
  sdk/resourcemanager/dataprotection/armdataprotection/ze_generated_example_operationstatus_client_test.go
  sdk/resourcemanager/dataprotection/armdataprotection/ze_generated_example_recoverypoints_client_test.go
  sdk/resourcemanager/dataprotection/armdataprotection/ze_generated_example_resourceguards_client_test.go
  sdk/resourcemanager/dataprotection/armdataprotection/ze_generated_example_restorabletimeranges_client_test.go
  sdk/resourcemanager/dataprotection/armdataprotection/zz_generated_backupinstances_client.go
  sdk/resourcemanager/dataprotection/armdataprotection/zz_generated_backuppolicies_client.go
  sdk/resourcemanager/dataprotection/armdataprotection/zz_generated_backupvaultoperationresults_client.go
  sdk/resourcemanager/dataprotection/armdataprotection/zz_generated_backupvaults_client.go
  sdk/resourcemanager/dataprotection/armdataprotection/zz_generated_constants.go
  sdk/resourcemanager/dataprotection/armdataprotection/zz_generated_dataprotection_client.go
  sdk/resourcemanager/dataprotection/armdataprotection/zz_generated_dataprotectionoperations_client.go
  sdk/resourcemanager/dataprotection/armdataprotection/zz_generated_exportjobs_client.go
  sdk/resourcemanager/dataprotection/armdataprotection/zz_generated_exportjobsoperationresult_client.go
  sdk/resourcemanager/dataprotection/armdataprotection/zz_generated_jobs_client.go
  sdk/resourcemanager/dataprotection/armdataprotection/zz_generated_models.go
  sdk/resourcemanager/dataprotection/armdataprotection/zz_generated_operationresult_client.go
  sdk/resourcemanager/dataprotection/armdataprotection/zz_generated_operationstatus_client.go
  sdk/resourcemanager/dataprotection/armdataprotection/zz_generated_pagers.go
  sdk/resourcemanager/dataprotection/armdataprotection/zz_generated_pollers.go
  sdk/resourcemanager/dataprotection/armdataprotection/zz_generated_polymorphic_helpers.go
  sdk/resourcemanager/dataprotection/armdataprotection/zz_generated_recoverypoints_client.go
  sdk/resourcemanager/dataprotection/armdataprotection/zz_generated_resourceguards_client.go
  sdk/resourcemanager/dataprotection/armdataprotection/zz_generated_response_types.go
  sdk/resourcemanager/dataprotection/armdataprotection/zz_generated_restorabletimeranges_client.go
  sdk/resourcemanager/dataprotection/armdataprotection/zz_generated_time_rfc3339.go
Labels: Mgmt

#16312 Release sdk/resourcemanager/datashare/armdatashare v0.1.0
  sdk/resourcemanager/datashare/armdatashare/CHANGELOG.md
  sdk/resourcemanager/datashare/armdatashare/LICENSE.txt
  sdk/resourcemanager/datashare/armdatashare/README.md
  sdk/resourcemanager/datashare/armdatashare/autorest.md
  sdk/resourcemanager/datashare/armdatashare/build.go
  sdk/resourcemanager/datashare/armdatashare/ci.yml
  sdk/resourcemanager/datashare/armdatashare/go.mod
  sdk/resourcemanager/datashare/armdatashare/go.sum
  sdk/resourcemanager/datashare/armdatashare/go_mod_tidy_hack.go
  sdk/resourcemanager/datashare/armdatashare/ze_generated_example_accounts_client_test.go
  sdk/resourcemanager/datashare/armdatashare/ze_generated_example_consumerinvitations_client_test.go
  sdk/resourcemanager/datashare/armdatashare/ze_generated_example_consumersourcedatasets_client_test.go
  sdk/resourcemanager/datashare/armdatashare/ze_generated_example_datasetmappings_client_test.go
  sdk/resourcemanager/datashare/armdatashare/ze_generated_example_datasets_client_test.go
  sdk/resourcemanager/datashare/armdatashare/ze_generated_example_emailregistrations_client_test.go
  sdk/resourcemanager/datashare/armdatashare/ze_generated_example_invitations_client_test.go
  sdk/resourcemanager/datashare/armdatashare/ze_generated_example_operations_client_test.go
  sdk/resourcemanager/datashare/armdatashare/ze_generated_example_providersharesubscriptions_client_test.go
  sdk/resourcemanager/datashare/armdatashare/ze_generated_example_shares_client_test.go
  sdk/resourcemanager/datashare/armdatashare/ze_generated_example_sharesubscriptions_client_test.go
  sdk/resourcemanager/datashare/armdatashare/ze_generated_example_synchronizationsettings_client_test.go
  sdk/resourcemanager/datashare/armdatashare/ze_generated_example_triggers_client_test.go
  sdk/resourcemanager/datashare/armdatashare/zz_generated_accounts_client.go
  sdk/resourcemanager/datashare/armdatashare/zz_generated_constants.go
  sdk/resourcemanager/datashare/armdatashare/zz_generated_consumerinvitations_client.go
  sdk/resourcemanager/datashare/armdatashare/zz_generated_consumersourcedatasets_client.go
  sdk/resourcemanager/datashare/armdatashare/zz_generated_datasetmappings_client.go
  sdk/resourcemanager/datashare/armdatashare/zz_generated_datasets_client.go
  sdk/resourcemanager/datashare/armdatashare/zz_generated_emailregistrations_client.go
  sdk/resourcemanager/datashare/armdatashare/zz_generated_invitations_client.go
  sdk/resourcemanager/datashare/armdatashare/zz_generated_models.go
  sdk/resourcemanager/datashare/armdatashare/zz_generated_operations_client.go
  sdk/resourcemanager/datashare/armdatashare/zz_generated_pagers.go
  sdk/resourcemanager/datashare/armdatashare/zz_generated_pollers.go
  sdk/resourcemanager/datashare/armdatashare/zz_generated_polymorphic_helpers.go
  sdk/resourcemanager/datashare/armdatashare/zz_generated_providersharesubscriptions_client.go
  sdk/resourcemanager/datashare/armdatashare/zz_generated_response_types.go
  sdk/resourcemanager/datashare/armdatashare/zz_generated_shares_client.go
  sdk/resourcemanager/datashare/armdatashare/zz_generated_sharesubscriptions_client.go
  sdk/resourcemanager/datashare/armdatashare/zz_generated_synchronizationsettings_client.go
  sdk/resourcemanager/datashare/armdatashare/zz_generated_time_rfc3339.go
  sdk/resourcemanager/datashare/armdatashare/zz_generated_triggers_client.go
Labels: Mgmt

#16313 Release sdk/resourcemanager/deploymentmanager/armdeploymentmanager v0.1.0
  sdk/resourcemanager/deploymentmanager/armdeploymentmanager/CHANGELOG.md
  sdk/resourcemanager/deploymentmanager/armdeploymentmanager/LICENSE.txt
  sdk/resourcemanager/deploymentmanager/armdeploymentmanager/README.md
  sdk/resourcemanager/deploymentmanager/armdeploymentmanager/autorest.md
  sdk/resourcemanager/deploymentmanager/armdeploymentmanager/build.go
  sdk/resourcemanager/deploymentmanager/armdeploymentmanager/ci.yml
  sdk/resourcemanager/deploymentmanager/armdeploymentmanager/go.mod
  sdk/resourcemanager/deploymentmanager/armdeploymentmanager/go.sum
  sdk/resourcemanager/deploymentmanager/armdeploymentmanager/go_mod_tidy_hack.go
  sdk/resourcemanager/deploymentmanager/armdeploymentmanager/ze_generated_example_artifactsources_client_test.go
  sdk/resourcemanager/deploymentmanager/armdeploymentmanager/ze_generated_example_operations_client_test.go
  sdk/resourcemanager/deploymentmanager/armdeploymentmanager/ze_generated_example_rollouts_client_test.go
  sdk/resourcemanager/deploymentmanager/armdeploymentmanager/ze_generated_example_services_client_test.go
  sdk/resourcemanager/deploymentmanager/armdeploymentmanager/ze_generated_example_servicetopologies_client_test.go
  sdk/resourcemanager/deploymentmanager/armdeploymentmanager/ze_generated_example_serviceunits_client_test.go
  sdk/resourcemanager/deploymentmanager/armdeploymentmanager/ze_generated_example_steps_client_test.go
  sdk/resourcemanager/deploymentmanager/armdeploymentmanager/zz_generated_artifactsources_client.go
  sdk/resourcemanager/deploymentmanager/armdeploymentmanager/zz_generated_constants.go
  sdk/resourcemanager/deploymentmanager/armdeploymentmanager/zz_generated_models.go
  sdk/resourcemanager/deploymentmanager/armdeploymentmanager/zz_generated_operations_client.go
  sdk/resourcemanager/deploymentmanager/armdeploymentmanager/zz_generated_pollers.go
  sdk/resourcemanager/deploymentmanager/armdeploymentmanager/zz_generated_polymorphic_helpers.go
  sdk/resourcemanager/deploymentmanager/armdeploymentmanager/zz_generated_response_types.go
  sdk/resourcemanager/deploymentmanager/armdeploymentmanager/zz_generated_rollouts_client.go
  sdk/resourcemanager/deploymentmanager/armdeploymentmanager/zz_generated_services_client.go
  sdk/resourcemanager/deploymentmanager/armdeploymentmanager/zz_generated_servicetopologies_client.go
  sdk/resourcemanager/deploymentmanager/armdeploymentmanager/zz_generated_serviceunits_client.go
  sdk/resourcemanager/deploymentmanager/armdeploymentmanager/zz_generated_steps_client.go
  sdk/resourcemanager/deploymentmanager/armdeploymentmanager/zz_generated_time_rfc3339.go
Labels: Mgmt

#16314 Release sdk/resourcemanagerdesktopvirtualization/armdesktopvirtualization v0.1.0
  sdk/resourcemanager/desktopvirtualization/armdesktopvirtualization/CHANGELOG.md
  sdk/resourcemanager/desktopvirtualization/armdesktopvirtualization/LICENSE.txt
  sdk/resourcemanager/desktopvirtualization/armdesktopvirtualization/README.md
  sdk/resourcemanager/desktopvirtualization/armdesktopvirtualization/autorest.md
  sdk/resourcemanager/desktopvirtualization/armdesktopvirtualization/build.go
  sdk/resourcemanager/desktopvirtualization/armdesktopvirtualization/ci.yml
  sdk/resourcemanager/desktopvirtualization/armdesktopvirtualization/go.mod
  sdk/resourcemanager/desktopvirtualization/armdesktopvirtualization/go.sum
  sdk/resourcemanager/desktopvirtualization/armdesktopvirtualization/go_mod_tidy_hack.go
  sdk/resourcemanager/desktopvirtualization/armdesktopvirtualization/ze_generated_example_applicationgroups_client_test.go
  sdk/resourcemanager/desktopvirtualization/armdesktopvirtualization/ze_generated_example_applications_client_test.go
  sdk/resourcemanager/desktopvirtualization/armdesktopvirtualization/ze_generated_example_desktops_client_test.go
  sdk/resourcemanager/desktopvirtualization/armdesktopvirtualization/ze_generated_example_hostpools_client_test.go
  sdk/resourcemanager/desktopvirtualization/armdesktopvirtualization/ze_generated_example_msiximages_client_test.go
  sdk/resourcemanager/desktopvirtualization/armdesktopvirtualization/ze_generated_example_msixpackages_client_test.go
  sdk/resourcemanager/desktopvirtualization/armdesktopvirtualization/ze_generated_example_operations_client_test.go
  sdk/resourcemanager/desktopvirtualization/armdesktopvirtualization/ze_generated_example_privateendpointconnections_client_test.go
  sdk/resourcemanager/desktopvirtualization/armdesktopvirtualization/ze_generated_example_privatelinkresources_client_test.go
  sdk/resourcemanager/desktopvirtualization/armdesktopvirtualization/ze_generated_example_scalingplans_client_test.go
  sdk/resourcemanager/desktopvirtualization/armdesktopvirtualization/ze_generated_example_sessionhosts_client_test.go
  sdk/resourcemanager/desktopvirtualization/armdesktopvirtualization/ze_generated_example_startmenuitems_client_test.go
  sdk/resourcemanager/desktopvirtualization/armdesktopvirtualization/ze_generated_example_usersessions_client_test.go
  sdk/resourcemanager/desktopvirtualization/armdesktopvirtualization/ze_generated_example_workspaces_client_test.go
  sdk/resourcemanager/desktopvirtualization/armdesktopvirtualization/zz_generated_applicationgroups_client.go
  sdk/resourcemanager/desktopvirtualization/armdesktopvirtualization/zz_generated_applications_client.go
  sdk/resourcemanager/desktopvirtualization/armdesktopvirtualization/zz_generated_constants.go
  sdk/resourcemanager/desktopvirtualization/armdesktopvirtualization/zz_generated_desktops_client.go
  sdk/resourcemanager/desktopvirtualization/armdesktopvirtualization/zz_generated_hostpools_client.go
  sdk/resourcemanager/desktopvirtualization/armdesktopvirtualization/zz_generated_models.go
  sdk/resourcemanager/desktopvirtualization/armdesktopvirtualization/zz_generated_msiximages_client.go
  sdk/resourcemanager/desktopvirtualization/armdesktopvirtualization/zz_generated_msixpackages_client.go
  sdk/resourcemanager/desktopvirtualization/armdesktopvirtualization/zz_generated_operations_client.go
  sdk/resourcemanager/desktopvirtualization/armdesktopvirtualization/zz_generated_pagers.go
  sdk/resourcemanager/desktopvirtualization/armdesktopvirtualization/zz_generated_privateendpointconnections_client.go
  sdk/resourcemanager/desktopvirtualization/armdesktopvirtualization/zz_generated_privatelinkresources_client.go
  sdk/resourcemanager/desktopvirtualization/armdesktopvirtualization/zz_generated_response_types.go
  sdk/resourcemanager/desktopvirtualization/armdesktopvirtualization/zz_generated_scalingplans_client.go
  sdk/resourcemanager/desktopvirtualization/armdesktopvirtualization/zz_generated_sessionhosts_client.go
  sdk/resourcemanager/desktopvirtualization/armdesktopvirtualization/zz_generated_startmenuitems_client.go
  sdk/resourcemanager/desktopvirtualization/armdesktopvirtualization/zz_generated_time_rfc3339.go
  sdk/resourcemanager/desktopvirtualization/armdesktopvirtualization/zz_generated_usersessions_client.go
  sdk/resourcemanager/desktopvirtualization/armdesktopvirtualization/zz_generated_workspaces_client.go
Labels: Mgmt

#16315 Release sdk/resourcemanager/deviceprovisioningservices/armdeviceprovisioningservices v0.1.0
  sdk/resourcemanager/deviceprovisioningservices/armdeviceprovisioningservices/CHANGELOG.md
  sdk/resourcemanager/deviceprovisioningservices/armdeviceprovisioningservices/LICENSE.txt
  sdk/resourcemanager/deviceprovisioningservices/armdeviceprovisioningservices/README.md
  sdk/resourcemanager/deviceprovisioningservices/armdeviceprovisioningservices/autorest.md
  sdk/resourcemanager/deviceprovisioningservices/armdeviceprovisioningservices/build.go
  sdk/resourcemanager/deviceprovisioningservices/armdeviceprovisioningservices/ci.yml
  sdk/resourcemanager/deviceprovisioningservices/armdeviceprovisioningservices/go.mod
  sdk/resourcemanager/deviceprovisioningservices/armdeviceprovisioningservices/go.sum
  sdk/resourcemanager/deviceprovisioningservices/armdeviceprovisioningservices/go_mod_tidy_hack.go
  sdk/resourcemanager/deviceprovisioningservices/armdeviceprovisioningservices/ze_generated_example_dpscertificate_client_test.go
  sdk/resourcemanager/deviceprovisioningservices/armdeviceprovisioningservices/ze_generated_example_iotdpsresource_client_test.go
  sdk/resourcemanager/deviceprovisioningservices/armdeviceprovisioningservices/ze_generated_example_operations_client_test.go
  sdk/resourcemanager/deviceprovisioningservices/armdeviceprovisioningservices/zz_generated_constants.go
  sdk/resourcemanager/deviceprovisioningservices/armdeviceprovisioningservices/zz_generated_dpscertificate_client.go
  sdk/resourcemanager/deviceprovisioningservices/armdeviceprovisioningservices/zz_generated_iotdpsresource_client.go
  sdk/resourcemanager/deviceprovisioningservices/armdeviceprovisioningservices/zz_generated_models.go
  sdk/resourcemanager/deviceprovisioningservices/armdeviceprovisioningservices/zz_generated_operations_client.go
  sdk/resourcemanager/deviceprovisioningservices/armdeviceprovisioningservices/zz_generated_pagers.go
  sdk/resourcemanager/deviceprovisioningservices/armdeviceprovisioningservices/zz_generated_pollers.go
  sdk/resourcemanager/deviceprovisioningservices/armdeviceprovisioningservices/zz_generated_response_types.go
  sdk/resourcemanager/deviceprovisioningservices/armdeviceprovisioningservices/zz_generated_time_rfc1123.go
Labels: Mgmt

#16316 Release sdk/resourcemanager/deviceupdate/armdeviceupdate v0.1.0
  sdk/resourcemanager/deviceupdate/armdeviceupdate/CHANGELOG.md
  sdk/resourcemanager/deviceupdate/armdeviceupdate/LICENSE.txt
  sdk/resourcemanager/deviceupdate/armdeviceupdate/README.md
  sdk/resourcemanager/deviceupdate/armdeviceupdate/autorest.md
  sdk/resourcemanager/deviceupdate/armdeviceupdate/build.go
  sdk/resourcemanager/deviceupdate/armdeviceupdate/ci.yml
  sdk/resourcemanager/deviceupdate/armdeviceupdate/go.mod
  sdk/resourcemanager/deviceupdate/armdeviceupdate/go.sum
  sdk/resourcemanager/deviceupdate/armdeviceupdate/go_mod_tidy_hack.go
  sdk/resourcemanager/deviceupdate/armdeviceupdate/ze_generated_example_accounts_client_test.go
  sdk/resourcemanager/deviceupdate/armdeviceupdate/ze_generated_example_deviceupdate_client_test.go
  sdk/resourcemanager/deviceupdate/armdeviceupdate/ze_generated_example_instances_client_test.go
  sdk/resourcemanager/deviceupdate/armdeviceupdate/ze_generated_example_privateendpointconnectionproxies_client_test.go
  sdk/resourcemanager/deviceupdate/armdeviceupdate/ze_generated_example_privateendpointconnections_client_test.go
  sdk/resourcemanager/deviceupdate/armdeviceupdate/ze_generated_example_privatelinkresources_client_test.go
  sdk/resourcemanager/deviceupdate/armdeviceupdate/zz_generated_accounts_client.go
  sdk/resourcemanager/deviceupdate/armdeviceupdate/zz_generated_constants.go
  sdk/resourcemanager/deviceupdate/armdeviceupdate/zz_generated_deviceupdate_client.go
  sdk/resourcemanager/deviceupdate/armdeviceupdate/zz_generated_instances_client.go
  sdk/resourcemanager/deviceupdate/armdeviceupdate/zz_generated_models.go
  sdk/resourcemanager/deviceupdate/armdeviceupdate/zz_generated_operations_client.go
  sdk/resourcemanager/deviceupdate/armdeviceupdate/zz_generated_pagers.go
  sdk/resourcemanager/deviceupdate/armdeviceupdate/zz_generated_pollers.go
  sdk/resourcemanager/deviceupdate/armdeviceupdate/zz_generated_privateendpointconnectionproxies_client.go
  sdk/resourcemanager/deviceupdate/armdeviceupdate/zz_generated_privateendpointconnections_client.go
  sdk/resourcemanager/deviceupdate/armdeviceupdate/zz_generated_privatelinkresources_client.go
  sdk/resourcemanager/deviceupdate/armdeviceupdate/zz_generated_response_types.go
  sdk/resourcemanager/deviceupdate/armdeviceupdate/zz_generated_time_rfc3339.go
Labels: Mgmt

#16317 Release sdk/resourcemanager/kusto/armkusto v0.1.0
  sdk/resourcemanager/kusto/armkusto/CHANGELOG.md
  sdk/resourcemanager/kusto/armkusto/LICENSE.txt
  sdk/resourcemanager/kusto/armkusto/README.md
  sdk/resourcemanager/kusto/armkusto/autorest.md
  sdk/resourcemanager/kusto/armkusto/build.go
  sdk/resourcemanager/kusto/armkusto/ci.yml
  sdk/resourcemanager/kusto/armkusto/go.mod
  sdk/resourcemanager/kusto/armkusto/go.sum
  sdk/resourcemanager/kusto/armkusto/go_mod_tidy_hack.go
  sdk/resourcemanager/kusto/armkusto/ze_generated_example_attacheddatabaseconfigurations_client_test.go
  sdk/resourcemanager/kusto/armkusto/ze_generated_example_clusterprincipalassignments_client_test.go
  sdk/resourcemanager/kusto/armkusto/ze_generated_example_clusters_client_test.go
  sdk/resourcemanager/kusto/armkusto/ze_generated_example_databaseprincipalassignments_client_test.go
  sdk/resourcemanager/kusto/armkusto/ze_generated_example_databases_client_test.go
  sdk/resourcemanager/kusto/armkusto/ze_generated_example_dataconnections_client_test.go
  sdk/resourcemanager/kusto/armkusto/ze_generated_example_managedprivateendpoints_client_test.go
  sdk/resourcemanager/kusto/armkusto/ze_generated_example_operations_client_test.go
  sdk/resourcemanager/kusto/armkusto/ze_generated_example_operationsresults_client_test.go
  sdk/resourcemanager/kusto/armkusto/ze_generated_example_privateendpointconnections_client_test.go
  sdk/resourcemanager/kusto/armkusto/ze_generated_example_privatelinkresources_client_test.go
  sdk/resourcemanager/kusto/armkusto/ze_generated_example_scripts_client_test.go
  sdk/resourcemanager/kusto/armkusto/zz_generated_attacheddatabaseconfigurations_client.go
  sdk/resourcemanager/kusto/armkusto/zz_generated_clusterprincipalassignments_client.go
  sdk/resourcemanager/kusto/armkusto/zz_generated_clusters_client.go
  sdk/resourcemanager/kusto/armkusto/zz_generated_constants.go
  sdk/resourcemanager/kusto/armkusto/zz_generated_databaseprincipalassignments_client.go
  sdk/resourcemanager/kusto/armkusto/zz_generated_databases_client.go
  sdk/resourcemanager/kusto/armkusto/zz_generated_dataconnections_client.go
  sdk/resourcemanager/kusto/armkusto/zz_generated_managedprivateendpoints_client.go
  sdk/resourcemanager/kusto/armkusto/zz_generated_models.go
  sdk/resourcemanager/kusto/armkusto/zz_generated_operations_client.go
  sdk/resourcemanager/kusto/armkusto/zz_generated_operationsresults_client.go
  sdk/resourcemanager/kusto/armkusto/zz_generated_pagers.go
  sdk/resourcemanager/kusto/armkusto/zz_generated_pollers.go
  sdk/resourcemanager/kusto/armkusto/zz_generated_polymorphic_helpers.go
  sdk/resourcemanager/kusto/armkusto/zz_generated_privateendpointconnections_client.go
  sdk/resourcemanager/kusto/armkusto/zz_generated_privatelinkresources_client.go
  sdk/resourcemanager/kusto/armkusto/zz_generated_response_types.go
  sdk/resourcemanager/kusto/armkusto/zz_generated_scripts_client.go
  sdk/resourcemanager/kusto/armkusto/zz_generated_time_rfc3339.go
Labels: Mgmt

#16318 Release sdk/resourcemanager/costmanagement/armcostmanagement v0.1.0
  sdk/resourcemanager/costmanagement/armcostmanagement/CHANGELOG.md
  sdk/resourcemanager/costmanagement/armcostmanagement/LICENSE.txt
  sdk/resourcemanager/costmanagement/armcostmanagement/README.md
  sdk/resourcemanager/costmanagement/armcostmanagement/autorest.md
  sdk/resourcemanager/costmanagement/armcostmanagement/build.go
  sdk/resourcemanager/costmanagement/armcostmanagement/ci.yml
  sdk/resourcemanager/costmanagement/armcostmanagement/go.mod
  sdk/resourcemanager/costmanagement/armcostmanagement/go.sum
  sdk/resourcemanager/costmanagement/armcostmanagement/go_mod_tidy_hack.go
  sdk/resourcemanager/costmanagement/armcostmanagement/ze_generated_example_alerts_client_test.go
  sdk/resourcemanager/costmanagement/armcostmanagement/ze_generated_example_dimensions_client_test.go
  sdk/resourcemanager/costmanagement/armcostmanagement/ze_generated_example_exports_client_test.go
  sdk/resourcemanager/costmanagement/armcostmanagement/ze_generated_example_forecast_client_test.go
  sdk/resourcemanager/costmanagement/armcostmanagement/ze_generated_example_generatedetailedcostreport_client_test.go
  sdk/resourcemanager/costmanagement/armcostmanagement/ze_generated_example_generatedetailedcostreportoperationresults_client_test.go
  sdk/resourcemanager/costmanagement/armcostmanagement/ze_generated_example_generatedetailedcostreportoperationstatus_client_test.go
  sdk/resourcemanager/costmanagement/armcostmanagement/ze_generated_example_query_client_test.go
  sdk/resourcemanager/costmanagement/armcostmanagement/ze_generated_example_views_client_test.go
  sdk/resourcemanager/costmanagement/armcostmanagement/zz_generated_alerts_client.go
  sdk/resourcemanager/costmanagement/armcostmanagement/zz_generated_constants.go
  sdk/resourcemanager/costmanagement/armcostmanagement/zz_generated_dimensions_client.go
  sdk/resourcemanager/costmanagement/armcostmanagement/zz_generated_exports_client.go
  sdk/resourcemanager/costmanagement/armcostmanagement/zz_generated_forecast_client.go
  sdk/resourcemanager/costmanagement/armcostmanagement/zz_generated_generatedetailedcostreport_client.go
  sdk/resourcemanager/costmanagement/armcostmanagement/zz_generated_generatedetailedcostreportoperationresults_client.go
  sdk/resourcemanager/costmanagement/armcostmanagement/zz_generated_generatedetailedcostreportoperationstatus_client.go
  sdk/resourcemanager/costmanagement/armcostmanagement/zz_generated_models.go
  sdk/resourcemanager/costmanagement/armcostmanagement/zz_generated_operations_client.go
  sdk/resourcemanager/costmanagement/armcostmanagement/zz_generated_pagers.go
  sdk/resourcemanager/costmanagement/armcostmanagement/zz_generated_pollers.go
  sdk/resourcemanager/costmanagement/armcostmanagement/zz_generated_query_client.go
  sdk/resourcemanager/costmanagement/armcostmanagement/zz_generated_response_types.go
  sdk/resourcemanager/costmanagement/armcostmanagement/zz_generated_time_rfc3339.go
  sdk/resourcemanager/costmanagement/armcostmanagement/zz_generated_views_client.go
Labels: Mgmt

#16341 Release sdk/resourcemanager/customerlockbox/armcustomerlockbox v0.1.0
  sdk/resourcemanager/customerlockbox/armcustomerlockbox/CHANGELOG.md
  sdk/resourcemanager/customerlockbox/armcustomerlockbox/LICENSE.txt
  sdk/resourcemanager/customerlockbox/armcustomerlockbox/README.md
  sdk/resourcemanager/customerlockbox/armcustomerlockbox/autorest.md
  sdk/resourcemanager/customerlockbox/armcustomerlockbox/build.go
  sdk/resourcemanager/customerlockbox/armcustomerlockbox/ci.yml
  sdk/resourcemanager/customerlockbox/armcustomerlockbox/go.mod
  sdk/resourcemanager/customerlockbox/armcustomerlockbox/go.sum
  sdk/resourcemanager/customerlockbox/armcustomerlockbox/go_mod_tidy_hack.go
  sdk/resourcemanager/customerlockbox/armcustomerlockbox/ze_generated_example_get_client_test.go
  sdk/resourcemanager/customerlockbox/armcustomerlockbox/ze_generated_example_operations_client_test.go
  sdk/resourcemanager/customerlockbox/armcustomerlockbox/ze_generated_example_post_client_test.go
  sdk/resourcemanager/customerlockbox/armcustomerlockbox/ze_generated_example_requests_client_test.go
  sdk/resourcemanager/customerlockbox/armcustomerlockbox/zz_generated_constants.go
  sdk/resourcemanager/customerlockbox/armcustomerlockbox/zz_generated_get_client.go
  sdk/resourcemanager/customerlockbox/armcustomerlockbox/zz_generated_models.go
  sdk/resourcemanager/customerlockbox/armcustomerlockbox/zz_generated_operations_client.go
  sdk/resourcemanager/customerlockbox/armcustomerlockbox/zz_generated_pagers.go
  sdk/resourcemanager/customerlockbox/armcustomerlockbox/zz_generated_post_client.go
  sdk/resourcemanager/customerlockbox/armcustomerlockbox/zz_generated_requests_client.go
  sdk/resourcemanager/customerlockbox/armcustomerlockbox/zz_generated_response_types.go
  sdk/resourcemanager/customerlockbox/armcustomerlockbox/zz_generated_time_rfc3339.go
Labels: Mgmt

#16342 Release sdk/resourcemanager/digitaltwins/armdigitaltwins v0.1.0
  sdk/resourcemanager/digitaltwins/armdigitaltwins/CHANGELOG.md
  sdk/resourcemanager/digitaltwins/armdigitaltwins/LICENSE.txt
  sdk/resourcemanager/digitaltwins/armdigitaltwins/README.md
  sdk/resourcemanager/digitaltwins/armdigitaltwins/autorest.md
  sdk/resourcemanager/digitaltwins/armdigitaltwins/build.go
  sdk/resourcemanager/digitaltwins/armdigitaltwins/ci.yml
  sdk/resourcemanager/digitaltwins/armdigitaltwins/go.mod
  sdk/resourcemanager/digitaltwins/armdigitaltwins/go.sum
  sdk/resourcemanager/digitaltwins/armdigitaltwins/go_mod_tidy_hack.go
  sdk/resourcemanager/digitaltwins/armdigitaltwins/ze_generated_example_digitaltwins_client_test.go
  sdk/resourcemanager/digitaltwins/armdigitaltwins/ze_generated_example_digitaltwinsendpoint_client_test.go
  sdk/resourcemanager/digitaltwins/armdigitaltwins/ze_generated_example_operations_client_test.go
  sdk/resourcemanager/digitaltwins/armdigitaltwins/ze_generated_example_privateendpointconnections_client_test.go
  sdk/resourcemanager/digitaltwins/armdigitaltwins/ze_generated_example_privatelinkresources_client_test.go
  sdk/resourcemanager/digitaltwins/armdigitaltwins/zz_generated_constants.go
  sdk/resourcemanager/digitaltwins/armdigitaltwins/zz_generated_digitaltwins_client.go
  sdk/resourcemanager/digitaltwins/armdigitaltwins/zz_generated_digitaltwinsendpoint_client.go
  sdk/resourcemanager/digitaltwins/armdigitaltwins/zz_generated_models.go
  sdk/resourcemanager/digitaltwins/armdigitaltwins/zz_generated_operations_client.go
  sdk/resourcemanager/digitaltwins/armdigitaltwins/zz_generated_pagers.go
  sdk/resourcemanager/digitaltwins/armdigitaltwins/zz_generated_pollers.go
  sdk/resourcemanager/digitaltwins/armdigitaltwins/zz_generated_polymorphic_helpers.go
  sdk/resourcemanager/digitaltwins/armdigitaltwins/zz_generated_privateendpointconnections_client.go
  sdk/resourcemanager/digitaltwins/armdigitaltwins/zz_generated_privatelinkresources_client.go
  sdk/resourcemanager/digitaltwins/armdigitaltwins/zz_generated_response_types.go
  sdk/resourcemanager/digitaltwins/armdigitaltwins/zz_generated_time_rfc3339.go
Labels: Mgmt

#16343 Release sdk/resourcemanager/dns/armdns v0.1.0
  sdk/resourcemanager/dns/armdns/CHANGELOG.md
  sdk/resourcemanager/dns/armdns/LICENSE.txt
  sdk/resourcemanager/dns/armdns/README.md
  sdk/resourcemanager/dns/armdns/autorest.md
  sdk/resourcemanager/dns/armdns/build.go
  sdk/resourcemanager/dns/armdns/ci.yml
  sdk/resourcemanager/dns/armdns/go.mod
  sdk/resourcemanager/dns/armdns/go.sum
  sdk/resourcemanager/dns/armdns/go_mod_tidy_hack.go
  sdk/resourcemanager/dns/armdns/ze_generated_example_dnsresourcereference_client_test.go
  sdk/resourcemanager/dns/armdns/ze_generated_example_recordsets_client_test.go
  sdk/resourcemanager/dns/armdns/ze_generated_example_zones_client_test.go
  sdk/resourcemanager/dns/armdns/zz_generated_constants.go
  sdk/resourcemanager/dns/armdns/zz_generated_dnsresourcereference_client.go
  sdk/resourcemanager/dns/armdns/zz_generated_models.go
  sdk/resourcemanager/dns/armdns/zz_generated_pagers.go
  sdk/resourcemanager/dns/armdns/zz_generated_pollers.go
  sdk/resourcemanager/dns/armdns/zz_generated_recordsets_client.go
  sdk/resourcemanager/dns/armdns/zz_generated_response_types.go
  sdk/resourcemanager/dns/armdns/zz_generated_zones_client.go
Labels: Mgmt

#16344 Release sdk/resourcemanager/edgeorder/armedgeorder v0.1.0
  sdk/resourcemanager/edgeorder/armedgeorder/CHANGELOG.md
  sdk/resourcemanager/edgeorder/armedgeorder/LICENSE.txt
  sdk/resourcemanager/edgeorder/armedgeorder/README.md
  sdk/resourcemanager/edgeorder/armedgeorder/autorest.md
  sdk/resourcemanager/edgeorder/armedgeorder/build.go
  sdk/resourcemanager/edgeorder/armedgeorder/ci.yml
  sdk/resourcemanager/edgeorder/armedgeorder/go.mod
  sdk/resourcemanager/edgeorder/armedgeorder/go.sum
  sdk/resourcemanager/edgeorder/armedgeorder/go_mod_tidy_hack.go
  sdk/resourcemanager/edgeorder/armedgeorder/ze_generated_example_edgeordermanagementclient_client_test.go
  sdk/resourcemanager/edgeorder/armedgeorder/zz_generated_constants.go
  sdk/resourcemanager/edgeorder/armedgeorder/zz_generated_edgeordermanagementclient_client.go
  sdk/resourcemanager/edgeorder/armedgeorder/zz_generated_models.go
  sdk/resourcemanager/edgeorder/armedgeorder/zz_generated_pagers.go
  sdk/resourcemanager/edgeorder/armedgeorder/zz_generated_pollers.go
  sdk/resourcemanager/edgeorder/armedgeorder/zz_generated_polymorphic_helpers.go
  sdk/resourcemanager/edgeorder/armedgeorder/zz_generated_response_types.go
  sdk/resourcemanager/edgeorder/armedgeorder/zz_generated_time_rfc3339.go
Labels: Mgmt

#16346 Release sdk/resourcemanager/elastic/armelastic v0.1.0
  sdk/resourcemanager/elastic/armelastic/CHANGELOG.md
  sdk/resourcemanager/elastic/armelastic/LICENSE.txt
  sdk/resourcemanager/elastic/armelastic/README.md
  sdk/resourcemanager/elastic/armelastic/autorest.md
  sdk/resourcemanager/elastic/armelastic/build.go
  sdk/resourcemanager/elastic/armelastic/ci.yml
  sdk/resourcemanager/elastic/armelastic/go.mod
  sdk/resourcemanager/elastic/armelastic/go.sum
  sdk/resourcemanager/elastic/armelastic/go_mod_tidy_hack.go
  sdk/resourcemanager/elastic/armelastic/ze_generated_example_deploymentinfo_client_test.go
  sdk/resourcemanager/elastic/armelastic/ze_generated_example_monitoredresources_client_test.go
  sdk/resourcemanager/elastic/armelastic/ze_generated_example_monitors_client_test.go
  sdk/resourcemanager/elastic/armelastic/ze_generated_example_operations_client_test.go
  sdk/resourcemanager/elastic/armelastic/ze_generated_example_tagrules_client_test.go
  sdk/resourcemanager/elastic/armelastic/ze_generated_example_vmcollection_client_test.go
  sdk/resourcemanager/elastic/armelastic/ze_generated_example_vmhost_client_test.go
  sdk/resourcemanager/elastic/armelastic/ze_generated_example_vmingestion_client_test.go
  sdk/resourcemanager/elastic/armelastic/zz_generated_constants.go
  sdk/resourcemanager/elastic/armelastic/zz_generated_deploymentinfo_client.go
  sdk/resourcemanager/elastic/armelastic/zz_generated_models.go
  sdk/resourcemanager/elastic/armelastic/zz_generated_monitoredresources_client.go
  sdk/resourcemanager/elastic/armelastic/zz_generated_monitors_client.go
  sdk/resourcemanager/elastic/armelastic/zz_generated_operations_client.go
  sdk/resourcemanager/elastic/armelastic/zz_generated_pagers.go
  sdk/resourcemanager/elastic/armelastic/zz_generated_pollers.go
  sdk/resourcemanager/elastic/armelastic/zz_generated_response_types.go
  sdk/resourcemanager/elastic/armelastic/zz_generated_tagrules_client.go
  sdk/resourcemanager/elastic/armelastic/zz_generated_time_rfc3339.go
  sdk/resourcemanager/elastic/armelastic/zz_generated_vmcollection_client.go
  sdk/resourcemanager/elastic/armelastic/zz_generated_vmhost_client.go
  sdk/resourcemanager/elastic/armelastic/zz_generated_vmingestion_client.go
Labels: Mgmt

#16349 Release sdk/resourcemanager/frontdoor/armfrontdoor v0.1.0
  sdk/resourcemanager/frontdoor/armfrontdoor/CHANGELOG.md
  sdk/resourcemanager/frontdoor/armfrontdoor/LICENSE.txt
  sdk/resourcemanager/frontdoor/armfrontdoor/README.md
  sdk/resourcemanager/frontdoor/armfrontdoor/autorest.md
  sdk/resourcemanager/frontdoor/armfrontdoor/build.go
  sdk/resourcemanager/frontdoor/armfrontdoor/ci.yml
  sdk/resourcemanager/frontdoor/armfrontdoor/go.mod
  sdk/resourcemanager/frontdoor/armfrontdoor/go.sum
  sdk/resourcemanager/frontdoor/armfrontdoor/go_mod_tidy_hack.go
  sdk/resourcemanager/frontdoor/armfrontdoor/ze_generated_example_endpoints_client_test.go
  sdk/resourcemanager/frontdoor/armfrontdoor/ze_generated_example_experiments_client_test.go
  sdk/resourcemanager/frontdoor/armfrontdoor/ze_generated_example_frontdoornameavailability_client_test.go
  sdk/resourcemanager/frontdoor/armfrontdoor/ze_generated_example_frontdoornameavailabilitywithsubscription_client_test.go
  sdk/resourcemanager/frontdoor/armfrontdoor/ze_generated_example_frontdoors_client_test.go
  sdk/resourcemanager/frontdoor/armfrontdoor/ze_generated_example_frontendendpoints_client_test.go
  sdk/resourcemanager/frontdoor/armfrontdoor/ze_generated_example_managedrulesets_client_test.go
  sdk/resourcemanager/frontdoor/armfrontdoor/ze_generated_example_networkexperimentprofiles_client_test.go
  sdk/resourcemanager/frontdoor/armfrontdoor/ze_generated_example_policies_client_test.go
  sdk/resourcemanager/frontdoor/armfrontdoor/ze_generated_example_preconfiguredendpoints_client_test.go
  sdk/resourcemanager/frontdoor/armfrontdoor/ze_generated_example_reports_client_test.go
  sdk/resourcemanager/frontdoor/armfrontdoor/ze_generated_example_rulesengines_client_test.go
  sdk/resourcemanager/frontdoor/armfrontdoor/zz_generated_constants.go
  sdk/resourcemanager/frontdoor/armfrontdoor/zz_generated_endpoints_client.go
  sdk/resourcemanager/frontdoor/armfrontdoor/zz_generated_experiments_client.go
  sdk/resourcemanager/frontdoor/armfrontdoor/zz_generated_frontdoornameavailability_client.go
  sdk/resourcemanager/frontdoor/armfrontdoor/zz_generated_frontdoornameavailabilitywithsubscription_client.go
  sdk/resourcemanager/frontdoor/armfrontdoor/zz_generated_frontdoors_client.go
  sdk/resourcemanager/frontdoor/armfrontdoor/zz_generated_frontendendpoints_client.go
  sdk/resourcemanager/frontdoor/armfrontdoor/zz_generated_managedrulesets_client.go
  sdk/resourcemanager/frontdoor/armfrontdoor/zz_generated_models.go
  sdk/resourcemanager/frontdoor/armfrontdoor/zz_generated_networkexperimentprofiles_client.go
  sdk/resourcemanager/frontdoor/armfrontdoor/zz_generated_pagers.go
  sdk/resourcemanager/frontdoor/armfrontdoor/zz_generated_policies_client.go
  sdk/resourcemanager/frontdoor/armfrontdoor/zz_generated_pollers.go
  sdk/resourcemanager/frontdoor/armfrontdoor/zz_generated_polymorphic_helpers.go
  sdk/resourcemanager/frontdoor/armfrontdoor/zz_generated_preconfiguredendpoints_client.go
  sdk/resourcemanager/frontdoor/armfrontdoor/zz_generated_reports_client.go
  sdk/resourcemanager/frontdoor/armfrontdoor/zz_generated_response_types.go
  sdk/resourcemanager/frontdoor/armfrontdoor/zz_generated_rulesengines_client.go
  sdk/resourcemanager/frontdoor/armfrontdoor/zz_generated_time_rfc3339.go
Labels: Mgmt

#16350 Release sdk/resourcemanager/guestconfiguration/armguestconfiguration v0.1.0
  sdk/resourcemanager/guestconfiguration/armguestconfiguration/CHANGELOG.md
  sdk/resourcemanager/guestconfiguration/armguestconfiguration/LICENSE.txt
  sdk/resourcemanager/guestconfiguration/armguestconfiguration/README.md
  sdk/resourcemanager/guestconfiguration/armguestconfiguration/autorest.md
  sdk/resourcemanager/guestconfiguration/armguestconfiguration/build.go
  sdk/resourcemanager/guestconfiguration/armguestconfiguration/ci.yml
  sdk/resourcemanager/guestconfiguration/armguestconfiguration/go.mod
  sdk/resourcemanager/guestconfiguration/armguestconfiguration/go.sum
  sdk/resourcemanager/guestconfiguration/armguestconfiguration/go_mod_tidy_hack.go
  sdk/resourcemanager/guestconfiguration/armguestconfiguration/ze_generated_example_guestconfigurationassignmentreports_client_test.go
  sdk/resourcemanager/guestconfiguration/armguestconfiguration/ze_generated_example_guestconfigurationassignments_client_test.go
  sdk/resourcemanager/guestconfiguration/armguestconfiguration/ze_generated_example_guestconfigurationhcrpassignmentreports_client_test.go
  sdk/resourcemanager/guestconfiguration/armguestconfiguration/ze_generated_example_guestconfigurationhcrpassignments_client_test.go
  sdk/resourcemanager/guestconfiguration/armguestconfiguration/ze_generated_example_operations_client_test.go
  sdk/resourcemanager/guestconfiguration/armguestconfiguration/zz_generated_constants.go
  sdk/resourcemanager/guestconfiguration/armguestconfiguration/zz_generated_guestconfigurationassignmentreports_client.go
  sdk/resourcemanager/guestconfiguration/armguestconfiguration/zz_generated_guestconfigurationassignments_client.go
  sdk/resourcemanager/guestconfiguration/armguestconfiguration/zz_generated_guestconfigurationhcrpassignmentreports_client.go
  sdk/resourcemanager/guestconfiguration/armguestconfiguration/zz_generated_guestconfigurationhcrpassignments_client.go
  sdk/resourcemanager/guestconfiguration/armguestconfiguration/zz_generated_models.go
  sdk/resourcemanager/guestconfiguration/armguestconfiguration/zz_generated_operations_client.go
  sdk/resourcemanager/guestconfiguration/armguestconfiguration/zz_generated_response_types.go
  sdk/resourcemanager/guestconfiguration/armguestconfiguration/zz_generated_time_rfc3339.go
Labels: Mgmt

#16351 Release sdk/resourcemanager/devops/armdevops v0.1.0
  sdk/resourcemanager/devops/armdevops/CHANGELOG.md
  sdk/resourcemanager/devops/armdevops/LICENSE.txt
  sdk/resourcemanager/devops/armdevops/README.md
  sdk/resourcemanager/devops/armdevops/autorest.md
  sdk/resourcemanager/devops/armdevops/build.go
  sdk/resourcemanager/devops/armdevops/ci.yml
  sdk/resourcemanager/devops/armdevops/go.mod
  sdk/resourcemanager/devops/armdevops/go.sum
  sdk/resourcemanager/devops/armdevops/go_mod_tidy_hack.go
  sdk/resourcemanager/devops/armdevops/ze_generated_example_operations_client_test.go
  sdk/resourcemanager/devops/armdevops/ze_generated_example_pipelines_client_test.go
  sdk/resourcemanager/devops/armdevops/ze_generated_example_pipelinetemplatedefinitions_client_test.go
  sdk/resourcemanager/devops/armdevops/zz_generated_constants.go
  sdk/resourcemanager/devops/armdevops/zz_generated_models.go
  sdk/resourcemanager/devops/armdevops/zz_generated_operations_client.go
  sdk/resourcemanager/devops/armdevops/zz_generated_pagers.go
  sdk/resourcemanager/devops/armdevops/zz_generated_pipelines_client.go
  sdk/resourcemanager/devops/armdevops/zz_generated_pipelinetemplatedefinitions_client.go
  sdk/resourcemanager/devops/armdevops/zz_generated_pollers.go
  sdk/resourcemanager/devops/armdevops/zz_generated_response_types.go
Labels: Mgmt

#16490 Increment version for internal releases
  sdk/internal/CHANGELOG.md
  sdk/internal/version.go
Labels: auto-merge

#16407 Sync eng/common directory with azure-sdk-tools for PR 2381
  eng/common/pipelines/templates/steps/write-filesystemmetrics.yml
  eng/common/scripts/Write-FileSystemMetrics.ps1
Labels: EngSys, Central-EngSys

#16406 Sync eng/common directory with azure-sdk-tools for PR 2363
  eng/common/TestResources/New-TestResources.ps1
  eng/common/TestResources/New-TestResources.ps1.md
  eng/common/scripts/stress-testing/deploy-stress-tests.ps1
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: EngSys, Central-EngSys

#16501 Sync eng/common directory with azure-sdk-tools for PR 2393
  eng/common/scripts/Update-DocsMsPackages.ps1
Labels: EngSys, Central-EngSys

#16531 [Tables] Point customers to new tables package
  storage/README.md
Labels: Tables

#16533 Sync eng/common directory with azure-sdk-tools for PR 2402
  eng/common/scripts/Invoke-GitHubAPI.ps1
Labels: EngSys, Central-EngSys

#16537 Sync eng/common directory with azure-sdk-tools for PR 2408
  eng/common/scripts/stress-testing/find-all-stress-packages.ps1
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: EngSys, Central-EngSys

#16554 Sync eng/common directory with azure-sdk-tools for PR 2412
  eng/common/TestResources/New-TestResources.ps1
Labels: EngSys, Central-EngSys

#16556 Sync eng/common directory with azure-sdk-tools for PR 2415
  eng/common/scripts/Update-DocsMsMetadata.ps1
Labels: EngSys, Central-EngSys

#16538 Increment version for messaging/azservicebus releases
  sdk/messaging/azservicebus/CHANGELOG.md
  sdk/messaging/azservicebus/internal/constants.go
Labels: auto-merge

#16557 Sync eng/common directory with azure-sdk-tools for PR 2417
  eng/common/pipelines/templates/steps/verify-readme.yml
  eng/common/scripts/Verify-Readme.ps1
Labels: EngSys, Central-EngSys

#16243 Adopt msal for non-managed identity credentials
  sdk/azidentity/aad_identity_client.go
  sdk/azidentity/aad_identity_client_test.go
  sdk/azidentity/authorization_code_credential.go
  sdk/azidentity/authorization_code_credential_test.go
  sdk/azidentity/azidentity.go
  sdk/azidentity/azidentity_test.go
  sdk/azidentity/azure_cli_credential_test.go
  sdk/azidentity/chained_token_credential_test.go
  sdk/azidentity/client_certificate_credential.go
  sdk/azidentity/client_certificate_credential_test.go
  sdk/azidentity/client_secret_credential.go
  sdk/azidentity/client_secret_credential_test.go
  sdk/azidentity/default_azure_credential.go
  sdk/azidentity/default_azure_credential_test.go
  sdk/azidentity/device_code_credential.go
  sdk/azidentity/device_code_credential_test.go
  sdk/azidentity/environment_credential.go
  sdk/azidentity/environment_credential_test.go
  sdk/azidentity/errors.go
  sdk/azidentity/go.mod
  sdk/azidentity/go.sum
  sdk/azidentity/interactive_browser_credential.go
  sdk/azidentity/interactive_browser_credential_test.go
  sdk/azidentity/interactive_browser_server.go
  sdk/azidentity/jwt.go
  sdk/azidentity/live_test.go
  sdk/azidentity/managed_identity_client.go
  sdk/azidentity/managed_identity_client_test.go
  sdk/azidentity/managed_identity_credential.go
  sdk/azidentity/managed_identity_credential_test.go
  sdk/azidentity/testdata/certificate-with-chain.pem
  sdk/azidentity/testdata/recordings/TestAuthorizationCodeCredential_ConfidentialInvalidCodeLive.json
  sdk/azidentity/testdata/recordings/TestAuthorizationCodeCredential_ConfidentialLive.json
  sdk/azidentity/testdata/recordings/TestAuthorizationCodeCredential_PublicInvalidCodeLive.json
  sdk/azidentity/testdata/recordings/TestAuthorizationCodeCredential_PublicLive.json
  sdk/azidentity/testdata/recordings/TestClientCertificateCredential_InvalidCertLive.json
  sdk/azidentity/testdata/recordings/TestClientCertificateCredential_Live/PEM.json
  sdk/azidentity/testdata/recordings/TestClientCertificateCredential_Live/PKCS12.json
  sdk/azidentity/testdata/recordings/TestClientCertificateCredential_Live/SNI.json
  sdk/azidentity/testdata/recordings/TestClientSecretCredential_InvalidSecretLive.json
  sdk/azidentity/testdata/recordings/TestClientSecretCredential_Live.json
  sdk/azidentity/testdata/recordings/TestDeviceCodeCredential_Live.json
  sdk/azidentity/testdata/recordings/TestEnvironmentCredential_ClientSecretLive.json
  sdk/azidentity/testdata/recordings/TestEnvironmentCredential_InvalidClientSecretLive.json
  sdk/azidentity/testdata/recordings/TestEnvironmentCredential_InvalidPasswordLive.json
  sdk/azidentity/testdata/recordings/TestEnvironmentCredential_UserPasswordLive.json
  sdk/azidentity/testdata/recordings/TestUsernamePasswordCredential_InvalidPasswordLive.json
  sdk/azidentity/testdata/recordings/TestUsernamePasswordCredential_Live.json
  sdk/azidentity/username_password_credential.go
  sdk/azidentity/username_password_credential_test.go
Labels: Azure.Identity

#16534 [Secrets] Doc BugBash Fixes
  sdk/keyvault/azsecrets/README.md
  sdk/keyvault/azsecrets/client_test.go
  sdk/keyvault/azsecrets/consts.go
  sdk/keyvault/azsecrets/models.go
  sdk/keyvault/azsecrets/testdata/recordings/TestUpdateSecretProperties.json
Labels: KeyVault

#16648 Sync eng/common directory with azure-sdk-tools for PR 2442
  eng/common/scripts/Invoke-GitHubAPI.ps1
Labels: EngSys, Central-EngSys

#16600 [Release] sdk/resourcemanager/purview/armpurview/0.1.0
  sdk/resourcemanager/purview/armpurview/CHANGELOG.md
  sdk/resourcemanager/purview/armpurview/LICENSE.txt
  sdk/resourcemanager/purview/armpurview/README.md
  sdk/resourcemanager/purview/armpurview/autorest.md
  sdk/resourcemanager/purview/armpurview/build.go
  sdk/resourcemanager/purview/armpurview/ci.yml
  sdk/resourcemanager/purview/armpurview/go.mod
  sdk/resourcemanager/purview/armpurview/go.sum
  sdk/resourcemanager/purview/armpurview/go_mod_tidy_hack.go
  sdk/resourcemanager/purview/armpurview/ze_generated_example_accounts_client_test.go
  sdk/resourcemanager/purview/armpurview/ze_generated_example_defaultaccounts_client_test.go
  sdk/resourcemanager/purview/armpurview/ze_generated_example_operations_client_test.go
  sdk/resourcemanager/purview/armpurview/ze_generated_example_privateendpointconnections_client_test.go
  sdk/resourcemanager/purview/armpurview/ze_generated_example_privatelinkresources_client_test.go
  sdk/resourcemanager/purview/armpurview/zz_generated_accounts_client.go
  sdk/resourcemanager/purview/armpurview/zz_generated_constants.go
  sdk/resourcemanager/purview/armpurview/zz_generated_defaultaccounts_client.go
  sdk/resourcemanager/purview/armpurview/zz_generated_models.go
  sdk/resourcemanager/purview/armpurview/zz_generated_operations_client.go
  sdk/resourcemanager/purview/armpurview/zz_generated_pagers.go
  sdk/resourcemanager/purview/armpurview/zz_generated_pollers.go
  sdk/resourcemanager/purview/armpurview/zz_generated_privateendpointconnections_client.go
  sdk/resourcemanager/purview/armpurview/zz_generated_privatelinkresources_client.go
  sdk/resourcemanager/purview/armpurview/zz_generated_response_types.go
  sdk/resourcemanager/purview/armpurview/zz_generated_time_rfc3339.go
Labels: Mgmt

#16601 [Release] sdk/resourcemanager/quantum/armquantum/0.1.0
  sdk/resourcemanager/quantum/armquantum/CHANGELOG.md
  sdk/resourcemanager/quantum/armquantum/LICENSE.txt
  sdk/resourcemanager/quantum/armquantum/README.md
  sdk/resourcemanager/quantum/armquantum/autorest.md
  sdk/resourcemanager/quantum/armquantum/build.go
  sdk/resourcemanager/quantum/armquantum/ci.yml
  sdk/resourcemanager/quantum/armquantum/go.mod
  sdk/resourcemanager/quantum/armquantum/go.sum
  sdk/resourcemanager/quantum/armquantum/go_mod_tidy_hack.go
  sdk/resourcemanager/quantum/armquantum/ze_generated_example_offerings_client_test.go
  sdk/resourcemanager/quantum/armquantum/ze_generated_example_workspace_client_test.go
  sdk/resourcemanager/quantum/armquantum/ze_generated_example_workspaces_client_test.go
  sdk/resourcemanager/quantum/armquantum/zz_generated_constants.go
  sdk/resourcemanager/quantum/armquantum/zz_generated_models.go
  sdk/resourcemanager/quantum/armquantum/zz_generated_offerings_client.go
  sdk/resourcemanager/quantum/armquantum/zz_generated_operations_client.go
  sdk/resourcemanager/quantum/armquantum/zz_generated_pagers.go
  sdk/resourcemanager/quantum/armquantum/zz_generated_pollers.go
  sdk/resourcemanager/quantum/armquantum/zz_generated_response_types.go
  sdk/resourcemanager/quantum/armquantum/zz_generated_time_rfc3339.go
  sdk/resourcemanager/quantum/armquantum/zz_generated_workspace_client.go
  sdk/resourcemanager/quantum/armquantum/zz_generated_workspaces_client.go
Labels: Mgmt

#16602 [Release] sdk/resourcemanager/quota/armquota/0.1.0
  sdk/resourcemanager/quota/armquota/CHANGELOG.md
  sdk/resourcemanager/quota/armquota/LICENSE.txt
  sdk/resourcemanager/quota/armquota/README.md
  sdk/resourcemanager/quota/armquota/autorest.md
  sdk/resourcemanager/quota/armquota/build.go
  sdk/resourcemanager/quota/armquota/ci.yml
  sdk/resourcemanager/quota/armquota/go.mod
  sdk/resourcemanager/quota/armquota/go.sum
  sdk/resourcemanager/quota/armquota/go_mod_tidy_hack.go
  sdk/resourcemanager/quota/armquota/ze_generated_example_quota_client_test.go
  sdk/resourcemanager/quota/armquota/ze_generated_example_quotaoperation_client_test.go
  sdk/resourcemanager/quota/armquota/ze_generated_example_quotarequeststatus_client_test.go
  sdk/resourcemanager/quota/armquota/ze_generated_example_usages_client_test.go
  sdk/resourcemanager/quota/armquota/zz_generated_constants.go
  sdk/resourcemanager/quota/armquota/zz_generated_models.go
  sdk/resourcemanager/quota/armquota/zz_generated_pagers.go
  sdk/resourcemanager/quota/armquota/zz_generated_pollers.go
  sdk/resourcemanager/quota/armquota/zz_generated_polymorphic_helpers.go
  sdk/resourcemanager/quota/armquota/zz_generated_quota_client.go
  sdk/resourcemanager/quota/armquota/zz_generated_quotaoperation_client.go
  sdk/resourcemanager/quota/armquota/zz_generated_quotarequeststatus_client.go
  sdk/resourcemanager/quota/armquota/zz_generated_response_types.go
  sdk/resourcemanager/quota/armquota/zz_generated_time_rfc3339.go
  sdk/resourcemanager/quota/armquota/zz_generated_usages_client.go
Labels: Mgmt

#16617 [Release] sdk/resourcemanager/machinelearningservices/armmachinelearningservices/0.1.0
  sdk/resourcemanager/machinelearningservices/armmachinelearningservices/CHANGELOG.md
  sdk/resourcemanager/machinelearningservices/armmachinelearningservices/LICENSE.txt
  sdk/resourcemanager/machinelearningservices/armmachinelearningservices/README.md
  sdk/resourcemanager/machinelearningservices/armmachinelearningservices/autorest.md
  sdk/resourcemanager/machinelearningservices/armmachinelearningservices/build.go
  sdk/resourcemanager/machinelearningservices/armmachinelearningservices/ci.yml
  sdk/resourcemanager/machinelearningservices/armmachinelearningservices/go.mod
  sdk/resourcemanager/machinelearningservices/armmachinelearningservices/go.sum
  sdk/resourcemanager/machinelearningservices/armmachinelearningservices/go_mod_tidy_hack.go
  sdk/resourcemanager/machinelearningservices/armmachinelearningservices/ze_generated_example_compute_client_test.go
  sdk/resourcemanager/machinelearningservices/armmachinelearningservices/ze_generated_example_privateendpointconnections_client_test.go
  sdk/resourcemanager/machinelearningservices/armmachinelearningservices/ze_generated_example_privatelinkresources_client_test.go
  sdk/resourcemanager/machinelearningservices/armmachinelearningservices/ze_generated_example_quotas_client_test.go
  sdk/resourcemanager/machinelearningservices/armmachinelearningservices/ze_generated_example_usages_client_test.go
  sdk/resourcemanager/machinelearningservices/armmachinelearningservices/ze_generated_example_virtualmachinesizes_client_test.go
  sdk/resourcemanager/machinelearningservices/armmachinelearningservices/ze_generated_example_workspaceconnections_client_test.go
  sdk/resourcemanager/machinelearningservices/armmachinelearningservices/ze_generated_example_workspacefeatures_client_test.go
  sdk/resourcemanager/machinelearningservices/armmachinelearningservices/ze_generated_example_workspaces_client_test.go
  sdk/resourcemanager/machinelearningservices/armmachinelearningservices/ze_generated_example_workspaceskus_client_test.go
  sdk/resourcemanager/machinelearningservices/armmachinelearningservices/zz_generated_compute_client.go
  sdk/resourcemanager/machinelearningservices/armmachinelearningservices/zz_generated_constants.go
  sdk/resourcemanager/machinelearningservices/armmachinelearningservices/zz_generated_models.go
  sdk/resourcemanager/machinelearningservices/armmachinelearningservices/zz_generated_operations_client.go
  sdk/resourcemanager/machinelearningservices/armmachinelearningservices/zz_generated_pagers.go
  sdk/resourcemanager/machinelearningservices/armmachinelearningservices/zz_generated_pollers.go
  sdk/resourcemanager/machinelearningservices/armmachinelearningservices/zz_generated_polymorphic_helpers.go
  sdk/resourcemanager/machinelearningservices/armmachinelearningservices/zz_generated_privateendpointconnections_client.go
  sdk/resourcemanager/machinelearningservices/armmachinelearningservices/zz_generated_privatelinkresources_client.go
  sdk/resourcemanager/machinelearningservices/armmachinelearningservices/zz_generated_quotas_client.go
  sdk/resourcemanager/machinelearningservices/armmachinelearningservices/zz_generated_response_types.go
  sdk/resourcemanager/machinelearningservices/armmachinelearningservices/zz_generated_time_rfc3339.go
  sdk/resourcemanager/machinelearningservices/armmachinelearningservices/zz_generated_usages_client.go
  sdk/resourcemanager/machinelearningservices/armmachinelearningservices/zz_generated_virtualmachinesizes_client.go
  sdk/resourcemanager/machinelearningservices/armmachinelearningservices/zz_generated_workspaceconnections_client.go
  sdk/resourcemanager/machinelearningservices/armmachinelearningservices/zz_generated_workspacefeatures_client.go
  sdk/resourcemanager/machinelearningservices/armmachinelearningservices/zz_generated_workspaces_client.go
  sdk/resourcemanager/machinelearningservices/armmachinelearningservices/zz_generated_workspaceskus_client.go
Labels: Mgmt

#16618 [Release] sdk/resourcemanager/signalr/armsignalr/0.1.0
  sdk/resourcemanager/signalr/armsignalr/CHANGELOG.md
  sdk/resourcemanager/signalr/armsignalr/LICENSE.txt
  sdk/resourcemanager/signalr/armsignalr/README.md
  sdk/resourcemanager/signalr/armsignalr/autorest.md
  sdk/resourcemanager/signalr/armsignalr/build.go
  sdk/resourcemanager/signalr/armsignalr/ci.yml
  sdk/resourcemanager/signalr/armsignalr/go.mod
  sdk/resourcemanager/signalr/armsignalr/go.sum
  sdk/resourcemanager/signalr/armsignalr/go_mod_tidy_hack.go
  sdk/resourcemanager/signalr/armsignalr/ze_generated_example_operations_client_test.go
  sdk/resourcemanager/signalr/armsignalr/ze_generated_example_signalr_client_test.go
  sdk/resourcemanager/signalr/armsignalr/ze_generated_example_signalrprivateendpointconnections_client_test.go
  sdk/resourcemanager/signalr/armsignalr/ze_generated_example_signalrprivatelinkresources_client_test.go
  sdk/resourcemanager/signalr/armsignalr/ze_generated_example_signalrsharedprivatelinkresources_client_test.go
  sdk/resourcemanager/signalr/armsignalr/ze_generated_example_usages_client_test.go
  sdk/resourcemanager/signalr/armsignalr/zz_generated_constants.go
  sdk/resourcemanager/signalr/armsignalr/zz_generated_models.go
  sdk/resourcemanager/signalr/armsignalr/zz_generated_operations_client.go
  sdk/resourcemanager/signalr/armsignalr/zz_generated_pagers.go
  sdk/resourcemanager/signalr/armsignalr/zz_generated_pollers.go
  sdk/resourcemanager/signalr/armsignalr/zz_generated_response_types.go
  sdk/resourcemanager/signalr/armsignalr/zz_generated_signalr_client.go
  sdk/resourcemanager/signalr/armsignalr/zz_generated_signalrprivateendpointconnections_client.go
  sdk/resourcemanager/signalr/armsignalr/zz_generated_signalrprivatelinkresources_client.go
  sdk/resourcemanager/signalr/armsignalr/zz_generated_signalrsharedprivatelinkresources_client.go
  sdk/resourcemanager/signalr/armsignalr/zz_generated_time_rfc3339.go
  sdk/resourcemanager/signalr/armsignalr/zz_generated_usages_client.go
Labels: Mgmt

#16591 [Release] sdk/resourcemanager/monitor/armmonitor/0.3.0
  sdk/resourcemanager/monitor/armmonitor/CHANGELOG.md
  sdk/resourcemanager/monitor/armmonitor/autorest.md
  sdk/resourcemanager/monitor/armmonitor/go.mod
  sdk/resourcemanager/monitor/armmonitor/go.sum
  sdk/resourcemanager/monitor/armmonitor/ze_generated_example_actiongroups_client_test.go
  sdk/resourcemanager/monitor/armmonitor/ze_generated_example_activitylogalerts_client_test.go
  sdk/resourcemanager/monitor/armmonitor/ze_generated_example_activitylogs_client_test.go
  sdk/resourcemanager/monitor/armmonitor/ze_generated_example_alertruleincidents_client_test.go
  sdk/resourcemanager/monitor/armmonitor/ze_generated_example_alertrules_client_test.go
  sdk/resourcemanager/monitor/armmonitor/ze_generated_example_autoscalesettings_client_test.go
  sdk/resourcemanager/monitor/armmonitor/ze_generated_example_baselines_client_test.go
  sdk/resourcemanager/monitor/armmonitor/ze_generated_example_datacollectionendpoints_client_test.go
  sdk/resourcemanager/monitor/armmonitor/ze_generated_example_datacollectionruleassociations_client_test.go
  sdk/resourcemanager/monitor/armmonitor/ze_generated_example_datacollectionrules_client_test.go
  sdk/resourcemanager/monitor/armmonitor/ze_generated_example_diagnosticsettings_client_test.go
  sdk/resourcemanager/monitor/armmonitor/ze_generated_example_diagnosticsettingscategory_client_test.go
  sdk/resourcemanager/monitor/armmonitor/ze_generated_example_eventcategories_client_test.go
  sdk/resourcemanager/monitor/armmonitor/ze_generated_example_logprofiles_client_test.go
  sdk/resourcemanager/monitor/armmonitor/ze_generated_example_metricalerts_client_test.go
  sdk/resourcemanager/monitor/armmonitor/ze_generated_example_metricalertsstatus_client_test.go
  sdk/resourcemanager/monitor/armmonitor/ze_generated_example_metricdefinitions_client_test.go
  sdk/resourcemanager/monitor/armmonitor/ze_generated_example_metricnamespaces_client_test.go
  sdk/resourcemanager/monitor/armmonitor/ze_generated_example_metrics_client_test.go
  sdk/resourcemanager/monitor/armmonitor/ze_generated_example_operations_client_test.go
  sdk/resourcemanager/monitor/armmonitor/ze_generated_example_privateendpointconnections_client_test.go
  sdk/resourcemanager/monitor/armmonitor/ze_generated_example_privatelinkresources_client_test.go
  sdk/resourcemanager/monitor/armmonitor/ze_generated_example_privatelinkscopedresources_client_test.go
  sdk/resourcemanager/monitor/armmonitor/ze_generated_example_privatelinkscopeoperationstatus_client_test.go
  sdk/resourcemanager/monitor/armmonitor/ze_generated_example_privatelinkscopes_client_test.go
  sdk/resourcemanager/monitor/armmonitor/ze_generated_example_scheduledqueryrules_client_test.go
  sdk/resourcemanager/monitor/armmonitor/ze_generated_example_tenantactivitylogs_client_test.go
  sdk/resourcemanager/monitor/armmonitor/ze_generated_example_vminsights_client_test.go
  sdk/resourcemanager/monitor/armmonitor/zz_generated_actiongroups_client.go
  sdk/resourcemanager/monitor/armmonitor/zz_generated_constants.go
  sdk/resourcemanager/monitor/armmonitor/zz_generated_models.go
  sdk/resourcemanager/monitor/armmonitor/zz_generated_pollers.go
  sdk/resourcemanager/monitor/armmonitor/zz_generated_response_types.go
Labels: Mgmt

#16594 [Release] sdk/resourcemanager/peering/armpeering/0.1.0
  sdk/resourcemanager/peering/armpeering/CHANGELOG.md
  sdk/resourcemanager/peering/armpeering/LICENSE.txt
  sdk/resourcemanager/peering/armpeering/README.md
  sdk/resourcemanager/peering/armpeering/autorest.md
  sdk/resourcemanager/peering/armpeering/build.go
  sdk/resourcemanager/peering/armpeering/ci.yml
  sdk/resourcemanager/peering/armpeering/go.mod
  sdk/resourcemanager/peering/armpeering/go.sum
  sdk/resourcemanager/peering/armpeering/go_mod_tidy_hack.go
  sdk/resourcemanager/peering/armpeering/ze_generated_example_legacypeerings_client_test.go
  sdk/resourcemanager/peering/armpeering/ze_generated_example_operations_client_test.go
  sdk/resourcemanager/peering/armpeering/ze_generated_example_peerasns_client_test.go
  sdk/resourcemanager/peering/armpeering/ze_generated_example_peeringlocations_client_test.go
  sdk/resourcemanager/peering/armpeering/ze_generated_example_peeringmanagementclient_client_test.go
  sdk/resourcemanager/peering/armpeering/ze_generated_example_peerings_client_test.go
  sdk/resourcemanager/peering/armpeering/ze_generated_example_peeringservicelocations_client_test.go
  sdk/resourcemanager/peering/armpeering/ze_generated_example_peeringserviceprefixes_client_test.go
  sdk/resourcemanager/peering/armpeering/ze_generated_example_peeringserviceproviders_client_test.go
  sdk/resourcemanager/peering/armpeering/ze_generated_example_peeringservices_client_test.go
  sdk/resourcemanager/peering/armpeering/ze_generated_example_prefixes_client_test.go
  sdk/resourcemanager/peering/armpeering/zz_generated_constants.go
  sdk/resourcemanager/peering/armpeering/zz_generated_legacypeerings_client.go
  sdk/resourcemanager/peering/armpeering/zz_generated_models.go
  sdk/resourcemanager/peering/armpeering/zz_generated_operations_client.go
  sdk/resourcemanager/peering/armpeering/zz_generated_pagers.go
  sdk/resourcemanager/peering/armpeering/zz_generated_peerasns_client.go
  sdk/resourcemanager/peering/armpeering/zz_generated_peeringlocations_client.go
  sdk/resourcemanager/peering/armpeering/zz_generated_peeringmanagementclient_client.go
  sdk/resourcemanager/peering/armpeering/zz_generated_peerings_client.go
  sdk/resourcemanager/peering/armpeering/zz_generated_peeringservicelocations_client.go
  sdk/resourcemanager/peering/armpeering/zz_generated_peeringserviceprefixes_client.go
  sdk/resourcemanager/peering/armpeering/zz_generated_peeringserviceproviders_client.go
  sdk/resourcemanager/peering/armpeering/zz_generated_peeringservices_client.go
  sdk/resourcemanager/peering/armpeering/zz_generated_prefixes_client.go
  sdk/resourcemanager/peering/armpeering/zz_generated_response_types.go
Labels: Mgmt

#16593 [Release] sdk/resourcemanager/netapp/armnetapp/0.1.0
  sdk/resourcemanager/netapp/armnetapp/CHANGELOG.md
  sdk/resourcemanager/netapp/armnetapp/LICENSE.txt
  sdk/resourcemanager/netapp/armnetapp/README.md
  sdk/resourcemanager/netapp/armnetapp/autorest.md
  sdk/resourcemanager/netapp/armnetapp/build.go
  sdk/resourcemanager/netapp/armnetapp/ci.yml
  sdk/resourcemanager/netapp/armnetapp/go.mod
  sdk/resourcemanager/netapp/armnetapp/go.sum
  sdk/resourcemanager/netapp/armnetapp/go_mod_tidy_hack.go
  sdk/resourcemanager/netapp/armnetapp/ze_generated_example_accountbackups_client_test.go
  sdk/resourcemanager/netapp/armnetapp/ze_generated_example_accounts_client_test.go
  sdk/resourcemanager/netapp/armnetapp/ze_generated_example_backuppolicies_client_test.go
  sdk/resourcemanager/netapp/armnetapp/ze_generated_example_backups_client_test.go
  sdk/resourcemanager/netapp/armnetapp/ze_generated_example_netappresource_client_test.go
  sdk/resourcemanager/netapp/armnetapp/ze_generated_example_netappresourcequotalimits_client_test.go
  sdk/resourcemanager/netapp/armnetapp/ze_generated_example_pools_client_test.go
  sdk/resourcemanager/netapp/armnetapp/ze_generated_example_snapshotpolicies_client_test.go
  sdk/resourcemanager/netapp/armnetapp/ze_generated_example_snapshots_client_test.go
  sdk/resourcemanager/netapp/armnetapp/ze_generated_example_vaults_client_test.go
  sdk/resourcemanager/netapp/armnetapp/ze_generated_example_volumegroups_client_test.go
  sdk/resourcemanager/netapp/armnetapp/ze_generated_example_volumes_client_test.go
  sdk/resourcemanager/netapp/armnetapp/zz_generated_accountbackups_client.go
  sdk/resourcemanager/netapp/armnetapp/zz_generated_accounts_client.go
  sdk/resourcemanager/netapp/armnetapp/zz_generated_backuppolicies_client.go
  sdk/resourcemanager/netapp/armnetapp/zz_generated_backups_client.go
  sdk/resourcemanager/netapp/armnetapp/zz_generated_constants.go
  sdk/resourcemanager/netapp/armnetapp/zz_generated_models.go
  sdk/resourcemanager/netapp/armnetapp/zz_generated_netappresource_client.go
  sdk/resourcemanager/netapp/armnetapp/zz_generated_netappresourcequotalimits_client.go
  sdk/resourcemanager/netapp/armnetapp/zz_generated_operations_client.go
  sdk/resourcemanager/netapp/armnetapp/zz_generated_pagers.go
  sdk/resourcemanager/netapp/armnetapp/zz_generated_pollers.go
  sdk/resourcemanager/netapp/armnetapp/zz_generated_pools_client.go
  sdk/resourcemanager/netapp/armnetapp/zz_generated_response_types.go
  sdk/resourcemanager/netapp/armnetapp/zz_generated_snapshotpolicies_client.go
  sdk/resourcemanager/netapp/armnetapp/zz_generated_snapshots_client.go
  sdk/resourcemanager/netapp/armnetapp/zz_generated_time_rfc3339.go
  sdk/resourcemanager/netapp/armnetapp/zz_generated_vaults_client.go
  sdk/resourcemanager/netapp/armnetapp/zz_generated_volumegroups_client.go
  sdk/resourcemanager/netapp/armnetapp/zz_generated_volumes_client.go
Labels: Mgmt

#16636 [Release] sdk/resourcemanager/workloadmonitor/armworkloadmonitor/0.1.0
  sdk/resourcemanager/workloadmonitor/armworkloadmonitor/CHANGELOG.md
  sdk/resourcemanager/workloadmonitor/armworkloadmonitor/LICENSE.txt
  sdk/resourcemanager/workloadmonitor/armworkloadmonitor/README.md
  sdk/resourcemanager/workloadmonitor/armworkloadmonitor/autorest.md
  sdk/resourcemanager/workloadmonitor/armworkloadmonitor/build.go
  sdk/resourcemanager/workloadmonitor/armworkloadmonitor/ci.yml
  sdk/resourcemanager/workloadmonitor/armworkloadmonitor/go.mod
  sdk/resourcemanager/workloadmonitor/armworkloadmonitor/go.sum
  sdk/resourcemanager/workloadmonitor/armworkloadmonitor/go_mod_tidy_hack.go
  sdk/resourcemanager/workloadmonitor/armworkloadmonitor/ze_generated_example_healthmonitors_client_test.go
  sdk/resourcemanager/workloadmonitor/armworkloadmonitor/ze_generated_example_operations_client_test.go
  sdk/resourcemanager/workloadmonitor/armworkloadmonitor/zz_generated_constants.go
  sdk/resourcemanager/workloadmonitor/armworkloadmonitor/zz_generated_healthmonitors_client.go
  sdk/resourcemanager/workloadmonitor/armworkloadmonitor/zz_generated_models.go
  sdk/resourcemanager/workloadmonitor/armworkloadmonitor/zz_generated_operations_client.go
  sdk/resourcemanager/workloadmonitor/armworkloadmonitor/zz_generated_pagers.go
  sdk/resourcemanager/workloadmonitor/armworkloadmonitor/zz_generated_response_types.go
Labels: Mgmt

#16592 [Release] sdk/resourcemanager/mixedreality/armmixedreality/0.1.0
  sdk/resourcemanager/mixedreality/armmixedreality/CHANGELOG.md
  sdk/resourcemanager/mixedreality/armmixedreality/LICENSE.txt
  sdk/resourcemanager/mixedreality/armmixedreality/README.md
  sdk/resourcemanager/mixedreality/armmixedreality/autorest.md
  sdk/resourcemanager/mixedreality/armmixedreality/build.go
  sdk/resourcemanager/mixedreality/armmixedreality/ci.yml
  sdk/resourcemanager/mixedreality/armmixedreality/go.mod
  sdk/resourcemanager/mixedreality/armmixedreality/go.sum
  sdk/resourcemanager/mixedreality/armmixedreality/go_mod_tidy_hack.go
  sdk/resourcemanager/mixedreality/armmixedreality/ze_generated_example_mixedrealityclient_client_test.go
  sdk/resourcemanager/mixedreality/armmixedreality/ze_generated_example_objectanchorsaccounts_client_test.go
  sdk/resourcemanager/mixedreality/armmixedreality/ze_generated_example_operations_client_test.go
  sdk/resourcemanager/mixedreality/armmixedreality/ze_generated_example_remoterenderingaccounts_client_test.go
  sdk/resourcemanager/mixedreality/armmixedreality/ze_generated_example_spatialanchorsaccounts_client_test.go
  sdk/resourcemanager/mixedreality/armmixedreality/zz_generated_constants.go
  sdk/resourcemanager/mixedreality/armmixedreality/zz_generated_mixedrealityclient_client.go
  sdk/resourcemanager/mixedreality/armmixedreality/zz_generated_models.go
  sdk/resourcemanager/mixedreality/armmixedreality/zz_generated_objectanchorsaccounts_client.go
  sdk/resourcemanager/mixedreality/armmixedreality/zz_generated_operations_client.go
  sdk/resourcemanager/mixedreality/armmixedreality/zz_generated_pagers.go
  sdk/resourcemanager/mixedreality/armmixedreality/zz_generated_remoterenderingaccounts_client.go
  sdk/resourcemanager/mixedreality/armmixedreality/zz_generated_response_types.go
  sdk/resourcemanager/mixedreality/armmixedreality/zz_generated_spatialanchorsaccounts_client.go
  sdk/resourcemanager/mixedreality/armmixedreality/zz_generated_time_rfc3339.go
Labels: Mgmt

#16619 [Release] sdk/resourcemanager/hybridcompute/armhybridcompute/0.1.0
  sdk/resourcemanager/hybridcompute/armhybridcompute/CHANGELOG.md
  sdk/resourcemanager/hybridcompute/armhybridcompute/LICENSE.txt
  sdk/resourcemanager/hybridcompute/armhybridcompute/README.md
  sdk/resourcemanager/hybridcompute/armhybridcompute/autorest.md
  sdk/resourcemanager/hybridcompute/armhybridcompute/build.go
  sdk/resourcemanager/hybridcompute/armhybridcompute/ci.yml
  sdk/resourcemanager/hybridcompute/armhybridcompute/go.mod
  sdk/resourcemanager/hybridcompute/armhybridcompute/go.sum
  sdk/resourcemanager/hybridcompute/armhybridcompute/go_mod_tidy_hack.go
  sdk/resourcemanager/hybridcompute/armhybridcompute/ze_generated_example_hybridcomputemanagementclient_client_test.go
  sdk/resourcemanager/hybridcompute/armhybridcompute/ze_generated_example_machineextensions_client_test.go
  sdk/resourcemanager/hybridcompute/armhybridcompute/ze_generated_example_machines_client_test.go
  sdk/resourcemanager/hybridcompute/armhybridcompute/ze_generated_example_privateendpointconnections_client_test.go
  sdk/resourcemanager/hybridcompute/armhybridcompute/ze_generated_example_privatelinkresources_client_test.go
  sdk/resourcemanager/hybridcompute/armhybridcompute/ze_generated_example_privatelinkscopes_client_test.go
  sdk/resourcemanager/hybridcompute/armhybridcompute/zz_generated_constants.go
  sdk/resourcemanager/hybridcompute/armhybridcompute/zz_generated_hybridcomputemanagementclient_client.go
  sdk/resourcemanager/hybridcompute/armhybridcompute/zz_generated_machineextensions_client.go
  sdk/resourcemanager/hybridcompute/armhybridcompute/zz_generated_machines_client.go
  sdk/resourcemanager/hybridcompute/armhybridcompute/zz_generated_models.go
  sdk/resourcemanager/hybridcompute/armhybridcompute/zz_generated_operations_client.go
  sdk/resourcemanager/hybridcompute/armhybridcompute/zz_generated_pagers.go
  sdk/resourcemanager/hybridcompute/armhybridcompute/zz_generated_pollers.go
  sdk/resourcemanager/hybridcompute/armhybridcompute/zz_generated_privateendpointconnections_client.go
  sdk/resourcemanager/hybridcompute/armhybridcompute/zz_generated_privatelinkresources_client.go
  sdk/resourcemanager/hybridcompute/armhybridcompute/zz_generated_privatelinkscopes_client.go
  sdk/resourcemanager/hybridcompute/armhybridcompute/zz_generated_response_types.go
  sdk/resourcemanager/hybridcompute/armhybridcompute/zz_generated_time_rfc3339.go
Labels: Mgmt

#16623 [Release] sdk/resourcemanager/storagesync/armstoragesync/0.1.0
  sdk/resourcemanager/storagesync/armstoragesync/CHANGELOG.md
  sdk/resourcemanager/storagesync/armstoragesync/LICENSE.txt
  sdk/resourcemanager/storagesync/armstoragesync/README.md
  sdk/resourcemanager/storagesync/armstoragesync/autorest.md
  sdk/resourcemanager/storagesync/armstoragesync/build.go
  sdk/resourcemanager/storagesync/armstoragesync/ci.yml
  sdk/resourcemanager/storagesync/armstoragesync/go.mod
  sdk/resourcemanager/storagesync/armstoragesync/go.sum
  sdk/resourcemanager/storagesync/armstoragesync/go_mod_tidy_hack.go
  sdk/resourcemanager/storagesync/armstoragesync/ze_generated_example_cloudendpoints_client_test.go
  sdk/resourcemanager/storagesync/armstoragesync/ze_generated_example_microsoftstoragesync_client_test.go
  sdk/resourcemanager/storagesync/armstoragesync/ze_generated_example_operations_client_test.go
  sdk/resourcemanager/storagesync/armstoragesync/ze_generated_example_operationstatus_client_test.go
  sdk/resourcemanager/storagesync/armstoragesync/ze_generated_example_privateendpointconnections_client_test.go
  sdk/resourcemanager/storagesync/armstoragesync/ze_generated_example_privatelinkresources_client_test.go
  sdk/resourcemanager/storagesync/armstoragesync/ze_generated_example_registeredservers_client_test.go
  sdk/resourcemanager/storagesync/armstoragesync/ze_generated_example_serverendpoints_client_test.go
  sdk/resourcemanager/storagesync/armstoragesync/ze_generated_example_storagesyncservices_client_test.go
  sdk/resourcemanager/storagesync/armstoragesync/ze_generated_example_syncgroups_client_test.go
  sdk/resourcemanager/storagesync/armstoragesync/ze_generated_example_workflows_client_test.go
  sdk/resourcemanager/storagesync/armstoragesync/zz_generated_cloudendpoints_client.go
  sdk/resourcemanager/storagesync/armstoragesync/zz_generated_constants.go
  sdk/resourcemanager/storagesync/armstoragesync/zz_generated_microsoftstoragesync_client.go
  sdk/resourcemanager/storagesync/armstoragesync/zz_generated_models.go
  sdk/resourcemanager/storagesync/armstoragesync/zz_generated_operations_client.go
  sdk/resourcemanager/storagesync/armstoragesync/zz_generated_operationstatus_client.go
  sdk/resourcemanager/storagesync/armstoragesync/zz_generated_pagers.go
  sdk/resourcemanager/storagesync/armstoragesync/zz_generated_pollers.go
  sdk/resourcemanager/storagesync/armstoragesync/zz_generated_privateendpointconnections_client.go
  sdk/resourcemanager/storagesync/armstoragesync/zz_generated_privatelinkresources_client.go
  sdk/resourcemanager/storagesync/armstoragesync/zz_generated_registeredservers_client.go
  sdk/resourcemanager/storagesync/armstoragesync/zz_generated_response_types.go
  sdk/resourcemanager/storagesync/armstoragesync/zz_generated_serverendpoints_client.go
  sdk/resourcemanager/storagesync/armstoragesync/zz_generated_storagesyncservices_client.go
  sdk/resourcemanager/storagesync/armstoragesync/zz_generated_syncgroups_client.go
  sdk/resourcemanager/storagesync/armstoragesync/zz_generated_time_rfc3339.go
  sdk/resourcemanager/storagesync/armstoragesync/zz_generated_workflows_client.go
Labels: Mgmt

#16622 [Release] sdk/resourcemanager/storagepool/armstoragepool/0.1.0
  sdk/resourcemanager/storagepool/armstoragepool/CHANGELOG.md
  sdk/resourcemanager/storagepool/armstoragepool/LICENSE.txt
  sdk/resourcemanager/storagepool/armstoragepool/README.md
  sdk/resourcemanager/storagepool/armstoragepool/autorest.md
  sdk/resourcemanager/storagepool/armstoragepool/build.go
  sdk/resourcemanager/storagepool/armstoragepool/ci.yml
  sdk/resourcemanager/storagepool/armstoragepool/go.mod
  sdk/resourcemanager/storagepool/armstoragepool/go.sum
  sdk/resourcemanager/storagepool/armstoragepool/go_mod_tidy_hack.go
  sdk/resourcemanager/storagepool/armstoragepool/ze_generated_example_diskpools_client_test.go
  sdk/resourcemanager/storagepool/armstoragepool/ze_generated_example_diskpoolzones_client_test.go
  sdk/resourcemanager/storagepool/armstoragepool/ze_generated_example_iscsitargets_client_test.go
  sdk/resourcemanager/storagepool/armstoragepool/ze_generated_example_operations_client_test.go
  sdk/resourcemanager/storagepool/armstoragepool/ze_generated_example_resourceskus_client_test.go
  sdk/resourcemanager/storagepool/armstoragepool/zz_generated_constants.go
  sdk/resourcemanager/storagepool/armstoragepool/zz_generated_diskpools_client.go
  sdk/resourcemanager/storagepool/armstoragepool/zz_generated_diskpoolzones_client.go
  sdk/resourcemanager/storagepool/armstoragepool/zz_generated_iscsitargets_client.go
  sdk/resourcemanager/storagepool/armstoragepool/zz_generated_models.go
  sdk/resourcemanager/storagepool/armstoragepool/zz_generated_operations_client.go
  sdk/resourcemanager/storagepool/armstoragepool/zz_generated_pagers.go
  sdk/resourcemanager/storagepool/armstoragepool/zz_generated_pollers.go
  sdk/resourcemanager/storagepool/armstoragepool/zz_generated_resourceskus_client.go
  sdk/resourcemanager/storagepool/armstoragepool/zz_generated_response_types.go
  sdk/resourcemanager/storagepool/armstoragepool/zz_generated_time_rfc3339.go
Labels: Mgmt

#16639 Handle error response XML with whitespace
  sdk/storage/azblob/zc_storage_error.go
  sdk/storage/azblob/zc_storage_error_test.go
Labels: Storage

#16067 [chunkwriting] Return original buffer to the pool
  sdk/storage/azblob/chunkwriting.go
Labels: Storage, customer-reported

#15958 UploadStreamToBlockBlob: only require body be io.Reader
  sdk/storage/azblob/chunkwriting.go
  sdk/storage/azblob/highlevel.go
Labels: Storage, customer-reported

#16660 Sync eng/common directory with azure-sdk-tools for PR 2447
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: EngSys, Central-EngSys

#16688 Add trademark section to root readme
  README.md
Labels: auto-merge

#16595 [Release] sdk/resourcemanager/postgresqlhsc/armpostgresqlhsc/0.1.0
  sdk/resourcemanager/postgresqlhsc/armpostgresqlhsc/CHANGELOG.md
  sdk/resourcemanager/postgresqlhsc/armpostgresqlhsc/LICENSE.txt
  sdk/resourcemanager/postgresqlhsc/armpostgresqlhsc/README.md
  sdk/resourcemanager/postgresqlhsc/armpostgresqlhsc/autorest.md
  sdk/resourcemanager/postgresqlhsc/armpostgresqlhsc/build.go
  sdk/resourcemanager/postgresqlhsc/armpostgresqlhsc/ci.yml
  sdk/resourcemanager/postgresqlhsc/armpostgresqlhsc/go.mod
  sdk/resourcemanager/postgresqlhsc/armpostgresqlhsc/go.sum
  sdk/resourcemanager/postgresqlhsc/armpostgresqlhsc/go_mod_tidy_hack.go
  sdk/resourcemanager/postgresqlhsc/armpostgresqlhsc/ze_generated_example_configurations_client_test.go
  sdk/resourcemanager/postgresqlhsc/armpostgresqlhsc/ze_generated_example_firewallrules_client_test.go
  sdk/resourcemanager/postgresqlhsc/armpostgresqlhsc/ze_generated_example_operations_client_test.go
  sdk/resourcemanager/postgresqlhsc/armpostgresqlhsc/ze_generated_example_roles_client_test.go
  sdk/resourcemanager/postgresqlhsc/armpostgresqlhsc/ze_generated_example_servergroups_client_test.go
  sdk/resourcemanager/postgresqlhsc/armpostgresqlhsc/ze_generated_example_servers_client_test.go
  sdk/resourcemanager/postgresqlhsc/armpostgresqlhsc/zz_generated_configurations_client.go
  sdk/resourcemanager/postgresqlhsc/armpostgresqlhsc/zz_generated_constants.go
  sdk/resourcemanager/postgresqlhsc/armpostgresqlhsc/zz_generated_firewallrules_client.go
  sdk/resourcemanager/postgresqlhsc/armpostgresqlhsc/zz_generated_models.go
  sdk/resourcemanager/postgresqlhsc/armpostgresqlhsc/zz_generated_operations_client.go
  sdk/resourcemanager/postgresqlhsc/armpostgresqlhsc/zz_generated_pagers.go
  sdk/resourcemanager/postgresqlhsc/armpostgresqlhsc/zz_generated_pollers.go
  sdk/resourcemanager/postgresqlhsc/armpostgresqlhsc/zz_generated_response_types.go
  sdk/resourcemanager/postgresqlhsc/armpostgresqlhsc/zz_generated_roles_client.go
  sdk/resourcemanager/postgresqlhsc/armpostgresqlhsc/zz_generated_servergroups_client.go
  sdk/resourcemanager/postgresqlhsc/armpostgresqlhsc/zz_generated_servers_client.go
  sdk/resourcemanager/postgresqlhsc/armpostgresqlhsc/zz_generated_time_rfc3339.go
Labels: Mgmt

#16596 [Release] sdk/resourcemanager/powerbidedicated/armpowerbidedicated/0.1.0
  sdk/resourcemanager/powerbidedicated/armpowerbidedicated/CHANGELOG.md
  sdk/resourcemanager/powerbidedicated/armpowerbidedicated/LICENSE.txt
  sdk/resourcemanager/powerbidedicated/armpowerbidedicated/README.md
  sdk/resourcemanager/powerbidedicated/armpowerbidedicated/autorest.md
  sdk/resourcemanager/powerbidedicated/armpowerbidedicated/build.go
  sdk/resourcemanager/powerbidedicated/armpowerbidedicated/ci.yml
  sdk/resourcemanager/powerbidedicated/armpowerbidedicated/go.mod
  sdk/resourcemanager/powerbidedicated/armpowerbidedicated/go.sum
  sdk/resourcemanager/powerbidedicated/armpowerbidedicated/go_mod_tidy_hack.go
  sdk/resourcemanager/powerbidedicated/armpowerbidedicated/ze_generated_example_autoscalevcores_client_test.go
  sdk/resourcemanager/powerbidedicated/armpowerbidedicated/ze_generated_example_capacities_client_test.go
  sdk/resourcemanager/powerbidedicated/armpowerbidedicated/zz_generated_autoscalevcores_client.go
  sdk/resourcemanager/powerbidedicated/armpowerbidedicated/zz_generated_capacities_client.go
  sdk/resourcemanager/powerbidedicated/armpowerbidedicated/zz_generated_constants.go
  sdk/resourcemanager/powerbidedicated/armpowerbidedicated/zz_generated_models.go
  sdk/resourcemanager/powerbidedicated/armpowerbidedicated/zz_generated_operations_client.go
  sdk/resourcemanager/powerbidedicated/armpowerbidedicated/zz_generated_pagers.go
  sdk/resourcemanager/powerbidedicated/armpowerbidedicated/zz_generated_pollers.go
  sdk/resourcemanager/powerbidedicated/armpowerbidedicated/zz_generated_response_types.go
  sdk/resourcemanager/powerbidedicated/armpowerbidedicated/zz_generated_time_rfc3339.go
Labels: Mgmt

#16597 [Release] sdk/resourcemanager/powerbiembedded/armpowerbiembedded/0.1.0
  sdk/resourcemanager/powerbiembedded/armpowerbiembedded/CHANGELOG.md
  sdk/resourcemanager/powerbiembedded/armpowerbiembedded/LICENSE.txt
  sdk/resourcemanager/powerbiembedded/armpowerbiembedded/README.md
  sdk/resourcemanager/powerbiembedded/armpowerbiembedded/autorest.md
  sdk/resourcemanager/powerbiembedded/armpowerbiembedded/build.go
  sdk/resourcemanager/powerbiembedded/armpowerbiembedded/ci.yml
  sdk/resourcemanager/powerbiembedded/armpowerbiembedded/go.mod
  sdk/resourcemanager/powerbiembedded/armpowerbiembedded/go.sum
  sdk/resourcemanager/powerbiembedded/armpowerbiembedded/go_mod_tidy_hack.go
  sdk/resourcemanager/powerbiembedded/armpowerbiembedded/zz_generated_constants.go
  sdk/resourcemanager/powerbiembedded/armpowerbiembedded/zz_generated_models.go
  sdk/resourcemanager/powerbiembedded/armpowerbiembedded/zz_generated_pollers.go
  sdk/resourcemanager/powerbiembedded/armpowerbiembedded/zz_generated_powerbiembeddedmanagementclient_client.go
  sdk/resourcemanager/powerbiembedded/armpowerbiembedded/zz_generated_response_types.go
  sdk/resourcemanager/powerbiembedded/armpowerbiembedded/zz_generated_workspacecollections_client.go
  sdk/resourcemanager/powerbiembedded/armpowerbiembedded/zz_generated_workspaces_client.go
Labels: Mgmt

#16598 [Release] sdk/resourcemanager/powerbiprivatelinks/armpowerbiprivatelinks/0.1.0
  sdk/resourcemanager/powerbiprivatelinks/armpowerbiprivatelinks/CHANGELOG.md
  sdk/resourcemanager/powerbiprivatelinks/armpowerbiprivatelinks/LICENSE.txt
  sdk/resourcemanager/powerbiprivatelinks/armpowerbiprivatelinks/README.md
  sdk/resourcemanager/powerbiprivatelinks/armpowerbiprivatelinks/autorest.md
  sdk/resourcemanager/powerbiprivatelinks/armpowerbiprivatelinks/build.go
  sdk/resourcemanager/powerbiprivatelinks/armpowerbiprivatelinks/ci.yml
  sdk/resourcemanager/powerbiprivatelinks/armpowerbiprivatelinks/go.mod
  sdk/resourcemanager/powerbiprivatelinks/armpowerbiprivatelinks/go.sum
  sdk/resourcemanager/powerbiprivatelinks/armpowerbiprivatelinks/go_mod_tidy_hack.go
  sdk/resourcemanager/powerbiprivatelinks/armpowerbiprivatelinks/ze_generated_example_operations_client_test.go
  sdk/resourcemanager/powerbiprivatelinks/armpowerbiprivatelinks/ze_generated_example_powerbiresources_client_test.go
  sdk/resourcemanager/powerbiprivatelinks/armpowerbiprivatelinks/ze_generated_example_privateendpointconnections_client_test.go
  sdk/resourcemanager/powerbiprivatelinks/armpowerbiprivatelinks/ze_generated_example_privatelinkresources_client_test.go
  sdk/resourcemanager/powerbiprivatelinks/armpowerbiprivatelinks/ze_generated_example_privatelinkserviceresourceoperationresults_client_test.go
  sdk/resourcemanager/powerbiprivatelinks/armpowerbiprivatelinks/ze_generated_example_privatelinkservices_client_test.go
  sdk/resourcemanager/powerbiprivatelinks/armpowerbiprivatelinks/ze_generated_example_privatelinkservicesforpowerbi_client_test.go
  sdk/resourcemanager/powerbiprivatelinks/armpowerbiprivatelinks/zz_generated_constants.go
  sdk/resourcemanager/powerbiprivatelinks/armpowerbiprivatelinks/zz_generated_models.go
  sdk/resourcemanager/powerbiprivatelinks/armpowerbiprivatelinks/zz_generated_operations_client.go
  sdk/resourcemanager/powerbiprivatelinks/armpowerbiprivatelinks/zz_generated_pagers.go
  sdk/resourcemanager/powerbiprivatelinks/armpowerbiprivatelinks/zz_generated_pollers.go
  sdk/resourcemanager/powerbiprivatelinks/armpowerbiprivatelinks/zz_generated_powerbiresources_client.go
  sdk/resourcemanager/powerbiprivatelinks/armpowerbiprivatelinks/zz_generated_privateendpointconnections_client.go
  sdk/resourcemanager/powerbiprivatelinks/armpowerbiprivatelinks/zz_generated_privatelinkresources_client.go
  sdk/resourcemanager/powerbiprivatelinks/armpowerbiprivatelinks/zz_generated_privatelinkserviceresourceoperationresults_client.go
  sdk/resourcemanager/powerbiprivatelinks/armpowerbiprivatelinks/zz_generated_privatelinkservices_client.go
  sdk/resourcemanager/powerbiprivatelinks/armpowerbiprivatelinks/zz_generated_privatelinkservicesforpowerbi_client.go
  sdk/resourcemanager/powerbiprivatelinks/armpowerbiprivatelinks/zz_generated_response_types.go
  sdk/resourcemanager/powerbiprivatelinks/armpowerbiprivatelinks/zz_generated_time_rfc3339.go
Labels: Mgmt

#16599 [Release] sdk/resourcemanager/providerhub/armproviderhub/0.1.0
  sdk/resourcemanager/providerhub/armproviderhub/CHANGELOG.md
  sdk/resourcemanager/providerhub/armproviderhub/LICENSE.txt
  sdk/resourcemanager/providerhub/armproviderhub/README.md
  sdk/resourcemanager/providerhub/armproviderhub/autorest.md
  sdk/resourcemanager/providerhub/armproviderhub/build.go
  sdk/resourcemanager/providerhub/armproviderhub/ci.yml
  sdk/resourcemanager/providerhub/armproviderhub/go.mod
  sdk/resourcemanager/providerhub/armproviderhub/go.sum
  sdk/resourcemanager/providerhub/armproviderhub/go_mod_tidy_hack.go
  sdk/resourcemanager/providerhub/armproviderhub/ze_generated_example_customrollouts_client_test.go
  sdk/resourcemanager/providerhub/armproviderhub/ze_generated_example_defaultrollouts_client_test.go
  sdk/resourcemanager/providerhub/armproviderhub/ze_generated_example_notificationregistrations_client_test.go
  sdk/resourcemanager/providerhub/armproviderhub/ze_generated_example_operations_client_test.go
  sdk/resourcemanager/providerhub/armproviderhub/ze_generated_example_providerhub_client_test.go
  sdk/resourcemanager/providerhub/armproviderhub/ze_generated_example_providerregistrations_client_test.go
  sdk/resourcemanager/providerhub/armproviderhub/ze_generated_example_resourcetyperegistrations_client_test.go
  sdk/resourcemanager/providerhub/armproviderhub/ze_generated_example_skus_client_test.go
  sdk/resourcemanager/providerhub/armproviderhub/zz_generated_constants.go
  sdk/resourcemanager/providerhub/armproviderhub/zz_generated_customrollouts_client.go
  sdk/resourcemanager/providerhub/armproviderhub/zz_generated_defaultrollouts_client.go
  sdk/resourcemanager/providerhub/armproviderhub/zz_generated_models.go
  sdk/resourcemanager/providerhub/armproviderhub/zz_generated_notificationregistrations_client.go
  sdk/resourcemanager/providerhub/armproviderhub/zz_generated_operations_client.go
  sdk/resourcemanager/providerhub/armproviderhub/zz_generated_pagers.go
  sdk/resourcemanager/providerhub/armproviderhub/zz_generated_pollers.go
  sdk/resourcemanager/providerhub/armproviderhub/zz_generated_providerhub_client.go
  sdk/resourcemanager/providerhub/armproviderhub/zz_generated_providerregistrations_client.go
  sdk/resourcemanager/providerhub/armproviderhub/zz_generated_resourcetyperegistrations_client.go
  sdk/resourcemanager/providerhub/armproviderhub/zz_generated_response_types.go
  sdk/resourcemanager/providerhub/armproviderhub/zz_generated_skus_client.go
  sdk/resourcemanager/providerhub/armproviderhub/zz_generated_time_rfc3339.go
Labels: Mgmt

#16621 [Release] sdk/resourcemanager/storageimportexport/armstorageimportexport/0.1.0
  sdk/resourcemanager/storageimportexport/armstorageimportexport/CHANGELOG.md
  sdk/resourcemanager/storageimportexport/armstorageimportexport/LICENSE.txt
  sdk/resourcemanager/storageimportexport/armstorageimportexport/README.md
  sdk/resourcemanager/storageimportexport/armstorageimportexport/autorest.md
  sdk/resourcemanager/storageimportexport/armstorageimportexport/build.go
  sdk/resourcemanager/storageimportexport/armstorageimportexport/ci.yml
  sdk/resourcemanager/storageimportexport/armstorageimportexport/go.mod
  sdk/resourcemanager/storageimportexport/armstorageimportexport/go.sum
  sdk/resourcemanager/storageimportexport/armstorageimportexport/go_mod_tidy_hack.go
  sdk/resourcemanager/storageimportexport/armstorageimportexport/ze_generated_example_bitlockerkeys_client_test.go
  sdk/resourcemanager/storageimportexport/armstorageimportexport/ze_generated_example_jobs_client_test.go
  sdk/resourcemanager/storageimportexport/armstorageimportexport/ze_generated_example_locations_client_test.go
  sdk/resourcemanager/storageimportexport/armstorageimportexport/ze_generated_example_operations_client_test.go
  sdk/resourcemanager/storageimportexport/armstorageimportexport/zz_generated_bitlockerkeys_client.go
  sdk/resourcemanager/storageimportexport/armstorageimportexport/zz_generated_constants.go
  sdk/resourcemanager/storageimportexport/armstorageimportexport/zz_generated_jobs_client.go
  sdk/resourcemanager/storageimportexport/armstorageimportexport/zz_generated_locations_client.go
  sdk/resourcemanager/storageimportexport/armstorageimportexport/zz_generated_models.go
  sdk/resourcemanager/storageimportexport/armstorageimportexport/zz_generated_operations_client.go
  sdk/resourcemanager/storageimportexport/armstorageimportexport/zz_generated_pagers.go
  sdk/resourcemanager/storageimportexport/armstorageimportexport/zz_generated_response_types.go
  sdk/resourcemanager/storageimportexport/armstorageimportexport/zz_generated_time_rfc3339.go
Labels: Mgmt

#16627 [Release] sdk/resourcemanager/storagecache/armstoragecache/0.1.0
  sdk/resourcemanager/storagecache/armstoragecache/CHANGELOG.md
  sdk/resourcemanager/storagecache/armstoragecache/LICENSE.txt
  sdk/resourcemanager/storagecache/armstoragecache/README.md
  sdk/resourcemanager/storagecache/armstoragecache/autorest.md
  sdk/resourcemanager/storagecache/armstoragecache/build.go
  sdk/resourcemanager/storagecache/armstoragecache/ci.yml
  sdk/resourcemanager/storagecache/armstoragecache/go.mod
  sdk/resourcemanager/storagecache/armstoragecache/go.sum
  sdk/resourcemanager/storagecache/armstoragecache/go_mod_tidy_hack.go
  sdk/resourcemanager/storagecache/armstoragecache/ze_generated_example_ascoperations_client_test.go
  sdk/resourcemanager/storagecache/armstoragecache/ze_generated_example_caches_client_test.go
  sdk/resourcemanager/storagecache/armstoragecache/ze_generated_example_operations_client_test.go
  sdk/resourcemanager/storagecache/armstoragecache/ze_generated_example_skus_client_test.go
  sdk/resourcemanager/storagecache/armstoragecache/ze_generated_example_storagetarget_client_test.go
  sdk/resourcemanager/storagecache/armstoragecache/ze_generated_example_storagetargets_client_test.go
  sdk/resourcemanager/storagecache/armstoragecache/ze_generated_example_usagemodels_client_test.go
  sdk/resourcemanager/storagecache/armstoragecache/zz_generated_ascoperations_client.go
  sdk/resourcemanager/storagecache/armstoragecache/zz_generated_caches_client.go
  sdk/resourcemanager/storagecache/armstoragecache/zz_generated_constants.go
  sdk/resourcemanager/storagecache/armstoragecache/zz_generated_models.go
  sdk/resourcemanager/storagecache/armstoragecache/zz_generated_operations_client.go
  sdk/resourcemanager/storagecache/armstoragecache/zz_generated_pagers.go
  sdk/resourcemanager/storagecache/armstoragecache/zz_generated_pollers.go
  sdk/resourcemanager/storagecache/armstoragecache/zz_generated_response_types.go
  sdk/resourcemanager/storagecache/armstoragecache/zz_generated_skus_client.go
  sdk/resourcemanager/storagecache/armstoragecache/zz_generated_storagetarget_client.go
  sdk/resourcemanager/storagecache/armstoragecache/zz_generated_storagetargets_client.go
  sdk/resourcemanager/storagecache/armstoragecache/zz_generated_time_rfc3339.go
  sdk/resourcemanager/storagecache/armstoragecache/zz_generated_usagemodels_client.go
Labels: Mgmt

#16628 [Release] sdk/resourcemanager/trafficmanager/armtrafficmanager/0.1.0
  sdk/resourcemanager/trafficmanager/armtrafficmanager/CHANGELOG.md
  sdk/resourcemanager/trafficmanager/armtrafficmanager/LICENSE.txt
  sdk/resourcemanager/trafficmanager/armtrafficmanager/README.md
  sdk/resourcemanager/trafficmanager/armtrafficmanager/autorest.md
  sdk/resourcemanager/trafficmanager/armtrafficmanager/build.go
  sdk/resourcemanager/trafficmanager/armtrafficmanager/ci.yml
  sdk/resourcemanager/trafficmanager/armtrafficmanager/go.mod
  sdk/resourcemanager/trafficmanager/armtrafficmanager/go.sum
  sdk/resourcemanager/trafficmanager/armtrafficmanager/go_mod_tidy_hack.go
  sdk/resourcemanager/trafficmanager/armtrafficmanager/ze_generated_example_endpoints_client_test.go
  sdk/resourcemanager/trafficmanager/armtrafficmanager/ze_generated_example_geographichierarchies_client_test.go
  sdk/resourcemanager/trafficmanager/armtrafficmanager/ze_generated_example_heatmap_client_test.go
  sdk/resourcemanager/trafficmanager/armtrafficmanager/ze_generated_example_profiles_client_test.go
  sdk/resourcemanager/trafficmanager/armtrafficmanager/ze_generated_example_trafficmanagerusermetricskeys_client_test.go
  sdk/resourcemanager/trafficmanager/armtrafficmanager/zz_generated_constants.go
  sdk/resourcemanager/trafficmanager/armtrafficmanager/zz_generated_endpoints_client.go
  sdk/resourcemanager/trafficmanager/armtrafficmanager/zz_generated_geographichierarchies_client.go
  sdk/resourcemanager/trafficmanager/armtrafficmanager/zz_generated_heatmap_client.go
  sdk/resourcemanager/trafficmanager/armtrafficmanager/zz_generated_models.go
  sdk/resourcemanager/trafficmanager/armtrafficmanager/zz_generated_profiles_client.go
  sdk/resourcemanager/trafficmanager/armtrafficmanager/zz_generated_response_types.go
  sdk/resourcemanager/trafficmanager/armtrafficmanager/zz_generated_time_rfc3339.go
  sdk/resourcemanager/trafficmanager/armtrafficmanager/zz_generated_trafficmanagerusermetricskeys_client.go
Labels: Mgmt

#16625 [Release] sdk/resourcemanager/support/armsupport/0.1.0
  sdk/resourcemanager/support/armsupport/CHANGELOG.md
  sdk/resourcemanager/support/armsupport/LICENSE.txt
  sdk/resourcemanager/support/armsupport/README.md
  sdk/resourcemanager/support/armsupport/autorest.md
  sdk/resourcemanager/support/armsupport/build.go
  sdk/resourcemanager/support/armsupport/ci.yml
  sdk/resourcemanager/support/armsupport/go.mod
  sdk/resourcemanager/support/armsupport/go.sum
  sdk/resourcemanager/support/armsupport/go_mod_tidy_hack.go
  sdk/resourcemanager/support/armsupport/ze_generated_example_communications_client_test.go
  sdk/resourcemanager/support/armsupport/ze_generated_example_operations_client_test.go
  sdk/resourcemanager/support/armsupport/ze_generated_example_problemclassifications_client_test.go
  sdk/resourcemanager/support/armsupport/ze_generated_example_services_client_test.go
  sdk/resourcemanager/support/armsupport/ze_generated_example_supporttickets_client_test.go
  sdk/resourcemanager/support/armsupport/zz_generated_communications_client.go
  sdk/resourcemanager/support/armsupport/zz_generated_constants.go
  sdk/resourcemanager/support/armsupport/zz_generated_models.go
  sdk/resourcemanager/support/armsupport/zz_generated_operations_client.go
  sdk/resourcemanager/support/armsupport/zz_generated_pagers.go
  sdk/resourcemanager/support/armsupport/zz_generated_pollers.go
  sdk/resourcemanager/support/armsupport/zz_generated_problemclassifications_client.go
  sdk/resourcemanager/support/armsupport/zz_generated_response_types.go
  sdk/resourcemanager/support/armsupport/zz_generated_services_client.go
  sdk/resourcemanager/support/armsupport/zz_generated_supporttickets_client.go
  sdk/resourcemanager/support/armsupport/zz_generated_time_rfc3339.go
Labels: Mgmt

#16682 [Release] sdk/resourcemanager/logz/armlogz/0.1.0
  sdk/resourcemanager/logz/armlogz/CHANGELOG.md
  sdk/resourcemanager/logz/armlogz/LICENSE.txt
  sdk/resourcemanager/logz/armlogz/README.md
  sdk/resourcemanager/logz/armlogz/autorest.md
  sdk/resourcemanager/logz/armlogz/build.go
  sdk/resourcemanager/logz/armlogz/ci.yml
  sdk/resourcemanager/logz/armlogz/go.mod
  sdk/resourcemanager/logz/armlogz/go.sum
  sdk/resourcemanager/logz/armlogz/go_mod_tidy_hack.go
  sdk/resourcemanager/logz/armlogz/ze_generated_example_monitor_client_test.go
  sdk/resourcemanager/logz/armlogz/ze_generated_example_monitors_client_test.go
  sdk/resourcemanager/logz/armlogz/ze_generated_example_operations_client_test.go
  sdk/resourcemanager/logz/armlogz/ze_generated_example_singlesignon_client_test.go
  sdk/resourcemanager/logz/armlogz/ze_generated_example_subaccount_client_test.go
  sdk/resourcemanager/logz/armlogz/ze_generated_example_subaccounttagrules_client_test.go
  sdk/resourcemanager/logz/armlogz/ze_generated_example_tagrules_client_test.go
  sdk/resourcemanager/logz/armlogz/zz_generated_constants.go
  sdk/resourcemanager/logz/armlogz/zz_generated_models.go
  sdk/resourcemanager/logz/armlogz/zz_generated_monitor_client.go
  sdk/resourcemanager/logz/armlogz/zz_generated_monitors_client.go
  sdk/resourcemanager/logz/armlogz/zz_generated_operations_client.go
  sdk/resourcemanager/logz/armlogz/zz_generated_pagers.go
  sdk/resourcemanager/logz/armlogz/zz_generated_pollers.go
  sdk/resourcemanager/logz/armlogz/zz_generated_response_types.go
  sdk/resourcemanager/logz/armlogz/zz_generated_singlesignon_client.go
  sdk/resourcemanager/logz/armlogz/zz_generated_subaccount_client.go
  sdk/resourcemanager/logz/armlogz/zz_generated_subaccounttagrules_client.go
  sdk/resourcemanager/logz/armlogz/zz_generated_tagrules_client.go
  sdk/resourcemanager/logz/armlogz/zz_generated_time_rfc3339.go
Labels: Mgmt

#16683 [Release] sdk/resourcemanager/datadog/armdatadog/0.1.0
  sdk/resourcemanager/datadog/armdatadog/CHANGELOG.md
  sdk/resourcemanager/datadog/armdatadog/LICENSE.txt
  sdk/resourcemanager/datadog/armdatadog/README.md
  sdk/resourcemanager/datadog/armdatadog/autorest.md
  sdk/resourcemanager/datadog/armdatadog/build.go
  sdk/resourcemanager/datadog/armdatadog/ci.yml
  sdk/resourcemanager/datadog/armdatadog/go.mod
  sdk/resourcemanager/datadog/armdatadog/go.sum
  sdk/resourcemanager/datadog/armdatadog/go_mod_tidy_hack.go
  sdk/resourcemanager/datadog/armdatadog/ze_generated_example_marketplaceagreements_client_test.go
  sdk/resourcemanager/datadog/armdatadog/ze_generated_example_monitors_client_test.go
  sdk/resourcemanager/datadog/armdatadog/ze_generated_example_operations_client_test.go
  sdk/resourcemanager/datadog/armdatadog/ze_generated_example_singlesignonconfigurations_client_test.go
  sdk/resourcemanager/datadog/armdatadog/ze_generated_example_tagrules_client_test.go
  sdk/resourcemanager/datadog/armdatadog/zz_generated_constants.go
  sdk/resourcemanager/datadog/armdatadog/zz_generated_marketplaceagreements_client.go
  sdk/resourcemanager/datadog/armdatadog/zz_generated_models.go
  sdk/resourcemanager/datadog/armdatadog/zz_generated_monitors_client.go
  sdk/resourcemanager/datadog/armdatadog/zz_generated_operations_client.go
  sdk/resourcemanager/datadog/armdatadog/zz_generated_pagers.go
  sdk/resourcemanager/datadog/armdatadog/zz_generated_pollers.go
  sdk/resourcemanager/datadog/armdatadog/zz_generated_response_types.go
  sdk/resourcemanager/datadog/armdatadog/zz_generated_singlesignonconfigurations_client.go
  sdk/resourcemanager/datadog/armdatadog/zz_generated_tagrules_client.go
  sdk/resourcemanager/datadog/armdatadog/zz_generated_time_rfc3339.go
Labels: Mgmt

#16684 [Release] sdk/resourcemanager/customproviders/armcustomproviders/0.1.0
  sdk/resourcemanager/customproviders/armcustomproviders/CHANGELOG.md
  sdk/resourcemanager/customproviders/armcustomproviders/LICENSE.txt
  sdk/resourcemanager/customproviders/armcustomproviders/README.md
  sdk/resourcemanager/customproviders/armcustomproviders/autorest.md
  sdk/resourcemanager/customproviders/armcustomproviders/build.go
  sdk/resourcemanager/customproviders/armcustomproviders/ci.yml
  sdk/resourcemanager/customproviders/armcustomproviders/go.mod
  sdk/resourcemanager/customproviders/armcustomproviders/go.sum
  sdk/resourcemanager/customproviders/armcustomproviders/go_mod_tidy_hack.go
  sdk/resourcemanager/customproviders/armcustomproviders/ze_generated_example_associations_client_test.go
  sdk/resourcemanager/customproviders/armcustomproviders/ze_generated_example_customresourceprovider_client_test.go
  sdk/resourcemanager/customproviders/armcustomproviders/ze_generated_example_operations_client_test.go
  sdk/resourcemanager/customproviders/armcustomproviders/zz_generated_associations_client.go
  sdk/resourcemanager/customproviders/armcustomproviders/zz_generated_constants.go
  sdk/resourcemanager/customproviders/armcustomproviders/zz_generated_customresourceprovider_client.go
  sdk/resourcemanager/customproviders/armcustomproviders/zz_generated_models.go
  sdk/resourcemanager/customproviders/armcustomproviders/zz_generated_operations_client.go
  sdk/resourcemanager/customproviders/armcustomproviders/zz_generated_pagers.go
  sdk/resourcemanager/customproviders/armcustomproviders/zz_generated_pollers.go
  sdk/resourcemanager/customproviders/armcustomproviders/zz_generated_response_types.go
Labels: Mgmt

#16633 [Release] sdk/resourcemanager/webpubsub/armwebpubsub/0.1.0
  sdk/resourcemanager/webpubsub/armwebpubsub/CHANGELOG.md
  sdk/resourcemanager/webpubsub/armwebpubsub/LICENSE.txt
  sdk/resourcemanager/webpubsub/armwebpubsub/README.md
  sdk/resourcemanager/webpubsub/armwebpubsub/autorest.md
  sdk/resourcemanager/webpubsub/armwebpubsub/build.go
  sdk/resourcemanager/webpubsub/armwebpubsub/ci.yml
  sdk/resourcemanager/webpubsub/armwebpubsub/go.mod
  sdk/resourcemanager/webpubsub/armwebpubsub/go.sum
  sdk/resourcemanager/webpubsub/armwebpubsub/go_mod_tidy_hack.go
  sdk/resourcemanager/webpubsub/armwebpubsub/ze_generated_example_operations_client_test.go
  sdk/resourcemanager/webpubsub/armwebpubsub/ze_generated_example_usages_client_test.go
  sdk/resourcemanager/webpubsub/armwebpubsub/ze_generated_example_webpubsub_client_test.go
  sdk/resourcemanager/webpubsub/armwebpubsub/ze_generated_example_webpubsubhubs_client_test.go
  sdk/resourcemanager/webpubsub/armwebpubsub/ze_generated_example_webpubsubprivateendpointconnections_client_test.go
  sdk/resourcemanager/webpubsub/armwebpubsub/ze_generated_example_webpubsubprivatelinkresources_client_test.go
  sdk/resourcemanager/webpubsub/armwebpubsub/ze_generated_example_webpubsubsharedprivatelinkresources_client_test.go
  sdk/resourcemanager/webpubsub/armwebpubsub/zz_generated_constants.go
  sdk/resourcemanager/webpubsub/armwebpubsub/zz_generated_models.go
  sdk/resourcemanager/webpubsub/armwebpubsub/zz_generated_operations_client.go
  sdk/resourcemanager/webpubsub/armwebpubsub/zz_generated_pagers.go
  sdk/resourcemanager/webpubsub/armwebpubsub/zz_generated_pollers.go
  sdk/resourcemanager/webpubsub/armwebpubsub/zz_generated_response_types.go
  sdk/resourcemanager/webpubsub/armwebpubsub/zz_generated_time_rfc3339.go
  sdk/resourcemanager/webpubsub/armwebpubsub/zz_generated_usages_client.go
  sdk/resourcemanager/webpubsub/armwebpubsub/zz_generated_webpubsub_client.go
  sdk/resourcemanager/webpubsub/armwebpubsub/zz_generated_webpubsubhubs_client.go
  sdk/resourcemanager/webpubsub/armwebpubsub/zz_generated_webpubsubprivateendpointconnections_client.go
  sdk/resourcemanager/webpubsub/armwebpubsub/zz_generated_webpubsubprivatelinkresources_client.go
  sdk/resourcemanager/webpubsub/armwebpubsub/zz_generated_webpubsubsharedprivatelinkresources_client.go
Labels: Mgmt

#16634 [Release] sdk/resourcemanager/windowsesu/armwindowsesu/0.1.0
  sdk/resourcemanager/windowsesu/armwindowsesu/CHANGELOG.md
  sdk/resourcemanager/windowsesu/armwindowsesu/LICENSE.txt
  sdk/resourcemanager/windowsesu/armwindowsesu/README.md
  sdk/resourcemanager/windowsesu/armwindowsesu/autorest.md
  sdk/resourcemanager/windowsesu/armwindowsesu/build.go
  sdk/resourcemanager/windowsesu/armwindowsesu/ci.yml
  sdk/resourcemanager/windowsesu/armwindowsesu/go.mod
  sdk/resourcemanager/windowsesu/armwindowsesu/go.sum
  sdk/resourcemanager/windowsesu/armwindowsesu/go_mod_tidy_hack.go
  sdk/resourcemanager/windowsesu/armwindowsesu/ze_generated_example_multipleactivationkeys_client_test.go
  sdk/resourcemanager/windowsesu/armwindowsesu/ze_generated_example_operations_client_test.go
  sdk/resourcemanager/windowsesu/armwindowsesu/zz_generated_constants.go
  sdk/resourcemanager/windowsesu/armwindowsesu/zz_generated_models.go
  sdk/resourcemanager/windowsesu/armwindowsesu/zz_generated_multipleactivationkeys_client.go
  sdk/resourcemanager/windowsesu/armwindowsesu/zz_generated_operations_client.go
  sdk/resourcemanager/windowsesu/armwindowsesu/zz_generated_pagers.go
  sdk/resourcemanager/windowsesu/armwindowsesu/zz_generated_pollers.go
  sdk/resourcemanager/windowsesu/armwindowsesu/zz_generated_response_types.go
  sdk/resourcemanager/windowsesu/armwindowsesu/zz_generated_time_rfc3339.go
Labels: Mgmt

#16635 [Release] sdk/resourcemanager/windowsiot/armwindowsiot/0.1.0
  sdk/resourcemanager/windowsiot/armwindowsiot/CHANGELOG.md
  sdk/resourcemanager/windowsiot/armwindowsiot/LICENSE.txt
  sdk/resourcemanager/windowsiot/armwindowsiot/README.md
  sdk/resourcemanager/windowsiot/armwindowsiot/autorest.md
  sdk/resourcemanager/windowsiot/armwindowsiot/build.go
  sdk/resourcemanager/windowsiot/armwindowsiot/ci.yml
  sdk/resourcemanager/windowsiot/armwindowsiot/go.mod
  sdk/resourcemanager/windowsiot/armwindowsiot/go.sum
  sdk/resourcemanager/windowsiot/armwindowsiot/go_mod_tidy_hack.go
  sdk/resourcemanager/windowsiot/armwindowsiot/ze_generated_example_operations_client_test.go
  sdk/resourcemanager/windowsiot/armwindowsiot/ze_generated_example_services_client_test.go
  sdk/resourcemanager/windowsiot/armwindowsiot/zz_generated_constants.go
  sdk/resourcemanager/windowsiot/armwindowsiot/zz_generated_models.go
  sdk/resourcemanager/windowsiot/armwindowsiot/zz_generated_operations_client.go
  sdk/resourcemanager/windowsiot/armwindowsiot/zz_generated_pagers.go
  sdk/resourcemanager/windowsiot/armwindowsiot/zz_generated_response_types.go
  sdk/resourcemanager/windowsiot/armwindowsiot/zz_generated_services_client.go
  sdk/resourcemanager/windowsiot/armwindowsiot/zz_generated_time_rfc3339.go
Labels: Mgmt

#16624 [Release] sdk/resourcemanager/subscription/armsubscription/0.1.0
  sdk/resourcemanager/subscription/armsubscription/CHANGELOG.md
  sdk/resourcemanager/subscription/armsubscription/LICENSE.txt
  sdk/resourcemanager/subscription/armsubscription/README.md
  sdk/resourcemanager/subscription/armsubscription/autorest.md
  sdk/resourcemanager/subscription/armsubscription/build.go
  sdk/resourcemanager/subscription/armsubscription/ci.yml
  sdk/resourcemanager/subscription/armsubscription/go.mod
  sdk/resourcemanager/subscription/armsubscription/go.sum
  sdk/resourcemanager/subscription/armsubscription/go_mod_tidy_hack.go
  sdk/resourcemanager/subscription/armsubscription/ze_generated_example_alias_client_test.go
  sdk/resourcemanager/subscription/armsubscription/ze_generated_example_billingaccount_client_test.go
  sdk/resourcemanager/subscription/armsubscription/ze_generated_example_operations_client_test.go
  sdk/resourcemanager/subscription/armsubscription/ze_generated_example_subscription_client_test.go
  sdk/resourcemanager/subscription/armsubscription/ze_generated_example_subscriptionpolicy_client_test.go
  sdk/resourcemanager/subscription/armsubscription/zz_generated_alias_client.go
  sdk/resourcemanager/subscription/armsubscription/zz_generated_billingaccount_client.go
  sdk/resourcemanager/subscription/armsubscription/zz_generated_constants.go
  sdk/resourcemanager/subscription/armsubscription/zz_generated_models.go
  sdk/resourcemanager/subscription/armsubscription/zz_generated_operations_client.go
  sdk/resourcemanager/subscription/armsubscription/zz_generated_pagers.go
  sdk/resourcemanager/subscription/armsubscription/zz_generated_pollers.go
  sdk/resourcemanager/subscription/armsubscription/zz_generated_response_types.go
  sdk/resourcemanager/subscription/armsubscription/zz_generated_subscription_client.go
  sdk/resourcemanager/subscription/armsubscription/zz_generated_subscriptionpolicy_client.go
  sdk/resourcemanager/subscription/armsubscription/zz_generated_time_rfc3339.go
Labels: Mgmt

#16629 [Release] sdk/resourcemanager/videoanalyzer/armvideoanalyzer/0.1.0
  sdk/resourcemanager/videoanalyzer/armvideoanalyzer/CHANGELOG.md
  sdk/resourcemanager/videoanalyzer/armvideoanalyzer/LICENSE.txt
  sdk/resourcemanager/videoanalyzer/armvideoanalyzer/README.md
  sdk/resourcemanager/videoanalyzer/armvideoanalyzer/autorest.md
  sdk/resourcemanager/videoanalyzer/armvideoanalyzer/build.go
  sdk/resourcemanager/videoanalyzer/armvideoanalyzer/ci.yml
  sdk/resourcemanager/videoanalyzer/armvideoanalyzer/go.mod
  sdk/resourcemanager/videoanalyzer/armvideoanalyzer/go.sum
  sdk/resourcemanager/videoanalyzer/armvideoanalyzer/go_mod_tidy_hack.go
  sdk/resourcemanager/videoanalyzer/armvideoanalyzer/ze_generated_example_accesspolicies_client_test.go
  sdk/resourcemanager/videoanalyzer/armvideoanalyzer/ze_generated_example_edgemodules_client_test.go
  sdk/resourcemanager/videoanalyzer/armvideoanalyzer/ze_generated_example_livepipelineoperationstatuses_client_test.go
  sdk/resourcemanager/videoanalyzer/armvideoanalyzer/ze_generated_example_livepipelines_client_test.go
  sdk/resourcemanager/videoanalyzer/armvideoanalyzer/ze_generated_example_locations_client_test.go
  sdk/resourcemanager/videoanalyzer/armvideoanalyzer/ze_generated_example_operationresults_client_test.go
  sdk/resourcemanager/videoanalyzer/armvideoanalyzer/ze_generated_example_operations_client_test.go
  sdk/resourcemanager/videoanalyzer/armvideoanalyzer/ze_generated_example_operationstatuses_client_test.go
  sdk/resourcemanager/videoanalyzer/armvideoanalyzer/ze_generated_example_pipelinejoboperationstatuses_client_test.go
  sdk/resourcemanager/videoanalyzer/armvideoanalyzer/ze_generated_example_pipelinejobs_client_test.go
  sdk/resourcemanager/videoanalyzer/armvideoanalyzer/ze_generated_example_pipelinetopologies_client_test.go
  sdk/resourcemanager/videoanalyzer/armvideoanalyzer/ze_generated_example_privateendpointconnections_client_test.go
  sdk/resourcemanager/videoanalyzer/armvideoanalyzer/ze_generated_example_privatelinkresources_client_test.go
  sdk/resourcemanager/videoanalyzer/armvideoanalyzer/ze_generated_example_videoanalyzeroperationresults_client_test.go
  sdk/resourcemanager/videoanalyzer/armvideoanalyzer/ze_generated_example_videoanalyzeroperationstatuses_client_test.go
  sdk/resourcemanager/videoanalyzer/armvideoanalyzer/ze_generated_example_videoanalyzers_client_test.go
  sdk/resourcemanager/videoanalyzer/armvideoanalyzer/ze_generated_example_videos_client_test.go
  sdk/resourcemanager/videoanalyzer/armvideoanalyzer/zz_generated_accesspolicies_client.go
  sdk/resourcemanager/videoanalyzer/armvideoanalyzer/zz_generated_constants.go
  sdk/resourcemanager/videoanalyzer/armvideoanalyzer/zz_generated_edgemodules_client.go
  sdk/resourcemanager/videoanalyzer/armvideoanalyzer/zz_generated_livepipelineoperationstatuses_client.go
  sdk/resourcemanager/videoanalyzer/armvideoanalyzer/zz_generated_livepipelines_client.go
  sdk/resourcemanager/videoanalyzer/armvideoanalyzer/zz_generated_locations_client.go
  sdk/resourcemanager/videoanalyzer/armvideoanalyzer/zz_generated_models.go
  sdk/resourcemanager/videoanalyzer/armvideoanalyzer/zz_generated_operationresults_client.go
  sdk/resourcemanager/videoanalyzer/armvideoanalyzer/zz_generated_operations_client.go
  sdk/resourcemanager/videoanalyzer/armvideoanalyzer/zz_generated_operationstatuses_client.go
  sdk/resourcemanager/videoanalyzer/armvideoanalyzer/zz_generated_pagers.go
  sdk/resourcemanager/videoanalyzer/armvideoanalyzer/zz_generated_pipelinejoboperationstatuses_client.go
  sdk/resourcemanager/videoanalyzer/armvideoanalyzer/zz_generated_pipelinejobs_client.go
  sdk/resourcemanager/videoanalyzer/armvideoanalyzer/zz_generated_pipelinetopologies_client.go
  sdk/resourcemanager/videoanalyzer/armvideoanalyzer/zz_generated_pollers.go
  sdk/resourcemanager/videoanalyzer/armvideoanalyzer/zz_generated_polymorphic_helpers.go
  sdk/resourcemanager/videoanalyzer/armvideoanalyzer/zz_generated_privateendpointconnections_client.go
  sdk/resourcemanager/videoanalyzer/armvideoanalyzer/zz_generated_privatelinkresources_client.go
  sdk/resourcemanager/videoanalyzer/armvideoanalyzer/zz_generated_response_types.go
  sdk/resourcemanager/videoanalyzer/armvideoanalyzer/zz_generated_time_rfc3339.go
  sdk/resourcemanager/videoanalyzer/armvideoanalyzer/zz_generated_videoanalyzeroperationresults_client.go
  sdk/resourcemanager/videoanalyzer/armvideoanalyzer/zz_generated_videoanalyzeroperationstatuses_client.go
  sdk/resourcemanager/videoanalyzer/armvideoanalyzer/zz_generated_videoanalyzers_client.go
  sdk/resourcemanager/videoanalyzer/armvideoanalyzer/zz_generated_videos_client.go
Labels: Mgmt

#16630 [Release] sdk/resourcemanager/visualstudio/armvisualstudio/0.1.0
  sdk/resourcemanager/visualstudio/armvisualstudio/CHANGELOG.md
  sdk/resourcemanager/visualstudio/armvisualstudio/LICENSE.txt
  sdk/resourcemanager/visualstudio/armvisualstudio/README.md
  sdk/resourcemanager/visualstudio/armvisualstudio/autorest.md
  sdk/resourcemanager/visualstudio/armvisualstudio/build.go
  sdk/resourcemanager/visualstudio/armvisualstudio/ci.yml
  sdk/resourcemanager/visualstudio/armvisualstudio/go.mod
  sdk/resourcemanager/visualstudio/armvisualstudio/go.sum
  sdk/resourcemanager/visualstudio/armvisualstudio/go_mod_tidy_hack.go
  sdk/resourcemanager/visualstudio/armvisualstudio/ze_generated_example_accounts_client_test.go
  sdk/resourcemanager/visualstudio/armvisualstudio/ze_generated_example_extensions_client_test.go
  sdk/resourcemanager/visualstudio/armvisualstudio/ze_generated_example_operations_client_test.go
  sdk/resourcemanager/visualstudio/armvisualstudio/ze_generated_example_projects_client_test.go
  sdk/resourcemanager/visualstudio/armvisualstudio/zz_generated_accounts_client.go
  sdk/resourcemanager/visualstudio/armvisualstudio/zz_generated_constants.go
  sdk/resourcemanager/visualstudio/armvisualstudio/zz_generated_extensions_client.go
  sdk/resourcemanager/visualstudio/armvisualstudio/zz_generated_models.go
  sdk/resourcemanager/visualstudio/armvisualstudio/zz_generated_operations_client.go
  sdk/resourcemanager/visualstudio/armvisualstudio/zz_generated_pollers.go
  sdk/resourcemanager/visualstudio/armvisualstudio/zz_generated_projects_client.go
  sdk/resourcemanager/visualstudio/armvisualstudio/zz_generated_response_types.go
Labels: Mgmt

#16631 Release sdk/resourcemanager/avs/armavs/0.1.0
  sdk/resourcemanager/avs/armavs/CHANGELOG.md
  sdk/resourcemanager/avs/armavs/LICENSE.txt
  sdk/resourcemanager/avs/armavs/README.md
  sdk/resourcemanager/avs/armavs/autorest.md
  sdk/resourcemanager/avs/armavs/build.go
  sdk/resourcemanager/avs/armavs/ci.yml
  sdk/resourcemanager/avs/armavs/go.mod
  sdk/resourcemanager/avs/armavs/go.sum
  sdk/resourcemanager/avs/armavs/go_mod_tidy_hack.go
  sdk/resourcemanager/avs/armavs/ze_generated_example_addons_client_test.go
  sdk/resourcemanager/avs/armavs/ze_generated_example_authorizations_client_test.go
  sdk/resourcemanager/avs/armavs/ze_generated_example_cloudlinks_client_test.go
  sdk/resourcemanager/avs/armavs/ze_generated_example_clusters_client_test.go
  sdk/resourcemanager/avs/armavs/ze_generated_example_datastores_client_test.go
  sdk/resourcemanager/avs/armavs/ze_generated_example_globalreachconnections_client_test.go
  sdk/resourcemanager/avs/armavs/ze_generated_example_hcxenterprisesites_client_test.go
  sdk/resourcemanager/avs/armavs/ze_generated_example_locations_client_test.go
  sdk/resourcemanager/avs/armavs/ze_generated_example_operations_client_test.go
  sdk/resourcemanager/avs/armavs/ze_generated_example_placementpolicies_client_test.go
  sdk/resourcemanager/avs/armavs/ze_generated_example_privateclouds_client_test.go
  sdk/resourcemanager/avs/armavs/ze_generated_example_scriptcmdlets_client_test.go
  sdk/resourcemanager/avs/armavs/ze_generated_example_scriptexecutions_client_test.go
  sdk/resourcemanager/avs/armavs/ze_generated_example_scriptpackages_client_test.go
  sdk/resourcemanager/avs/armavs/ze_generated_example_virtualmachines_client_test.go
  sdk/resourcemanager/avs/armavs/ze_generated_example_workloadnetworks_client_test.go
  sdk/resourcemanager/avs/armavs/zz_generated_addons_client.go
  sdk/resourcemanager/avs/armavs/zz_generated_authorizations_client.go
  sdk/resourcemanager/avs/armavs/zz_generated_cloudlinks_client.go
  sdk/resourcemanager/avs/armavs/zz_generated_clusters_client.go
  sdk/resourcemanager/avs/armavs/zz_generated_constants.go
  sdk/resourcemanager/avs/armavs/zz_generated_datastores_client.go
  sdk/resourcemanager/avs/armavs/zz_generated_globalreachconnections_client.go
  sdk/resourcemanager/avs/armavs/zz_generated_hcxenterprisesites_client.go
  sdk/resourcemanager/avs/armavs/zz_generated_locations_client.go
  sdk/resourcemanager/avs/armavs/zz_generated_models.go
  sdk/resourcemanager/avs/armavs/zz_generated_operations_client.go
  sdk/resourcemanager/avs/armavs/zz_generated_pagers.go
  sdk/resourcemanager/avs/armavs/zz_generated_placementpolicies_client.go
  sdk/resourcemanager/avs/armavs/zz_generated_pollers.go
  sdk/resourcemanager/avs/armavs/zz_generated_polymorphic_helpers.go
  sdk/resourcemanager/avs/armavs/zz_generated_privateclouds_client.go
  sdk/resourcemanager/avs/armavs/zz_generated_response_types.go
  sdk/resourcemanager/avs/armavs/zz_generated_scriptcmdlets_client.go
  sdk/resourcemanager/avs/armavs/zz_generated_scriptexecutions_client.go
  sdk/resourcemanager/avs/armavs/zz_generated_scriptpackages_client.go
  sdk/resourcemanager/avs/armavs/zz_generated_time_rfc3339.go
  sdk/resourcemanager/avs/armavs/zz_generated_virtualmachines_client.go
  sdk/resourcemanager/avs/armavs/zz_generated_workloadnetworks_client.go
Labels: Mgmt

#16632 [Release] sdk/resourcemanager/vmwarecloudsimple/armvmwarecloudsimple/0.1.0
  sdk/resourcemanager/vmwarecloudsimple/armvmwarecloudsimple/CHANGELOG.md
  sdk/resourcemanager/vmwarecloudsimple/armvmwarecloudsimple/LICENSE.txt
  sdk/resourcemanager/vmwarecloudsimple/armvmwarecloudsimple/README.md
  sdk/resourcemanager/vmwarecloudsimple/armvmwarecloudsimple/autorest.md
  sdk/resourcemanager/vmwarecloudsimple/armvmwarecloudsimple/build.go
  sdk/resourcemanager/vmwarecloudsimple/armvmwarecloudsimple/ci.yml
  sdk/resourcemanager/vmwarecloudsimple/armvmwarecloudsimple/go.mod
  sdk/resourcemanager/vmwarecloudsimple/armvmwarecloudsimple/go.sum
  sdk/resourcemanager/vmwarecloudsimple/armvmwarecloudsimple/go_mod_tidy_hack.go
  sdk/resourcemanager/vmwarecloudsimple/armvmwarecloudsimple/ze_generated_example_customizationpolicies_client_test.go
  sdk/resourcemanager/vmwarecloudsimple/armvmwarecloudsimple/ze_generated_example_dedicatedcloudnodes_client_test.go
  sdk/resourcemanager/vmwarecloudsimple/armvmwarecloudsimple/ze_generated_example_dedicatedcloudservices_client_test.go
  sdk/resourcemanager/vmwarecloudsimple/armvmwarecloudsimple/ze_generated_example_operations_client_test.go
  sdk/resourcemanager/vmwarecloudsimple/armvmwarecloudsimple/ze_generated_example_privateclouds_client_test.go
  sdk/resourcemanager/vmwarecloudsimple/armvmwarecloudsimple/ze_generated_example_resourcepools_client_test.go
  sdk/resourcemanager/vmwarecloudsimple/armvmwarecloudsimple/ze_generated_example_skusavailability_client_test.go
  sdk/resourcemanager/vmwarecloudsimple/armvmwarecloudsimple/ze_generated_example_usages_client_test.go
  sdk/resourcemanager/vmwarecloudsimple/armvmwarecloudsimple/ze_generated_example_virtualmachines_client_test.go
  sdk/resourcemanager/vmwarecloudsimple/armvmwarecloudsimple/ze_generated_example_virtualmachinetemplates_client_test.go
  sdk/resourcemanager/vmwarecloudsimple/armvmwarecloudsimple/ze_generated_example_virtualnetworks_client_test.go
  sdk/resourcemanager/vmwarecloudsimple/armvmwarecloudsimple/zz_generated_constants.go
  sdk/resourcemanager/vmwarecloudsimple/armvmwarecloudsimple/zz_generated_customizationpolicies_client.go
  sdk/resourcemanager/vmwarecloudsimple/armvmwarecloudsimple/zz_generated_dedicatedcloudnodes_client.go
  sdk/resourcemanager/vmwarecloudsimple/armvmwarecloudsimple/zz_generated_dedicatedcloudservices_client.go
  sdk/resourcemanager/vmwarecloudsimple/armvmwarecloudsimple/zz_generated_models.go
  sdk/resourcemanager/vmwarecloudsimple/armvmwarecloudsimple/zz_generated_operations_client.go
  sdk/resourcemanager/vmwarecloudsimple/armvmwarecloudsimple/zz_generated_pagers.go
  sdk/resourcemanager/vmwarecloudsimple/armvmwarecloudsimple/zz_generated_pollers.go
  sdk/resourcemanager/vmwarecloudsimple/armvmwarecloudsimple/zz_generated_privateclouds_client.go
  sdk/resourcemanager/vmwarecloudsimple/armvmwarecloudsimple/zz_generated_resourcepools_client.go
  sdk/resourcemanager/vmwarecloudsimple/armvmwarecloudsimple/zz_generated_response_types.go
  sdk/resourcemanager/vmwarecloudsimple/armvmwarecloudsimple/zz_generated_skusavailability_client.go
  sdk/resourcemanager/vmwarecloudsimple/armvmwarecloudsimple/zz_generated_time_rfc3339.go
  sdk/resourcemanager/vmwarecloudsimple/armvmwarecloudsimple/zz_generated_usages_client.go
  sdk/resourcemanager/vmwarecloudsimple/armvmwarecloudsimple/zz_generated_virtualmachines_client.go
  sdk/resourcemanager/vmwarecloudsimple/armvmwarecloudsimple/zz_generated_virtualmachinetemplates_client.go
  sdk/resourcemanager/vmwarecloudsimple/armvmwarecloudsimple/zz_generated_virtualnetworks_client.go
Labels: Mgmt

#16680 [Release] sdk/resourcemanager/resourcemover/armresourcemover/0.1.0
  sdk/resourcemanager/resourcemover/armresourcemover/CHANGELOG.md
  sdk/resourcemanager/resourcemover/armresourcemover/LICENSE.txt
  sdk/resourcemanager/resourcemover/armresourcemover/README.md
  sdk/resourcemanager/resourcemover/armresourcemover/autorest.md
  sdk/resourcemanager/resourcemover/armresourcemover/build.go
  sdk/resourcemanager/resourcemover/armresourcemover/ci.yml
  sdk/resourcemanager/resourcemover/armresourcemover/go.mod
  sdk/resourcemanager/resourcemover/armresourcemover/go.sum
  sdk/resourcemanager/resourcemover/armresourcemover/go_mod_tidy_hack.go
  sdk/resourcemanager/resourcemover/armresourcemover/ze_generated_example_movecollections_client_test.go
  sdk/resourcemanager/resourcemover/armresourcemover/ze_generated_example_moveresources_client_test.go
  sdk/resourcemanager/resourcemover/armresourcemover/ze_generated_example_operationsdiscovery_client_test.go
  sdk/resourcemanager/resourcemover/armresourcemover/ze_generated_example_unresolveddependencies_client_test.go
  sdk/resourcemanager/resourcemover/armresourcemover/zz_generated_constants.go
  sdk/resourcemanager/resourcemover/armresourcemover/zz_generated_models.go
  sdk/resourcemanager/resourcemover/armresourcemover/zz_generated_movecollections_client.go
  sdk/resourcemanager/resourcemover/armresourcemover/zz_generated_moveresources_client.go
  sdk/resourcemanager/resourcemover/armresourcemover/zz_generated_operationsdiscovery_client.go
  sdk/resourcemanager/resourcemover/armresourcemover/zz_generated_pagers.go
  sdk/resourcemanager/resourcemover/armresourcemover/zz_generated_pollers.go
  sdk/resourcemanager/resourcemover/armresourcemover/zz_generated_polymorphic_helpers.go
  sdk/resourcemanager/resourcemover/armresourcemover/zz_generated_response_types.go
  sdk/resourcemanager/resourcemover/armresourcemover/zz_generated_time_rfc3339.go
  sdk/resourcemanager/resourcemover/armresourcemover/zz_generated_unresolveddependencies_client.go
Labels: Mgmt

#16681 [Release] sdk/resourcemanager/saas/armsaas/0.1.0
  sdk/resourcemanager/saas/armsaas/CHANGELOG.md
  sdk/resourcemanager/saas/armsaas/LICENSE.txt
  sdk/resourcemanager/saas/armsaas/README.md
  sdk/resourcemanager/saas/armsaas/autorest.md
  sdk/resourcemanager/saas/armsaas/build.go
  sdk/resourcemanager/saas/armsaas/ci.yml
  sdk/resourcemanager/saas/armsaas/go.mod
  sdk/resourcemanager/saas/armsaas/go.sum
  sdk/resourcemanager/saas/armsaas/go_mod_tidy_hack.go
  sdk/resourcemanager/saas/armsaas/ze_generated_example_applications_client_test.go
  sdk/resourcemanager/saas/armsaas/ze_generated_example_operations_client_test.go
  sdk/resourcemanager/saas/armsaas/ze_generated_example_saas_client_test.go
  sdk/resourcemanager/saas/armsaas/ze_generated_example_saasoperation_client_test.go
  sdk/resourcemanager/saas/armsaas/ze_generated_example_saasresources_client_test.go
  sdk/resourcemanager/saas/armsaas/ze_generated_example_saassubscriptionlevel_client_test.go
  sdk/resourcemanager/saas/armsaas/zz_generated_applications_client.go
  sdk/resourcemanager/saas/armsaas/zz_generated_constants.go
  sdk/resourcemanager/saas/armsaas/zz_generated_models.go
  sdk/resourcemanager/saas/armsaas/zz_generated_operations_client.go
  sdk/resourcemanager/saas/armsaas/zz_generated_pagers.go
  sdk/resourcemanager/saas/armsaas/zz_generated_pollers.go
  sdk/resourcemanager/saas/armsaas/zz_generated_response_types.go
  sdk/resourcemanager/saas/armsaas/zz_generated_saas_client.go
  sdk/resourcemanager/saas/armsaas/zz_generated_saasoperation_client.go
  sdk/resourcemanager/saas/armsaas/zz_generated_saasresources_client.go
  sdk/resourcemanager/saas/armsaas/zz_generated_saassubscriptionlevel_client.go
Labels: Mgmt
