Repository Azure/azure-sdk-for-go, pull requests merged in 2021-11, with the labels that each got.

#15974 Add live tests to azidentity pipeline
  sdk/azidentity/aad_identity_client_test.go
  sdk/azidentity/azidentity.go
  sdk/azidentity/azidentity_test.go
  sdk/azidentity/ci.yml
  sdk/azidentity/client_certificate_credential_test.go
  sdk/azidentity/client_secret_credential_test.go
  sdk/azidentity/environment_credential_test.go
  sdk/azidentity/logging.go
  sdk/azidentity/username_password_credential_test.go
Labels: Azure.Identity

#16043 Sync eng/common directory with azure-sdk-tools for PR 2177
  eng/common/scripts/Invoke-GitHubAPI.ps1
Labels: EngSys, Central-EngSys

#16047 Sync eng/common directory with azure-sdk-tools for PR 2203
  eng/common/pipelines/templates/steps/sparse-checkout.yml
Labels: EngSys, Central-EngSys

#16048 Sync eng/common directory with azure-sdk-tools for PR 2179
  eng/common/pipelines/templates/steps/docker-pull-image.yml
  eng/common/scripts/Update-DocsMsPackages.ps1
Labels: EngSys, Central-EngSys

#16038 Increment version for resourcemanager/recoveryservices/armrecoveryservices releases
  sdk/resourcemanager/recoveryservices/armrecoveryservices/CHANGELOG.md
  sdk/resourcemanager/recoveryservices/armrecoveryservices/zz_generated_constants.go
Labels: auto-merge

#16037 Increment version for resourcemanager/sql/armsql releases
  sdk/resourcemanager/sql/armsql/CHANGELOG.md
  sdk/resourcemanager/sql/armsql/zz_generated_constants.go
Labels: auto-merge

#16036 Increment version for resourcemanager/storage/armstorage releases
  sdk/resourcemanager/storage/armstorage/CHANGELOG.md
  sdk/resourcemanager/storage/armstorage/zz_generated_constants.go
Labels: auto-merge

#16035 Increment version for resourcemanager/streamanalytics/armstreamanalytics releases
  sdk/resourcemanager/streamanalytics/armstreamanalytics/CHANGELOG.md
  sdk/resourcemanager/streamanalytics/armstreamanalytics/zz_generated_constants.go
Labels: auto-merge

#16034 Increment version for resourcemanager/relay/armrelay releases
  sdk/resourcemanager/relay/armrelay/CHANGELOG.md
  sdk/resourcemanager/relay/armrelay/zz_generated_constants.go
Labels: auto-merge

#16033 Increment version for resourcemanager/web/armweb releases
  sdk/resourcemanager/web/armweb/CHANGELOG.md
  sdk/resourcemanager/web/armweb/zz_generated_constants.go
Labels: auto-merge

#16032 Increment version for resourcemanager/redis/armredis releases
  sdk/resourcemanager/redis/armredis/CHANGELOG.md
  sdk/resourcemanager/redis/armredis/zz_generated_constants.go
Labels: auto-merge

#16030 Increment version for resourcemanager/search/armsearch releases
  sdk/resourcemanager/search/armsearch/CHANGELOG.md
  sdk/resourcemanager/search/armsearch/zz_generated_constants.go
Labels: auto-merge

#16029 Increment version for resourcemanager/servicebus/armservicebus releases
  sdk/resourcemanager/servicebus/armservicebus/CHANGELOG.md
  sdk/resourcemanager/servicebus/armservicebus/zz_generated_constants.go
Labels: auto-merge

#16031 Increment version for resourcemanager/servicefabric/armservicefabric releases
  sdk/resourcemanager/servicefabric/armservicefabric/CHANGELOG.md
  sdk/resourcemanager/servicefabric/armservicefabric/zz_generated_constants.go
Labels: auto-merge

#16028 Increment version for resourcemanager/security/armsecurity releases
  sdk/resourcemanager/security/armsecurity/CHANGELOG.md
  sdk/resourcemanager/security/armsecurity/zz_generated_constants.go
Labels: auto-merge

#16026 Increment version for resourcemanager/resources/armresources releases
  sdk/resourcemanager/resources/armresources/CHANGELOG.md
  sdk/resourcemanager/resources/armresources/zz_generated_constants.go
Labels: auto-merge

#16027 Increment version for resourcemanager/scheduler/armscheduler releases
  sdk/resourcemanager/scheduler/armscheduler/CHANGELOG.md
  sdk/resourcemanager/scheduler/armscheduler/zz_generated_constants.go
Labels: auto-merge

#16023 Increment version for resourcemanager/operationsmanagement/armoperationsmanagement releases
  sdk/resourcemanager/operationsmanagement/armoperationsmanagement/CHANGELOG.md
  sdk/resourcemanager/operationsmanagement/armoperationsmanagement/zz_generated_constants.go
Labels: auto-merge

#16024 Increment version for resourcemanager/privatedns/armprivatedns releases
  sdk/resourcemanager/privatedns/armprivatedns/CHANGELOG.md
  sdk/resourcemanager/privatedns/armprivatedns/zz_generated_constants.go
Labels: auto-merge

#16022 Increment version for resourcemanager/postgresql/armpostgresqlflexibleservers releases
  sdk/resourcemanager/postgresql/armpostgresqlflexibleservers/CHANGELOG.md
  sdk/resourcemanager/postgresql/armpostgresqlflexibleservers/zz_generated_constants.go
Labels: auto-merge

#16020 Increment version for resourcemanager/operationalinsights/armoperationalinsights releases
  sdk/resourcemanager/operationalinsights/armoperationalinsights/CHANGELOG.md
  sdk/resourcemanager/operationalinsights/armoperationalinsights/zz_generated_constants.go
Labels: auto-merge

#16019 Increment version for resourcemanager/postgresql/armpostgresql releases
  sdk/resourcemanager/postgresql/armpostgresql/CHANGELOG.md
  sdk/resourcemanager/postgresql/armpostgresql/zz_generated_constants.go
Labels: auto-merge

#16021 Increment version for resourcemanager/notificationhubs/armnotificationhubs releases
  sdk/resourcemanager/notificationhubs/armnotificationhubs/CHANGELOG.md
  sdk/resourcemanager/notificationhubs/armnotificationhubs/zz_generated_constants.go
Labels: auto-merge

#16025 Increment version for resourcemanager/resourcehealth/armresourcehealth releases
  sdk/resourcemanager/resourcehealth/armresourcehealth/CHANGELOG.md
  sdk/resourcemanager/resourcehealth/armresourcehealth/zz_generated_constants.go
Labels: auto-merge

#16018 Increment version for resourcemanager/network/armnetwork releases
  sdk/resourcemanager/network/armnetwork/CHANGELOG.md
  sdk/resourcemanager/network/armnetwork/zz_generated_constants.go
Labels: auto-merge

#16017 Increment version for resourcemanager/msi/armmsi releases
  sdk/resourcemanager/msi/armmsi/CHANGELOG.md
  sdk/resourcemanager/msi/armmsi/zz_generated_constants.go
Labels: auto-merge

#16014 Increment version for resourcemanager/mysql/armmysql releases
  sdk/resourcemanager/mysql/armmysql/CHANGELOG.md
  sdk/resourcemanager/mysql/armmysql/zz_generated_constants.go
Labels: auto-merge

#16016 Increment version for resourcemanager/mediaservices/armmediaservices releases
  sdk/resourcemanager/mediaservices/armmediaservices/CHANGELOG.md
  sdk/resourcemanager/mediaservices/armmediaservices/zz_generated_constants.go
Labels: auto-merge

#16015 Increment version for resourcemanager/monitor/armmonitor releases
  sdk/resourcemanager/monitor/armmonitor/CHANGELOG.md
  sdk/resourcemanager/monitor/armmonitor/zz_generated_constants.go
Labels: auto-merge

#16052 Adding step to ensure no replace directives
  eng/pipelines/templates/jobs/archetype-go-release.yml
  eng/scripts/validate_go_mod.ps1
Labels: EngSys, auto-merge

#15959 [KeyVault] bumping azsecrets to latest azcore
  sdk/keyvault/azsecrets/CHANGELOG.md
  sdk/keyvault/azsecrets/autorest.md
  sdk/keyvault/azsecrets/client.go
  sdk/keyvault/azsecrets/client_test.go
  sdk/keyvault/azsecrets/go.mod
  sdk/keyvault/azsecrets/go.sum
  sdk/keyvault/azsecrets/internal/connection.go
  sdk/keyvault/azsecrets/internal/constants.go
  sdk/keyvault/azsecrets/internal/hsmsecuritydomain_client.go
  sdk/keyvault/azsecrets/internal/keyvaultclient_client.go
  sdk/keyvault/azsecrets/internal/models.go
  sdk/keyvault/azsecrets/internal/pagers.go
  sdk/keyvault/azsecrets/internal/pollers.go
  sdk/keyvault/azsecrets/internal/response_types.go
  sdk/keyvault/azsecrets/internal/roleassignments_client.go
  sdk/keyvault/azsecrets/internal/roledefinitions_client.go
  sdk/keyvault/azsecrets/internal/time_unix.go
  sdk/keyvault/azsecrets/testdata/recordings/TestBackupSecret.json
  sdk/keyvault/azsecrets/testdata/recordings/TestBeginRecoverDeletedSecret.json
  sdk/keyvault/azsecrets/testdata/recordings/TestDeleteSecret.json
  sdk/keyvault/azsecrets/testdata/recordings/TestListDeletedSecrets.json
  sdk/keyvault/azsecrets/testdata/recordings/TestListSecretVersions.json
  sdk/keyvault/azsecrets/testdata/recordings/TestListSecrets.json
  sdk/keyvault/azsecrets/testdata/recordings/TestPurgeDeletedSecret.json
  sdk/keyvault/azsecrets/testdata/recordings/TestSetGetSecret.json
  sdk/keyvault/azsecrets/testdata/recordings/TestUpdateSecretProperties.json
  sdk/keyvault/azsecrets/utils_test.go
Labels: KeyVault, auto-merge

#16055 [Tables] updating options
  sdk/data/aztables/CHANGELOG.md
  sdk/data/aztables/go.mod
  sdk/data/aztables/go.sum
  sdk/data/aztables/internal/constants.go
  sdk/data/aztables/service_client.go
Labels: Tables, auto-merge

#16057 [Cosmos DB] DatabaseClient and ContainerClient as pointers
  sdk/data/azcosmos/cosmos_client.go
  sdk/data/azcosmos/cosmos_container.go
  sdk/data/azcosmos/cosmos_database.go
  sdk/data/azcosmos/emulator_tests.go
Labels: Cosmos

#16060 Increment version for azidentity releases
  sdk/azidentity/CHANGELOG.md
  sdk/azidentity/version.go
Labels: auto-merge

#16065 Sync eng/common directory with azure-sdk-tools for PR 2053
  eng/common/TestResources/New-TestResources.ps1
Labels: EngSys, Central-EngSys

#15998 Increment version for resourcemanager/containerservice/armcontainerservice releases
  sdk/resourcemanager/containerservice/armcontainerservice/CHANGELOG.md
  sdk/resourcemanager/containerservice/armcontainerservice/zz_generated_constants.go
Labels: auto-merge

#15999 Increment version for resourcemanager/cosmos/armcosmos releases
  sdk/resourcemanager/cosmos/armcosmos/CHANGELOG.md
  sdk/resourcemanager/cosmos/armcosmos/zz_generated_constants.go
Labels: auto-merge

#16000 Increment version for resourcemanager/consumption/armconsumption releases
  sdk/resourcemanager/consumption/armconsumption/CHANGELOG.md
  sdk/resourcemanager/consumption/armconsumption/zz_generated_constants.go
Labels: auto-merge

#16001 Increment version for resourcemanager/cognitiveservices/armcognitiveservices releases
  sdk/resourcemanager/cognitiveservices/armcognitiveservices/CHANGELOG.md
  sdk/resourcemanager/cognitiveservices/armcognitiveservices/zz_generated_constants.go
Labels: auto-merge

#16002 Increment version for resourcemanager/cdn/armcdn releases
  sdk/resourcemanager/cdn/armcdn/CHANGELOG.md
  sdk/resourcemanager/cdn/armcdn/zz_generated_constants.go
Labels: auto-merge

#16003 Increment version for resourcemanager/compute/armcompute releases
  sdk/resourcemanager/compute/armcompute/CHANGELOG.md
  sdk/resourcemanager/compute/armcompute/zz_generated_constants.go
Labels: auto-merge

#16062 [Tables] fixing SAS in ServiceClient.NewClient
  sdk/data/aztables/proxy_test.go
  sdk/data/aztables/service_client.go
Labels: Tables, auto-merge

#16066 Increment version for data/aztables releases
  sdk/data/aztables/CHANGELOG.md
  sdk/data/aztables/internal/constants.go
Labels: auto-merge

#16068 Increment version for keyvault/azsecrets releases
  sdk/keyvault/azsecrets/CHANGELOG.md
  sdk/keyvault/azsecrets/internal/constants.go
Labels: KeyVault, auto-merge

#15722 Refactor azblob constructors for azcore 0.20.0
  sdk/storage/azblob/CHANGELOG.md
  sdk/storage/azblob/README.md
  sdk/storage/azblob/constants.go
  sdk/storage/azblob/go.mod
  sdk/storage/azblob/go.sum
  sdk/storage/azblob/zc_append_blob_client.go
  sdk/storage/azblob/zc_blob_client.go
  sdk/storage/azblob/zc_block_blob_client.go
  sdk/storage/azblob/zc_connection_string.go
  sdk/storage/azblob/zc_container_client.go
  sdk/storage/azblob/zc_page_blob_client.go
  sdk/storage/azblob/zc_service_client.go
  sdk/storage/azblob/zc_shared_policy_shared_key_credential.go
  sdk/storage/azblob/zm_client_options.go
  sdk/storage/azblob/zt_block_blob_client_test.go
  sdk/storage/azblob/zt_connection_string_test.go
  sdk/storage/azblob/zt_container_client_test.go
  sdk/storage/azblob/zt_examples_test.go
  sdk/storage/azblob/zt_service_client_test.go
  sdk/storage/azblob/zt_test.go
  sdk/storage/azblob/zz_generated_connection.go
Labels: Storage, Client

#16075 Prepare azblob 0.2.0 release
  sdk/storage/azblob/CHANGELOG.md
  sdk/storage/azblob/zz_generated_constants.go
Labels: Storage

#16070 Sync eng/common directory with azure-sdk-tools for PR 2199
  eng/common/scripts/stress-testing/deploy-stress-tests.ps1
  eng/common/scripts/stress-testing/find-all-stress-packages.ps1
Labels: EngSys, Central-EngSys

#16077 Increment version for storage/azblob releases
  sdk/storage/azblob/CHANGELOG.md
  sdk/storage/azblob/zz_generated_constants.go
Labels: Storage, auto-merge

#16044 [azservicebus] AdminClient can now create topics and subscriptions
  sdk/messaging/azservicebus/CHANGELOG.md
  sdk/messaging/azservicebus/admin_client.go
  sdk/messaging/azservicebus/admin_client_models.go
  sdk/messaging/azservicebus/admin_client_queue.go
  sdk/messaging/azservicebus/admin_client_subscription.go
  sdk/messaging/azservicebus/admin_client_test.go
  sdk/messaging/azservicebus/admin_client_topic.go
  sdk/messaging/azservicebus/example_admin_client_test.go
  sdk/messaging/azservicebus/internal/atom/admin_test.go
  sdk/messaging/azservicebus/internal/atom/converters.go
  sdk/messaging/azservicebus/internal/atom/entity_manager.go
  sdk/messaging/azservicebus/internal/atom/models.go
  sdk/messaging/azservicebus/internal/atom/queue_manager.go
  sdk/messaging/azservicebus/internal/atom/subscription_manager.go
  sdk/messaging/azservicebus/internal/atom/topic.go
  sdk/messaging/azservicebus/internal/atom/topic_manager.go
  sdk/messaging/azservicebus/liveTestHelpers_test.go
  sdk/messaging/azservicebus/sample.env
  sdk/messaging/azservicebus/stress/stress.go
  sdk/messaging/azservicebus/test-resources.bicep
Labels: Service Bus, Client

#16080 Sync eng/common directory with azure-sdk-tools for PR 2202
  eng/common/scripts/ChangeLog-Operations.ps1
  eng/common/scripts/Prepare-Release.ps1
Labels: EngSys, Central-EngSys

#15991 Increment version for resourcemanager/agrifood/armagrifood releases
  sdk/resourcemanager/agrifood/armagrifood/CHANGELOG.md
  sdk/resourcemanager/agrifood/armagrifood/zz_generated_constants.go
Labels: auto-merge

#15992 Increment version for resourcemanager/alertsmanagement/armalertsmanagement releases
  sdk/resourcemanager/alertsmanagement/armalertsmanagement/CHANGELOG.md
  sdk/resourcemanager/alertsmanagement/armalertsmanagement/zz_generated_constants.go
Labels: auto-merge

#15993 Increment version for resourcemanager/containerregistry/armcontainerregistry releases
  sdk/resourcemanager/containerregistry/armcontainerregistry/CHANGELOG.md
  sdk/resourcemanager/containerregistry/armcontainerregistry/zz_generated_constants.go
Labels: auto-merge

#15994 Increment version for resourcemanager/appplatform/armappplatform releases
  sdk/resourcemanager/appplatform/armappplatform/CHANGELOG.md
  sdk/resourcemanager/appplatform/armappplatform/zz_generated_constants.go
Labels: auto-merge

#15995 Increment version for resourcemanager/authorization/armauthorization releases
  sdk/resourcemanager/authorization/armauthorization/CHANGELOG.md
  sdk/resourcemanager/authorization/armauthorization/zz_generated_constants.go
Labels: auto-merge

#16004 Increment version for resourcemanager/datalake-analytics/armdatalakeanalytics releases
  sdk/resourcemanager/datalake-analytics/armdatalakeanalytics/CHANGELOG.md
  sdk/resourcemanager/datalake-analytics/armdatalakeanalytics/zz_generated_constants.go
Labels: auto-merge

#16005 Increment version for resourcemanager/databricks/armdatabricks releases
  sdk/resourcemanager/databricks/armdatabricks/CHANGELOG.md
  sdk/resourcemanager/databricks/armdatabricks/zz_generated_constants.go
Labels: auto-merge

#15997 Increment version for resourcemanager/automation/armautomation releases
  sdk/resourcemanager/automation/armautomation/CHANGELOG.md
  sdk/resourcemanager/automation/armautomation/zz_generated_constants.go
Labels: auto-merge

#15996 Increment version for resourcemanager/apimanagement/armapimanagement releases
  sdk/resourcemanager/apimanagement/armapimanagement/CHANGELOG.md
  sdk/resourcemanager/apimanagement/armapimanagement/zz_generated_constants.go
Labels: auto-merge

#16007 Increment version for resourcemanager/datalake-store/armdatalakestore releases
  sdk/resourcemanager/datalake-store/armdatalakestore/CHANGELOG.md
  sdk/resourcemanager/datalake-store/armdatalakestore/zz_generated_constants.go
Labels: auto-merge

#16008 Increment version for resourcemanager/eventhub/armeventhub releases
  sdk/resourcemanager/eventhub/armeventhub/CHANGELOG.md
  sdk/resourcemanager/eventhub/armeventhub/zz_generated_constants.go
Labels: auto-merge

#16011 Increment version for resourcemanager/mysql/armmysqlflexibleservers releases
  sdk/resourcemanager/mysql/armmysqlflexibleservers/CHANGELOG.md
  sdk/resourcemanager/mysql/armmysqlflexibleservers/zz_generated_constants.go
Labels: auto-merge

#16009 Increment version for resourcemanager/iothub/armiothub releases
  sdk/resourcemanager/iothub/armiothub/CHANGELOG.md
  sdk/resourcemanager/iothub/armiothub/zz_generated_constants.go
Labels: auto-merge

#16010 Increment version for resourcemanager/keyvault/armkeyvault releases
  sdk/resourcemanager/keyvault/armkeyvault/CHANGELOG.md
  sdk/resourcemanager/keyvault/armkeyvault/zz_generated_constants.go
Labels: auto-merge

#16012 Increment version for resourcemanager/managementgroups/armmanagementgroups releases
  sdk/resourcemanager/managementgroups/armmanagementgroups/CHANGELOG.md
  sdk/resourcemanager/managementgroups/armmanagementgroups/zz_generated_constants.go
Labels: auto-merge

#16013 Increment version for resourcemanager/logic/armlogic releases
  sdk/resourcemanager/logic/armlogic/CHANGELOG.md
  sdk/resourcemanager/logic/armlogic/zz_generated_constants.go
Labels: auto-merge

#16073 Increment version for messaging/azservicebus releases
  sdk/messaging/azservicebus/CHANGELOG.md
  sdk/messaging/azservicebus/internal/constants.go
Labels: auto-merge

#16087 [Tables] Adding ContinuationToken support
  sdk/data/aztables/CHANGELOG.md
  sdk/data/aztables/client.go
  sdk/data/aztables/client_test.go
  sdk/data/aztables/internal/constants.go
  sdk/data/aztables/testdata/recordings/TestContinuationTokens/TestContinuationTokens_cosmos.json
  sdk/data/aztables/testdata/recordings/TestContinuationTokens/TestContinuationTokens_storage.json
Labels: Tables

#16076 Add allow-lists for headers and query parameters
  sdk/azcore/CHANGELOG.md
  sdk/azcore/policy/policy.go
  sdk/azcore/runtime/policy_logging.go
  sdk/azcore/runtime/policy_logging_test.go
  sdk/azcore/runtime/response.go
Labels: Azure.Core

#16089 Remove AzureGermany Endpoint
  sdk/azcore/arm/client_options.go
  sdk/azcore/internal/shared/shared_test.go
Labels: Azure.Core

#16103 docs and pulling main
  eng/pipelines/templates/jobs/archetype-go-release.yml
  eng/pipelines/templates/jobs/archetype-sdk-client.yml
  eng/pipelines/templates/jobs/live.tests.yml
  eng/pipelines/templates/steps/analyze.yml
  eng/pipelines/templates/steps/build-test.yml
  sdk/keyvault/azkeys/README.md
  sdk/keyvault/azkeys/doc.go
  sdk/keyvault/internal/expiring_resource_test.go
Labels: KeyVault

#16107 Incorporate azidentity architecture review feedback
  sdk/azidentity/environment_credential.go
  sdk/azidentity/errors.go
  sdk/azidentity/logging.go
Labels: Azure.Identity

#16105 Sync eng/common directory with azure-sdk-tools for PR 2219
  eng/common/testproxy/docker-start-proxy.ps1
  eng/common/testproxy/test-proxy-docker.yml
Labels: EngSys, Central-EngSys

#16102 [Tables] Updating Documentation
  sdk/data/aztables/README.md
  sdk/data/aztables/example_test.go
Labels: Tables

#16115 Sync eng/common directory with azure-sdk-tools for PR 2223
  eng/common/scripts/stress-testing/deploy-stress-tests.ps1
  eng/common/scripts/stress-testing/find-all-stress-packages.ps1
Labels: EngSys, Central-EngSys

#16091 Add options struct for NewPipeline
  sdk/azcore/CHANGELOG.md
  sdk/azcore/arm/runtime/pipeline.go
  sdk/azcore/arm/runtime/pipeline_test.go
  sdk/azcore/arm/runtime/policy_bearer_token_test.go
  sdk/azcore/arm/runtime/policy_register_rp.go
  sdk/azcore/arm/runtime/policy_register_rp_test.go
  sdk/azcore/arm/runtime/poller_test.go
  sdk/azcore/example_test.go
  sdk/azcore/runtime/pipeline.go
  sdk/azcore/runtime/pipeline_test.go
  sdk/azcore/runtime/policy_bearer_token_test.go
  sdk/azcore/runtime/policy_http_header_test.go
Labels: Azure.Core, blocking-release

#16106 Update azidentity V1 adapter sample
  sdk/samples/azidentity/SDKV1Adapter/example_SDKV1_test.go
  sdk/samples/azidentity/SDKV1Adapter/go.mod
  sdk/samples/azidentity/SDKV1Adapter/go.sum
Labels: Docs, Azure.Identity, test-enhancement

#16114 [Tables] Fixes Transactional Batch for insert merge/replace entity.
  sdk/data/aztables/CHANGELOG.md
  sdk/data/aztables/client.go
  sdk/data/aztables/testdata/recordings/TestBatchAdd/TestBatchAdd_cosmos.json
  sdk/data/aztables/testdata/recordings/TestBatchAdd/TestBatchAdd_storage.json
  sdk/data/aztables/testdata/recordings/TestBatchComplex/TestBatchComplex_cosmos.json
  sdk/data/aztables/testdata/recordings/TestBatchComplex/TestBatchComplex_storage.json
  sdk/data/aztables/testdata/recordings/TestBatchError/TestBatchError_cosmos.json
  sdk/data/aztables/testdata/recordings/TestBatchError/TestBatchError_storage.json
  sdk/data/aztables/testdata/recordings/TestBatchInsert/TestBatchInsert_cosmos.json
  sdk/data/aztables/testdata/recordings/TestBatchInsert/TestBatchInsert_storage.json
  sdk/data/aztables/testdata/recordings/TestBatchMixed/TestBatchMixed_cosmos.json
  sdk/data/aztables/testdata/recordings/TestBatchMixed/TestBatchMixed_storage.json
  sdk/data/aztables/transaction_batch_test.go
  sdk/data/aztables/transactional_batch.go
Labels: Tables

#16122 Increment version for data/aztables releases
  sdk/data/aztables/CHANGELOG.md
  sdk/data/aztables/internal/constants.go
Labels: auto-merge

#16093 Revise azidentity doc comments
  sdk/azidentity/authorization_code_credential.go
  sdk/azidentity/azure_cli_credential.go
  sdk/azidentity/chained_token_credential.go
  sdk/azidentity/client_certificate_credential.go
  sdk/azidentity/client_secret_credential.go
  sdk/azidentity/default_azure_credential.go
  sdk/azidentity/device_code_credential.go
  sdk/azidentity/doc.go
  sdk/azidentity/environment_credential.go
  sdk/azidentity/interactive_browser_credential.go
  sdk/azidentity/managed_identity_credential.go
  sdk/azidentity/username_password_credential.go
Labels: Azure.Identity, blocking-release

#16113 Add Pipelines for keyvault/internal and prepare for release
  eng/config.json
  sdk/keyvault/internal/CHANGELOG.md
  sdk/keyvault/internal/LICENSE.txt
  sdk/keyvault/internal/README.md
  sdk/keyvault/internal/challenge_policy_test.go
  sdk/keyvault/internal/ci.keyvault.yml
  sdk/keyvault/internal/constants.go
Labels: KeyVault

#16123 Increment version for keyvault/internal releases
  sdk/keyvault/internal/CHANGELOG.md
  sdk/keyvault/internal/constants.go
Labels: KeyVault, auto-merge

#16126 Sync eng/common directory with azure-sdk-tools for PR 2240
  eng/common/scripts/get-codeowners.ps1
Labels: EngSys, Central-EngSys

#16127 Add error hint for common version const format mistake
  eng/scripts/Language-Settings.ps1
Labels: Central-EngSys

#16128 Sync eng/common directory with azure-sdk-tools for PR 2242
  eng/common/testproxy/test-proxy-tool.yml
Labels: EngSys, Central-EngSys

#16061 Update azidentity docs
  sdk/azidentity/README.md
  sdk/azidentity/img/AzureCLILogin.png
  sdk/azidentity/img/AzureCLILoginDeviceCode.png
  sdk/azidentity/img/azure-portal-managed-identity.png
  sdk/azidentity/img/devicecode-enable.png
  sdk/azidentity/img/devicecode-permissions.png
  sdk/azidentity/img/interactive-redirecturi.png
  sdk/azidentity/troubleshoot.md
Labels: Docs, Azure.Identity, blocking-release

#16125 [KeyVault] Update azsecrets authentication policy
  sdk/keyvault/azsecrets/CHANGELOG.md
  sdk/keyvault/azsecrets/client.go
  sdk/keyvault/azsecrets/client_test.go
  sdk/keyvault/azsecrets/go.mod
  sdk/keyvault/azsecrets/go.sum
  sdk/keyvault/azsecrets/internal/constants.go
  sdk/keyvault/azsecrets/testdata/recordings/TestBackupSecret.json
  sdk/keyvault/azsecrets/testdata/recordings/TestBeginRecoverDeletedSecret.json
  sdk/keyvault/azsecrets/testdata/recordings/TestDeleteSecret.json
  sdk/keyvault/azsecrets/testdata/recordings/TestListDeletedSecrets.json
  sdk/keyvault/azsecrets/testdata/recordings/TestListSecretVersions.json
  sdk/keyvault/azsecrets/testdata/recordings/TestListSecrets.json
  sdk/keyvault/azsecrets/testdata/recordings/TestPurgeDeletedSecret.json
  sdk/keyvault/azsecrets/testdata/recordings/TestSetGetSecret.json
  sdk/keyvault/azsecrets/testdata/recordings/TestUpdateSecretProperties.json
Labels: KeyVault

#16130 Increment version for keyvault/azsecrets releases
  sdk/keyvault/azsecrets/CHANGELOG.md
  sdk/keyvault/azsecrets/internal/constants.go
Labels: KeyVault, auto-merge

#16134 [Cosmos DB] Fix emulator CI
  sdk/data/azcosmos/ci.yml
Labels: Cosmos

#16136 Increment version for data/azcosmos releases
  sdk/data/azcosmos/CHANGELOG.md
  sdk/data/azcosmos/version.go
Labels: auto-merge

#16069 Update Developer Documentation
  documentation/README.md
  documentation/developer_setup.md
  documentation/release.md
Labels: Docs, auto-merge

#16139 Rename arm/ClientOptions.Host -> .Endpoint
  sdk/azcore/CHANGELOG.md
  sdk/azcore/arm/client_options.go
  sdk/azcore/arm/runtime/pipeline.go
  sdk/azcore/internal/shared/constants.go
Labels: Azure.Core, blocking-release

#16140 Sync eng/common directory with azure-sdk-tools for PR 2249
  eng/common/testproxy/test-proxy-docker.yml
  eng/common/testproxy/test-proxy-tool.yml
Labels: EngSys, Central-EngSys

#16124 [KeyVault] Update go.mod and go.sum
  sdk/keyvault/azkeys/README.md
  sdk/keyvault/azkeys/crypto/constants.go
  sdk/keyvault/azkeys/crypto/crypto_client.go
  sdk/keyvault/azkeys/crypto/crypto_client_test.go
  sdk/keyvault/azkeys/crypto/examples_test.go
  sdk/keyvault/azkeys/crypto/models.go
  sdk/keyvault/azkeys/crypto/testdata/recordings/TestClient_Decrypt.json
  sdk/keyvault/azkeys/crypto/testdata/recordings/TestClient_Encrypt.json
  sdk/keyvault/azkeys/crypto/testdata/recordings/TestClient_SignVerify.json
  sdk/keyvault/azkeys/crypto/testdata/recordings/TestClient_WrapUnwrap.json
  sdk/keyvault/azkeys/crypto/utils_test.go
  sdk/keyvault/azkeys/go.mod
  sdk/keyvault/azkeys/go.sum
Labels: KeyVault

#16147 Increment version for keyvault/azkeys releases
  sdk/keyvault/azkeys/CHANGELOG.md
  sdk/keyvault/azkeys/internal/generated/constants.go
Labels: KeyVault, auto-merge

#16149 Increment version for internal releases
  sdk/internal/CHANGELOG.md
  sdk/internal/version.go
Labels: auto-merge

#16152 Sync eng/common directory with azure-sdk-tools for PR 2247
  eng/common/TestResources/New-TestResources.ps1
  eng/common/TestResources/clouds/AzureChinaCloud.json
  eng/common/TestResources/clouds/AzureCloud.json
  eng/common/TestResources/clouds/AzureUSGovernment.json
Labels: EngSys, Central-EngSys

#16154 Sync eng/common directory with azure-sdk-tools for PR 2259
  eng/common/testproxy/test-proxy-tool.yml
Labels: EngSys, Central-EngSys

#16163 Sync eng/common directory with azure-sdk-tools for PR 2265
  eng/common/scripts/Verify-Links.ps1
Labels: EngSys, Central-EngSys

#16006 Increment version for resourcemanager/eventgrid/armeventgrid releases
  sdk/resourcemanager/eventgrid/armeventgrid/CHANGELOG.md
  sdk/resourcemanager/eventgrid/armeventgrid/zz_generated_constants.go
Labels: auto-merge

#16177 Increment version for resourcemanager/resources/armdeploymentscripts releases
  sdk/resourcemanager/resources/armdeploymentscripts/CHANGELOG.md
  sdk/resourcemanager/resources/armdeploymentscripts/zz_generated_constants.go
Labels: auto-merge

#16094 Release sdk/resourcemanager/batch/armbatch v0.1.0
  sdk/resourcemanager/batch/armbatch/CHANGELOG.md
  sdk/resourcemanager/batch/armbatch/LICENSE.txt
  sdk/resourcemanager/batch/armbatch/README.md
  sdk/resourcemanager/batch/armbatch/autorest.md
  sdk/resourcemanager/batch/armbatch/build.go
  sdk/resourcemanager/batch/armbatch/ci.yml
  sdk/resourcemanager/batch/armbatch/go.mod
  sdk/resourcemanager/batch/armbatch/go.sum
  sdk/resourcemanager/batch/armbatch/go_mod_tidy_hack.go
  sdk/resourcemanager/batch/armbatch/zz_generated_application_client.go
  sdk/resourcemanager/batch/armbatch/zz_generated_applicationpackage_client.go
  sdk/resourcemanager/batch/armbatch/zz_generated_batchaccount_client.go
  sdk/resourcemanager/batch/armbatch/zz_generated_certificate_client.go
  sdk/resourcemanager/batch/armbatch/zz_generated_constants.go
  sdk/resourcemanager/batch/armbatch/zz_generated_location_client.go
  sdk/resourcemanager/batch/armbatch/zz_generated_models.go
  sdk/resourcemanager/batch/armbatch/zz_generated_operations_client.go
  sdk/resourcemanager/batch/armbatch/zz_generated_pagers.go
  sdk/resourcemanager/batch/armbatch/zz_generated_pollers.go
  sdk/resourcemanager/batch/armbatch/zz_generated_pool_client.go
  sdk/resourcemanager/batch/armbatch/zz_generated_privateendpointconnection_client.go
  sdk/resourcemanager/batch/armbatch/zz_generated_privatelinkresource_client.go
  sdk/resourcemanager/batch/armbatch/zz_generated_response_types.go
  sdk/resourcemanager/batch/armbatch/zz_generated_time_rfc3339.go
Labels: Mgmt

#16096 Release sdk/resourcemanager/botservice/armbotservice v0.1.0
  sdk/resourcemanager/botservice/armbotservice/CHANGELOG.md
  sdk/resourcemanager/botservice/armbotservice/LICENSE.txt
  sdk/resourcemanager/botservice/armbotservice/README.md
  sdk/resourcemanager/botservice/armbotservice/autorest.md
  sdk/resourcemanager/botservice/armbotservice/build.go
  sdk/resourcemanager/botservice/armbotservice/ci.yml
  sdk/resourcemanager/botservice/armbotservice/go.mod
  sdk/resourcemanager/botservice/armbotservice/go.sum
  sdk/resourcemanager/botservice/armbotservice/go_mod_tidy_hack.go
  sdk/resourcemanager/botservice/armbotservice/zz_generated_botconnection_client.go
  sdk/resourcemanager/botservice/armbotservice/zz_generated_bots_client.go
  sdk/resourcemanager/botservice/armbotservice/zz_generated_channels_client.go
  sdk/resourcemanager/botservice/armbotservice/zz_generated_constants.go
  sdk/resourcemanager/botservice/armbotservice/zz_generated_directline_client.go
  sdk/resourcemanager/botservice/armbotservice/zz_generated_hostsettings_client.go
  sdk/resourcemanager/botservice/armbotservice/zz_generated_models.go
  sdk/resourcemanager/botservice/armbotservice/zz_generated_operationresults_client.go
  sdk/resourcemanager/botservice/armbotservice/zz_generated_operations_client.go
  sdk/resourcemanager/botservice/armbotservice/zz_generated_pagers.go
  sdk/resourcemanager/botservice/armbotservice/zz_generated_pollers.go
  sdk/resourcemanager/botservice/armbotservice/zz_generated_polymorphic_helpers.go
  sdk/resourcemanager/botservice/armbotservice/zz_generated_privateendpointconnections_client.go
  sdk/resourcemanager/botservice/armbotservice/zz_generated_privatelinkresources_client.go
  sdk/resourcemanager/botservice/armbotservice/zz_generated_response_types.go
  sdk/resourcemanager/botservice/armbotservice/zz_generated_time_rfc3339.go
Labels: Mgmt

#16095 Release sdk/resourcemanager/devtestlabs/armdevtestlabs v0.1.0
  sdk/resourcemanager/devtestlabs/armdevtestlabs/CHANGELOG.md
  sdk/resourcemanager/devtestlabs/armdevtestlabs/LICENSE.txt
  sdk/resourcemanager/devtestlabs/armdevtestlabs/README.md
  sdk/resourcemanager/devtestlabs/armdevtestlabs/autorest.md
  sdk/resourcemanager/devtestlabs/armdevtestlabs/build.go
  sdk/resourcemanager/devtestlabs/armdevtestlabs/ci.yml
  sdk/resourcemanager/devtestlabs/armdevtestlabs/go.mod
  sdk/resourcemanager/devtestlabs/armdevtestlabs/go.sum
  sdk/resourcemanager/devtestlabs/armdevtestlabs/go_mod_tidy_hack.go
  sdk/resourcemanager/devtestlabs/armdevtestlabs/zz_generated_armtemplates_client.go
  sdk/resourcemanager/devtestlabs/armdevtestlabs/zz_generated_artifacts_client.go
  sdk/resourcemanager/devtestlabs/armdevtestlabs/zz_generated_artifactsources_client.go
  sdk/resourcemanager/devtestlabs/armdevtestlabs/zz_generated_constants.go
  sdk/resourcemanager/devtestlabs/armdevtestlabs/zz_generated_costs_client.go
  sdk/resourcemanager/devtestlabs/armdevtestlabs/zz_generated_customimages_client.go
  sdk/resourcemanager/devtestlabs/armdevtestlabs/zz_generated_disks_client.go
  sdk/resourcemanager/devtestlabs/armdevtestlabs/zz_generated_environments_client.go
  sdk/resourcemanager/devtestlabs/armdevtestlabs/zz_generated_formulas_client.go
  sdk/resourcemanager/devtestlabs/armdevtestlabs/zz_generated_galleryimages_client.go
  sdk/resourcemanager/devtestlabs/armdevtestlabs/zz_generated_globalschedules_client.go
  sdk/resourcemanager/devtestlabs/armdevtestlabs/zz_generated_labs_client.go
  sdk/resourcemanager/devtestlabs/armdevtestlabs/zz_generated_models.go
  sdk/resourcemanager/devtestlabs/armdevtestlabs/zz_generated_notificationchannels_client.go
  sdk/resourcemanager/devtestlabs/armdevtestlabs/zz_generated_operations_client.go
  sdk/resourcemanager/devtestlabs/armdevtestlabs/zz_generated_pagers.go
  sdk/resourcemanager/devtestlabs/armdevtestlabs/zz_generated_policies_client.go
  sdk/resourcemanager/devtestlabs/armdevtestlabs/zz_generated_policysets_client.go
  sdk/resourcemanager/devtestlabs/armdevtestlabs/zz_generated_pollers.go
  sdk/resourcemanager/devtestlabs/armdevtestlabs/zz_generated_provideroperations_client.go
  sdk/resourcemanager/devtestlabs/armdevtestlabs/zz_generated_response_types.go
  sdk/resourcemanager/devtestlabs/armdevtestlabs/zz_generated_schedules_client.go
  sdk/resourcemanager/devtestlabs/armdevtestlabs/zz_generated_secrets_client.go
  sdk/resourcemanager/devtestlabs/armdevtestlabs/zz_generated_servicefabrics_client.go
  sdk/resourcemanager/devtestlabs/armdevtestlabs/zz_generated_servicefabricschedules_client.go
  sdk/resourcemanager/devtestlabs/armdevtestlabs/zz_generated_servicerunners_client.go
  sdk/resourcemanager/devtestlabs/armdevtestlabs/zz_generated_time_rfc3339.go
  sdk/resourcemanager/devtestlabs/armdevtestlabs/zz_generated_users_client.go
  sdk/resourcemanager/devtestlabs/armdevtestlabs/zz_generated_virtualmachines_client.go
  sdk/resourcemanager/devtestlabs/armdevtestlabs/zz_generated_virtualmachineschedules_client.go
  sdk/resourcemanager/devtestlabs/armdevtestlabs/zz_generated_virtualnetworks_client.go
Labels: Mgmt

#16097 Release sdk/resourcemanger/advisor/armadvisor v0.1.0
  sdk/resourcemanager/advisor/armadvisor/CHANGELOG.md
  sdk/resourcemanager/advisor/armadvisor/LICENSE.txt
  sdk/resourcemanager/advisor/armadvisor/README.md
  sdk/resourcemanager/advisor/armadvisor/autorest.md
  sdk/resourcemanager/advisor/armadvisor/build.go
  sdk/resourcemanager/advisor/armadvisor/ci.yml
  sdk/resourcemanager/advisor/armadvisor/go.mod
  sdk/resourcemanager/advisor/armadvisor/go.sum
  sdk/resourcemanager/advisor/armadvisor/go_mod_tidy_hack.go
  sdk/resourcemanager/advisor/armadvisor/zz_generated_configurations_client.go
  sdk/resourcemanager/advisor/armadvisor/zz_generated_constants.go
  sdk/resourcemanager/advisor/armadvisor/zz_generated_models.go
  sdk/resourcemanager/advisor/armadvisor/zz_generated_operations_client.go
  sdk/resourcemanager/advisor/armadvisor/zz_generated_pagers.go
  sdk/resourcemanager/advisor/armadvisor/zz_generated_recommendationmetadata_client.go
  sdk/resourcemanager/advisor/armadvisor/zz_generated_recommendations_client.go
  sdk/resourcemanager/advisor/armadvisor/zz_generated_response_types.go
  sdk/resourcemanager/advisor/armadvisor/zz_generated_suppressions_client.go
  sdk/resourcemanager/advisor/armadvisor/zz_generated_time_rfc3339.go
Labels: Mgmt

#16098 Release sdk/resourcemanger/analysisservices/armanalysisservices v0.1.0
  sdk/resourcemanager/analysisservices/armanalysisservices/CHANGELOG.md
  sdk/resourcemanager/analysisservices/armanalysisservices/LICENSE.txt
  sdk/resourcemanager/analysisservices/armanalysisservices/README.md
  sdk/resourcemanager/analysisservices/armanalysisservices/autorest.md
  sdk/resourcemanager/analysisservices/armanalysisservices/build.go
  sdk/resourcemanager/analysisservices/armanalysisservices/ci.yml
  sdk/resourcemanager/analysisservices/armanalysisservices/go.mod
  sdk/resourcemanager/analysisservices/armanalysisservices/go.sum
  sdk/resourcemanager/analysisservices/armanalysisservices/go_mod_tidy_hack.go
  sdk/resourcemanager/analysisservices/armanalysisservices/zz_generated_constants.go
  sdk/resourcemanager/analysisservices/armanalysisservices/zz_generated_models.go
  sdk/resourcemanager/analysisservices/armanalysisservices/zz_generated_operations_client.go
  sdk/resourcemanager/analysisservices/armanalysisservices/zz_generated_pagers.go
  sdk/resourcemanager/analysisservices/armanalysisservices/zz_generated_pollers.go
  sdk/resourcemanager/analysisservices/armanalysisservices/zz_generated_response_types.go
  sdk/resourcemanager/analysisservices/armanalysisservices/zz_generated_servers_client.go
Labels: Mgmt

#16099 Release sdk/resourcemanger/portal/armportal v0.1.0
  sdk/resourcemanager/portal/armportal/CHANGELOG.md
  sdk/resourcemanager/portal/armportal/LICENSE.txt
  sdk/resourcemanager/portal/armportal/README.md
  sdk/resourcemanager/portal/armportal/autorest.md
  sdk/resourcemanager/portal/armportal/build.go
  sdk/resourcemanager/portal/armportal/ci.yml
  sdk/resourcemanager/portal/armportal/go.mod
  sdk/resourcemanager/portal/armportal/go.sum
  sdk/resourcemanager/portal/armportal/go_mod_tidy_hack.go
  sdk/resourcemanager/portal/armportal/zz_generated_constants.go
  sdk/resourcemanager/portal/armportal/zz_generated_dashboards_client.go
  sdk/resourcemanager/portal/armportal/zz_generated_listtenantconfigurationviolations_client.go
  sdk/resourcemanager/portal/armportal/zz_generated_models.go
  sdk/resourcemanager/portal/armportal/zz_generated_operations_client.go
  sdk/resourcemanager/portal/armportal/zz_generated_pagers.go
  sdk/resourcemanager/portal/armportal/zz_generated_polymorphic_helpers.go
  sdk/resourcemanager/portal/armportal/zz_generated_response_types.go
  sdk/resourcemanager/portal/armportal/zz_generated_tenantconfigurations_client.go
Labels: Mgmt

#16166 Sync eng/common directory with azure-sdk-tools for PR 2276
  eng/common/pipelines/templates/jobs/archetype-sdk-tests-generate.yml
Labels: EngSys, Central-EngSys

#16138 [Tables] Adds a test for continuation tokens that also uses a filter
  sdk/data/aztables/client_test.go
  sdk/data/aztables/testdata/recordings/TestContinuationTokensFilters/TestContinuationTokensFilters_cosmos.json
  sdk/data/aztables/testdata/recordings/TestContinuationTokensFilters/TestContinuationTokensFilters_storage.json
Labels: Tables

#16194 Increment version for messaging/azservicebus releases
  sdk/messaging/azservicebus/CHANGELOG.md
  sdk/messaging/azservicebus/internal/constants.go
Labels: auto-merge

#16196 Sync eng/common directory with azure-sdk-tools for PR 2267
  eng/common/scripts/Prepare-Release.ps1
Labels: EngSys, Central-EngSys

#16197 Sync eng/common directory with azure-sdk-tools for PR 2272
  eng/common/scripts/Helpers/Resource-Helpers.ps1
Labels: EngSys, Central-EngSys

#16170 Add recorded managed identity tests
  sdk/azidentity/azidentity_test.go
  sdk/azidentity/client_certificate_credential_test.go
  sdk/azidentity/client_secret_credential_test.go
  sdk/azidentity/environment_credential_test.go
  sdk/azidentity/go.mod
  sdk/azidentity/go.sum
  sdk/azidentity/live_test.go
  sdk/azidentity/managed_identity_credential_test.go
  sdk/azidentity/testdata/recordings/TestManagedIdentityCredential_IMDSClientIDLive.json
  sdk/azidentity/testdata/recordings/TestManagedIdentityCredential_IMDSLive.json
  sdk/azidentity/testdata/recordings/TestManagedIdentityCredential_IMDSResourceIDLive.json
  sdk/azidentity/username_password_credential_test.go
Labels: Azure.Identity, test-enhancement

#16206 Sync eng/common directory with azure-sdk-tools for PR 2290
  eng/common/testproxy/docker-start-proxy.ps1
  eng/common/testproxy/test-proxy-tool.yml
Labels: EngSys, Central-EngSys

#16162 [KeyVault] enable Managed HSM live tests
  eng/config.json
  eng/pipelines/templates/jobs/live.tests.yml
  sdk/keyvault/azkeys/ci.yml
  sdk/keyvault/azkeys/client.go
  sdk/keyvault/azkeys/crypto/crypto_client.go
  sdk/keyvault/azkeys/crypto/crypto_client_test.go
  sdk/keyvault/azkeys/crypto/testdata/recordings/TestClient_Decrypt.json
  sdk/keyvault/azkeys/crypto/utils_test.go
  sdk/keyvault/azkeys/go.mod
  sdk/keyvault/azkeys/go.sum
  sdk/keyvault/azkeys/platform-matrix.json
  sdk/keyvault/azkeys/testdata/recordings/TestBackupKey/TestBackupKey_HSM.json
  sdk/keyvault/azkeys/testdata/recordings/TestBackupKey/TestBackupKey_NON-HSM.json
  sdk/keyvault/azkeys/testdata/recordings/TestCreateECKey/TestCreateECKey_HSM.json
  sdk/keyvault/azkeys/testdata/recordings/TestCreateECKey/TestCreateECKey_NON-HSM.json
  sdk/keyvault/azkeys/testdata/recordings/TestCreateKeyRSA/TestCreateKeyRSA_HSM.json
  sdk/keyvault/azkeys/testdata/recordings/TestCreateKeyRSA/TestCreateKeyRSA_NON-HSM.json
  sdk/keyvault/azkeys/testdata/recordings/TestCreateOCTKey/TestCreateOCTKey_HSM.json
  sdk/keyvault/azkeys/testdata/recordings/TestDeleteKey/TestDeleteKey_HSM.json
  sdk/keyvault/azkeys/testdata/recordings/TestDeleteKey/TestDeleteKey_NON-HSM.json
  sdk/keyvault/azkeys/testdata/recordings/TestGetKey/TestGetKey_HSM.json
  sdk/keyvault/azkeys/testdata/recordings/TestGetKey/TestGetKey_NON-HSM.json
  sdk/keyvault/azkeys/testdata/recordings/TestGetKeyRotationPolicy/TestGetKeyRotationPolicy_NON-HSM.json
  sdk/keyvault/azkeys/testdata/recordings/TestGetRandomBytes/TestGetRandomBytes_HSM.json
  sdk/keyvault/azkeys/testdata/recordings/TestImportKey/TestImportKey_HSM.json
  sdk/keyvault/azkeys/testdata/recordings/TestImportKey/TestImportKey_NON-HSM.json
  sdk/keyvault/azkeys/testdata/recordings/TestListDeletedKeys/TestListDeletedKeys_HSM.json
  sdk/keyvault/azkeys/testdata/recordings/TestListDeletedKeys/TestListDeletedKeys_NON-HSM.json
  sdk/keyvault/azkeys/testdata/recordings/TestListKeyVersions/TestListKeyVersions_HSM.json
  sdk/keyvault/azkeys/testdata/recordings/TestListKeyVersions/TestListKeyVersions_NON-HSM.json
  sdk/keyvault/azkeys/testdata/recordings/TestListKeys/TestListKeys_HSM.json
  sdk/keyvault/azkeys/testdata/recordings/TestListKeys/TestListKeys_NON-HSM.json
  sdk/keyvault/azkeys/testdata/recordings/TestRecoverDeletedKey/TestRecoverDeletedKey_HSM.json
  sdk/keyvault/azkeys/testdata/recordings/TestRecoverDeletedKey/TestRecoverDeletedKey_NON-HSM.json
  sdk/keyvault/azkeys/testdata/recordings/TestRotateKey/TestRotateKey_NON-HSM.json
  sdk/keyvault/azkeys/testdata/recordings/TestUpdateKeyProperties/TestUpdateKeyProperties_HSM.json
  sdk/keyvault/azkeys/testdata/recordings/TestUpdateKeyProperties/TestUpdateKeyProperties_NON-HSM.json
  sdk/keyvault/azkeys/testdata/recordings/TestUpdateKeyRotationPolicy/TestUpdateKeyRotationPolicy_NON-HSM.json
  sdk/keyvault/azkeys/utils_test.go
  sdk/keyvault/internal/challenge_policy.go
Labels: KeyVault

#16101 Release sdk/resourcemanager/hdinsight/armhdinsight v0.1.0
  sdk/resourcemanager/hdinsight/armhdinsight/CHANGELOG.md
  sdk/resourcemanager/hdinsight/armhdinsight/LICENSE.txt
  sdk/resourcemanager/hdinsight/armhdinsight/README.md
  sdk/resourcemanager/hdinsight/armhdinsight/autorest.md
  sdk/resourcemanager/hdinsight/armhdinsight/build.go
  sdk/resourcemanager/hdinsight/armhdinsight/ci.yml
  sdk/resourcemanager/hdinsight/armhdinsight/go.mod
  sdk/resourcemanager/hdinsight/armhdinsight/go.sum
  sdk/resourcemanager/hdinsight/armhdinsight/go_mod_tidy_hack.go
  sdk/resourcemanager/hdinsight/armhdinsight/zz_generated_applications_client.go
  sdk/resourcemanager/hdinsight/armhdinsight/zz_generated_clusters_client.go
  sdk/resourcemanager/hdinsight/armhdinsight/zz_generated_configurations_client.go
  sdk/resourcemanager/hdinsight/armhdinsight/zz_generated_constants.go
  sdk/resourcemanager/hdinsight/armhdinsight/zz_generated_extensions_client.go
  sdk/resourcemanager/hdinsight/armhdinsight/zz_generated_locations_client.go
  sdk/resourcemanager/hdinsight/armhdinsight/zz_generated_models.go
  sdk/resourcemanager/hdinsight/armhdinsight/zz_generated_operations_client.go
  sdk/resourcemanager/hdinsight/armhdinsight/zz_generated_pagers.go
  sdk/resourcemanager/hdinsight/armhdinsight/zz_generated_pollers.go
  sdk/resourcemanager/hdinsight/armhdinsight/zz_generated_privateendpointconnections_client.go
  sdk/resourcemanager/hdinsight/armhdinsight/zz_generated_privatelinkresources_client.go
  sdk/resourcemanager/hdinsight/armhdinsight/zz_generated_response_types.go
  sdk/resourcemanager/hdinsight/armhdinsight/zz_generated_scriptactions_client.go
  sdk/resourcemanager/hdinsight/armhdinsight/zz_generated_scriptexecutionhistory_client.go
  sdk/resourcemanager/hdinsight/armhdinsight/zz_generated_time_rfc3339.go
  sdk/resourcemanager/hdinsight/armhdinsight/zz_generated_virtualmachines_client.go
Labels: Mgmt

#16100 Release sdk/resourcemanager/sqlvirtualmachine/armsqlvirtualmachine v0.1.0
  sdk/resourcemanager/sqlvirtualmachine/armsqlvirtualmachine/CHANGELOG.md
  sdk/resourcemanager/sqlvirtualmachine/armsqlvirtualmachine/LICENSE.txt
  sdk/resourcemanager/sqlvirtualmachine/armsqlvirtualmachine/README.md
  sdk/resourcemanager/sqlvirtualmachine/armsqlvirtualmachine/autorest.md
  sdk/resourcemanager/sqlvirtualmachine/armsqlvirtualmachine/build.go
  sdk/resourcemanager/sqlvirtualmachine/armsqlvirtualmachine/ci.yml
  sdk/resourcemanager/sqlvirtualmachine/armsqlvirtualmachine/go.mod
  sdk/resourcemanager/sqlvirtualmachine/armsqlvirtualmachine/go.sum
  sdk/resourcemanager/sqlvirtualmachine/armsqlvirtualmachine/go_mod_tidy_hack.go
  sdk/resourcemanager/sqlvirtualmachine/armsqlvirtualmachine/zz_generated_availabilitygrouplisteners_client.go
  sdk/resourcemanager/sqlvirtualmachine/armsqlvirtualmachine/zz_generated_constants.go
  sdk/resourcemanager/sqlvirtualmachine/armsqlvirtualmachine/zz_generated_models.go
  sdk/resourcemanager/sqlvirtualmachine/armsqlvirtualmachine/zz_generated_operations_client.go
  sdk/resourcemanager/sqlvirtualmachine/armsqlvirtualmachine/zz_generated_pagers.go
  sdk/resourcemanager/sqlvirtualmachine/armsqlvirtualmachine/zz_generated_pollers.go
  sdk/resourcemanager/sqlvirtualmachine/armsqlvirtualmachine/zz_generated_response_types.go
  sdk/resourcemanager/sqlvirtualmachine/armsqlvirtualmachine/zz_generated_sqlvirtualmachinegroups_client.go
  sdk/resourcemanager/sqlvirtualmachine/armsqlvirtualmachine/zz_generated_sqlvirtualmachines_client.go
Labels: Mgmt

#16222 Sync eng/common directory with azure-sdk-tools for PR 2321
  eng/common/testproxy/docker-start-proxy.ps1
  eng/common/testproxy/test-proxy-tool.yml
  sdk/internal/recording/sanitizer.go
Labels: EngSys, Central-EngSys

#16227 Sync eng/common directory with azure-sdk-tools for PR 2306
  eng/common/scripts/Helpers/Resource-Helpers.ps1
Labels: EngSys, Central-EngSys

#16208 [Internal] updating docs and adding samples for internal package
  sdk/internal/recording/README.md
  sdk/internal/recording/example_test.go
Labels: MQ

#16242 Sync eng/common directory with azure-sdk-tools for PR 2322
  eng/common/scripts/get-codeowners.ps1
Labels: EngSys, Central-EngSys

#16178 Increment version for resourcemanager/resources/armlinks releases
  sdk/resourcemanager/resources/armlinks/CHANGELOG.md
  sdk/resourcemanager/resources/armlinks/zz_generated_constants.go
Labels: auto-merge

#16179 Increment version for resourcemanager/resources/armtemplatespecs releases
  sdk/resourcemanager/resources/armtemplatespecs/CHANGELOG.md
  sdk/resourcemanager/resources/armtemplatespecs/zz_generated_constants.go
Labels: auto-merge

#16244 Sync eng/common directory with azure-sdk-tools for PR 2333
  eng/common/testproxy/docker-start-proxy.ps1
Labels: EngSys, Central-EngSys

#16257 Sync eng/common directory with azure-sdk-tools for PR 2086
  eng/common/pipelines/templates/steps/get-pr-owners.yml
  eng/common/scripts/Update-DocsMsMetadata.ps1
  eng/common/scripts/get-codeowners.ps1
Labels: EngSys, Central-EngSys

#16294 refresh dependencies for ring 0 RPs with examples
  sdk/resourcemanager/compute/armcompute/CHANGELOG.md
  sdk/resourcemanager/compute/armcompute/autorest.md
  sdk/resourcemanager/compute/armcompute/go.mod
  sdk/resourcemanager/compute/armcompute/go.sum
  sdk/resourcemanager/keyvault/armkeyvault/CHANGELOG.md
  sdk/resourcemanager/keyvault/armkeyvault/autorest.md
  sdk/resourcemanager/keyvault/armkeyvault/go.mod
  sdk/resourcemanager/keyvault/armkeyvault/go.sum
  sdk/resourcemanager/network/armnetwork/CHANGELOG.md
  sdk/resourcemanager/network/armnetwork/autorest.md
  sdk/resourcemanager/network/armnetwork/go.mod
  sdk/resourcemanager/network/armnetwork/go.sum
  sdk/resourcemanager/resources/armresources/CHANGELOG.md
  sdk/resourcemanager/resources/armresources/autorest.md
  sdk/resourcemanager/resources/armresources/go.mod
  sdk/resourcemanager/resources/armresources/go.sum
  sdk/resourcemanager/storage/armstorage/CHANGELOG.md
  sdk/resourcemanager/storage/armstorage/autorest.md
  sdk/resourcemanager/storage/armstorage/go.mod
  sdk/resourcemanager/storage/armstorage/go.sum
Labels: Mgmt

#16290 fix a few azkey links
  sdk/keyvault/azkeys/README.md
Labels: KeyVault

#16320 [Tables] Adding azurite test for Tables
  sdk/data/aztables/README.md
  sdk/data/aztables/client_test.go
Labels: Tables

#16325 Sync eng/common directory with azure-sdk-tools for PR 2348
  eng/common/scripts/get-codeowners.ps1
Labels: EngSys, Central-EngSys

#15654 [ARMCore] resource identifiers
  sdk/azcore/arm/example_resource_identifier_test.go
  sdk/azcore/arm/resource_identifier.go
  sdk/azcore/arm/resource_identifier_test.go
  sdk/azcore/arm/resource_type.go
  sdk/azcore/arm/resource_type_test.go
Labels: Mgmt, Azure.Core

#16324 Sync eng/common directory with azure-sdk-tools for PR 2331
  eng/common/scripts/stress-testing/deploy-stress-tests.ps1
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: EngSys, Central-EngSys
