Repository Azure/azure-sdk-for-go, pull requests merged in 2022-06, with the labels that each got.

#18286 Remove trailing slashes from parsed vault URLs
  sdk/keyvault/internal/CHANGELOG.md
  sdk/keyvault/internal/constants.go
  sdk/keyvault/internal/parse.go
  sdk/keyvault/internal/parse_test.go
Labels: KeyVault, Client

#18257 Sync eng/common directory with azure-sdk-tools for PR 3381
  eng/common/pipelines/templates/steps/sparse-checkout.yml
Labels: EngSys, Central-EngSys

#18306 Sync eng/common directory with azure-sdk-tools for PR 3392
  eng/common/scripts/job-matrix/job-matrix-functions.ps1
  eng/common/scripts/job-matrix/tests/job-matrix-functions.modification.tests.ps1
Labels: EngSys, Central-EngSys

#18307 Override live test location default to westus
  eng/pipelines/templates/jobs/archetype-sdk-client.yml
Labels: Central-EngSys

#18313 Prepare azcore v1.1.0 for release
  sdk/azcore/CHANGELOG.md
  sdk/azcore/internal/shared/constants.go
Labels: Azure.Core

#18315 Increment version for azcore releases
  sdk/azcore/CHANGELOG.md
  sdk/azcore/internal/shared/constants.go
Labels: auto-merge

#18312 Prepare azidentity 1.0.1 release
  sdk/azidentity/CHANGELOG.md
Labels: Azure.Identity

#18318 Prevent azkeys tests incorrectly targeting MHSM
  sdk/keyvault/azkeys/client_test.go
  sdk/keyvault/azkeys/utils_test.go
Labels: KeyVault, Client, test-reliability

#17099 azidentity: environmnet credential add supports for the cert password
  sdk/azidentity/README.md
  sdk/azidentity/environment_credential.go
  sdk/azidentity/environment_credential_test.go
Labels: Client, Azure.Identity

#18328 Increment version for azidentity releases
  sdk/azidentity/CHANGELOG.md
  sdk/azidentity/version.go
Labels: auto-merge

#18330 Increment version for messaging/azservicebus releases
  sdk/messaging/azservicebus/CHANGELOG.md
  sdk/messaging/azservicebus/internal/constants.go
Labels: auto-merge

#18331 Prepare azidentity 1.1.0 release
  sdk/azidentity/CHANGELOG.md
  sdk/azidentity/azidentity.go
  sdk/azidentity/client_certificate_credential.go
  sdk/azidentity/client_certificate_credential_test.go
  sdk/azidentity/client_secret_credential.go
  sdk/azidentity/testdata/recordings/TestClientCertificateCredential_Regional.json
  sdk/azidentity/version.go
Labels: Azure.Identity

#18329 Prepare azidentity v1.2.0-beta.1 release
  sdk/azidentity/CHANGELOG.md
  sdk/azidentity/version.go
Labels: Azure.Identity

#18334 Increment version for azidentity releases
  sdk/azidentity/CHANGELOG.md
  sdk/azidentity/version.go
Labels: auto-merge

#18228 [Release] sdk/resourcemanager/servicebus/armservicebus/2.0.0-beta.1
  sdk/resourcemanager/servicebus/armservicebus/CHANGELOG.md
  sdk/resourcemanager/servicebus/armservicebus/autorest.md
  sdk/resourcemanager/servicebus/armservicebus/go.mod
  sdk/resourcemanager/servicebus/armservicebus/ze_generated_example_disasterrecoveryconfigs_client_test.go
  sdk/resourcemanager/servicebus/armservicebus/ze_generated_example_migrationconfigs_client_test.go
  sdk/resourcemanager/servicebus/armservicebus/ze_generated_example_namespaces_client_test.go
  sdk/resourcemanager/servicebus/armservicebus/ze_generated_example_operations_client_test.go
  sdk/resourcemanager/servicebus/armservicebus/ze_generated_example_privateendpointconnections_client_test.go
  sdk/resourcemanager/servicebus/armservicebus/ze_generated_example_privatelinkresources_client_test.go
  sdk/resourcemanager/servicebus/armservicebus/ze_generated_example_queues_client_test.go
  sdk/resourcemanager/servicebus/armservicebus/ze_generated_example_rules_client_test.go
  sdk/resourcemanager/servicebus/armservicebus/ze_generated_example_subscriptions_client_test.go
  sdk/resourcemanager/servicebus/armservicebus/ze_generated_example_topics_client_test.go
  sdk/resourcemanager/servicebus/armservicebus/zz_generated_constants.go
  sdk/resourcemanager/servicebus/armservicebus/zz_generated_disasterrecoveryconfigs_client.go
  sdk/resourcemanager/servicebus/armservicebus/zz_generated_migrationconfigs_client.go
  sdk/resourcemanager/servicebus/armservicebus/zz_generated_models.go
  sdk/resourcemanager/servicebus/armservicebus/zz_generated_models_serde.go
  sdk/resourcemanager/servicebus/armservicebus/zz_generated_namespaces_client.go
  sdk/resourcemanager/servicebus/armservicebus/zz_generated_operations_client.go
  sdk/resourcemanager/servicebus/armservicebus/zz_generated_privateendpointconnections_client.go
  sdk/resourcemanager/servicebus/armservicebus/zz_generated_privatelinkresources_client.go
  sdk/resourcemanager/servicebus/armservicebus/zz_generated_queues_client.go
  sdk/resourcemanager/servicebus/armservicebus/zz_generated_rules_client.go
  sdk/resourcemanager/servicebus/armservicebus/zz_generated_subscriptions_client.go
  sdk/resourcemanager/servicebus/armservicebus/zz_generated_topics_client.go
Labels: breaking-change

#18230 [Release] sdk/resourcemanager/desktopvirtualization/armdesktopvirtualization/2.0.0-beta.1
  sdk/resourcemanager/desktopvirtualization/armdesktopvirtualization/CHANGELOG.md
  sdk/resourcemanager/desktopvirtualization/armdesktopvirtualization/autorest.md
  sdk/resourcemanager/desktopvirtualization/armdesktopvirtualization/go.mod
  sdk/resourcemanager/desktopvirtualization/armdesktopvirtualization/ze_generated_example_applicationgroups_client_test.go
  sdk/resourcemanager/desktopvirtualization/armdesktopvirtualization/ze_generated_example_applications_client_test.go
  sdk/resourcemanager/desktopvirtualization/armdesktopvirtualization/ze_generated_example_desktops_client_test.go
  sdk/resourcemanager/desktopvirtualization/armdesktopvirtualization/ze_generated_example_hostpools_client_test.go
  sdk/resourcemanager/desktopvirtualization/armdesktopvirtualization/ze_generated_example_msiximages_client_test.go
  sdk/resourcemanager/desktopvirtualization/armdesktopvirtualization/ze_generated_example_msixpackages_client_test.go
  sdk/resourcemanager/desktopvirtualization/armdesktopvirtualization/ze_generated_example_operations_client_test.go
  sdk/resourcemanager/desktopvirtualization/armdesktopvirtualization/ze_generated_example_privateendpointconnections_client_test.go
  sdk/resourcemanager/desktopvirtualization/armdesktopvirtualization/ze_generated_example_privatelinkresources_client_test.go
  sdk/resourcemanager/desktopvirtualization/armdesktopvirtualization/ze_generated_example_scalingplans_client_test.go
  sdk/resourcemanager/desktopvirtualization/armdesktopvirtualization/ze_generated_example_sessionhosts_client_test.go
  sdk/resourcemanager/desktopvirtualization/armdesktopvirtualization/ze_generated_example_startmenuitems_client_test.go
  sdk/resourcemanager/desktopvirtualization/armdesktopvirtualization/ze_generated_example_usersessions_client_test.go
  sdk/resourcemanager/desktopvirtualization/armdesktopvirtualization/ze_generated_example_workspaces_client_test.go
  sdk/resourcemanager/desktopvirtualization/armdesktopvirtualization/zz_generated_applicationgroups_client.go
  sdk/resourcemanager/desktopvirtualization/armdesktopvirtualization/zz_generated_applications_client.go
  sdk/resourcemanager/desktopvirtualization/armdesktopvirtualization/zz_generated_constants.go
  sdk/resourcemanager/desktopvirtualization/armdesktopvirtualization/zz_generated_desktops_client.go
  sdk/resourcemanager/desktopvirtualization/armdesktopvirtualization/zz_generated_hostpools_client.go
  sdk/resourcemanager/desktopvirtualization/armdesktopvirtualization/zz_generated_models.go
  sdk/resourcemanager/desktopvirtualization/armdesktopvirtualization/zz_generated_models_serde.go
  sdk/resourcemanager/desktopvirtualization/armdesktopvirtualization/zz_generated_msiximages_client.go
  sdk/resourcemanager/desktopvirtualization/armdesktopvirtualization/zz_generated_msixpackages_client.go
  sdk/resourcemanager/desktopvirtualization/armdesktopvirtualization/zz_generated_operations_client.go
  sdk/resourcemanager/desktopvirtualization/armdesktopvirtualization/zz_generated_privateendpointconnections_client.go
  sdk/resourcemanager/desktopvirtualization/armdesktopvirtualization/zz_generated_privatelinkresources_client.go
  sdk/resourcemanager/desktopvirtualization/armdesktopvirtualization/zz_generated_response_types.go
  sdk/resourcemanager/desktopvirtualization/armdesktopvirtualization/zz_generated_scalingplans_client.go
  sdk/resourcemanager/desktopvirtualization/armdesktopvirtualization/zz_generated_sessionhosts_client.go
  sdk/resourcemanager/desktopvirtualization/armdesktopvirtualization/zz_generated_startmenuitems_client.go
  sdk/resourcemanager/desktopvirtualization/armdesktopvirtualization/zz_generated_usersessions_client.go
  sdk/resourcemanager/desktopvirtualization/armdesktopvirtualization/zz_generated_workspaces_client.go
Labels: breaking-change

#18231 [Release] sdk/resourcemanager/hybridnetwork/armhybridnetwork/2.0.0-beta.1
  sdk/resourcemanager/hybridnetwork/armhybridnetwork/CHANGELOG.md
  sdk/resourcemanager/hybridnetwork/armhybridnetwork/autorest.md
  sdk/resourcemanager/hybridnetwork/armhybridnetwork/go.mod
  sdk/resourcemanager/hybridnetwork/armhybridnetwork/ze_generated_example_devices_client_test.go
  sdk/resourcemanager/hybridnetwork/armhybridnetwork/ze_generated_example_networkfunctions_client_test.go
  sdk/resourcemanager/hybridnetwork/armhybridnetwork/ze_generated_example_networkfunctionvendors_client_test.go
  sdk/resourcemanager/hybridnetwork/armhybridnetwork/ze_generated_example_networkfunctionvendorskus_client_test.go
  sdk/resourcemanager/hybridnetwork/armhybridnetwork/ze_generated_example_operations_client_test.go
  sdk/resourcemanager/hybridnetwork/armhybridnetwork/ze_generated_example_roleinstances_client_test.go
  sdk/resourcemanager/hybridnetwork/armhybridnetwork/ze_generated_example_vendornetworkfunctions_client_test.go
  sdk/resourcemanager/hybridnetwork/armhybridnetwork/ze_generated_example_vendors_client_test.go
  sdk/resourcemanager/hybridnetwork/armhybridnetwork/ze_generated_example_vendorskupreview_client_test.go
  sdk/resourcemanager/hybridnetwork/armhybridnetwork/ze_generated_example_vendorskus_client_test.go
  sdk/resourcemanager/hybridnetwork/armhybridnetwork/zz_generated_constants.go
  sdk/resourcemanager/hybridnetwork/armhybridnetwork/zz_generated_devices_client.go
  sdk/resourcemanager/hybridnetwork/armhybridnetwork/zz_generated_models.go
  sdk/resourcemanager/hybridnetwork/armhybridnetwork/zz_generated_models_serde.go
  sdk/resourcemanager/hybridnetwork/armhybridnetwork/zz_generated_networkfunctions_client.go
  sdk/resourcemanager/hybridnetwork/armhybridnetwork/zz_generated_networkfunctionvendors_client.go
  sdk/resourcemanager/hybridnetwork/armhybridnetwork/zz_generated_networkfunctionvendorskus_client.go
  sdk/resourcemanager/hybridnetwork/armhybridnetwork/zz_generated_operations_client.go
  sdk/resourcemanager/hybridnetwork/armhybridnetwork/zz_generated_response_types.go
  sdk/resourcemanager/hybridnetwork/armhybridnetwork/zz_generated_roleinstances_client.go
  sdk/resourcemanager/hybridnetwork/armhybridnetwork/zz_generated_vendornetworkfunctions_client.go
  sdk/resourcemanager/hybridnetwork/armhybridnetwork/zz_generated_vendors_client.go
  sdk/resourcemanager/hybridnetwork/armhybridnetwork/zz_generated_vendorskupreview_client.go
  sdk/resourcemanager/hybridnetwork/armhybridnetwork/zz_generated_vendorskus_client.go
Labels: breaking-change

#18402 Sync eng/common directory with azure-sdk-tools for PR 3433
  eng/common/pipelines/templates/steps/create-apireview.yml
Labels: EngSys, Central-EngSys

#18410 Sync eng/common directory with azure-sdk-tools for PR 3386
  eng/common/docgeneration/templates/matthews/partials/class.header.tmpl.partial
  eng/common/docgeneration/templates/matthews/partials/class.tmpl.partial
Labels: EngSys, Central-EngSys

#18405 Sync eng/common directory with azure-sdk-tools for PR 3402
  eng/common/pipelines/templates/steps/credscan.yml
Labels: EngSys, Central-EngSys

#18429 Increment version for data/aztables releases
  sdk/data/aztables/CHANGELOG.md
  sdk/data/aztables/internal/constants.go
Labels: auto-merge

#18431 Sync eng/common directory with azure-sdk-tools for PR 3457
  eng/common/TestResources/New-TestResources.ps1
  eng/common/TestResources/Remove-TestResources.ps1
  eng/common/TestResources/deploy-test-resources.yml
  eng/common/TestResources/remove-test-resources.yml
Labels: EngSys, Central-EngSys

#18440 Sync eng/common directory with azure-sdk-tools for PR 3453
  eng/common/scripts/Verify-Resource-Ref.ps1
Labels: EngSys, Central-EngSys

#18232 [Release] sdk/resourcemanager/iotcentral/armiotcentral/2.0.0-beta.1
  sdk/resourcemanager/iotcentral/armiotcentral/CHANGELOG.md
  sdk/resourcemanager/iotcentral/armiotcentral/README.md
  sdk/resourcemanager/iotcentral/armiotcentral/apps_client.go
  sdk/resourcemanager/iotcentral/armiotcentral/apps_client_example_test.go
  sdk/resourcemanager/iotcentral/armiotcentral/autorest.md
  sdk/resourcemanager/iotcentral/armiotcentral/constants.go
  sdk/resourcemanager/iotcentral/armiotcentral/go.mod
  sdk/resourcemanager/iotcentral/armiotcentral/go.sum
  sdk/resourcemanager/iotcentral/armiotcentral/models.go
  sdk/resourcemanager/iotcentral/armiotcentral/models_serde.go
  sdk/resourcemanager/iotcentral/armiotcentral/operations_client.go
  sdk/resourcemanager/iotcentral/armiotcentral/operations_client_example_test.go
  sdk/resourcemanager/iotcentral/armiotcentral/privateendpointconnections_client.go
  sdk/resourcemanager/iotcentral/armiotcentral/privateendpointconnections_client_example_test.go
  sdk/resourcemanager/iotcentral/armiotcentral/privatelinks_client.go
  sdk/resourcemanager/iotcentral/armiotcentral/privatelinks_client_example_test.go
  sdk/resourcemanager/iotcentral/armiotcentral/response_types.go
  sdk/resourcemanager/iotcentral/armiotcentral/time_rfc3339.go
  sdk/resourcemanager/iotcentral/armiotcentral/zz_generated_constants.go
  sdk/resourcemanager/iotcentral/armiotcentral/zz_generated_models.go
  sdk/resourcemanager/iotcentral/armiotcentral/zz_generated_models_serde.go
Labels: Do Not Merge, breaking-change

#18466 Increment version for resourcemanager/internal releases
  sdk/resourcemanager/internal/CHANGELOG.md
  sdk/resourcemanager/internal/version.go
Labels: auto-merge

#18470 Fix broken aka links
  documentation/new-version-quickstart.md
  sdk/resourcemanager/compute/armcompute/README.md
Labels: Central-EngSys

#18476 [Release] sdk/resourcemanager/mediaservices/armmediaservices/3.0.0
  sdk/resourcemanager/mediaservices/armmediaservices/CHANGELOG.md
  sdk/resourcemanager/mediaservices/armmediaservices/accountfilters_client_example_test.go
  sdk/resourcemanager/mediaservices/armmediaservices/assetfilters_client_example_test.go
  sdk/resourcemanager/mediaservices/armmediaservices/assets_client_example_test.go
  sdk/resourcemanager/mediaservices/armmediaservices/assettrackoperationresults_client.go
  sdk/resourcemanager/mediaservices/armmediaservices/assettrackoperationresults_client_example_test.go
  sdk/resourcemanager/mediaservices/armmediaservices/assettrackoperationstatuses_client.go
  sdk/resourcemanager/mediaservices/armmediaservices/assettrackoperationstatuses_client_example_test.go
  sdk/resourcemanager/mediaservices/armmediaservices/autorest.md
  sdk/resourcemanager/mediaservices/armmediaservices/constants.go
  sdk/resourcemanager/mediaservices/armmediaservices/contentkeypolicies_client_example_test.go
  sdk/resourcemanager/mediaservices/armmediaservices/go.mod
  sdk/resourcemanager/mediaservices/armmediaservices/jobs_client_example_test.go
  sdk/resourcemanager/mediaservices/armmediaservices/liveevents_client_example_test.go
  sdk/resourcemanager/mediaservices/armmediaservices/liveoutputs_client_example_test.go
  sdk/resourcemanager/mediaservices/armmediaservices/locations_client_example_test.go
  sdk/resourcemanager/mediaservices/armmediaservices/mediaserviceoperationresults_client.go
  sdk/resourcemanager/mediaservices/armmediaservices/mediaserviceoperationstatuses_client.go
  sdk/resourcemanager/mediaservices/armmediaservices/mediaservices_client_example_test.go
  sdk/resourcemanager/mediaservices/armmediaservices/mediaservicesoperationresults_client_example_test.go
  sdk/resourcemanager/mediaservices/armmediaservices/mediaservicesoperationstatuses_client_example_test.go
  sdk/resourcemanager/mediaservices/armmediaservices/models.go
  sdk/resourcemanager/mediaservices/armmediaservices/operationresults_client.go
  sdk/resourcemanager/mediaservices/armmediaservices/operations_client_example_test.go
  sdk/resourcemanager/mediaservices/armmediaservices/operationstatuses_client.go
  sdk/resourcemanager/mediaservices/armmediaservices/privateendpointconnections_client_example_test.go
  sdk/resourcemanager/mediaservices/armmediaservices/privatelinkresources_client_example_test.go
  sdk/resourcemanager/mediaservices/armmediaservices/response_types.go
  sdk/resourcemanager/mediaservices/armmediaservices/streamingendpoints_client_example_test.go
  sdk/resourcemanager/mediaservices/armmediaservices/streaminglocators_client_example_test.go
  sdk/resourcemanager/mediaservices/armmediaservices/streamingpolicies_client_example_test.go
  sdk/resourcemanager/mediaservices/armmediaservices/tracks_client_example_test.go
  sdk/resourcemanager/mediaservices/armmediaservices/transforms_client_example_test.go
Labels: breaking-change

#18468 Move api review step into analyze job. Block on apiview failures/missing approvals
  eng/pipelines/templates/steps/analyze.yml
  eng/pipelines/templates/steps/build-test.yml
Labels: Central-EngSys

#18488 Sync eng/common directory with azure-sdk-tools for PR 3509
  eng/common/pipelines/templates/steps/cosmos-emulator.yml
Labels: EngSys, Central-EngSys

#18491 Sync eng/common directory with azure-sdk-tools for PR 3510
  eng/common/pipelines/templates/steps/verify-readme.yml
  eng/common/scripts/Verify-Readme.ps1
Labels: EngSys, Central-EngSys

#18496 Sync eng/common directory with azure-sdk-tools for PR 3491
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: EngSys, Central-EngSys

#18497 Prepare azcore 1.1.1 for release
  sdk/azcore/CHANGELOG.md
Labels: Azure.Core

#18459 Log more information when MHSM provisioning fails
  sdk/keyvault/azkeys/test-resources-post.ps1
Labels: KeyVault, Client, test-enhancement
