Repository Azure/azure-sdk-for-go, pull requests merged in 2022-10, with the labels that each got.

#19208 expand examples
  sdk/monitor/azquery/README.md
  sdk/monitor/azquery/example_test.go
Labels: Docs, Client, Monitor - Query

#19278 JoinPaths: don't add "/" before the query string
  sdk/azcore/CHANGELOG.md
  sdk/azcore/runtime/request.go
  sdk/azcore/runtime/request_test.go
  sdk/storage/azblob/CHANGELOG.md
  sdk/storage/azblob/blob/client.go
  sdk/storage/azblob/container/client.go
  sdk/storage/azblob/service/client.go
Labels: customer-reported

#19293 Improve doc comments for client constructors
  sdk/storage/azblob/CHANGELOG.md
  sdk/storage/azblob/appendblob/client.go
  sdk/storage/azblob/blob/client.go
  sdk/storage/azblob/blockblob/client.go
  sdk/storage/azblob/client.go
  sdk/storage/azblob/container/client.go
  sdk/storage/azblob/lease/blob_client.go
  sdk/storage/azblob/lease/container_client.go
  sdk/storage/azblob/pageblob/client.go
  sdk/storage/azblob/service/client.go
Labels: Storage

#19296 Sync eng/common directory with azure-sdk-tools for PR 4315
  eng/common/testproxy/target_version.txt
Labels: EngSys, Central-EngSys

#19300 Increment version for azcore releases
  sdk/azcore/CHANGELOG.md
  sdk/azcore/internal/shared/constants.go
Labels: auto-merge

#19301 Sync eng/common directory with azure-sdk-tools for PR 4311
  eng/common/scripts/Verify-Links.ps1
Labels: EngSys, Central-EngSys

#19299 Updating SAS Version
  sdk/storage/azblob/CHANGELOG.md
  sdk/storage/azblob/go.mod
  sdk/storage/azblob/go.sum
  sdk/storage/azblob/internal/exported/user_delegation_credential.go
  sdk/storage/azblob/sas/query_params.go
  sdk/storage/azblob/service/client_test.go
  sdk/storage/azblob/testdata/perf/go.mod
  sdk/storage/azblob/testdata/perf/go.sum
Labels: Storage

#19303 Prepare for next release
  sdk/storage/azblob/CHANGELOG.md
Labels: Storage

#19307 Consolidate common MSAL options
  sdk/azidentity/azidentity.go
  sdk/azidentity/client_assertion_credential.go
  sdk/azidentity/client_certificate_credential.go
  sdk/azidentity/client_secret_credential.go
  sdk/azidentity/device_code_credential.go
  sdk/azidentity/interactive_browser_credential.go
  sdk/azidentity/username_password_credential.go
Labels: Azure.Identity

#19242 Add constants for azidentity environment variables
  sdk/azidentity/azidentity.go
  sdk/azidentity/default_azure_credential_test.go
  sdk/azidentity/environment_credential.go
  sdk/azidentity/environment_credential_test.go
Labels: Azure.Identity

#19325 Prepare azidentity v1.2.0-beta.3 for release
  sdk/azidentity/CHANGELOG.md
Labels: Azure.Identity

#19331 Increment version for storage/azblob releases
  sdk/storage/azblob/CHANGELOG.md
  sdk/storage/azblob/internal/exported/version.go
Labels: Storage, auto-merge

#19334 Increment version for azidentity releases
  sdk/azidentity/CHANGELOG.md
  sdk/azidentity/version.go
Labels: auto-merge

#19332 Fix race condition in test
  sdk/storage/azblob/service/client_test.go
Labels: Storage

#19308 Sync eng/common directory with azure-sdk-tools for PR 4341
  eng/common/testproxy/target_version.txt
Labels: EngSys, Central-EngSys

#19335 Increment version for monitor/azquery releases
  sdk/monitor/azquery/CHANGELOG.md
  sdk/monitor/azquery/version.go
Labels: auto-merge

#19346 Sync eng/common directory with azure-sdk-tools for PR 4372
  eng/common/scripts/get-codeowners.ps1
Labels: EngSys, Central-EngSys

#19363 Enable users to override client default API versions
  sdk/azcore/CHANGELOG.md
  sdk/azcore/arm/runtime/pipeline.go
  sdk/azcore/arm/runtime/pipeline_test.go
  sdk/azcore/internal/shared/constants.go
  sdk/azcore/policy/policy.go
  sdk/azcore/runtime/pipeline.go
  sdk/azcore/runtime/policy_api_version.go
  sdk/azcore/runtime/policy_api_version_test.go
Labels: Client, Mgmt, Azure.Core

#19207 Tests for undeleting blob versions and snapshots
  sdk/storage/azblob/appendblob/client_test.go
  sdk/storage/azblob/blockblob/client_test.go
  sdk/storage/azblob/container/client_test.go
  sdk/storage/azblob/internal/testcommon/clients_auth.go
  sdk/storage/azblob/pageblob/client_test.go
  sdk/storage/azblob/service/client_test.go
  sdk/storage/azblob/test-resources.json
  sdk/storage/azblob/testdata/recordings/Test/TestBlockBlobSetTierOnSnapshots.json
  sdk/storage/azblob/testdata/recordings/Test/TestBlockBlobSetTierOnVersions.json
  sdk/storage/azblob/testdata/recordings/Test/TestContainerRestore.json
  sdk/storage/azblob/testdata/recordings/Test/TestContainerRestoreFailures.json
  sdk/storage/azblob/testdata/recordings/Test/TestContainerUndelete.json
  sdk/storage/azblob/testdata/recordings/Test/TestUndeleteAppendBlobSnapshot.json
  sdk/storage/azblob/testdata/recordings/Test/TestUndeleteAppendBlobVersion.json
  sdk/storage/azblob/testdata/recordings/Test/TestUndeleteBlockBlobSnapshot.json
  sdk/storage/azblob/testdata/recordings/Test/TestUndeleteBlockBlobVersion.json
  sdk/storage/azblob/testdata/recordings/Test/TestUndeletePageBlobSnapshot.json
  sdk/storage/azblob/testdata/recordings/Test/TestUndeletePageBlobVersion.json
Labels: Storage

#19375 Increment version for messaging/azeventhubs releases
  sdk/messaging/azeventhubs/CHANGELOG.md
  sdk/messaging/azeventhubs/internal/constants.go
Labels: auto-merge

#19383 Set default MaxRetryDelay to 60s
  sdk/azcore/CHANGELOG.md
  sdk/azcore/runtime/policy_retry.go
Labels: Azure.Core

#19395 Don't touch resp when err is non nil
  sdk/data/azappconfig/CHANGELOG.md
  sdk/data/azappconfig/policy_sync_token.go
Labels: App Configuration

#19397 Increment version for data/azappconfig releases
  sdk/data/azappconfig/CHANGELOG.md
  sdk/data/azappconfig/internal/generated/constants.go
Labels: auto-merge

#19322 Add support for making recordings external to the repository
  .gitignore
  eng/scripts/run_tests.ps1
  sdk/internal/CHANGELOG.md
  sdk/internal/recording/recording.go
  sdk/internal/recording/recording_test.go
  sdk/internal/version.go
Labels: EngSys, Central-EngSys

#19399 [azquery] troubleshooting guide
  sdk/monitor/azquery/README.md
  sdk/monitor/azquery/TROUBLESHOOTING.md
Labels: Docs, Client, Monitor - Query

#19392 Sync eng/common directory with azure-sdk-tools for PR 3790
  eng/common/scripts/Helpers/PSModule-Helpers.ps1
  eng/common/scripts/job-matrix/Create-JobMatrix.ps1
  eng/common/scripts/job-matrix/job-matrix-functions.ps1
  eng/common/scripts/stress-testing/deploy-stress-tests.ps1
  eng/common/scripts/stress-testing/find-all-stress-packages.ps1
  eng/common/scripts/stress-testing/generate-scenario-matrix.ps1
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: EngSys, Central-EngSys

#19370 Release v67.0.1
  CHANGELOG.md
  services/preview/iotspaces/mgmt/2017-10-01-preview/iotspaces/client.go
  version/version.go
Labels: Do Not Merge

#19405 Sync eng/common directory with azure-sdk-tools for PR 4486
  eng/common/spelling/Invoke-Cspell.ps1
  eng/common/spelling/package-lock.json
  eng/common/spelling/package.json
Labels: EngSys, Central-EngSys

#19406 Sync eng/common directory with azure-sdk-tools for PR 4480
  eng/common/scripts/Update-DocsMsToc.ps1
Labels: EngSys, Central-EngSys

#19398 Regenerate internal code with latest code generator
  sdk/data/azappconfig/CHANGELOG.md
  sdk/data/azappconfig/autorest.md
  sdk/data/azappconfig/build.go
  sdk/data/azappconfig/client.go
  sdk/data/azappconfig/internal/generated/azureappconfiguration_client.go
  sdk/data/azappconfig/internal/generated/constants.go
  sdk/data/azappconfig/internal/generated/models.go
  sdk/data/azappconfig/internal/generated/models_serde.go
  sdk/data/azappconfig/internal/generated/response_types.go
  sdk/data/azappconfig/internal/generated/time_rfc3339.go
  sdk/data/azappconfig/policy_sync_token_test.go
  sdk/data/azappconfig/setting.go
  sdk/data/azappconfig/setting_selector.go
  sdk/data/azappconfig/version.go
Labels: App Configuration

#19422 Sync eng/common directory with azure-sdk-tools for PR 4504
  eng/common/scripts/stress-testing/generate-scenario-matrix.ps1
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: EngSys, Central-EngSys

#19429 Sync eng/common directory with azure-sdk-tools for PR 4527
  eng/common/testproxy/target_version.txt
Labels: EngSys, Central-EngSys

#19439 Sync eng/common directory with azure-sdk-tools for PR 4543
  eng/common/scripts/stress-testing/find-all-stress-packages.ps1
Labels: EngSys, Central-EngSys

#19351 [Release] sdk/resourcemanager/nginx/armnginx/2.0.0
  sdk/resourcemanager/nginx/armnginx/CHANGELOG.md
  sdk/resourcemanager/nginx/armnginx/autorest.md
  sdk/resourcemanager/nginx/armnginx/certificates_client.go
  sdk/resourcemanager/nginx/armnginx/certificates_client_example_test.go
  sdk/resourcemanager/nginx/armnginx/configurations_client.go
  sdk/resourcemanager/nginx/armnginx/configurations_client_example_test.go
  sdk/resourcemanager/nginx/armnginx/constants.go
  sdk/resourcemanager/nginx/armnginx/deployments_client.go
  sdk/resourcemanager/nginx/armnginx/deployments_client_example_test.go
  sdk/resourcemanager/nginx/armnginx/go.mod
  sdk/resourcemanager/nginx/armnginx/models.go
  sdk/resourcemanager/nginx/armnginx/models_serde.go
  sdk/resourcemanager/nginx/armnginx/operations_client.go
  sdk/resourcemanager/nginx/armnginx/operations_client_example_test.go
  sdk/resourcemanager/nginx/armnginx/response_types.go
Labels: Do Not Merge

#19391 Set blob expiry
  sdk/storage/azblob/CHANGELOG.md
  sdk/storage/azblob/appendblob/client.go
  sdk/storage/azblob/appendblob/client_test.go
  sdk/storage/azblob/appendblob/examples_test.go
  sdk/storage/azblob/blob/client.go
  sdk/storage/azblob/blob/client_test.go
  sdk/storage/azblob/blob/constants.go
  sdk/storage/azblob/blob/models.go
  sdk/storage/azblob/blob/responses.go
  sdk/storage/azblob/blockblob/client.go
  sdk/storage/azblob/blockblob/client_test.go
  sdk/storage/azblob/blockblob/examples_test.go
  sdk/storage/azblob/internal/testcommon/clients_auth.go
  sdk/storage/azblob/test-resources.json
  sdk/storage/azblob/testdata/recordings/Test/TestAppendBlobSetExpiryRelativeToCreation.json
  sdk/storage/azblob/testdata/recordings/Test/TestAppendBlobSetExpiryRelativeToNow.json
  sdk/storage/azblob/testdata/recordings/Test/TestAppendBlobSetExpiryToNeverExpire.json
  sdk/storage/azblob/testdata/recordings/Test/TestBlobSetExpiry.json
  sdk/storage/azblob/testdata/recordings/Test/TestBlockBlobSetExpiryOnHnsDisabledAccount.json
  sdk/storage/azblob/testdata/recordings/Test/TestBlockBlobSetExpiryRelativeToCreation.json
  sdk/storage/azblob/testdata/recordings/Test/TestBlockBlobSetExpiryRelativeToNow.json
  sdk/storage/azblob/testdata/recordings/Test/TestBlockBlobSetExpiryToNeverExpire.json
Labels: Storage

#19381 Add service client accessor to azblob.Client
  sdk/storage/azblob/CHANGELOG.md
  sdk/storage/azblob/client.go
Labels: Storage

#19458 Increment version for data/azappconfig releases
  sdk/data/azappconfig/CHANGELOG.md
  sdk/data/azappconfig/version.go
Labels: auto-merge

#19435 Sync eng/common directory with azure-sdk-tools for PR 4532
  eng/common/TestResources/New-TestResources.ps1
Labels: EngSys, Central-EngSys
