Repository Azure/azure-sdk-for-go, pull requests merged in 2022-07, with the labels that each got.

#18524 Sync eng/common directory with azure-sdk-tools for PR 3563
  eng/common/pipelines/templates/steps/verify-samples.yml
Labels: EngSys, Central-EngSys

#18529 Sync eng/common directory with azure-sdk-tools for PR 3428
  eng/common/scripts/Helpers/Metadata-Helpers.ps1
  eng/common/scripts/Service-Level-Readme-Automation.ps1
  eng/common/scripts/Update-DocsMsToc.ps1
Labels: EngSys, Central-EngSys

#18446 Remove azsecrets convenience API
  sdk/keyvault/azsecrets/README.md
  sdk/keyvault/azsecrets/autorest.md
  sdk/keyvault/azsecrets/client.go
  sdk/keyvault/azsecrets/client_test.go
  sdk/keyvault/azsecrets/constants.go
  sdk/keyvault/azsecrets/custom_client.go
  sdk/keyvault/azsecrets/doc.go
  sdk/keyvault/azsecrets/example_test.go
  sdk/keyvault/azsecrets/go.mod
  sdk/keyvault/azsecrets/go.sum
  sdk/keyvault/azsecrets/internal/generated/custom_client.go
  sdk/keyvault/azsecrets/internal/generated/keyvault_client.go
  sdk/keyvault/azsecrets/internal/generated/models.go
  sdk/keyvault/azsecrets/internal/generated/models_serde.go
  sdk/keyvault/azsecrets/internal/generated/response_types.go
  sdk/keyvault/azsecrets/models.go
  sdk/keyvault/azsecrets/models_serde.go
  sdk/keyvault/azsecrets/pollers.go
  sdk/keyvault/azsecrets/response_types.go
  sdk/keyvault/azsecrets/test-resources-post.ps1
  sdk/keyvault/azsecrets/testdata/recordings/TestBackupRestore.json
  sdk/keyvault/azsecrets/testdata/recordings/TestBackupSecret.json
  sdk/keyvault/azsecrets/testdata/recordings/TestBeginDeleteSecretRehydrated.json
  sdk/keyvault/azsecrets/testdata/recordings/TestBeginRecoverDeletedSecret.json
  sdk/keyvault/azsecrets/testdata/recordings/TestCRUD.json
  sdk/keyvault/azsecrets/testdata/recordings/TestDeleteSecret.json
  sdk/keyvault/azsecrets/testdata/recordings/TestListDeletedSecrets.json
  sdk/keyvault/azsecrets/testdata/recordings/TestListSecretVersions.json
  sdk/keyvault/azsecrets/testdata/recordings/TestListSecrets.json
  sdk/keyvault/azsecrets/testdata/recordings/TestPurgeDeletedSecret.json
  sdk/keyvault/azsecrets/testdata/recordings/TestRecover.json
  sdk/keyvault/azsecrets/testdata/recordings/TestSecretTags.json
  sdk/keyvault/azsecrets/testdata/recordings/TestSetGetSecret.json
  sdk/keyvault/azsecrets/testdata/recordings/TestUpdateSecretProperties.json
  sdk/keyvault/azsecrets/time_unix.go
  sdk/keyvault/azsecrets/utils_test.go
Labels: KeyVault, Client

#18502 Remove azcertificates convenience API
  sdk/keyvault/azcertificates/README.md
  sdk/keyvault/azcertificates/autorest.md
  sdk/keyvault/azcertificates/client.go
  sdk/keyvault/azcertificates/client_test.go
  sdk/keyvault/azcertificates/constants.go
  sdk/keyvault/azcertificates/custom_client.go
  sdk/keyvault/azcertificates/doc.go
  sdk/keyvault/azcertificates/example_test.go
  sdk/keyvault/azcertificates/internal/generated/constants.go
  sdk/keyvault/azcertificates/internal/generated/custom_client.go
  sdk/keyvault/azcertificates/internal/generated/keyvault_client.go
  sdk/keyvault/azcertificates/internal/generated/models.go
  sdk/keyvault/azcertificates/internal/generated/models_serde.go
  sdk/keyvault/azcertificates/internal/generated/response_types.go
  sdk/keyvault/azcertificates/models.go
  sdk/keyvault/azcertificates/models_serde.go
  sdk/keyvault/azcertificates/pollers.go
  sdk/keyvault/azcertificates/response_types.go
  sdk/keyvault/azcertificates/testdata/recordings/TestBackupRestore.json
  sdk/keyvault/azcertificates/testdata/recordings/TestCRUD.json
  sdk/keyvault/azcertificates/testdata/recordings/TestCRUDOperations.json
  sdk/keyvault/azcertificates/testdata/recordings/TestClient_BackupCertificate.json
  sdk/keyvault/azcertificates/testdata/recordings/TestClient_BeginCreateCertificate.json
  sdk/keyvault/azcertificates/testdata/recordings/TestClient_BeginCreateCertificateRehydrated.json
  sdk/keyvault/azcertificates/testdata/recordings/TestClient_BeginDeleteCertificate.json
  sdk/keyvault/azcertificates/testdata/recordings/TestClient_BeginDeleteCertificateRehydrated.json
  sdk/keyvault/azcertificates/testdata/recordings/TestClient_BeginRecoverDeletedCertificate.json
  sdk/keyvault/azcertificates/testdata/recordings/TestClient_BeginRecoverDeletedCertificateRehydrated.json
  sdk/keyvault/azcertificates/testdata/recordings/TestClient_CancelCertificateOperation.json
  sdk/keyvault/azcertificates/testdata/recordings/TestClient_ContactsCRUD.json
  sdk/keyvault/azcertificates/testdata/recordings/TestClient_GetCertificateOperation.json
  sdk/keyvault/azcertificates/testdata/recordings/TestClient_ImportCertificate.json
  sdk/keyvault/azcertificates/testdata/recordings/TestClient_IssuerCRUD.json
  sdk/keyvault/azcertificates/testdata/recordings/TestClient_ListCertificateVersions.json
  sdk/keyvault/azcertificates/testdata/recordings/TestClient_ListCertificates.json
  sdk/keyvault/azcertificates/testdata/recordings/TestClient_ListDeletedCertificates.json
  sdk/keyvault/azcertificates/testdata/recordings/TestClient_RestoreCertificateBackup.json
  sdk/keyvault/azcertificates/testdata/recordings/TestContactsCRUD.json
  sdk/keyvault/azcertificates/testdata/recordings/TestDeleteRecover.json
  sdk/keyvault/azcertificates/testdata/recordings/TestImportCertificate.json
  sdk/keyvault/azcertificates/testdata/recordings/TestIssuerCRUD.json
  sdk/keyvault/azcertificates/testdata/recordings/TestListCertificateVersions.json
  sdk/keyvault/azcertificates/testdata/recordings/TestListCertificates.json
  sdk/keyvault/azcertificates/testdata/recordings/TestMergeCertificate.json
  sdk/keyvault/azcertificates/testdata/recordings/TestOperationCRUD.json
  sdk/keyvault/azcertificates/testdata/recordings/TestPolicy.json
  sdk/keyvault/azcertificates/testdata/recordings/TestUpdateCertificatePolicy.json
  sdk/keyvault/azcertificates/time_unix.go
  sdk/keyvault/azcertificates/utils_test.go
  sdk/keyvault/azcertificates/version.go
Labels: KeyVault, Client

#18518 Sync eng/common directory with azure-sdk-tools for PR 3527
  eng/common/scripts/Helpers/PSModule-Helpers.ps1
Labels: EngSys, Central-EngSys

#18541 Sync eng/common directory with azure-sdk-tools for PR 3500
  eng/common/testproxy/target_version.txt
Labels: EngSys, Central-EngSys

#18495 Skip dumping package properties for eng directories
  eng/pipelines/templates/jobs/archetype-sdk-eng-client.yml
  eng/pipelines/templates/steps/analyze.yml
  eng/tools/apidiff/ci.yml
  eng/tools/deprecate/ci.yml
  eng/tools/generator/ci.yml
  eng/tools/indexer/ci.yml
  eng/tools/internal/ci.yml
  eng/tools/pkgchk/ci.yml
  eng/tools/profileBuilder/ci.yml
Labels: auto-merge, Central-EngSys

#18543 Sync eng/common directory with azure-sdk-tools for PR 3480
  eng/common/pipelines/templates/steps/validate-filename.yml
Labels: EngSys, Central-EngSys

#18553 Increment version for keyvault/azsecrets releases
  sdk/keyvault/azsecrets/CHANGELOG.md
  sdk/keyvault/azsecrets/version.go
Labels: KeyVault, auto-merge

#18552 Increment version for keyvault/azkeys releases
  sdk/keyvault/azkeys/CHANGELOG.md
  sdk/keyvault/azkeys/version.go
Labels: KeyVault, auto-merge

#18551 Increment version for keyvault/azcertificates releases
  sdk/keyvault/azcertificates/CHANGELOG.md
  sdk/keyvault/azcertificates/version.go
Labels: KeyVault, auto-merge

#18549 Implement Cosmos db new client with connection string
  sdk/data/azcosmos/CHANGELOG.md
  sdk/data/azcosmos/cosmos_client.go
  sdk/data/azcosmos/cosmos_client_test.go
  sdk/data/azcosmos/doc.go
  sdk/data/azcosmos/example_test.go
Labels: customer-reported

#18555 Sync eng/common directory with azure-sdk-tools for PR 3546
  eng/common/scripts/SetTestPipelineVersion.ps1
Labels: EngSys, Central-EngSys

#18569 Sync eng/common directory with azure-sdk-tools for PR 3606
  eng/common/pipelines/templates/steps/sparse-checkout.yml
Labels: EngSys, Central-EngSys

#18577 Cosmos DB: Support for parametrized queries
  sdk/data/azcosmos/CHANGELOG.md
  sdk/data/azcosmos/cosmos_client.go
  sdk/data/azcosmos/cosmos_client_test.go
  sdk/data/azcosmos/cosmos_container.go
  sdk/data/azcosmos/cosmos_offers.go
  sdk/data/azcosmos/cosmos_query.go
  sdk/data/azcosmos/cosmos_query_request_options.go
  sdk/data/azcosmos/doc.go
  sdk/data/azcosmos/emulator_cosmos_query_test.go
  sdk/data/azcosmos/example_test.go
Labels: Cosmos

#18571 Sync eng/common directory with azure-sdk-tools for PR 3584
  eng/common/pipelines/templates/jobs/docindex.yml
Labels: EngSys, Central-EngSys

#18579 Cosmos DB: Fixes whitespace and supported special characters handling
  sdk/data/azcosmos/CHANGELOG.md
  sdk/data/azcosmos/cosmos_paths.go
  sdk/data/azcosmos/cosmos_paths_test.go
  sdk/data/azcosmos/emulator_cosmos_item_test.go
  sdk/data/azcosmos/partition_key.go
  sdk/data/azcosmos/shared_key_credential.go
  sdk/data/azcosmos/shared_key_credential_test.go
Labels: Cosmos

#18586 Sync eng/common directory with azure-sdk-tools for PR 3642
  eng/common/scripts/Helpers/Metadata-Helpers.ps1
  eng/common/scripts/Service-Level-Readme-Automation.ps1
Labels: EngSys, Central-EngSys

#18600 Sync eng/common directory with azure-sdk-tools for PR 3657
  eng/common/pipelines/templates/jobs/perf.yml
Labels: EngSys, Central-EngSys

#18601 Sync eng/common directory with azure-sdk-tools for PR 3656
  eng/common/testproxy/test-proxy-docker.yml
  eng/common/testproxy/test-proxy-tool.yml
Labels: EngSys, Central-EngSys

#18584 Sync eng/common directory with azure-sdk-tools for PR 3628
  eng/common/scripts/Update-DocsMsMetadata.ps1
Labels: EngSys, Central-EngSys

#17649 [azservicebus] Adding DeadLetterMessage options example
  sdk/messaging/azservicebus/example_receiver_test.go
Labels: Service Bus

#18633 Sync eng/common directory with azure-sdk-tools for PR 3700
  eng/common/pipelines/templates/jobs/perf.yml
Labels: EngSys, Central-EngSys

#18634 Sync eng/common directory with azure-sdk-tools for PR 3702
  eng/common/scripts/Test-SampleMetadata.ps1
Labels: EngSys, Central-EngSys

#18655 Fix Key Vault doc typos
  sdk/keyvault/azcertificates/README.md
  sdk/keyvault/azcertificates/client_test.go
  sdk/keyvault/azcertificates/example_test.go
  sdk/keyvault/azkeys/example_test.go
  sdk/keyvault/azsecrets/example_test.go
Labels: KeyVault

#18668 Allow more time for certificate creation in tests
  sdk/keyvault/azcertificates/client_test.go
Labels: KeyVault, test-reliability

#18677 Sync eng/common directory with azure-sdk-tools for PR 3661
  eng/common/pipelines/templates/steps/sparse-checkout.yml
Labels: EngSys, Central-EngSys

#18675 Sync eng/common directory with azure-sdk-tools for PR 3735
  eng/common/scripts/Detect-Api-Changes.ps1
Labels: EngSys, Central-EngSys

#18687 Move the entry in CHANGELOG
  sdk/azidentity/CHANGELOG.md
Labels: auto-merge

#18692 Sync eng/common directory with azure-sdk-tools for PR 3754
  eng/common/pipelines/templates/steps/sparse-checkout.yml
Labels: EngSys, Central-EngSys

#18583 Fix broken pkg.go.dev link in azkeys README
  sdk/keyvault/azkeys/README.md
Labels: auto-merge

#18709 Sync eng/common directory with azure-sdk-tools for PR 3753
  eng/common/scripts/job-matrix/README.md
  eng/common/scripts/job-matrix/samples/matrix.json
  eng/common/scripts/job-matrix/tests/job-matrix-functions.filter.tests.ps1
  eng/common/scripts/job-matrix/tests/job-matrix-functions.tests.ps1
Labels: EngSys, Central-EngSys

#18764 Sync eng/common directory with azure-sdk-tools for PR 3787
  eng/common/TestResources/setup-environments.yml
Labels: EngSys, Central-EngSys
