Repository Azure/azure-sdk-for-go, pull requests merged in 2022-03, with the labels that each got.

#17141 [Secrets] Improving consistency with other Tier-1 languages
  sdk/keyvault/azsecrets/CHANGELOG.md
  sdk/keyvault/azsecrets/autorest.md
  sdk/keyvault/azsecrets/build.go
  sdk/keyvault/azsecrets/client.go
  sdk/keyvault/azsecrets/client_test.go
  sdk/keyvault/azsecrets/consts.go
  sdk/keyvault/azsecrets/internal/constants.go
  sdk/keyvault/azsecrets/internal/hsmsecuritydomain_client.go
  sdk/keyvault/azsecrets/internal/keyvault_client.go
  sdk/keyvault/azsecrets/internal/models.go
  sdk/keyvault/azsecrets/internal/pagers.go
  sdk/keyvault/azsecrets/internal/pollers.go
  sdk/keyvault/azsecrets/internal/response_types.go
  sdk/keyvault/azsecrets/internal/roleassignments_client.go
  sdk/keyvault/azsecrets/internal/roledefinitions_client.go
  sdk/keyvault/azsecrets/models.go
Labels: KeyVault

#17199 Sync eng/common directory with azure-sdk-tools for PR 2778
  eng/common/pipelines/templates/steps/credscan.yml
  eng/common/scripts/update-docs-metadata.ps1
Labels: EngSys, Central-EngSys

#17204 Sync eng/common directory with azure-sdk-tools for PR 2823
  eng/common/testproxy/docker-start-proxy.ps1
  eng/common/testproxy/target_version.txt
  eng/common/testproxy/test-proxy-docker.yml
  eng/common/testproxy/test-proxy-tool.yml
Labels: EngSys, Central-EngSys

#17198 Sync eng/common directory with azure-sdk-tools for PR 2830
  eng/common/pipelines/templates/steps/cosmos-emulator.yml
  eng/common/scripts/Cosmos-Emulator.ps1
Labels: EngSys, Central-EngSys

#17215 [Certificates] update pagers
  sdk/keyvault/azcertificates/CHANGELOG.md
  sdk/keyvault/azcertificates/autorest.md
  sdk/keyvault/azcertificates/client.go
  sdk/keyvault/azcertificates/client_test.go
  sdk/keyvault/azcertificates/example_test.go
  sdk/keyvault/azcertificates/internal/generated/constants.go
  sdk/keyvault/azcertificates/internal/generated/keyvault_client.go
  sdk/keyvault/azcertificates/internal/generated/pagers.go
Labels: KeyVault

#17214 [Secrets] Change pagers to new design
  eng/config.json
  sdk/keyvault/azsecrets/CHANGELOG.md
  sdk/keyvault/azsecrets/client.go
  sdk/keyvault/azsecrets/client_test.go
  sdk/keyvault/azsecrets/example_test.go
  sdk/keyvault/azsecrets/internal/keyvault_client.go
  sdk/keyvault/azsecrets/internal/pagers.go
Labels: KeyVault

#17220 Sync eng/common directory with azure-sdk-tools for PR 2824
  eng/common/scripts/git-diff-changes.ps1
Labels: EngSys, Central-EngSys

#17223 Increment version for azcore releases
  sdk/azcore/CHANGELOG.md
  sdk/azcore/internal/shared/constants.go
Labels: auto-merge

#16933 [KeyVault] Removing embedded models in azkeys
  sdk/keyvault/azkeys/CHANGELOG.md
  sdk/keyvault/azkeys/autorest.md
  sdk/keyvault/azkeys/client.go
  sdk/keyvault/azkeys/client_test.go
  sdk/keyvault/azkeys/constants.go
  sdk/keyvault/azkeys/constants_test.go
  sdk/keyvault/azkeys/crypto/constants.go
  sdk/keyvault/azkeys/crypto/crypto_client.go
  sdk/keyvault/azkeys/crypto/crypto_client_test.go
  sdk/keyvault/azkeys/crypto/examples_test.go
  sdk/keyvault/azkeys/crypto/models.go
  sdk/keyvault/azkeys/example_test.go
  sdk/keyvault/azkeys/internal/generated/constants.go
  sdk/keyvault/azkeys/internal/generated/hsmsecuritydomain_client.go
  sdk/keyvault/azkeys/internal/generated/keyvault_client.go
  sdk/keyvault/azkeys/internal/generated/models.go
  sdk/keyvault/azkeys/internal/generated/pagers.go
  sdk/keyvault/azkeys/internal/generated/pollers.go
  sdk/keyvault/azkeys/internal/generated/response_types.go
  sdk/keyvault/azkeys/internal/generated/roleassignments_client.go
  sdk/keyvault/azkeys/internal/generated/roledefinitions_client.go
  sdk/keyvault/azkeys/models.go
  sdk/keyvault/azkeys/testdata/recordings/TestUpdateKeyPropertiesImmutable/TestUpdateKeyPropertiesImmutable_NON-HSM.json
  sdk/keyvault/azkeys/utils_test.go
Labels: KeyVault

#17146 [Tables] GA Preparation
  sdk/data/aztables/CHANGELOG.md
  sdk/data/aztables/autorest.md
  sdk/data/aztables/build.go
  sdk/data/aztables/client.go
  sdk/data/aztables/client_test.go
  sdk/data/aztables/constants.go
  sdk/data/aztables/entity_test.go
  sdk/data/aztables/example_test.go
  sdk/data/aztables/internal/models.go
  sdk/data/aztables/internal/service_client.go
  sdk/data/aztables/internal/table_client.go
  sdk/data/aztables/internal/time_rfc1123.go
  sdk/data/aztables/internal/time_rfc3339.go
  sdk/data/aztables/proxy_test.go
  sdk/data/aztables/sas_account.go
  sdk/data/aztables/sas_query_params.go
  sdk/data/aztables/sas_service.go
  sdk/data/aztables/service_client.go
  sdk/data/aztables/service_client_test.go
  sdk/data/aztables/shared_access_signature_test.go
  sdk/data/aztables/shared_policy_shared_key_credential.go
  sdk/data/aztables/testdata/recordings/TestBatchErrorHandleResponse/TestBatchErrorHandleResponse_cosmos.json
  sdk/data/aztables/testdata/recordings/TestBatchErrorHandleResponse/TestBatchErrorHandleResponse_storage.json
  sdk/data/aztables/transaction_batch_test.go
  sdk/data/aztables/transactional_batch.go
  sdk/data/aztables/zt_table_recorded_tests.go
Labels: Tables

#17170 Prevent ChainedTokenCredential data race
  sdk/azidentity/CHANGELOG.md
  sdk/azidentity/chained_token_credential.go
  sdk/azidentity/chained_token_credential_test.go
  sdk/azidentity/environment_credential_test.go
Labels: Client, Azure.Identity

#17230 [Tables] removing `RawResponse`
  sdk/data/aztables/CHANGELOG.md
  sdk/data/aztables/client.go
  sdk/data/aztables/client_test.go
  sdk/data/aztables/internal/constants.go
  sdk/data/aztables/service_client.go
  sdk/data/aztables/service_client_test.go
  sdk/data/aztables/transaction_batch_test.go
  sdk/data/aztables/transactional_batch.go
Labels: KeyVault

#17226 [Keys] Remove `RawResponse`
  sdk/keyvault/azkeys/CHANGELOG.md
  sdk/keyvault/azkeys/README.md
  sdk/keyvault/azkeys/client.go
  sdk/keyvault/azkeys/client_test.go
  sdk/keyvault/azkeys/go.mod
  sdk/keyvault/azkeys/go.sum
Labels: KeyVault

#17224 [Secrets] Remove `RawResponse`
  sdk/keyvault/azsecrets/CHANGELOG.md
  sdk/keyvault/azsecrets/README.md
  sdk/keyvault/azsecrets/client.go
  sdk/keyvault/azsecrets/go.mod
  sdk/keyvault/azsecrets/go.sum
Labels: KeyVault

#17225 [Certificates] Remove `RawResponse`
  sdk/keyvault/azcertificates/CHANGELOG.md
  sdk/keyvault/azcertificates/README.md
  sdk/keyvault/azcertificates/client.go
  sdk/keyvault/azcertificates/go.mod
  sdk/keyvault/azcertificates/go.sum
Labels: KeyVault

#17093 Azure App Configuration SDK
  .vscode/cspell.json
  sdk/appconfiguration/azappconfig/autorest.md
  sdk/appconfiguration/azappconfig/client.go
  sdk/appconfiguration/azappconfig/client_test.go
  sdk/appconfiguration/azappconfig/internal/generated/azureappconfiguration_client.go
  sdk/appconfiguration/azappconfig/internal/generated/constants.go
  sdk/appconfiguration/azappconfig/internal/generated/models.go
  sdk/appconfiguration/azappconfig/internal/generated/pagers.go
  sdk/appconfiguration/azappconfig/internal/generated/response_types.go
  sdk/appconfiguration/azappconfig/internal/generated/time_rfc3339.go
  sdk/appconfiguration/azappconfig/policy_hmac_auth.go
  sdk/appconfiguration/azappconfig/policy_hmac_auth_parse_test.go
  sdk/appconfiguration/azappconfig/policy_sync_token.go
  sdk/appconfiguration/azappconfig/policy_sync_token_parse_test.go
  sdk/appconfiguration/azappconfig/setting.go
  sdk/appconfiguration/azappconfig/setting_selector.go
Labels: App Configuration

#17238 Sync eng/common directory with azure-sdk-tools for PR 2875
  eng/common/pipelines/templates/steps/detect-api-changes.yml
  eng/common/scripts/Detect-Api-Changes.ps1
Labels: EngSys, Central-EngSys

#17243 Update azidentity readme
  sdk/azidentity/README.md
Labels: Docs, Azure.Identity

#17247 Increment version for keyvault/azkeys releases
  sdk/keyvault/azkeys/CHANGELOG.md
  sdk/keyvault/azkeys/internal/generated/constants.go
Labels: KeyVault, auto-merge

#17245 [Certificates] fixing live test issue
  sdk/keyvault/azcertificates/client_test.go
  sdk/keyvault/azcertificates/utils_test.go
Labels: KeyVault

#17244 [Tables] Batching response struct is now empty
  sdk/data/aztables/CHANGELOG.md
  sdk/data/aztables/constants.go
  sdk/data/aztables/example_test.go
  sdk/data/aztables/go.mod
  sdk/data/aztables/go.sum
  sdk/data/aztables/transaction_batch_test.go
  sdk/data/aztables/transactional_batch.go
Labels: Tables

#17250 [Certificates] Fixing Changelog
  sdk/keyvault/azcertificates/CHANGELOG.md
Labels: KeyVault

#17253 Increment version for data/aztables releases
  sdk/data/aztables/CHANGELOG.md
  sdk/data/aztables/internal/constants.go
Labels: auto-merge

#17254 Increment version for keyvault/azcertificates releases
  sdk/keyvault/azcertificates/CHANGELOG.md
  sdk/keyvault/azcertificates/internal/generated/constants.go
Labels: KeyVault, auto-merge

#17252 Increment version for messaging/azservicebus releases
  sdk/messaging/azservicebus/CHANGELOG.md
  sdk/messaging/azservicebus/internal/constants.go
Labels: auto-merge

#17242 Increment version for keyvault/azsecrets releases
  sdk/keyvault/azsecrets/CHANGELOG.md
  sdk/keyvault/azsecrets/internal/constants.go
Labels: KeyVault, auto-merge

#17240 App Configuration: prepare release
  eng/config.json
  sdk/appconfig/azappconfig/CHANGELOG.md
  sdk/appconfig/azappconfig/LICENSE.txt
  sdk/appconfig/azappconfig/README.md
  sdk/appconfig/azappconfig/client.go
  sdk/appconfig/azappconfig/client_test.go
  sdk/appconfig/azappconfig/doc.go
  sdk/appconfig/azappconfig/internal/generated/azureappconfiguration_client.go
  sdk/appconfig/azappconfig/internal/generated/models.go
  sdk/appconfig/azappconfig/internal/generated/pagers.go
  sdk/appconfig/azappconfig/internal/generated/time_rfc3339.go
  sdk/appconfig/azappconfig/policy_hmac_auth.go
  sdk/appconfig/azappconfig/setting.go
Labels: App Configuration

#17265 Increment version for appconfig/azappconfig releases
  sdk/appconfig/azappconfig/CHANGELOG.md
  sdk/appconfig/azappconfig/internal/generated/constants.go
Labels: auto-merge

#17165 Sync eng/common directory with azure-sdk-tools for PR 2810
  eng/common/TestResources/New-TestResources.ps1
  eng/common/TestResources/SubConfig-Helpers.ps1
Labels: EngSys, Central-EngSys

#17255 Sync eng/common directory with azure-sdk-tools for PR 2889
  eng/common/TestResources/New-TestResources.ps1
Labels: EngSys, Central-EngSys

#17262 Sync eng/common directory with azure-sdk-tools for PR 2892
  eng/common/scripts/stress-testing/deploy-stress-tests.ps1
  eng/common/scripts/stress-testing/find-all-stress-packages.ps1
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: EngSys, Central-EngSys

#17217 Sync eng/common directory with azure-sdk-tools for PR 2836
  eng/common/scripts/ChangeLog-Operations.ps1
Labels: EngSys, Central-EngSys

#17246 Increment version for azidentity releases
  sdk/azidentity/CHANGELOG.md
  sdk/azidentity/version.go
Labels: auto-merge

#17268 Sync eng/common directory with azure-sdk-tools for PR 2899
  eng/common/scripts/ChangeLog-Operations.ps1
Labels: EngSys, Central-EngSys

#17294 Sync eng/common directory with azure-sdk-tools for PR 2910
  eng/common/scripts/Update-DocsMsMetadata.ps1
Labels: EngSys, Central-EngSys

#17273 Increment version for resourcemanager/internal releases
  sdk/resourcemanager/internal/CHANGELOG.md
  sdk/resourcemanager/internal/version.go
Labels: auto-merge

#17309 Sync eng/common directory with azure-sdk-tools for PR 2913
  eng/common/pipelines/templates/jobs/archetype-sdk-tests-generate.yml
  eng/common/scripts/job-matrix/README.md
Labels: EngSys, Central-EngSys

#17310 Sync eng/common directory with azure-sdk-tools for PR 2870
  eng/common/pipelines/templates/jobs/archetype-sdk-tests-generate.yml
Labels: EngSys, Central-EngSys

#17311 Sync eng/common directory with azure-sdk-tools for PR 2866
  eng/common/TestResources/New-TestResources.ps1
Labels: EngSys, Central-EngSys

#17319 Increment version for resourcemanager/internal releases
  sdk/resourcemanager/internal/CHANGELOG.md
  sdk/resourcemanager/internal/version.go
Labels: auto-merge

#17320 [appconfig] Update documentation
  sdk/appconfig/azappconfig/setting_selector.go
Labels: App Configuration, auto-merge

#17296 [Perf] Fixing race conditions in performance
  sdk/data/aztables/testdata/perf/batch.go
  sdk/data/aztables/testdata/perf/go.mod
  sdk/data/aztables/testdata/perf/go.sum
  sdk/data/aztables/testdata/perf/insert_entity.go
  sdk/data/aztables/testdata/perf/list_entities.go
  sdk/data/aztables/testdata/perf/main.go
  sdk/internal/perf/README.md
  sdk/internal/perf/implementation.go
  sdk/internal/perf/perf.go
  sdk/internal/perf/perf_runner.go
  sdk/internal/perf/perf_test.go
  sdk/internal/perf/random_stream.go
  sdk/internal/perf/status.go
  sdk/internal/perf/testdata/perf/sleep_perf.go
  sdk/internal/perf/utils.go
Labels: pillar-performance

#17316 Sync eng/common directory with azure-sdk-tools for PR 2901
  eng/common/pipelines/templates/steps/credscan.yml
Labels: EngSys, Central-EngSys

#17321 [Blob] Return all clients by ptr
  sdk/storage/azblob/CHANGELOG.md
  sdk/storage/azblob/ci.yml
  sdk/storage/azblob/zc_append_blob_client.go
  sdk/storage/azblob/zc_blob_client.go
  sdk/storage/azblob/zc_block_blob_client.go
  sdk/storage/azblob/zc_container_client.go
  sdk/storage/azblob/zc_page_blob_client.go
  sdk/storage/azblob/zc_service_client.go
  sdk/storage/azblob/zt_append_blob_client_test.go
  sdk/storage/azblob/zt_blob_client_test.go
  sdk/storage/azblob/zt_block_blob_client_test.go
  sdk/storage/azblob/zt_container_client_test.go
  sdk/storage/azblob/zt_page_blob_client_test.go
  sdk/storage/azblob/zt_service_client_test.go
  sdk/storage/azblob/zt_test.go
Labels: Storage

#17324 Sync eng/common directory with azure-sdk-tools for PR 2922
  eng/common/scripts/Update-DocsMsToc.ps1
Labels: EngSys, Central-EngSys

#17276 Fixing Metadata and other properties setting in UploadStreamToBlockBlob
  sdk/storage/azblob/highlevel.go
  sdk/storage/azblob/zt_client_provided_key_test.go
  sdk/storage/azblob/zt_highlevel_test.go
Labels: Storage

#17340 Sync eng/common directory with azure-sdk-tools for PR 2847
  eng/common/scripts/Helpers/Metadata-Helpers.ps1
  eng/common/scripts/Import-AzModules.ps1
  eng/common/scripts/Update-DocsMsMetadata.ps1
Labels: EngSys, Central-EngSys

#17343 Sync eng/common directory with azure-sdk-tools for PR 2928
  eng/common/scripts/Update-DocsMsToc.ps1
Labels: EngSys, Central-EngSys

#17344 [Keyvault] Updating READMEs
  sdk/keyvault/azcertificates/README.md
  sdk/keyvault/azkeys/README.md
  sdk/keyvault/azkeys/example_test.go
  sdk/keyvault/azsecrets/README.md
  sdk/keyvault/azsecrets/example_test.go
Labels: KeyVault

#17341 [Keys] Preparing for release with 7.3 swagger
  sdk/keyvault/azkeys/CHANGELOG.md
  sdk/keyvault/azkeys/autorest.md
  sdk/keyvault/azkeys/client.go
  sdk/keyvault/azkeys/client_test.go
  sdk/keyvault/azkeys/crypto/crypto_client.go
  sdk/keyvault/azkeys/internal/generated/keyvault_client.go
  sdk/keyvault/azkeys/internal/generated/models.go
  sdk/keyvault/azkeys/internal/generated/models_serde.go
  sdk/keyvault/azkeys/internal/generated/pagers.go
  sdk/keyvault/azkeys/internal/generated/response_types.go
  sdk/keyvault/azkeys/internal/generated/time_unix.go
  sdk/keyvault/azkeys/models.go
  sdk/keyvault/azkeys/testdata/recordings/TestBackupKey/TestBackupKey_HSM.json
  sdk/keyvault/azkeys/testdata/recordings/TestBackupKey/TestBackupKey_NON-HSM.json
  sdk/keyvault/azkeys/testdata/recordings/TestClient_EncryptDecrypt.json
  sdk/keyvault/azkeys/testdata/recordings/TestClient_SignVerify.json
  sdk/keyvault/azkeys/testdata/recordings/TestClient_WrapUnwrap.json
  sdk/keyvault/azkeys/testdata/recordings/TestCreateECKey/TestCreateECKey_HSM.json
  sdk/keyvault/azkeys/testdata/recordings/TestCreateECKey/TestCreateECKey_NON-HSM.json
  sdk/keyvault/azkeys/testdata/recordings/TestCreateKeyRSA/TestCreateKeyRSA_HSM.json
  sdk/keyvault/azkeys/testdata/recordings/TestCreateKeyRSA/TestCreateKeyRSA_NON-HSM.json
  sdk/keyvault/azkeys/testdata/recordings/TestCreateKeyRSATags.json
  sdk/keyvault/azkeys/testdata/recordings/TestCreateOCTKey/TestCreateOCTKey_HSM.json
  sdk/keyvault/azkeys/testdata/recordings/TestCreateOCTKey/TestCreateOCTKey_NON-HSM.json
  sdk/keyvault/azkeys/testdata/recordings/TestDeleteKey/TestDeleteKey_HSM.json
  sdk/keyvault/azkeys/testdata/recordings/TestDeleteKey/TestDeleteKey_NON-HSM.json
  sdk/keyvault/azkeys/testdata/recordings/TestGetDeletedKey/TestGetDeletedKey_NON-HSM.json
  sdk/keyvault/azkeys/testdata/recordings/TestGetKey/TestGetKey_HSM.json
  sdk/keyvault/azkeys/testdata/recordings/TestGetKey/TestGetKey_NON-HSM.json
  sdk/keyvault/azkeys/testdata/recordings/TestGetKeyRotationPolicy/TestGetKeyRotationPolicy_HSM.json
  sdk/keyvault/azkeys/testdata/recordings/TestGetKeyRotationPolicy/TestGetKeyRotationPolicy_NON-HSM.json
  sdk/keyvault/azkeys/testdata/recordings/TestGetRandomBytes/TestGetRandomBytes_HSM.json
  sdk/keyvault/azkeys/testdata/recordings/TestImportKey/TestImportKey_HSM.json
  sdk/keyvault/azkeys/testdata/recordings/TestImportKey/TestImportKey_NON-HSM.json
  sdk/keyvault/azkeys/testdata/recordings/TestListDeletedKeys/TestListDeletedKeys_HSM.json
  sdk/keyvault/azkeys/testdata/recordings/TestListDeletedKeys/TestListDeletedKeys_NON-HSM.json
  sdk/keyvault/azkeys/testdata/recordings/TestListKeyVersions/TestListKeyVersions_HSM.json
  sdk/keyvault/azkeys/testdata/recordings/TestListKeyVersions/TestListKeyVersions_NON-HSM.json
  sdk/keyvault/azkeys/testdata/recordings/TestListKeys/TestListKeys_HSM.json
  sdk/keyvault/azkeys/testdata/recordings/TestListKeys/TestListKeys_NON-HSM.json
  sdk/keyvault/azkeys/testdata/recordings/TestRecoverDeletedKey/TestRecoverDeletedKey_HSM.json
  sdk/keyvault/azkeys/testdata/recordings/TestRecoverDeletedKey/TestRecoverDeletedKey_NON-HSM.json
  sdk/keyvault/azkeys/testdata/recordings/TestReleaseKey/TestReleaseKey_NON-HSM.json
  sdk/keyvault/azkeys/testdata/recordings/TestRotateKey/TestRotateKey_HSM.json
  sdk/keyvault/azkeys/testdata/recordings/TestRotateKey/TestRotateKey_NON-HSM.json
  sdk/keyvault/azkeys/testdata/recordings/TestUpdateKeyProperties/TestUpdateKeyProperties_HSM.json
  sdk/keyvault/azkeys/testdata/recordings/TestUpdateKeyProperties/TestUpdateKeyProperties_NON-HSM.json
  sdk/keyvault/azkeys/testdata/recordings/TestUpdateKeyPropertiesImmutable/TestUpdateKeyPropertiesImmutable_NON-HSM.json
  sdk/keyvault/azkeys/testdata/recordings/TestUpdateKeyRotationPolicy/TestUpdateKeyRotationPolicy_HSM.json
  sdk/keyvault/azkeys/testdata/recordings/TestUpdateKeyRotationPolicy/TestUpdateKeyRotationPolicy_NON-HSM.json
Labels: KeyVault

#17322 [Cosmos] fixing doc tool for cosmos
  sdk/data/azcosmos/composite_index_order.go
  sdk/data/azcosmos/conflict_resolution_mode.go
  sdk/data/azcosmos/consistency_level.go
  sdk/data/azcosmos/cosmos_client.go
  sdk/data/azcosmos/cosmos_container.go
  sdk/data/azcosmos/cosmos_container_properties.go
  sdk/data/azcosmos/cosmos_database.go
  sdk/data/azcosmos/cosmos_database_properties.go
  sdk/data/azcosmos/data_type.go
  sdk/data/azcosmos/indexing_directive.go
  sdk/data/azcosmos/indexing_mode.go
  sdk/data/azcosmos/indexing_policy.go
  sdk/data/azcosmos/spatial_type.go
  sdk/data/azcosmos/throughput_properties.go
Labels: Cosmos, auto-merge

#17350 [Tables] fixing README samples in tables
  sdk/data/aztables/README.md
  sdk/data/aztables/example_test.go
Labels: Tables

#17355 Sync eng/common directory with azure-sdk-tools for PR 2939
  eng/common/scripts/Update-DocsMsToc.ps1
Labels: EngSys, Central-EngSys

#17306 [EngSys] adding ci checks for performance
  eng/pipelines/templates/steps/build-test.yml
  eng/scripts/Build_Perf.ps1
Labels: EngSys

#17353 [KeyVault] regenerating azsecrets for 7.3 swagger
  sdk/keyvault/azsecrets/CHANGELOG.md
  sdk/keyvault/azsecrets/autorest.md
  sdk/keyvault/azsecrets/client.go
  sdk/keyvault/azsecrets/internal/constants.go
  sdk/keyvault/azsecrets/internal/keyvault_client.go
  sdk/keyvault/azsecrets/internal/models.go
  sdk/keyvault/azsecrets/internal/models_serde.go
  sdk/keyvault/azsecrets/internal/pagers.go
  sdk/keyvault/azsecrets/internal/response_types.go
  sdk/keyvault/azsecrets/testdata/recordings/TestBackupSecret.json
  sdk/keyvault/azsecrets/testdata/recordings/TestBeginRecoverDeletedSecret.json
  sdk/keyvault/azsecrets/testdata/recordings/TestDeleteSecret.json
  sdk/keyvault/azsecrets/testdata/recordings/TestListDeletedSecrets.json
  sdk/keyvault/azsecrets/testdata/recordings/TestListSecretVersions.json
  sdk/keyvault/azsecrets/testdata/recordings/TestListSecrets.json
  sdk/keyvault/azsecrets/testdata/recordings/TestPurgeDeletedSecret.json
  sdk/keyvault/azsecrets/testdata/recordings/TestSecretTags.json
  sdk/keyvault/azsecrets/testdata/recordings/TestSetGetSecret.json
  sdk/keyvault/azsecrets/testdata/recordings/TestUpdateSecretProperties.json
Labels: KeyVault

#17361 Sync eng/common directory with azure-sdk-tools for PR 2938
  eng/common/scripts/Update-DocsMsToc.ps1
Labels: EngSys, Central-EngSys

#17299 Sync eng/common directory with azure-sdk-tools for PR 2861
  eng/common/pipelines/templates/steps/credscan.yml
  eng/common/pipelines/templates/steps/eng-common-workflow-enforcer.yml
  eng/common/scripts/Detect-Api-Changes.ps1
  eng/common/scripts/Helpers/git-helpers.ps1
  eng/common/scripts/check-spelling-in-changed-files.ps1
  eng/common/scripts/common.ps1
  eng/common/scripts/get-changedfiles.ps1
  eng/common/scripts/get-markdown-files-from-changed-files.ps1
  eng/common/scripts/git-diff-changes.ps1
Labels: EngSys, Central-EngSys

#17365 Fix performance test build task
  eng/pipelines/templates/steps/build-test.yml
Labels: Central-EngSys

#17373 Sync eng/common directory with azure-sdk-tools for PR 2972
  eng/common/pipelines/templates/steps/eng-common-workflow-enforcer.yml
  eng/common/scripts/Helpers/git-helpers.ps1
Labels: EngSys, Central-EngSys

#17352 [KeyVault] regenerate azcertificates from 7.3 swagger
  sdk/keyvault/azcertificates/autorest.md
  sdk/keyvault/azcertificates/client.go
  sdk/keyvault/azcertificates/internal/generated/constants.go
  sdk/keyvault/azcertificates/internal/generated/keyvault_client.go
  sdk/keyvault/azcertificates/internal/generated/models.go
  sdk/keyvault/azcertificates/internal/generated/models_serde.go
  sdk/keyvault/azcertificates/internal/generated/pagers.go
  sdk/keyvault/azcertificates/internal/generated/response_types.go
  sdk/keyvault/azcertificates/internal/generated/roleassignments_client.go
  sdk/keyvault/azcertificates/internal/generated/roledefinitions_client.go
  sdk/keyvault/azcertificates/testdata/recordings/TestCRUDOperations.json
  sdk/keyvault/azcertificates/testdata/recordings/TestClient_BackupCertificate.json
  sdk/keyvault/azcertificates/testdata/recordings/TestClient_BeginCreateCertificate.json
  sdk/keyvault/azcertificates/testdata/recordings/TestClient_BeginDeleteCertificate.json
  sdk/keyvault/azcertificates/testdata/recordings/TestClient_BeginRecoverDeletedCertificate.json
  sdk/keyvault/azcertificates/testdata/recordings/TestClient_CancelCertificateOperation.json
  sdk/keyvault/azcertificates/testdata/recordings/TestClient_ContactsCRUD.json
  sdk/keyvault/azcertificates/testdata/recordings/TestClient_GetCertificateOperation.json
  sdk/keyvault/azcertificates/testdata/recordings/TestClient_ImportCertificate.json
  sdk/keyvault/azcertificates/testdata/recordings/TestClient_IssuerCRUD.json
  sdk/keyvault/azcertificates/testdata/recordings/TestClient_ListCertificateVersions.json
  sdk/keyvault/azcertificates/testdata/recordings/TestClient_ListCertificates.json
  sdk/keyvault/azcertificates/testdata/recordings/TestClient_ListDeletedCertificates.json
  sdk/keyvault/azcertificates/testdata/recordings/TestClient_RestoreCertificateBackup.json
  sdk/keyvault/azcertificates/testdata/recordings/TestMergeCertificate.json
  sdk/keyvault/azcertificates/testdata/recordings/TestPolicy.json
Labels: KeyVault

#17374 Fix pkg.go.dev link for certificates README
  sdk/keyvault/azcertificates/README.md
Labels: KeyVault

#17189 Add test case for sdk/resourcemanager/storage
  sdk/resourcemanager/storage/armstorage/go.mod
  sdk/resourcemanager/storage/armstorage/go.sum
  sdk/resourcemanager/storage/armstorage/testdata/recordings/TestBlobContainersClient.json
  sdk/resourcemanager/storage/armstorage/testdata/recordings/TestEncryptionScopesClient.json
  sdk/resourcemanager/storage/armstorage/testdata/recordings/TestManagementPoliciesClient.json
  sdk/resourcemanager/storage/armstorage/testdata/recordings/TestOperationsClient.json
  sdk/resourcemanager/storage/armstorage/testdata/recordings/TestSKUsClient.json
  sdk/resourcemanager/storage/armstorage/testdata/recordings/TestStorageAccountsClient.json
  sdk/resourcemanager/storage/armstorage/testdata/recordings/TestUsagesClient.json
  sdk/resourcemanager/storage/armstorage/zt_blobcontainers_client_live_test.go
  sdk/resourcemanager/storage/armstorage/zt_encryptionscopes_client_live_test.go
  sdk/resourcemanager/storage/armstorage/zt_managementpolicies_client_live_test.go
  sdk/resourcemanager/storage/armstorage/zt_operations_client_live_test.go
  sdk/resourcemanager/storage/armstorage/zt_skus_client_live_test.go
  sdk/resourcemanager/storage/armstorage/zt_storageaccounts_client_live_test.go
  sdk/resourcemanager/storage/armstorage/zt_usages_client_live_test.go
Labels: Mgmt

#17076 Add test case for sdk/resourcemanager/keyvault
  sdk/resourcemanager/keyvault/armkeyvault/go.mod
  sdk/resourcemanager/keyvault/armkeyvault/go.sum
  sdk/resourcemanager/keyvault/armkeyvault/testdata/recordings/TestKeysClient.json
  sdk/resourcemanager/keyvault/armkeyvault/testdata/recordings/TestSecretsClient.json
  sdk/resourcemanager/keyvault/armkeyvault/testdata/recordings/TestVaultsClient.json
  sdk/resourcemanager/keyvault/armkeyvault/zt_keys_client_live_test.go
  sdk/resourcemanager/keyvault/armkeyvault/zt_secrets_client_live_test.go
  sdk/resourcemanager/keyvault/armkeyvault/zt_vaults_client_live_test.go
Labels: Mgmt

#17056 Add test case for sdk/reourcemanager/network
  sdk/resourcemanager/network/armnetwork/go.mod
  sdk/resourcemanager/network/armnetwork/go.sum
  sdk/resourcemanager/network/armnetwork/testdata/recordings/TestIPGroupsClient.json
  sdk/resourcemanager/network/armnetwork/testdata/recordings/TestSubnetsClient.json
  sdk/resourcemanager/network/armnetwork/testdata/recordings/TestVirtualNetworksClient.json
  sdk/resourcemanager/network/armnetwork/zt_ipgroups_client_live_test.go
  sdk/resourcemanager/network/armnetwork/zt_subnets_client_live_test.go
  sdk/resourcemanager/network/armnetwork/zt_virtualnetworks_client_live_test.go
Labels: Mgmt

#17055 Add test case for sdk/reourcemanager/compute
  sdk/resourcemanager/compute/armcompute/go.mod
  sdk/resourcemanager/compute/armcompute/go.sum
  sdk/resourcemanager/compute/armcompute/testdata/recordings/TestAvailabilitySetsClient.json
  sdk/resourcemanager/compute/armcompute/testdata/recordings/TestVirtualMachineScaleSetsClient.json
  sdk/resourcemanager/compute/armcompute/testdata/recordings/TestVirtualMachinesClient.json
  sdk/resourcemanager/compute/armcompute/zt_availabilitysets_client_live_test.go
  sdk/resourcemanager/compute/armcompute/zt_virtualmachines_client_live_test.go
  sdk/resourcemanager/compute/armcompute/zt_virtualmachinescalesets_client_live_test.go
Labels: Mgmt

#17394 Use correct argument name in function description
  sdk/messaging/azservicebus/session_receiver.go
Labels: customer-reported

#17379 [KeyVault] adding KeyVault intro section to all readmes
  sdk/keyvault/azcertificates/README.md
  sdk/keyvault/azkeys/README.md
  sdk/keyvault/azsecrets/README.md
Labels: KeyVault

#17395 [Fabric Bot] Add CXP Responder
  .github/fabricbot.json
Labels: Client, EngSys

#17403 Increment version for messaging/internal releases
  sdk/messaging/internal/CHANGELOG.md
  sdk/messaging/internal/version.go
Labels: auto-merge

#17410 Sync eng/common directory with azure-sdk-tools for PR 2979
  eng/common/pipelines/templates/steps/check-spelling.yml
  eng/common/scripts/check-spelling-in-changed-files.ps1
Labels: EngSys, Central-EngSys

#16942 Add cloud configuration API to azcore
  sdk/azcore/CHANGELOG.md
  sdk/azcore/arm/arm.go
  sdk/azcore/arm/client_options.go
  sdk/azcore/arm/runtime/pipeline.go
  sdk/azcore/arm/runtime/pipeline_test.go
  sdk/azcore/arm/runtime/policy_bearer_token_test.go
  sdk/azcore/arm/runtime/policy_register_rp.go
  sdk/azcore/arm/runtime/policy_register_rp_test.go
  sdk/azcore/cloud/cloud.go
  sdk/azcore/cloud/doc.go
  sdk/azcore/internal/shared/shared.go
  sdk/azcore/internal/shared/shared_test.go
  sdk/azcore/policy/policy.go
Labels: Azure.Core
