Repository Azure/azure-sdk-for-go, pull requests merged in 2022-02, with the labels that each got.

#16954 Increment version for internal releases
  sdk/internal/CHANGELOG.md
  sdk/internal/version.go
Labels: auto-merge

#16946 Cloud Shell doesn't support user assigned identities
  sdk/azidentity/CHANGELOG.md
  sdk/azidentity/managed_identity_client.go
  sdk/azidentity/managed_identity_credential_test.go
Labels: Client, Azure.Identity

#16959 Sync eng/common directory with azure-sdk-tools for PR 2608
  eng/common/pipelines/templates/steps/update-docsms-metadata.yml
  eng/common/scripts/Helpers/Metadata-Helpers.ps1
  eng/common/scripts/Update-DocsMsMetadata.ps1
Labels: EngSys, Central-EngSys

#16958 Sync eng/common directory with azure-sdk-tools for PR 2605
  eng/common/scripts/Update-DocsMsMetadata.ps1
Labels: EngSys, Central-EngSys

#16970 Sync eng/common directory with azure-sdk-tools for PR 2673
  eng/common/scripts/Helpers/Metadata-Helpers.ps1
  eng/common/scripts/Update-DocsMsMetadata.ps1
Labels: EngSys, Central-EngSys

#16947 [KeyVault] Create azcertificates library
  eng/config.json
  sdk/keyvault/azcertificates/CHANGELOG.md
  sdk/keyvault/azcertificates/LICENSE.txt
  sdk/keyvault/azcertificates/README.md
  sdk/keyvault/azcertificates/autorest.md
  sdk/keyvault/azcertificates/ci.yml
  sdk/keyvault/azcertificates/client.go
  sdk/keyvault/azcertificates/client_test.go
  sdk/keyvault/azcertificates/constants.go
  sdk/keyvault/azcertificates/doc.go
  sdk/keyvault/azcertificates/example_test.go
  sdk/keyvault/azcertificates/go.mod
  sdk/keyvault/azcertificates/go.sum
  sdk/keyvault/azcertificates/internal/generated/constants.go
  sdk/keyvault/azcertificates/internal/generated/keyvault_client.go
  sdk/keyvault/azcertificates/internal/generated/models.go
  sdk/keyvault/azcertificates/internal/generated/pagers.go
  sdk/keyvault/azcertificates/internal/generated/response_types.go
  sdk/keyvault/azcertificates/internal/generated/roleassignments_client.go
  sdk/keyvault/azcertificates/internal/generated/roledefinitions_client.go
  sdk/keyvault/azcertificates/internal/generated/time_unix.go
  sdk/keyvault/azcertificates/models.go
  sdk/keyvault/azcertificates/test-resources.json
  sdk/keyvault/azcertificates/testdata/ca.crt
  sdk/keyvault/azcertificates/testdata/ca.key
  sdk/keyvault/azcertificates/testdata/recordings/TestCRUDOperations.json
  sdk/keyvault/azcertificates/testdata/recordings/TestClient_BackupCertificate.json
  sdk/keyvault/azcertificates/testdata/recordings/TestClient_BeginCreateCertificate.json
  sdk/keyvault/azcertificates/testdata/recordings/TestClient_BeginDeleteCertificate.json
  sdk/keyvault/azcertificates/testdata/recordings/TestClient_BeginRecoverDeletedCertificate.json
  sdk/keyvault/azcertificates/testdata/recordings/TestClient_CancelCertificateOperation.json
  sdk/keyvault/azcertificates/testdata/recordings/TestClient_ContactsCRUD.json
  sdk/keyvault/azcertificates/testdata/recordings/TestClient_GetCertificateOperation.json
  sdk/keyvault/azcertificates/testdata/recordings/TestClient_ImportCertificate.json
  sdk/keyvault/azcertificates/testdata/recordings/TestClient_IssuerCRUD.json
  sdk/keyvault/azcertificates/testdata/recordings/TestClient_ListCertificateVersions.json
  sdk/keyvault/azcertificates/testdata/recordings/TestClient_ListCertificates.json
  sdk/keyvault/azcertificates/testdata/recordings/TestClient_ListDeletedCertificates.json
  sdk/keyvault/azcertificates/testdata/recordings/TestClient_RestoreCertificateBackup.json
  sdk/keyvault/azcertificates/testdata/recordings/TestMergeCertificate.json
  sdk/keyvault/azcertificates/testdata/recordings/TestPolicy.json
  sdk/keyvault/azcertificates/utils_test.go
Labels: KeyVault

#16968 Sync eng/common directory with azure-sdk-tools for PR 2668
  eng/common/scripts/artifact-metadata-parsing.ps1
Labels: EngSys, Central-EngSys

#16981 Increment version for azcore releases
  sdk/azcore/CHANGELOG.md
  sdk/azcore/internal/shared/constants.go
Labels: auto-merge

#16983 Sync eng/common directory with azure-sdk-tools for PR 2682
  eng/common/scripts/stress-testing/find-all-stress-packages.ps1
Labels: EngSys, Central-EngSys

#16984 Sync eng/common directory with azure-sdk-tools for PR 2685
  eng/common/scripts/Helpers/Metadata-Helpers.ps1
  eng/common/scripts/Update-DocsMsMetadata.ps1
Labels: EngSys, Central-EngSys

#16901 Fix SAS Creation + other issue
  sdk/storage/azblob/CHANGELOG.md
  sdk/storage/azblob/zc_container_client.go
  sdk/storage/azblob/zc_sas_account.go
  sdk/storage/azblob/zc_sas_query_params.go
  sdk/storage/azblob/zc_sas_service.go
  sdk/storage/azblob/zc_validators.go
  sdk/storage/azblob/zm_blob_request_options.go
Labels: Storage

#16978 [Storage] convert options to take pointer
  sdk/storage/azblob/CHANGELOG.md
  sdk/storage/azblob/highlevel.go
  sdk/storage/azblob/zc_response_helpers.go
  sdk/storage/azblob/zt_append_blob_client_test.go
  sdk/storage/azblob/zt_blob_client_test.go
  sdk/storage/azblob/zt_blob_tags_test.go
  sdk/storage/azblob/zt_blob_versioning_test.go
  sdk/storage/azblob/zt_block_blob_client_test.go
  sdk/storage/azblob/zt_client_provided_key_test.go
  sdk/storage/azblob/zt_examples_test.go
  sdk/storage/azblob/zt_page_blob_client_test.go
Labels: Storage

#16991 Sync eng/common directory with azure-sdk-tools for PR 2691
  eng/common/scripts/Helpers/DevOps-WorkItem-Helpers.ps1
  eng/common/scripts/Prepare-Release.ps1
Labels: EngSys, Central-EngSys

#16999 [Certificates] Add Date to changelog
  sdk/keyvault/azcertificates/CHANGELOG.md
Labels: KeyVault

#16992 azblob: fix ListBlob to preserve prefix while paging
  sdk/storage/azblob/zc_container_client.go
  sdk/storage/azblob/zc_service_client.go
Labels: Storage, customer-reported

#17002 Increment version for keyvault/azkeys releases
  sdk/keyvault/azkeys/CHANGELOG.md
  sdk/keyvault/azkeys/internal/generated/constants.go
Labels: KeyVault, auto-merge

#17003 Correct the date
  sdk/keyvault/azcertificates/CHANGELOG.md
Labels: KeyVault, auto-merge

#16986 Revise azidentity error messages
  sdk/azidentity/CHANGELOG.md
  sdk/azidentity/authorization_code_credential.go
  sdk/azidentity/azure_cli_credential.go
  sdk/azidentity/chained_token_credential.go
  sdk/azidentity/chained_token_credential_test.go
  sdk/azidentity/client_certificate_credential.go
  sdk/azidentity/client_secret_credential.go
  sdk/azidentity/default_azure_credential.go
  sdk/azidentity/device_code_credential.go
  sdk/azidentity/environment_credential.go
  sdk/azidentity/errors.go
  sdk/azidentity/interactive_browser_credential.go
  sdk/azidentity/managed_identity_client.go
  sdk/azidentity/managed_identity_credential.go
  sdk/azidentity/username_password_credential.go
Labels: Client, Azure.Identity

#16945 [Storage] improving documentation
  sdk/storage/azblob/CHANGELOG.md
  sdk/storage/azblob/README.md
  sdk/storage/azblob/doc.go
  sdk/storage/azblob/zc_service_client.go
  sdk/storage/azblob/zt_examples_test.go
Labels: Storage

#17006 Increment version for keyvault/azcertificates releases
  sdk/keyvault/azcertificates/CHANGELOG.md
  sdk/keyvault/azcertificates/internal/generated/constants.go
Labels: KeyVault, auto-merge

#17005 Sync eng/common directory with azure-sdk-tools for PR 2686
  eng/common/pipelines/templates/steps/credscan.yml
Labels: EngSys, Central-EngSys

#17004 Increment version for messaging/azservicebus releases
  sdk/messaging/azservicebus/CHANGELOG.md
  sdk/messaging/azservicebus/internal/constants.go
Labels: auto-merge

#17007 Remove empty changelog section
  sdk/azidentity/CHANGELOG.md
Labels: Client, Azure.Identity

#17008 Upgrade azidentity internal dependency
  sdk/azidentity/go.mod
  sdk/azidentity/go.sum
Labels: Azure.Identity

#17011 Increment version for azidentity releases
  sdk/azidentity/CHANGELOG.md
  sdk/azidentity/version.go
Labels: auto-merge

#17012 Sync eng/common directory with azure-sdk-tools for PR 2720
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: EngSys, Central-EngSys

#17020 Update CHANGELOG.md
  sdk/storage/azblob/CHANGELOG.md
Labels: Storage, auto-merge

#17022 Increment version for storage/azblob releases
  sdk/storage/azblob/CHANGELOG.md
  sdk/storage/azblob/zz_generated_constants.go
Labels: Storage, auto-merge

#16857 [KeyVault] Add Immutable Property
  sdk/keyvault/azkeys/CHANGELOG.md
  sdk/keyvault/azkeys/autorest.md
  sdk/keyvault/azkeys/client.go
  sdk/keyvault/azkeys/client_test.go
  sdk/keyvault/azkeys/constants.go
  sdk/keyvault/azkeys/constants_test.go
  sdk/keyvault/azkeys/example_test.go
  sdk/keyvault/azkeys/internal/generated/keyvault_client.go
  sdk/keyvault/azkeys/internal/generated/models.go
  sdk/keyvault/azkeys/internal/generated/response_types.go
  sdk/keyvault/azkeys/internal/generated/time_unix.go
  sdk/keyvault/azkeys/models.go
  sdk/keyvault/azkeys/testdata/recordings/TestUpdateKeyPropertiesImmutable/TestUpdateKeyPropertiesImmutable_NON-HSM.json
Labels: KeyVault

#17001 Increment version for keyvault/azsecrets releases
  sdk/keyvault/azsecrets/CHANGELOG.md
  sdk/keyvault/azsecrets/internal/constants.go
Labels: KeyVault, auto-merge

#16993 Sync eng/common directory with azure-sdk-tools for PR 2679
  eng/common/TestResources/New-TestResources.ps1
  eng/common/TestResources/Update-TestResources.ps1
Labels: EngSys, Central-EngSys

#17026 [KeyVault] Fixing issue with returned empty struct from DeleteKey poller
  sdk/keyvault/azkeys/client.go
  sdk/keyvault/azkeys/client_test.go
Labels: KeyVault

#16532 [Tables] update internal and improve code coverage
  eng/config.json
  sdk/data/aztables/client_test.go
  sdk/data/aztables/proxy_test.go
  sdk/data/aztables/testdata/recordings/TestAddComplexEntity/TestAddComplexEntity_cosmos.json
  sdk/data/aztables/testdata/recordings/TestAddComplexEntity/TestAddComplexEntity_storage.json
  sdk/data/aztables/testdata/recordings/TestBatchAdd/TestBatchAdd_cosmos.json
  sdk/data/aztables/testdata/recordings/TestBatchAdd/TestBatchAdd_storage.json
  sdk/data/aztables/testdata/recordings/TestBatchComplex/TestBatchComplex_cosmos.json
  sdk/data/aztables/testdata/recordings/TestBatchComplex/TestBatchComplex_storage.json
  sdk/data/aztables/testdata/recordings/TestBatchError/TestBatchError_cosmos.json
  sdk/data/aztables/testdata/recordings/TestBatchError/TestBatchError_storage.json
  sdk/data/aztables/testdata/recordings/TestBatchInsert/TestBatchInsert_cosmos.json
  sdk/data/aztables/testdata/recordings/TestBatchInsert/TestBatchInsert_storage.json
  sdk/data/aztables/testdata/recordings/TestBatchMixed/TestBatchMixed_cosmos.json
  sdk/data/aztables/testdata/recordings/TestBatchMixed/TestBatchMixed_storage.json
  sdk/data/aztables/testdata/recordings/TestQueryComplexEntity/TestQueryComplexEntity_cosmos.json
  sdk/data/aztables/testdata/recordings/TestQueryComplexEntity/TestQueryComplexEntity_storage.json
  sdk/data/aztables/transaction_batch_test.go
Labels: Tables

#17037 Sync eng/common directory with azure-sdk-tools for PR 2739
  eng/common/pipelines/templates/steps/credscan.yml
Labels: EngSys, Central-EngSys

#17035 remove raw responses
  sdk/keyvault/azkeys/client.go
  sdk/keyvault/azkeys/client_test.go
  sdk/keyvault/azkeys/crypto/crypto_client.go
  sdk/keyvault/azkeys/crypto/responses/responses.go
  sdk/keyvault/azkeys/responses/pagers.go
  sdk/keyvault/azkeys/responses/pollers.go
  sdk/keyvault/azkeys/responses/responses.go
Labels: KeyVault

#17043 Sync eng/common directory with azure-sdk-tools for PR 2740
  eng/common/pipelines/templates/steps/credscan.yml
Labels: EngSys, Central-EngSys

#17040 Increment version for messaging/azservicebus releases
  sdk/messaging/azservicebus/CHANGELOG.md
  sdk/messaging/azservicebus/internal/constants.go
Labels: auto-merge

#17063 Document that nil credential options get default settings
  sdk/azidentity/authorization_code_credential.go
  sdk/azidentity/azure_cli_credential.go
  sdk/azidentity/chained_token_credential.go
  sdk/azidentity/client_certificate_credential.go
  sdk/azidentity/client_secret_credential.go
  sdk/azidentity/device_code_credential.go
  sdk/azidentity/environment_credential.go
  sdk/azidentity/interactive_browser_credential.go
  sdk/azidentity/managed_identity_credential.go
  sdk/azidentity/username_password_credential.go
Labels: Docs, Azure.Identity

#17059 Return topic name in subscription properties item
  sdk/messaging/azservicebus/admin/admin_client_subscription.go
  sdk/messaging/azservicebus/admin/admin_client_test.go
Labels: customer-reported

#17073 Sync eng/common directory with azure-sdk-tools for PR 2754
  eng/common/pipelines/templates/steps/credscan.yml
Labels: EngSys, Central-EngSys

#17050 Sync eng/common directory with azure-sdk-tools for PR 2741
  eng/common/TestResources/New-TestResources.ps1
Labels: EngSys, Central-EngSys

#17072 Sync eng/common directory with azure-sdk-tools for PR 2758
  eng/common/testproxy/docker-start-proxy.ps1
  eng/common/testproxy/test-proxy-tool.yml
  sdk/internal/recording/recording.go
  sdk/internal/recording/sanitizer.go
  sdk/internal/recording/sanitizer_test.go
Labels: EngSys, Central-EngSys

#17086 Upgrade App Service managed identity version
  sdk/azidentity/CHANGELOG.md
  sdk/azidentity/managed_identity_client.go
  sdk/azidentity/managed_identity_client_test.go
  sdk/azidentity/managed_identity_credential_test.go
Labels: Client, Azure.Identity

#17081 Sync eng/common directory with azure-sdk-tools for PR 2759
  eng/common/scripts/Update-DocsMsToc.ps1
  eng/common/scripts/common.ps1
Labels: EngSys, Central-EngSys

#17098 Sync eng/common directory with azure-sdk-tools for PR 2775
  eng/common/pipelines/templates/steps/credscan.yml
Labels: EngSys, Central-EngSys

#17100 Sync eng/common directory with azure-sdk-tools for PR 2768
  eng/common/scripts/Verify-Links.ps1
Labels: EngSys, Central-EngSys

#17085 Sync eng/common directory with azure-sdk-tools for PR 2765
  eng/common/pipelines/templates/steps/install-pipeline-generation.yml
Labels: EngSys, Central-EngSys

#17074 Sync eng/common directory with azure-sdk-tools for PR 2750
  eng/common/pipelines/templates/steps/prepare-pipelines.yml
Labels: EngSys, Central-EngSys

#17107 Add missing 'or' expression to find command in track 1 test discovery
  azure-pipelines.yml
Labels: EngSys, Central-EngSys

#17140 [Tables] Improving documentation on client methods
  sdk/data/aztables/client.go
  sdk/data/aztables/connection_string.go
  sdk/data/aztables/service_client.go
Labels: Tables, auto-merge

#17039 Revise azidentity logging
  sdk/azidentity/authorization_code_credential.go
  sdk/azidentity/azure_cli_credential.go
  sdk/azidentity/chained_token_credential.go
  sdk/azidentity/client_certificate_credential.go
  sdk/azidentity/client_secret_credential.go
  sdk/azidentity/default_azure_credential.go
  sdk/azidentity/default_azure_credential_test.go
  sdk/azidentity/device_code_credential.go
  sdk/azidentity/environment_credential.go
  sdk/azidentity/interactive_browser_credential.go
  sdk/azidentity/logging.go
  sdk/azidentity/managed_identity_client.go
  sdk/azidentity/managed_identity_credential.go
  sdk/azidentity/username_password_credential.go
Labels: Client, Azure.Identity

#17142 Update CODEOWNERS
  .github/CODEOWNERS
Labels: auto-merge

#17163 Sync eng/common directory with azure-sdk-tools for PR 2805
  eng/common/scripts/Update-DocsMsToc.ps1
Labels: EngSys, Central-EngSys

#17097 [KeyVault] adding a comment about nil options
  sdk/keyvault/azkeys/CHANGELOG.md
  sdk/keyvault/azkeys/client.go
  sdk/keyvault/azkeys/client_test.go
  sdk/keyvault/azkeys/testdata/recordings/TestCreateOCTKey/TestCreateOCTKey_NON-HSM.json
Labels: KeyVault

#17164 Sync eng/common directory with azure-sdk-tools for PR 2808
  eng/common/scripts/Detect-Api-Changes.ps1
Labels: EngSys, Central-EngSys

#17180 Sync eng/common directory with azure-sdk-tools for PR 2771
  eng/common/scripts/copy-from-blobstorage.ps1
Labels: EngSys, Central-EngSys
