Repository Azure/azure-sdk-for-go, pull requests merged in 2024-09, with the labels that each got.

#23393 Increment version for storage/azdatalake releases
  sdk/storage/azdatalake/CHANGELOG.md
  sdk/storage/azdatalake/internal/exported/version.go
Labels: Storage

#23397 Sync eng/common directory with azure-sdk-tools for PR 8912
  eng/common/scripts/Package-Properties.ps1
Labels: EngSys, Central-EngSys

#23398 Sync eng/common directory with azure-sdk-tools for PR 8887
  eng/common/scripts/Verify-Links.ps1
Labels: EngSys, Central-EngSys

#23402 Sync eng/common directory with azure-sdk-tools for PR 8928
  eng/common/spelling/package-lock.json
Labels: EngSys, Central-EngSys

#23400 [azservicebus] Fixing a bug where our management link would hang in certain circumstances
  sdk/messaging/azeventhubs/CHANGELOG.md
  sdk/messaging/azeventhubs/internal/constants.go
  sdk/messaging/azeventhubs/internal/rpc.go
  sdk/messaging/azeventhubs/internal/rpc_test.go
  sdk/messaging/azservicebus/CHANGELOG.md
  sdk/messaging/azservicebus/internal/rpc.go
  sdk/messaging/azservicebus/internal/rpc_test.go
Labels: Service Bus

#23404 Update managed identity docs
  sdk/azidentity/example_test.go
  sdk/azidentity/managed_identity_credential.go
Labels: Azure.Identity

#23408 [aznamespaces] Fix examples so they use a credential that will work in test pipelines
  sdk/messaging/eventgrid/aznamespaces/example_publish_and_receive_test.go
  sdk/messaging/eventgrid/aznamespaces/example_test.go
  sdk/messaging/eventgrid/aznamespaces/go.mod
Labels: Event Grid

#23406 Add support for MaxIntegratedCacheStaleness option
  sdk/data/azcosmos/CHANGELOG.md
  sdk/data/azcosmos/cosmos_dedicated_gateway_request_options.go
  sdk/data/azcosmos/cosmos_http_constants.go
  sdk/data/azcosmos/cosmos_item_request_options.go
  sdk/data/azcosmos/cosmos_item_request_options_test.go
  sdk/data/azcosmos/cosmos_query_request_options.go
  sdk/data/azcosmos/cosmos_query_request_options_test.go
Labels: Cosmos, customer-reported, Community Contribution

#23407 Remove redundant auth error content
  sdk/azidentity/CHANGELOG.md
  sdk/azidentity/azidentity_test.go
  sdk/azidentity/azure_cli_credential_test.go
  sdk/azidentity/azure_developer_cli_credential_test.go
  sdk/azidentity/azure_pipelines_credential.go
  sdk/azidentity/chained_token_credential.go
  sdk/azidentity/chained_token_credential_test.go
  sdk/azidentity/confidential_client.go
  sdk/azidentity/errors.go
  sdk/azidentity/errors_test.go
  sdk/azidentity/managed_identity_client.go
  sdk/azidentity/public_client.go
Labels: Azure.Identity

#23415 Sync .github/workflows directory with azure-sdk-tools for PR 8942
  .github/workflows/event-processor.yml
  .github/workflows/scheduled-event-processor.yml
Labels: EngSys, Central-EngSys

#23412 Sync eng/common directory with azure-sdk-tools for PR 8929
  eng/common/pipelines/templates/jobs/prepare-pipelines.yml
Labels: EngSys, Central-EngSys

#23416 [azsystemevents] Fixing broken links in readme.
  sdk/messaging/eventgrid/azsystemevents/README.md
Labels: Event Grid

#23410 Sync eng/common directory with azure-sdk-tools for PR 8902
  eng/common/TestResources/SubConfig-Helpers.ps1
  eng/common/TestResources/deploy-test-resources.yml
Labels: EngSys, Central-EngSys

#23420 [azservicebus] updating changelog to reflect a release date of today
  sdk/messaging/azservicebus/CHANGELOG.md
  sdk/messaging/azservicebus/receiver_test.go
Labels: Service Bus

#23422 [Cosmos] versions upgrade for release
  sdk/data/azcosmos/CHANGELOG.md
  sdk/data/azcosmos/version.go
Labels: Cosmos

#23425 [azservicebus] Stub out appinsights so this package can be released
  sdk/messaging/azservicebus/CHANGELOG.md
  sdk/messaging/azservicebus/go.mod
  sdk/messaging/azservicebus/go.sum
  sdk/messaging/azservicebus/internal/stress/shared/stress_context.go
  sdk/messaging/azservicebus/internal/stress/shared/tracking_receiver.go
  sdk/messaging/azservicebus/internal/stress/shared/tracking_sender.go
Labels: Service Bus

#23426 Increment version for data/azcosmos releases
  sdk/data/azcosmos/CHANGELOG.md
  sdk/data/azcosmos/version.go
Labels: Cosmos

#23428 Create credential chains section in Azure Identity README
  sdk/azidentity/README.md
Labels: Azure.Identity

#23430 Add auto-baseline main pipeline config for core
  eng/pipelines/templates/stages/1es-redirect.yml
Labels: Central-EngSys

#23432 Sync eng/common directory with azure-sdk-tools for PR 8958
  eng/common/scripts/stress-testing/find-all-stress-packages.ps1
Labels: EngSys, Central-EngSys

#23436 [Storage] Swagger update for stg95
  sdk/storage/azblob/internal/generated/autorest.md
  sdk/storage/azblob/internal/generated/constants.go
  sdk/storage/azblob/internal/generated/zz_appendblob_client.go
  sdk/storage/azblob/internal/generated/zz_blob_client.go
  sdk/storage/azblob/internal/generated/zz_blockblob_client.go
  sdk/storage/azblob/internal/generated/zz_container_client.go
  sdk/storage/azblob/internal/generated/zz_pageblob_client.go
  sdk/storage/azblob/internal/generated/zz_service_client.go
  sdk/storage/azfile/internal/generated/autorest.md
  sdk/storage/azfile/internal/generated/constants.go
  sdk/storage/azfile/internal/generated/zz_constants.go
  sdk/storage/azfile/internal/generated/zz_directory_client.go
  sdk/storage/azfile/internal/generated/zz_file_client.go
  sdk/storage/azfile/internal/generated/zz_models.go
  sdk/storage/azfile/internal/generated/zz_models_serde.go
  sdk/storage/azfile/internal/generated/zz_options.go
  sdk/storage/azfile/internal/generated/zz_response_types.go
  sdk/storage/azfile/internal/generated/zz_service_client.go
  sdk/storage/azfile/internal/generated/zz_share_client.go
Labels: Storage

#23433 Sync eng/common directory with azure-sdk-tools for PR 8959
  eng/common/pipelines/templates/steps/publish-1es-artifact.yml
Labels: EngSys, Central-EngSys

#23437 Sync eng/common directory with azure-sdk-tools for PR 8963
  eng/common/pipelines/templates/steps/run-pester-tests.yml
Labels: EngSys, Central-EngSys

#23434 Prepare azidentity v1.8.0-beta.3 for release
  sdk/azidentity/CHANGELOG.md
Labels: Azure.Identity

#23447 Increment version for azidentity releases
  sdk/azidentity/CHANGELOG.md
  sdk/azidentity/version.go
Labels: Azure.Identity

#23448 [query/azlogs] prep for release
  sdk/monitor/query/azlogs/CHANGELOG.md
  sdk/monitor/query/azlogs/go.mod
  sdk/monitor/query/azlogs/go.sum
Labels: Monitor, Client

#23449 Sync eng/common directory with azure-sdk-tools for PR 8994
  eng/common/pipelines/codeowners-linter.yml
Labels: EngSys, Central-EngSys

#23451 Sync .github/workflows directory with azure-sdk-tools for PR 8995
  .github/workflows/event-processor.yml
  .github/workflows/scheduled-event-processor.yml
Labels: EngSys, Central-EngSys

#23452 [Storage] Prep for release - Changelog changes for blob and files release
  sdk/storage/azblob/CHANGELOG.md
  sdk/storage/azblob/internal/exported/version.go
  sdk/storage/azfile/CHANGELOG.md
  sdk/storage/azfile/internal/exported/version.go
Labels: Storage

#23456 Increment version for storage/azblob releases
  sdk/storage/azblob/CHANGELOG.md
  sdk/storage/azblob/internal/exported/version.go
Labels: Storage

#23457 Increment version for storage/azfile releases
  sdk/storage/azfile/CHANGELOG.md
  sdk/storage/azfile/internal/exported/version.go
Labels: Storage

#23453 Sync eng/common directory with azure-sdk-tools for PR 9000
  eng/common/pipelines/templates/jobs/perf.yml
Labels: EngSys, Central-EngSys

#23460 Sync eng/common directory with azure-sdk-tools for PR 9004
  eng/common/scripts/Helpers/Metadata-Helpers.ps1
Labels: EngSys, Central-EngSys

#23461 [azsystemevents] Regenerating system events for Sept
  sdk/messaging/eventgrid/azsystemevents/CHANGELOG.md
  sdk/messaging/eventgrid/azsystemevents/models.go
  sdk/messaging/eventgrid/azsystemevents/models_serde.go
  sdk/messaging/eventgrid/azsystemevents/testdata/tsp-location.yaml
Labels: Event Grid

#23455 Sync eng/common directory with azure-sdk-tools for PR 8998
  eng/common/pipelines/templates/steps/verify-readmes.yml
Labels: EngSys, Central-EngSys

#23466 Sync eng/common directory with azure-sdk-tools for PR 9008
  eng/common/scripts/Package-Properties.ps1
Labels: EngSys, Central-EngSys

#23459 Increment version for monitor/query/azlogs releases
  sdk/monitor/query/azlogs/CHANGELOG.md
  sdk/monitor/query/azlogs/version.go
Labels: Monitor

#23467 Sync eng/common directory with azure-sdk-tools for PR 9016
  eng/common/testproxy/target_version.txt
Labels: EngSys, Central-EngSys

#23478 [Storage] stg94 Adls release
  sdk/storage/azdatalake/CHANGELOG.md
  sdk/storage/azdatalake/go.mod
  sdk/storage/azdatalake/go.sum
  sdk/storage/azdatalake/internal/exported/version.go
Labels: Storage

#23483 Increment version for storage/azdatalake releases
  sdk/storage/azdatalake/CHANGELOG.md
  sdk/storage/azdatalake/internal/exported/version.go
Labels: Storage

#23484 Updating CODEOWNERS for 1espt config
  .github/CODEOWNERS
Labels: Central-EngSys

#23468 Sync eng/common directory with azure-sdk-tools for PR 9013
  eng/common/scripts/check-spelling-in-changed-files.ps1
  eng/common/spelling/Invoke-Cspell.ps1
Labels: EngSys, Central-EngSys

#23297 [Release] sdk/resourcemanager/elasticsan/armelasticsan/1.1.0
  sdk/resourcemanager/elasticsan/armelasticsan/CHANGELOG.md
  sdk/resourcemanager/elasticsan/armelasticsan/autorest.md
  sdk/resourcemanager/elasticsan/armelasticsan/client_factory.go
  sdk/resourcemanager/elasticsan/armelasticsan/constants.go
  sdk/resourcemanager/elasticsan/armelasticsan/elasticsans_client.go
  sdk/resourcemanager/elasticsan/armelasticsan/elasticsans_client_example_test.go
  sdk/resourcemanager/elasticsan/armelasticsan/fake/time_rfc3339.go
  sdk/resourcemanager/elasticsan/armelasticsan/models.go
  sdk/resourcemanager/elasticsan/armelasticsan/models_serde.go
  sdk/resourcemanager/elasticsan/armelasticsan/operations_client.go
  sdk/resourcemanager/elasticsan/armelasticsan/operations_client_example_test.go
  sdk/resourcemanager/elasticsan/armelasticsan/privateendpointconnections_client.go
  sdk/resourcemanager/elasticsan/armelasticsan/privateendpointconnections_client_example_test.go
  sdk/resourcemanager/elasticsan/armelasticsan/privatelinkresources_client.go
  sdk/resourcemanager/elasticsan/armelasticsan/privatelinkresources_client_example_test.go
  sdk/resourcemanager/elasticsan/armelasticsan/responses.go
  sdk/resourcemanager/elasticsan/armelasticsan/skus_client.go
  sdk/resourcemanager/elasticsan/armelasticsan/skus_client_example_test.go
  sdk/resourcemanager/elasticsan/armelasticsan/time_rfc3339.go
  sdk/resourcemanager/elasticsan/armelasticsan/volumegroups_client.go
  sdk/resourcemanager/elasticsan/armelasticsan/volumegroups_client_example_test.go
  sdk/resourcemanager/elasticsan/armelasticsan/volumes_client.go
  sdk/resourcemanager/elasticsan/armelasticsan/volumes_client_example_test.go
  sdk/resourcemanager/elasticsan/armelasticsan/volumesnapshots_client.go
  sdk/resourcemanager/elasticsan/armelasticsan/volumesnapshots_client_example_test.go
Labels: Stable

#23209 [Release] sdk/resourcemanager/eventhub/armeventhub/1.3.0
  sdk/resourcemanager/eventhub/armeventhub/CHANGELOG.md
  sdk/resourcemanager/eventhub/armeventhub/README.md
  sdk/resourcemanager/eventhub/armeventhub/applicationgroup_client.go
  sdk/resourcemanager/eventhub/armeventhub/applicationgroup_client_example_test.go
  sdk/resourcemanager/eventhub/armeventhub/assets.json
  sdk/resourcemanager/eventhub/armeventhub/autorest.md
  sdk/resourcemanager/eventhub/armeventhub/client_factory.go
  sdk/resourcemanager/eventhub/armeventhub/clusters_client.go
  sdk/resourcemanager/eventhub/armeventhub/clusters_client_example_test.go
  sdk/resourcemanager/eventhub/armeventhub/configuration_client.go
  sdk/resourcemanager/eventhub/armeventhub/configuration_client_example_test.go
  sdk/resourcemanager/eventhub/armeventhub/constants.go
  sdk/resourcemanager/eventhub/armeventhub/consumergroups_client.go
  sdk/resourcemanager/eventhub/armeventhub/consumergroups_client_example_test.go
  sdk/resourcemanager/eventhub/armeventhub/disasterrecoveryconfigs_client.go
  sdk/resourcemanager/eventhub/armeventhub/disasterrecoveryconfigs_client_example_test.go
  sdk/resourcemanager/eventhub/armeventhub/eventhubs_client.go
  sdk/resourcemanager/eventhub/armeventhub/eventhubs_client_example_test.go
  sdk/resourcemanager/eventhub/armeventhub/fake/time_rfc3339.go
  sdk/resourcemanager/eventhub/armeventhub/models.go
  sdk/resourcemanager/eventhub/armeventhub/models_serde.go
  sdk/resourcemanager/eventhub/armeventhub/namespaces_client.go
  sdk/resourcemanager/eventhub/armeventhub/namespaces_client_example_test.go
  sdk/resourcemanager/eventhub/armeventhub/networksecurityperimeterconfiguration_client.go
  sdk/resourcemanager/eventhub/armeventhub/networksecurityperimeterconfiguration_client_example_test.go
  sdk/resourcemanager/eventhub/armeventhub/networksecurityperimeterconfigurations_client.go
  sdk/resourcemanager/eventhub/armeventhub/networksecurityperimeterconfigurations_client_example_test.go
  sdk/resourcemanager/eventhub/armeventhub/operations_client.go
  sdk/resourcemanager/eventhub/armeventhub/operations_client_example_test.go
  sdk/resourcemanager/eventhub/armeventhub/polymorphic_helpers.go
  sdk/resourcemanager/eventhub/armeventhub/privateendpointconnections_client.go
  sdk/resourcemanager/eventhub/armeventhub/privateendpointconnections_client_example_test.go
  sdk/resourcemanager/eventhub/armeventhub/privatelinkresources_client.go
  sdk/resourcemanager/eventhub/armeventhub/privatelinkresources_client_example_test.go
  sdk/resourcemanager/eventhub/armeventhub/responses.go
  sdk/resourcemanager/eventhub/armeventhub/schemaregistry_client.go
  sdk/resourcemanager/eventhub/armeventhub/schemaregistry_client_example_test.go
  sdk/resourcemanager/eventhub/armeventhub/time_rfc3339.go
Labels: Mgmt, Stable

#23497 Sync eng/common directory with azure-sdk-tools for PR 9035
  eng/common/scripts/Verify-ChangeLogs.ps1
Labels: EngSys, Central-EngSys

#23469 Increment version for messaging/eventgrid/azsystemevents releases
  sdk/messaging/eventgrid/azsystemevents/CHANGELOG.md
  sdk/messaging/eventgrid/azsystemevents/internal/version.go
Labels: Event Grid

#23475 [azadmin] change frequency of poller in tests
  sdk/security/keyvault/azadmin/backup/client_test.go
Labels: KeyVault, Client, test-enhancement

#23392 [Release] sdk/resourcemanager/fabric/armfabric/0.1.0
  sdk/resourcemanager/fabric/armfabric/CHANGELOG.md
  sdk/resourcemanager/fabric/armfabric/LICENSE.txt
  sdk/resourcemanager/fabric/armfabric/README.md
  sdk/resourcemanager/fabric/armfabric/autorest.md
  sdk/resourcemanager/fabric/armfabric/build.go
  sdk/resourcemanager/fabric/armfabric/capacities_client.go
  sdk/resourcemanager/fabric/armfabric/capacities_client_example_test.go
  sdk/resourcemanager/fabric/armfabric/ci.yml
  sdk/resourcemanager/fabric/armfabric/client_factory.go
  sdk/resourcemanager/fabric/armfabric/constants.go
  sdk/resourcemanager/fabric/armfabric/fake/capacities_server.go
  sdk/resourcemanager/fabric/armfabric/fake/internal.go
  sdk/resourcemanager/fabric/armfabric/fake/operations_server.go
  sdk/resourcemanager/fabric/armfabric/fake/server_factory.go
  sdk/resourcemanager/fabric/armfabric/fake/time_rfc3339.go
  sdk/resourcemanager/fabric/armfabric/go.mod
  sdk/resourcemanager/fabric/armfabric/go.sum
  sdk/resourcemanager/fabric/armfabric/models.go
  sdk/resourcemanager/fabric/armfabric/models_serde.go
  sdk/resourcemanager/fabric/armfabric/operations_client.go
  sdk/resourcemanager/fabric/armfabric/operations_client_example_test.go
  sdk/resourcemanager/fabric/armfabric/options.go
  sdk/resourcemanager/fabric/armfabric/responses.go
  sdk/resourcemanager/fabric/armfabric/time_rfc3339.go
Labels: FirstGA

#23500 [Release] sdk/resourcemanager/servicenetworking/armservicenetworking/1.1.0-beta.2
  sdk/resourcemanager/servicenetworking/armservicenetworking/CHANGELOG.md
  sdk/resourcemanager/servicenetworking/armservicenetworking/associationsinterface_client_example_test.go
  sdk/resourcemanager/servicenetworking/armservicenetworking/autorest.md
  sdk/resourcemanager/servicenetworking/armservicenetworking/constants.go
  sdk/resourcemanager/servicenetworking/armservicenetworking/fake/securitypoliciesinterface_server.go
  sdk/resourcemanager/servicenetworking/armservicenetworking/frontendsinterface_client_example_test.go
  sdk/resourcemanager/servicenetworking/armservicenetworking/operations_client_example_test.go
  sdk/resourcemanager/servicenetworking/armservicenetworking/securitypoliciesinterface_client.go
  sdk/resourcemanager/servicenetworking/armservicenetworking/securitypoliciesinterface_client_example_test.go
  sdk/resourcemanager/servicenetworking/armservicenetworking/trafficcontrollerinterface_client_example_test.go
Labels: Mgmt

#23390 [Release] sdk/resourcemanager/containerservice/armcontainerservice/6.1.0-beta.2
  sdk/resourcemanager/containerservice/armcontainerservice/CHANGELOG.md
  sdk/resourcemanager/containerservice/armcontainerservice/agentpools_client.go
  sdk/resourcemanager/containerservice/armcontainerservice/agentpools_client_example_test.go
  sdk/resourcemanager/containerservice/armcontainerservice/assets.json
  sdk/resourcemanager/containerservice/armcontainerservice/autorest.md
  sdk/resourcemanager/containerservice/armcontainerservice/constants.go
  sdk/resourcemanager/containerservice/armcontainerservice/loadbalancers_client.go
  sdk/resourcemanager/containerservice/armcontainerservice/loadbalancers_client_example_test.go
  sdk/resourcemanager/containerservice/armcontainerservice/machines_client.go
  sdk/resourcemanager/containerservice/armcontainerservice/machines_client_example_test.go
  sdk/resourcemanager/containerservice/armcontainerservice/maintenanceconfigurations_client.go
  sdk/resourcemanager/containerservice/armcontainerservice/maintenanceconfigurations_client_example_test.go
  sdk/resourcemanager/containerservice/armcontainerservice/managedclusters_client.go
  sdk/resourcemanager/containerservice/armcontainerservice/managedclusters_client_example_test.go
  sdk/resourcemanager/containerservice/armcontainerservice/managedclustersnapshots_client.go
  sdk/resourcemanager/containerservice/armcontainerservice/managedclustersnapshots_client_example_test.go
  sdk/resourcemanager/containerservice/armcontainerservice/models.go
  sdk/resourcemanager/containerservice/armcontainerservice/models_serde.go
  sdk/resourcemanager/containerservice/armcontainerservice/operations_client.go
  sdk/resourcemanager/containerservice/armcontainerservice/operations_client_example_test.go
  sdk/resourcemanager/containerservice/armcontainerservice/operationstatusresult_client.go
  sdk/resourcemanager/containerservice/armcontainerservice/operationstatusresult_client_example_test.go
  sdk/resourcemanager/containerservice/armcontainerservice/privateendpointconnections_client.go
  sdk/resourcemanager/containerservice/armcontainerservice/privateendpointconnections_client_example_test.go
  sdk/resourcemanager/containerservice/armcontainerservice/privatelinkresources_client.go
  sdk/resourcemanager/containerservice/armcontainerservice/privatelinkresources_client_example_test.go
  sdk/resourcemanager/containerservice/armcontainerservice/resolveprivatelinkserviceid_client.go
  sdk/resourcemanager/containerservice/armcontainerservice/resolveprivatelinkserviceid_client_example_test.go
  sdk/resourcemanager/containerservice/armcontainerservice/snapshots_client.go
  sdk/resourcemanager/containerservice/armcontainerservice/snapshots_client_example_test.go
  sdk/resourcemanager/containerservice/armcontainerservice/trustedaccessrolebindings_client.go
  sdk/resourcemanager/containerservice/armcontainerservice/trustedaccessrolebindings_client_example_test.go
  sdk/resourcemanager/containerservice/armcontainerservice/trustedaccessroles_client.go
  sdk/resourcemanager/containerservice/armcontainerservice/trustedaccessroles_client_example_test.go
Labels: Beta

#23435 [Release] sdk/resourcemanager/devhub/armdevhub/0.6.0
  sdk/resourcemanager/devhub/armdevhub/CHANGELOG.md
  sdk/resourcemanager/devhub/armdevhub/README.md
  sdk/resourcemanager/devhub/armdevhub/autorest.md
  sdk/resourcemanager/devhub/armdevhub/client_factory.go
  sdk/resourcemanager/devhub/armdevhub/constants.go
  sdk/resourcemanager/devhub/armdevhub/developerhubservice_client.go
  sdk/resourcemanager/devhub/armdevhub/developerhubservice_client_example_test.go
  sdk/resourcemanager/devhub/armdevhub/fake/iacprofiles_server.go
  sdk/resourcemanager/devhub/armdevhub/fake/server_factory.go
  sdk/resourcemanager/devhub/armdevhub/fake/time_rfc3339.go
  sdk/resourcemanager/devhub/armdevhub/iacprofiles_client.go
  sdk/resourcemanager/devhub/armdevhub/iacprofiles_client_example_test.go
  sdk/resourcemanager/devhub/armdevhub/models.go
  sdk/resourcemanager/devhub/armdevhub/models_serde.go
  sdk/resourcemanager/devhub/armdevhub/operations_client.go
  sdk/resourcemanager/devhub/armdevhub/operations_client_example_test.go
  sdk/resourcemanager/devhub/armdevhub/options.go
  sdk/resourcemanager/devhub/armdevhub/responses.go
  sdk/resourcemanager/devhub/armdevhub/time_rfc3339.go
  sdk/resourcemanager/devhub/armdevhub/workflow_client.go
  sdk/resourcemanager/devhub/armdevhub/workflow_client_example_test.go
Labels: Beta

#23413 [Release] sdk/resourcemanager/privatedns/armprivatedns/1.3.0
  sdk/resourcemanager/privatedns/armprivatedns/CHANGELOG.md
  sdk/resourcemanager/privatedns/armprivatedns/assets.json
  sdk/resourcemanager/privatedns/armprivatedns/autorest.md
  sdk/resourcemanager/privatedns/armprivatedns/client_factory.go
  sdk/resourcemanager/privatedns/armprivatedns/constants.go
  sdk/resourcemanager/privatedns/armprivatedns/models.go
  sdk/resourcemanager/privatedns/armprivatedns/models_serde.go
  sdk/resourcemanager/privatedns/armprivatedns/privatezones_client.go
  sdk/resourcemanager/privatedns/armprivatedns/privatezones_client_example_test.go
  sdk/resourcemanager/privatedns/armprivatedns/recordsets_client.go
  sdk/resourcemanager/privatedns/armprivatedns/recordsets_client_example_test.go
  sdk/resourcemanager/privatedns/armprivatedns/responses.go
  sdk/resourcemanager/privatedns/armprivatedns/virtualnetworklinks_client.go
  sdk/resourcemanager/privatedns/armprivatedns/virtualnetworklinks_client_example_test.go
Labels: Stable

#23509 Sync eng/common directory with azure-sdk-tools for PR 9057
  eng/common/scripts/Update-DocsMsPackages.ps1
Labels: EngSys, Central-EngSys

#23485 Improve AzurePipelinesCredential diagnosability
  sdk/azidentity/CHANGELOG.md
  sdk/azidentity/TROUBLESHOOTING.md
  sdk/azidentity/azure_pipelines_credential.go
  sdk/azidentity/azure_pipelines_credential_test.go
Labels: Azure.Identity

#23502 [Release] sdk/resourcemanager/avs/armavs/2.0.0
  sdk/resourcemanager/avs/armavs/CHANGELOG.md
  sdk/resourcemanager/avs/armavs/addons_client_example_test.go
  sdk/resourcemanager/avs/armavs/authorizations_client_example_test.go
  sdk/resourcemanager/avs/armavs/autorest.md
  sdk/resourcemanager/avs/armavs/cloudlinks_client_example_test.go
  sdk/resourcemanager/avs/armavs/clusters_client_example_test.go
  sdk/resourcemanager/avs/armavs/constants.go
  sdk/resourcemanager/avs/armavs/datastores_client_example_test.go
  sdk/resourcemanager/avs/armavs/globalreachconnections_client_example_test.go
  sdk/resourcemanager/avs/armavs/hcxenterprisesites_client_example_test.go
  sdk/resourcemanager/avs/armavs/iscsipaths_client_example_test.go
  sdk/resourcemanager/avs/armavs/locations_client_example_test.go
  sdk/resourcemanager/avs/armavs/operations_client_example_test.go
  sdk/resourcemanager/avs/armavs/placementpolicies_client_example_test.go
  sdk/resourcemanager/avs/armavs/privateclouds_client_example_test.go
  sdk/resourcemanager/avs/armavs/scriptcmdlets_client_example_test.go
  sdk/resourcemanager/avs/armavs/scriptexecutions_client_example_test.go
  sdk/resourcemanager/avs/armavs/scriptpackages_client_example_test.go
  sdk/resourcemanager/avs/armavs/virtualmachines_client_example_test.go
  sdk/resourcemanager/avs/armavs/workloadnetworks_client_example_test.go
Labels: Mgmt, Approved Major Version

#23389 [Release] sdk/resourcemanager/batch/armbatch/3.0.0
  sdk/resourcemanager/batch/armbatch/CHANGELOG.md
  sdk/resourcemanager/batch/armbatch/README.md
  sdk/resourcemanager/batch/armbatch/account_client.go
  sdk/resourcemanager/batch/armbatch/account_client_example_test.go
  sdk/resourcemanager/batch/armbatch/application_client.go
  sdk/resourcemanager/batch/armbatch/application_client_example_test.go
  sdk/resourcemanager/batch/armbatch/applicationpackage_client.go
  sdk/resourcemanager/batch/armbatch/applicationpackage_client_example_test.go
  sdk/resourcemanager/batch/armbatch/autorest.md
  sdk/resourcemanager/batch/armbatch/certificate_client.go
  sdk/resourcemanager/batch/armbatch/certificate_client_example_test.go
  sdk/resourcemanager/batch/armbatch/client_factory.go
  sdk/resourcemanager/batch/armbatch/constants.go
  sdk/resourcemanager/batch/armbatch/fake/account_server.go
  sdk/resourcemanager/batch/armbatch/fake/application_server.go
  sdk/resourcemanager/batch/armbatch/fake/applicationpackage_server.go
  sdk/resourcemanager/batch/armbatch/fake/certificate_server.go
  sdk/resourcemanager/batch/armbatch/fake/location_server.go
  sdk/resourcemanager/batch/armbatch/fake/networksecurityperimeter_server.go
  sdk/resourcemanager/batch/armbatch/fake/operations_server.go
  sdk/resourcemanager/batch/armbatch/fake/pool_server.go
  sdk/resourcemanager/batch/armbatch/fake/privateendpointconnection_server.go
  sdk/resourcemanager/batch/armbatch/fake/privatelinkresource_server.go
  sdk/resourcemanager/batch/armbatch/fake/server_factory.go
  sdk/resourcemanager/batch/armbatch/go.mod
  sdk/resourcemanager/batch/armbatch/location_client.go
  sdk/resourcemanager/batch/armbatch/location_client_example_test.go
  sdk/resourcemanager/batch/armbatch/models.go
  sdk/resourcemanager/batch/armbatch/models_serde.go
  sdk/resourcemanager/batch/armbatch/networksecurityperimeter_client.go
  sdk/resourcemanager/batch/armbatch/networksecurityperimeter_client_example_test.go
  sdk/resourcemanager/batch/armbatch/operations_client.go
  sdk/resourcemanager/batch/armbatch/operations_client_example_test.go
  sdk/resourcemanager/batch/armbatch/options.go
  sdk/resourcemanager/batch/armbatch/pool_client.go
  sdk/resourcemanager/batch/armbatch/pool_client_example_test.go
  sdk/resourcemanager/batch/armbatch/privateendpointconnection_client.go
  sdk/resourcemanager/batch/armbatch/privateendpointconnection_client_example_test.go
  sdk/resourcemanager/batch/armbatch/privatelinkresource_client.go
  sdk/resourcemanager/batch/armbatch/privatelinkresource_client_example_test.go
  sdk/resourcemanager/batch/armbatch/responses.go
Labels: BreakingChange, Approved Major Version, Stable

#23512 Release mongocluster armmongocluster 1.0.0 1727405513
  sdk/resourcemanager/mongocluster/armmongocluster/CHANGELOG.md
  sdk/resourcemanager/mongocluster/armmongocluster/assets.json
  sdk/resourcemanager/mongocluster/armmongocluster/constants.go
  sdk/resourcemanager/mongocluster/armmongocluster/firewallrules_client.go
  sdk/resourcemanager/mongocluster/armmongocluster/firewallrules_client_example_test.go
  sdk/resourcemanager/mongocluster/armmongocluster/go.mod
  sdk/resourcemanager/mongocluster/armmongocluster/go.sum
  sdk/resourcemanager/mongocluster/armmongocluster/models.go
  sdk/resourcemanager/mongocluster/armmongocluster/models_serde.go
  sdk/resourcemanager/mongocluster/armmongocluster/mongocluster_live_test.go
  sdk/resourcemanager/mongocluster/armmongocluster/mongoclusters_client.go
  sdk/resourcemanager/mongocluster/armmongocluster/mongoclusters_client_example_test.go
  sdk/resourcemanager/mongocluster/armmongocluster/operations_client.go
  sdk/resourcemanager/mongocluster/armmongocluster/operations_client_example_test.go
  sdk/resourcemanager/mongocluster/armmongocluster/privateendpointconnections_client.go
  sdk/resourcemanager/mongocluster/armmongocluster/privateendpointconnections_client_example_test.go
  sdk/resourcemanager/mongocluster/armmongocluster/privatelinks_client.go
  sdk/resourcemanager/mongocluster/armmongocluster/privatelinks_client_example_test.go
  sdk/resourcemanager/mongocluster/armmongocluster/replicas_client.go
  sdk/resourcemanager/mongocluster/armmongocluster/replicas_client_example_test.go
  sdk/resourcemanager/mongocluster/armmongocluster/tsp-location.yaml
Labels: Mgmt

#23515 [Release] sdk/resourcemanager/containerservice/armcontainerservice/6.1.0
  sdk/resourcemanager/containerservice/armcontainerservice/CHANGELOG.md
  sdk/resourcemanager/containerservice/armcontainerservice/agentpools_client.go
  sdk/resourcemanager/containerservice/armcontainerservice/agentpools_client_example_test.go
  sdk/resourcemanager/containerservice/armcontainerservice/assets.json
  sdk/resourcemanager/containerservice/armcontainerservice/autorest.md
  sdk/resourcemanager/containerservice/armcontainerservice/client_factory.go
  sdk/resourcemanager/containerservice/armcontainerservice/constants.go
  sdk/resourcemanager/containerservice/armcontainerservice/fake/agentpools_server.go
  sdk/resourcemanager/containerservice/armcontainerservice/fake/internal.go
  sdk/resourcemanager/containerservice/armcontainerservice/fake/loadbalancers_server.go
  sdk/resourcemanager/containerservice/armcontainerservice/fake/managedclusters_server.go
  sdk/resourcemanager/containerservice/armcontainerservice/fake/managedclustersnapshots_server.go
  sdk/resourcemanager/containerservice/armcontainerservice/fake/operationstatusresult_server.go
  sdk/resourcemanager/containerservice/armcontainerservice/fake/server_factory.go
  sdk/resourcemanager/containerservice/armcontainerservice/loadbalancers_client.go
  sdk/resourcemanager/containerservice/armcontainerservice/loadbalancers_client_example_test.go
  sdk/resourcemanager/containerservice/armcontainerservice/machines_client.go
  sdk/resourcemanager/containerservice/armcontainerservice/machines_client_example_test.go
  sdk/resourcemanager/containerservice/armcontainerservice/maintenanceconfigurations_client.go
  sdk/resourcemanager/containerservice/armcontainerservice/maintenanceconfigurations_client_example_test.go
  sdk/resourcemanager/containerservice/armcontainerservice/managedclusters_client.go
  sdk/resourcemanager/containerservice/armcontainerservice/managedclusters_client_example_test.go
  sdk/resourcemanager/containerservice/armcontainerservice/managedclustersnapshots_client.go
  sdk/resourcemanager/containerservice/armcontainerservice/managedclustersnapshots_client_example_test.go
  sdk/resourcemanager/containerservice/armcontainerservice/models.go
  sdk/resourcemanager/containerservice/armcontainerservice/models_serde.go
  sdk/resourcemanager/containerservice/armcontainerservice/operations_client.go
  sdk/resourcemanager/containerservice/armcontainerservice/operations_client_example_test.go
  sdk/resourcemanager/containerservice/armcontainerservice/operationstatusresult_client.go
  sdk/resourcemanager/containerservice/armcontainerservice/operationstatusresult_client_example_test.go
  sdk/resourcemanager/containerservice/armcontainerservice/options.go
  sdk/resourcemanager/containerservice/armcontainerservice/privateendpointconnections_client.go
  sdk/resourcemanager/containerservice/armcontainerservice/privateendpointconnections_client_example_test.go
  sdk/resourcemanager/containerservice/armcontainerservice/privatelinkresources_client.go
  sdk/resourcemanager/containerservice/armcontainerservice/privatelinkresources_client_example_test.go
  sdk/resourcemanager/containerservice/armcontainerservice/resolveprivatelinkserviceid_client.go
  sdk/resourcemanager/containerservice/armcontainerservice/resolveprivatelinkserviceid_client_example_test.go
  sdk/resourcemanager/containerservice/armcontainerservice/responses.go
  sdk/resourcemanager/containerservice/armcontainerservice/snapshots_client.go
  sdk/resourcemanager/containerservice/armcontainerservice/snapshots_client_example_test.go
  sdk/resourcemanager/containerservice/armcontainerservice/trustedaccessrolebindings_client.go
  sdk/resourcemanager/containerservice/armcontainerservice/trustedaccessrolebindings_client_example_test.go
  sdk/resourcemanager/containerservice/armcontainerservice/trustedaccessroles_client.go
  sdk/resourcemanager/containerservice/armcontainerservice/trustedaccessroles_client_example_test.go
Labels: Mgmt

#23439 [Release] sdk/resourcemanager/computeschedule/armcomputeschedule/0.1.0
  sdk/resourcemanager/computeschedule/armcomputeschedule/CHANGELOG.md
  sdk/resourcemanager/computeschedule/armcomputeschedule/LICENSE.txt
  sdk/resourcemanager/computeschedule/armcomputeschedule/README.md
  sdk/resourcemanager/computeschedule/armcomputeschedule/autorest.md
  sdk/resourcemanager/computeschedule/armcomputeschedule/build.go
  sdk/resourcemanager/computeschedule/armcomputeschedule/ci.yml
  sdk/resourcemanager/computeschedule/armcomputeschedule/client_factory.go
  sdk/resourcemanager/computeschedule/armcomputeschedule/constants.go
  sdk/resourcemanager/computeschedule/armcomputeschedule/fake/internal.go
  sdk/resourcemanager/computeschedule/armcomputeschedule/fake/operations_server.go
  sdk/resourcemanager/computeschedule/armcomputeschedule/fake/scheduledactions_server.go
  sdk/resourcemanager/computeschedule/armcomputeschedule/fake/server_factory.go
  sdk/resourcemanager/computeschedule/armcomputeschedule/fake/time_rfc3339.go
  sdk/resourcemanager/computeschedule/armcomputeschedule/go.mod
  sdk/resourcemanager/computeschedule/armcomputeschedule/go.sum
  sdk/resourcemanager/computeschedule/armcomputeschedule/models.go
  sdk/resourcemanager/computeschedule/armcomputeschedule/models_serde.go
  sdk/resourcemanager/computeschedule/armcomputeschedule/operations_client.go
  sdk/resourcemanager/computeschedule/armcomputeschedule/operations_client_example_test.go
  sdk/resourcemanager/computeschedule/armcomputeschedule/options.go
  sdk/resourcemanager/computeschedule/armcomputeschedule/responses.go
  sdk/resourcemanager/computeschedule/armcomputeschedule/scheduledactions_client.go
  sdk/resourcemanager/computeschedule/armcomputeschedule/scheduledactions_client_example_test.go
  sdk/resourcemanager/computeschedule/armcomputeschedule/time_rfc3339.go
Labels: FirstBeta

#23520 update armcomputeschedule readme
  sdk/resourcemanager/computeschedule/armcomputeschedule/README.md
Labels: Mgmt

#23519 [Release] sdk/resourcemanager/trustedsigning/armtrustedsigning/0.1.0
  sdk/resourcemanager/trustedsigning/armtrustedsigning/CHANGELOG.md
  sdk/resourcemanager/trustedsigning/armtrustedsigning/LICENSE.txt
  sdk/resourcemanager/trustedsigning/armtrustedsigning/README.md
  sdk/resourcemanager/trustedsigning/armtrustedsigning/certificateprofiles_client.go
  sdk/resourcemanager/trustedsigning/armtrustedsigning/certificateprofiles_client_example_test.go
  sdk/resourcemanager/trustedsigning/armtrustedsigning/ci.yml
  sdk/resourcemanager/trustedsigning/armtrustedsigning/client_factory.go
  sdk/resourcemanager/trustedsigning/armtrustedsigning/codesigningaccounts_client.go
  sdk/resourcemanager/trustedsigning/armtrustedsigning/codesigningaccounts_client_example_test.go
  sdk/resourcemanager/trustedsigning/armtrustedsigning/constants.go
  sdk/resourcemanager/trustedsigning/armtrustedsigning/fake/certificateprofiles_server.go
  sdk/resourcemanager/trustedsigning/armtrustedsigning/fake/codesigningaccounts_server.go
  sdk/resourcemanager/trustedsigning/armtrustedsigning/fake/internal.go
  sdk/resourcemanager/trustedsigning/armtrustedsigning/fake/operations_server.go
  sdk/resourcemanager/trustedsigning/armtrustedsigning/fake/server_factory.go
  sdk/resourcemanager/trustedsigning/armtrustedsigning/fake/time_rfc3339.go
  sdk/resourcemanager/trustedsigning/armtrustedsigning/go.mod
  sdk/resourcemanager/trustedsigning/armtrustedsigning/go.sum
  sdk/resourcemanager/trustedsigning/armtrustedsigning/models.go
  sdk/resourcemanager/trustedsigning/armtrustedsigning/models_serde.go
  sdk/resourcemanager/trustedsigning/armtrustedsigning/operations_client.go
  sdk/resourcemanager/trustedsigning/armtrustedsigning/operations_client_example_test.go
  sdk/resourcemanager/trustedsigning/armtrustedsigning/options.go
  sdk/resourcemanager/trustedsigning/armtrustedsigning/responses.go
  sdk/resourcemanager/trustedsigning/armtrustedsigning/time_rfc3339.go
  sdk/resourcemanager/trustedsigning/armtrustedsigning/tsp-location.yaml
Labels: Mgmt
