Repository Azure/azure-sdk-for-go, pull requests merged in 2024-11, with the labels that each got.

#23577 Add API for creating hierarchical `PartitionKey`s
  sdk/data/azcosmos/CHANGELOG.md
  sdk/data/azcosmos/emulator_cosmos_item_test.go
  sdk/data/azcosmos/partition_key.go
  sdk/data/azcosmos/partition_key_definition.go
  sdk/data/azcosmos/partition_key_definition_test.go
  sdk/data/azcosmos/partition_key_test.go
Labels: Cosmos, customer-reported, Community Contribution

#23685 Sync eng/common directory with azure-sdk-tools for PR 9300
  eng/common/testproxy/target_version.txt
Labels: EngSys, Central-EngSys

#23690 Sync eng/common directory with azure-sdk-tools for PR 9308
  eng/common/scripts/Package-Properties.ps1
Labels: EngSys, Central-EngSys

#23691 Prepare azidentity/cache v0.3.1 for release
  sdk/azidentity/cache/CHANGELOG.md
Labels: Azure.Identity

#23684 Sync eng/common directory with azure-sdk-tools for PR 9277
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: EngSys, Central-EngSys

#23695 Increment version for azidentity/cache releases
  sdk/azidentity/cache/CHANGELOG.md
  sdk/azidentity/cache/version.go
Labels: Azure.Identity

#23697 Increment version for data/aztables releases
  sdk/data/aztables/CHANGELOG.md
  sdk/data/aztables/internal/version.go
Labels: Tables

#23696 Sync eng/common directory with azure-sdk-tools for PR 9330
  eng/common/scripts/Package-Properties.ps1
Labels: EngSys, Central-EngSys

#23698 [azsystemevents] Re-enabling the scheduledOn test that was disabled
  sdk/messaging/eventgrid/azsystemevents/system_events5_test.go
  sdk/messaging/eventgrid/azsystemevents/time_rfc1123.go
Labels: Event Grid

#23701 [query/azlogs] prep for release
  sdk/monitor/query/azlogs/CHANGELOG.md
  sdk/monitor/query/azlogs/go.mod
  sdk/monitor/query/azlogs/go.sum
  sdk/monitor/query/azlogs/version.go
Labels: Monitor, Client

#23702 [keyvault] prep for release
  sdk/security/keyvault/azadmin/CHANGELOG.md
  sdk/security/keyvault/azadmin/go.mod
  sdk/security/keyvault/azadmin/go.sum
  sdk/security/keyvault/azadmin/internal/version.go
  sdk/security/keyvault/azcertificates/CHANGELOG.md
  sdk/security/keyvault/azcertificates/go.mod
  sdk/security/keyvault/azcertificates/go.sum
  sdk/security/keyvault/azcertificates/testdata/perf/go.mod
  sdk/security/keyvault/azcertificates/testdata/perf/go.sum
  sdk/security/keyvault/azcertificates/version.go
  sdk/security/keyvault/azkeys/CHANGELOG.md
  sdk/security/keyvault/azkeys/go.mod
  sdk/security/keyvault/azkeys/go.sum
  sdk/security/keyvault/azkeys/testdata/perf/go.mod
  sdk/security/keyvault/azkeys/testdata/perf/go.sum
  sdk/security/keyvault/azkeys/version.go
  sdk/security/keyvault/azsecrets/CHANGELOG.md
  sdk/security/keyvault/azsecrets/go.mod
  sdk/security/keyvault/azsecrets/go.sum
  sdk/security/keyvault/azsecrets/testdata/perf/go.mod
  sdk/security/keyvault/azsecrets/testdata/perf/go.sum
  sdk/security/keyvault/azsecrets/version.go
Labels: KeyVault, Client

#23704 Increment version for monitor/query/azlogs releases
  sdk/monitor/query/azlogs/CHANGELOG.md
  sdk/monitor/query/azlogs/version.go
Labels: Monitor

#23707 Increment version for security/keyvault/azsecrets releases
  sdk/security/keyvault/azsecrets/CHANGELOG.md
  sdk/security/keyvault/azsecrets/version.go
Labels: KeyVault

#23705 Increment version for security/keyvault/azkeys releases
  sdk/security/keyvault/azkeys/CHANGELOG.md
  sdk/security/keyvault/azkeys/version.go
Labels: KeyVault

#23706 Increment version for security/keyvault/azcertificates releases
  sdk/security/keyvault/azcertificates/CHANGELOG.md
  sdk/security/keyvault/azcertificates/version.go
Labels: KeyVault

#23703 Sync eng/common directory with azure-sdk-tools for PR 9333
  eng/common/scripts/Helpers/Resource-Helpers.ps1
Labels: EngSys, Central-EngSys

#23711 release azadmin
  sdk/security/keyvault/azadmin/CHANGELOG.md
Labels: KeyVault

#23710 Sync eng/common directory with azure-sdk-tools for PR 9331
  eng/common/pipelines/templates/steps/docker-pull-image.yml
  eng/common/pipelines/templates/steps/update-docsms-metadata.yml
  eng/common/scripts/Update-DocsMsMetadata.ps1
  eng/common/scripts/Update-DocsMsPackages.ps1
Labels: EngSys, Central-EngSys

#23714 Sync eng/common directory with azure-sdk-tools for PR 9354
  eng/common/pipelines/templates/steps/emit-rate-limit-metrics.yml
  eng/common/pipelines/templates/steps/git-push-changes.yml
Labels: EngSys, Central-EngSys

#23712 User credential types consistently log token scopes
  sdk/azidentity/CHANGELOG.md
  sdk/azidentity/azidentity.go
  sdk/azidentity/confidential_client.go
  sdk/azidentity/confidential_client_test.go
  sdk/azidentity/public_client.go
  sdk/azidentity/public_client_test.go
Labels: Azure.Identity

#23719 Sync eng/common directory with azure-sdk-tools for PR 9358
  eng/common/pipelines/templates/jobs/docindex.yml
Labels: EngSys, Central-EngSys

#23722 Refresh OIDC token for keyvault azadmin tests when deployment is slow
  sdk/security/keyvault/azadmin/ci.yml
  sdk/security/keyvault/azadmin/test-resources-post.ps1
  sdk/security/keyvault/azadmin/test-resources-pre.ps1
  sdk/security/keyvault/azadmin/test-resources.json
Labels: Central-EngSys

#23693 [Storage] Swagger stg 96
  sdk/storage/azblob/go.mod
  sdk/storage/azblob/go.sum
  sdk/storage/azblob/internal/generated/autorest.md
  sdk/storage/azblob/internal/generated/constants.go
  sdk/storage/azblob/internal/generated/zz_appendblob_client.go
  sdk/storage/azblob/internal/generated/zz_blob_client.go
  sdk/storage/azblob/internal/generated/zz_blockblob_client.go
  sdk/storage/azblob/internal/generated/zz_constants.go
  sdk/storage/azblob/internal/generated/zz_container_client.go
  sdk/storage/azblob/internal/generated/zz_options.go
  sdk/storage/azblob/internal/generated/zz_pageblob_client.go
  sdk/storage/azblob/internal/generated/zz_responses.go
  sdk/storage/azblob/internal/generated/zz_service_client.go
  sdk/storage/azdatalake/go.mod
  sdk/storage/azdatalake/go.sum
  sdk/storage/azdatalake/internal/generated/autorest.md
  sdk/storage/azdatalake/internal/generated/constants.go
  sdk/storage/azdatalake/internal/generated/zz_filesystem_client.go
  sdk/storage/azdatalake/internal/generated/zz_options.go
  sdk/storage/azdatalake/internal/generated/zz_path_client.go
  sdk/storage/azdatalake/internal/generated/zz_responses.go
  sdk/storage/azdatalake/internal/generated/zz_service_client.go
  sdk/storage/azdatalake/internal/generated_blob/autorest.md
  sdk/storage/azdatalake/internal/generated_blob/zz_appendblob_client.go
  sdk/storage/azdatalake/internal/generated_blob/zz_blob_client.go
  sdk/storage/azdatalake/internal/generated_blob/zz_blockblob_client.go
  sdk/storage/azdatalake/internal/generated_blob/zz_constants.go
  sdk/storage/azdatalake/internal/generated_blob/zz_container_client.go
  sdk/storage/azdatalake/internal/generated_blob/zz_options.go
  sdk/storage/azdatalake/internal/generated_blob/zz_pageblob_client.go
  sdk/storage/azdatalake/internal/generated_blob/zz_responses.go
  sdk/storage/azdatalake/internal/generated_blob/zz_service_client.go
  sdk/storage/azfile/go.mod
  sdk/storage/azfile/go.sum
  sdk/storage/azfile/internal/generated/autorest.md
  sdk/storage/azfile/internal/generated/constants.go
  sdk/storage/azfile/internal/generated/zz_constants.go
  sdk/storage/azfile/internal/generated/zz_directory_client.go
  sdk/storage/azfile/internal/generated/zz_file_client.go
  sdk/storage/azfile/internal/generated/zz_models.go
  sdk/storage/azfile/internal/generated/zz_models_serde.go
  sdk/storage/azfile/internal/generated/zz_options.go
  sdk/storage/azfile/internal/generated/zz_response_types.go
  sdk/storage/azfile/internal/generated/zz_service_client.go
  sdk/storage/azfile/internal/generated/zz_share_client.go
Labels: Storage

#23724 Add Premium access tier to Files Shares
  sdk/storage/azfile/CHANGELOG.md
  sdk/storage/azfile/assets.json
  sdk/storage/azfile/share/client_test.go
  sdk/storage/azfile/share/constants.go
Labels: Storage

#23728 Cosmos: update for 1.2.0 release
  sdk/data/azcosmos/CHANGELOG.md
  sdk/data/azcosmos/version.go
Labels: Cosmos

#23692 Sync eng/common directory with azure-sdk-tools for PR 9328
  eng/common/pipelines/templates/steps/save-package-properties.yml
  eng/common/scripts/Generate-PR-Diff.ps1
Labels: EngSys, Central-EngSys

#23687 Added permissions & resourcetype parameters in listblob response
  sdk/storage/azblob/internal/generated/autorest.md
  sdk/storage/azblob/internal/generated/zz_models.go
Labels: Storage, customer-reported, Community Contribution

#23742 [Storage] Prep for stg 95 GA release
  sdk/storage/azblob/CHANGELOG.md
  sdk/storage/azblob/internal/exported/version.go
  sdk/storage/azdatalake/CHANGELOG.md
  sdk/storage/azdatalake/internal/exported/version.go
  sdk/storage/azfile/CHANGELOG.md
  sdk/storage/azfile/internal/exported/version.go
Labels: Storage

#23740 Sync eng/common directory with azure-sdk-tools for PR 9373
  eng/common/pipelines/templates/archetype-typespec-emitter.yml
Labels: EngSys, Central-EngSys

#23726 Sync eng/common directory with azure-sdk-tools for PR 9364
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: EngSys, Central-EngSys

#23746 [azadmin] prep for release
  sdk/security/keyvault/azadmin/CHANGELOG.md
Labels: KeyVault

#23753 [Release] sdk/resourcemanager/hybridcompute/armhybridcompute/2.1.0-beta.1
  sdk/resourcemanager/hybridcompute/armhybridcompute/CHANGELOG.md
  sdk/resourcemanager/hybridcompute/armhybridcompute/autorest.md
  sdk/resourcemanager/hybridcompute/armhybridcompute/client_factory.go
  sdk/resourcemanager/hybridcompute/armhybridcompute/constants.go
  sdk/resourcemanager/hybridcompute/armhybridcompute/extensionmetadata_client.go
  sdk/resourcemanager/hybridcompute/armhybridcompute/extensionmetadata_client_example_test.go
  sdk/resourcemanager/hybridcompute/armhybridcompute/fake/gateways_server.go
  sdk/resourcemanager/hybridcompute/armhybridcompute/fake/machineruncommands_server.go
  sdk/resourcemanager/hybridcompute/armhybridcompute/fake/server_factory.go
  sdk/resourcemanager/hybridcompute/armhybridcompute/fake/settings_server.go
  sdk/resourcemanager/hybridcompute/armhybridcompute/gateways_client.go
  sdk/resourcemanager/hybridcompute/armhybridcompute/gateways_client_example_test.go
  sdk/resourcemanager/hybridcompute/armhybridcompute/licenseprofiles_client.go
  sdk/resourcemanager/hybridcompute/armhybridcompute/licenseprofiles_client_example_test.go
  sdk/resourcemanager/hybridcompute/armhybridcompute/licenses_client.go
  sdk/resourcemanager/hybridcompute/armhybridcompute/licenses_client_example_test.go
  sdk/resourcemanager/hybridcompute/armhybridcompute/machineextensions_client.go
  sdk/resourcemanager/hybridcompute/armhybridcompute/machineextensions_client_example_test.go
  sdk/resourcemanager/hybridcompute/armhybridcompute/machineruncommands_client.go
  sdk/resourcemanager/hybridcompute/armhybridcompute/machineruncommands_client_example_test.go
  sdk/resourcemanager/hybridcompute/armhybridcompute/machines_client.go
  sdk/resourcemanager/hybridcompute/armhybridcompute/machines_client_example_test.go
  sdk/resourcemanager/hybridcompute/armhybridcompute/management_client.go
  sdk/resourcemanager/hybridcompute/armhybridcompute/management_client_example_test.go
  sdk/resourcemanager/hybridcompute/armhybridcompute/models.go
  sdk/resourcemanager/hybridcompute/armhybridcompute/models_serde.go
  sdk/resourcemanager/hybridcompute/armhybridcompute/networkprofile_client.go
  sdk/resourcemanager/hybridcompute/armhybridcompute/networkprofile_client_example_test.go
  sdk/resourcemanager/hybridcompute/armhybridcompute/networksecurityperimeterconfigurations_client.go
  sdk/resourcemanager/hybridcompute/armhybridcompute/networksecurityperimeterconfigurations_client_example_test.go
  sdk/resourcemanager/hybridcompute/armhybridcompute/operations_client.go
  sdk/resourcemanager/hybridcompute/armhybridcompute/operations_client_example_test.go
  sdk/resourcemanager/hybridcompute/armhybridcompute/options.go
  sdk/resourcemanager/hybridcompute/armhybridcompute/privateendpointconnections_client.go
  sdk/resourcemanager/hybridcompute/armhybridcompute/privateendpointconnections_client_example_test.go
  sdk/resourcemanager/hybridcompute/armhybridcompute/privatelinkresources_client.go
  sdk/resourcemanager/hybridcompute/armhybridcompute/privatelinkresources_client_example_test.go
  sdk/resourcemanager/hybridcompute/armhybridcompute/privatelinkscopes_client.go
  sdk/resourcemanager/hybridcompute/armhybridcompute/privatelinkscopes_client_example_test.go
  sdk/resourcemanager/hybridcompute/armhybridcompute/responses.go
  sdk/resourcemanager/hybridcompute/armhybridcompute/settings_client.go
  sdk/resourcemanager/hybridcompute/armhybridcompute/settings_client_example_test.go
Labels: Mgmt

#23749 Increment version for security/keyvault/azadmin releases
  sdk/security/keyvault/azadmin/CHANGELOG.md
  sdk/security/keyvault/azadmin/internal/version.go
Labels: KeyVault

#23757 [Release] sdk/resourcemanager/networkcloud/armnetworkcloud/1.2.0-beta.1
  sdk/resourcemanager/networkcloud/armnetworkcloud/CHANGELOG.md
  sdk/resourcemanager/networkcloud/armnetworkcloud/README.md
  sdk/resourcemanager/networkcloud/armnetworkcloud/agentpools_client.go
  sdk/resourcemanager/networkcloud/armnetworkcloud/agentpools_client_example_test.go
  sdk/resourcemanager/networkcloud/armnetworkcloud/autorest.md
  sdk/resourcemanager/networkcloud/armnetworkcloud/baremetalmachinekeysets_client.go
  sdk/resourcemanager/networkcloud/armnetworkcloud/baremetalmachinekeysets_client_example_test.go
  sdk/resourcemanager/networkcloud/armnetworkcloud/baremetalmachines_client.go
  sdk/resourcemanager/networkcloud/armnetworkcloud/baremetalmachines_client_example_test.go
  sdk/resourcemanager/networkcloud/armnetworkcloud/bmckeysets_client.go
  sdk/resourcemanager/networkcloud/armnetworkcloud/bmckeysets_client_example_test.go
  sdk/resourcemanager/networkcloud/armnetworkcloud/client_factory.go
  sdk/resourcemanager/networkcloud/armnetworkcloud/cloudservicesnetworks_client.go
  sdk/resourcemanager/networkcloud/armnetworkcloud/cloudservicesnetworks_client_example_test.go
  sdk/resourcemanager/networkcloud/armnetworkcloud/clustermanagers_client.go
  sdk/resourcemanager/networkcloud/armnetworkcloud/clustermanagers_client_example_test.go
  sdk/resourcemanager/networkcloud/armnetworkcloud/clusters_client.go
  sdk/resourcemanager/networkcloud/armnetworkcloud/clusters_client_example_test.go
  sdk/resourcemanager/networkcloud/armnetworkcloud/consoles_client.go
  sdk/resourcemanager/networkcloud/armnetworkcloud/consoles_client_example_test.go
  sdk/resourcemanager/networkcloud/armnetworkcloud/constants.go
  sdk/resourcemanager/networkcloud/armnetworkcloud/fake/baremetalmachines_server.go
  sdk/resourcemanager/networkcloud/armnetworkcloud/fake/clusters_server.go
  sdk/resourcemanager/networkcloud/armnetworkcloud/fake/kubernetesclusterfeatures_server.go
  sdk/resourcemanager/networkcloud/armnetworkcloud/fake/kubernetesclusters_server.go
  sdk/resourcemanager/networkcloud/armnetworkcloud/fake/server_factory.go
  sdk/resourcemanager/networkcloud/armnetworkcloud/fake/storageappliances_server.go
  sdk/resourcemanager/networkcloud/armnetworkcloud/fake/time_rfc3339.go
  sdk/resourcemanager/networkcloud/armnetworkcloud/fake/virtualmachines_server.go
  sdk/resourcemanager/networkcloud/armnetworkcloud/kubernetesclusterfeatures_client.go
  sdk/resourcemanager/networkcloud/armnetworkcloud/kubernetesclusterfeatures_client_example_test.go
  sdk/resourcemanager/networkcloud/armnetworkcloud/kubernetesclusters_client.go
  sdk/resourcemanager/networkcloud/armnetworkcloud/kubernetesclusters_client_example_test.go
  sdk/resourcemanager/networkcloud/armnetworkcloud/l2networks_client.go
  sdk/resourcemanager/networkcloud/armnetworkcloud/l2networks_client_example_test.go
  sdk/resourcemanager/networkcloud/armnetworkcloud/l3networks_client.go
  sdk/resourcemanager/networkcloud/armnetworkcloud/l3networks_client_example_test.go
  sdk/resourcemanager/networkcloud/armnetworkcloud/metricsconfigurations_client.go
  sdk/resourcemanager/networkcloud/armnetworkcloud/metricsconfigurations_client_example_test.go
  sdk/resourcemanager/networkcloud/armnetworkcloud/models.go
  sdk/resourcemanager/networkcloud/armnetworkcloud/models_serde.go
  sdk/resourcemanager/networkcloud/armnetworkcloud/operations_client.go
  sdk/resourcemanager/networkcloud/armnetworkcloud/operations_client_example_test.go
  sdk/resourcemanager/networkcloud/armnetworkcloud/options.go
  sdk/resourcemanager/networkcloud/armnetworkcloud/racks_client.go
  sdk/resourcemanager/networkcloud/armnetworkcloud/racks_client_example_test.go
  sdk/resourcemanager/networkcloud/armnetworkcloud/rackskus_client.go
  sdk/resourcemanager/networkcloud/armnetworkcloud/rackskus_client_example_test.go
  sdk/resourcemanager/networkcloud/armnetworkcloud/responses.go
  sdk/resourcemanager/networkcloud/armnetworkcloud/storageappliances_client.go
  sdk/resourcemanager/networkcloud/armnetworkcloud/storageappliances_client_example_test.go
  sdk/resourcemanager/networkcloud/armnetworkcloud/time_rfc3339.go
  sdk/resourcemanager/networkcloud/armnetworkcloud/trunkednetworks_client.go
  sdk/resourcemanager/networkcloud/armnetworkcloud/trunkednetworks_client_example_test.go
  sdk/resourcemanager/networkcloud/armnetworkcloud/virtualmachines_client.go
  sdk/resourcemanager/networkcloud/armnetworkcloud/virtualmachines_client_example_test.go
  sdk/resourcemanager/networkcloud/armnetworkcloud/volumes_client.go
  sdk/resourcemanager/networkcloud/armnetworkcloud/volumes_client_example_test.go
Labels: Mgmt

#23764 Sync eng/common directory with azure-sdk-tools for PR 9389
  eng/common/scripts/logging.ps1
Labels: EngSys, Central-EngSys

#23745 Increment version for storage/azdatalake releases
  sdk/storage/azdatalake/CHANGELOG.md
  sdk/storage/azdatalake/internal/exported/version.go
Labels: Storage

#23744 Increment version for storage/azblob releases
  sdk/storage/azblob/CHANGELOG.md
  sdk/storage/azblob/internal/exported/version.go
Labels: Storage

#23743 Increment version for storage/azfile releases
  sdk/storage/azfile/CHANGELOG.md
  sdk/storage/azfile/internal/exported/version.go
Labels: Storage

#23773 Sync eng/common directory with azure-sdk-tools for PR 9393
  eng/common/scripts/job-matrix/Create-PrJobMatrix.ps1
  eng/common/scripts/job-matrix/job-matrix-functions.ps1
Labels: EngSys, Central-EngSys

#23774 Sync eng/common directory with azure-sdk-tools for PR 9381
  eng/common/scripts/Verify-ChangeLogs.ps1
Labels: EngSys, Central-EngSys

#23771 [Release] sdk/resourcemanager/netapp/armnetapp/7.4.0-beta.1
  sdk/resourcemanager/netapp/armnetapp/CHANGELOG.md
  sdk/resourcemanager/netapp/armnetapp/accounts_client.go
  sdk/resourcemanager/netapp/armnetapp/accounts_client_example_test.go
  sdk/resourcemanager/netapp/armnetapp/autorest.md
  sdk/resourcemanager/netapp/armnetapp/backuppolicies_client.go
  sdk/resourcemanager/netapp/armnetapp/backuppolicies_client_example_test.go
  sdk/resourcemanager/netapp/armnetapp/backups_client.go
  sdk/resourcemanager/netapp/armnetapp/backups_client_example_test.go
  sdk/resourcemanager/netapp/armnetapp/backupsunderaccount_client.go
  sdk/resourcemanager/netapp/armnetapp/backupsunderaccount_client_example_test.go
  sdk/resourcemanager/netapp/armnetapp/backupsunderbackupvault_client.go
  sdk/resourcemanager/netapp/armnetapp/backupsunderbackupvault_client_example_test.go
  sdk/resourcemanager/netapp/armnetapp/backupsundervolume_client.go
  sdk/resourcemanager/netapp/armnetapp/backupsundervolume_client_example_test.go
  sdk/resourcemanager/netapp/armnetapp/backupvaults_client.go
  sdk/resourcemanager/netapp/armnetapp/backupvaults_client_example_test.go
  sdk/resourcemanager/netapp/armnetapp/constants.go
  sdk/resourcemanager/netapp/armnetapp/fake/accounts_server.go
  sdk/resourcemanager/netapp/armnetapp/fake/volumes_server.go
  sdk/resourcemanager/netapp/armnetapp/models.go
  sdk/resourcemanager/netapp/armnetapp/models_serde.go
  sdk/resourcemanager/netapp/armnetapp/operations_client.go
  sdk/resourcemanager/netapp/armnetapp/operations_client_example_test.go
  sdk/resourcemanager/netapp/armnetapp/options.go
  sdk/resourcemanager/netapp/armnetapp/pools_client.go
  sdk/resourcemanager/netapp/armnetapp/pools_client_example_test.go
  sdk/resourcemanager/netapp/armnetapp/resource_client.go
  sdk/resourcemanager/netapp/armnetapp/resource_client_example_test.go
  sdk/resourcemanager/netapp/armnetapp/resourcequotalimits_client.go
  sdk/resourcemanager/netapp/armnetapp/resourcequotalimits_client_example_test.go
  sdk/resourcemanager/netapp/armnetapp/resourceregioninfos_client.go
  sdk/resourcemanager/netapp/armnetapp/resourceregioninfos_client_example_test.go
  sdk/resourcemanager/netapp/armnetapp/responses.go
  sdk/resourcemanager/netapp/armnetapp/snapshotpolicies_client.go
  sdk/resourcemanager/netapp/armnetapp/snapshotpolicies_client_example_test.go
  sdk/resourcemanager/netapp/armnetapp/snapshots_client.go
  sdk/resourcemanager/netapp/armnetapp/snapshots_client_example_test.go
  sdk/resourcemanager/netapp/armnetapp/subvolumes_client.go
  sdk/resourcemanager/netapp/armnetapp/subvolumes_client_example_test.go
  sdk/resourcemanager/netapp/armnetapp/volumegroups_client.go
  sdk/resourcemanager/netapp/armnetapp/volumegroups_client_example_test.go
  sdk/resourcemanager/netapp/armnetapp/volumequotarules_client.go
  sdk/resourcemanager/netapp/armnetapp/volumequotarules_client_example_test.go
  sdk/resourcemanager/netapp/armnetapp/volumes_client.go
  sdk/resourcemanager/netapp/armnetapp/volumes_client_example_test.go
Labels: Mgmt

#23770 [Release] sdk/resourcemanager/containerservice/armcontainerservice/6.3.0
  sdk/resourcemanager/containerservice/armcontainerservice/CHANGELOG.md
  sdk/resourcemanager/containerservice/armcontainerservice/agentpools_client.go
  sdk/resourcemanager/containerservice/armcontainerservice/agentpools_client_example_test.go
  sdk/resourcemanager/containerservice/armcontainerservice/assets.json
  sdk/resourcemanager/containerservice/armcontainerservice/autorest.md
  sdk/resourcemanager/containerservice/armcontainerservice/constants.go
  sdk/resourcemanager/containerservice/armcontainerservice/fake/agentpools_server.go
  sdk/resourcemanager/containerservice/armcontainerservice/fake/internal.go
  sdk/resourcemanager/containerservice/armcontainerservice/fake/managedclusters_server.go
  sdk/resourcemanager/containerservice/armcontainerservice/machines_client.go
  sdk/resourcemanager/containerservice/armcontainerservice/machines_client_example_test.go
  sdk/resourcemanager/containerservice/armcontainerservice/maintenanceconfigurations_client.go
  sdk/resourcemanager/containerservice/armcontainerservice/maintenanceconfigurations_client_example_test.go
  sdk/resourcemanager/containerservice/armcontainerservice/managedclusters_client.go
  sdk/resourcemanager/containerservice/armcontainerservice/managedclusters_client_example_test.go
  sdk/resourcemanager/containerservice/armcontainerservice/models.go
  sdk/resourcemanager/containerservice/armcontainerservice/models_serde.go
  sdk/resourcemanager/containerservice/armcontainerservice/operations_client.go
  sdk/resourcemanager/containerservice/armcontainerservice/operations_client_example_test.go
  sdk/resourcemanager/containerservice/armcontainerservice/options.go
  sdk/resourcemanager/containerservice/armcontainerservice/privateendpointconnections_client.go
  sdk/resourcemanager/containerservice/armcontainerservice/privateendpointconnections_client_example_test.go
  sdk/resourcemanager/containerservice/armcontainerservice/privatelinkresources_client.go
  sdk/resourcemanager/containerservice/armcontainerservice/privatelinkresources_client_example_test.go
  sdk/resourcemanager/containerservice/armcontainerservice/resolveprivatelinkserviceid_client.go
  sdk/resourcemanager/containerservice/armcontainerservice/resolveprivatelinkserviceid_client_example_test.go
  sdk/resourcemanager/containerservice/armcontainerservice/snapshots_client.go
  sdk/resourcemanager/containerservice/armcontainerservice/snapshots_client_example_test.go
  sdk/resourcemanager/containerservice/armcontainerservice/trustedaccessrolebindings_client.go
  sdk/resourcemanager/containerservice/armcontainerservice/trustedaccessrolebindings_client_example_test.go
  sdk/resourcemanager/containerservice/armcontainerservice/trustedaccessroles_client.go
  sdk/resourcemanager/containerservice/armcontainerservice/trustedaccessroles_client_example_test.go
Labels: Mgmt

#23769 [Release] sdk/resourcemanager/hardwaresecuritymodules/armhardwaresecuritymodules/2.0.0-beta.2
  sdk/resourcemanager/hardwaresecuritymodules/armhardwaresecuritymodules/CHANGELOG.md
  sdk/resourcemanager/hardwaresecuritymodules/armhardwaresecuritymodules/README.md
  sdk/resourcemanager/hardwaresecuritymodules/armhardwaresecuritymodules/autorest.md
  sdk/resourcemanager/hardwaresecuritymodules/armhardwaresecuritymodules/client_factory.go
  sdk/resourcemanager/hardwaresecuritymodules/armhardwaresecuritymodules/cloudhsmclusterbackupstatus_client.go
  sdk/resourcemanager/hardwaresecuritymodules/armhardwaresecuritymodules/cloudhsmclusterbackupstatus_client_example_test.go
  sdk/resourcemanager/hardwaresecuritymodules/armhardwaresecuritymodules/cloudhsmclusterprivateendpointconnections_client.go
  sdk/resourcemanager/hardwaresecuritymodules/armhardwaresecuritymodules/cloudhsmclusterprivateendpointconnections_client_example_test.go
  sdk/resourcemanager/hardwaresecuritymodules/armhardwaresecuritymodules/cloudhsmclusterprivatelinkresources_client.go
  sdk/resourcemanager/hardwaresecuritymodules/armhardwaresecuritymodules/cloudhsmclusterprivatelinkresources_client_example_test.go
  sdk/resourcemanager/hardwaresecuritymodules/armhardwaresecuritymodules/cloudhsmclusterrestorestatus_client.go
  sdk/resourcemanager/hardwaresecuritymodules/armhardwaresecuritymodules/cloudhsmclusterrestorestatus_client_example_test.go
  sdk/resourcemanager/hardwaresecuritymodules/armhardwaresecuritymodules/cloudhsmclusters_client.go
  sdk/resourcemanager/hardwaresecuritymodules/armhardwaresecuritymodules/cloudhsmclusters_client_example_test.go
  sdk/resourcemanager/hardwaresecuritymodules/armhardwaresecuritymodules/constants.go
  sdk/resourcemanager/hardwaresecuritymodules/armhardwaresecuritymodules/dedicatedhsm_client.go
  sdk/resourcemanager/hardwaresecuritymodules/armhardwaresecuritymodules/dedicatedhsm_client_example_test.go
  sdk/resourcemanager/hardwaresecuritymodules/armhardwaresecuritymodules/fake/cloudhsmclusterbackupstatus_server.go
  sdk/resourcemanager/hardwaresecuritymodules/armhardwaresecuritymodules/fake/cloudhsmclusterprivateendpointconnections_server.go
  sdk/resourcemanager/hardwaresecuritymodules/armhardwaresecuritymodules/fake/cloudhsmclusterprivatelinkresources_server.go
  sdk/resourcemanager/hardwaresecuritymodules/armhardwaresecuritymodules/fake/cloudhsmclusterrestorestatus_server.go
  sdk/resourcemanager/hardwaresecuritymodules/armhardwaresecuritymodules/fake/cloudhsmclusters_server.go
  sdk/resourcemanager/hardwaresecuritymodules/armhardwaresecuritymodules/fake/dedicatedhsm_server.go
  sdk/resourcemanager/hardwaresecuritymodules/armhardwaresecuritymodules/fake/server_factory.go
  sdk/resourcemanager/hardwaresecuritymodules/armhardwaresecuritymodules/fake/time_rfc3339.go
  sdk/resourcemanager/hardwaresecuritymodules/armhardwaresecuritymodules/models.go
  sdk/resourcemanager/hardwaresecuritymodules/armhardwaresecuritymodules/models_serde.go
  sdk/resourcemanager/hardwaresecuritymodules/armhardwaresecuritymodules/operations_client.go
  sdk/resourcemanager/hardwaresecuritymodules/armhardwaresecuritymodules/operations_client_example_test.go
  sdk/resourcemanager/hardwaresecuritymodules/armhardwaresecuritymodules/options.go
  sdk/resourcemanager/hardwaresecuritymodules/armhardwaresecuritymodules/privateendpointconnections_client.go
  sdk/resourcemanager/hardwaresecuritymodules/armhardwaresecuritymodules/privateendpointconnections_client_example_test.go
  sdk/resourcemanager/hardwaresecuritymodules/armhardwaresecuritymodules/responses.go
  sdk/resourcemanager/hardwaresecuritymodules/armhardwaresecuritymodules/time_rfc3339.go
Labels: Mgmt

#23729 Add zos support to storage/azblob
  sdk/storage/azblob/internal/shared/mmf_unix.go
Labels: Storage, customer-reported, Community Contribution

#23775 [azsystemevents] Updating to the latest commit: fb64eaa0dfc7ee8abc8e10369495729d5b3c1cc5
  sdk/messaging/eventgrid/azsystemevents/CHANGELOG.md
  sdk/messaging/eventgrid/azsystemevents/constants.go
  sdk/messaging/eventgrid/azsystemevents/go.mod
  sdk/messaging/eventgrid/azsystemevents/go.sum
  sdk/messaging/eventgrid/azsystemevents/internal/generate/generate.go
  sdk/messaging/eventgrid/azsystemevents/internal/version.go
  sdk/messaging/eventgrid/azsystemevents/models.go
  sdk/messaging/eventgrid/azsystemevents/models_serde.go
  sdk/messaging/eventgrid/azsystemevents/system_events.go
  sdk/messaging/eventgrid/azsystemevents/temp_models.go
  sdk/messaging/eventgrid/azsystemevents/testdata/package-lock.json
  sdk/messaging/eventgrid/azsystemevents/testdata/package.json
  sdk/messaging/eventgrid/azsystemevents/testdata/tsp-location.yaml
Labels: Event Grid

#23778 Increment version for messaging/eventgrid/azsystemevents releases
  sdk/messaging/eventgrid/azsystemevents/CHANGELOG.md
  sdk/messaging/eventgrid/azsystemevents/internal/version.go
Labels: Event Grid

#23786 [Release] sdk/resourcemanager/healthdataaiservices/armhealthdataaiservice/1.0.0
  sdk/resourcemanager/healthdataaiservices/armhealthdataaiservices/CHANGELOG.md
  sdk/resourcemanager/healthdataaiservices/armhealthdataaiservices/constants.go
  sdk/resourcemanager/healthdataaiservices/armhealthdataaiservices/deidservices_client.go
  sdk/resourcemanager/healthdataaiservices/armhealthdataaiservices/deidservices_client_example_test.go
  sdk/resourcemanager/healthdataaiservices/armhealthdataaiservices/fake/deidservices_server.go
  sdk/resourcemanager/healthdataaiservices/armhealthdataaiservices/fake/internal.go
  sdk/resourcemanager/healthdataaiservices/armhealthdataaiservices/fake/operations_server.go
  sdk/resourcemanager/healthdataaiservices/armhealthdataaiservices/fake/privateendpointconnections_server.go
  sdk/resourcemanager/healthdataaiservices/armhealthdataaiservices/fake/privatelinks_server.go
  sdk/resourcemanager/healthdataaiservices/armhealthdataaiservices/go.mod
  sdk/resourcemanager/healthdataaiservices/armhealthdataaiservices/go.sum
  sdk/resourcemanager/healthdataaiservices/armhealthdataaiservices/operations_client.go
  sdk/resourcemanager/healthdataaiservices/armhealthdataaiservices/operations_client_example_test.go
  sdk/resourcemanager/healthdataaiservices/armhealthdataaiservices/privateendpointconnections_client.go
  sdk/resourcemanager/healthdataaiservices/armhealthdataaiservices/privateendpointconnections_client_example_test.go
  sdk/resourcemanager/healthdataaiservices/armhealthdataaiservices/privatelinks_client.go
  sdk/resourcemanager/healthdataaiservices/armhealthdataaiservices/privatelinks_client_example_test.go
  sdk/resourcemanager/healthdataaiservices/armhealthdataaiservices/tsp-location.yaml
Labels: Mgmt

#23782 [Release] sdk/resourcemanager/devopsinfrastructure/armdevopsinfrastructure/1.0.0
  sdk/resourcemanager/devopsinfrastructure/armdevopsinfrastructure/CHANGELOG.md
  sdk/resourcemanager/devopsinfrastructure/armdevopsinfrastructure/autorest.md
  sdk/resourcemanager/devopsinfrastructure/armdevopsinfrastructure/build.go
  sdk/resourcemanager/devopsinfrastructure/armdevopsinfrastructure/client_factory.go
  sdk/resourcemanager/devopsinfrastructure/armdevopsinfrastructure/constants.go
  sdk/resourcemanager/devopsinfrastructure/armdevopsinfrastructure/fake/imageversions_server.go
  sdk/resourcemanager/devopsinfrastructure/armdevopsinfrastructure/fake/internal.go
  sdk/resourcemanager/devopsinfrastructure/armdevopsinfrastructure/fake/operations_server.go
  sdk/resourcemanager/devopsinfrastructure/armdevopsinfrastructure/fake/pools_server.go
  sdk/resourcemanager/devopsinfrastructure/armdevopsinfrastructure/fake/resourcedetails_server.go
  sdk/resourcemanager/devopsinfrastructure/armdevopsinfrastructure/fake/server_factory.go
  sdk/resourcemanager/devopsinfrastructure/armdevopsinfrastructure/fake/sku_server.go
  sdk/resourcemanager/devopsinfrastructure/armdevopsinfrastructure/fake/subscriptionusages_server.go
  sdk/resourcemanager/devopsinfrastructure/armdevopsinfrastructure/fake/time_rfc3339.go
  sdk/resourcemanager/devopsinfrastructure/armdevopsinfrastructure/go.mod
  sdk/resourcemanager/devopsinfrastructure/armdevopsinfrastructure/go.sum
  sdk/resourcemanager/devopsinfrastructure/armdevopsinfrastructure/imageversions_client.go
  sdk/resourcemanager/devopsinfrastructure/armdevopsinfrastructure/imageversions_client_example_test.go
  sdk/resourcemanager/devopsinfrastructure/armdevopsinfrastructure/interfaces.go
  sdk/resourcemanager/devopsinfrastructure/armdevopsinfrastructure/models.go
  sdk/resourcemanager/devopsinfrastructure/armdevopsinfrastructure/models_serde.go
  sdk/resourcemanager/devopsinfrastructure/armdevopsinfrastructure/operations_client.go
  sdk/resourcemanager/devopsinfrastructure/armdevopsinfrastructure/operations_client_example_test.go
  sdk/resourcemanager/devopsinfrastructure/armdevopsinfrastructure/options.go
  sdk/resourcemanager/devopsinfrastructure/armdevopsinfrastructure/polymorphic_helpers.go
  sdk/resourcemanager/devopsinfrastructure/armdevopsinfrastructure/pools_client.go
  sdk/resourcemanager/devopsinfrastructure/armdevopsinfrastructure/pools_client_example_test.go
  sdk/resourcemanager/devopsinfrastructure/armdevopsinfrastructure/resourcedetails_client.go
  sdk/resourcemanager/devopsinfrastructure/armdevopsinfrastructure/resourcedetails_client_example_test.go
  sdk/resourcemanager/devopsinfrastructure/armdevopsinfrastructure/responses.go
  sdk/resourcemanager/devopsinfrastructure/armdevopsinfrastructure/sku_client.go
  sdk/resourcemanager/devopsinfrastructure/armdevopsinfrastructure/sku_client_example_test.go
  sdk/resourcemanager/devopsinfrastructure/armdevopsinfrastructure/subscriptionusages_client.go
  sdk/resourcemanager/devopsinfrastructure/armdevopsinfrastructure/subscriptionusages_client_example_test.go
  sdk/resourcemanager/devopsinfrastructure/armdevopsinfrastructure/time_rfc3339.go
  sdk/resourcemanager/devopsinfrastructure/armdevopsinfrastructure/tsp-location.yaml
Labels: Mgmt

#23755 Sync eng/common directory with azure-sdk-tools for PR 9326
  eng/common/scripts/Cadl-Project-Generate.ps1
  eng/common/scripts/Cadl-Project-Sync.ps1
  eng/common/scripts/Helpers/Package-Helpers.ps1
  eng/common/scripts/TypeSpec-Project-Generate.ps1
  eng/common/scripts/TypeSpec-Project-Process.ps1
  eng/common/scripts/TypeSpec-Project-Sync.ps1
  eng/common/scripts/Update-DocsMsToc.ps1
  eng/common/scripts/Verify-Resource-Ref.ps1
  eng/common/scripts/Verify-RestApiSpecLocation.ps1
  eng/common/scripts/job-matrix/job-matrix-functions.ps1
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: EngSys, Central-EngSys

#23777 Sync eng/common directory with azure-sdk-tools for PR 9390
  eng/common/scripts/Helpers/ApiView-Helpers.ps1
Labels: EngSys, Central-EngSys

#23785 [Release] sdk/resourcemanager/terraform/armterraform/0.1.0
  sdk/resourcemanager/terraform/armterraform/CHANGELOG.md
  sdk/resourcemanager/terraform/armterraform/LICENSE.txt
  sdk/resourcemanager/terraform/armterraform/README.md
  sdk/resourcemanager/terraform/armterraform/ci.yml
  sdk/resourcemanager/terraform/armterraform/client_factory.go
  sdk/resourcemanager/terraform/armterraform/constants.go
  sdk/resourcemanager/terraform/armterraform/fake/internal.go
  sdk/resourcemanager/terraform/armterraform/fake/operations_server.go
  sdk/resourcemanager/terraform/armterraform/fake/polymorphic_helpers.go
  sdk/resourcemanager/terraform/armterraform/fake/server_factory.go
  sdk/resourcemanager/terraform/armterraform/fake/terraform_server.go
  sdk/resourcemanager/terraform/armterraform/fake/time_rfc3339.go
  sdk/resourcemanager/terraform/armterraform/go.mod
  sdk/resourcemanager/terraform/armterraform/go.sum
  sdk/resourcemanager/terraform/armterraform/interfaces.go
  sdk/resourcemanager/terraform/armterraform/models.go
  sdk/resourcemanager/terraform/armterraform/models_serde.go
  sdk/resourcemanager/terraform/armterraform/operations_client.go
  sdk/resourcemanager/terraform/armterraform/operations_client_example_test.go
  sdk/resourcemanager/terraform/armterraform/options.go
  sdk/resourcemanager/terraform/armterraform/responses.go
  sdk/resourcemanager/terraform/armterraform/terraform_client.go
  sdk/resourcemanager/terraform/armterraform/terraform_client_example_test.go
  sdk/resourcemanager/terraform/armterraform/time_rfc3339.go
  sdk/resourcemanager/terraform/armterraform/tsp-location.yaml
Labels: Mgmt

#23783 [Release] sdk/resourcemanager/connectedcache/armconnectedcache /0.1.0
  sdk/resourcemanager/connectedcache/armconnectedcache/CHANGELOG.md
  sdk/resourcemanager/connectedcache/armconnectedcache/LICENSE.txt
  sdk/resourcemanager/connectedcache/armconnectedcache/README.md
  sdk/resourcemanager/connectedcache/armconnectedcache/cachenodesoperations_client.go
  sdk/resourcemanager/connectedcache/armconnectedcache/cachenodesoperations_client_example_test.go
  sdk/resourcemanager/connectedcache/armconnectedcache/ci.yml
  sdk/resourcemanager/connectedcache/armconnectedcache/client_factory.go
  sdk/resourcemanager/connectedcache/armconnectedcache/constants.go
  sdk/resourcemanager/connectedcache/armconnectedcache/enterprisecustomeroperations_client.go
  sdk/resourcemanager/connectedcache/armconnectedcache/enterprisecustomeroperations_client_example_test.go
  sdk/resourcemanager/connectedcache/armconnectedcache/enterprisemcccachenodesoperations_client.go
  sdk/resourcemanager/connectedcache/armconnectedcache/enterprisemcccachenodesoperations_client_example_test.go
  sdk/resourcemanager/connectedcache/armconnectedcache/enterprisemcccustomers_client.go
  sdk/resourcemanager/connectedcache/armconnectedcache/enterprisemcccustomers_client_example_test.go
  sdk/resourcemanager/connectedcache/armconnectedcache/fake/cachenodesoperations_server.go
  sdk/resourcemanager/connectedcache/armconnectedcache/fake/enterprisecustomeroperations_server.go
  sdk/resourcemanager/connectedcache/armconnectedcache/fake/enterprisemcccachenodesoperations_server.go
  sdk/resourcemanager/connectedcache/armconnectedcache/fake/enterprisemcccustomers_server.go
  sdk/resourcemanager/connectedcache/armconnectedcache/fake/internal.go
  sdk/resourcemanager/connectedcache/armconnectedcache/fake/ispcachenodesoperations_server.go
  sdk/resourcemanager/connectedcache/armconnectedcache/fake/ispcustomers_server.go
  sdk/resourcemanager/connectedcache/armconnectedcache/fake/operations_server.go
  sdk/resourcemanager/connectedcache/armconnectedcache/fake/server_factory.go
  sdk/resourcemanager/connectedcache/armconnectedcache/fake/time_rfc3339.go
  sdk/resourcemanager/connectedcache/armconnectedcache/go.mod
  sdk/resourcemanager/connectedcache/armconnectedcache/go.sum
  sdk/resourcemanager/connectedcache/armconnectedcache/ispcachenodesoperations_client.go
  sdk/resourcemanager/connectedcache/armconnectedcache/ispcachenodesoperations_client_example_test.go
  sdk/resourcemanager/connectedcache/armconnectedcache/ispcustomers_client.go
  sdk/resourcemanager/connectedcache/armconnectedcache/ispcustomers_client_example_test.go
  sdk/resourcemanager/connectedcache/armconnectedcache/models.go
  sdk/resourcemanager/connectedcache/armconnectedcache/models_serde.go
  sdk/resourcemanager/connectedcache/armconnectedcache/operations_client.go
  sdk/resourcemanager/connectedcache/armconnectedcache/operations_client_example_test.go
  sdk/resourcemanager/connectedcache/armconnectedcache/options.go
  sdk/resourcemanager/connectedcache/armconnectedcache/responses.go
  sdk/resourcemanager/connectedcache/armconnectedcache/time_rfc3339.go
  sdk/resourcemanager/connectedcache/armconnectedcache/tsp-location.yaml
Labels: Mgmt

#23791 Sync eng/common directory with azure-sdk-tools for PR 9392
  eng/common/scripts/Helpers/PSModule-Helpers.ps1
Labels: EngSys, Central-EngSys

#23731 Increment version for data/azcosmos releases
  sdk/data/azcosmos/CHANGELOG.md
  sdk/data/azcosmos/version.go
Labels: Cosmos

#23718 chore(deps): bump MSAL dependency to 1.3.1
  sdk/azidentity/cache/go.mod
  sdk/azidentity/cache/go.sum
  sdk/azidentity/go.mod
  sdk/azidentity/go.sum
  sdk/azidentity/testdata/managed-id-test/go.mod
  sdk/azidentity/testdata/managed-id-test/go.sum
Labels: customer-reported, Azure.Identity, Community Contribution

#23798 Sync eng/common directory with azure-sdk-tools for PR 9428
  eng/common/scripts/Cadl-Project-Generate.ps1
  eng/common/scripts/Cadl-Project-Sync.ps1
Labels: EngSys, Central-EngSys

#23784 [Release] sdk/resourcemanager/neonpostgres /armneonpostgres/0.1.0
  sdk/resourcemanager/neonpostgres/armneonpostgres/CHANGELOG.md
  sdk/resourcemanager/neonpostgres/armneonpostgres/LICENSE.txt
  sdk/resourcemanager/neonpostgres/armneonpostgres/README.md
  sdk/resourcemanager/neonpostgres/armneonpostgres/ci.yml
  sdk/resourcemanager/neonpostgres/armneonpostgres/client_factory.go
  sdk/resourcemanager/neonpostgres/armneonpostgres/constants.go
  sdk/resourcemanager/neonpostgres/armneonpostgres/fake/internal.go
  sdk/resourcemanager/neonpostgres/armneonpostgres/fake/operations_server.go
  sdk/resourcemanager/neonpostgres/armneonpostgres/fake/organizations_server.go
  sdk/resourcemanager/neonpostgres/armneonpostgres/fake/server_factory.go
  sdk/resourcemanager/neonpostgres/armneonpostgres/fake/time_rfc3339.go
  sdk/resourcemanager/neonpostgres/armneonpostgres/go.mod
  sdk/resourcemanager/neonpostgres/armneonpostgres/go.sum
  sdk/resourcemanager/neonpostgres/armneonpostgres/models.go
  sdk/resourcemanager/neonpostgres/armneonpostgres/models_serde.go
  sdk/resourcemanager/neonpostgres/armneonpostgres/operations_client.go
  sdk/resourcemanager/neonpostgres/armneonpostgres/operations_client_example_test.go
  sdk/resourcemanager/neonpostgres/armneonpostgres/options.go
  sdk/resourcemanager/neonpostgres/armneonpostgres/organizations_client.go
  sdk/resourcemanager/neonpostgres/armneonpostgres/organizations_client_example_test.go
  sdk/resourcemanager/neonpostgres/armneonpostgres/responses.go
  sdk/resourcemanager/neonpostgres/armneonpostgres/time_rfc3339.go
  sdk/resourcemanager/neonpostgres/armneonpostgres/tsp-location.yaml
Labels: Mgmt
