Repository Azure/azure-sdk-for-go, pull requests merged in 2024-12, with the labels that each got.

#23814 Sync eng/common directory with azure-sdk-tools for PR 9440
  eng/common/scripts/Helpers/PSModule-Helpers.ps1
Labels: EngSys, Central-EngSys

#23803 Connectedcache live test
  sdk/resourcemanager/connectedcache/armconnectedcache/assets.json
  sdk/resourcemanager/connectedcache/armconnectedcache/ci.yml
  sdk/resourcemanager/connectedcache/armconnectedcache/connectedcache_live_test.go
  sdk/resourcemanager/connectedcache/armconnectedcache/go.mod
  sdk/resourcemanager/connectedcache/armconnectedcache/go.sum
  sdk/resourcemanager/connectedcache/armconnectedcache/utils_test.go
Labels: Mgmt

#23805 Sql live test
  sdk/resourcemanager/sql/armsql/assets.json
  sdk/resourcemanager/sql/armsql/ci.yml
  sdk/resourcemanager/sql/armsql/go.mod
  sdk/resourcemanager/sql/armsql/go.sum
  sdk/resourcemanager/sql/armsql/sql_live_test.go
  sdk/resourcemanager/sql/armsql/utils_test.go
Labels: Mgmt

#23811 add cae support mock test for mgmt. library
  sdk/resourcemanager/resources/armresources/cae_mock_test.go
Labels: Mgmt

#23806 terraform live-record test
  sdk/resourcemanager/terraform/armterraform/assets.json
  sdk/resourcemanager/terraform/armterraform/ci.yml
  sdk/resourcemanager/terraform/armterraform/go.mod
  sdk/resourcemanager/terraform/armterraform/go.sum
  sdk/resourcemanager/terraform/armterraform/terraform_live_test.go
  sdk/resourcemanager/terraform/armterraform/utils_test.go
Labels: Mgmt

#23809 neonpostgres add live test
  sdk/resourcemanager/neonpostgres/armneonpostgres/assets.json
  sdk/resourcemanager/neonpostgres/armneonpostgres/ci.yml
  sdk/resourcemanager/neonpostgres/armneonpostgres/go.mod
  sdk/resourcemanager/neonpostgres/armneonpostgres/go.sum
  sdk/resourcemanager/neonpostgres/armneonpostgres/neonpostgres_live_test.go
  sdk/resourcemanager/neonpostgres/armneonpostgres/utils_test.go
Labels: Mgmt

#23834 Sync eng/common directory with azure-sdk-tools for PR 9471
  eng/common/scripts/Helpers/DevOps-WorkItem-Helpers.ps1
Labels: EngSys, Central-EngSys

#23816 Changing aznamespaces over to using tsp-client
  sdk/messaging/eventgrid/aznamespaces/build.go
  sdk/messaging/eventgrid/aznamespaces/custom_models.go
  sdk/messaging/eventgrid/aznamespaces/go.mod
  sdk/messaging/eventgrid/aznamespaces/go.sum
  sdk/messaging/eventgrid/aznamespaces/internal/generate/generate.go
  sdk/messaging/eventgrid/aznamespaces/models.go
  sdk/messaging/eventgrid/aznamespaces/models_serde.go
  sdk/messaging/eventgrid/aznamespaces/receiver_client.go
  sdk/messaging/eventgrid/aznamespaces/sender_client.go
  sdk/messaging/eventgrid/aznamespaces/testdata/.gitignore
  sdk/messaging/eventgrid/aznamespaces/testdata/gen.ps1
  sdk/messaging/eventgrid/aznamespaces/testdata/package-lock.json
  sdk/messaging/eventgrid/aznamespaces/testdata/package.json
  sdk/messaging/eventgrid/aznamespaces/testdata/tspconfig.yaml
  sdk/messaging/eventgrid/aznamespaces/tsp-location.yaml
Labels: Event Grid

#23835 Sync eng/common directory with azure-sdk-tools for PR 9466
  eng/common/pipelines/templates/jobs/prepare-pipelines.yml
  eng/common/pipelines/templates/steps/install-pipeline-generation.yml
Labels: EngSys, Central-EngSys

#23828 Sync eng/common directory with azure-sdk-tools for PR 9460
  eng/common/testproxy/publish-proxy-logs.yml
  eng/common/testproxy/test-proxy-standalone-tool.yml
  eng/common/testproxy/test-proxy-tool.yml
Labels: EngSys, Central-EngSys

#23830 [azsystemevents] switch over to use tsp-client
  sdk/messaging/eventgrid/azsystemevents/CHANGELOG.md
  sdk/messaging/eventgrid/azsystemevents/build.go
  sdk/messaging/eventgrid/azsystemevents/constants.go
  sdk/messaging/eventgrid/azsystemevents/interfaces.go
  sdk/messaging/eventgrid/azsystemevents/internal/generate/generate.go
  sdk/messaging/eventgrid/azsystemevents/internal/generate/generate_constants.go
  sdk/messaging/eventgrid/azsystemevents/internal/version.go
  sdk/messaging/eventgrid/azsystemevents/models.go
  sdk/messaging/eventgrid/azsystemevents/models_serde.go
  sdk/messaging/eventgrid/azsystemevents/polymorphic_helpers.go
  sdk/messaging/eventgrid/azsystemevents/system_events.go
  sdk/messaging/eventgrid/azsystemevents/system_events2_test.go
  sdk/messaging/eventgrid/azsystemevents/system_events4_test.go
  sdk/messaging/eventgrid/azsystemevents/temp_models.go
  sdk/messaging/eventgrid/azsystemevents/testdata/tspconfig.yaml
  sdk/messaging/eventgrid/azsystemevents/tsp-location.yaml
Labels: Event Grid

#23842 Sync .github/workflows directory with azure-sdk-tools for PR 9490
  .github/workflows/event-processor.yml
  .github/workflows/scheduled-event-processor.yml
Labels: EngSys, Central-EngSys

#23853 Sync eng/common directory with azure-sdk-tools for PR 9497
  eng/common/testproxy/target_version.txt
Labels: EngSys, Central-EngSys

#23733 Add OperationLocationResultPath to NewPollerOptions[T]
  sdk/azcore/CHANGELOG.md
  sdk/azcore/internal/pollers/op/op.go
  sdk/azcore/internal/pollers/op/op_test.go
  sdk/azcore/runtime/poller.go
  sdk/azcore/runtime/poller_test.go
Labels: Azure.Core

#23843 [azservicebus/azeventhubs] Enable custom endpoints, which allows our library to be used with TCP proxies
  sdk/messaging/azeventhubs/CHANGELOG.md
  sdk/messaging/azeventhubs/consumer_client.go
  sdk/messaging/azeventhubs/example_consumerclient_test.go
  sdk/messaging/azeventhubs/example_producerclient_test.go
  sdk/messaging/azeventhubs/internal/constants.go
  sdk/messaging/azeventhubs/internal/namespace.go
  sdk/messaging/azeventhubs/producer_client.go
  sdk/messaging/azservicebus/CHANGELOG.md
  sdk/messaging/azservicebus/client.go
  sdk/messaging/azservicebus/example_client_test.go
  sdk/messaging/azservicebus/internal/constants.go
  sdk/messaging/azservicebus/internal/namespace.go
Labels: Service Bus, Event Hubs

#23859 Drive traffic to credential chains doc
  sdk/azidentity/README.md
  sdk/azidentity/chained_token_credential.go
  sdk/azidentity/default_azure_credential.go
  sdk/azidentity/img/mermaidjs/DefaultAzureCredentialAuthFlow.md
  sdk/azidentity/img/mermaidjs/DefaultAzureCredentialAuthFlow.svg
Labels: Azure.Identity

#23862 Fixing ModuleName to be compliant with the standard
  sdk/messaging/eventgrid/azeventgrid/internal/version.go
  sdk/messaging/eventgrid/aznamespaces/internal/version.go
  sdk/messaging/eventgrid/azsystemevents/internal/version.go
  sdk/template/aztemplate/version.go
Labels: Event Grid, EngSys

#23844 Sync eng/common directory with azure-sdk-tools for PR 9493
  eng/common/scripts/Helpers/PSModule-Helpers.ps1
  eng/common/scripts/Helpers/Package-Helpers.ps1
Labels: EngSys, Central-EngSys

#23865 Update dependencies for core modules
  sdk/azcore/go.mod
  sdk/azcore/go.sum
  sdk/azcore/testdata/perf/go.mod
  sdk/azcore/testdata/perf/go.sum
  sdk/azidentity/cache/go.mod
  sdk/azidentity/cache/go.sum
  sdk/azidentity/go.mod
  sdk/azidentity/go.sum
  sdk/azidentity/testdata/managed-id-test/go.mod
  sdk/azidentity/testdata/managed-id-test/go.sum
  sdk/internal/go.mod
  sdk/internal/go.sum
  sdk/samples/fakes/go.mod
  sdk/samples/fakes/go.sum
  sdk/template/aztemplate/go.mod
  sdk/template/aztemplate/go.sum
Labels: Azure.Identity, Azure.Core, EngSys, Internal

#23800 Fix Filter Blob API encoding issue
  sdk/storage/azblob/CHANGELOG.md
  sdk/storage/azblob/container/client_test.go
  sdk/storage/azblob/internal/generated/autorest.md
  sdk/storage/azblob/internal/generated/zz_container_client.go
  sdk/storage/azblob/internal/generated/zz_service_client.go
  sdk/storage/azblob/internal/testcommon/clients_auth.go
  sdk/storage/azblob/pageblob/client_test.go
  sdk/storage/azdatalake/CHANGELOG.md
  sdk/storage/azdatalake/internal/generated/autorest.md
  sdk/storage/azdatalake/internal/generated_blob/autorest.md
  sdk/storage/azdatalake/internal/generated_blob/zz_container_client.go
  sdk/storage/azdatalake/internal/generated_blob/zz_service_client.go
Labels: Storage

#23864 [Release] sdk/resourcemanager/iotoperations/armiotoperations/1.0.0
  sdk/resourcemanager/iotoperations/armiotoperations/CHANGELOG.md
  sdk/resourcemanager/iotoperations/armiotoperations/constants.go
  sdk/resourcemanager/iotoperations/armiotoperations/fake/broker_server.go
  sdk/resourcemanager/iotoperations/armiotoperations/fake/brokerauthentication_server.go
  sdk/resourcemanager/iotoperations/armiotoperations/fake/brokerauthorization_server.go
  sdk/resourcemanager/iotoperations/armiotoperations/fake/brokerlistener_server.go
  sdk/resourcemanager/iotoperations/armiotoperations/fake/dataflow_server.go
  sdk/resourcemanager/iotoperations/armiotoperations/fake/dataflowendpoint_server.go
  sdk/resourcemanager/iotoperations/armiotoperations/fake/dataflowprofile_server.go
  sdk/resourcemanager/iotoperations/armiotoperations/fake/instance_server.go
  sdk/resourcemanager/iotoperations/armiotoperations/fake/internal.go
  sdk/resourcemanager/iotoperations/armiotoperations/fake/operations_server.go
  sdk/resourcemanager/iotoperations/armiotoperations/go.mod
  sdk/resourcemanager/iotoperations/armiotoperations/go.sum
  sdk/resourcemanager/iotoperations/armiotoperations/tsp-location.yaml
Labels: Mgmt

#23854 [Release] sdk/resourcemanager/containerregistry/armcontainerregistry/1.3.0-beta.2
  sdk/resourcemanager/containerregistry/armcontainerregistry/CHANGELOG.md
  sdk/resourcemanager/containerregistry/armcontainerregistry/README.md
  sdk/resourcemanager/containerregistry/armcontainerregistry/agentpools_client_example_test.go
  sdk/resourcemanager/containerregistry/armcontainerregistry/archives_client.go
  sdk/resourcemanager/containerregistry/armcontainerregistry/archives_client_example_test.go
  sdk/resourcemanager/containerregistry/armcontainerregistry/archiveversions_client.go
  sdk/resourcemanager/containerregistry/armcontainerregistry/archiveversions_client_example_test.go
  sdk/resourcemanager/containerregistry/armcontainerregistry/assets.json
  sdk/resourcemanager/containerregistry/armcontainerregistry/autorest.md
  sdk/resourcemanager/containerregistry/armcontainerregistry/cacherules_client.go
  sdk/resourcemanager/containerregistry/armcontainerregistry/cacherules_client_example_test.go
  sdk/resourcemanager/containerregistry/armcontainerregistry/client_factory.go
  sdk/resourcemanager/containerregistry/armcontainerregistry/connectedregistries_client.go
  sdk/resourcemanager/containerregistry/armcontainerregistry/connectedregistries_client_example_test.go
  sdk/resourcemanager/containerregistry/armcontainerregistry/constants.go
  sdk/resourcemanager/containerregistry/armcontainerregistry/credentialsets_client.go
  sdk/resourcemanager/containerregistry/armcontainerregistry/credentialsets_client_example_test.go
  sdk/resourcemanager/containerregistry/armcontainerregistry/exportpipelines_client.go
  sdk/resourcemanager/containerregistry/armcontainerregistry/exportpipelines_client_example_test.go
  sdk/resourcemanager/containerregistry/armcontainerregistry/fake/polymorphic_helpers.go
  sdk/resourcemanager/containerregistry/armcontainerregistry/fake/time_rfc3339.go
  sdk/resourcemanager/containerregistry/armcontainerregistry/importpipelines_client.go
  sdk/resourcemanager/containerregistry/armcontainerregistry/importpipelines_client_example_test.go
  sdk/resourcemanager/containerregistry/armcontainerregistry/models.go
  sdk/resourcemanager/containerregistry/armcontainerregistry/models_serde.go
  sdk/resourcemanager/containerregistry/armcontainerregistry/operations_client.go
  sdk/resourcemanager/containerregistry/armcontainerregistry/operations_client_example_test.go
  sdk/resourcemanager/containerregistry/armcontainerregistry/pipelineruns_client.go
  sdk/resourcemanager/containerregistry/armcontainerregistry/pipelineruns_client_example_test.go
  sdk/resourcemanager/containerregistry/armcontainerregistry/polymorphic_helpers.go
  sdk/resourcemanager/containerregistry/armcontainerregistry/privateendpointconnections_client.go
  sdk/resourcemanager/containerregistry/armcontainerregistry/privateendpointconnections_client_example_test.go
  sdk/resourcemanager/containerregistry/armcontainerregistry/registries_client.go
  sdk/resourcemanager/containerregistry/armcontainerregistry/registries_client_example_test.go
  sdk/resourcemanager/containerregistry/armcontainerregistry/replications_client.go
  sdk/resourcemanager/containerregistry/armcontainerregistry/replications_client_example_test.go
  sdk/resourcemanager/containerregistry/armcontainerregistry/responses.go
  sdk/resourcemanager/containerregistry/armcontainerregistry/runs_client.go
  sdk/resourcemanager/containerregistry/armcontainerregistry/runs_client_example_test.go
  sdk/resourcemanager/containerregistry/armcontainerregistry/scopemaps_client.go
  sdk/resourcemanager/containerregistry/armcontainerregistry/scopemaps_client_example_test.go
  sdk/resourcemanager/containerregistry/armcontainerregistry/taskruns_client_example_test.go
  sdk/resourcemanager/containerregistry/armcontainerregistry/tasks_client_example_test.go
  sdk/resourcemanager/containerregistry/armcontainerregistry/time_rfc3339.go
  sdk/resourcemanager/containerregistry/armcontainerregistry/tokens_client.go
  sdk/resourcemanager/containerregistry/armcontainerregistry/tokens_client_example_test.go
  sdk/resourcemanager/containerregistry/armcontainerregistry/webhooks_client.go
  sdk/resourcemanager/containerregistry/armcontainerregistry/webhooks_client_example_test.go
Labels: Beta

#23845 [Release] sdk/resourcemanager/datafactory/armdatafactory/9.1.0
  sdk/resourcemanager/datafactory/armdatafactory/CHANGELOG.md
  sdk/resourcemanager/datafactory/armdatafactory/activityruns_client_example_test.go
  sdk/resourcemanager/datafactory/armdatafactory/autorest.md
  sdk/resourcemanager/datafactory/armdatafactory/changedatacapture_client_example_test.go
  sdk/resourcemanager/datafactory/armdatafactory/constants.go
  sdk/resourcemanager/datafactory/armdatafactory/credentialoperations_client_example_test.go
  sdk/resourcemanager/datafactory/armdatafactory/dataflowdebugsession_client_example_test.go
  sdk/resourcemanager/datafactory/armdatafactory/dataflows_client_example_test.go
  sdk/resourcemanager/datafactory/armdatafactory/datasets_client_example_test.go
  sdk/resourcemanager/datafactory/armdatafactory/exposurecontrol_client_example_test.go
  sdk/resourcemanager/datafactory/armdatafactory/factories_client_example_test.go
  sdk/resourcemanager/datafactory/armdatafactory/globalparameters_client_example_test.go
  sdk/resourcemanager/datafactory/armdatafactory/integrationruntimenodes_client_example_test.go
  sdk/resourcemanager/datafactory/armdatafactory/integrationruntimeobjectmetadata_client_example_test.go
  sdk/resourcemanager/datafactory/armdatafactory/integrationruntimes_client_example_test.go
  sdk/resourcemanager/datafactory/armdatafactory/interfaces.go
  sdk/resourcemanager/datafactory/armdatafactory/linkedservices_client_example_test.go
  sdk/resourcemanager/datafactory/armdatafactory/managedprivateendpoints_client_example_test.go
  sdk/resourcemanager/datafactory/armdatafactory/managedvirtualnetworks_client_example_test.go
  sdk/resourcemanager/datafactory/armdatafactory/models.go
  sdk/resourcemanager/datafactory/armdatafactory/models_serde.go
  sdk/resourcemanager/datafactory/armdatafactory/operations_client_example_test.go
  sdk/resourcemanager/datafactory/armdatafactory/pipelineruns_client_example_test.go
  sdk/resourcemanager/datafactory/armdatafactory/pipelines_client_example_test.go
  sdk/resourcemanager/datafactory/armdatafactory/polymorphic_helpers.go
  sdk/resourcemanager/datafactory/armdatafactory/privateendpointconnection_client_example_test.go
  sdk/resourcemanager/datafactory/armdatafactory/privateendpointconnections_client_example_test.go
  sdk/resourcemanager/datafactory/armdatafactory/privatelinkresources_client_example_test.go
  sdk/resourcemanager/datafactory/armdatafactory/triggerruns_client_example_test.go
  sdk/resourcemanager/datafactory/armdatafactory/triggers_client_example_test.go
Labels: Stable

#23839 [Release] sdk/resourcemanager/playwrighttesting/armplaywrighttesting/1.0.0
  sdk/resourcemanager/playwrighttesting/armplaywrighttesting/CHANGELOG.md
  sdk/resourcemanager/playwrighttesting/armplaywrighttesting/README.md
  sdk/resourcemanager/playwrighttesting/armplaywrighttesting/accountquotas_client.go
  sdk/resourcemanager/playwrighttesting/armplaywrighttesting/accountquotas_client_example_test.go
  sdk/resourcemanager/playwrighttesting/armplaywrighttesting/accounts_client.go
  sdk/resourcemanager/playwrighttesting/armplaywrighttesting/accounts_client_example_test.go
  sdk/resourcemanager/playwrighttesting/armplaywrighttesting/autorest.md
  sdk/resourcemanager/playwrighttesting/armplaywrighttesting/client_factory.go
  sdk/resourcemanager/playwrighttesting/armplaywrighttesting/constants.go
  sdk/resourcemanager/playwrighttesting/armplaywrighttesting/fake/accountquotas_server.go
  sdk/resourcemanager/playwrighttesting/armplaywrighttesting/fake/accounts_server.go
  sdk/resourcemanager/playwrighttesting/armplaywrighttesting/fake/quotas_server.go
  sdk/resourcemanager/playwrighttesting/armplaywrighttesting/fake/server_factory.go
  sdk/resourcemanager/playwrighttesting/armplaywrighttesting/fake/time_rfc3339.go
  sdk/resourcemanager/playwrighttesting/armplaywrighttesting/models.go
  sdk/resourcemanager/playwrighttesting/armplaywrighttesting/models_serde.go
  sdk/resourcemanager/playwrighttesting/armplaywrighttesting/operations_client.go
  sdk/resourcemanager/playwrighttesting/armplaywrighttesting/operations_client_example_test.go
  sdk/resourcemanager/playwrighttesting/armplaywrighttesting/options.go
  sdk/resourcemanager/playwrighttesting/armplaywrighttesting/quotas_client.go
  sdk/resourcemanager/playwrighttesting/armplaywrighttesting/quotas_client_example_test.go
  sdk/resourcemanager/playwrighttesting/armplaywrighttesting/responses.go
  sdk/resourcemanager/playwrighttesting/armplaywrighttesting/time_rfc3339.go
Labels: BreakingChange, FirstGA

#23823 [Release] sdk/resourcemanager/servicefabricmanagedclusters/armservicefabricmanagedclusters/0.3.0
  sdk/resourcemanager/servicefabricmanagedclusters/armservicefabricmanagedclusters/CHANGELOG.md
  sdk/resourcemanager/servicefabricmanagedclusters/armservicefabricmanagedclusters/applications_client.go
  sdk/resourcemanager/servicefabricmanagedclusters/armservicefabricmanagedclusters/applications_client_example_test.go
  sdk/resourcemanager/servicefabricmanagedclusters/armservicefabricmanagedclusters/applicationtypes_client.go
  sdk/resourcemanager/servicefabricmanagedclusters/armservicefabricmanagedclusters/applicationtypes_client_example_test.go
  sdk/resourcemanager/servicefabricmanagedclusters/armservicefabricmanagedclusters/applicationtypeversions_client.go
  sdk/resourcemanager/servicefabricmanagedclusters/armservicefabricmanagedclusters/applicationtypeversions_client_example_test.go
  sdk/resourcemanager/servicefabricmanagedclusters/armservicefabricmanagedclusters/autorest.md
  sdk/resourcemanager/servicefabricmanagedclusters/armservicefabricmanagedclusters/constants.go
  sdk/resourcemanager/servicefabricmanagedclusters/armservicefabricmanagedclusters/fake/nodetypes_server.go
  sdk/resourcemanager/servicefabricmanagedclusters/armservicefabricmanagedclusters/go.mod
  sdk/resourcemanager/servicefabricmanagedclusters/armservicefabricmanagedclusters/go.sum
  sdk/resourcemanager/servicefabricmanagedclusters/armservicefabricmanagedclusters/managedapplymaintenancewindow_client.go
  sdk/resourcemanager/servicefabricmanagedclusters/armservicefabricmanagedclusters/managedapplymaintenancewindow_client_example_test.go
  sdk/resourcemanager/servicefabricmanagedclusters/armservicefabricmanagedclusters/managedazresiliencystatus_client.go
  sdk/resourcemanager/servicefabricmanagedclusters/armservicefabricmanagedclusters/managedazresiliencystatus_client_example_test.go
  sdk/resourcemanager/servicefabricmanagedclusters/armservicefabricmanagedclusters/managedclusters_client.go
  sdk/resourcemanager/servicefabricmanagedclusters/armservicefabricmanagedclusters/managedclusters_client_example_test.go
  sdk/resourcemanager/servicefabricmanagedclusters/armservicefabricmanagedclusters/managedclusterversion_client.go
  sdk/resourcemanager/servicefabricmanagedclusters/armservicefabricmanagedclusters/managedclusterversion_client_example_test.go
  sdk/resourcemanager/servicefabricmanagedclusters/armservicefabricmanagedclusters/managedmaintenancewindowstatus_client.go
  sdk/resourcemanager/servicefabricmanagedclusters/armservicefabricmanagedclusters/managedmaintenancewindowstatus_client_example_test.go
  sdk/resourcemanager/servicefabricmanagedclusters/armservicefabricmanagedclusters/managedunsupportedvmsizes_client.go
  sdk/resourcemanager/servicefabricmanagedclusters/armservicefabricmanagedclusters/managedunsupportedvmsizes_client_example_test.go
  sdk/resourcemanager/servicefabricmanagedclusters/armservicefabricmanagedclusters/models.go
  sdk/resourcemanager/servicefabricmanagedclusters/armservicefabricmanagedclusters/models_serde.go
  sdk/resourcemanager/servicefabricmanagedclusters/armservicefabricmanagedclusters/nodetypes_client.go
  sdk/resourcemanager/servicefabricmanagedclusters/armservicefabricmanagedclusters/nodetypes_client_example_test.go
  sdk/resourcemanager/servicefabricmanagedclusters/armservicefabricmanagedclusters/nodetypeskus_client.go
  sdk/resourcemanager/servicefabricmanagedclusters/armservicefabricmanagedclusters/nodetypeskus_client_example_test.go
  sdk/resourcemanager/servicefabricmanagedclusters/armservicefabricmanagedclusters/operationresults_client.go
  sdk/resourcemanager/servicefabricmanagedclusters/armservicefabricmanagedclusters/operationresults_client_example_test.go
  sdk/resourcemanager/servicefabricmanagedclusters/armservicefabricmanagedclusters/operations_client.go
  sdk/resourcemanager/servicefabricmanagedclusters/armservicefabricmanagedclusters/operations_client_example_test.go
  sdk/resourcemanager/servicefabricmanagedclusters/armservicefabricmanagedclusters/operationstatus_client.go
  sdk/resourcemanager/servicefabricmanagedclusters/armservicefabricmanagedclusters/operationstatus_client_example_test.go
  sdk/resourcemanager/servicefabricmanagedclusters/armservicefabricmanagedclusters/options.go
  sdk/resourcemanager/servicefabricmanagedclusters/armservicefabricmanagedclusters/responses.go
  sdk/resourcemanager/servicefabricmanagedclusters/armservicefabricmanagedclusters/services_client.go
  sdk/resourcemanager/servicefabricmanagedclusters/armservicefabricmanagedclusters/services_client_example_test.go
Labels: BreakingChange, Beta

#23381 [azcore] Add text [un]marshalling support to ResourceID
  sdk/azcore/CHANGELOG.md
  sdk/azcore/arm/internal/resource/resource_identifier.go
  sdk/azcore/arm/internal/resource/resource_identifier_test.go
Labels: customer-reported, Azure.Core, Community Contribution

#23871 [azmetrics] add api version support
  sdk/monitor/query/azmetrics/CHANGELOG.md
  sdk/monitor/query/azmetrics/client_test.go
  sdk/monitor/query/azmetrics/custom_client.go
  sdk/monitor/query/azmetrics/version.go
Labels: Monitor, Client

#23872 Add error code in azfile error codes.go
  sdk/storage/azfile/assets.json
  sdk/storage/azfile/fileerror/error_codes.go
  sdk/storage/azfile/share/client_test.go
Labels: Storage

#23861 [Release] sdk/resourcemanager/deviceregistry/armdeviceregistry/0.2.0
  sdk/resourcemanager/deviceregistry/armdeviceregistry/CHANGELOG.md
  sdk/resourcemanager/deviceregistry/armdeviceregistry/assetendpointprofiles_client.go
  sdk/resourcemanager/deviceregistry/armdeviceregistry/assetendpointprofiles_client_example_test.go
  sdk/resourcemanager/deviceregistry/armdeviceregistry/assets_client.go
  sdk/resourcemanager/deviceregistry/armdeviceregistry/assets_client_example_test.go
  sdk/resourcemanager/deviceregistry/armdeviceregistry/autorest.md
  sdk/resourcemanager/deviceregistry/armdeviceregistry/billingcontainers_client.go
  sdk/resourcemanager/deviceregistry/armdeviceregistry/build.go
  sdk/resourcemanager/deviceregistry/armdeviceregistry/client_factory.go
  sdk/resourcemanager/deviceregistry/armdeviceregistry/constants.go
  sdk/resourcemanager/deviceregistry/armdeviceregistry/fake/assetendpointprofiles_server.go
  sdk/resourcemanager/deviceregistry/armdeviceregistry/fake/assets_server.go
  sdk/resourcemanager/deviceregistry/armdeviceregistry/fake/billingcontainers_server.go
  sdk/resourcemanager/deviceregistry/armdeviceregistry/fake/internal.go
  sdk/resourcemanager/deviceregistry/armdeviceregistry/fake/operations_server.go
  sdk/resourcemanager/deviceregistry/armdeviceregistry/fake/operationstatus_server.go
  sdk/resourcemanager/deviceregistry/armdeviceregistry/fake/server_factory.go
  sdk/resourcemanager/deviceregistry/armdeviceregistry/fake/time_rfc3339.go
  sdk/resourcemanager/deviceregistry/armdeviceregistry/go.mod
  sdk/resourcemanager/deviceregistry/armdeviceregistry/go.sum
  sdk/resourcemanager/deviceregistry/armdeviceregistry/models.go
  sdk/resourcemanager/deviceregistry/armdeviceregistry/models_serde.go
  sdk/resourcemanager/deviceregistry/armdeviceregistry/operations_client.go
  sdk/resourcemanager/deviceregistry/armdeviceregistry/operations_client_example_test.go
  sdk/resourcemanager/deviceregistry/armdeviceregistry/operationstatus_client.go
  sdk/resourcemanager/deviceregistry/armdeviceregistry/operationstatus_client_example_test.go
  sdk/resourcemanager/deviceregistry/armdeviceregistry/options.go
  sdk/resourcemanager/deviceregistry/armdeviceregistry/responses.go
  sdk/resourcemanager/deviceregistry/armdeviceregistry/time_rfc3339.go
  sdk/resourcemanager/deviceregistry/armdeviceregistry/tsp-location.yaml
Labels: Mgmt

#23880 Adls sas url from user delegation key
  sdk/storage/azdatalake/CHANGELOG.md
  sdk/storage/azdatalake/file/client_test.go
  sdk/storage/azdatalake/internal/exported/version.go
  sdk/storage/azdatalake/internal/testcommon/clients_auth.go
Labels: Storage

#23888 Documentation correction for create container error
  sdk/storage/azblob/client.go
Labels: Storage

#23801 Added BlobProperties field to BlobPrefix in listblob response
  sdk/storage/azblob/CHANGELOG.md
  sdk/storage/azblob/internal/generated/autorest.md
  sdk/storage/azblob/internal/generated/zz_models.go
Labels: Storage, customer-reported, Community Contribution
