Repository Azure/azure-sdk-for-go, pull requests merged in 2025-03, with the labels that each got.

#24189 Sync eng/common directory with azure-sdk-tools for PR 9950
  eng/common/pipelines/templates/archetype-typespec-emitter.yml
  eng/common/pipelines/templates/jobs/prepare-pipelines.yml
Labels: EngSys, Central-EngSys

#24196 Sync eng/common directory with azure-sdk-tools for PR 9955
  eng/common/scripts/Detect-Api-Changes.ps1
Labels: EngSys, Central-EngSys

#24197 Sync eng/common directory with azure-sdk-tools for PR 9945
  eng/common/scripts/job-matrix/Create-PrJobMatrix.ps1
Labels: EngSys, Central-EngSys

#24198 [azeventhubs] Fixed bug where AMQP sessions weren't being closed.
  sdk/messaging/azeventhubs/CHANGELOG.md
  sdk/messaging/azeventhubs/internal/constants.go
  sdk/messaging/azeventhubs/internal/links.go
  sdk/messaging/azeventhubs/internal/links_unit_test.go
Labels: Event Hubs

#24166 Don't run apiview for eng changes
  eng/pipelines/templates/steps/analyze.yml
Labels: Central-EngSys

#24202 Sync eng/common directory with azure-sdk-tools for PR 9963
  eng/common/scripts/Package-Properties.ps1
Labels: EngSys, Central-EngSys

#24207 Revert "Don't run apiview for eng changes"
  eng/pipelines/templates/steps/analyze.yml
Labels: Central-EngSys

#24205 [docs] module deprecation guide
  documentation/deprecation_guide.md
Labels: Docs

#24209 Sync eng/common directory with azure-sdk-tools for PR 9982
  eng/common/pipelines/templates/steps/sparse-checkout.yml
Labels: EngSys, Central-EngSys

#24204 Sync eng/common directory with azure-sdk-tools for PR 9918
  eng/common/scripts/job-matrix/pullrequest-faq.md
Labels: EngSys, Central-EngSys

#24199 [azcertificates] generate 7.6-preview.2
  sdk/security/keyvault/azcertificates/CHANGELOG.md
  sdk/security/keyvault/azcertificates/assets.json
  sdk/security/keyvault/azcertificates/client.go
  sdk/security/keyvault/azcertificates/client_test.go
  sdk/security/keyvault/azcertificates/models.go
  sdk/security/keyvault/azcertificates/models_serde.go
  sdk/security/keyvault/azcertificates/tsp-location.yaml
Labels: KeyVault, Client

#24219 Remove deprecated flow content from README
  sdk/azidentity/README.md
Labels: Azure.Identity

#24173 [azsecrets] generate 7.6-preview.2
  sdk/security/keyvault/azsecrets/CHANGELOG.md
  sdk/security/keyvault/azsecrets/assets.json
  sdk/security/keyvault/azsecrets/client.go
  sdk/security/keyvault/azsecrets/tsp-location.yaml
Labels: KeyVault, Client

#24216 Address 1ES Release Warning
  eng/pipelines/templates/jobs/archetype-go-release.yml
  sdk/template/aztemplate/CHANGELOG.md
  sdk/template/aztemplate/version.go
Labels: EngSys

#24226 Sync eng/common directory with azure-sdk-tools for PR 10013
  eng/common/TestResources/New-TestResources.ps1
Labels: EngSys, Central-EngSys

#24229 [azkeys] generate 7.6-preview.2
  sdk/security/keyvault/azkeys/CHANGELOG.md
  sdk/security/keyvault/azkeys/assets.json
  sdk/security/keyvault/azkeys/client.go
  sdk/security/keyvault/azkeys/client_test.go
  sdk/security/keyvault/azkeys/constants.go
  sdk/security/keyvault/azkeys/models.go
  sdk/security/keyvault/azkeys/models_serde.go
  sdk/security/keyvault/azkeys/options.go
  sdk/security/keyvault/azkeys/responses.go
  sdk/security/keyvault/azkeys/tsp-location.yaml
Labels: KeyVault, Client

#24220 [azadmin] generate 7.6-preview.2
  sdk/security/keyvault/azadmin/CHANGELOG.md
  sdk/security/keyvault/azadmin/assets.json
  sdk/security/keyvault/azadmin/backup/client.go
  sdk/security/keyvault/azadmin/backup/client_test.go
  sdk/security/keyvault/azadmin/backup/custom_client.go
  sdk/security/keyvault/azadmin/backup/models.go
  sdk/security/keyvault/azadmin/backup/models_serde.go
  sdk/security/keyvault/azadmin/backup/options.go
  sdk/security/keyvault/azadmin/backup/responses.go
  sdk/security/keyvault/azadmin/backup/tsp-location.yaml
  sdk/security/keyvault/azadmin/build.go
  sdk/security/keyvault/azadmin/internal/generate/transforms.go
  sdk/security/keyvault/azadmin/internal/version.go
  sdk/security/keyvault/azadmin/rbac/client.go
  sdk/security/keyvault/azadmin/rbac/tsp-location.yaml
  sdk/security/keyvault/azadmin/settings/client.go
  sdk/security/keyvault/azadmin/settings/tsp-location.yaml
Labels: KeyVault, Client

#24241 [azeventhubs] Update release notes
  sdk/messaging/azeventhubs/CHANGELOG.md
Labels: Event Hubs

#24240 Sync eng/common directory with azure-sdk-tools for PR 9993
  eng/common/scripts/Package-Properties.ps1
Labels: EngSys, Central-EngSys

#24242 Increment version for security/keyvault/internal releases
  sdk/security/keyvault/internal/CHANGELOG.md
  sdk/security/keyvault/internal/constants.go
Labels: KeyVault

#24256 Sync eng/common directory with azure-sdk-tools for PR 10028
  eng/common/scripts/Package-Properties.ps1
Labels: EngSys, Central-EngSys

#24111 Fix return value of DownloadBuffer when HTTPRange count is less than data length
  sdk/storage/azblob/CHANGELOG.md
  sdk/storage/azblob/assets.json
  sdk/storage/azblob/blob/client.go
  sdk/storage/azblob/blob/client_test.go
  sdk/storage/azblob/client_test.go
  sdk/storage/azfile/CHANGELOG.md
  sdk/storage/azfile/file/client.go
  sdk/storage/azfile/file/client_test.go
Labels: Storage, customer-reported, Community Contribution, AzFile, AzBlob

#24245 Sync eng/common directory with azure-sdk-tools for PR 10027
  eng/common/TestResources/New-TestResources.ps1
Labels: EngSys, Central-EngSys

#24263 [azcertificates] fix tests
  sdk/security/keyvault/azcertificates/assets.json
  sdk/security/keyvault/azcertificates/client_test.go
Labels: KeyVault

#24260 Sync eng/common directory with azure-sdk-tools for PR 10039
  eng/common/scripts/job-matrix/Create-PrJobMatrix.ps1
Labels: EngSys, Central-EngSys

#24264 Sync eng/common directory with azure-sdk-tools for PR 10041
  eng/common/scripts/Helpers/Resource-Helpers.ps1
Labels: EngSys, Central-EngSys

#24272 Sync eng/common directory with azure-sdk-tools for PR 10046
  eng/common/scripts/job-matrix/Create-PrJobMatrix.ps1
Labels: EngSys, Central-EngSys

#24266 Sync eng/common directory with azure-sdk-tools for PR 10045
  eng/common/pipelines/templates/jobs/prepare-pipelines.yml
Labels: EngSys, Central-EngSys

#24206 Skip apireview creation on main scheduled+ci pipelines for non-sdk changes
  eng/pipelines/templates/steps/analyze.yml
Labels: Central-EngSys

#24275 Sync .github/workflows directory with azure-sdk-tools for PR 10054
  .github/workflows/event-processor.yml
  .github/workflows/scheduled-event-processor.yml
Labels: EngSys, Central-EngSys

#24269 [stress] Fixing the stress tests so they're now a bit cleaner and work again
  .github/CODEOWNERS
  sdk/messaging/stress/.gitignore
  sdk/messaging/stress/go.mod
  sdk/messaging/stress/go.sum
  sdk/messaging/stress/internal/servicebus/.helmignore
  sdk/messaging/stress/internal/servicebus/Dockerfile
  sdk/messaging/stress/internal/servicebus/README.md
  sdk/messaging/stress/internal/servicebus/deploy.ps1
  sdk/messaging/stress/internal/servicebus/main.go
  sdk/messaging/stress/internal/servicebus/scenarios-matrix.yaml
  sdk/messaging/stress/internal/servicebus/shared/streaming_batch.go
  sdk/messaging/stress/internal/servicebus/templates/stress-test-job.yaml
  sdk/messaging/stress/internal/servicebus/tests/benchmarks/backup_settlement_leak_test.go
  sdk/messaging/stress/internal/servicebus/tests/benchmarks/main_test.go
  sdk/messaging/stress/internal/servicebus/tests/tests.go
Labels: Service Bus

#24273 [Cosmos] Add an abstraction and option to integrate an external client-side query engine
  sdk/data/azcosmos/CHANGELOG.md
  sdk/data/azcosmos/cosmos_container.go
  sdk/data/azcosmos/cosmos_container_query_engine.go
  sdk/data/azcosmos/cosmos_container_query_engine_test.go
  sdk/data/azcosmos/cosmos_http_constants.go
  sdk/data/azcosmos/cosmos_query_request_options.go
  sdk/data/azcosmos/internal/mock_query_engine.go
  sdk/data/azcosmos/unstable/README.md
  sdk/data/azcosmos/unstable/queryengine/cosmos_query_engine.go
Labels: Cosmos

#24265 Use same matrix for ci and live tests. Bump go test versions.
  eng/pipelines/templates/jobs/archetype-sdk-client.yml
  eng/pipelines/templates/jobs/ci.tests.yml
  eng/pipelines/templates/stages/ci-platform-matrix-complete.json
  eng/pipelines/templates/stages/ci-platform-matrix.json
  eng/pipelines/templates/stages/platform-matrix.json
  eng/tools/generator/ci.yml
  sdk/ai/azopenaiextensions/ci.yml
  sdk/data/azcosmos/ci.yml
  sdk/tracing/azotel/ci.yml
Labels: Central-EngSys

#24282 [Release] sdk/resourcemanager/resources/armpolicy/0.10.0
  sdk/resourcemanager/resources/armpolicy/CHANGELOG.md
  sdk/resourcemanager/resources/armpolicy/README.md
  sdk/resourcemanager/resources/armpolicy/assets.json
  sdk/resourcemanager/resources/armpolicy/assignments_client.go
  sdk/resourcemanager/resources/armpolicy/assignments_client_example_test.go
  sdk/resourcemanager/resources/armpolicy/autorest.md
  sdk/resourcemanager/resources/armpolicy/client_factory.go
  sdk/resourcemanager/resources/armpolicy/constants.go
  sdk/resourcemanager/resources/armpolicy/datapolicymanifests_client.go
  sdk/resourcemanager/resources/armpolicy/datapolicymanifests_client_example_test.go
  sdk/resourcemanager/resources/armpolicy/definitions_client.go
  sdk/resourcemanager/resources/armpolicy/definitions_client_example_test.go
  sdk/resourcemanager/resources/armpolicy/definitionversions_client.go
  sdk/resourcemanager/resources/armpolicy/definitionversions_client_example_test.go
  sdk/resourcemanager/resources/armpolicy/exemptions_client.go
  sdk/resourcemanager/resources/armpolicy/exemptions_client_example_test.go
  sdk/resourcemanager/resources/armpolicy/fake/assignments_server.go
  sdk/resourcemanager/resources/armpolicy/fake/datapolicymanifests_server.go
  sdk/resourcemanager/resources/armpolicy/fake/definitions_server.go
  sdk/resourcemanager/resources/armpolicy/fake/definitionversions_server.go
  sdk/resourcemanager/resources/armpolicy/fake/exemptions_server.go
  sdk/resourcemanager/resources/armpolicy/fake/internal.go
  sdk/resourcemanager/resources/armpolicy/fake/server_factory.go
  sdk/resourcemanager/resources/armpolicy/fake/setdefinitions_server.go
  sdk/resourcemanager/resources/armpolicy/fake/setdefinitionversions_server.go
  sdk/resourcemanager/resources/armpolicy/fake/time_rfc3339.go
  sdk/resourcemanager/resources/armpolicy/fake/variables_server.go
  sdk/resourcemanager/resources/armpolicy/fake/variablevalues_server.go
  sdk/resourcemanager/resources/armpolicy/models.go
  sdk/resourcemanager/resources/armpolicy/models_serde.go
  sdk/resourcemanager/resources/armpolicy/options.go
  sdk/resourcemanager/resources/armpolicy/responses.go
  sdk/resourcemanager/resources/armpolicy/setdefinitions_client.go
  sdk/resourcemanager/resources/armpolicy/setdefinitions_client_example_test.go
  sdk/resourcemanager/resources/armpolicy/setdefinitionversions_client.go
  sdk/resourcemanager/resources/armpolicy/setdefinitionversions_client_example_test.go
  sdk/resourcemanager/resources/armpolicy/time_rfc3339.go
  sdk/resourcemanager/resources/armpolicy/variables_client.go
  sdk/resourcemanager/resources/armpolicy/variables_client_example_test.go
  sdk/resourcemanager/resources/armpolicy/variablevalues_client.go
  sdk/resourcemanager/resources/armpolicy/variablevalues_client_example_test.go
Labels: Mgmt

#24285 Sync eng/common directory with azure-sdk-tools for PR 10081
  eng/common/scripts/job-matrix/job-matrix-functions.ps1
Labels: EngSys, Central-EngSys

#24223 [Release] sdk/resourcemanager/databox/armdatabox/2.2.0
  sdk/resourcemanager/databox/armdatabox/CHANGELOG.md
  sdk/resourcemanager/databox/armdatabox/README.md
  sdk/resourcemanager/databox/armdatabox/autorest.md
  sdk/resourcemanager/databox/armdatabox/client_factory.go
  sdk/resourcemanager/databox/armdatabox/constants.go
  sdk/resourcemanager/databox/armdatabox/fake/internal.go
  sdk/resourcemanager/databox/armdatabox/fake/jobs_server.go
  sdk/resourcemanager/databox/armdatabox/fake/management_server.go
  sdk/resourcemanager/databox/armdatabox/fake/operations_server.go
  sdk/resourcemanager/databox/armdatabox/fake/polymorphic_helpers.go
  sdk/resourcemanager/databox/armdatabox/fake/server_factory.go
  sdk/resourcemanager/databox/armdatabox/fake/service_server.go
  sdk/resourcemanager/databox/armdatabox/fake/time_rfc3339.go
  sdk/resourcemanager/databox/armdatabox/go.mod
  sdk/resourcemanager/databox/armdatabox/go.sum
  sdk/resourcemanager/databox/armdatabox/interfaces.go
  sdk/resourcemanager/databox/armdatabox/jobs_client.go
  sdk/resourcemanager/databox/armdatabox/jobs_client_example_test.go
  sdk/resourcemanager/databox/armdatabox/management_client.go
  sdk/resourcemanager/databox/armdatabox/management_client_example_test.go
  sdk/resourcemanager/databox/armdatabox/models.go
  sdk/resourcemanager/databox/armdatabox/models_serde.go
  sdk/resourcemanager/databox/armdatabox/operations_client.go
  sdk/resourcemanager/databox/armdatabox/operations_client_example_test.go
  sdk/resourcemanager/databox/armdatabox/options.go
  sdk/resourcemanager/databox/armdatabox/polymorphic_helpers.go
  sdk/resourcemanager/databox/armdatabox/responses.go
  sdk/resourcemanager/databox/armdatabox/service_client.go
  sdk/resourcemanager/databox/armdatabox/service_client_example_test.go
  sdk/resourcemanager/databox/armdatabox/time_rfc3339.go
Labels: Stable

#24295 Increment version for azcore releases
  sdk/azcore/CHANGELOG.md
  sdk/azcore/internal/shared/constants.go
Labels: Azure.Core

#24299 Sync eng/common directory with azure-sdk-tools for PR 10096
  eng/common/scripts/Package-Properties.ps1
  eng/common/scripts/Save-Package-Properties.ps1
Labels: EngSys, Central-EngSys

#24300 Sync eng/common directory with azure-sdk-tools for PR 10100
  eng/common/pipelines/templates/stages/archetype-spec-gen-sdk.yml
Labels: EngSys, Central-EngSys

#24293 Merge azcore v1.17.1 to main
  sdk/azcore/CHANGELOG.md
  sdk/azcore/go.mod
  sdk/azcore/go.sum
  sdk/azcore/testdata/perf/go.mod
  sdk/azcore/testdata/perf/go.sum
Labels: Azure.Core

#24292 [Release] sdk/resourcemanager/durabletask/armdurabletask/0.1.0
  sdk/resourcemanager/durabletask/armdurabletask/CHANGELOG.md
  sdk/resourcemanager/durabletask/armdurabletask/LICENSE.txt
  sdk/resourcemanager/durabletask/armdurabletask/README.md
  sdk/resourcemanager/durabletask/armdurabletask/ci.yml
  sdk/resourcemanager/durabletask/armdurabletask/client_factory.go
  sdk/resourcemanager/durabletask/armdurabletask/constants.go
  sdk/resourcemanager/durabletask/armdurabletask/fake/internal.go
  sdk/resourcemanager/durabletask/armdurabletask/fake/operations_server.go
  sdk/resourcemanager/durabletask/armdurabletask/fake/schedulers_server.go
  sdk/resourcemanager/durabletask/armdurabletask/fake/server_factory.go
  sdk/resourcemanager/durabletask/armdurabletask/fake/taskhubs_server.go
  sdk/resourcemanager/durabletask/armdurabletask/fake/time_rfc3339.go
  sdk/resourcemanager/durabletask/armdurabletask/go.mod
  sdk/resourcemanager/durabletask/armdurabletask/go.sum
  sdk/resourcemanager/durabletask/armdurabletask/models.go
  sdk/resourcemanager/durabletask/armdurabletask/models_serde.go
  sdk/resourcemanager/durabletask/armdurabletask/operations_client.go
  sdk/resourcemanager/durabletask/armdurabletask/operations_client_example_test.go
  sdk/resourcemanager/durabletask/armdurabletask/options.go
  sdk/resourcemanager/durabletask/armdurabletask/responses.go
  sdk/resourcemanager/durabletask/armdurabletask/schedulers_client.go
  sdk/resourcemanager/durabletask/armdurabletask/schedulers_client_example_test.go
  sdk/resourcemanager/durabletask/armdurabletask/taskhubs_client.go
  sdk/resourcemanager/durabletask/armdurabletask/taskhubs_client_example_test.go
  sdk/resourcemanager/durabletask/armdurabletask/time_rfc3339.go
  sdk/resourcemanager/durabletask/armdurabletask/tsp-location.yaml
Labels: Mgmt

#24190 [Release] sdk/resourcemanager/keyvault/armkeyvault/1.5.0
  sdk/resourcemanager/keyvault/armkeyvault/CHANGELOG.md
  sdk/resourcemanager/keyvault/armkeyvault/README.md
  sdk/resourcemanager/keyvault/armkeyvault/assets.json
  sdk/resourcemanager/keyvault/armkeyvault/autorest.md
  sdk/resourcemanager/keyvault/armkeyvault/client_factory.go
  sdk/resourcemanager/keyvault/armkeyvault/constants.go
  sdk/resourcemanager/keyvault/armkeyvault/fake/internal.go
  sdk/resourcemanager/keyvault/armkeyvault/fake/keys_server.go
  sdk/resourcemanager/keyvault/armkeyvault/fake/managedhsmkeys_server.go
  sdk/resourcemanager/keyvault/armkeyvault/fake/managedhsms_server.go
  sdk/resourcemanager/keyvault/armkeyvault/fake/mhsmprivateendpointconnections_server.go
  sdk/resourcemanager/keyvault/armkeyvault/fake/mhsmprivatelinkresources_server.go
  sdk/resourcemanager/keyvault/armkeyvault/fake/mhsmregions_server.go
  sdk/resourcemanager/keyvault/armkeyvault/fake/operations_server.go
  sdk/resourcemanager/keyvault/armkeyvault/fake/privateendpointconnections_server.go
  sdk/resourcemanager/keyvault/armkeyvault/fake/privatelinkresources_server.go
  sdk/resourcemanager/keyvault/armkeyvault/fake/secrets_server.go
  sdk/resourcemanager/keyvault/armkeyvault/fake/server_factory.go
  sdk/resourcemanager/keyvault/armkeyvault/fake/time_rfc3339.go
  sdk/resourcemanager/keyvault/armkeyvault/fake/time_unix.go
  sdk/resourcemanager/keyvault/armkeyvault/fake/vaults_server.go
  sdk/resourcemanager/keyvault/armkeyvault/keys_client.go
  sdk/resourcemanager/keyvault/armkeyvault/keys_client_example_test.go
  sdk/resourcemanager/keyvault/armkeyvault/keys_client_live_test.go
  sdk/resourcemanager/keyvault/armkeyvault/managedhsmkeys_client.go
  sdk/resourcemanager/keyvault/armkeyvault/managedhsmkeys_client_example_test.go
  sdk/resourcemanager/keyvault/armkeyvault/managedhsms_client.go
  sdk/resourcemanager/keyvault/armkeyvault/managedhsms_client_example_test.go
  sdk/resourcemanager/keyvault/armkeyvault/mhsmprivateendpointconnections_client.go
  sdk/resourcemanager/keyvault/armkeyvault/mhsmprivateendpointconnections_client_example_test.go
  sdk/resourcemanager/keyvault/armkeyvault/mhsmprivatelinkresources_client.go
  sdk/resourcemanager/keyvault/armkeyvault/mhsmprivatelinkresources_client_example_test.go
  sdk/resourcemanager/keyvault/armkeyvault/mhsmregions_client.go
  sdk/resourcemanager/keyvault/armkeyvault/mhsmregions_client_example_test.go
  sdk/resourcemanager/keyvault/armkeyvault/models.go
  sdk/resourcemanager/keyvault/armkeyvault/models_serde.go
  sdk/resourcemanager/keyvault/armkeyvault/operations_client.go
  sdk/resourcemanager/keyvault/armkeyvault/operations_client_example_test.go
  sdk/resourcemanager/keyvault/armkeyvault/options.go
  sdk/resourcemanager/keyvault/armkeyvault/privateendpointconnections_client.go
  sdk/resourcemanager/keyvault/armkeyvault/privateendpointconnections_client_example_test.go
  sdk/resourcemanager/keyvault/armkeyvault/privatelinkresources_client.go
  sdk/resourcemanager/keyvault/armkeyvault/privatelinkresources_client_example_test.go
  sdk/resourcemanager/keyvault/armkeyvault/responses.go
  sdk/resourcemanager/keyvault/armkeyvault/secrets_client.go
  sdk/resourcemanager/keyvault/armkeyvault/secrets_client_example_test.go
  sdk/resourcemanager/keyvault/armkeyvault/time_rfc3339.go
  sdk/resourcemanager/keyvault/armkeyvault/time_unix.go
  sdk/resourcemanager/keyvault/armkeyvault/vaults_client.go
  sdk/resourcemanager/keyvault/armkeyvault/vaults_client_example_test.go
Labels: Stable

#24268 Make temporal.Resource refreshing configurable
  sdk/internal/CHANGELOG.md
  sdk/internal/temporal/resource.go
  sdk/internal/temporal/resource_test.go
Labels: Internal

#24312 [azservicebus] Check that an annotation isn't nil before casting it to a string.
  sdk/messaging/azservicebus/CHANGELOG.md
  sdk/messaging/azservicebus/internal/constants.go
  sdk/messaging/azservicebus/message.go
  sdk/messaging/azservicebus/receiver_test.go
Labels: Service Bus

#24318 Sync eng/common directory with azure-sdk-tools for PR 10129
  eng/common/scripts/job-matrix/Create-PrJobMatrix.ps1
Labels: EngSys, Central-EngSys

#24294 Sync eng/common directory with azure-sdk-tools for PR 10099
  eng/common/TestResources/New-TestResources.ps1
  eng/common/TestResources/deploy-test-resources.yml
Labels: EngSys, Central-EngSys

#24322 [Release] sdk/resourcemanager/containerservice/armcontainerservice/6.5.0
  sdk/resourcemanager/containerservice/armcontainerservice/CHANGELOG.md
  sdk/resourcemanager/containerservice/armcontainerservice/agentpools_client.go
  sdk/resourcemanager/containerservice/armcontainerservice/agentpools_client_example_test.go
  sdk/resourcemanager/containerservice/armcontainerservice/assets.json
  sdk/resourcemanager/containerservice/armcontainerservice/autorest.md
  sdk/resourcemanager/containerservice/armcontainerservice/client.go
  sdk/resourcemanager/containerservice/armcontainerservice/client_example_test.go
  sdk/resourcemanager/containerservice/armcontainerservice/client_factory.go
  sdk/resourcemanager/containerservice/armcontainerservice/constants.go
  sdk/resourcemanager/containerservice/armcontainerservice/fake/loadbalancers_server.go
  sdk/resourcemanager/containerservice/armcontainerservice/fake/managedclusters_server.go
  sdk/resourcemanager/containerservice/armcontainerservice/fake/managedclustersnapshots_server.go
  sdk/resourcemanager/containerservice/armcontainerservice/fake/operationstatusresult_server.go
  sdk/resourcemanager/containerservice/armcontainerservice/fake/server.go
  sdk/resourcemanager/containerservice/armcontainerservice/fake/server_factory.go
  sdk/resourcemanager/containerservice/armcontainerservice/loadbalancers_client.go
  sdk/resourcemanager/containerservice/armcontainerservice/loadbalancers_client_example_test.go
  sdk/resourcemanager/containerservice/armcontainerservice/machines_client.go
  sdk/resourcemanager/containerservice/armcontainerservice/machines_client_example_test.go
  sdk/resourcemanager/containerservice/armcontainerservice/maintenanceconfigurations_client.go
  sdk/resourcemanager/containerservice/armcontainerservice/maintenanceconfigurations_client_example_test.go
  sdk/resourcemanager/containerservice/armcontainerservice/managedclusters_client.go
  sdk/resourcemanager/containerservice/armcontainerservice/managedclusters_client_example_test.go
  sdk/resourcemanager/containerservice/armcontainerservice/managedclustersnapshots_client.go
  sdk/resourcemanager/containerservice/armcontainerservice/managedclustersnapshots_client_example_test.go
  sdk/resourcemanager/containerservice/armcontainerservice/models.go
  sdk/resourcemanager/containerservice/armcontainerservice/models_serde.go
  sdk/resourcemanager/containerservice/armcontainerservice/operations_client.go
  sdk/resourcemanager/containerservice/armcontainerservice/operations_client_example_test.go
  sdk/resourcemanager/containerservice/armcontainerservice/operationstatusresult_client.go
  sdk/resourcemanager/containerservice/armcontainerservice/operationstatusresult_client_example_test.go
  sdk/resourcemanager/containerservice/armcontainerservice/options.go
  sdk/resourcemanager/containerservice/armcontainerservice/privateendpointconnections_client.go
  sdk/resourcemanager/containerservice/armcontainerservice/privateendpointconnections_client_example_test.go
  sdk/resourcemanager/containerservice/armcontainerservice/privatelinkresources_client.go
  sdk/resourcemanager/containerservice/armcontainerservice/privatelinkresources_client_example_test.go
  sdk/resourcemanager/containerservice/armcontainerservice/resolveprivatelinkserviceid_client.go
  sdk/resourcemanager/containerservice/armcontainerservice/resolveprivatelinkserviceid_client_example_test.go
  sdk/resourcemanager/containerservice/armcontainerservice/responses.go
  sdk/resourcemanager/containerservice/armcontainerservice/snapshots_client.go
  sdk/resourcemanager/containerservice/armcontainerservice/snapshots_client_example_test.go
  sdk/resourcemanager/containerservice/armcontainerservice/trustedaccessrolebindings_client.go
  sdk/resourcemanager/containerservice/armcontainerservice/trustedaccessrolebindings_client_example_test.go
  sdk/resourcemanager/containerservice/armcontainerservice/trustedaccessroles_client.go
  sdk/resourcemanager/containerservice/armcontainerservice/trustedaccessroles_client_example_test.go
Labels: Mgmt

#24284 CopyfilenfsProperty struct created
  sdk/storage/azfile/assets.json
  sdk/storage/azfile/file/client_test.go
  sdk/storage/azfile/file/models.go
  sdk/storage/azfile/internal/exported/copy_file_nfs_property.go
Labels: Storage

#24326 Sync eng/common directory with azure-sdk-tools for PR 10135
  eng/common/TestResources/deploy-test-resources.yml
Labels: EngSys, Central-EngSys

#24320 Fix azadmin HSM weekly deployment tests/timeout
  sdk/security/keyvault/azadmin/platform-matrix.json
  sdk/security/keyvault/azadmin/test-resources-post.ps1
  sdk/security/keyvault/azadmin/test-resources-pre.ps1
  sdk/security/keyvault/azkeys/ci.yml
  sdk/security/keyvault/azkeys/platform-matrix.json
  sdk/security/keyvault/azkeys/test-resources-post.ps1
Labels: Central-EngSys

#24335 Sync eng/common directory with azure-sdk-tools for PR 10004
  eng/common/scripts/Helpers/ApiView-Helpers.ps1
  eng/common/scripts/Invoke-GitHubAPI.ps1
Labels: EngSys, Central-EngSys

#24332 Sync eng/common directory with azure-sdk-tools for PR 10145
  eng/common/pipelines/templates/jobs/generate-job-matrix.yml
  eng/common/scripts/job-matrix/Create-PrJobMatrix.ps1
Labels: EngSys, Central-EngSys

#24156 Adopt MSAL managed identity implementation
  sdk/azidentity/assets.json
  sdk/azidentity/azidentity_test.go
  sdk/azidentity/default_azure_credential_test.go
  sdk/azidentity/live_test.go
  sdk/azidentity/managed_identity_client.go
  sdk/azidentity/managed_identity_client_test.go
  sdk/azidentity/managed_identity_credential.go
  sdk/azidentity/managed_identity_credential_test.go
Labels: Azure.Identity

#24252 [Release] sdk/resourcemanager/weightsandbiases/armweightsandbiases/0.1.0
  sdk/resourcemanager/weightsandbiases/armweightsandbiases/CHANGELOG.md
  sdk/resourcemanager/weightsandbiases/armweightsandbiases/LICENSE.txt
  sdk/resourcemanager/weightsandbiases/armweightsandbiases/README.md
  sdk/resourcemanager/weightsandbiases/armweightsandbiases/ci.yml
  sdk/resourcemanager/weightsandbiases/armweightsandbiases/client_factory.go
  sdk/resourcemanager/weightsandbiases/armweightsandbiases/constants.go
  sdk/resourcemanager/weightsandbiases/armweightsandbiases/fake/instances_server.go
  sdk/resourcemanager/weightsandbiases/armweightsandbiases/fake/internal.go
  sdk/resourcemanager/weightsandbiases/armweightsandbiases/fake/operations_server.go
  sdk/resourcemanager/weightsandbiases/armweightsandbiases/fake/server_factory.go
  sdk/resourcemanager/weightsandbiases/armweightsandbiases/fake/time_rfc3339.go
  sdk/resourcemanager/weightsandbiases/armweightsandbiases/go.mod
  sdk/resourcemanager/weightsandbiases/armweightsandbiases/go.sum
  sdk/resourcemanager/weightsandbiases/armweightsandbiases/instances_client.go
  sdk/resourcemanager/weightsandbiases/armweightsandbiases/instances_client_example_test.go
  sdk/resourcemanager/weightsandbiases/armweightsandbiases/models.go
  sdk/resourcemanager/weightsandbiases/armweightsandbiases/models_serde.go
  sdk/resourcemanager/weightsandbiases/armweightsandbiases/operations_client.go
  sdk/resourcemanager/weightsandbiases/armweightsandbiases/operations_client_example_test.go
  sdk/resourcemanager/weightsandbiases/armweightsandbiases/options.go
  sdk/resourcemanager/weightsandbiases/armweightsandbiases/responses.go
  sdk/resourcemanager/weightsandbiases/armweightsandbiases/time_rfc3339.go
  sdk/resourcemanager/weightsandbiases/armweightsandbiases/tsp-location.yaml
Labels: Mgmt

#24251 [Release] sdk/resourcemanager/arizeaiobservabilityeval/armarizeaiobservabilityeval/0.1.0
  sdk/resourcemanager/arizeaiobservabilityeval/armarizeaiobservabilityeval/CHANGELOG.md
  sdk/resourcemanager/arizeaiobservabilityeval/armarizeaiobservabilityeval/LICENSE.txt
  sdk/resourcemanager/arizeaiobservabilityeval/armarizeaiobservabilityeval/README.md
  sdk/resourcemanager/arizeaiobservabilityeval/armarizeaiobservabilityeval/ci.yml
  sdk/resourcemanager/arizeaiobservabilityeval/armarizeaiobservabilityeval/client_factory.go
  sdk/resourcemanager/arizeaiobservabilityeval/armarizeaiobservabilityeval/constants.go
  sdk/resourcemanager/arizeaiobservabilityeval/armarizeaiobservabilityeval/fake/internal.go
  sdk/resourcemanager/arizeaiobservabilityeval/armarizeaiobservabilityeval/fake/operations_server.go
  sdk/resourcemanager/arizeaiobservabilityeval/armarizeaiobservabilityeval/fake/organizations_server.go
  sdk/resourcemanager/arizeaiobservabilityeval/armarizeaiobservabilityeval/fake/server_factory.go
  sdk/resourcemanager/arizeaiobservabilityeval/armarizeaiobservabilityeval/fake/time_rfc3339.go
  sdk/resourcemanager/arizeaiobservabilityeval/armarizeaiobservabilityeval/go.mod
  sdk/resourcemanager/arizeaiobservabilityeval/armarizeaiobservabilityeval/go.sum
  sdk/resourcemanager/arizeaiobservabilityeval/armarizeaiobservabilityeval/models.go
  sdk/resourcemanager/arizeaiobservabilityeval/armarizeaiobservabilityeval/models_serde.go
  sdk/resourcemanager/arizeaiobservabilityeval/armarizeaiobservabilityeval/operations_client.go
  sdk/resourcemanager/arizeaiobservabilityeval/armarizeaiobservabilityeval/operations_client_example_test.go
  sdk/resourcemanager/arizeaiobservabilityeval/armarizeaiobservabilityeval/options.go
  sdk/resourcemanager/arizeaiobservabilityeval/armarizeaiobservabilityeval/organizations_client.go
  sdk/resourcemanager/arizeaiobservabilityeval/armarizeaiobservabilityeval/organizations_client_example_test.go
  sdk/resourcemanager/arizeaiobservabilityeval/armarizeaiobservabilityeval/responses.go
  sdk/resourcemanager/arizeaiobservabilityeval/armarizeaiobservabilityeval/time_rfc3339.go
  sdk/resourcemanager/arizeaiobservabilityeval/armarizeaiobservabilityeval/tsp-location.yaml
Labels: Mgmt

#24342 Remove prerelease tracing features from main
  sdk/azcore/CHANGELOG.md
  sdk/azcore/runtime/policy_http_trace.go
  sdk/azcore/runtime/policy_http_trace_test.go
  sdk/azcore/tracing/tracing.go
  sdk/azcore/tracing/tracing_test.go
  sdk/internal/CHANGELOG.md
  sdk/internal/go.mod
  sdk/internal/go.sum
  sdk/internal/test/tracingvalidator/validator.go
  sdk/internal/test/tracingvalidator/validator_test.go
  sdk/tracing/azotel/CHANGELOG.md
  sdk/tracing/azotel/go.mod
  sdk/tracing/azotel/go.sum
  sdk/tracing/azotel/otel.go
  sdk/tracing/azotel/otel_test.go
Labels: Azure.Core, Internal

#24334 Sync eng/common directory with azure-sdk-tools for PR 10134
  eng/common/scripts/Delete-RemoteTag.ps1
  eng/common/scripts/Helpers/git-helpers.ps1
  eng/common/scripts/Helpers/git-helpers.tests.ps1
Labels: EngSys, Central-EngSys
