Repository Azure/azure-sdk-for-go, pull requests merged in 2025-09, with the labels that each got.

#25187 Sync eng/common directory with azure-sdk-tools for PR 11974
  eng/common/scripts/Helpers/DevOps-WorkItem-Helpers.ps1
  eng/common/scripts/Update-PullRequest-In-ReleasePlan.ps1
Labels: EngSys, Central-EngSys

#25186 CLI credentials handle claims
  sdk/azidentity/CHANGELOG.md
  sdk/azidentity/azidentity_test.go
  sdk/azidentity/azure_cli_credential.go
  sdk/azidentity/azure_cli_credential_test.go
  sdk/azidentity/azure_developer_cli_credential.go
  sdk/azidentity/azure_developer_cli_credential_test.go
  sdk/azidentity/default_azure_credential_test.go
  sdk/azidentity/developer_credential_util.go
Labels: Azure.Identity

#25201 Users/gupta kashish/deprecation date update
  sdk/resourcemanager/playwrighttesting/armplaywrighttesting/CHANGELOG.md
  sdk/resourcemanager/playwrighttesting/armplaywrighttesting/README.md
  sdk/resourcemanager/playwrighttesting/armplaywrighttesting/constants.go
Labels: Mgmt

#25206 Return ResponseError for LROs with an unsuccessful initial response
  sdk/azcore/CHANGELOG.md
  sdk/azcore/runtime/poller.go
Labels: Azure.Core

#25192 Upgrade azidentity dependencies
  sdk/azidentity/cache/go.mod
  sdk/azidentity/cache/go.sum
  sdk/azidentity/go.mod
  sdk/azidentity/go.sum
  sdk/azidentity/mock_test.go
  sdk/azidentity/testdata/managed-id-test/go.mod
  sdk/azidentity/testdata/managed-id-test/go.sum
Labels: Azure.Identity

#25224 changes to blob spec document, and adding startFrom to listblob api (…
  sdk/storage/azblob/container/models.go
  sdk/storage/azblob/internal/generated/autorest.md
  sdk/storage/azblob/internal/generated/constants.go
  sdk/storage/azblob/internal/generated/zz_appendblob_client.go
  sdk/storage/azblob/internal/generated/zz_blob_client.go
  sdk/storage/azblob/internal/generated/zz_blockblob_client.go
  sdk/storage/azblob/internal/generated/zz_container_client.go
  sdk/storage/azblob/internal/generated/zz_models.go
  sdk/storage/azblob/internal/generated/zz_models_serde.go
  sdk/storage/azblob/internal/generated/zz_options.go
  sdk/storage/azblob/internal/generated/zz_pageblob_client.go
  sdk/storage/azblob/internal/generated/zz_service_client.go
Labels: Storage

#25234 [keyvault] Switch to gofmt
  sdk/security/keyvault/azadmin/backup/build.go
  sdk/security/keyvault/azadmin/rbac/build.go
  sdk/security/keyvault/azcertificates/build.go
  sdk/security/keyvault/azkeys/build.go
  sdk/security/keyvault/azsecrets/build.go
Labels: KeyVault

#25231 Prepare azidentity v1.12.0 for release
  sdk/azidentity/CHANGELOG.md
  sdk/azidentity/cache/go.mod
  sdk/azidentity/cache/go.sum
  sdk/azidentity/go.mod
  sdk/azidentity/go.sum
  sdk/azidentity/testdata/managed-id-test/go.mod
  sdk/azidentity/testdata/managed-id-test/go.sum
Labels: Azure.Identity

#25204 [Release-regeneration] sdk/resourcemanager/trustedsigning/armtrustedsigning/0.1.1
  sdk/resourcemanager/trustedsigning/armtrustedsigning/certificateprofiles_client.go
  sdk/resourcemanager/trustedsigning/armtrustedsigning/codesigningaccounts_client.go
  sdk/resourcemanager/trustedsigning/armtrustedsigning/constants.go
  sdk/resourcemanager/trustedsigning/armtrustedsigning/fake/certificateprofiles_server.go
  sdk/resourcemanager/trustedsigning/armtrustedsigning/fake/codesigningaccounts_server.go
  sdk/resourcemanager/trustedsigning/armtrustedsigning/fake/internal.go
  sdk/resourcemanager/trustedsigning/armtrustedsigning/fake/operations_server.go
  sdk/resourcemanager/trustedsigning/armtrustedsigning/fake/time_rfc3339.go
  sdk/resourcemanager/trustedsigning/armtrustedsigning/go.mod
  sdk/resourcemanager/trustedsigning/armtrustedsigning/go.sum
  sdk/resourcemanager/trustedsigning/armtrustedsigning/models.go
  sdk/resourcemanager/trustedsigning/armtrustedsigning/testdata/_metadata.json
  sdk/resourcemanager/trustedsigning/armtrustedsigning/tsp-location.yaml
  sdk/resourcemanager/trustedsigning/armtrustedsigning/version.go
Labels: Mgmt

#25202 [Release-regeneration] sdk/resourcemanager/neonpostgres/armneonpostgres/2.0.0
  sdk/resourcemanager/neonpostgres/armneonpostgres/branches_client.go
  sdk/resourcemanager/neonpostgres/armneonpostgres/branches_client_example_test.go
  sdk/resourcemanager/neonpostgres/armneonpostgres/computes_client.go
  sdk/resourcemanager/neonpostgres/armneonpostgres/computes_client_example_test.go
  sdk/resourcemanager/neonpostgres/armneonpostgres/constants.go
  sdk/resourcemanager/neonpostgres/armneonpostgres/endpoints_client.go
  sdk/resourcemanager/neonpostgres/armneonpostgres/endpoints_client_example_test.go
  sdk/resourcemanager/neonpostgres/armneonpostgres/fake/branches_server.go
  sdk/resourcemanager/neonpostgres/armneonpostgres/fake/computes_server.go
  sdk/resourcemanager/neonpostgres/armneonpostgres/fake/endpoints_server.go
  sdk/resourcemanager/neonpostgres/armneonpostgres/fake/neondatabases_server.go
  sdk/resourcemanager/neonpostgres/armneonpostgres/fake/neonroles_server.go
  sdk/resourcemanager/neonpostgres/armneonpostgres/fake/organizations_server.go
  sdk/resourcemanager/neonpostgres/armneonpostgres/fake/projects_server.go
  sdk/resourcemanager/neonpostgres/armneonpostgres/fake/time_rfc3339.go
  sdk/resourcemanager/neonpostgres/armneonpostgres/go.mod
  sdk/resourcemanager/neonpostgres/armneonpostgres/go.sum
  sdk/resourcemanager/neonpostgres/armneonpostgres/models.go
  sdk/resourcemanager/neonpostgres/armneonpostgres/neondatabases_client.go
  sdk/resourcemanager/neonpostgres/armneonpostgres/neondatabases_client_example_test.go
  sdk/resourcemanager/neonpostgres/armneonpostgres/neonpostgres_live_test.go
  sdk/resourcemanager/neonpostgres/armneonpostgres/neonroles_client.go
  sdk/resourcemanager/neonpostgres/armneonpostgres/neonroles_client_example_test.go
  sdk/resourcemanager/neonpostgres/armneonpostgres/operations_client_example_test.go
  sdk/resourcemanager/neonpostgres/armneonpostgres/options.go
  sdk/resourcemanager/neonpostgres/armneonpostgres/organizations_client.go
  sdk/resourcemanager/neonpostgres/armneonpostgres/organizations_client_example_test.go
  sdk/resourcemanager/neonpostgres/armneonpostgres/projects_client.go
  sdk/resourcemanager/neonpostgres/armneonpostgres/projects_client_example_test.go
  sdk/resourcemanager/neonpostgres/armneonpostgres/responses.go
  sdk/resourcemanager/neonpostgres/armneonpostgres/testdata/_metadata.json
  sdk/resourcemanager/neonpostgres/armneonpostgres/tsp-location.yaml
  sdk/resourcemanager/neonpostgres/armneonpostgres/version.go
Labels: Mgmt

#25226 [Azblob] [Storage] Blobtagsconditional headers
  sdk/storage/azblob/blob/client.go
  sdk/storage/azblob/blob/client_test.go
  sdk/storage/azblob/blob/models.go
  sdk/storage/azblob/internal/exported/access_conditions.go
  sdk/storage/azblob/internal/generated/autorest.md
  sdk/storage/azblob/internal/generated/zz_blob_client.go
Labels: Storage

#25168 [AutoPR sdk-resourcemanager/storagemover/armstoragemover]-generated-from-SDK Generation - Go-5276147
  sdk/resourcemanager/storagemover/armstoragemover/CHANGELOG.md
  sdk/resourcemanager/storagemover/armstoragemover/agent_live_test.go
  sdk/resourcemanager/storagemover/armstoragemover/agents_client.go
  sdk/resourcemanager/storagemover/armstoragemover/agents_client_example_test.go
  sdk/resourcemanager/storagemover/armstoragemover/autorest.md
  sdk/resourcemanager/storagemover/armstoragemover/build.go
  sdk/resourcemanager/storagemover/armstoragemover/client_factory.go
  sdk/resourcemanager/storagemover/armstoragemover/constants.go
  sdk/resourcemanager/storagemover/armstoragemover/endpoints_client.go
  sdk/resourcemanager/storagemover/armstoragemover/endpoints_client_example_test.go
  sdk/resourcemanager/storagemover/armstoragemover/fake/agents_server.go
  sdk/resourcemanager/storagemover/armstoragemover/fake/endpoints_server.go
  sdk/resourcemanager/storagemover/armstoragemover/fake/internal.go
  sdk/resourcemanager/storagemover/armstoragemover/fake/jobdefinitions_server.go
  sdk/resourcemanager/storagemover/armstoragemover/fake/jobruns_server.go
  sdk/resourcemanager/storagemover/armstoragemover/fake/operations_server.go
  sdk/resourcemanager/storagemover/armstoragemover/fake/projects_server.go
  sdk/resourcemanager/storagemover/armstoragemover/fake/server_factory.go
  sdk/resourcemanager/storagemover/armstoragemover/fake/storagemovers_server.go
  sdk/resourcemanager/storagemover/armstoragemover/fake/time_rfc3339.go
  sdk/resourcemanager/storagemover/armstoragemover/go.mod
  sdk/resourcemanager/storagemover/armstoragemover/go.sum
  sdk/resourcemanager/storagemover/armstoragemover/interfaces.go
  sdk/resourcemanager/storagemover/armstoragemover/jobdefinitions_client.go
  sdk/resourcemanager/storagemover/armstoragemover/jobdefinitions_client_example_test.go
  sdk/resourcemanager/storagemover/armstoragemover/jobruns_client.go
  sdk/resourcemanager/storagemover/armstoragemover/jobruns_client_example_test.go
  sdk/resourcemanager/storagemover/armstoragemover/models.go
  sdk/resourcemanager/storagemover/armstoragemover/models_serde.go
  sdk/resourcemanager/storagemover/armstoragemover/operations_client.go
  sdk/resourcemanager/storagemover/armstoragemover/operations_client_example_test.go
  sdk/resourcemanager/storagemover/armstoragemover/options.go
  sdk/resourcemanager/storagemover/armstoragemover/polymorphic_helpers.go
  sdk/resourcemanager/storagemover/armstoragemover/projects_client.go
  sdk/resourcemanager/storagemover/armstoragemover/projects_client_example_test.go
  sdk/resourcemanager/storagemover/armstoragemover/responses.go
  sdk/resourcemanager/storagemover/armstoragemover/storagemover_live_test.go
  sdk/resourcemanager/storagemover/armstoragemover/storagemovers_client.go
  sdk/resourcemanager/storagemover/armstoragemover/storagemovers_client_example_test.go
  sdk/resourcemanager/storagemover/armstoragemover/testdata/_metadata.json
  sdk/resourcemanager/storagemover/armstoragemover/time_rfc3339.go
  sdk/resourcemanager/storagemover/armstoragemover/tsp-location.yaml
  sdk/resourcemanager/storagemover/armstoragemover/version.go
Labels: Mgmt

#25262 Prepare azidentity 1.13.0-beta.1 for release
  sdk/azidentity/CHANGELOG.md
  sdk/azidentity/version.go
Labels: Azure.Identity

#25263 Increment version for azidentity releases
  sdk/azidentity/CHANGELOG.md
  sdk/azidentity/version.go
Labels: Azure.Identity

#25172 Update Changelog After 1.4.1
  sdk/data/azcosmos/CHANGELOG.md
Labels: Cosmos

#25267 Sync eng/common directory with azure-sdk-tools for PR 12124
  eng/common/instructions/azsdk-tools/typespec-to-sdk.instructions.md
Labels: EngSys, Central-EngSys

#25283 Sync eng/common directory with azure-sdk-tools for PR 11968
  eng/common/instructions/azsdk-tools/sdk-details-in-release-plan.instructions.md
Labels: EngSys, Central-EngSys

#25284 Sync eng/common directory with azure-sdk-tools for PR 11868
  eng/common/instructions/azsdk-tools/create-sdk-locally.instructions.md
  eng/common/instructions/azsdk-tools/local-sdk-workflow.instructions.md
  eng/common/instructions/azsdk-tools/typespec-to-sdk.instructions.md
Labels: EngSys, Central-EngSys

#25285 Sync eng/common directory with azure-sdk-tools for PR 12060
  eng/common/tsp-client/README.md
  eng/common/tsp-client/package-lock.json
  eng/common/tsp-client/package.json
Labels: EngSys, Central-EngSys

#25253 [Release-regeneration] sdk/resourcemanager/avs/armavs/2.1.0
  sdk/resourcemanager/avs/armavs/addons_client.go
  sdk/resourcemanager/avs/armavs/authorizations_client.go
  sdk/resourcemanager/avs/armavs/cloudlinks_client.go
  sdk/resourcemanager/avs/armavs/clusters_client.go
  sdk/resourcemanager/avs/armavs/datastores_client.go
  sdk/resourcemanager/avs/armavs/globalreachconnections_client.go
  sdk/resourcemanager/avs/armavs/go.mod
  sdk/resourcemanager/avs/armavs/go.sum
  sdk/resourcemanager/avs/armavs/hcxenterprisesites_client.go
  sdk/resourcemanager/avs/armavs/iscsipaths_client.go
  sdk/resourcemanager/avs/armavs/models.go
  sdk/resourcemanager/avs/armavs/placementpolicies_client.go
  sdk/resourcemanager/avs/armavs/privateclouds_client.go
  sdk/resourcemanager/avs/armavs/purestoragepolicies_client.go
  sdk/resourcemanager/avs/armavs/scriptexecutions_client.go
  sdk/resourcemanager/avs/armavs/testdata/_metadata.json
  sdk/resourcemanager/avs/armavs/tsp-location.yaml
  sdk/resourcemanager/avs/armavs/virtualmachines_client.go
  sdk/resourcemanager/avs/armavs/workloadnetworks_client.go
Labels: Mgmt

#25277 [Release-regeneration] sdk/resourcemanager/mongocluster/armmongocluster
  sdk/resourcemanager/mongocluster/armmongocluster/testdata/_metadata.json
  sdk/resourcemanager/mongocluster/armmongocluster/tsp-location.yaml
Labels: Mgmt

#25271 [Release-regeneration] sdk/resourcemanager/servicefabricmanagedclusters/armservicefabricmanagedclusters
  sdk/resourcemanager/servicefabricmanagedclusters/armservicefabricmanagedclusters/testdata/_metadata.json
  sdk/resourcemanager/servicefabricmanagedclusters/armservicefabricmanagedclusters/tsp-location.yaml
Labels: Mgmt

#25272 [Release-regeneration] sdk/resourcemanager/servicenetworking/armservicenetworking
  sdk/resourcemanager/servicenetworking/armservicenetworking/testdata/_metadata.json
  sdk/resourcemanager/servicenetworking/armservicenetworking/tsp-location.yaml
Labels: Mgmt

#25273 [Release-regeneration] sdk/resourcemanager/programmableconnectivity/armprogrammableconnectivity
  sdk/resourcemanager/programmableconnectivity/armprogrammableconnectivity/constants.go
  sdk/resourcemanager/programmableconnectivity/armprogrammableconnectivity/fake/gateways_server.go
  sdk/resourcemanager/programmableconnectivity/armprogrammableconnectivity/fake/operatorapiconnections_server.go
  sdk/resourcemanager/programmableconnectivity/armprogrammableconnectivity/fake/operatorapiplans_server.go
  sdk/resourcemanager/programmableconnectivity/armprogrammableconnectivity/gateways_client.go
  sdk/resourcemanager/programmableconnectivity/armprogrammableconnectivity/go.mod
  sdk/resourcemanager/programmableconnectivity/armprogrammableconnectivity/go.sum
  sdk/resourcemanager/programmableconnectivity/armprogrammableconnectivity/models.go
  sdk/resourcemanager/programmableconnectivity/armprogrammableconnectivity/operatorapiconnections_client.go
  sdk/resourcemanager/programmableconnectivity/armprogrammableconnectivity/responses.go
  sdk/resourcemanager/programmableconnectivity/armprogrammableconnectivity/testdata/_metadata.json
  sdk/resourcemanager/programmableconnectivity/armprogrammableconnectivity/tsp-location.yaml
  sdk/resourcemanager/programmableconnectivity/armprogrammableconnectivity/version.go
Labels: Mgmt

#25259 [Release-regeneration] sdk/resourcemanager/fabric/armfabric/1.0.0
  sdk/resourcemanager/fabric/armfabric/capacities_client.go
  sdk/resourcemanager/fabric/armfabric/constants.go
  sdk/resourcemanager/fabric/armfabric/fake/capacities_server.go
  sdk/resourcemanager/fabric/armfabric/fake/internal.go
  sdk/resourcemanager/fabric/armfabric/fake/operations_server.go
  sdk/resourcemanager/fabric/armfabric/fake/time_rfc3339.go
  sdk/resourcemanager/fabric/armfabric/go.mod
  sdk/resourcemanager/fabric/armfabric/go.sum
  sdk/resourcemanager/fabric/armfabric/models.go
  sdk/resourcemanager/fabric/armfabric/testdata/_metadata.json
  sdk/resourcemanager/fabric/armfabric/tsp-location.yaml
  sdk/resourcemanager/fabric/armfabric/version.go
Labels: Mgmt

#25270 [Release-regeneration] sdk/resourcemanager/recoveryservicesdatareplication/armrecoveryservicesdatareplication
  sdk/resourcemanager/recoveryservicesdatareplication/armrecoveryservicesdatareplication/constants.go
  sdk/resourcemanager/recoveryservicesdatareplication/armrecoveryservicesdatareplication/event_client.go
  sdk/resourcemanager/recoveryservicesdatareplication/armrecoveryservicesdatareplication/fabric_client.go
  sdk/resourcemanager/recoveryservicesdatareplication/armrecoveryservicesdatareplication/fabricagent_client.go
  sdk/resourcemanager/recoveryservicesdatareplication/armrecoveryservicesdatareplication/fake/event_server.go
  sdk/resourcemanager/recoveryservicesdatareplication/armrecoveryservicesdatareplication/fake/job_server.go
  sdk/resourcemanager/recoveryservicesdatareplication/armrecoveryservicesdatareplication/fake/protecteditem_server.go
  sdk/resourcemanager/recoveryservicesdatareplication/armrecoveryservicesdatareplication/go.mod
  sdk/resourcemanager/recoveryservicesdatareplication/armrecoveryservicesdatareplication/go.sum
  sdk/resourcemanager/recoveryservicesdatareplication/armrecoveryservicesdatareplication/job_client.go
  sdk/resourcemanager/recoveryservicesdatareplication/armrecoveryservicesdatareplication/models.go
  sdk/resourcemanager/recoveryservicesdatareplication/armrecoveryservicesdatareplication/options.go
  sdk/resourcemanager/recoveryservicesdatareplication/armrecoveryservicesdatareplication/policy_client.go
  sdk/resourcemanager/recoveryservicesdatareplication/armrecoveryservicesdatareplication/privateendpointconnectionproxies_client.go
  sdk/resourcemanager/recoveryservicesdatareplication/armrecoveryservicesdatareplication/privateendpointconnections_client.go
  sdk/resourcemanager/recoveryservicesdatareplication/armrecoveryservicesdatareplication/protecteditem_client.go
  sdk/resourcemanager/recoveryservicesdatareplication/armrecoveryservicesdatareplication/replicationextension_client.go
  sdk/resourcemanager/recoveryservicesdatareplication/armrecoveryservicesdatareplication/testdata/_metadata.json
  sdk/resourcemanager/recoveryservicesdatareplication/armrecoveryservicesdatareplication/tsp-location.yaml
  sdk/resourcemanager/recoveryservicesdatareplication/armrecoveryservicesdatareplication/vault_client.go
  sdk/resourcemanager/recoveryservicesdatareplication/armrecoveryservicesdatareplication/version.go
Labels: Mgmt

#25302 [Storage][Files] Making SMB Directory leases configurable on a share level
  sdk/storage/azfile/assets.json
  sdk/storage/azfile/share/client_test.go
  sdk/storage/azfile/share/models.go
Labels: Storage

#25322 Sync eng/common directory with azure-sdk-tools for PR 12235
  eng/common/scripts/Helpers/CommandInvocation-Helpers.ps1
  eng/common/scripts/logging.ps1
Labels: EngSys, Central-EngSys

#25337 [Release] sdk/resourcemanager/datamigration/armdatamigration/2.0.0
  sdk/resourcemanager/datamigration/armdatamigration/CHANGELOG.md
  sdk/resourcemanager/datamigration/armdatamigration/autorest.md
  sdk/resourcemanager/datamigration/armdatamigration/constants.go
  sdk/resourcemanager/datamigration/armdatamigration/databasemigrationsmongotocosmosdbrumongo_client.go
  sdk/resourcemanager/datamigration/armdatamigration/databasemigrationsmongotocosmosdbrumongo_client_example_test.go
  sdk/resourcemanager/datamigration/armdatamigration/databasemigrationsmongotocosmosdbvcoremongo_client.go
  sdk/resourcemanager/datamigration/armdatamigration/databasemigrationsmongotocosmosdbvcoremongo_client_example_test.go
  sdk/resourcemanager/datamigration/armdatamigration/databasemigrationssqldb_client.go
  sdk/resourcemanager/datamigration/armdatamigration/databasemigrationssqldb_client_example_test.go
  sdk/resourcemanager/datamigration/armdatamigration/databasemigrationssqlmi_client.go
  sdk/resourcemanager/datamigration/armdatamigration/databasemigrationssqlmi_client_example_test.go
  sdk/resourcemanager/datamigration/armdatamigration/databasemigrationssqlvm_client.go
  sdk/resourcemanager/datamigration/armdatamigration/databasemigrationssqlvm_client_example_test.go
  sdk/resourcemanager/datamigration/armdatamigration/fake/databasemigrationsmongotocosmosdbrumongo_server.go
  sdk/resourcemanager/datamigration/armdatamigration/fake/databasemigrationsmongotocosmosdbvcoremongo_server.go
  sdk/resourcemanager/datamigration/armdatamigration/fake/databasemigrationssqldb_server.go
  sdk/resourcemanager/datamigration/armdatamigration/fake/databasemigrationssqlmi_server.go
  sdk/resourcemanager/datamigration/armdatamigration/fake/databasemigrationssqlvm_server.go
  sdk/resourcemanager/datamigration/armdatamigration/fake/files_server.go
  sdk/resourcemanager/datamigration/armdatamigration/fake/migrationservices_server.go
  sdk/resourcemanager/datamigration/armdatamigration/fake/projects_server.go
  sdk/resourcemanager/datamigration/armdatamigration/fake/resourceskus_server.go
  sdk/resourcemanager/datamigration/armdatamigration/fake/services_server.go
  sdk/resourcemanager/datamigration/armdatamigration/fake/servicetasks_server.go
  sdk/resourcemanager/datamigration/armdatamigration/fake/sqlmigrationservices_server.go
  sdk/resourcemanager/datamigration/armdatamigration/fake/tasks_server.go
  sdk/resourcemanager/datamigration/armdatamigration/fake/usages_server.go
  sdk/resourcemanager/datamigration/armdatamigration/files_client.go
  sdk/resourcemanager/datamigration/armdatamigration/files_client_example_test.go
  sdk/resourcemanager/datamigration/armdatamigration/go.mod
  sdk/resourcemanager/datamigration/armdatamigration/go.sum
  sdk/resourcemanager/datamigration/armdatamigration/migrationservices_client.go
  sdk/resourcemanager/datamigration/armdatamigration/migrationservices_client_example_test.go
  sdk/resourcemanager/datamigration/armdatamigration/models.go
  sdk/resourcemanager/datamigration/armdatamigration/models_serde.go
  sdk/resourcemanager/datamigration/armdatamigration/operations_client.go
  sdk/resourcemanager/datamigration/armdatamigration/operations_client_example_test.go
  sdk/resourcemanager/datamigration/armdatamigration/options.go
  sdk/resourcemanager/datamigration/armdatamigration/projects_client.go
  sdk/resourcemanager/datamigration/armdatamigration/projects_client_example_test.go
  sdk/resourcemanager/datamigration/armdatamigration/resourceskus_client.go
  sdk/resourcemanager/datamigration/armdatamigration/resourceskus_client_example_test.go
  sdk/resourcemanager/datamigration/armdatamigration/responses.go
  sdk/resourcemanager/datamigration/armdatamigration/services_client.go
  sdk/resourcemanager/datamigration/armdatamigration/services_client_example_test.go
  sdk/resourcemanager/datamigration/armdatamigration/servicetasks_client.go
  sdk/resourcemanager/datamigration/armdatamigration/servicetasks_client_example_test.go
  sdk/resourcemanager/datamigration/armdatamigration/sqlmigrationservices_client.go
  sdk/resourcemanager/datamigration/armdatamigration/sqlmigrationservices_client_example_test.go
  sdk/resourcemanager/datamigration/armdatamigration/tasks_client.go
  sdk/resourcemanager/datamigration/armdatamigration/tasks_client_example_test.go
  sdk/resourcemanager/datamigration/armdatamigration/usages_client.go
  sdk/resourcemanager/datamigration/armdatamigration/usages_client_example_test.go
  sdk/resourcemanager/datamigration/armdatamigration/version.go
Labels: Mgmt

#25347 Sync eng/common directory with azure-sdk-tools for PR 12246
  eng/common/mcp/azure-sdk-mcp.ps1
Labels: EngSys, Central-EngSys

#25325 DefaultAzureCredential: disable IMDS probe when ManagedIdentityCredential selected
  sdk/azidentity/CHANGELOG.md
  sdk/azidentity/default_azure_credential.go
  sdk/azidentity/default_azure_credential_test.go
  sdk/azidentity/version.go
Labels: Azure.Identity
