Repository Azure/azure-sdk-for-go, pull requests merged in 2025-08, with the labels that each got.

#25018 cosmos: Merge 1.5.0 beta branch to main
  sdk/data/azcosmos/CHANGELOG.md
  sdk/data/azcosmos/cosmos_container.go
  sdk/data/azcosmos/cosmos_container_query_engine.go
  sdk/data/azcosmos/cosmos_container_query_engine_test.go
  sdk/data/azcosmos/cosmos_query_request_options.go
  sdk/data/azcosmos/internal/mock_query_engine.go
  sdk/data/azcosmos/queryengine/cosmos_query_engine.go
  sdk/data/azcosmos/version.go
Labels: Cosmos

#25045 Sync eng/common directory with azure-sdk-tools for PR 11493
  eng/common/mcp/README.md
Labels: EngSys, Central-EngSys

#25050 Increment version for azidentity releases
  sdk/azidentity/CHANGELOG.md
  sdk/azidentity/version.go
Labels: Azure.Identity

#25051 Sync eng/common directory with azure-sdk-tools for PR 11524
  eng/common/testproxy/target_version.txt
Labels: EngSys, Central-EngSys

#25052 Sync eng/common directory with azure-sdk-tools for PR 10749
  eng/common/TestResources/TestResources-Helpers.ps1
Labels: EngSys, Central-EngSys

#25047 [azservicebus] Prep for release.
  sdk/messaging/azservicebus/CHANGELOG.md
  sdk/messaging/azservicebus/go.mod
  sdk/messaging/azservicebus/go.sum
Labels: Service Bus

#25049 Increment version for storage/azdatalake releases
  sdk/storage/azdatalake/CHANGELOG.md
  sdk/storage/azdatalake/internal/exported/version.go
Labels: Storage

#25061 Sync eng/common directory with azure-sdk-tools for PR 11547
  eng/common/TestResources/New-TestResources.ps1
Labels: EngSys, Central-EngSys

#25062 [Release] sdk/resourcemanager/azurestackhci/armazurestackhcivm/0.1.0
  sdk/resourcemanager/azurestackhci/armazurestackhcivm/CHANGELOG.md
  sdk/resourcemanager/azurestackhci/armazurestackhcivm/LICENSE.txt
  sdk/resourcemanager/azurestackhci/armazurestackhcivm/README.md
  sdk/resourcemanager/azurestackhci/armazurestackhcivm/attestationstatuses_client.go
  sdk/resourcemanager/azurestackhci/armazurestackhcivm/attestationstatuses_client_example_test.go
  sdk/resourcemanager/azurestackhci/armazurestackhcivm/ci.yml
  sdk/resourcemanager/azurestackhci/armazurestackhcivm/client_factory.go
  sdk/resourcemanager/azurestackhci/armazurestackhcivm/constants.go
  sdk/resourcemanager/azurestackhci/armazurestackhcivm/fake/attestationstatuses_server.go
  sdk/resourcemanager/azurestackhci/armazurestackhcivm/fake/galleryimages_server.go
  sdk/resourcemanager/azurestackhci/armazurestackhcivm/fake/guestagents_server.go
  sdk/resourcemanager/azurestackhci/armazurestackhcivm/fake/hybrididentitymetadata_server.go
  sdk/resourcemanager/azurestackhci/armazurestackhcivm/fake/internal.go
  sdk/resourcemanager/azurestackhci/armazurestackhcivm/fake/logicalnetworks_server.go
  sdk/resourcemanager/azurestackhci/armazurestackhcivm/fake/marketplacegalleryimages_server.go
  sdk/resourcemanager/azurestackhci/armazurestackhcivm/fake/networkinterfaces_server.go
  sdk/resourcemanager/azurestackhci/armazurestackhcivm/fake/networksecuritygroups_server.go
  sdk/resourcemanager/azurestackhci/armazurestackhcivm/fake/securityrules_server.go
  sdk/resourcemanager/azurestackhci/armazurestackhcivm/fake/server_factory.go
  sdk/resourcemanager/azurestackhci/armazurestackhcivm/fake/storagecontainers_server.go
  sdk/resourcemanager/azurestackhci/armazurestackhcivm/fake/virtualharddisks_server.go
  sdk/resourcemanager/azurestackhci/armazurestackhcivm/fake/virtualmachineinstances_server.go
  sdk/resourcemanager/azurestackhci/armazurestackhcivm/galleryimages_client.go
  sdk/resourcemanager/azurestackhci/armazurestackhcivm/galleryimages_client_example_test.go
  sdk/resourcemanager/azurestackhci/armazurestackhcivm/go.mod
  sdk/resourcemanager/azurestackhci/armazurestackhcivm/go.sum
  sdk/resourcemanager/azurestackhci/armazurestackhcivm/guestagents_client.go
  sdk/resourcemanager/azurestackhci/armazurestackhcivm/guestagents_client_example_test.go
  sdk/resourcemanager/azurestackhci/armazurestackhcivm/hybrididentitymetadata_client.go
  sdk/resourcemanager/azurestackhci/armazurestackhcivm/hybrididentitymetadata_client_example_test.go
  sdk/resourcemanager/azurestackhci/armazurestackhcivm/logicalnetworks_client.go
  sdk/resourcemanager/azurestackhci/armazurestackhcivm/logicalnetworks_client_example_test.go
  sdk/resourcemanager/azurestackhci/armazurestackhcivm/marketplacegalleryimages_client.go
  sdk/resourcemanager/azurestackhci/armazurestackhcivm/marketplacegalleryimages_client_example_test.go
  sdk/resourcemanager/azurestackhci/armazurestackhcivm/models.go
  sdk/resourcemanager/azurestackhci/armazurestackhcivm/models_serde.go
  sdk/resourcemanager/azurestackhci/armazurestackhcivm/networkinterfaces_client.go
  sdk/resourcemanager/azurestackhci/armazurestackhcivm/networkinterfaces_client_example_test.go
  sdk/resourcemanager/azurestackhci/armazurestackhcivm/networksecuritygroups_client.go
  sdk/resourcemanager/azurestackhci/armazurestackhcivm/networksecuritygroups_client_example_test.go
  sdk/resourcemanager/azurestackhci/armazurestackhcivm/options.go
  sdk/resourcemanager/azurestackhci/armazurestackhcivm/responses.go
  sdk/resourcemanager/azurestackhci/armazurestackhcivm/securityrules_client.go
  sdk/resourcemanager/azurestackhci/armazurestackhcivm/securityrules_client_example_test.go
  sdk/resourcemanager/azurestackhci/armazurestackhcivm/storagecontainers_client.go
  sdk/resourcemanager/azurestackhci/armazurestackhcivm/storagecontainers_client_example_test.go
  sdk/resourcemanager/azurestackhci/armazurestackhcivm/testdata/_metadata.json
  sdk/resourcemanager/azurestackhci/armazurestackhcivm/time_rfc3339.go
  sdk/resourcemanager/azurestackhci/armazurestackhcivm/tsp-location.yaml
  sdk/resourcemanager/azurestackhci/armazurestackhcivm/version.go
  sdk/resourcemanager/azurestackhci/armazurestackhcivm/virtualharddisks_client.go
  sdk/resourcemanager/azurestackhci/armazurestackhcivm/virtualharddisks_client_example_test.go
  sdk/resourcemanager/azurestackhci/armazurestackhcivm/virtualmachineinstances_client.go
  sdk/resourcemanager/azurestackhci/armazurestackhcivm/virtualmachineinstances_client_example_test.go
Labels: Mgmt

#25046 Sync eng/common directory with azure-sdk-tools for PR 11330
  eng/common/spelling/Invoke-Cspell.ps1
  eng/common/spelling/README.md
Labels: EngSys, Central-EngSys

#25072 [Release] sdk/resourcemanager/servicefabricmanagedclusters/armservicefabricmanagedclusters/0.5.0
  sdk/resourcemanager/servicefabricmanagedclusters/armservicefabricmanagedclusters/CHANGELOG.md
  sdk/resourcemanager/servicefabricmanagedclusters/armservicefabricmanagedclusters/applications_client.go
  sdk/resourcemanager/servicefabricmanagedclusters/armservicefabricmanagedclusters/applications_client_example_test.go
  sdk/resourcemanager/servicefabricmanagedclusters/armservicefabricmanagedclusters/applicationtypes_client.go
  sdk/resourcemanager/servicefabricmanagedclusters/armservicefabricmanagedclusters/applicationtypes_client_example_test.go
  sdk/resourcemanager/servicefabricmanagedclusters/armservicefabricmanagedclusters/applicationtypeversions_client.go
  sdk/resourcemanager/servicefabricmanagedclusters/armservicefabricmanagedclusters/applicationtypeversions_client_example_test.go
  sdk/resourcemanager/servicefabricmanagedclusters/armservicefabricmanagedclusters/constants.go
  sdk/resourcemanager/servicefabricmanagedclusters/armservicefabricmanagedclusters/go.mod
  sdk/resourcemanager/servicefabricmanagedclusters/armservicefabricmanagedclusters/go.sum
  sdk/resourcemanager/servicefabricmanagedclusters/armservicefabricmanagedclusters/managedapplymaintenancewindow_client.go
  sdk/resourcemanager/servicefabricmanagedclusters/armservicefabricmanagedclusters/managedapplymaintenancewindow_client_example_test.go
  sdk/resourcemanager/servicefabricmanagedclusters/armservicefabricmanagedclusters/managedazresiliencystatus_client.go
  sdk/resourcemanager/servicefabricmanagedclusters/armservicefabricmanagedclusters/managedazresiliencystatus_client_example_test.go
  sdk/resourcemanager/servicefabricmanagedclusters/armservicefabricmanagedclusters/managedclusters_client.go
  sdk/resourcemanager/servicefabricmanagedclusters/armservicefabricmanagedclusters/managedclusters_client_example_test.go
  sdk/resourcemanager/servicefabricmanagedclusters/armservicefabricmanagedclusters/managedclusterversion_client.go
  sdk/resourcemanager/servicefabricmanagedclusters/armservicefabricmanagedclusters/managedclusterversion_client_example_test.go
  sdk/resourcemanager/servicefabricmanagedclusters/armservicefabricmanagedclusters/managedmaintenancewindowstatus_client.go
  sdk/resourcemanager/servicefabricmanagedclusters/armservicefabricmanagedclusters/managedmaintenancewindowstatus_client_example_test.go
  sdk/resourcemanager/servicefabricmanagedclusters/armservicefabricmanagedclusters/managedunsupportedvmsizes_client.go
  sdk/resourcemanager/servicefabricmanagedclusters/armservicefabricmanagedclusters/managedunsupportedvmsizes_client_example_test.go
  sdk/resourcemanager/servicefabricmanagedclusters/armservicefabricmanagedclusters/models.go
  sdk/resourcemanager/servicefabricmanagedclusters/armservicefabricmanagedclusters/models_serde.go
  sdk/resourcemanager/servicefabricmanagedclusters/armservicefabricmanagedclusters/nodetypes_client.go
  sdk/resourcemanager/servicefabricmanagedclusters/armservicefabricmanagedclusters/nodetypes_client_example_test.go
  sdk/resourcemanager/servicefabricmanagedclusters/armservicefabricmanagedclusters/nodetypeskus_client.go
  sdk/resourcemanager/servicefabricmanagedclusters/armservicefabricmanagedclusters/nodetypeskus_client_example_test.go
  sdk/resourcemanager/servicefabricmanagedclusters/armservicefabricmanagedclusters/operationresults_client.go
  sdk/resourcemanager/servicefabricmanagedclusters/armservicefabricmanagedclusters/operationresults_client_example_test.go
  sdk/resourcemanager/servicefabricmanagedclusters/armservicefabricmanagedclusters/operations_client.go
  sdk/resourcemanager/servicefabricmanagedclusters/armservicefabricmanagedclusters/operations_client_example_test.go
  sdk/resourcemanager/servicefabricmanagedclusters/armservicefabricmanagedclusters/operationstatus_client.go
  sdk/resourcemanager/servicefabricmanagedclusters/armservicefabricmanagedclusters/operationstatus_client_example_test.go
  sdk/resourcemanager/servicefabricmanagedclusters/armservicefabricmanagedclusters/services_client.go
  sdk/resourcemanager/servicefabricmanagedclusters/armservicefabricmanagedclusters/services_client_example_test.go
  sdk/resourcemanager/servicefabricmanagedclusters/armservicefabricmanagedclusters/testdata/_metadata.json
  sdk/resourcemanager/servicefabricmanagedclusters/armservicefabricmanagedclusters/tsp-location.yaml
  sdk/resourcemanager/servicefabricmanagedclusters/armservicefabricmanagedclusters/version.go
Labels: Mgmt

#25076 IPv6 Client Test
  sdk/azcore/core_test.go
Labels: Azure.Core

#24996 Update API version policy to handle path params
  sdk/azcore/CHANGELOG.md
  sdk/azcore/internal/shared/constants.go
  sdk/azcore/runtime/policy_api_version.go
  sdk/azcore/runtime/policy_api_version_test.go
Labels: Azure.Core

#25063 [Release] sdk/resourcemanager/containerservicefleet/armcontainerservicefleet/3.0.0-beta.1
  sdk/resourcemanager/containerservicefleet/armcontainerservicefleet/CHANGELOG.md
  sdk/resourcemanager/containerservicefleet/armcontainerservicefleet/README.md
  sdk/resourcemanager/containerservicefleet/armcontainerservicefleet/autoupgradeprofileoperations_client.go
  sdk/resourcemanager/containerservicefleet/armcontainerservicefleet/autoupgradeprofileoperations_client_example_test.go
  sdk/resourcemanager/containerservicefleet/armcontainerservicefleet/autoupgradeprofiles_client.go
  sdk/resourcemanager/containerservicefleet/armcontainerservicefleet/autoupgradeprofiles_client_example_test.go
  sdk/resourcemanager/containerservicefleet/armcontainerservicefleet/client_factory.go
  sdk/resourcemanager/containerservicefleet/armcontainerservicefleet/constants.go
  sdk/resourcemanager/containerservicefleet/armcontainerservicefleet/fake/autoupgradeprofileoperations_server.go
  sdk/resourcemanager/containerservicefleet/armcontainerservicefleet/fake/autoupgradeprofiles_server.go
  sdk/resourcemanager/containerservicefleet/armcontainerservicefleet/fake/fleetmembers_server.go
  sdk/resourcemanager/containerservicefleet/armcontainerservicefleet/fake/fleets_server.go
  sdk/resourcemanager/containerservicefleet/armcontainerservicefleet/fake/fleetupdatestrategies_server.go
  sdk/resourcemanager/containerservicefleet/armcontainerservicefleet/fake/gates_server.go
  sdk/resourcemanager/containerservicefleet/armcontainerservicefleet/fake/operations_server.go
  sdk/resourcemanager/containerservicefleet/armcontainerservicefleet/fake/server_factory.go
  sdk/resourcemanager/containerservicefleet/armcontainerservicefleet/fake/time_rfc3339.go
  sdk/resourcemanager/containerservicefleet/armcontainerservicefleet/fake/updateruns_server.go
  sdk/resourcemanager/containerservicefleet/armcontainerservicefleet/fleetmembers_client.go
  sdk/resourcemanager/containerservicefleet/armcontainerservicefleet/fleetmembers_client_example_test.go
  sdk/resourcemanager/containerservicefleet/armcontainerservicefleet/fleets_client.go
  sdk/resourcemanager/containerservicefleet/armcontainerservicefleet/fleets_client_example_test.go
  sdk/resourcemanager/containerservicefleet/armcontainerservicefleet/fleets_live_test.go
  sdk/resourcemanager/containerservicefleet/armcontainerservicefleet/fleetupdatestrategies_client.go
  sdk/resourcemanager/containerservicefleet/armcontainerservicefleet/fleetupdatestrategies_client_example_test.go
  sdk/resourcemanager/containerservicefleet/armcontainerservicefleet/gates_client.go
  sdk/resourcemanager/containerservicefleet/armcontainerservicefleet/gates_client_example_test.go
  sdk/resourcemanager/containerservicefleet/armcontainerservicefleet/go.mod
  sdk/resourcemanager/containerservicefleet/armcontainerservicefleet/go.sum
  sdk/resourcemanager/containerservicefleet/armcontainerservicefleet/models.go
  sdk/resourcemanager/containerservicefleet/armcontainerservicefleet/models_serde.go
  sdk/resourcemanager/containerservicefleet/armcontainerservicefleet/operations_client.go
  sdk/resourcemanager/containerservicefleet/armcontainerservicefleet/operations_client_example_test.go
  sdk/resourcemanager/containerservicefleet/armcontainerservicefleet/options.go
  sdk/resourcemanager/containerservicefleet/armcontainerservicefleet/responses.go
  sdk/resourcemanager/containerservicefleet/armcontainerservicefleet/testdata/_metadata.json
  sdk/resourcemanager/containerservicefleet/armcontainerservicefleet/tsp-location.yaml
  sdk/resourcemanager/containerservicefleet/armcontainerservicefleet/updateruns_client.go
  sdk/resourcemanager/containerservicefleet/armcontainerservicefleet/updateruns_client_example_test.go
  sdk/resourcemanager/containerservicefleet/armcontainerservicefleet/version.go
Labels: Mgmt

#24971 Increment version for storage/azqueue releases
  sdk/storage/azqueue/CHANGELOG.md
  sdk/storage/azqueue/internal/exported/version.go
Labels: Storage

#25097 Sync eng/common directory with azure-sdk-tools for PR 11726
  eng/common/scripts/Mark-ReleasePlanCompletion.ps1
Labels: EngSys, Central-EngSys

#25113 [AutoPR sdk-resourcemanager/impactreporting/armimpactreporting]-generated-from-SDK Generation - Go-5237817
  sdk/resourcemanager/impactreporting/armimpactreporting/CHANGELOG.md
  sdk/resourcemanager/impactreporting/armimpactreporting/connectors_client.go
  sdk/resourcemanager/impactreporting/armimpactreporting/constants.go
  sdk/resourcemanager/impactreporting/armimpactreporting/fake/connectors_server.go
  sdk/resourcemanager/impactreporting/armimpactreporting/fake/impactcategories_server.go
  sdk/resourcemanager/impactreporting/armimpactreporting/fake/insights_server.go
  sdk/resourcemanager/impactreporting/armimpactreporting/fake/time_rfc3339.go
  sdk/resourcemanager/impactreporting/armimpactreporting/fake/workloadimpacts_server.go
  sdk/resourcemanager/impactreporting/armimpactreporting/go.mod
  sdk/resourcemanager/impactreporting/armimpactreporting/go.sum
  sdk/resourcemanager/impactreporting/armimpactreporting/insights_client.go
  sdk/resourcemanager/impactreporting/armimpactreporting/models.go
  sdk/resourcemanager/impactreporting/armimpactreporting/testdata/_metadata.json
  sdk/resourcemanager/impactreporting/armimpactreporting/tsp-location.yaml
  sdk/resourcemanager/impactreporting/armimpactreporting/version.go
  sdk/resourcemanager/impactreporting/armimpactreporting/workloadimpacts_client.go
  sdk/resourcemanager/impactreporting/armimpactreporting/workloadimpacts_client_example_test.go
Labels: Mgmt

#25121 Sync eng/common directory with azure-sdk-tools for PR 11741
  eng/common/pipelines/templates/steps/mark-release-completion.yml
  eng/common/scripts/Helpers/DevOps-WorkItem-Helpers.ps1
Labels: EngSys, Central-EngSys

#25133 Prep azcore v1.19.0 for release
  sdk/azcore/CHANGELOG.md
Labels: Azure.Core

#25137 Sync eng/common directory with azure-sdk-tools for PR 11801
  eng/common/scripts/ChangeLog-Operations.ps1
Labels: EngSys, Central-EngSys

#25140 Sync eng/common directory with azure-sdk-tools for PR 11807
  eng/common/scripts/Mark-ReleasePlanCompletion.ps1
Labels: EngSys, Central-EngSys

#25127 Add Allow Tentative Writes Header
  sdk/data/azcosmos/CHANGELOG.md
  sdk/data/azcosmos/cosmos_client.go
  sdk/data/azcosmos/cosmos_global_endpoint_manager.go
  sdk/data/azcosmos/cosmos_global_endpoint_manager_policy.go
  sdk/data/azcosmos/cosmos_global_endpoint_manager_test.go
  sdk/data/azcosmos/cosmos_http_constants.go
Labels: Cosmos

#25138 Sync eng/common directory with azure-sdk-tools for PR 11802
  eng/common/instructions/azsdk-tools/typespec-to-sdk.instructions.md
  eng/common/instructions/azsdk-tools/validate-codeowners.instructions.md
  eng/common/instructions/azsdk-tools/validate-service-label.instruction.md
Labels: EngSys, Central-EngSys

#25152 Sync eng/common directory with azure-sdk-tools for PR 11839
  eng/common/instructions/azsdk-tools/check-package-readiness.instructions.md
  eng/common/instructions/azsdk-tools/create-release-plan.instructions.md
  eng/common/instructions/azsdk-tools/sdk-details-in-release-plan.instructions.md
  eng/common/instructions/azsdk-tools/typespec-to-sdk.instructions.md
  eng/common/instructions/azsdk-tools/verify-namespace-approval.instructions.md
Labels: EngSys, Central-EngSys

#25155 [Release] sdk/resourcemanager/workloadorchestration/armworkloadorchestration/0.2.0
  sdk/resourcemanager/workloadorchestration/armworkloadorchestration/CHANGELOG.md
  sdk/resourcemanager/workloadorchestration/armworkloadorchestration/configtemplates_client.go
  sdk/resourcemanager/workloadorchestration/armworkloadorchestration/configtemplates_client_example_test.go
  sdk/resourcemanager/workloadorchestration/armworkloadorchestration/contexts_client.go
  sdk/resourcemanager/workloadorchestration/armworkloadorchestration/contexts_client_example_test.go
  sdk/resourcemanager/workloadorchestration/armworkloadorchestration/diagnostics_client.go
  sdk/resourcemanager/workloadorchestration/armworkloadorchestration/diagnostics_client_example_test.go
  sdk/resourcemanager/workloadorchestration/armworkloadorchestration/dynamicschemaversions_client.go
  sdk/resourcemanager/workloadorchestration/armworkloadorchestration/fake/configtemplates_server.go
  sdk/resourcemanager/workloadorchestration/armworkloadorchestration/fake/contexts_server.go
  sdk/resourcemanager/workloadorchestration/armworkloadorchestration/fake/diagnostics_server.go
  sdk/resourcemanager/workloadorchestration/armworkloadorchestration/fake/dynamicschemaversions_server.go
  sdk/resourcemanager/workloadorchestration/armworkloadorchestration/fake/schemas_server.go
  sdk/resourcemanager/workloadorchestration/armworkloadorchestration/fake/solutions_server.go
  sdk/resourcemanager/workloadorchestration/armworkloadorchestration/fake/targets_server.go
  sdk/resourcemanager/workloadorchestration/armworkloadorchestration/go.mod
  sdk/resourcemanager/workloadorchestration/armworkloadorchestration/go.sum
  sdk/resourcemanager/workloadorchestration/armworkloadorchestration/models.go
  sdk/resourcemanager/workloadorchestration/armworkloadorchestration/models_serde.go
  sdk/resourcemanager/workloadorchestration/armworkloadorchestration/schemas_client.go
  sdk/resourcemanager/workloadorchestration/armworkloadorchestration/schemas_client_example_test.go
  sdk/resourcemanager/workloadorchestration/armworkloadorchestration/solutions_client.go
  sdk/resourcemanager/workloadorchestration/armworkloadorchestration/solutions_client_example_test.go
  sdk/resourcemanager/workloadorchestration/armworkloadorchestration/targets_client.go
  sdk/resourcemanager/workloadorchestration/armworkloadorchestration/targets_client_example_test.go
  sdk/resourcemanager/workloadorchestration/armworkloadorchestration/tsp-location.yaml
  sdk/resourcemanager/workloadorchestration/armworkloadorchestration/version.go
Labels: Mgmt

#25115 fix resource identifier parsing
  sdk/azcore/CHANGELOG.md
  sdk/azcore/arm/internal/resource/resource_identifier.go
  sdk/azcore/arm/internal/resource/resource_identifier_test.go
Labels: Azure.Core

#25166 Remove pod identity content from TSG
  sdk/azidentity/TROUBLESHOOTING.md
Labels: Azure.Identity

#25169 Sync eng/common directory with azure-sdk-tools for PR 11905
  eng/common/instructions/azsdk-tools/validate-codeowners.instructions.md
  eng/common/instructions/azsdk-tools/validate-service-label.instructions.md
Labels: EngSys, Central-EngSys

#25170 Sync eng/common directory with azure-sdk-tools for PR 11896
  eng/common/TestResources/New-TestResources.ps1
Labels: EngSys, Central-EngSys
