Repository Azure/azure-sdk-for-go, pull requests merged in 2025-02, with the labels that each got.

#24049 Sync eng/common directory with azure-sdk-tools for PR 9752
  eng/common/scripts/Helpers/DevOps-WorkItem-Helpers.ps1
  eng/common/scripts/Helpers/PSModule-Helpers.ps1
Labels: EngSys, Central-EngSys

#24050 Sync eng/common directory with azure-sdk-tools for PR 9698
  eng/common/pipelines/templates/jobs/prepare-pipelines.yml
  eng/common/pipelines/templates/steps/sparse-checkout.yml
  eng/common/pipelines/templates/steps/validate-all-packages.yml
Labels: EngSys, Central-EngSys

#24052 Sync eng/common directory with azure-sdk-tools for PR 9733
  eng/common/scripts/Detect-Api-Changes.ps1
Labels: EngSys, Central-EngSys

#24045 Sync eng/common directory with azure-sdk-tools for PR 9747
  eng/common/scripts/job-matrix/Create-PrJobMatrix.ps1
  eng/common/scripts/job-matrix/job-matrix-functions.ps1
Labels: EngSys, Central-EngSys

#24047 Conditionally allow and test connection strings (only in TME)
  sdk/messaging/azeventhubs/internal/test/test_helpers.go
  sdk/messaging/azeventhubs/test-resources.bicep
  sdk/messaging/azservicebus/admin/admin_client_test.go
  sdk/messaging/azservicebus/client_test.go
  sdk/messaging/azservicebus/internal/test/test_helpers.go
  sdk/messaging/azservicebus/receiver_test.go
  sdk/messaging/azservicebus/test-resources.bicep
Labels: Event Hubs

#24054 Sync eng/common directory with azure-sdk-tools for PR 9745
  eng/common/TestResources/New-TestResources.ps1
Labels: EngSys, Central-EngSys

#23996 [Release] sdk/resourcemanager/servicenetworking/armservicenetworking/1.1.0
  sdk/resourcemanager/servicenetworking/armservicenetworking/CHANGELOG.md
  sdk/resourcemanager/servicenetworking/armservicenetworking/associationsinterface_client.go
  sdk/resourcemanager/servicenetworking/armservicenetworking/associationsinterface_client_example_test.go
  sdk/resourcemanager/servicenetworking/armservicenetworking/autorest.md
  sdk/resourcemanager/servicenetworking/armservicenetworking/build.go
  sdk/resourcemanager/servicenetworking/armservicenetworking/client_factory.go
  sdk/resourcemanager/servicenetworking/armservicenetworking/constants.go
  sdk/resourcemanager/servicenetworking/armservicenetworking/fake/associationsinterface_server.go
  sdk/resourcemanager/servicenetworking/armservicenetworking/fake/frontendsinterface_server.go
  sdk/resourcemanager/servicenetworking/armservicenetworking/fake/internal.go
  sdk/resourcemanager/servicenetworking/armservicenetworking/fake/operations_server.go
  sdk/resourcemanager/servicenetworking/armservicenetworking/fake/securitypoliciesinterface_server.go
  sdk/resourcemanager/servicenetworking/armservicenetworking/fake/server_factory.go
  sdk/resourcemanager/servicenetworking/armservicenetworking/fake/time_rfc3339.go
  sdk/resourcemanager/servicenetworking/armservicenetworking/fake/trafficcontrollerinterface_server.go
  sdk/resourcemanager/servicenetworking/armservicenetworking/frontendsinterface_client.go
  sdk/resourcemanager/servicenetworking/armservicenetworking/frontendsinterface_client_example_test.go
  sdk/resourcemanager/servicenetworking/armservicenetworking/models.go
  sdk/resourcemanager/servicenetworking/armservicenetworking/models_serde.go
  sdk/resourcemanager/servicenetworking/armservicenetworking/operations_client.go
  sdk/resourcemanager/servicenetworking/armservicenetworking/operations_client_example_test.go
  sdk/resourcemanager/servicenetworking/armservicenetworking/options.go
  sdk/resourcemanager/servicenetworking/armservicenetworking/responses.go
  sdk/resourcemanager/servicenetworking/armservicenetworking/securitypoliciesinterface_client.go
  sdk/resourcemanager/servicenetworking/armservicenetworking/securitypoliciesinterface_client_example_test.go
  sdk/resourcemanager/servicenetworking/armservicenetworking/time_rfc3339.go
  sdk/resourcemanager/servicenetworking/armservicenetworking/trafficcontrollerinterface_client.go
  sdk/resourcemanager/servicenetworking/armservicenetworking/trafficcontrollerinterface_client_example_test.go
  sdk/resourcemanager/servicenetworking/armservicenetworking/tsp-location.yaml
Labels: Mgmt

#24058 Sync eng/common directory with azure-sdk-tools for PR 9781
  eng/common/TestResources/New-TestResources.ps1
Labels: EngSys, Central-EngSys

#23980 [Release] sdk/resourcemanager/pineconevectordb/armpineconevectordb/0.1.0
  sdk/resourcemanager/pineconevectordb/armpineconevectordb/CHANGELOG.md
  sdk/resourcemanager/pineconevectordb/armpineconevectordb/LICENSE.txt
  sdk/resourcemanager/pineconevectordb/armpineconevectordb/README.md
  sdk/resourcemanager/pineconevectordb/armpineconevectordb/ci.yml
  sdk/resourcemanager/pineconevectordb/armpineconevectordb/client_factory.go
  sdk/resourcemanager/pineconevectordb/armpineconevectordb/constants.go
  sdk/resourcemanager/pineconevectordb/armpineconevectordb/fake/internal.go
  sdk/resourcemanager/pineconevectordb/armpineconevectordb/fake/operations_server.go
  sdk/resourcemanager/pineconevectordb/armpineconevectordb/fake/organizations_server.go
  sdk/resourcemanager/pineconevectordb/armpineconevectordb/fake/server_factory.go
  sdk/resourcemanager/pineconevectordb/armpineconevectordb/fake/time_rfc3339.go
  sdk/resourcemanager/pineconevectordb/armpineconevectordb/go.mod
  sdk/resourcemanager/pineconevectordb/armpineconevectordb/go.sum
  sdk/resourcemanager/pineconevectordb/armpineconevectordb/models.go
  sdk/resourcemanager/pineconevectordb/armpineconevectordb/models_serde.go
  sdk/resourcemanager/pineconevectordb/armpineconevectordb/operations_client.go
  sdk/resourcemanager/pineconevectordb/armpineconevectordb/operations_client_example_test.go
  sdk/resourcemanager/pineconevectordb/armpineconevectordb/options.go
  sdk/resourcemanager/pineconevectordb/armpineconevectordb/organizations_client.go
  sdk/resourcemanager/pineconevectordb/armpineconevectordb/organizations_client_example_test.go
  sdk/resourcemanager/pineconevectordb/armpineconevectordb/responses.go
  sdk/resourcemanager/pineconevectordb/armpineconevectordb/time_rfc3339.go
  sdk/resourcemanager/pineconevectordb/armpineconevectordb/tsp-location.yaml
Labels: Mgmt

#24064 Sync eng/common directory with azure-sdk-tools for PR 9764
  eng/common/pipelines/templates/jobs/prepare-pipelines.yml
Labels: EngSys, Central-EngSys

#24040 fix: make it os compatible.
  eng/tools/generator/cmd/issue/link/common.go
  eng/tools/generator/cmd/v2/common/changelogProcessor.go
  eng/tools/generator/cmd/v2/common/fileProcessor.go
  eng/tools/generator/cmd/v2/refresh/refreshCmd.go
  eng/tools/generator/cmd/v2/release/releaseCmd.go
  eng/tools/internal/coverage/coverage.go
  eng/tools/mgmtreport/main.go
  eng/tools/profileBuilder/model/latest.go
  eng/tools/profileBuilder/model/transforms.go
  eng/tools/smoketests/cmd/root.go
  sdk/internal/recording/server.go
Labels: Storage, customer-reported, Community Contribution, Internal

#24067 Sync eng/common directory with azure-sdk-tools for PR 9788
  eng/common/scripts/Package-Properties.ps1
Labels: EngSys, Central-EngSys

#24068 Sync eng/common directory with azure-sdk-tools for PR 9793
  eng/common/pipelines/templates/steps/install-pipeline-generation.yml
Labels: EngSys, Central-EngSys

#24071 Removing impression tracking pixels from READMEs ***NO_CI***
  sdk/azidentity/MIGRATION.md
  sdk/azidentity/README.md
  sdk/azidentity/cache/README.md
  sdk/data/azappconfig/README.md
  sdk/data/azcosmos/README.md
  sdk/data/aztables/README.md
  sdk/messaging/azeventhubs/README.md
  sdk/messaging/azservicebus/README.md
  sdk/security/keyvault/azcertificates/README.md
  sdk/security/keyvault/azkeys/README.md
  sdk/security/keyvault/azsecrets/README.md
  sdk/storage/azblob/README.md
Labels: Storage, KeyVault, Cosmos, Service Bus, Event Hubs, Tables, Azure.Identity, App Configuration

#24072 Sync eng/common directory with azure-sdk-tools for PR 9799
  eng/common/scripts/Helpers/Package-Helpers.ps1
Labels: EngSys, Central-EngSys

#24060 [azservicebus] Prepping for v1.8.0, releasing CustomEndpoint feature
  sdk/messaging/azservicebus/CHANGELOG.md
  sdk/messaging/azservicebus/client.go
  sdk/messaging/azservicebus/client_test.go
  sdk/messaging/azservicebus/example_client_test.go
  sdk/messaging/azservicebus/internal/constants.go
Labels: Service Bus

#24062 [azeventhubs] Promoting CustomEndpoint to a GA feature.
  sdk/messaging/azeventhubs/CHANGELOG.md
  sdk/messaging/azeventhubs/consumer_client_test.go
  sdk/messaging/azeventhubs/producer_client_test.go
Labels: Event Hubs

#24057 [Storage] [AzFile] NFS over REST STG 97
  sdk/storage/azfile/CHANGELOG.md
  sdk/storage/azfile/assets.json
  sdk/storage/azfile/directory/client_test.go
  sdk/storage/azfile/directory/examples_test.go
  sdk/storage/azfile/directory/models.go
  sdk/storage/azfile/file/client.go
  sdk/storage/azfile/file/client_test.go
  sdk/storage/azfile/file/constants.go
  sdk/storage/azfile/file/examples_test.go
  sdk/storage/azfile/file/models.go
  sdk/storage/azfile/file/responses.go
  sdk/storage/azfile/internal/exported/file_permissions.go
  sdk/storage/azfile/internal/exported/smb_property.go
  sdk/storage/azfile/service/client_test.go
Labels: Storage

#24085 Case change for NFSFileType
  sdk/storage/azfile/assets.json
  sdk/storage/azfile/directory/client_test.go
  sdk/storage/azfile/file/client_test.go
  sdk/storage/azfile/file/constants.go
  sdk/storage/azfile/internal/exported/version.go
  sdk/storage/azfile/internal/generated/autorest.md
  sdk/storage/azfile/internal/generated/zz_constants.go
  sdk/storage/azfile/internal/generated/zz_directory_client.go
  sdk/storage/azfile/internal/generated/zz_file_client.go
  sdk/storage/azfile/internal/generated/zz_options.go
  sdk/storage/azfile/internal/generated/zz_response_types.go
Labels: Storage

#24091 Sync eng/common directory with azure-sdk-tools for PR 9803
  eng/common/scripts/Helpers/Package-Helpers.ps1
Labels: EngSys, Central-EngSys

#24069 [azcore/tracing] Add propagator and link wrapper
  sdk/azcore/CHANGELOG.md
  sdk/azcore/internal/shared/constants.go
  sdk/azcore/tracing/tracing.go
  sdk/azcore/tracing/tracing_test.go
Labels: customer-reported, Azure.Core, Community Contribution

#24087 Convert to dfs error while getproperties call
  sdk/storage/azdatalake/directory/client_test.go
  sdk/storage/azdatalake/file/client.go
  sdk/storage/azdatalake/file/client_test.go
Labels: Storage

#24090 Changelog updates for Cosmos release 1.3.0
  sdk/data/azcosmos/CHANGELOG.md
  sdk/data/azcosmos/version.go
Labels: Cosmos

#24094 Sync eng/common directory with azure-sdk-tools for PR 9810
  eng/common/pipelines/templates/steps/set-test-pipeline-version.yml
  eng/common/scripts/SetTestPipelineVersion.ps1
Labels: EngSys, Central-EngSys

#24095 Sync eng/common directory with azure-sdk-tools for PR 9778
  eng/common/scripts/Detect-Api-Changes.ps1
Labels: EngSys, Central-EngSys

#24100 [Storage] Prep for release stg97 - Blob and Files
  sdk/storage/azblob/CHANGELOG.md
  sdk/storage/azfile/CHANGELOG.md
Labels: Storage

#24103 [Storage] Prep for azdatalake preview
  sdk/storage/azdatalake/CHANGELOG.md
  sdk/storage/azdatalake/file/client_test.go
  sdk/storage/azdatalake/go.mod
  sdk/storage/azdatalake/go.sum
Labels: Storage

#24102 Increment version for storage/azblob releases
  sdk/storage/azblob/CHANGELOG.md
  sdk/storage/azblob/internal/exported/version.go
Labels: Storage

#24101 Increment version for storage/azfile releases
  sdk/storage/azfile/CHANGELOG.md
  sdk/storage/azfile/internal/exported/version.go
Labels: Storage

#24105 Increment version for storage/azdatalake releases
  sdk/storage/azdatalake/CHANGELOG.md
  sdk/storage/azdatalake/internal/exported/version.go
Labels: Storage

#24081 [tracing/azotel] Enable span link and propagation support
  sdk/tracing/azotel/CHANGELOG.md
  sdk/tracing/azotel/go.mod
  sdk/tracing/azotel/go.sum
  sdk/tracing/azotel/otel.go
  sdk/tracing/azotel/otel_test.go
Labels: customer-reported, Azure.Core, Community Contribution

#24108 Prepare azidentity v1.8.2 for release
  sdk/azidentity/CHANGELOG.md
  sdk/azidentity/cache/go.mod
  sdk/azidentity/cache/go.sum
  sdk/azidentity/go.mod
  sdk/azidentity/go.sum
  sdk/azidentity/testdata/managed-id-test/go.mod
  sdk/azidentity/testdata/managed-id-test/go.sum
Labels: Azure.Identity

#24110 Increment version for azidentity releases
  sdk/azidentity/CHANGELOG.md
  sdk/azidentity/version.go
Labels: Azure.Identity

#24079 Merge tools CI pipeline with main CI pipeline
  eng/pipelines/templates/jobs/archetype-sdk-client.yml
  eng/pipelines/templates/jobs/archetype-sdk-eng-client.yml
  eng/tools/apidiff/ci.yml
  eng/tools/deprecate/ci.yml
  eng/tools/doccheck/main.go
  eng/tools/generator/ci.yml
  eng/tools/generator/cmd/issue/link/common.go
  eng/tools/generator/cmd/v2/common/version.go
  eng/tools/generator/config/validate/remoteValidator.go
  eng/tools/generator/typespec/tspconfig_test.go
  eng/tools/generator/typespec/typespec-go.go
  eng/tools/generator/typespec/typespec-go_test.go
  eng/tools/indexer/ci.yml
  eng/tools/internal/ci.yml
  eng/tools/internal/coverage/coverage.go
  eng/tools/internal/coverage/coverage_test.go
  eng/tools/profileBuilder/ci.yml
  eng/tools/smoketests/cmd/models.go
  eng/tools/smoketests/cmd/root.go
  eng/tools/smoketests/main.go
  sdk/data/azcosmos/ci.yml
Labels: Central-EngSys

#24113 Sync eng/common directory with azure-sdk-tools for PR 9807
  eng/common/scripts/Package-Properties.ps1
  eng/common/scripts/job-matrix/Create-PrJobMatrix.ps1
Labels: EngSys, Central-EngSys

#24112 Sync eng/common directory with azure-sdk-tools for PR 9821
  eng/common/pipelines/templates/steps/save-package-properties.yml
Labels: EngSys, Central-EngSys

#24119 Improve docs for EDMEntity properties
  sdk/data/aztables/entity.go
Labels: Tables

#24114 Sync eng/common directory with azure-sdk-tools for PR 9823
  eng/common/scripts/Generate-PR-Diff.ps1
Labels: EngSys, Central-EngSys

#24120 [keyvault] make challenge policy thread safe
  sdk/security/keyvault/internal/CHANGELOG.md
  sdk/security/keyvault/internal/challenge_policy.go
  sdk/security/keyvault/internal/challenge_policy_test.go
  sdk/security/keyvault/internal/ci.keyvault.yml
  sdk/security/keyvault/internal/go.mod
  sdk/security/keyvault/internal/go.sum
Labels: KeyVault, Client

#24121 Increment version for security/keyvault/internal releases
  sdk/security/keyvault/internal/CHANGELOG.md
  sdk/security/keyvault/internal/constants.go
Labels: KeyVault

#24122 [keyvault] prep for release
  sdk/security/keyvault/azadmin/CHANGELOG.md
  sdk/security/keyvault/azadmin/go.mod
  sdk/security/keyvault/azadmin/go.sum
  sdk/security/keyvault/azcertificates/CHANGELOG.md
  sdk/security/keyvault/azcertificates/go.mod
  sdk/security/keyvault/azcertificates/go.sum
  sdk/security/keyvault/azcertificates/testdata/perf/go.mod
  sdk/security/keyvault/azcertificates/testdata/perf/go.sum
  sdk/security/keyvault/azkeys/CHANGELOG.md
  sdk/security/keyvault/azkeys/go.mod
  sdk/security/keyvault/azkeys/go.sum
  sdk/security/keyvault/azkeys/testdata/perf/go.mod
  sdk/security/keyvault/azkeys/testdata/perf/go.sum
  sdk/security/keyvault/azsecrets/CHANGELOG.md
  sdk/security/keyvault/azsecrets/go.mod
  sdk/security/keyvault/azsecrets/go.sum
  sdk/security/keyvault/azsecrets/testdata/perf/go.mod
  sdk/security/keyvault/azsecrets/testdata/perf/go.sum
Labels: KeyVault, Client

#24123 Sync eng/common directory with azure-sdk-tools for PR 9832
  eng/common/pipelines/templates/steps/save-package-properties.yml
Labels: EngSys, Central-EngSys

#24116 Deprecated sdk/resourcemanager/logz/armlogz
  sdk/resourcemanager/logz/armlogz/CHANGELOG.md
  sdk/resourcemanager/logz/armlogz/README.md
  sdk/resourcemanager/logz/armlogz/autorest.md
  sdk/resourcemanager/logz/armlogz/constants.go
  sdk/resourcemanager/logz/armlogz/go.mod
Labels: Mgmt

#24124 Sync eng/common directory with azure-sdk-tools for PR 9834
  eng/common/TestResources/New-TestResources.ps1
  eng/common/TestResources/Remove-TestResources.ps1
  eng/common/TestResources/Update-TestResources.ps1
Labels: EngSys, Central-EngSys

#24129 Sync eng/common directory with azure-sdk-tools for PR 9836
  eng/common/scripts/job-matrix/Create-PrJobMatrix.ps1
Labels: EngSys, Central-EngSys

#24048 Log user-assigned managed identity IDs
  sdk/azidentity/CHANGELOG.md
  sdk/azidentity/managed_identity_client.go
  sdk/azidentity/managed_identity_credential_test.go
Labels: Azure.Identity

#24126 Increment version for security/keyvault/azcertificates releases
  sdk/security/keyvault/azcertificates/CHANGELOG.md
  sdk/security/keyvault/azcertificates/version.go
Labels: KeyVault

#24127 Increment version for security/keyvault/azkeys releases
  sdk/security/keyvault/azkeys/CHANGELOG.md
  sdk/security/keyvault/azkeys/version.go
Labels: KeyVault

#24128 Increment version for security/keyvault/azsecrets releases
  sdk/security/keyvault/azsecrets/CHANGELOG.md
  sdk/security/keyvault/azsecrets/version.go
Labels: KeyVault

#24082 [keyvault] add fakes support to internal
  sdk/security/keyvault/internal/CHANGELOG.md
  sdk/security/keyvault/internal/challenge_policy.go
  sdk/security/keyvault/internal/challenge_policy_test.go
  sdk/security/keyvault/internal/constants.go
  sdk/security/keyvault/internal/doc.go
  sdk/security/keyvault/internal/fake_challenge.go
  sdk/security/keyvault/internal/fake_challenge_test.go
  sdk/security/keyvault/internal/parse.go
  sdk/security/keyvault/internal/parse_test.go
Labels: KeyVault, Client

#24138 [azcore/runtime] add error.type attribute and span links to runtime.StartSpan
  sdk/azcore/CHANGELOG.md
  sdk/azcore/runtime/policy_http_trace.go
  sdk/azcore/runtime/policy_http_trace_test.go
Labels: Azure.Core

#24143 Revert go-keychain upgrade
  sdk/azidentity/cache/go.mod
  sdk/azidentity/cache/go.sum
  sdk/azidentity/go.mod
  sdk/azidentity/go.sum
  sdk/azidentity/go.work
Labels: Azure.Identity

#24147 Increment version for messaging/eventgrid/azsystemevents releases
  sdk/messaging/eventgrid/azsystemevents/CHANGELOG.md
  sdk/messaging/eventgrid/azsystemevents/internal/version.go
Labels: Event Grid

#24144 Deprecate UsernamePasswordCredential
  sdk/azidentity/CHANGELOG.md
  sdk/azidentity/README.md
  sdk/azidentity/environment_credential.go
  sdk/azidentity/username_password_credential.go
Labels: Azure.Identity

#24145 Sync eng/common directory with azure-sdk-tools for PR 9862
  eng/common/scripts/Helpers/Package-Helpers.ps1
  eng/common/scripts/Package-Properties.ps1
Labels: EngSys, Central-EngSys

#24150 Sync eng/common directory with azure-sdk-tools for PR 9896
  eng/common/scripts/Package-Properties.ps1
Labels: EngSys, Central-EngSys

#24149 Sync eng/common directory with azure-sdk-tools for PR 9889
  eng/common/scripts/Verify-Links.ps1
Labels: EngSys, Central-EngSys

#24142 [internal/test] Add Internal Span Validator for Unit Tests
  sdk/internal/CHANGELOG.md
  sdk/internal/go.mod
  sdk/internal/go.sum
  sdk/internal/test/tracingvalidator/validator.go
  sdk/internal/test/tracingvalidator/validator_test.go
  sdk/internal/version.go
Labels: Internal

#24152 Sync eng/common directory with azure-sdk-tools for PR 9895
  eng/common/pipelines/templates/steps/detect-api-changes.yml
  eng/common/scripts/Detect-Api-Changes.ps1
Labels: EngSys, Central-EngSys

#24097 [Release] sdk/resourcemanager/netapp/armnetapp/7.4.0
  sdk/resourcemanager/netapp/armnetapp/CHANGELOG.md
  sdk/resourcemanager/netapp/armnetapp/accounts_client.go
  sdk/resourcemanager/netapp/armnetapp/accounts_client_example_test.go
  sdk/resourcemanager/netapp/armnetapp/autorest.md
  sdk/resourcemanager/netapp/armnetapp/backuppolicies_client.go
  sdk/resourcemanager/netapp/armnetapp/backuppolicies_client_example_test.go
  sdk/resourcemanager/netapp/armnetapp/backups_client.go
  sdk/resourcemanager/netapp/armnetapp/backups_client_example_test.go
  sdk/resourcemanager/netapp/armnetapp/backupsunderaccount_client.go
  sdk/resourcemanager/netapp/armnetapp/backupsunderaccount_client_example_test.go
  sdk/resourcemanager/netapp/armnetapp/backupsunderbackupvault_client.go
  sdk/resourcemanager/netapp/armnetapp/backupsunderbackupvault_client_example_test.go
  sdk/resourcemanager/netapp/armnetapp/backupsundervolume_client.go
  sdk/resourcemanager/netapp/armnetapp/backupsundervolume_client_example_test.go
  sdk/resourcemanager/netapp/armnetapp/backupvaults_client.go
  sdk/resourcemanager/netapp/armnetapp/backupvaults_client_example_test.go
  sdk/resourcemanager/netapp/armnetapp/constants.go
  sdk/resourcemanager/netapp/armnetapp/fake/accounts_server.go
  sdk/resourcemanager/netapp/armnetapp/fake/volumes_server.go
  sdk/resourcemanager/netapp/armnetapp/models.go
  sdk/resourcemanager/netapp/armnetapp/models_serde.go
  sdk/resourcemanager/netapp/armnetapp/operations_client.go
  sdk/resourcemanager/netapp/armnetapp/operations_client_example_test.go
  sdk/resourcemanager/netapp/armnetapp/options.go
  sdk/resourcemanager/netapp/armnetapp/pools_client.go
  sdk/resourcemanager/netapp/armnetapp/pools_client_example_test.go
  sdk/resourcemanager/netapp/armnetapp/resource_client.go
  sdk/resourcemanager/netapp/armnetapp/resource_client_example_test.go
  sdk/resourcemanager/netapp/armnetapp/resourcequotalimits_client.go
  sdk/resourcemanager/netapp/armnetapp/resourcequotalimits_client_example_test.go
  sdk/resourcemanager/netapp/armnetapp/resourceregioninfos_client.go
  sdk/resourcemanager/netapp/armnetapp/resourceregioninfos_client_example_test.go
  sdk/resourcemanager/netapp/armnetapp/responses.go
  sdk/resourcemanager/netapp/armnetapp/snapshotpolicies_client.go
  sdk/resourcemanager/netapp/armnetapp/snapshotpolicies_client_example_test.go
  sdk/resourcemanager/netapp/armnetapp/snapshots_client.go
  sdk/resourcemanager/netapp/armnetapp/snapshots_client_example_test.go
  sdk/resourcemanager/netapp/armnetapp/subvolumes_client.go
  sdk/resourcemanager/netapp/armnetapp/subvolumes_client_example_test.go
  sdk/resourcemanager/netapp/armnetapp/volumegroups_client.go
  sdk/resourcemanager/netapp/armnetapp/volumegroups_client_example_test.go
  sdk/resourcemanager/netapp/armnetapp/volumequotarules_client.go
  sdk/resourcemanager/netapp/armnetapp/volumequotarules_client_example_test.go
  sdk/resourcemanager/netapp/armnetapp/volumes_client.go
  sdk/resourcemanager/netapp/armnetapp/volumes_client_example_test.go
Labels: Mgmt

#24084 [Release] sdk/resourcemanager/networkcloud/armnetworkcloud/1.2.0
  sdk/resourcemanager/networkcloud/armnetworkcloud/CHANGELOG.md
  sdk/resourcemanager/networkcloud/armnetworkcloud/agentpools_client.go
  sdk/resourcemanager/networkcloud/armnetworkcloud/agentpools_client_example_test.go
  sdk/resourcemanager/networkcloud/armnetworkcloud/autorest.md
  sdk/resourcemanager/networkcloud/armnetworkcloud/baremetalmachinekeysets_client.go
  sdk/resourcemanager/networkcloud/armnetworkcloud/baremetalmachinekeysets_client_example_test.go
  sdk/resourcemanager/networkcloud/armnetworkcloud/baremetalmachines_client.go
  sdk/resourcemanager/networkcloud/armnetworkcloud/baremetalmachines_client_example_test.go
  sdk/resourcemanager/networkcloud/armnetworkcloud/bmckeysets_client.go
  sdk/resourcemanager/networkcloud/armnetworkcloud/bmckeysets_client_example_test.go
  sdk/resourcemanager/networkcloud/armnetworkcloud/cloudservicesnetworks_client.go
  sdk/resourcemanager/networkcloud/armnetworkcloud/cloudservicesnetworks_client_example_test.go
  sdk/resourcemanager/networkcloud/armnetworkcloud/clustermanagers_client.go
  sdk/resourcemanager/networkcloud/armnetworkcloud/clustermanagers_client_example_test.go
  sdk/resourcemanager/networkcloud/armnetworkcloud/clusters_client.go
  sdk/resourcemanager/networkcloud/armnetworkcloud/clusters_client_example_test.go
  sdk/resourcemanager/networkcloud/armnetworkcloud/consoles_client.go
  sdk/resourcemanager/networkcloud/armnetworkcloud/consoles_client_example_test.go
  sdk/resourcemanager/networkcloud/armnetworkcloud/constants.go
  sdk/resourcemanager/networkcloud/armnetworkcloud/kubernetesclusterfeatures_client.go
  sdk/resourcemanager/networkcloud/armnetworkcloud/kubernetesclusterfeatures_client_example_test.go
  sdk/resourcemanager/networkcloud/armnetworkcloud/kubernetesclusters_client.go
  sdk/resourcemanager/networkcloud/armnetworkcloud/kubernetesclusters_client_example_test.go
  sdk/resourcemanager/networkcloud/armnetworkcloud/l2networks_client.go
  sdk/resourcemanager/networkcloud/armnetworkcloud/l2networks_client_example_test.go
  sdk/resourcemanager/networkcloud/armnetworkcloud/l3networks_client.go
  sdk/resourcemanager/networkcloud/armnetworkcloud/l3networks_client_example_test.go
  sdk/resourcemanager/networkcloud/armnetworkcloud/metricsconfigurations_client.go
  sdk/resourcemanager/networkcloud/armnetworkcloud/metricsconfigurations_client_example_test.go
  sdk/resourcemanager/networkcloud/armnetworkcloud/operations_client.go
  sdk/resourcemanager/networkcloud/armnetworkcloud/operations_client_example_test.go
  sdk/resourcemanager/networkcloud/armnetworkcloud/racks_client.go
  sdk/resourcemanager/networkcloud/armnetworkcloud/racks_client_example_test.go
  sdk/resourcemanager/networkcloud/armnetworkcloud/rackskus_client.go
  sdk/resourcemanager/networkcloud/armnetworkcloud/rackskus_client_example_test.go
  sdk/resourcemanager/networkcloud/armnetworkcloud/storageappliances_client.go
  sdk/resourcemanager/networkcloud/armnetworkcloud/storageappliances_client_example_test.go
  sdk/resourcemanager/networkcloud/armnetworkcloud/trunkednetworks_client.go
  sdk/resourcemanager/networkcloud/armnetworkcloud/trunkednetworks_client_example_test.go
  sdk/resourcemanager/networkcloud/armnetworkcloud/virtualmachines_client.go
  sdk/resourcemanager/networkcloud/armnetworkcloud/virtualmachines_client_example_test.go
  sdk/resourcemanager/networkcloud/armnetworkcloud/volumes_client.go
  sdk/resourcemanager/networkcloud/armnetworkcloud/volumes_client_example_test.go
Labels: Mgmt

#24151 Trigger live ACI test via HTTP
  sdk/azidentity/managed_identity_credential_test.go
  sdk/azidentity/test-resources-post.ps1
Labels: Azure.Identity

#24153 Sync eng/common directory with azure-sdk-tools for PR 9901
  eng/common/testproxy/target_version.txt
Labels: EngSys, Central-EngSys

#24157 Sync eng/common directory with azure-sdk-tools for PR 9902
  eng/common/scripts/Package-Properties.ps1
Labels: EngSys, Central-EngSys

#24148 avoid clientFactory CTOR break change
  eng/scripts/build.ps1
  sdk/resourcemanager/advisor/armadvisor/build.go
  sdk/resourcemanager/agrifood/armagrifood/build.go
  sdk/resourcemanager/alertsmanagement/armalertsmanagement/build.go
  sdk/resourcemanager/appplatform/armappplatform/build.go
  sdk/resourcemanager/appservice/armappservice/build.go
  sdk/resourcemanager/authorization/armauthorization/build.go
  sdk/resourcemanager/automanage/armautomanage/build.go
  sdk/resourcemanager/azurestackhci/armazurestackhci/build.go
  sdk/resourcemanager/billing/armbilling/build.go
  sdk/resourcemanager/cdn/armcdn/build.go
  sdk/resourcemanager/changeanalysis/armchangeanalysis/build.go
  sdk/resourcemanager/confluent/armconfluent/build.go
  sdk/resourcemanager/connectedvmware/armconnectedvmware/build.go
  sdk/resourcemanager/consumption/armconsumption/build.go
  sdk/resourcemanager/customproviders/armcustomproviders/build.go
  sdk/resourcemanager/datacatalog/armdatacatalog/build.go
  sdk/resourcemanager/dataprotection/armdataprotection/build.go
  sdk/resourcemanager/datashare/armdatashare/build.go
  sdk/resourcemanager/devops/armdevops/build.go
  sdk/resourcemanager/devtestlabs/armdevtestlabs/build.go
  sdk/resourcemanager/domainservices/armdomainservices/build.go
  sdk/resourcemanager/eventgrid/armeventgrid/build.go
  sdk/resourcemanager/frontdoor/armfrontdoor/build.go
  sdk/resourcemanager/hybridcontainerservice/armhybridcontainerservice/build.go
  sdk/resourcemanager/managednetwork/armmanagednetwork/build.go
  sdk/resourcemanager/mobilenetwork/armmobilenetwork/build.go
  sdk/resourcemanager/msi/armmsi/build.go
  sdk/resourcemanager/mysql/armmysqlflexibleservers/build.go
  sdk/resourcemanager/network/armnetwork/build.go
  sdk/resourcemanager/networkfunction/armnetworkfunction/build.go
  sdk/resourcemanager/paloaltonetworksngfw/armpanngfw/build.go
  sdk/resourcemanager/policyinsights/armpolicyinsights/build.go
  sdk/resourcemanager/portal/armportal/build.go
  sdk/resourcemanager/postgresql/armpostgresqlflexibleservers/build.go
  sdk/resourcemanager/powerbiembedded/armpowerbiembedded/build.go
  sdk/resourcemanager/purview/armpurview/build.go
  sdk/resourcemanager/resourcehealth/armresourcehealth/build.go
  sdk/resourcemanager/resourcemover/armresourcemover/build.go
  sdk/resourcemanager/resources/armfeatures/build.go
  sdk/resourcemanager/resources/armlocks/build.go
  sdk/resourcemanager/resources/armmanagedapplications/build.go
  sdk/resourcemanager/resources/armpolicy/build.go
  sdk/resourcemanager/saas/armsaas/build.go
  sdk/resourcemanager/scvmm/armscvmm/build.go
  sdk/resourcemanager/security/armsecurity/build.go
  sdk/resourcemanager/solutions/armmanagedapplications/build.go
  sdk/resourcemanager/storageimportexport/armstorageimportexport/build.go
  sdk/resourcemanager/storsimple1200series/armstorsimple1200series/build.go
  sdk/resourcemanager/support/armsupport/build.go
  sdk/resourcemanager/synapse/armsynapse/build.go
Labels: Mgmt

#24061 [Release] sdk/resourcemanager/containerservice/armcontainerservice/6.4.0
  sdk/resourcemanager/containerservice/armcontainerservice/CHANGELOG.md
  sdk/resourcemanager/containerservice/armcontainerservice/agentpools_client.go
  sdk/resourcemanager/containerservice/armcontainerservice/agentpools_client_example_test.go
  sdk/resourcemanager/containerservice/armcontainerservice/assets.json
  sdk/resourcemanager/containerservice/armcontainerservice/autorest.md
  sdk/resourcemanager/containerservice/armcontainerservice/client_factory.go
  sdk/resourcemanager/containerservice/armcontainerservice/constants.go
  sdk/resourcemanager/containerservice/armcontainerservice/fake/loadbalancers_server.go
  sdk/resourcemanager/containerservice/armcontainerservice/fake/managedclusters_server.go
  sdk/resourcemanager/containerservice/armcontainerservice/fake/managedclustersnapshots_server.go
  sdk/resourcemanager/containerservice/armcontainerservice/fake/operationstatusresult_server.go
  sdk/resourcemanager/containerservice/armcontainerservice/fake/server_factory.go
  sdk/resourcemanager/containerservice/armcontainerservice/loadbalancers_client.go
  sdk/resourcemanager/containerservice/armcontainerservice/loadbalancers_client_example_test.go
  sdk/resourcemanager/containerservice/armcontainerservice/machines_client.go
  sdk/resourcemanager/containerservice/armcontainerservice/machines_client_example_test.go
  sdk/resourcemanager/containerservice/armcontainerservice/maintenanceconfigurations_client.go
  sdk/resourcemanager/containerservice/armcontainerservice/maintenanceconfigurations_client_example_test.go
  sdk/resourcemanager/containerservice/armcontainerservice/managedclusters_client.go
  sdk/resourcemanager/containerservice/armcontainerservice/managedclusters_client_example_test.go
  sdk/resourcemanager/containerservice/armcontainerservice/managedclustersnapshots_client.go
  sdk/resourcemanager/containerservice/armcontainerservice/managedclustersnapshots_client_example_test.go
  sdk/resourcemanager/containerservice/armcontainerservice/models.go
  sdk/resourcemanager/containerservice/armcontainerservice/models_serde.go
  sdk/resourcemanager/containerservice/armcontainerservice/operations_client.go
  sdk/resourcemanager/containerservice/armcontainerservice/operations_client_example_test.go
  sdk/resourcemanager/containerservice/armcontainerservice/operationstatusresult_client.go
  sdk/resourcemanager/containerservice/armcontainerservice/operationstatusresult_client_example_test.go
  sdk/resourcemanager/containerservice/armcontainerservice/options.go
  sdk/resourcemanager/containerservice/armcontainerservice/privateendpointconnections_client.go
  sdk/resourcemanager/containerservice/armcontainerservice/privateendpointconnections_client_example_test.go
  sdk/resourcemanager/containerservice/armcontainerservice/privatelinkresources_client.go
  sdk/resourcemanager/containerservice/armcontainerservice/privatelinkresources_client_example_test.go
  sdk/resourcemanager/containerservice/armcontainerservice/resolveprivatelinkserviceid_client.go
  sdk/resourcemanager/containerservice/armcontainerservice/resolveprivatelinkserviceid_client_example_test.go
  sdk/resourcemanager/containerservice/armcontainerservice/responses.go
  sdk/resourcemanager/containerservice/armcontainerservice/snapshots_client.go
  sdk/resourcemanager/containerservice/armcontainerservice/snapshots_client_example_test.go
  sdk/resourcemanager/containerservice/armcontainerservice/trustedaccessrolebindings_client.go
  sdk/resourcemanager/containerservice/armcontainerservice/trustedaccessrolebindings_client_example_test.go
  sdk/resourcemanager/containerservice/armcontainerservice/trustedaccessroles_client.go
  sdk/resourcemanager/containerservice/armcontainerservice/trustedaccessroles_client_example_test.go
Labels: Stable

#24161 [Release] sdk/resourcemanager/impactreporting/armimpactreporting/0.1.0
  sdk/resourcemanager/impactreporting/armimpactreporting/CHANGELOG.md
  sdk/resourcemanager/impactreporting/armimpactreporting/LICENSE.txt
  sdk/resourcemanager/impactreporting/armimpactreporting/README.md
  sdk/resourcemanager/impactreporting/armimpactreporting/ci.yml
  sdk/resourcemanager/impactreporting/armimpactreporting/client_factory.go
  sdk/resourcemanager/impactreporting/armimpactreporting/connectors_client.go
  sdk/resourcemanager/impactreporting/armimpactreporting/connectors_client_example_test.go
  sdk/resourcemanager/impactreporting/armimpactreporting/constants.go
  sdk/resourcemanager/impactreporting/armimpactreporting/fake/connectors_server.go
  sdk/resourcemanager/impactreporting/armimpactreporting/fake/impactcategories_server.go
  sdk/resourcemanager/impactreporting/armimpactreporting/fake/insights_server.go
  sdk/resourcemanager/impactreporting/armimpactreporting/fake/internal.go
  sdk/resourcemanager/impactreporting/armimpactreporting/fake/operations_server.go
  sdk/resourcemanager/impactreporting/armimpactreporting/fake/server_factory.go
  sdk/resourcemanager/impactreporting/armimpactreporting/fake/time_rfc3339.go
  sdk/resourcemanager/impactreporting/armimpactreporting/fake/workloadimpacts_server.go
  sdk/resourcemanager/impactreporting/armimpactreporting/go.mod
  sdk/resourcemanager/impactreporting/armimpactreporting/go.sum
  sdk/resourcemanager/impactreporting/armimpactreporting/impactcategories_client.go
  sdk/resourcemanager/impactreporting/armimpactreporting/impactcategories_client_example_test.go
  sdk/resourcemanager/impactreporting/armimpactreporting/insights_client.go
  sdk/resourcemanager/impactreporting/armimpactreporting/insights_client_example_test.go
  sdk/resourcemanager/impactreporting/armimpactreporting/models.go
  sdk/resourcemanager/impactreporting/armimpactreporting/models_serde.go
  sdk/resourcemanager/impactreporting/armimpactreporting/operations_client.go
  sdk/resourcemanager/impactreporting/armimpactreporting/operations_client_example_test.go
  sdk/resourcemanager/impactreporting/armimpactreporting/options.go
  sdk/resourcemanager/impactreporting/armimpactreporting/responses.go
  sdk/resourcemanager/impactreporting/armimpactreporting/time_rfc3339.go
  sdk/resourcemanager/impactreporting/armimpactreporting/tsp-location.yaml
  sdk/resourcemanager/impactreporting/armimpactreporting/workloadimpacts_client.go
  sdk/resourcemanager/impactreporting/armimpactreporting/workloadimpacts_client_example_test.go
Labels: Mgmt

#24165 Improve presentation of test proxy recording mismatch errors
  sdk/internal/CHANGELOG.md
  sdk/internal/recording/recording.go
  sdk/internal/recording/recording_test.go
Labels: Internal

#24106 Increment version for data/azcosmos releases
  sdk/data/azcosmos/CHANGELOG.md
  sdk/data/azcosmos/version.go
Labels: Cosmos

#24160 [Release] sdk/resourcemanager/quota/armquota/1.1.0
  sdk/resourcemanager/quota/armquota/CHANGELOG.md
  sdk/resourcemanager/quota/armquota/assets.json
  sdk/resourcemanager/quota/armquota/autorest.md
  sdk/resourcemanager/quota/armquota/client.go
  sdk/resourcemanager/quota/armquota/client_example_test.go
  sdk/resourcemanager/quota/armquota/client_factory.go
  sdk/resourcemanager/quota/armquota/constants.go
  sdk/resourcemanager/quota/armquota/fake/groupquotalimits_server.go
  sdk/resourcemanager/quota/armquota/fake/groupquotalimitsrequest_server.go
  sdk/resourcemanager/quota/armquota/fake/groupquotas_server.go
  sdk/resourcemanager/quota/armquota/fake/groupquotasubscriptionallocation_server.go
  sdk/resourcemanager/quota/armquota/fake/groupquotasubscriptionallocationrequest_server.go
  sdk/resourcemanager/quota/armquota/fake/groupquotasubscriptionrequests_server.go
  sdk/resourcemanager/quota/armquota/fake/groupquotasubscriptions_server.go
  sdk/resourcemanager/quota/armquota/fake/internal.go
  sdk/resourcemanager/quota/armquota/fake/operation_server.go
  sdk/resourcemanager/quota/armquota/fake/requeststatus_server.go
  sdk/resourcemanager/quota/armquota/fake/server.go
  sdk/resourcemanager/quota/armquota/fake/server_factory.go
  sdk/resourcemanager/quota/armquota/fake/time_rfc3339.go
  sdk/resourcemanager/quota/armquota/fake/usages_server.go
  sdk/resourcemanager/quota/armquota/groupquotalimits_client.go
  sdk/resourcemanager/quota/armquota/groupquotalimits_client_example_test.go
  sdk/resourcemanager/quota/armquota/groupquotalimitsrequest_client.go
  sdk/resourcemanager/quota/armquota/groupquotalimitsrequest_client_example_test.go
  sdk/resourcemanager/quota/armquota/groupquotas_client.go
  sdk/resourcemanager/quota/armquota/groupquotas_client_example_test.go
  sdk/resourcemanager/quota/armquota/groupquotasubscriptionallocation_client.go
  sdk/resourcemanager/quota/armquota/groupquotasubscriptionallocation_client_example_test.go
  sdk/resourcemanager/quota/armquota/groupquotasubscriptionallocationrequest_client.go
  sdk/resourcemanager/quota/armquota/groupquotasubscriptionallocationrequest_client_example_test.go
  sdk/resourcemanager/quota/armquota/groupquotasubscriptionrequests_client.go
  sdk/resourcemanager/quota/armquota/groupquotasubscriptionrequests_client_example_test.go
  sdk/resourcemanager/quota/armquota/groupquotasubscriptions_client.go
  sdk/resourcemanager/quota/armquota/groupquotasubscriptions_client_example_test.go
  sdk/resourcemanager/quota/armquota/interfaces.go
  sdk/resourcemanager/quota/armquota/models.go
  sdk/resourcemanager/quota/armquota/models_serde.go
  sdk/resourcemanager/quota/armquota/operation_client.go
  sdk/resourcemanager/quota/armquota/operation_client_example_test.go
  sdk/resourcemanager/quota/armquota/options.go
  sdk/resourcemanager/quota/armquota/polymorphic_helpers.go
  sdk/resourcemanager/quota/armquota/requeststatus_client.go
  sdk/resourcemanager/quota/armquota/requeststatus_client_example_test.go
  sdk/resourcemanager/quota/armquota/responses.go
  sdk/resourcemanager/quota/armquota/time_rfc3339.go
  sdk/resourcemanager/quota/armquota/usages_client.go
  sdk/resourcemanager/quota/armquota/usages_client_example_test.go
Labels: Mgmt

#24134 [Release] sdk/resourcemanager/mysql/armmysqlflexibleservers/2.0.0-beta.4
  sdk/resourcemanager/mysql/armmysqlflexibleservers/CHANGELOG.md
  sdk/resourcemanager/mysql/armmysqlflexibleservers/advancedthreatprotectionsettings_client.go
  sdk/resourcemanager/mysql/armmysqlflexibleservers/advancedthreatprotectionsettings_client_example_test.go
  sdk/resourcemanager/mysql/armmysqlflexibleservers/autorest.md
  sdk/resourcemanager/mysql/armmysqlflexibleservers/azureadadministrators_client.go
  sdk/resourcemanager/mysql/armmysqlflexibleservers/azureadadministrators_client_example_test.go
  sdk/resourcemanager/mysql/armmysqlflexibleservers/backupandexport_client.go
  sdk/resourcemanager/mysql/armmysqlflexibleservers/backupandexport_client_example_test.go
  sdk/resourcemanager/mysql/armmysqlflexibleservers/backups_client.go
  sdk/resourcemanager/mysql/armmysqlflexibleservers/backups_client_example_test.go
  sdk/resourcemanager/mysql/armmysqlflexibleservers/checknameavailability_client.go
  sdk/resourcemanager/mysql/armmysqlflexibleservers/checknameavailability_client_example_test.go
  sdk/resourcemanager/mysql/armmysqlflexibleservers/checknameavailabilitywithoutlocation_client.go
  sdk/resourcemanager/mysql/armmysqlflexibleservers/checknameavailabilitywithoutlocation_client_example_test.go
  sdk/resourcemanager/mysql/armmysqlflexibleservers/checkvirtualnetworksubnetusage_client.go
  sdk/resourcemanager/mysql/armmysqlflexibleservers/checkvirtualnetworksubnetusage_client_example_test.go
  sdk/resourcemanager/mysql/armmysqlflexibleservers/configurations_client.go
  sdk/resourcemanager/mysql/armmysqlflexibleservers/configurations_client_example_test.go
  sdk/resourcemanager/mysql/armmysqlflexibleservers/constants.go
  sdk/resourcemanager/mysql/armmysqlflexibleservers/databases_client.go
  sdk/resourcemanager/mysql/armmysqlflexibleservers/databases_client_example_test.go
  sdk/resourcemanager/mysql/armmysqlflexibleservers/fake/servers_server.go
  sdk/resourcemanager/mysql/armmysqlflexibleservers/firewallrules_client.go
  sdk/resourcemanager/mysql/armmysqlflexibleservers/firewallrules_client_example_test.go
  sdk/resourcemanager/mysql/armmysqlflexibleservers/getprivatednszonesuffix_client.go
  sdk/resourcemanager/mysql/armmysqlflexibleservers/getprivatednszonesuffix_client_example_test.go
  sdk/resourcemanager/mysql/armmysqlflexibleservers/locationbasedcapabilities_client.go
  sdk/resourcemanager/mysql/armmysqlflexibleservers/locationbasedcapabilities_client_example_test.go
  sdk/resourcemanager/mysql/armmysqlflexibleservers/locationbasedcapabilityset_client.go
  sdk/resourcemanager/mysql/armmysqlflexibleservers/locationbasedcapabilityset_client_example_test.go
  sdk/resourcemanager/mysql/armmysqlflexibleservers/logfiles_client.go
  sdk/resourcemanager/mysql/armmysqlflexibleservers/logfiles_client_example_test.go
  sdk/resourcemanager/mysql/armmysqlflexibleservers/longrunningbackup_client.go
  sdk/resourcemanager/mysql/armmysqlflexibleservers/longrunningbackup_client_example_test.go
  sdk/resourcemanager/mysql/armmysqlflexibleservers/longrunningbackups_client.go
  sdk/resourcemanager/mysql/armmysqlflexibleservers/longrunningbackups_client_example_test.go
  sdk/resourcemanager/mysql/armmysqlflexibleservers/maintenances_client.go
  sdk/resourcemanager/mysql/armmysqlflexibleservers/maintenances_client_example_test.go
  sdk/resourcemanager/mysql/armmysqlflexibleservers/models.go
  sdk/resourcemanager/mysql/armmysqlflexibleservers/models_serde.go
  sdk/resourcemanager/mysql/armmysqlflexibleservers/operationprogress_client.go
  sdk/resourcemanager/mysql/armmysqlflexibleservers/operationprogress_client_example_test.go
  sdk/resourcemanager/mysql/armmysqlflexibleservers/operationresults_client.go
  sdk/resourcemanager/mysql/armmysqlflexibleservers/operationresults_client_example_test.go
  sdk/resourcemanager/mysql/armmysqlflexibleservers/operations_client.go
  sdk/resourcemanager/mysql/armmysqlflexibleservers/operations_client_example_test.go
  sdk/resourcemanager/mysql/armmysqlflexibleservers/options.go
  sdk/resourcemanager/mysql/armmysqlflexibleservers/replicas_client.go
  sdk/resourcemanager/mysql/armmysqlflexibleservers/replicas_client_example_test.go
  sdk/resourcemanager/mysql/armmysqlflexibleservers/responses.go
  sdk/resourcemanager/mysql/armmysqlflexibleservers/servers_client.go
  sdk/resourcemanager/mysql/armmysqlflexibleservers/servers_client_example_test.go
  sdk/resourcemanager/mysql/armmysqlflexibleservers/serversmigration_client.go
  sdk/resourcemanager/mysql/armmysqlflexibleservers/serversmigration_client_example_test.go
Labels: Beta

#24056 [Release] sdk/resourcemanager/nginx/armnginx/3.1.0-beta.2
  sdk/resourcemanager/nginx/armnginx/CHANGELOG.md
  sdk/resourcemanager/nginx/armnginx/README.md
  sdk/resourcemanager/nginx/armnginx/apikeys_client.go
  sdk/resourcemanager/nginx/armnginx/apikeys_client_example_test.go
  sdk/resourcemanager/nginx/armnginx/autorest.md
  sdk/resourcemanager/nginx/armnginx/certificates_client.go
  sdk/resourcemanager/nginx/armnginx/certificates_client_example_test.go
  sdk/resourcemanager/nginx/armnginx/client_factory.go
  sdk/resourcemanager/nginx/armnginx/configurations_client.go
  sdk/resourcemanager/nginx/armnginx/configurations_client_example_test.go
  sdk/resourcemanager/nginx/armnginx/constants.go
  sdk/resourcemanager/nginx/armnginx/deployments_client.go
  sdk/resourcemanager/nginx/armnginx/deployments_client_example_test.go
  sdk/resourcemanager/nginx/armnginx/fake/apikeys_server.go
  sdk/resourcemanager/nginx/armnginx/fake/configurations_server.go
  sdk/resourcemanager/nginx/armnginx/fake/server_factory.go
  sdk/resourcemanager/nginx/armnginx/models.go
  sdk/resourcemanager/nginx/armnginx/models_serde.go
  sdk/resourcemanager/nginx/armnginx/operations_client.go
  sdk/resourcemanager/nginx/armnginx/operations_client_example_test.go
  sdk/resourcemanager/nginx/armnginx/options.go
  sdk/resourcemanager/nginx/armnginx/responses.go
Labels: BreakingChange, Beta

#24181 Sync eng/common directory with azure-sdk-tools for PR 9921
  eng/common/scripts/Package-Properties.ps1
Labels: EngSys, Central-EngSys

#24158 Sync eng/common directory with azure-sdk-tools for PR 9888
  eng/common/scripts/Helpers/PSModule-Helpers.ps1
  eng/common/scripts/stress-testing/deploy-stress-tests.ps1
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: EngSys, Central-EngSys

#24115 [Release] sdk/resourcemanager/resources/armresources/2.0.0
  sdk/resourcemanager/resources/armresources/CHANGELOG.md
  sdk/resourcemanager/resources/armresources/README.md
  sdk/resourcemanager/resources/armresources/assets.json
  sdk/resourcemanager/resources/armresources/autorest.md
  sdk/resourcemanager/resources/armresources/client.go
  sdk/resourcemanager/resources/armresources/client_factory.go
  sdk/resourcemanager/resources/armresources/constants.go
  sdk/resourcemanager/resources/armresources/deploymentoperations_client.go
  sdk/resourcemanager/resources/armresources/deployments_client.go
  sdk/resourcemanager/resources/armresources/deployments_client_example_test.go
  sdk/resourcemanager/resources/armresources/deployments_client_live_test.go
  sdk/resourcemanager/resources/armresources/fake/deploymentoperations_server.go
  sdk/resourcemanager/resources/armresources/fake/deployments_server.go
  sdk/resourcemanager/resources/armresources/fake/operations_server.go
  sdk/resourcemanager/resources/armresources/fake/providerresourcetypes_server.go
  sdk/resourcemanager/resources/armresources/fake/providers_server.go
  sdk/resourcemanager/resources/armresources/fake/resourcegroups_server.go
  sdk/resourcemanager/resources/armresources/fake/server.go
  sdk/resourcemanager/resources/armresources/fake/tags_server.go
  sdk/resourcemanager/resources/armresources/fake/time_rfc3339.go
  sdk/resourcemanager/resources/armresources/go.mod
  sdk/resourcemanager/resources/armresources/go.sum
  sdk/resourcemanager/resources/armresources/models.go
  sdk/resourcemanager/resources/armresources/models_serde.go
  sdk/resourcemanager/resources/armresources/operations_client.go
  sdk/resourcemanager/resources/armresources/options.go
  sdk/resourcemanager/resources/armresources/providerresourcetypes_client.go
  sdk/resourcemanager/resources/armresources/providerresourcetypes_client_example_test.go
  sdk/resourcemanager/resources/armresources/providers_client.go
  sdk/resourcemanager/resources/armresources/providers_client_example_test.go
  sdk/resourcemanager/resources/armresources/resourcegroups_client.go
  sdk/resourcemanager/resources/armresources/resourcegroups_client_example_test.go
  sdk/resourcemanager/resources/armresources/resourcegroups_client_live_test.go
  sdk/resourcemanager/resources/armresources/resources_client_live_test.go
  sdk/resourcemanager/resources/armresources/responses.go
  sdk/resourcemanager/resources/armresources/tags_client.go
  sdk/resourcemanager/resources/armresources/tags_client_example_test.go
  sdk/resourcemanager/resources/armresources/tags_client_live_test.go
  sdk/resourcemanager/resources/armresources/time_rfc3339.go
Labels: Mgmt, BreakingChange, Approved Major Version, Stable

#24184 [Release] sdk/resourcemanager/hybridconnectivity/armhybridconnectivity/1.2.0-beta.1
  sdk/resourcemanager/hybridconnectivity/armhybridconnectivity/CHANGELOG.md
  sdk/resourcemanager/hybridconnectivity/armhybridconnectivity/README.md
  sdk/resourcemanager/hybridconnectivity/armhybridconnectivity/autorest.md
  sdk/resourcemanager/hybridconnectivity/armhybridconnectivity/build.go
  sdk/resourcemanager/hybridconnectivity/armhybridconnectivity/client_factory.go
  sdk/resourcemanager/hybridconnectivity/armhybridconnectivity/constants.go
  sdk/resourcemanager/hybridconnectivity/armhybridconnectivity/endpoints_client.go
  sdk/resourcemanager/hybridconnectivity/armhybridconnectivity/endpoints_client_example_test.go
  sdk/resourcemanager/hybridconnectivity/armhybridconnectivity/fake/endpoints_server.go
  sdk/resourcemanager/hybridconnectivity/armhybridconnectivity/fake/generateawstemplate_server.go
  sdk/resourcemanager/hybridconnectivity/armhybridconnectivity/fake/internal.go
  sdk/resourcemanager/hybridconnectivity/armhybridconnectivity/fake/inventory_server.go
  sdk/resourcemanager/hybridconnectivity/armhybridconnectivity/fake/operations_server.go
  sdk/resourcemanager/hybridconnectivity/armhybridconnectivity/fake/publiccloudconnectors_server.go
  sdk/resourcemanager/hybridconnectivity/armhybridconnectivity/fake/server_factory.go
  sdk/resourcemanager/hybridconnectivity/armhybridconnectivity/fake/serviceconfigurations_server.go
  sdk/resourcemanager/hybridconnectivity/armhybridconnectivity/fake/solutionconfigurations_server.go
  sdk/resourcemanager/hybridconnectivity/armhybridconnectivity/fake/solutiontypes_server.go
  sdk/resourcemanager/hybridconnectivity/armhybridconnectivity/fake/time_rfc3339.go
  sdk/resourcemanager/hybridconnectivity/armhybridconnectivity/generateawstemplate_client.go
  sdk/resourcemanager/hybridconnectivity/armhybridconnectivity/generateawstemplate_client_example_test.go
  sdk/resourcemanager/hybridconnectivity/armhybridconnectivity/inventory_client.go
  sdk/resourcemanager/hybridconnectivity/armhybridconnectivity/inventory_client_example_test.go
  sdk/resourcemanager/hybridconnectivity/armhybridconnectivity/models.go
  sdk/resourcemanager/hybridconnectivity/armhybridconnectivity/models_serde.go
  sdk/resourcemanager/hybridconnectivity/armhybridconnectivity/operations_client.go
  sdk/resourcemanager/hybridconnectivity/armhybridconnectivity/operations_client_example_test.go
  sdk/resourcemanager/hybridconnectivity/armhybridconnectivity/options.go
  sdk/resourcemanager/hybridconnectivity/armhybridconnectivity/publiccloudconnectors_client.go
  sdk/resourcemanager/hybridconnectivity/armhybridconnectivity/publiccloudconnectors_client_example_test.go
  sdk/resourcemanager/hybridconnectivity/armhybridconnectivity/response_types.go
  sdk/resourcemanager/hybridconnectivity/armhybridconnectivity/responses.go
  sdk/resourcemanager/hybridconnectivity/armhybridconnectivity/serviceconfigurations_client.go
  sdk/resourcemanager/hybridconnectivity/armhybridconnectivity/serviceconfigurations_client_example_test.go
  sdk/resourcemanager/hybridconnectivity/armhybridconnectivity/solutionconfigurations_client.go
  sdk/resourcemanager/hybridconnectivity/armhybridconnectivity/solutionconfigurations_client_example_test.go
  sdk/resourcemanager/hybridconnectivity/armhybridconnectivity/solutiontypes_client.go
  sdk/resourcemanager/hybridconnectivity/armhybridconnectivity/solutiontypes_client_example_test.go
  sdk/resourcemanager/hybridconnectivity/armhybridconnectivity/time_rfc3339.go
  sdk/resourcemanager/hybridconnectivity/armhybridconnectivity/tsp-location.yaml
Labels: Mgmt

#24186 Sync eng/common directory with azure-sdk-tools for PR 9917
  eng/common/pipelines/templates/steps/detect-api-changes.yml
Labels: EngSys, Central-EngSys

#24179 [Release] sdk/resourcemanager/databasewatcher/armdatabasewatcher/0.1.0
  sdk/resourcemanager/databasewatcher/armdatabasewatcher/CHANGELOG.md
  sdk/resourcemanager/databasewatcher/armdatabasewatcher/LICENSE.txt
  sdk/resourcemanager/databasewatcher/armdatabasewatcher/README.md
  sdk/resourcemanager/databasewatcher/armdatabasewatcher/alertruleresources_client.go
  sdk/resourcemanager/databasewatcher/armdatabasewatcher/alertruleresources_client_example_test.go
  sdk/resourcemanager/databasewatcher/armdatabasewatcher/assets.json
  sdk/resourcemanager/databasewatcher/armdatabasewatcher/ci.yml
  sdk/resourcemanager/databasewatcher/armdatabasewatcher/client_factory.go
  sdk/resourcemanager/databasewatcher/armdatabasewatcher/constants.go
  sdk/resourcemanager/databasewatcher/armdatabasewatcher/fake/alertruleresources_server.go
  sdk/resourcemanager/databasewatcher/armdatabasewatcher/fake/healthvalidations_server.go
  sdk/resourcemanager/databasewatcher/armdatabasewatcher/fake/internal.go
  sdk/resourcemanager/databasewatcher/armdatabasewatcher/fake/operations_server.go
  sdk/resourcemanager/databasewatcher/armdatabasewatcher/fake/server_factory.go
  sdk/resourcemanager/databasewatcher/armdatabasewatcher/fake/sharedprivatelinkresources_server.go
  sdk/resourcemanager/databasewatcher/armdatabasewatcher/fake/targets_server.go
  sdk/resourcemanager/databasewatcher/armdatabasewatcher/fake/time_rfc3339.go
  sdk/resourcemanager/databasewatcher/armdatabasewatcher/fake/watchers_server.go
  sdk/resourcemanager/databasewatcher/armdatabasewatcher/go.mod
  sdk/resourcemanager/databasewatcher/armdatabasewatcher/go.sum
  sdk/resourcemanager/databasewatcher/armdatabasewatcher/healthvalidations_client.go
  sdk/resourcemanager/databasewatcher/armdatabasewatcher/healthvalidations_client_example_test.go
  sdk/resourcemanager/databasewatcher/armdatabasewatcher/interfaces.go
  sdk/resourcemanager/databasewatcher/armdatabasewatcher/models.go
  sdk/resourcemanager/databasewatcher/armdatabasewatcher/models_serde.go
  sdk/resourcemanager/databasewatcher/armdatabasewatcher/operation_live_test.go
  sdk/resourcemanager/databasewatcher/armdatabasewatcher/operations_client.go
  sdk/resourcemanager/databasewatcher/armdatabasewatcher/operations_client_example_test.go
  sdk/resourcemanager/databasewatcher/armdatabasewatcher/options.go
  sdk/resourcemanager/databasewatcher/armdatabasewatcher/polymorphic_helpers.go
  sdk/resourcemanager/databasewatcher/armdatabasewatcher/responses.go
  sdk/resourcemanager/databasewatcher/armdatabasewatcher/sharedprivatelinkresources_client.go
  sdk/resourcemanager/databasewatcher/armdatabasewatcher/sharedprivatelinkresources_client_example_test.go
  sdk/resourcemanager/databasewatcher/armdatabasewatcher/targets_client.go
  sdk/resourcemanager/databasewatcher/armdatabasewatcher/targets_client_example_test.go
  sdk/resourcemanager/databasewatcher/armdatabasewatcher/time_rfc3339.go
  sdk/resourcemanager/databasewatcher/armdatabasewatcher/tsp-location.yaml
  sdk/resourcemanager/databasewatcher/armdatabasewatcher/utils_test.go
  sdk/resourcemanager/databasewatcher/armdatabasewatcher/watchers_client.go
  sdk/resourcemanager/databasewatcher/armdatabasewatcher/watchers_client_example_test.go
Labels: Mgmt
