Repository Azure/azure-sdk-for-go, pull requests merged in 2025-06, with the labels that each got.

#24589 [Release] sdk/resourcemanager/dell/armdellstorage/0.1.0
  sdk/resourcemanager/dell/armdellstorage/CHANGELOG.md
  sdk/resourcemanager/dell/armdellstorage/LICENSE.txt
  sdk/resourcemanager/dell/armdellstorage/README.md
  sdk/resourcemanager/dell/armdellstorage/ci.yml
  sdk/resourcemanager/dell/armdellstorage/client_factory.go
  sdk/resourcemanager/dell/armdellstorage/constants.go
  sdk/resourcemanager/dell/armdellstorage/fake/filesystems_server.go
  sdk/resourcemanager/dell/armdellstorage/fake/internal.go
  sdk/resourcemanager/dell/armdellstorage/fake/operations_server.go
  sdk/resourcemanager/dell/armdellstorage/fake/server_factory.go
  sdk/resourcemanager/dell/armdellstorage/filesystems_client.go
  sdk/resourcemanager/dell/armdellstorage/filesystems_client_example_test.go
  sdk/resourcemanager/dell/armdellstorage/go.mod
  sdk/resourcemanager/dell/armdellstorage/go.sum
  sdk/resourcemanager/dell/armdellstorage/models.go
  sdk/resourcemanager/dell/armdellstorage/models_serde.go
  sdk/resourcemanager/dell/armdellstorage/operations_client.go
  sdk/resourcemanager/dell/armdellstorage/operations_client_example_test.go
  sdk/resourcemanager/dell/armdellstorage/options.go
  sdk/resourcemanager/dell/armdellstorage/responses.go
  sdk/resourcemanager/dell/armdellstorage/time_rfc3339.go
  sdk/resourcemanager/dell/armdellstorage/tsp-location.yaml
Labels: Mgmt

#24712 Prevent CLI credentials waiting indefinitely for subprocess output
  sdk/azidentity/CHANGELOG.md
  sdk/azidentity/azure_cli_credential.go
  sdk/azidentity/azure_developer_cli_credential.go
Labels: Azure.Identity

#24715 Sync eng/common directory with azure-sdk-tools for PR 10755
  eng/common/scripts/Helpers/ApiView-Helpers.ps1
Labels: EngSys, Central-EngSys

#24718 Sync eng/common directory with azure-sdk-tools for PR 10795
  eng/common/scripts/Helpers/ApiView-Helpers.ps1
Labels: EngSys, Central-EngSys

#24621 [Release] sdk/resourcemanager/lambdatesthyperexecute/armlambdatesthyperexecute/1.0.0
  sdk/resourcemanager/lambdatesthyperexecute/armlambdatesthyperexecute/CHANGELOG.md
  sdk/resourcemanager/lambdatesthyperexecute/armlambdatesthyperexecute/constants.go
  sdk/resourcemanager/lambdatesthyperexecute/armlambdatesthyperexecute/operations_client.go
  sdk/resourcemanager/lambdatesthyperexecute/armlambdatesthyperexecute/operations_client_example_test.go
  sdk/resourcemanager/lambdatesthyperexecute/armlambdatesthyperexecute/organizations_client.go
  sdk/resourcemanager/lambdatesthyperexecute/armlambdatesthyperexecute/organizations_client_example_test.go
  sdk/resourcemanager/lambdatesthyperexecute/armlambdatesthyperexecute/tsp-location.yaml
Labels: Mgmt

#24662 Sync eng/common directory with azure-sdk-tools for PR 10681
  eng/common/mcp/azure-sdk-mcp.ps1
Labels: EngSys, Central-EngSys

#24663 Sync eng/common directory with azure-sdk-tools for PR 10694
  eng/common/scripts/common.ps1
Labels: EngSys, Central-EngSys

#24741 Add in a simple service bus troubleshooting guide.
  sdk/messaging/azservicebus/README.md
  sdk/messaging/azservicebus/TROUBLESHOOTING.md
Labels: Service Bus

#24733 [keyvault] upgrade to 7.6
  sdk/security/keyvault/azadmin/CHANGELOG.md
  sdk/security/keyvault/azadmin/assets.json
  sdk/security/keyvault/azadmin/backup/_metadata.json
  sdk/security/keyvault/azadmin/backup/client.go
  sdk/security/keyvault/azadmin/backup/tsp-location.yaml
  sdk/security/keyvault/azadmin/internal/version.go
  sdk/security/keyvault/azadmin/rbac/_metadata.json
  sdk/security/keyvault/azadmin/rbac/client.go
  sdk/security/keyvault/azadmin/rbac/tsp-location.yaml
  sdk/security/keyvault/azadmin/settings/_metadata.json
  sdk/security/keyvault/azadmin/settings/client.go
  sdk/security/keyvault/azadmin/settings/tsp-location.yaml
  sdk/security/keyvault/azcertificates/CHANGELOG.md
  sdk/security/keyvault/azcertificates/_metadata.json
  sdk/security/keyvault/azcertificates/assets.json
  sdk/security/keyvault/azcertificates/client.go
  sdk/security/keyvault/azcertificates/tsp-location.yaml
  sdk/security/keyvault/azcertificates/version.go
  sdk/security/keyvault/azkeys/CHANGELOG.md
  sdk/security/keyvault/azkeys/_metadata.json
  sdk/security/keyvault/azkeys/assets.json
  sdk/security/keyvault/azkeys/client.go
  sdk/security/keyvault/azkeys/models.go
  sdk/security/keyvault/azkeys/tsp-location.yaml
  sdk/security/keyvault/azkeys/version.go
  sdk/security/keyvault/azsecrets/CHANGELOG.md
  sdk/security/keyvault/azsecrets/_metadata.json
  sdk/security/keyvault/azsecrets/assets.json
  sdk/security/keyvault/azsecrets/client.go
  sdk/security/keyvault/azsecrets/tsp-location.yaml
  sdk/security/keyvault/azsecrets/version.go
Labels: KeyVault, Client

#24746 Prepare azidentity v1.10.1 for release
  sdk/azidentity/CHANGELOG.md
  sdk/azidentity/version.go
Labels: Azure.Identity

#24747 cosmos: changelog for 1.5.0-beta.0
  sdk/data/azcosmos/CHANGELOG.md
Labels: Cosmos

#24754 Sync eng/common directory with azure-sdk-tools for PR 10835
  eng/common/pipelines/templates/jobs/prepare-pipelines.yml
Labels: EngSys, Central-EngSys

#24763 Increment version for azidentity releases
  sdk/azidentity/CHANGELOG.md
  sdk/azidentity/version.go
Labels: Azure.Identity

#24755 Fix live managed identity test deployment
  sdk/azidentity/test-resources-post.ps1
Labels: Azure.Identity

#24756 [Release] sdk/resourcemanager/onlineexperimentation/onlineexperimentation/0.1.0
  sdk/resourcemanager/onlineexperimentation/armonlineexperimentation/CHANGELOG.md
  sdk/resourcemanager/onlineexperimentation/armonlineexperimentation/README.md
  sdk/resourcemanager/onlineexperimentation/armonlineexperimentation/_metadata.json
  sdk/resourcemanager/onlineexperimentation/armonlineexperimentation/client_factory.go
  sdk/resourcemanager/onlineexperimentation/armonlineexperimentation/fake/server_factory.go
  sdk/resourcemanager/onlineexperimentation/armonlineexperimentation/fake/workspaces_server.go
  sdk/resourcemanager/onlineexperimentation/armonlineexperimentation/go.mod
  sdk/resourcemanager/onlineexperimentation/armonlineexperimentation/go.sum
  sdk/resourcemanager/onlineexperimentation/armonlineexperimentation/models.go
  sdk/resourcemanager/onlineexperimentation/armonlineexperimentation/models_serde.go
  sdk/resourcemanager/onlineexperimentation/armonlineexperimentation/operations_client_example_test.go
  sdk/resourcemanager/onlineexperimentation/armonlineexperimentation/options.go
  sdk/resourcemanager/onlineexperimentation/armonlineexperimentation/responses.go
  sdk/resourcemanager/onlineexperimentation/armonlineexperimentation/tsp-location.yaml
  sdk/resourcemanager/onlineexperimentation/armonlineexperimentation/workspaces_client.go
  sdk/resourcemanager/onlineexperimentation/armonlineexperimentation/workspaces_client_example_test.go
Labels: Mgmt

#24774 Sync eng/common directory with azure-sdk-tools for PR 10857
  eng/common/scripts/Helpers/ApiView-Helpers.ps1
  eng/common/scripts/Invoke-GitHubAPI.ps1
Labels: EngSys, Central-EngSys

#24654 [Release] sdk/resourcemanager/planetarycomputer/armplanetarycomputer/0.1.0
  sdk/resourcemanager/planetarycomputer/armplanetarycomputer/CHANGELOG.md
  sdk/resourcemanager/planetarycomputer/armplanetarycomputer/LICENSE.txt
  sdk/resourcemanager/planetarycomputer/armplanetarycomputer/README.md
  sdk/resourcemanager/planetarycomputer/armplanetarycomputer/ci.yml
  sdk/resourcemanager/planetarycomputer/armplanetarycomputer/client_factory.go
  sdk/resourcemanager/planetarycomputer/armplanetarycomputer/constants.go
  sdk/resourcemanager/planetarycomputer/armplanetarycomputer/fake/geocatalogs_server.go
  sdk/resourcemanager/planetarycomputer/armplanetarycomputer/fake/internal.go
  sdk/resourcemanager/planetarycomputer/armplanetarycomputer/fake/server_factory.go
  sdk/resourcemanager/planetarycomputer/armplanetarycomputer/geocatalogs_client.go
  sdk/resourcemanager/planetarycomputer/armplanetarycomputer/geocatalogs_client_example_test.go
  sdk/resourcemanager/planetarycomputer/armplanetarycomputer/go.mod
  sdk/resourcemanager/planetarycomputer/armplanetarycomputer/go.sum
  sdk/resourcemanager/planetarycomputer/armplanetarycomputer/models.go
  sdk/resourcemanager/planetarycomputer/armplanetarycomputer/models_serde.go
  sdk/resourcemanager/planetarycomputer/armplanetarycomputer/options.go
  sdk/resourcemanager/planetarycomputer/armplanetarycomputer/responses.go
  sdk/resourcemanager/planetarycomputer/armplanetarycomputer/time_rfc3339.go
  sdk/resourcemanager/planetarycomputer/armplanetarycomputer/tsp-location.yaml
Labels: Mgmt

#24787 Increment version for security/keyvault/internal releases
  sdk/security/keyvault/internal/CHANGELOG.md
  sdk/security/keyvault/internal/constants.go
Labels: KeyVault

#24768 [azcertificate] add fakes support
  eng/config.json
  sdk/security/keyvault/azcertificates/CHANGELOG.md
  sdk/security/keyvault/azcertificates/_metadata.json
  sdk/security/keyvault/azcertificates/client.go
  sdk/security/keyvault/azcertificates/fake/custom_server.go
  sdk/security/keyvault/azcertificates/fake/internal.go
  sdk/security/keyvault/azcertificates/fake/server.go
  sdk/security/keyvault/azcertificates/fake/server_test.go
  sdk/security/keyvault/azcertificates/go.mod
  sdk/security/keyvault/azcertificates/go.sum
  sdk/security/keyvault/azcertificates/internal/transforms.go
  sdk/security/keyvault/azcertificates/testdata/perf/go.mod
  sdk/security/keyvault/azcertificates/testdata/perf/go.sum
  sdk/security/keyvault/azcertificates/tsp-location.yaml
Labels: KeyVault, Client

#24789 Increment version for security/keyvault/azadmin releases
  sdk/security/keyvault/azadmin/CHANGELOG.md
  sdk/security/keyvault/azadmin/internal/version.go
Labels: KeyVault

#24790 Increment version for security/keyvault/azsecrets releases
  sdk/security/keyvault/azsecrets/CHANGELOG.md
  sdk/security/keyvault/azsecrets/version.go
Labels: KeyVault

#24791 Increment version for security/keyvault/azcertificates releases
  sdk/security/keyvault/azcertificates/CHANGELOG.md
  sdk/security/keyvault/azcertificates/version.go
Labels: KeyVault

#24745 [Release] sdk/resourcemanager/chaos/armchaos/2.0.0
  sdk/resourcemanager/chaos/armchaos/CHANGELOG.md
  sdk/resourcemanager/chaos/armchaos/README.md
  sdk/resourcemanager/chaos/armchaos/_metadata.json
  sdk/resourcemanager/chaos/armchaos/assets.json
  sdk/resourcemanager/chaos/armchaos/autorest.md
  sdk/resourcemanager/chaos/armchaos/build.go
  sdk/resourcemanager/chaos/armchaos/capabilities_client.go
  sdk/resourcemanager/chaos/armchaos/capabilities_client_example_test.go
  sdk/resourcemanager/chaos/armchaos/capabilities_live_test.go
  sdk/resourcemanager/chaos/armchaos/capabilitytypes_client.go
  sdk/resourcemanager/chaos/armchaos/capabilitytypes_client_example_test.go
  sdk/resourcemanager/chaos/armchaos/capabilitytypes_live_test.go
  sdk/resourcemanager/chaos/armchaos/client_factory.go
  sdk/resourcemanager/chaos/armchaos/constants.go
  sdk/resourcemanager/chaos/armchaos/experiments_client.go
  sdk/resourcemanager/chaos/armchaos/experiments_client_example_test.go
  sdk/resourcemanager/chaos/armchaos/experiments_live_test.go
  sdk/resourcemanager/chaos/armchaos/fake/capabilities_server.go
  sdk/resourcemanager/chaos/armchaos/fake/capabilitytypes_server.go
  sdk/resourcemanager/chaos/armchaos/fake/experiments_server.go
  sdk/resourcemanager/chaos/armchaos/fake/internal.go
  sdk/resourcemanager/chaos/armchaos/fake/operations_server.go
  sdk/resourcemanager/chaos/armchaos/fake/operationstatuses_server.go
  sdk/resourcemanager/chaos/armchaos/fake/server_factory.go
  sdk/resourcemanager/chaos/armchaos/fake/targets_server.go
  sdk/resourcemanager/chaos/armchaos/fake/targettypes_server.go
  sdk/resourcemanager/chaos/armchaos/fake/time_rfc3339.go
  sdk/resourcemanager/chaos/armchaos/go.mod
  sdk/resourcemanager/chaos/armchaos/go.sum
  sdk/resourcemanager/chaos/armchaos/interfaces.go
  sdk/resourcemanager/chaos/armchaos/models.go
  sdk/resourcemanager/chaos/armchaos/models_serde.go
  sdk/resourcemanager/chaos/armchaos/operations_client.go
  sdk/resourcemanager/chaos/armchaos/operations_client_example_test.go
  sdk/resourcemanager/chaos/armchaos/operations_live_test.go
  sdk/resourcemanager/chaos/armchaos/operationstatuses_client.go
  sdk/resourcemanager/chaos/armchaos/operationstatuses_client_example_test.go
  sdk/resourcemanager/chaos/armchaos/options.go
  sdk/resourcemanager/chaos/armchaos/polymorphic_helpers.go
  sdk/resourcemanager/chaos/armchaos/responses.go
  sdk/resourcemanager/chaos/armchaos/targets_client.go
  sdk/resourcemanager/chaos/armchaos/targets_client_example_test.go
  sdk/resourcemanager/chaos/armchaos/targets_live_test.go
  sdk/resourcemanager/chaos/armchaos/targettypes_client.go
  sdk/resourcemanager/chaos/armchaos/targettypes_client_example_test.go
  sdk/resourcemanager/chaos/armchaos/targettypes_live_test.go
  sdk/resourcemanager/chaos/armchaos/time_rfc3339.go
  sdk/resourcemanager/chaos/armchaos/tsp-location.yaml
Labels: BreakingChange, Approved Major Version, Stable

#24793 Increment version for security/keyvault/azkeys releases
  sdk/security/keyvault/azkeys/CHANGELOG.md
  sdk/security/keyvault/azkeys/version.go
Labels: KeyVault

#24796 Sync eng/common directory with azure-sdk-tools for PR 10895
  eng/common/pipelines/templates/steps/verify-links.yml
  eng/common/scripts/Verify-Links.ps1
Labels: EngSys, Central-EngSys

#24801 azcosmos: stop depending on Track 1
  sdk/data/azcosmos/go.mod
  sdk/data/azcosmos/go.sum
  sdk/data/azcosmos/go_mod_tidy_hack.go
Labels: Cosmos, customer-reported, Community Contribution

#24757 [Release] sdk/resourcemanager/appconfiguration/armappconfiguration/3.0.0
  sdk/resourcemanager/appconfiguration/armappconfiguration/CHANGELOG.md
  sdk/resourcemanager/appconfiguration/armappconfiguration/README.md
  sdk/resourcemanager/appconfiguration/armappconfiguration/appconfiguration_live_test.go
  sdk/resourcemanager/appconfiguration/armappconfiguration/assets.json
  sdk/resourcemanager/appconfiguration/armappconfiguration/autorest.md
  sdk/resourcemanager/appconfiguration/armappconfiguration/client_factory.go
  sdk/resourcemanager/appconfiguration/armappconfiguration/configurationstores_client.go
  sdk/resourcemanager/appconfiguration/armappconfiguration/configurationstores_client_example_test.go
  sdk/resourcemanager/appconfiguration/armappconfiguration/constants.go
  sdk/resourcemanager/appconfiguration/armappconfiguration/fake/configurationstores_server.go
  sdk/resourcemanager/appconfiguration/armappconfiguration/fake/internal.go
  sdk/resourcemanager/appconfiguration/armappconfiguration/fake/keyvalues_server.go
  sdk/resourcemanager/appconfiguration/armappconfiguration/fake/operations_server.go
  sdk/resourcemanager/appconfiguration/armappconfiguration/fake/privateendpointconnections_server.go
  sdk/resourcemanager/appconfiguration/armappconfiguration/fake/privatelinkresources_server.go
  sdk/resourcemanager/appconfiguration/armappconfiguration/fake/replicas_server.go
  sdk/resourcemanager/appconfiguration/armappconfiguration/fake/server_factory.go
  sdk/resourcemanager/appconfiguration/armappconfiguration/fake/snapshots_server.go
  sdk/resourcemanager/appconfiguration/armappconfiguration/fake/time_rfc3339.go
  sdk/resourcemanager/appconfiguration/armappconfiguration/go.mod
  sdk/resourcemanager/appconfiguration/armappconfiguration/go.sum
  sdk/resourcemanager/appconfiguration/armappconfiguration/keyvalues_client.go
  sdk/resourcemanager/appconfiguration/armappconfiguration/keyvalues_client_example_test.go
  sdk/resourcemanager/appconfiguration/armappconfiguration/models.go
  sdk/resourcemanager/appconfiguration/armappconfiguration/models_serde.go
  sdk/resourcemanager/appconfiguration/armappconfiguration/operations_client.go
  sdk/resourcemanager/appconfiguration/armappconfiguration/operations_client_example_test.go
  sdk/resourcemanager/appconfiguration/armappconfiguration/options.go
  sdk/resourcemanager/appconfiguration/armappconfiguration/privateendpointconnections_client.go
  sdk/resourcemanager/appconfiguration/armappconfiguration/privateendpointconnections_client_example_test.go
  sdk/resourcemanager/appconfiguration/armappconfiguration/privatelinkresources_client.go
  sdk/resourcemanager/appconfiguration/armappconfiguration/privatelinkresources_client_example_test.go
  sdk/resourcemanager/appconfiguration/armappconfiguration/replicas_client.go
  sdk/resourcemanager/appconfiguration/armappconfiguration/replicas_client_example_test.go
  sdk/resourcemanager/appconfiguration/armappconfiguration/responses.go
  sdk/resourcemanager/appconfiguration/armappconfiguration/snapshots_client.go
  sdk/resourcemanager/appconfiguration/armappconfiguration/snapshots_client_example_test.go
  sdk/resourcemanager/appconfiguration/armappconfiguration/time_rfc3339.go
Labels: Mgmt, BreakingChange, Approved Major Version, Stable

#24802 [Release] sdk/resourcemanager/containerservice/armcontainerservice/7.0.0
  sdk/resourcemanager/containerservice/armcontainerservice/CHANGELOG.md
  sdk/resourcemanager/containerservice/armcontainerservice/agentpools_client.go
  sdk/resourcemanager/containerservice/armcontainerservice/agentpools_client_example_test.go
  sdk/resourcemanager/containerservice/armcontainerservice/assets.json
  sdk/resourcemanager/containerservice/armcontainerservice/autorest.md
  sdk/resourcemanager/containerservice/armcontainerservice/client.go
  sdk/resourcemanager/containerservice/armcontainerservice/client_example_test.go
  sdk/resourcemanager/containerservice/armcontainerservice/client_factory.go
  sdk/resourcemanager/containerservice/armcontainerservice/constants.go
  sdk/resourcemanager/containerservice/armcontainerservice/fake/loadbalancers_server.go
  sdk/resourcemanager/containerservice/armcontainerservice/fake/managedclusters_server.go
  sdk/resourcemanager/containerservice/armcontainerservice/fake/managedclustersnapshots_server.go
  sdk/resourcemanager/containerservice/armcontainerservice/fake/managednamespaces_server.go
  sdk/resourcemanager/containerservice/armcontainerservice/fake/operationstatusresult_server.go
  sdk/resourcemanager/containerservice/armcontainerservice/fake/server.go
  sdk/resourcemanager/containerservice/armcontainerservice/fake/server_factory.go
  sdk/resourcemanager/containerservice/armcontainerservice/go.mod
  sdk/resourcemanager/containerservice/armcontainerservice/go.sum
  sdk/resourcemanager/containerservice/armcontainerservice/loadbalancers_client.go
  sdk/resourcemanager/containerservice/armcontainerservice/loadbalancers_client_example_test.go
  sdk/resourcemanager/containerservice/armcontainerservice/machines_client.go
  sdk/resourcemanager/containerservice/armcontainerservice/machines_client_example_test.go
  sdk/resourcemanager/containerservice/armcontainerservice/maintenanceconfigurations_client.go
  sdk/resourcemanager/containerservice/armcontainerservice/maintenanceconfigurations_client_example_test.go
  sdk/resourcemanager/containerservice/armcontainerservice/managedclusters_client.go
  sdk/resourcemanager/containerservice/armcontainerservice/managedclusters_client_example_test.go
  sdk/resourcemanager/containerservice/armcontainerservice/managedclustersnapshots_client.go
  sdk/resourcemanager/containerservice/armcontainerservice/managedclustersnapshots_client_example_test.go
  sdk/resourcemanager/containerservice/armcontainerservice/managednamespaces_client.go
  sdk/resourcemanager/containerservice/armcontainerservice/managednamespaces_client_example_test.go
  sdk/resourcemanager/containerservice/armcontainerservice/models.go
  sdk/resourcemanager/containerservice/armcontainerservice/models_serde.go
  sdk/resourcemanager/containerservice/armcontainerservice/operations_client.go
  sdk/resourcemanager/containerservice/armcontainerservice/operations_client_example_test.go
  sdk/resourcemanager/containerservice/armcontainerservice/operationstatusresult_client.go
  sdk/resourcemanager/containerservice/armcontainerservice/operationstatusresult_client_example_test.go
  sdk/resourcemanager/containerservice/armcontainerservice/options.go
  sdk/resourcemanager/containerservice/armcontainerservice/privateendpointconnections_client.go
  sdk/resourcemanager/containerservice/armcontainerservice/privateendpointconnections_client_example_test.go
  sdk/resourcemanager/containerservice/armcontainerservice/privatelinkresources_client.go
  sdk/resourcemanager/containerservice/armcontainerservice/privatelinkresources_client_example_test.go
  sdk/resourcemanager/containerservice/armcontainerservice/resolveprivatelinkserviceid_client.go
  sdk/resourcemanager/containerservice/armcontainerservice/resolveprivatelinkserviceid_client_example_test.go
  sdk/resourcemanager/containerservice/armcontainerservice/responses.go
  sdk/resourcemanager/containerservice/armcontainerservice/snapshots_client.go
  sdk/resourcemanager/containerservice/armcontainerservice/snapshots_client_example_test.go
  sdk/resourcemanager/containerservice/armcontainerservice/trustedaccessrolebindings_client.go
  sdk/resourcemanager/containerservice/armcontainerservice/trustedaccessrolebindings_client_example_test.go
  sdk/resourcemanager/containerservice/armcontainerservice/trustedaccessroles_client.go
  sdk/resourcemanager/containerservice/armcontainerservice/trustedaccessroles_client_example_test.go
Labels: Mgmt, Approved Major Version

#24775 [Release] sdk/resourcemanager/recoveryservices/armrecoveryservices/2.1.0
  sdk/resourcemanager/recoveryservices/armrecoveryservices/CHANGELOG.md
  sdk/resourcemanager/recoveryservices/armrecoveryservices/assets.json
  sdk/resourcemanager/recoveryservices/armrecoveryservices/autorest.md
  sdk/resourcemanager/recoveryservices/armrecoveryservices/client.go
  sdk/resourcemanager/recoveryservices/armrecoveryservices/client_example_test.go
  sdk/resourcemanager/recoveryservices/armrecoveryservices/client_factory.go
  sdk/resourcemanager/recoveryservices/armrecoveryservices/constants.go
  sdk/resourcemanager/recoveryservices/armrecoveryservices/fake/internal.go
  sdk/resourcemanager/recoveryservices/armrecoveryservices/fake/operations_server.go
  sdk/resourcemanager/recoveryservices/armrecoveryservices/fake/privatelinkresources_server.go
  sdk/resourcemanager/recoveryservices/armrecoveryservices/fake/registeredidentities_server.go
  sdk/resourcemanager/recoveryservices/armrecoveryservices/fake/replicationusages_server.go
  sdk/resourcemanager/recoveryservices/armrecoveryservices/fake/server.go
  sdk/resourcemanager/recoveryservices/armrecoveryservices/fake/server_factory.go
  sdk/resourcemanager/recoveryservices/armrecoveryservices/fake/time_rfc3339.go
  sdk/resourcemanager/recoveryservices/armrecoveryservices/fake/usages_server.go
  sdk/resourcemanager/recoveryservices/armrecoveryservices/fake/vaultcertificates_server.go
  sdk/resourcemanager/recoveryservices/armrecoveryservices/fake/vaultextendedinfo_server.go
  sdk/resourcemanager/recoveryservices/armrecoveryservices/fake/vaults_server.go
  sdk/resourcemanager/recoveryservices/armrecoveryservices/go.mod
  sdk/resourcemanager/recoveryservices/armrecoveryservices/go.sum
  sdk/resourcemanager/recoveryservices/armrecoveryservices/interfaces.go
  sdk/resourcemanager/recoveryservices/armrecoveryservices/models.go
  sdk/resourcemanager/recoveryservices/armrecoveryservices/models_serde.go
  sdk/resourcemanager/recoveryservices/armrecoveryservices/operations_client.go
  sdk/resourcemanager/recoveryservices/armrecoveryservices/operations_client_example_test.go
  sdk/resourcemanager/recoveryservices/armrecoveryservices/options.go
  sdk/resourcemanager/recoveryservices/armrecoveryservices/polymorphic_helpers.go
  sdk/resourcemanager/recoveryservices/armrecoveryservices/privatelinkresources_client.go
  sdk/resourcemanager/recoveryservices/armrecoveryservices/privatelinkresources_client_example_test.go
  sdk/resourcemanager/recoveryservices/armrecoveryservices/recoveryservices_live_test.go
  sdk/resourcemanager/recoveryservices/armrecoveryservices/registeredidentities_client.go
  sdk/resourcemanager/recoveryservices/armrecoveryservices/registeredidentities_client_example_test.go
  sdk/resourcemanager/recoveryservices/armrecoveryservices/replicationusages_client.go
  sdk/resourcemanager/recoveryservices/armrecoveryservices/replicationusages_client_example_test.go
  sdk/resourcemanager/recoveryservices/armrecoveryservices/responses.go
  sdk/resourcemanager/recoveryservices/armrecoveryservices/time_rfc3339.go
  sdk/resourcemanager/recoveryservices/armrecoveryservices/usages_client.go
  sdk/resourcemanager/recoveryservices/armrecoveryservices/usages_client_example_test.go
  sdk/resourcemanager/recoveryservices/armrecoveryservices/vaultcertificates_client.go
  sdk/resourcemanager/recoveryservices/armrecoveryservices/vaultcertificates_client_example_test.go
  sdk/resourcemanager/recoveryservices/armrecoveryservices/vaultextendedinfo_client.go
  sdk/resourcemanager/recoveryservices/armrecoveryservices/vaultextendedinfo_client_example_test.go
  sdk/resourcemanager/recoveryservices/armrecoveryservices/vaults_client.go
  sdk/resourcemanager/recoveryservices/armrecoveryservices/vaults_client_example_test.go
Labels: Mgmt

#24758 [Release] sdk/resourcemanager/kubernetesconfiguration/armprivatelinkscopes/0.1.0
  sdk/resourcemanager/kubernetesconfiguration/armprivatelinkscopes/CHANGELOG.md
  sdk/resourcemanager/kubernetesconfiguration/armprivatelinkscopes/LICENSE.txt
  sdk/resourcemanager/kubernetesconfiguration/armprivatelinkscopes/README.md
  sdk/resourcemanager/kubernetesconfiguration/armprivatelinkscopes/autorest.md
  sdk/resourcemanager/kubernetesconfiguration/armprivatelinkscopes/build.go
  sdk/resourcemanager/kubernetesconfiguration/armprivatelinkscopes/ci.yml
  sdk/resourcemanager/kubernetesconfiguration/armprivatelinkscopes/client.go
  sdk/resourcemanager/kubernetesconfiguration/armprivatelinkscopes/client_example_test.go
  sdk/resourcemanager/kubernetesconfiguration/armprivatelinkscopes/client_factory.go
  sdk/resourcemanager/kubernetesconfiguration/armprivatelinkscopes/constants.go
  sdk/resourcemanager/kubernetesconfiguration/armprivatelinkscopes/fake/internal.go
  sdk/resourcemanager/kubernetesconfiguration/armprivatelinkscopes/fake/privateendpointconnections_server.go
  sdk/resourcemanager/kubernetesconfiguration/armprivatelinkscopes/fake/privatelinkresources_server.go
  sdk/resourcemanager/kubernetesconfiguration/armprivatelinkscopes/fake/server.go
  sdk/resourcemanager/kubernetesconfiguration/armprivatelinkscopes/fake/server_factory.go
  sdk/resourcemanager/kubernetesconfiguration/armprivatelinkscopes/go.mod
  sdk/resourcemanager/kubernetesconfiguration/armprivatelinkscopes/go.sum
  sdk/resourcemanager/kubernetesconfiguration/armprivatelinkscopes/models.go
  sdk/resourcemanager/kubernetesconfiguration/armprivatelinkscopes/models_serde.go
  sdk/resourcemanager/kubernetesconfiguration/armprivatelinkscopes/options.go
  sdk/resourcemanager/kubernetesconfiguration/armprivatelinkscopes/privateendpointconnections_client.go
  sdk/resourcemanager/kubernetesconfiguration/armprivatelinkscopes/privateendpointconnections_client_example_test.go
  sdk/resourcemanager/kubernetesconfiguration/armprivatelinkscopes/privatelinkresources_client.go
  sdk/resourcemanager/kubernetesconfiguration/armprivatelinkscopes/privatelinkresources_client_example_test.go
  sdk/resourcemanager/kubernetesconfiguration/armprivatelinkscopes/responses.go
  sdk/resourcemanager/kubernetesconfiguration/armprivatelinkscopes/time_rfc3339.go
Labels: Mgmt

#24806 [Release] sdk/resourcemanager/containerservice/armcontainerservice/7.1.0
  sdk/resourcemanager/containerservice/armcontainerservice/CHANGELOG.md
  sdk/resourcemanager/containerservice/armcontainerservice/agentpools_client.go
  sdk/resourcemanager/containerservice/armcontainerservice/agentpools_client_example_test.go
  sdk/resourcemanager/containerservice/armcontainerservice/assets.json
  sdk/resourcemanager/containerservice/armcontainerservice/autorest.md
  sdk/resourcemanager/containerservice/armcontainerservice/constants.go
  sdk/resourcemanager/containerservice/armcontainerservice/machines_client.go
  sdk/resourcemanager/containerservice/armcontainerservice/machines_client_example_test.go
  sdk/resourcemanager/containerservice/armcontainerservice/maintenanceconfigurations_client.go
  sdk/resourcemanager/containerservice/armcontainerservice/maintenanceconfigurations_client_example_test.go
  sdk/resourcemanager/containerservice/armcontainerservice/managedclusters_client.go
  sdk/resourcemanager/containerservice/armcontainerservice/managedclusters_client_example_test.go
  sdk/resourcemanager/containerservice/armcontainerservice/models.go
  sdk/resourcemanager/containerservice/armcontainerservice/models_serde.go
  sdk/resourcemanager/containerservice/armcontainerservice/operations_client.go
  sdk/resourcemanager/containerservice/armcontainerservice/operations_client_example_test.go
  sdk/resourcemanager/containerservice/armcontainerservice/privateendpointconnections_client.go
  sdk/resourcemanager/containerservice/armcontainerservice/privateendpointconnections_client_example_test.go
  sdk/resourcemanager/containerservice/armcontainerservice/privatelinkresources_client.go
  sdk/resourcemanager/containerservice/armcontainerservice/privatelinkresources_client_example_test.go
  sdk/resourcemanager/containerservice/armcontainerservice/resolveprivatelinkserviceid_client.go
  sdk/resourcemanager/containerservice/armcontainerservice/resolveprivatelinkserviceid_client_example_test.go
  sdk/resourcemanager/containerservice/armcontainerservice/snapshots_client.go
  sdk/resourcemanager/containerservice/armcontainerservice/snapshots_client_example_test.go
  sdk/resourcemanager/containerservice/armcontainerservice/trustedaccessrolebindings_client.go
  sdk/resourcemanager/containerservice/armcontainerservice/trustedaccessrolebindings_client_example_test.go
  sdk/resourcemanager/containerservice/armcontainerservice/trustedaccessroles_client.go
  sdk/resourcemanager/containerservice/armcontainerservice/trustedaccessroles_client_example_test.go
Labels: Mgmt

#24811 [Storage][Azdatalake][BugFix] Fix panic on auth failure
  sdk/storage/azdatalake/CHANGELOG.md
  sdk/storage/azdatalake/directory/client.go
  sdk/storage/azdatalake/directory/client_test.go
  sdk/storage/azdatalake/file/client.go
  sdk/storage/azdatalake/file/client_test.go
Labels: Storage

#24817 Populate Request.values on creation
  sdk/azcore/CHANGELOG.md
  sdk/azcore/internal/exported/request.go
  sdk/azcore/runtime/policy_retry_test.go
Labels: Azure.Core

#24813 [Storage][Azfile] Fixed create File Api on passing permissionKey
  sdk/storage/azfile/CHANGELOG.md
  sdk/storage/azfile/assets.json
  sdk/storage/azfile/file/client_test.go
  sdk/storage/azfile/file/models.go
Labels: Storage

#24822 Sync eng/common directory with azure-sdk-tools for PR 10949
  eng/common/pipelines/templates/jobs/npm-publish.yml
  eng/common/pipelines/templates/steps/create-authenticated-npmrc.yml
  eng/common/scripts/copy-docs-to-blobstorage.ps1
Labels: EngSys, Central-EngSys

#24823 Address CodeQL findings
  CodeQL.yml
  sdk/azidentity/cache/cache.go
Labels: Azure.Identity

#24820 Update pool to azsdk-pool and linux image to ubuntu 24
  eng/pipelines/templates/jobs/archetype-go-release.yml
  eng/pipelines/templates/jobs/archetype-sdk-client-samples.yml
  eng/pipelines/templates/variables/image.yml
Labels: Central-EngSys

#24824 Test persistent cache separation
  sdk/azidentity/cache/cache_test.go
Labels: Azure.Identity

#24826 Sync eng/common directory with azure-sdk-tools for PR 10953
  eng/common/pipelines/codeowners-linter.yml
  eng/common/pipelines/templates/jobs/archetype-sdk-tests-generate.yml
  eng/common/pipelines/templates/jobs/docindex.yml
  eng/common/pipelines/templates/stages/archetype-sdk-tool-pwsh.yml
Labels: EngSys, Central-EngSys

#24825 Remove linux next image/pool
  eng/pipelines/mgmt-auto-release.yml
  eng/pipelines/templates/variables/image.yml
  sdk/azidentity/ci.yml
  sdk/azidentity/managed-identity-matrix.json
Labels: Central-EngSys

#24751 [azsystemevents] Prepping for release
  sdk/messaging/eventgrid/azsystemevents/CHANGELOG.md
  sdk/messaging/eventgrid/azsystemevents/constants.go
  sdk/messaging/eventgrid/azsystemevents/internal/generate/generate.go
  sdk/messaging/eventgrid/azsystemevents/internal/version.go
  sdk/messaging/eventgrid/azsystemevents/models.go
  sdk/messaging/eventgrid/azsystemevents/models_serde.go
  sdk/messaging/eventgrid/azsystemevents/system_events2_test.go
  sdk/messaging/eventgrid/azsystemevents/system_events4_test.go
  sdk/messaging/eventgrid/azsystemevents/testdata/_metadata.json
  sdk/messaging/eventgrid/azsystemevents/tsp-location.yaml
Labels: Event Grid

#24836 [azsystemevents] Updating constant names based on new typespec, and documenting deleted type
  sdk/messaging/eventgrid/azsystemevents/CHANGELOG.md
  sdk/messaging/eventgrid/azsystemevents/constants.go
  sdk/messaging/eventgrid/azsystemevents/system_events2_test.go
  sdk/messaging/eventgrid/azsystemevents/system_events4_test.go
  sdk/messaging/eventgrid/azsystemevents/tsp-location.yaml
Labels: Event Grid

#24759 [Release] sdk/resourcemanager/resources/armresources/3.0.0
  sdk/resourcemanager/resources/armresources/CHANGELOG.md
  sdk/resourcemanager/resources/armresources/README.md
  sdk/resourcemanager/resources/armresources/assets.json
  sdk/resourcemanager/resources/armresources/autorest.md
  sdk/resourcemanager/resources/armresources/client.go
  sdk/resourcemanager/resources/armresources/client_factory.go
  sdk/resourcemanager/resources/armresources/constants.go
  sdk/resourcemanager/resources/armresources/deploymentoperations_client.go
  sdk/resourcemanager/resources/armresources/deployments_client.go
  sdk/resourcemanager/resources/armresources/deployments_client_example_test.go
  sdk/resourcemanager/resources/armresources/deployments_client_live_test.go
  sdk/resourcemanager/resources/armresources/fake/deploymentoperations_server.go
  sdk/resourcemanager/resources/armresources/fake/deployments_server.go
  sdk/resourcemanager/resources/armresources/fake/operations_server.go
  sdk/resourcemanager/resources/armresources/fake/providerresourcetypes_server.go
  sdk/resourcemanager/resources/armresources/fake/providers_server.go
  sdk/resourcemanager/resources/armresources/fake/resourcegroups_server.go
  sdk/resourcemanager/resources/armresources/fake/server.go
  sdk/resourcemanager/resources/armresources/fake/server_factory.go
  sdk/resourcemanager/resources/armresources/fake/tags_server.go
  sdk/resourcemanager/resources/armresources/go.mod
  sdk/resourcemanager/resources/armresources/go.sum
  sdk/resourcemanager/resources/armresources/models.go
  sdk/resourcemanager/resources/armresources/models_serde.go
  sdk/resourcemanager/resources/armresources/operations_client.go
  sdk/resourcemanager/resources/armresources/options.go
  sdk/resourcemanager/resources/armresources/providerresourcetypes_client.go
  sdk/resourcemanager/resources/armresources/providerresourcetypes_client_example_test.go
  sdk/resourcemanager/resources/armresources/providers_client.go
  sdk/resourcemanager/resources/armresources/providers_client_example_test.go
  sdk/resourcemanager/resources/armresources/resourcegroups_client.go
  sdk/resourcemanager/resources/armresources/resourcegroups_client_example_test.go
  sdk/resourcemanager/resources/armresources/resourcegroups_client_live_test.go
  sdk/resourcemanager/resources/armresources/resources_client_live_test.go
  sdk/resourcemanager/resources/armresources/responses.go
  sdk/resourcemanager/resources/armresources/tags_client.go
  sdk/resourcemanager/resources/armresources/tags_client_example_test.go
  sdk/resourcemanager/resources/armresources/tags_client_live_test.go
Labels: Mgmt

#24815 [Storage][azqueue] Deprecate existing QueueProperties.ApproximateMessagesCount and convert int32 to int64
  sdk/storage/azqueue/CHANGELOG.md
  sdk/storage/azqueue/internal/generated/autorest.md
  sdk/storage/azqueue/internal/generated/zz_queue_client.go
  sdk/storage/azqueue/internal/generated/zz_response_types.go
  sdk/storage/azqueue/queue_client_test.go
Labels: Storage

#24833 cosmos: enable support for creating containers with vector and full-text policies
  sdk/data/azcosmos/CHANGELOG.md
  sdk/data/azcosmos/cosmos_container_properties.go
  sdk/data/azcosmos/cosmos_container_properties_test.go
  sdk/data/azcosmos/emulator_cosmos_container_test.go
  sdk/data/azcosmos/full_text_policy.go
  sdk/data/azcosmos/indexing_policy.go
  sdk/data/azcosmos/vector_embedding_policy.go
Labels: Cosmos

#24844 Update pool for sdl stage
  eng/pipelines/templates/stages/1es-redirect.yml
Labels: Central-EngSys

#24843 cosmos: Cherry-Pick Vector/FT container policies to 1.5.0 branch
  sdk/data/azcosmos/CHANGELOG.md
  sdk/data/azcosmos/cosmos_container_properties.go
  sdk/data/azcosmos/cosmos_container_properties_test.go
  sdk/data/azcosmos/emulator_cosmos_container_test.go
  sdk/data/azcosmos/full_text_policy.go
  sdk/data/azcosmos/indexing_policy.go
  sdk/data/azcosmos/vector_embedding_policy.go
Labels: Cosmos

#24845 Sync eng/common directory with azure-sdk-tools for PR 10987
  eng/common/mcp/azure-sdk-mcp.ps1
Labels: EngSys, Central-EngSys

#24852 [azsystemevents] Update with latest commit and prep for release.
  sdk/messaging/eventgrid/azsystemevents/CHANGELOG.md
  sdk/messaging/eventgrid/azsystemevents/tsp-location.yaml
Labels: Event Grid

#24856 Sync eng/common directory with azure-sdk-tools for PR 10964
  eng/common/TestResources/deploy-test-resources.yml
Labels: EngSys, Central-EngSys

#24857 Fix go release pipeline (properly this time)
  eng/pipelines/templates/jobs/archetype-go-release.yml
  sdk/template/aztemplate/CHANGELOG.md
  sdk/template/aztemplate/version.go
Labels: EngSys

#24720 [Release] sdk/resourcemanager/cloudhealth/armcloudhealth/0.1.0
  sdk/resourcemanager/cloudhealth/armcloudhealth/CHANGELOG.md
  sdk/resourcemanager/cloudhealth/armcloudhealth/LICENSE.txt
  sdk/resourcemanager/cloudhealth/armcloudhealth/README.md
  sdk/resourcemanager/cloudhealth/armcloudhealth/authenticationsettings_client.go
  sdk/resourcemanager/cloudhealth/armcloudhealth/authenticationsettings_client_example_test.go
  sdk/resourcemanager/cloudhealth/armcloudhealth/ci.yml
  sdk/resourcemanager/cloudhealth/armcloudhealth/client_factory.go
  sdk/resourcemanager/cloudhealth/armcloudhealth/constants.go
  sdk/resourcemanager/cloudhealth/armcloudhealth/discoveryrules_client.go
  sdk/resourcemanager/cloudhealth/armcloudhealth/discoveryrules_client_example_test.go
  sdk/resourcemanager/cloudhealth/armcloudhealth/entities_client.go
  sdk/resourcemanager/cloudhealth/armcloudhealth/entities_client_example_test.go
  sdk/resourcemanager/cloudhealth/armcloudhealth/fake/authenticationsettings_server.go
  sdk/resourcemanager/cloudhealth/armcloudhealth/fake/discoveryrules_server.go
  sdk/resourcemanager/cloudhealth/armcloudhealth/fake/entities_server.go
  sdk/resourcemanager/cloudhealth/armcloudhealth/fake/healthmodels_server.go
  sdk/resourcemanager/cloudhealth/armcloudhealth/fake/internal.go
  sdk/resourcemanager/cloudhealth/armcloudhealth/fake/operations_server.go
  sdk/resourcemanager/cloudhealth/armcloudhealth/fake/relationships_server.go
  sdk/resourcemanager/cloudhealth/armcloudhealth/fake/server_factory.go
  sdk/resourcemanager/cloudhealth/armcloudhealth/fake/signaldefinitions_server.go
  sdk/resourcemanager/cloudhealth/armcloudhealth/go.mod
  sdk/resourcemanager/cloudhealth/armcloudhealth/go.sum
  sdk/resourcemanager/cloudhealth/armcloudhealth/healthmodels_client.go
  sdk/resourcemanager/cloudhealth/armcloudhealth/healthmodels_client_example_test.go
  sdk/resourcemanager/cloudhealth/armcloudhealth/interfaces.go
  sdk/resourcemanager/cloudhealth/armcloudhealth/models.go
  sdk/resourcemanager/cloudhealth/armcloudhealth/models_serde.go
  sdk/resourcemanager/cloudhealth/armcloudhealth/operations_client.go
  sdk/resourcemanager/cloudhealth/armcloudhealth/operations_client_example_test.go
  sdk/resourcemanager/cloudhealth/armcloudhealth/options.go
  sdk/resourcemanager/cloudhealth/armcloudhealth/polymorphic_helpers.go
  sdk/resourcemanager/cloudhealth/armcloudhealth/relationships_client.go
  sdk/resourcemanager/cloudhealth/armcloudhealth/relationships_client_example_test.go
  sdk/resourcemanager/cloudhealth/armcloudhealth/responses.go
  sdk/resourcemanager/cloudhealth/armcloudhealth/signaldefinitions_client.go
  sdk/resourcemanager/cloudhealth/armcloudhealth/signaldefinitions_client_example_test.go
  sdk/resourcemanager/cloudhealth/armcloudhealth/testdata/_metadata.json
  sdk/resourcemanager/cloudhealth/armcloudhealth/time_rfc3339.go
  sdk/resourcemanager/cloudhealth/armcloudhealth/tsp-location.yaml
Labels: Mgmt
